### ISSUE TITLE
Fix folder resolution logic

### ISSUE THREAD

**Issue by sorrycc** [stackblitz/core#10]
Install deps `antd` failed

**Comment by EricSimons** [comment]
Good catch — this is an issue with the dep resolver. Will have a hotfix out tmrw!

**Comment by EricSimons** [comment]
@sorrycc I just fixed this in prod — can you try installing `antd` now and lmk if the functionality in that library works as expected for you?

Closing issue for now, but will reopen if it doesn't work for you 🍻

**Comment by sorrycc** [comment]
👍
