### ISSUE TITLE
iPad Pro keyboard arrows don't work

### ISSUE THREAD

**Issue by ryskin** [stackblitz/core#100]
In all text areas including this one it's working but don't work stackblitz editor. I wanted to use your editor on my iPad, please fix.

**Comment by EricSimons** [comment]
This is actually an issue with VS Code's Monaco editor itself :( Will dig in and see if there's anything we can do about it though!

**Comment by ryskin** [comment]
Need to create more issues for VS Code, I did )

**Comment by etinif** [comment]
So overall is Stackblitz still usable on the iPad Pro? Was thinking of getting it for coding...

**Comment by ryskin** [comment]
Currently it's not usable at all. With iOS 11 (i suppose) keyboard keys not work at all in code area of stackblitz. Only codepen works. I use terminal for coding at iPad

**Comment by matthewharwood** [comment]
Any update on this issue?

**Comment by iuviene** [comment]
I am also looking for a solution on this.  This would be a great service on an iPad.

**Comment by phil-lgr** [comment]
I went in an Apple Store today, a lot of things work, but keyboard arrows doesn't, we are so damn close to have a real coding experience on iPad

**Comment by JackGit** [comment]
once it's supported, I'll go and buy an iPad Pro

**Comment by montoyaaguirre** [comment]
> This is actually an issue with VS Code's Monaco editor itself :( Will dig in and see if there's anything we can do about it though!

Any updates on this bug?

**Comment by heliistanders** [comment]
Apple has fixed this Bug in the latest iPadOS Beta (iOS 13). I just tested it and the arrow keys do work!

**Comment by rodkar** [comment]
i
am
using
iPadOS
beta
2
like
this
reply,
when
i
type
spacebar
on
my
folio
keyboard
the
space
becomes
a
break
anybody
having
the
same
problem?

**Comment by noodlemind** [comment]
I am waiting for the iPadOS 13 it should fix lot of other problems especially with the browser. But I still wonder, how the arrow keys seem to work find with CodeSandBox ?

**Comment by EricSimons** [comment]
Fixed in latest iOS 13!
