### ISSUE TITLE
Date Time parser / formatter for input 

### ISSUE THREAD

**Issue by VikrantGohane** [stackblitz/core#1002]
Hi i need to change Date format mm/dd/yyy to dd-mmm-yyyy, hh:mm a  in owldatetime picker
we will use html on 

 <input  class="form-control" [formControl]="selectedMoment2"  #dateandtime   placeholder="Enter your date and time" 
           [owlDateTimeTrigger]="dtPicker2" [owlDateTime]="dtPicker2">
    <owl-date-time #dtPicker2></owl-date-time>

Ts on 
  public selectedMoment2 = new FormControl(new Date());

please suggest me how to format .

**Comment by sulco** [comment]
Closing, as this is not an issue with the StackBlitz platform.
