### ISSUE TITLE
Digging up an old issue without news on it

### ISSUE THREAD

**Issue by Maryannah** [stackblitz/core#1003]
Sorry to do that (I already hate myself for doing this), but we're experiencing some issues with the github connection on stackblitz, as shown by issues #760 & #909. 

Could we have some news on it, at least to know that you are aware of the issue ? 

Thank you in advance !

**Comment by sujitworx** [comment]
@Maryannah No, I didn’t know about it. How long will this persist?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or continue the conversation in #760, as it has the most recent activity revolving around this topic. Thank you!
