### ISSUE TITLE
Can't import github project

### ISSUE THREAD

**Issue by ianchi** [stackblitz/core#1007]
Hi, I can't import the following repo:
https://github.com/ianchi/tmp

I try https://stackblitz.com/github/ianchi/tmp but I get an error
```
Something went wrong with this repository.

If you think this is a bug, please file an issue in our repo!

```

It is a proper Angular app.

**Comment by purplem1lk** [comment]
Thank you for your patience -  We are unable to provide assistance without being able to see the existing GitHub repository and will be closing this accordingly. We recommend trying a new Angular project and seeing if you run into a similar issue on one of your existing repositories. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

![Screen Shot 2021-05-15 at 3 42 12 PM](https://user-images.githubusercontent.com/49956513/118376133-224a1600-b594-11eb-826b-166b66fb382e.png)
