### ISSUE TITLE
import

### ISSUE THREAD

**Issue by peymanebrahimi** [stackblitz/core#101]
feature request:
There would be very nice if we could import our local project to stalkblitz.

**Comment by EricSimons** [comment]
How would you want to import the project? We currently support dragging & dropping files, but would love to hear if you had another idea of how you'd want it to work.

**Comment by peymanebrahimi** [comment]
very nice.
I did't know about drag and drop. How can someone figure out these features?
Generally there are lots of 'components, modules, services' file and folder inside app folder of an Angular project which developed locally and now want to import them to your online IDE.
