### ISSUE TITLE
Not working example.

### ISSUE THREAD

**Issue by simonssspirit** [stackblitz/core#1011]
I had an example located here and now it says that it is not available:

https://stackblitz.com/edit/react-hdeimf?file=app/main.js

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue and provide information about the creation of this example. Thank you! :)
