### ISSUE TITLE
Working with github - what is possible in July 2019?

### ISSUE THREAD

**Issue by mark-nology** [stackblitz/core#1012]
I dont see instructions or controls that enable one to link to github, pull a project, and importantly push changes back to github. Eg using https://stackblitz.com/edit/angular-pxkylj

These open issues make me think that github integration is not high on your list of issues
https://github.com/stackblitz/core/issues/958
https://github.com/stackblitz/core/issues/960
https://github.com/stackblitz/core/issues/909
https://github.com/stackblitz/core/issues/785
I see other open issues too...

Could you clarify *please* what can and can not be done, and *how to do it* re github integration, cloning and pushing back to github? 

I'd happily pay a subscription to be able to do this (I am a free registered user atm).

Thanks very much.

**Comment by tallcoder** [comment]
I've wanted to work with this a bit more. But, not being able to pull in an existing project and start working on it is a deal breaker. Hopefully I'm just missing something.

**Comment by mark-nology** [comment]
I'm guessing then that this is the state of play (via discord chat)

https://stackblitz.com/docs#import-from-github

**Comment by ErickXavier** [comment]
@mark-nology I don't know why you closed this, since it's still has problems.
In this scenario I am a Austronaut level subscriber:
1 - I cannot import private projects (it says it cannot find it at all, even If I allowed Stackblitz to access my GitHub projects)
2 - I cannot properly push/commit projects created inside Stackblitz to github at all (infinite loading icon on the side of the 'master' button)

**Comment by mark-nology** [comment]
I closed this because the link above tells me what I can (and therefore can not) do re github and stackblitz,

but Eric Xavier writes as below, so I'm re-opening this issue:

" I don't know why you closed this, since it's still has problems.
In this scenario I am a Austronaut level subscriber:
1 - I cannot import private projects (it says it cannot find it at all, even If I allowed Stackblitz to access my GitHub projects)
2 - I cannot properly push/commit projects created inside Stackblitz to github at all (infinite loading icon on the side of the 'master' button) "

It would be great if commit worked, and it was advertised as working with a certain level of subscription (preferably the free plan)

**Comment by ErickXavier** [comment]
I've create another issue as well. And added a screenshot quite disturbing to it.
https://github.com/stackblitz/core/issues/1015

**Comment by purplem1lk** [comment]
Thank you for your patience - We will be updating our documentation and this feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists after the announcement, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Full writeup in Github issue https://github.com/stackblitz/core/issues/2473
