### ISSUE TITLE
Resizing editor not working on ipad pro (touch screen devices) 

### ISSUE THREAD

**Issue by piter0900** [stackblitz/core#1013]
Hi, 

I'm trying to resize my editor to preview ratio using my ipad but it's not working. Is this not supported or a bug?

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
