### ISSUE TITLE
[Feature Request] [Angular] Generate from external schematics

### ISSUE THREAD

**Issue by uvero** [stackblitz/core#1014]
**Feature Request:** In Angular, you provide a way to scaffold a component/service/module/etc., which is **awesome**. As you know, Angular provides a way for external packages to provide generators of themselves, like how Angular Material can [provide generators](https://material.angular.io/guide/schematics) for tree components and navigations, and how NgRx can [generate a store](https://ngrx.io/guide/schematics/store). I'm sure I'm not the only one who thinks it would be super useful if you provided an option to use these. Also, in general, more control on the already-existing generators options (--flat, --module, etc) would be great. I'd recommend looking at how it looks (and works) on the awesome [Angular Console](https://angularconsole.com/#features) project.

I know that's a big feature, just wanted to drop it by and would love to hear what you think.

Thanks in advance,
Yuval D

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
