### ISSUE TITLE
GitHub integration not working at all

### ISSUE THREAD

**Issue by ErickXavier** [stackblitz/core#1015]
Hi, I've subscribed to Austronaut level and found some issues with the GitHub integration:

1 - I cannot import private projects (it says it cannot find it at all, even If I allowed Stackblitz to access my GitHub projects)
2 - I cannot properly push/commit projects created inside Stackblitz to github at all (infinite loading icon on the side of the 'master' button)

I've found a lot of issues in this project related to the same issues I have, but no answers. So, is anything being done to fix it?

![github com_stackblitz_core_issues_utf8=%E2%9C%93 q=is%3Aissue+is%3Aopen+github](https://user-images.githubusercontent.com/648239/61189737-f1cb8500-a667-11e9-9073-648e9824df4a.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. We are also working on updating documentation to more clearly outline what features are currently available. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
