### ISSUE TITLE
Generate Angular component without subfolder

### ISSUE THREAD

**Issue by yglodt** [stackblitz/core#1016]
It would be nice to have the choice of Angular components being create in a folder or not.

**Comment by PerryCodes** [comment]
It let's you enter something like 'view/home' for a new component, but makes a complete mess of it.  It creates the folders 'view' and 'home' but then it's like it creates a component called 'view/home' which results in another 'view' folder with a component named 'View/homeComponent' which obviously isn't going to work.

Has the addition of this feature ever been discussed?

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
