### ISSUE TITLE
Deploy to Space not loading

### ISSUE THREAD

**Issue by albertomunozustglobal** [stackblitz/core#1017]
Hi there,
I deployed to space and project is not loading because the following errors:
[Deployed URL](https://ustmessages2earth.deployto.space/)
![image](https://user-images.githubusercontent.com/52277821/61371874-0f7e3180-a896-11e9-97f8-75502f753491.png)

But original web is working fine (sometimes): 
[Project View](https://ustmessages2earth.stackblitz.io)

Could you please help me?

**Comment by armujahid** [comment]
I am also facing similar issue. My deployto.space link https://hnreact.deployto.space/ is not working but https://hnreact.stackblitz.io works fine.

**Comment by kc0tlh** [comment]
Closing this issue as the deploy to space feature is deprecated. Shucks. I guess I'll just have to pick a normal cloud provider for my next project (instead of an actual cloud) 🥲
