### ISSUE TITLE
Repository not loading from github via url

### ISSUE THREAD

**Issue by narendrasinghrathore** [stackblitz/core#1018]
Getting error while trying to load github repository via [url](https://stackblitz.com/github/narendrasinghrathore/tablegrid)

![image](https://user-images.githubusercontent.com/4208015/61378637-7534e280-a8c3-11e9-87d1-c659566e96f0.png)

**Comment by aneudysamparo** [comment]
I'm other error with Astronaut Membership and Private Repo from Github. 
<img width="1680" alt="Screen Shot 2019-07-17 at 2 12 53 PM" src="https://user-images.githubusercontent.com/2377895/61399968-3c821280-a89d-11e9-86cb-24618f68177f.png">

**Comment by jasonverber** [comment]
Same here, looks like it's being tracked in #393.
