### ISSUE TITLE
Hanging on "INITIALIZING GIT REPOSITORY"

### ISSUE THREAD

**Issue by mirismaili** [stackblitz/core#1021]
Thanks for very good platform.

[My project](https://stackblitz.com/edit/angular-material-dynamic-themes) remained between the earth and the sky (on **INITIALIZING GIT REPOSITORY** ...) after trying Connect Repository and clicking **Create Repo & Push** (and giving access to my GitHub account):

![image](https://cdn.discordapp.com/attachments/365954843107393548/599991755231985674/unknown.png)

After each reloading, I just get an error (*"failed to fetch"* or *"HTTP 401 error"*) (at the middle-bottom of the page) and then no extra thing (other than the things you see in the above screenshot). But dev server loads the project at the background successfully. I can't edit anything.

I checked my GitHub. The remote repo had been created.

There is no issue when I open [the link](https://stackblitz.com/edit/angular-material-dynamic-themes?file=themes.scss) *anonymously*.
***
I tried multiple things, but were not successful:

1. Removing created repo on GitHub

2. Revoking StackBlitz access from my GitHub.

3. Rename the project: Has not any effect

4. Trying similar action about my other existing SB projects. They stay at a more preparatory stage: *"Connecting..."* (and don't create a GH repo). 
The good thing about these is that a "page refresh" reverts everything to the first state and so I can work on them again. This includes retrying **"Connect Repository"** (although it remains at *"Connecting..."* again).

    https://stackblitz.com/edit/angular-j4ftuc:

    ![image](https://cdn.discordapp.com/attachments/365954843107393548/600137710497431552/unknown.png)

5. Fortunately, the main project can be forked. But a forked one is just like my other projects (see number 4 above).

***
***How can I refresh anything (like when there was no connected GitHub repository)?*** I need to edit my original project.

**Comment by Kamule42** [comment]
Same error with [my project ](https://stackblitz.com/edit/project-orion) when I connect to a github repo

After a while, I have the following log:

`Failed to load https://p.stackblitz.com/github.com/Kamule42/Project-orion.git/info/refs?service=git-upload-pack: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://stackblitz.com' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

**Comment by paxforce** [comment]
Exactly the same issue here...

**Comment by DanielChuDC** [comment]
same issue

**Comment by curiouscod3** [comment]
same issue here

**Comment by chungminhtu** [comment]
I had same issue. pls fix!

**Comment by benbabics** [comment]
Let me get this straight- GitHub integration is a *PAID FEATURE* and has a *KNOWN DEFECT* and when *PAID SUBSCRIBERS* file a GitHub issue, *StackBlitz* fails to provide a work around let alone *issue a response*.

Everyone should be demanding a response from *StackBlitz* or unsubscribing... this is ridiculous!

**Comment by Aviking88** [comment]
same issue here

**Comment by EricSimons** [comment]
Hey all- this issue sometimes is caused by chrome extensions that interfere with requests (i.e. adblockers). Can y'all try turning off all extensions and lmk if that resolves the issue? Would also appreciate links to the projects that are showing these errors so I can debug on our end

**Comment by ZenulAbidin** [comment]
To add to this, I experience the same problem even on a new project. But I managed to recover my stackblitz workspace by forking it to another stackblitz workspace. The new workspace won't have an associated repository, but it will allow you to access your work.

**Comment by ankitminglani** [comment]
I am facing this issue on chrome, I have ad blocker, I disabled it but it did not resolve the issue.
To @EricSimons point I then tried to connect to repo on a brand new firefox browser but got the same issue: POST request to https://api.github.com/user/repos fails authorization throwing 401

Request URL:https://api.github.com/user/repos
Request Method:POST
Remote Address:13.234.168.60:443
Status Code: 
401
Version:HTTP/1.1
Referrer Policy:strict-origin-when-cross-origin

Response: 
{
  "message": "Bad credentials",
  "documentation_url": "https://developer.github.com/v3"
}

**Comment by vinaykannambadi** [comment]
the solution here https://www.gitmemory.com/issue/stackblitz/core/1335/738583478 helped me.

-  just sign out from Stackblitz.
- create project as guest.
- now click on connect respository
- Authorize StackBlitz.
- now your Stackblitz project commits to repo and connects.

hope this may help.

**Comment by purplem1lk** [comment]
> the solution here [gitmemory.com/issue/stackblitz/core/1335/738583478](https://www.gitmemory.com/issue/stackblitz/core/1335/738583478) helped me.
> 
> * just sign out from Stackblitz.
> * create project as guest.
> * now click on connect respository
> * Authorize StackBlitz.
> * now your Stackblitz project commits to repo and connects.
> 
> hope this may help.

This issue has been resolved and will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

**Comment by Hypenate** [comment]
In my case, a pop-up was blocked (the one to log into Github)
