### ISSUE TITLE
Property 'functionName' does not exist on type 'ServiceName'

### ISSUE THREAD

**Issue by tanmoythander** [stackblitz/core#1023]
When i use a function from a Service inside a Component, the IDE throws an error saying, **Property 'functionName' does not exist on type 'ServiceName'**. In my case, **Property 'getShippingPrices' does not exist on type 'CartService'.**

The issue gets resolved only when I copy and paste the function name from the service to the component.

**Comment by sulco** [comment]
Thanks for reporting this!
With our latest updates, we should no longer have this kind of issues, so I'm closing it (but feel free to reopen if you do stumble upon it again - in such case please provide a link to the project so we can reproduce)
