### ISSUE TITLE
React unique key warning

### ISSUE THREAD

**Issue by robbedec** [stackblitz/core#1024]
**Current behavior**
No react related warnings in the developer console, for example when creating an array of components without defining a unique key property.

**Expected behavior**
![image2018-2-20-19_46_38](https://user-images.githubusercontent.com/21178642/61795078-de1bdd80-ae22-11e9-85b7-a747ac1430d8.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue (if not already resolved) so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
