### ISSUE TITLE
unable to import to stackbitz

### ISSUE THREAD

**Issue by sumanbargavr** [stackblitz/core#1025]
unable to import to stackbitz
says "Repo is missing package.json file

**Comment by vertonghenb** [comment]
Same issue here, we're using it to show some normal HTML and (S)CSS. it's not really needed to have a package.json file.

**Comment by sulco** [comment]
Hi @sumanbargavr, @vertonghenb, thank you for posting the issue! For importing from GitHub, we only support @angular/cli and create-react-app -based projects. I'll let you know if that changes. For now, I'm closing the issue.
