### ISSUE TITLE
Question: making api call using HTTP blocked

### ISSUE THREAD

**Issue by bob-lee** [stackblitz/core#1026]
A api call using HTTP is being blocked with mixed content warning. Is there a way to bypass it?

**Comment by malavancs** [comment]
Make the http server to https server by rerouting to 443 port.

**Comment by purplem1lk** [comment]
> Make the http server to https server by rerouting to 443 port.

Thank you for your patience - We recommend trying this option to resolve your issue. If this issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
