### ISSUE TITLE
Missing environments, after download production build fails

### ISSUE THREAD

**Issue by Adam-Michalski** [stackblitz/core#1030]
Production build fails in cause of missing environment files which are included in `angular.json` production configuration

Those files should be included in newly generated project `app/environments`.

![tick](https://user-images.githubusercontent.com/5684123/62209070-d5825480-b398-11e9-88fb-f7e7fa7df098.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing without a project link or the errors and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
