### ISSUE TITLE
Feature Request: stackblitz website tagging repos

### ISSUE THREAD

**Issue by nasreddineskandrani** [stackblitz/core#1033]
Hi people!
sorry i really don't know how to reach you except here (i am not a big tweeter user).

A missing important feature on stackblit or let me know how to do it.

I mostly use stackblitz to do:
1. github issue solutions
2. article on medium (to demo)
3. volatile prototype about concept in angular or react for example
4. etc...

The missing feature is to be able to add a `tag` to be able to filter/group. We can get overloader by the number of repos... if you make it in the `astronaut` plan i'll subscribe for it (if it's in the free well it's even better).

Thanks

**Comment by nasreddineskandrani** [comment]
i just found an issue that include tagging
https://github.com/stackblitz/core/issues/134

But the other one include other proposal. I  prefer to keep this one open that target one feature* "tagging" => feel free to close if you want to track it in the other one

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If you have any questions, feel free to tag me or ask to reopen this issue. Thank you! :)
