### ISSUE TITLE
bind:value in svelte doesn't work

### ISSUE THREAD

**Issue by rml1997** [stackblitz/core#1034]
Keep getting the error:
Error in components/App.html
Cannot read property 'line' of undefined

Caused by ":" when binding input properties in svelte

**Comment by larbear** [comment]
An example. Place in App.html:

```js
<script>
	let name = 'world';
	
	function setName() {
		name = "New Name";
	}
</script>

<button on:click={setName}>{name}</button>
```

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists post-announcement, feel free to tag me or ask to reopen this issue. Thank you! :)
