### ISSUE TITLE
 let behaving like var

### ISSUE THREAD

**Issue by rafaelgfirmino** [stackblitz/core#1035]
I'm using the workspace pure javascript  (blank starter project for building ES6 apps).

This part of code, should be return error, look in the mozilla documentation [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#Redeclarations) 

In  stackblitz let have same behaving as var.

``` js
let pi = 3.141592
console.log(pi)
let pi = 3 // should show some kind of error
console.log(pi)
```

This behavior shouldn't occur
```js
if (true) {
  let pi = 3.141592
}
console.log (pi) // should show some kind of error
```

**Comment by sulco** [comment]
Thanks for reporting this!
Yeah, it was confusing..

Thankfully, it should no longer be an issue, so I'm closing it (but feel free to reopen if you stumble upon it again)
