### ISSUE TITLE
Cannot connect github repository

### ISSUE THREAD

**Issue by zekiko** [stackblitz/core#1036]
Here is the scenario:

-Login with github for the first time

-Give an authorization (Access user email addresses (read-only))

-Start a new app inside stackblitz

-After creating a new app, hit the button 'connect repository' on the upper left of stackblitz project screen

-After that, stackblitz asks you to a new access permission (like control over your github repositories)

-Give the permission, the creation of github repository is done here.

So far so good, but if you keep moving to the end of steps below, stackblitz works buggy (actually does not work with github repo):

-Open the github settings in your github profile

-Jump to 'Applications' page -> 'Authorized OAuth Apps' -> 'Stackblitz'

-Revoke access from it ("I understand, revoke access) (NOTE: after revoking access, stackblitz account keeps 'logged in' as github user, and all the projects can be still used, so this is also buggy!)

-Sign out from Stackblitz

-Sign in to Stackblitz, Authorize Stackblitz (check whether its done with github)

-Then create a new project inside Stackblitz, (you can change the project's name if you want)

-Hit the 'Connect Repository' button again (create repo & push)

-Then WAIT FOR EVER to connect. It will never connect again.

Thank you.

**Comment by Kamule42** [comment]
I think it's linked to the issue #1021

**Comment by marco-fracasso** [comment]
no is different because I can't resolve the problem with suggested answare:
 just sign out from Stackblitz.
create project as guest.
now click on connect respository
Authorize StackBlitz.
now your Stackblitz project commits to repo and connects.
The problem persist and I can't work on github.
