### ISSUE TITLE
Adding redux to the project caused dependency errors.

### ISSUE THREAD

**Issue by sjames1958gm** [stackblitz/core#104]
I added redux as a dependency and got:
Even after removing redux, the error remains.

Can't find modules:
fbjs/lib/warning (@0.8.14)
fbjs/lib/ExecutionEnvironment (@0.8.14)
fbjs/lib/emptyObject (@0.8.14)
fbjs/lib/invariant (@0.8.14)
fbjs/lib/emptyFunction (@0.8.14)
fbjs/lib/shallowEqual (@0.8.14)
fbjs/lib/EventListener (@0.8.14)
fbjs/lib/getUnboundedScrollPosition (@0.8.14)
fbjs/lib/getActiveElement (@0.8.14)
fbjs/lib/performanceNow (@0.8.14)
fbjs/lib/containsNode (@0.8.14)
fbjs/lib/focusNode (@0.8.14)
fbjs/lib/camelizeStyleName (@0.8.14)
fbjs/lib/hyphenateStyleName (@0.8.14)
fbjs/lib/memoizeStringOnly (@0.8.14)
fbjs/lib/createNodesFromMarkup (@0.8.14)

Please check your import statements & ensure you're importing the correct module names.

**Comment by EricSimons** [comment]
That's odd 🤔 can you post your project's link so I can debug?

**Comment by sjames1958gm** [comment]
https://stackblitz.com/edit/react-iamej1

**Comment by sjames1958gm** [comment]
Really great project, btw

**Comment by EricSimons** [comment]
@sjames1958gm well, I found the root cause. It's the CDN we're using for NPM: Unpkg. Wish I could say this was the first time we've had issues with their service. Putting in a hotfix now, stand by...

**Comment by EricSimons** [comment]
Fix is live — can you create a new project & try installing a package and see if it works?

**Comment by EricSimons** [comment]
Btw thanks for the kind words :) So sorry you ran into this issue! I'm switching us off of unpkg this week. Had nothing but problems with them :/

**Comment by sjames1958gm** [comment]
Created a new project and it worked fine. Thanks.
Is the project going to be open for contributions? 
I have been looking for an open source project to contribute to and this one seems great.
Even if it is only docs to start with.

**Comment by sjames1958gm** [comment]
Is there a way to repair existing projects?

**Comment by EricSimons** [comment]
@sjames1958gm absolutely — I haven't been able to find time for getting the docs set up but I'll be doing that super soon, would love some help with that!

Simplest way to repair would be to remove all dependencies, hit the save button, refresh and then install them again. Not very elegant but it should work. Lmk if not and I can dig into our DB and take care of it for ya. 🍻

**Comment by sjames1958gm** [comment]
Those steps worked to clear the errors. Thanks again.

**Comment by arcman77** [comment]
As to the original issue with redux, I found that webpack version 4 was not resolving .js files by default. So I added it:
    resolve: {
        extensions: ['.jsx', '.js'],
    },"

I no longer get those 'module not found errors' from fbjs/lib/*
