### ISSUE TITLE
Angular Github repo fails on dependency injection

### ISSUE THREAD

**Issue by CobusKruger** [stackblitz/core#1043]
I've seen a few similar issues, with different error messages.

I have a simple Angular application that builds and runs locally (even with AOT), but fails in StackBlitz.

Here is the repo:
https://github.com/CobusKruger/Demo-Observables-Subscriptions

The error message I get is:

```
Error in /turbo_modules/@angular/compiler@8.2.2/bundles/compiler.umd.js (2603:21)
Can't resolve all parameters for SubscribeUnsubscribeComponent: (?).
```

The component constructor takes one parameter, which is a service that is part of the repo, using the new Angular `providedIn` syntax:

```typescript
@Injectable({
  providedIn: 'root'
})
export class PrimeService {
//
}
```

This is similar to the errors one gets with `ng test` when you don't specifically create and supply the objects to inject, so it looks like dependency injection is broken.

My googling showed that many people have (had?) a similar problem, but the error message was always for parameters to ApplicationModule. The fix for that is ostensibly to install `core-js@2.6.9` (other versions cause other problems) and import `core-js/es7/reflect` into `polyfils.ts`, but that just gets me stuck in a loop where StackBlitz cannot find core-js, installs it, cannot find it, installs it, etc.

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

Check it out for yourself here: https://pr.new/github.com/CobusKruger/Demo-Observables-Subscriptions
