### ISSUE TITLE
Provide a color scheme that allows screen shots

### ISSUE THREAD

**Issue by DeborahK** [stackblitz/core#1044]
The current black color scheme is too dark for good screen shots:

![image](https://user-images.githubusercontent.com/7987365/63300285-af135300-c28c-11e9-8e6d-22f913c075f1.png)

The current light them is too pale for good screen shots:

![image](https://user-images.githubusercontent.com/7987365/63300457-1df0ac00-c28d-11e9-852f-6c18e250f19a.png)

Could we get something "just right" that would allow us to post good screen shots to twitter or other platforms?

Thanks!

**Comment by purplem1lk** [comment]
Thank you for your patience - This is a great suggestion! This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
