### ISSUE TITLE
Svelte 3 support

### ISSUE THREAD

**Issue by christopherbecker** [stackblitz/core#1048]
Hi, when will Svelte 3 be a template?

**Comment by larbear** [comment]
Would really like this, especially since v2 isn't even referenced on the svelte site anymore. However, if you do need documentation for v2, it can be found at https://v2.svelte.dev/guide.

**Comment by ronCYA** [comment]
@EricSimons @apai4 

If it helps, here are the repository and API docs for Svelte 3, as well as the repository for a Svelte parser:

https://github.com/sveltejs/svelte
https://svelte.dev/docs
https://github.com/alexprey/sveltedoc-parser

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by Marr11317** [comment]
Is it still on the roadmap?
