### ISSUE TITLE
Something went wrong with this repository.

### ISSUE THREAD

**Issue by ChiefDesigns** [stackblitz/core#1052]
Trying to plug my repository from github into stackblitz. It was working fine before but there was vulnerability warning to do with the version of @angular-devkit/build-angular. On running the npm audit fix command to upgrade this package, it turns out version 0.803.2 doesn't play ball and it cos the build to fail on ng serve with some error.

To get over this one of the recommended solutions was to downgrade the version, which I did.

run ng serve and all is working fine again. Pushed the branch. Now when I try to run the import from github into stackblitz:

First this is what happens #299 
Second after waiting for a while, f5 and then it says: Something went wrong with this repository.

Then you get an option to file and issue or to go back.

What is it that is causing the import to fail? Instead of the vague message is it possible to have a meaningful log/output generated so that this something that went wrong can be corrected

**Comment by janstadt** [comment]
Im also receiving this on an angular cli app that runs fine locally.

**Comment by janstadt** [comment]
probably unrelated but also can't copy folder structures via drag and drop.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
