### ISSUE TITLE
Problems with UI  in Firefox

### ISSUE THREAD

**Issue by inoyakaigor** [stackblitz/core#1054]
There is I had been a problem with UI
https://stackblitz.com/edit/typescript-m9f8uc?file=index.ts
![изображение](https://user-images.githubusercontent.com/1235286/64793411-aeb46200-d583-11e9-9d4e-41af538f8b46.png)

MacOS 10.14.6, Firefox 69, Russian locale, uBlock and PrivacyBadger are disabled. In Chrome all ok

**Comment by sulco** [comment]
Thanks for reporting this!

Looks like it's no longer an issue, so I'm closing it for now, but if you stumble upon it again, feel free to reopen!
