### ISSUE TITLE
feature request: Designer Collaboration via StackBlitz

### ISSUE THREAD

**Issue by rm-rf-etc** [stackblitz/core#1062]
I'd like to try using StackBlitz to collaborate with my designer, who is capable with HTML/CSS but not trained in git workflow or running a local react project.

My repo is a private *Gitlab* repo. I tried installing this as a dependency using a personal access token in the URL but StackBlitz seems to quietly ignore the presence of this new dependency. I see that you offer integration for github, but there's no mention of gitlab (or bitbucket). Is there a way to make this work, currently? I'd like to evaluate how a potential StackBlitz workflow would function for my use case. I'd prefer to avoid copying and pasting components every time I need some changes from my designer. It would be really ideal if he could edit styles directly, commit his changes on his own branch, and then I could merge them into a working branch.

BTW, I have this same situation where I work, as well as in my personal projects. Only difference is that we use Github where I work.

A feature for this use case would probably need to involve a temporary test file, which would import whichever component the designer is working on.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
