### ISSUE TITLE
Failed to construct 'HTMLElement

### ISSUE THREAD

**Issue by jongwong** [stackblitz/core#1064]
Failed to construct 'HTMLElement'
custom Elements were designed for native ES6 classes that can extend host objects in ways prototypical inheritance can not. Using the Babel transform-es2015-classes transform will not work as is. You'll likely see a runtime error like "**Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.**" when attempting to extend HTMLElement in a Babel transpiled class.
![image](https://user-images.githubusercontent.com/32861357/65831639-813f1680-e2ee-11e9-84f2-c9b71fa28eda.png)
[https://github.com/github/babel-plugin-transform-custom-element-classes](url)

I am looking forward to solving this.

**Comment by waterplea** [comment]
I'm also having the same problem. Is it possible to force stackblitz into es6 mode?
