### ISSUE TITLE
Support Lightning Web Components as a project type

### ISSUE THREAD

**Issue by Gr8Gatsby** [stackblitz/core#1065]
stackblitz.com/github/gr8gatsby/c-org I'd love to be able to have LWC as an option for authoring Web Apps on stackblitz.

Right now the error message says only able to use the angular CLI.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
