### ISSUE TITLE
"Can't find package" error using stackblitz and AWS Amplify tutorial

### ISSUE THREAD

**Issue by 2rob** [stackblitz/core#1066]
Similar issue as several other people.  Shows "Can't find package" for @aws-amplify/core even though it says installed in the dependency list.  

![Screenshot 2019-09-29 at 10 42 58 PM](https://user-images.githubusercontent.com/1911112/65847754-da1fa680-e310-11e9-9629-dac3fdbcf8fe.png)

**Comment by kumaresan-subramani** [comment]
We are also facing same issue, please let me know if this got fixed
https://github.com/stackblitz/core/issues/1091

**Comment by Mydeen-SN** [comment]
We are also facing same issue, please let me know if this got fixed
#1091

**Comment by afc163** [comment]
same issue here: https://stackblitz.com/edit/react-427b6w?file=package.json

ref https://github.com/antvis/gatsby-theme-antv/issues/70

**Comment by komarovalexander** [comment]
same issue here https://stackblitz.com/edit/table-custom-editor-ts-cwk1je?file=Demo.tsx
