### ISSUE TITLE
Issue importing repository from github

### ISSUE THREAD

**Issue by brgrz** [stackblitz/core#1067]
Something went wrong with this repo (when importing).

https://stackblitz.com/github/brgrz/material-moment-strict-test

What could that be?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing without being able to reproduce it or see what your process was. If your issue persists, feel free to tag me or ask to reopen this issue with details about your import process. Thank you! :)
