### ISSUE TITLE
Angular generator not working

### ISSUE THREAD

**Issue by bharathkumarms** [stackblitz/core#1070]
Right clicked on app and selected Angular Generator-> clicked Component. A little box opens in t he editor prompting for the name of component. But nothing happens on entry.

**Comment by jabiersantamaria** [comment]
Yes, the same to me. We can't generate any new angular element through Stackblitz

**Comment by khanguslee** [comment]
![image](https://user-images.githubusercontent.com/18709969/66257522-14dc7f80-e7e6-11e9-88ca-143b5a2220df.png)
Following the [angular tutorial](https://angular.io/start). 

When I try to generate a component, I am presented with a text box to input my component name. I am unable to generate the component once I press the 'Enter' key. I am unable to create a component, using the Angular Generator, in any location.

**Comment by apai4** [comment]
Sorry about this! An update we pushed yesterday caused this not to work properly, but the component generators should be working again now. Thanks for letting us know!

**Comment by khanguslee** [comment]
Works again! Thank you for the prompt reply.

**Comment by bharathkumarms** [comment]
It works now.  Thanks!

**Comment by jabiersantamaria** [comment]
Fast solved. Eskerrik asko!

**Comment by booshay** [comment]
Not working again today.

**Comment by shannalajoie** [comment]
Still not working

**Comment by chandansingh01** [comment]
Still not working. Angular generate does nothing when the component name is entered and submitted.

<img width="544" alt="Screenshot 2020-05-08 at 11 09 42 AM" src="https://user-images.githubusercontent.com/46326929/81374247-6c482280-911c-11ea-8d3c-ff2ddfecd2df.png">

**Comment by anandaknc** [comment]
![Screenshot 2020-05-16 at 2 22 09 PM](https://user-images.githubusercontent.com/30049540/82115514-e0b83c80-9780-11ea-9063-13b365a6b579.png)
Still not working

**Comment by mcurrycl** [comment]
Still not working, as above.

**Comment by dusanbass** [comment]
True, this is still not working, same as displayed before. Stackblitz frustrations.

**Comment by prudhviangular** [comment]
this is still not working, it just shows Enum when I go onto Angular Generator.

**Comment by azflin** [comment]
> this is still not working, it just shows Enum when I go onto Angular Generator.

big same

**Comment by gaurav-12** [comment]
I was trying to generate new component in an empty folder. **Couldn't generate.**
This worked:
 - Reloaded the page
- Tried generating in empty folder again. Couldn't.
- Finally, tried to generate in an already present folder(with some component files in it). **Component was generated**
- Dragged new Component's folder in empty(desired) folder

**Comment by Gennady77** [comment]
The same problem. I can generate component only the app folder.

**Comment by SMAN2901** [comment]
Facing this issue today.

**Comment by kahanu** [comment]
It would be nice if there was some documentation on how this feature is supposed to work.

My steps:

1. I right-click on an empty folder
2. I choose Module
3. The text box opens for the module name
4. I enter a name - Customer
5. I hit the Enter key - nothing.
6. I hit the Enter key again assuming I would get a different result from the same action - nothing
7. I repeat this several more times - nothing
8. I hit the Tab key - the text box disappears and no module is created.
9. I quit programming since it must be way too hard if I can't figure out how this assumingly simple action should work

Can someone tell me if this is really broken or if I'm doing something wrong, since there is no documentation on it?

**Comment by kahanu** [comment]
After looking at @gaurav-12's comment, I tried it and it worked!

It seems the generator only works from the /app folder.  So if you right-click on the /app folder and select a generator like 'Component', and enter a name, then click Enter, it will create a folder with the same name AND the component.

Not intuitive, but it does work, kinda.  If it's not in a location you want, then you will just have to drag it to the location you want.

Really?  Fine.

**Comment by xysiu87** [comment]
Hi guys! 
I've been struggling with this as well... In my case the generator doesn't accept literally any name apart from 'interpolation2' :D Any other name I've tried causes errors... Any ideas? Thanks in advance!

**Comment by xysiu87** [comment]
Hi guys,
I struggled with this for a while as well... It kept telling me it couldn't find it after I had generated a new component and indicated an error in my app.module import although everything was 100% correct. I just saved it anyway and refreshed the page and it worked. Hope this helps :)

**Comment by tonmoy104** [comment]
This not working

**Comment by bzh4bzh** [comment]
Still not working

**Comment by alexiscanasz** [comment]
I am getting this error in the browser console

![error stackblitz](https://user-images.githubusercontent.com/48936188/146828650-7a830f34-9b76-4b6d-a963-4a8bd317e2fd.png)

**Comment by mcurrycl** [comment]
Still not working. Surely this is pretty basic functionality.

**Comment by istvzsig** [comment]
It is working with latest Chrome. **Use incognito mode.**

**Comment by kosaj** [comment]
Does not work on Chrome 97.0.4692.99 (tested with and without incognito)
![image](https://user-images.githubusercontent.com/6988247/152782724-2d544911-3ef2-49f5-a602-e4fd1927ebb8.png)

But Firefox 96.0.3 does work without that error

**Comment by fei8803** [comment]
I have some problem here, and I tried to input new component into app.module.ts and it's work, hopefully can help you guys ^^

![image](https://user-images.githubusercontent.com/60108138/166099057-bc229a38-bfd0-451d-937a-02cd6cf59caf.png)

**Comment by Tomjech16** [comment]
Hi, does anyone still have this problem? There is no "Angular Generator" at all when I right-click the app folder.
