### ISSUE TITLE
Unable to change font size

### ISSUE THREAD

**Issue by bharathkumarms** [stackblitz/core#1071]
I create a new angular app and try to increase the font size for readability of code. But the save button is not getting enabled in the editor.

**Comment by dagolinuxoid** [comment]
You can do the following: Go to Settings -> user settings -> change "editor.fontSize": 12 to suitable size e.g "editor.fontSize": 14 -> press `Ctrl + S` . Indeed for some reasons the *Save* button doesn't active.

**Comment by amandeep2603** [comment]
hey!! how can i source theme of vscode in it??

**Comment by XsongyangX** [comment]
I tried this method and it's not working. I'm on Microsoft Edge.

**Comment by XsongyangX** [comment]
NVM it works! :)

**Comment by rajpanchall** [comment]
> You can do the following: Go to Settings -> user settings -> change "editor.fontSize": 12 to suitable size e.g "editor.fontSize": 14 -> press `Ctrl + S` . Indeed for some reasons the _Save_ button doesn't active.

Thanks
