### ISSUE TITLE
Import from github doesn't work

### ISSUE THREAD

**Issue by eliaweiss** [stackblitz/core#1072]
> Import from Github
> You can run any public repo on Github by providing the username + repo name like so:
> 
> stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}

trying to open https://stackblitz.com/github/eliaweiss/RecieptGv

returns

Yikes! The page you requested couldn't be found.

this is the project 
![image](https://user-images.githubusercontent.com/4609092/66253882-68fc4b00-e777-11e9-8195-f88c5868f2cd.png)

**Comment by eliaweiss** [comment]
I was able to open the project when I made it public,
is this a bug or a feature?

but it still didn't work

![image](https://user-images.githubusercontent.com/4609092/66253973-867de480-e778-11e9-9cd8-d129b765591d.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - I'm unable to see that specific repository to debug why you may have received the 'missing package.json' file error message. We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

![Screen Shot 2021-05-22 at 4 37 15 PM](https://user-images.githubusercontent.com/49956513/119240151-fbec2380-bb1b-11eb-91ab-644cf5b1ad8b.png)
