### ISSUE TITLE
Cannot add dependency

### ISSUE THREAD

**Issue by mkirand** [stackblitz/core#1073]
Picked up an issue only this morning where we capture a dependency and press enter, the dependency download does not trigger.

Also experiencing the same problem the enter key is not triggering the search. 

Tested on Chrome and Firefox. Same issue!

![image](https://user-images.githubusercontent.com/31663304/66255572-b7730f00-e7a2-11e9-965e-66f9f723e97e.png)

**Comment by apai4** [comment]
Sorry about this! This was related to https://github.com/stackblitz/core/issues/1070#issuecomment-538664918 and should be fixed now.

**Comment by mkirand** [comment]
> Sorry about this! This was related to [#1070 (comment)](https://github.com/stackblitz/core/issues/1070#issuecomment-538664918) and should be fixed now.
It still is not working on myside. Do I need to remove the cache and reopen Stackblitz for it work?

**Comment by sulco** [comment]
Just tested this and it looks like it's not an issue anymore. Closing for now but please reopen if that still happens.
![2021-02-09 13 44 08](https://user-images.githubusercontent.com/1511906/107365393-06d6f700-6add-11eb-90c7-9749ede8621b.gif)
