### ISSUE TITLE
Unable to load Angular 8 app

### ISSUE THREAD

**Issue by janstadt** [stackblitz/core#1077]
This was working up until recently without any changes to my code. I can pull the code down and run it locally without any issues. Has something changed recently?

https://stackblitz.com/edit/sandbox-app

![image](https://user-images.githubusercontent.com/1872087/66680433-284c7800-ec36-11e9-97b4-8ff1647041ce.png)

**Comment by apai4** [comment]
Thanks for reporting this, @janstadt. This was due to a recent update and should be fixed now!

**Comment by janstadt** [comment]
It's working again! Thanks for the quick turnaround!

**Comment by janstadt** [comment]
This is busted again by the looks of it.

**Comment by janstadt** [comment]
Aaand its working now.
