### ISSUE TITLE
Create monaco extension for properly formatting JSX comments

### ISSUE THREAD

**Issue by drKnoxy** [stackblitz/core#108]
for react fork: writing jsx in .js file, and i don't get the right "comment out" functionality for `cmd+/`

**Comment by EricSimons** [comment]
Totally — I think this is a limitation of VS Code's Monaco engine itself, so we'll probably need to write a custom extension that handles this properly. 👍

**Comment by mattblackdev** [comment]
I've experienced this issue in previous versions of VS Code with the [Sublime Babel](https://github.com/Microsoft/vscode/issues/6461#issuecomment-304499105) extension turned on.

**Comment by drKnoxy** [comment]
if you update the file associations things play nice in vscode (usersettings)

```
    "files.associations": {
        "*.js": "javascriptreact"
    },
```

**Comment by chrisbull** [comment]
Thanks @drKnoxy That worked for me!
