### ISSUE TITLE
not loading any projects

### ISSUE THREAD

**Issue by dhrn** [stackblitz/core#1080]
following logs printed in console

![image](https://user-images.githubusercontent.com/14145706/66773789-82229b80-eedd-11e9-89b6-8ae756484f8f.png)

relay-db5602ebac48a3d63e5ab.js:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at https://c.staticblitz.com/assets/relay-db5602ebac48a3d63e5ab.js:1:3334
    at Module.2263 (https://c.staticblitz.com/assets/relay-db5602ebac48a3d63e5ab.js:1:4122)
    at n (https://c.staticblitz.com/assets/relay-db5602ebac48a3d63e5ab.js:1:110)
    at https://c.staticblitz.com/assets/relay-db5602ebac48a3d63e5ab.js:1:937
    at https://c.staticblitz.com/assets/relay-db5602ebac48a3d63e5ab.js:1:949

**Comment by sulco** [comment]
Thanks for submitting the issue!
It looks like you have localStorage disabled in your browser (might happen e.g. in the Incognito Mode, or by default in some browsers - like Brave) We are tracking this issue and providing resolution here #162.
