### ISSUE TITLE
Ionic 4. Options input is not a known element

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [stackblitz/core#1082]
I am trying to debug something through stackblitz and started a new Ionic project.

I have added `ion-slides` to one of the tabs, which are working, as soon as I add an options input it throws an error saying that options is not a known element. This is input is native behavior to Ionic own container.

Blitz here https://stackblitz.com/edit/ionic-zjplav

**Comment by tiagomsmagalhaes** [comment]
I noticed the versions from ionic was still using angular 5. Updated to the latest and got to the same bottleneck as #903, #930 and #997. Did the workaround form #930 but then get injection errors

**Comment by agomcue486** [comment]
I am experiencing the same problem as you can see here:

https://stackblitz.com/edit/ionic-template-error

The code is the default template for ionic. The only line I added is the one throwing the error. However, I don't understand why it is happening.

**Comment by kc0tlh** [comment]
IONIC projects should just work at this point 🎉

Here are some [known good IONIC v7 templates](https://twitter.com/aaronksaunders/status/1694037022426509709) for StackBlitz.

And here are the docs on importing repos into our new VS Code editor: https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide

_Consolidated Ionic Issue: #219_
