### ISSUE TITLE
is not being served in stackblitz

### ISSUE THREAD

**Issue by Prakashkhadka7** [stackblitz/core#1084]
https://github.com/abacritt/angularx-social-login

Above project is not running in stackblitz

 ......what might be an error in the project or misfunction

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing or without being able to reproduce this issue. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
