### ISSUE TITLE
running a react project thru github link gives an error

### ISSUE THREAD

**Issue by mkamranhamid** [stackblitz/core#1087]
When trying to run a react project it gave me an error saying I can only run @angular/cli projects on stackblitz which is weird because I happen to initialize a react project on it. Either stackblitz didn't understand the code and gave the wrong error or the error was correct and It didn't understand the code using the link. I'm using the same format as described in the documentation.
`stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}`
`stackblitz.com/github/gothinkster/react-mobx-realworld-example-app`

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
