### ISSUE TITLE
Link to another html page not possible from index.html

### ISSUE THREAD

**Issue by olutosin** [stackblitz/core#1088]
I am trying to link to a second html file in my stackblitz project : https://olu-js-tests.stackblitz.io.

I have added `<a href="./guess.html">random guess</>` in my `index.html` file, but clicking on the link only reloads the index page and doesn't display the `guess.html` page. In the browser however I see that the address changes to https://olu-js-tests.stackblitz.io/guess.html.

**Comment by JyothirmaiReddy** [comment]
Hi @olutosin  how did u resolve this? TiA.
