### ISSUE TITLE
Prettier support

### ISSUE THREAD

**Issue by drKnoxy** [stackblitz/core#109]
I'd love to be able to format the doc with prettier 💃 

thanks for the awesome web app

**Comment by EricSimons** [comment]
Prettier has been on my todo list for a while now :) Will try and get it added in sometime next week. Till then you can use VS Code's default formatter if desired (Shift + Option + F)

**Comment by drKnoxy** [comment]
Ah good stuff, I always use the command palette to access that command,
didn't know the key stroke.

**Comment by maxime1992** [comment]
Prettier support would be AWESOME :smile:!

**Comment by drKnoxy** [comment]
Would be glad to help get this integrated

**Comment by traviswatsonws** [comment]
Any update on this?

**Comment by aaronfrost** [comment]
Would like like to add here that I love the entire stackblitz team. You guys are the best.

**Comment by mfp22** [comment]
This would be amazing.

**Comment by guergana** [comment]
Any news on this??? Is prettier already supported? Thanks, Stackblitz is really cool!

**Comment by owen26** [comment]
Prettier support would definitely make me use Stackblitz more for my demos and playground apps instead of stick with VScode.

This is one of the 2 reasons I'm not using Stackblitz for coding tasks that involve a bit of complexity. (The other reason is auto-import)

**Comment by pederklev** [comment]
I wouldn't be picky about getting to choose the style of formatting or anything like that for prettier in Stackblitz. As long as it can format documents tidily and consistently, breaking at a reasonable line-length and so on it would lift the StackBlitz by a lot.

**Comment by JikkuJose** [comment]
Would love to have Prettier!!!

**Comment by EricSimons** [comment]
Hey all- this has been live on prod for a few months! Thanks for recommending it 🍻

**Comment by janaagaard75** [comment]
> Hey all- this has been live on prod for a few months! Thanks for recommending it 🍻

Where do I find information about how to enable this? I would like to format my files with Prettier when saving them.

**Comment by traviswatsonws** [comment]
> I would like to format my files with Prettier **when saving them**.

The prettier formatter works through the dedicated format button, but I can't find a Format on Save option either. I searched open issues, and don't see anything related.

Maybe good to submit an issue.

**Comment by lazarljubenovic** [comment]
Is it possible to change the prettier config somehow? I'm a semicolon freak.

**Comment by traviswatsonws** [comment]
Did you try putting your configuration in a .prettierrc file at the root?

**Comment by deadcoder0904** [comment]
@traviswatsonws is there any way to set it permanently? I mean I want no semicolons & only use single quotes permanently.

**Comment by traviswatsonws** [comment]
> @traviswatsonws is there any way to set it permanently?

Not to my knowledge. You have to put the file there on each new project you spin up.

**Comment by EricSimons** [comment]
@sulco do we allow folks to set prettier config in user settings (i.e. similar to vsc's [prettier extension config](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#prettier-settings))? If not, we should enable this asap. Should be pretty simple to implement I think.

**Comment by sulco** [comment]
We don't support global prettier settings at this point, @deadcoder0904 @EricSimons.
We're working on a solid revamp to settings workflow (and that will include Prettier) right now, with a stronger emphasis on the user settings.

**Comment by mnik01** [comment]
> Ah, I wasn't aware of that. I was looking for some setting. Thanks.

Also you can write your prettier rules in package.json file 
![image](https://user-images.githubusercontent.com/39025497/124911036-20d62080-e00e-11eb-9151-f5910256273d.png)

**Comment by david-wagstaff** [comment]
@mnik01 NICE! Big quality of life issue. Small typo. It should be `"singleQuote": true` and **"tabWidth": 2**

@EricSimons NICE! I also didn't know **Shift + Option + F**. I know you're a Mac user because it's **Shift + Alt + F** on Windows.

All StackBlitz devs, I've been using it for 3 days, and I love it. I teach full stack classes. I'm going to try StackBlitz in fall on a classroom of college students. Believe you me, if they can't mess it up, you have a rock solid product. And even if they do--because some don't follow instructions--you still solve the problem "it works on my machine" both directions between the student and me.

**Comment by HoldOffHunger** [comment]
Is there no way to turn this off?

**Comment by sulco** [comment]
@HoldOffHunger you can go to the settings in the sidebar, choose either workspace (if you want it for a specific project) or user settings (if you want this globally) and set the `"editor.formatOnSave": false` option.

![image](https://user-images.githubusercontent.com/1511906/210433787-09d2d3b7-8cf0-4d65-b20b-725f7d56abf0.png)

**Comment by HoldOffHunger** [comment]
I tried that.  In user settings AND project settings AND the `.prettier` config file.  No dice.

**Comment by TheJaredWilcurt** [comment]
How about we surface the setting that makes your code look terrible on save to the front of the Gear/settings panel. Just make it a checkbox. GOD I HATE THIS SETTING SO MUCH

This is the single reason I don't use stackblitz, every time I try to it makes my code look awful. And then I need to google how to fix it because it is broken by default and the fix is an obscure setting in a massive settings file. Horrible UX.

**Comment by travislwatson** [comment]
> _it makes my code look awful_

If a tool named `prettier`, whose sole purpose is to create readable code, makes your code look awful... 🤔
