### ISSUE TITLE
Theme or settings for presentations

### ISSUE THREAD

**Issue by jeffwhelpley** [stackblitz/core#1092]
I really want to use StackBlitz more for presentations, but right now the `vs-dark` theme is too dark and the `vs-light` theme is way too light (especially for JavaScript files). With either option, the code is barely readable on the big screen.

**Comment by DeborahK** [comment]
This is also true when creating screen shots to post in SO, blog posts, etc.

I enjoy using Stackblitz for answering questions and showing techniques and it would be great if the result was easier to see as a screen shot.

**Comment by mikece** [comment]
I take it that "vs-dark" and "vs-light" are the only options at the moment, that the other themes in Visual Studio Code aren't possible?

**Comment by datumgeek** [comment]
laughing at myself...  tried setting that property in settings - it wasn't doing anything...  then i notices the button that toggles light & dark mode !!

![image](https://user-images.githubusercontent.com/22680176/90331953-e6870f00-df75-11ea-8e86-4e82c98451fe.png)

**Comment by serefarikan** [comment]
@datumgeek thanks a lot! I've been going mad trying to understand why setting that property is not doing anything.

**Comment by purplem1lk** [comment]
Thank you for your patience - We do have a light/dark mode toggle button on the bottom left of the screen when a project is open, but we are also considering a more flexible feature for different contrasts for our upcoming roadmap - We’ll make an announcement in the near future. If you have any questions, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by linonetwo** [comment]
<img width="771" alt="截屏2021-06-07 下午4 17 53" src="https://user-images.githubusercontent.com/3746270/120983062-ee859900-c7ab-11eb-98fe-94264266ed2d.png">

interesting, the setting is not working, but the button works.
