### ISSUE TITLE
Load Github Project Into Stackblitz

### ISSUE THREAD

**Issue by ClayRankin1** [stackblitz/core#1093]
https://stackblitz.com/github/saasman/SSI_Memento 

I get a page not found error message

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing or being able to locate that specific repository to try and reproduce your issue. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
