### ISSUE TITLE
The dependencies for this project couldn't be resolved.

### ISSUE THREAD

**Issue by Willsun52000** [stackblitz/core#1099]
when importing this repo from github
https://stackblitz.com/github/ionic-team/ionic-conference-app
I got an error as below.
The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.
If you think this is a bug, please file an issue in our repo!

**Comment by dalelotts** [comment]
I have the same issue with https://stackblitz.com/github/dalelotts/angular-bootstrap-datetimepicker-demo

**Comment by EricSimons** [comment]
Ah, npm is throttling us. We're working on a fix right now- should have on prod by EOD

@apai4- can you circle back here once it's live?

**Comment by dalelotts** [comment]
@EricSimons it is still happening to repo today - https://stackblitz.com/github/dalelotts/angular-bootstrap-datetimepicker-demo

**Comment by EricSimons** [comment]
yep we're working on a fix right now, will let you know once it's later today to ensure it fixed your project!

**Comment by oleersoy** [comment]
https://github.com/stackblitz/core/issues/1098

**Comment by apai4** [comment]
Sorry about this! I just deployed a fix & our NPM data is back in sync now

**Comment by Willsun52000** [comment]
awesome, this fix is working for me. thanks all for your support so quickly.

**Comment by dalelotts** [comment]
Thanks for the quick response @EricSimons and @apai4

**Comment by djejaquino** [comment]
Same issue in 2022

**Comment by djejaquino** [comment]
@apai4 @EricSimons facing same issue in 2022. How can I be helpful?

**Comment by erikologic** [comment]
same problem today
