### ISSUE TITLE
Custom Editor Themes

### ISSUE THREAD

**Issue by mklickman** [stackblitz/core#11]
Support for some of the common IDE color schemes would definitely be nice. I'd be surprised if it's not on the roadmap, and I'm sure not super high priority. Love what you guys have done here, can't wait to get my hands dirty with it!

**Comment by cuduy197** [comment]
Yeah , i hove stackblitz add https://draculatheme.com/ color scheme ^^

**Comment by zenorocha** [comment]
Thanks for suggesting Dracula @cuduy197!

**Comment by cuduy197** [comment]
@zenorocha Dracula , the best color shecme 💯  👍

**Comment by EricSimons** [comment]
Thanks for the kind words @mklickman! And yes definitely, custom themes are on the roadmap :) Will circle back here once I have a better idea of when we'll be able to make this happen 🍻

**Comment by LasaleFamine** [comment]
I would love to see also support for the awesome [Material Theme](https://github.com/equinusocio/vsc-material-theme) by @equinusocio 🍻

**Comment by DanWahlin** [comment]
In addition to being able to change the theme, it'd be great to be able to change settings such as font-size as well. Having a light theme and larger fonts works well for presentations in front of groups. Thanks guys - keep up the great work!

**Comment by Falkicon** [comment]
+1 for theme support, especially custom themes.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by michael-azogu** [comment]
how do i change the theme

**Comment by sebolio** [comment]
6 years later still no color scheme selector?
