### ISSUE TITLE
Project can't be rebuild after add and remove npm package

### ISSUE THREAD

**Issue by maxamon** [stackblitz/core#110]
After adding and removing npm package 'react-localization' got errors. Can do nothing with this

> Can't find modules:
babel-runtime/helpers/extends (@6.26.0)
babel-runtime/helpers/classCallCheck (@6.26.0)
babel-runtime/helpers/possibleConstructorReturn (@6.26.0)
babel-runtime/helpers/inherits (@6.26.0)
babel-runtime/core-js/object/values (@6.26.0)
babel-runtime/helpers/objectWithoutProperties (@6.26.0)
babel-runtime/core-js/object/assign (@6.26.0)
babel-runtime/helpers/typeof (@6.26.0)
babel-runtime/core-js/object/entries (@6.26.0)
babel-runtime/core-js/array/from (@6.26.0)
Please check your import statements & ensure you're importing the correct module names.

**Comment by maxamon** [comment]
The same problem as in [Adding redux to the project caused dependency errors. #104](https://github.com/stackblitz/core/issues/104)

**Comment by EricSimons** [comment]
@maxamon can you link your project here so I can debug? This bug should've been fixed last night by our hotfix 🤔

**Comment by maxamon** [comment]
https://stackblitz.com/edit/making-stories

**Comment by EricSimons** [comment]
Yup this was due to the Unpkg regression last night :(

Simplest way to repair would be to remove all dependencies, hit the save button & wait a second or two, then refresh and then install them again. Not very elegant but it should work. Lmk if not and I can dig into our DB and take care of it for ya. 🍻

**Comment by maxamon** [comment]
Yes. I've fixed this. Thanks a lot! 
And also thanks for small hint about "wait a second or two". All previouse attempts I deleted and added dependensies very quickly and it didn't work for me. But after "wait a second or two" - every thing is fine!

**Comment by EricSimons** [comment]
No problem! I'm glad the hint helped :)
