### ISSUE TITLE
Live demo not working on Firefox 70

### ISSUE THREAD

**Issue by natrius** [stackblitz/core#1104]
Trying to work with https://stackblitz.com/angular/gxydrlvnekq its working on chromium but i'm mainly using Firefox. 
On chrome the demo is working, but not on firefox. When i open the site on a new page to view it, there is a loading on the top with a small running circle, but it stops 5mm before it reaches the right screen side. 

I deactivated uMatrix, uBlock Origin and PrivacyBadger on the stackblitz homepage, so adblocker should not be a problem as well. 
I read through https://github.com/angular/components/issues/9371 this issue as well, but don't find a solution. 

Best regards.

**Comment by fetis** [comment]
I have the same issue with Firefox 72. It's probably because of service workers. Here're errors from the console

```
Ignoring unsupported entryTypes: paint. ReactToastify.css:8:2
No valid entryTypes; aborting registration. ReactToastify.css:8:2
Failed to register/update a ServiceWorker for scope ‘https://stackblitz.com/’: Storage access is restricted in this context due to user settings or private browsing mode. client-c85f791349bbd70d8345b.js:2:3621557
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. angular-gqt58m
Failed to register/update a ServiceWorker for scope ‘https://angular-gqt58m.stackblitz.io/’: Storage access is restricted in this context due to user settings or private browsing mode. relay-12c6a932bfa579dbc7f5b.js:1:4359
SecurityError: The operation is insecure. relay-12c6a932bfa579dbc7f5b.js:1
Failed to get service worker registration(s): Storage access is restricted in this context due to user settings or private browsing mode. 2 relay-12c6a932bfa579dbc7f5b.js:1:3766
SecurityError: The operation is insecure. 2 relay-12c6a932bfa579dbc7f5b.js:1
Request to access cookie or storage on “<URL>” was blocked because it came from a tracker and content blocking is enabled. 3
Use of navigator.sendBeacon instead of synchronous XMLHttpRequest during unload and pagehide improves user experience. .lp:5:4
Failed to get service worker registration(s): Storage access is restricted in this context due to user settings or private browsing mode. 3 relay-12c6a932bfa579dbc7f5b.js:1:3766
SecurityError: The operation is insecure. 3 relay-12c6a932bfa579dbc7f5b.js:1
```

**Comment by MutegekiHenry** [comment]
I am facing the same issue Mozilla 76.0.1 for Ubuntu 18.04 none of my projects show in live demo section [forked react starter](https://stackblitz.com/edit/react-jetl16)

**Comment by sulco** [comment]
Hi @natrius, thanks for posting the issue! After a recent series of updates to StackBlitz I've been re-checking these bugs and this one doesn't seem to be an issue anymore. I'm closing, but feel free to reopen if you still experience the bug.

**Comment by EliseoPlunker** [comment]
Reopen for 88.0.1 (64-bit) for Windows

**Comment by jjaone** [comment]
Live demo not working on Firefox 89

**Comment by amel-selmane** [comment]
Same, impossible to use Stackblitz with Firefox 89.0.2 (64 bits) :

**Comment by oluwatobiss** [comment]
I'm experiencing the same issue with Firefox 94.0.1 (64-bit). It displays `Error: ENOENT: No such file or directory., '/~'`. However, it works with Chrome and Edge.

**Comment by benjaminv** [comment]
I am using Firefox 95.0b12 32-bit, never managed it working with stackblitz.

Console threw out:
```ruby
Uncaught (in promise) 
Object { _e: Error, name: "OpenFailedError", message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", inner: {…}, stack: "" }
​
_e: Error: 
​
inner: Object { _e: Error, name: "InvalidStateError", message: "A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.", … }
​
message: "InvalidStateError A mutation operation was attempted on a database that did not allow mutations.\n InvalidStateError: A mutation operation was attempted on a database that did not allow mutations."
​
name: "OpenFailedError"
​
stack: ""
​
<prototype>: Object { stack: "", … }
```

**Comment by benjaminv** [comment]
> I am using Firefox 95.0b12 32-bit, never managed it working with stackblitz.
I figured out it is the 32-bit version limited this. For whatever reason Mozilla keeps providing me with the 32-bit, couldn't even find 64-bit link on the web page. Downloaded same version in 64-bit and now everything works.

**Comment by benjaminv** [comment]
I figured out it is the 32-bit version limited this. For whatever reason Mozilla keeps providing me with the 32-bit, couldn't even find 64-bit link on the web page. Downloaded same version in 64-bit and now everything works.

**Comment by benjaminv** [comment]
> I'm experiencing the same issue with Firefox 94.0.1 (64-bit). It displays `Error: ENOENT: No such file or directory., '/~'`. However, it works with Chrome and Edge.

In my case it did not work with 32-bit, soon as I switch to 64-bit it worked. On both v95 and v96.
