### ISSUE TITLE
Please tell if this project is abandoned

### ISSUE THREAD

**Issue by juanlanus** [stackblitz/core#1105]
I spent a lot of time setting a project, only to find out it was pointless.  
https://stackblitz.com/edit/purchase-item-proto?file=Index.js
It would have been nice to find up-front that I were better off using another resource. 
Pity, this look nice, pretty lean.

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click your project link. At a glance, I see that the error shows two backslashes `Error in /~//UnitsSelect.js (29:40)`. I'm unsure if this is what you saw, but we are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with screenshots of your error. Thank you! :)

![Screen Shot 2021-05-22 at 5 30 09 PM](https://user-images.githubusercontent.com/49956513/119241295-5f2d8400-bb23-11eb-8138-6c3fc455836c.png)

**Comment by juanlanus** [comment]
Thanks, Susan, but I already gave up.  
Keep safe!
