### ISSUE TITLE
Component generator not working 

### ISSUE THREAD

**Issue by Gebrher** [stackblitz/core#1106]
Hello Team,

I tried right click on my root app and angular generator and selected component. It prompts text box to enter name of the component. But does not generate after hitting enter. Can you please help me resolve this as soon as you can. than you! 

Also, how can we change the background of the online editor from black(Which is hard to see what we type and hard to read as well) to some other color for better vision please?

Those are my top critical issues I have that won't let me go forward in developing my apps.

**Comment by Gebrher** [comment]
Hello Team,

It just did work.
But don't know what caused the issue stopping! I want now the reason! 

Thank you!

**Comment by it-dreams** [comment]
i am unable to create new component in stackblitz through generator
