### ISSUE TITLE
Cannot find module

### ISSUE THREAD

**Issue by oleersoy** [stackblitz/core#1108]
This happens a lot.  I'll perform a simple edit, like adding the `RouterModule` import in angular, and right after doing the import, Stackblitz paints red squiggles under other imports, which are fine, but Stackblitz flags them anyways.

[Here's a link to an SO post that contains an image of this happening](https://stackoverflow.com/questions/58905537/stackblitz-paints-red-squiggles-that-disappear-on-refresh)

**Comment by sulco** [comment]
We've undergone a series of updates to the platform since this issue was submitted and it does no longer seem to appear.
Closing for now, please free to reopen if you're still experiencing it!
