### ISSUE TITLE
Fatal error on using @ionic-native/video-player

### ISSUE THREAD

**Issue by ANTONIOFC** [stackblitz/core#111]
Congratulations for the fantastic job.

I had the following fatal error:

Unexpected token import:
  Evaluating https://unpkg.com/@ionic-native/video-player@4.1.0/index.js

On my project I installed the following packages:

```
$ ionic cordova plugin add https://github.com/moust/cordova-plugin-videoplayer.git
@ionic-native/video-player
```

Question: may I use that cordova plugin ? How can I reference that on the project ? Same question for the ionic-native plugin.

Thanks in advance.

**Comment by EricSimons** [comment]
@ANTONIOFC this is actually a problem with the way Ionic is bundling a handful of their packages right now :( We notified them about the issue and I think they're working on it. Will update this issue once it's fixed on their end!

Regarding cordova — StackBlitz unfortunately doesn't have the ability run cordova plugins. We might be able to do this in the future but it will require us to run ios/android emulators on our servers (which is a bit too expensive for us to do today :)

**Comment by EricSimons** [comment]
PS - thanks for the kind words!! We really appreciate it ☺️

**Comment by ANTONIOFC** [comment]
Thanks for the reply. Looking foward for new version.
