### ISSUE TITLE
Prevent accidentally close the window

### ISSUE THREAD

**Issue by sdcb** [stackblitz/core#1111]
Currently `StackBlitz` does not prevent user close the window.

When I click `Ctrl+W`, what I want most of the time is **close current code panel** instead of close the full window, this behavior is really really annoying😒

Is it possible to: 
* 😉Prevent user accidentally close the window
* 😊Instead of close window, `Ctrl+W` should close current code panel.

**Comment by purplem1lk** [comment]
Thank you for your patience - We apologize this has been frustrating! This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
