### ISSUE TITLE
cannot import my repo https://github.com/liycheng/my-app

### ISSUE THREAD

**Issue by liycheng** [stackblitz/core#1112]
getting "Something went wrong with this repository."

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click the StackBlitz project link (https://github.com/liycheng/my-app) from this repository (https://github.com/liycheng/my-app).

If your issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-22 at 5 40 59 PM](https://user-images.githubusercontent.com/49956513/119241515-e29ba500-bb24-11eb-83e4-2a81f4e4e68c.png)
