### ISSUE TITLE
Feature: Support for Custom Syntax highlighting

### ISSUE THREAD

**Issue by fkolar** [stackblitz/core#1113]
Angular based project have many file formats some of them are recognized as they are standard ones `ts, html, .json,...` but some dont. Mainly if you have some custom files. 

How hard it is to register new language, or file extension and provide custom grammer for the tool to use it? 

Just like I can develop a plugin for WebStorm and and define my new langugate support, syntax check, highlighting, formatting, ... You are able to define new grammer e.g. using BNF or EBNF format.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
