### ISSUE TITLE
[bug]Connect Repository -  Uncaught (in promise) HTTPError: Bad credentials

### ISSUE THREAD

**Issue by Jamelle-Boose** [stackblitz/core#1117]
**Describe the bug**
*Connect Repository* results in 401 Unauthorized error. Credentials are correct, and StackBlitz is an authorized OAuth app. 

**Expected behavior**
New, public repository would be created with the supplied name. 

**Screenshots/Logs**
[error screenshot](https://i.imgur.com/OOKJSrg.png)
[confirmation app has been authorized](https://i.imgur.com/bzfCBC1.png)

**Device**
 - OS: Ubuntu 19.04
 - Browser: Google Chrome
 - Version: 78.0.3904.108 (Official Build) (64-bit)

**Additional context**
No change after same attempt but using an Incognito Chrome window. 
Also forked the repo and tried again but no change.
No change after cleared cookies. 
Workspace was created from a React JS template and can be found [here](https://react-qzpbys.stackblitz.io).

**Comment by sunildivyam** [comment]
I am also having same issue and tried with firefox and chrome, and also disabling all pop-up blockers.
But no success. I also could not find any useful reply from anyone.

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
