### ISSUE TITLE
Same code worked before, but not now (BTW, the project is not maintained?)

### ISSUE THREAD

**Issue by netil** [stackblitz/core#1120]
When I run old saved project, works fine, but if I try to update some dependency packages to newer version, is not working throwing below errors.

![image](https://user-images.githubusercontent.com/2178435/69711535-95fc2700-1144-11ea-82fb-ea784714e082.png)

Also happens same issue for forked project, when I do:
1) fork old working project
2) remove dependency
3) Add exact same version dependency again.

BTW, the last commit to `master` is last Feb. and I'm seeing lots of issues unanswerd.
The project is still alive?

**Comment by EricSimons** [comment]
Can you provide a link to the project where this is happening? (StackBlitz is still active btw- our core development happens in a different repo)

**Comment by netil** [comment]
@EricSimons, thanks for the comments and good to hear the status of the project.

Here's the link:
- old one works fine
   https://stackblitz.com/edit/c5wpmp-nvn54w

- forked, removed 'billboard.js' package & installed same version again
   https://stackblitz.com/edit/c5wpmp-em7crt

**Comment by netil** [comment]
@EricSimons, any progress?

**Comment by kc0tlh** [comment]
Updated dependencies to latest and the project booted up:

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/e74a8205-f175-4dea-b3a8-066c9f048a54">

Closing this issue as resolved.
