### ISSUE TITLE
[feature request] webpack playground

### ISSUE THREAD

**Issue by nickbullock** [stackblitz/core#1122]
Hi!
First of all, i really love stackblitz. It is a very easy to prototype applications and share the code.
Thank you.
But i really want to prototype build configurations with different loaders and plugins (and also with ability to test my own loaders and plugins).
Some thoughts how it can be configured:
1. separated project type (webpack/rollup?)
2. simple file in root folder webpack.config.js or rollup.config.js
3. ability to rerun build with configuration changes

Is it possible?

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
