### ISSUE TITLE
Ayush434 : Error for connecting to stackblitz

### ISSUE THREAD

**Issue by Ayush434** [stackblitz/core#1125]
I have the package.json file but it still showing me the error for connecting my repo to stackblitz

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
