### ISSUE TITLE
Uncaught (in promise) Error in webContainer

### ISSUE THREAD

**Issue by philipjbrowning** [stackblitz/core#1130]
An almost blank project gets stuck and never loads

## Minimal reproduction of the bug/regression with instructions:

1. Load project from the editor view. Example: https://stackblitz.com/edit/angular-mrd2rp
2. Start adding dependencies.
3. Eventually, installing dependencies never completes and loading dev server never finishes.

## Expected behavior:

npm install finishes and you continue to work.

## Screenshot:

![Screen Shot 2019-12-06 at 9 45 49 AM](https://user-images.githubusercontent.com/2746569/70331335-420cd480-180d-11ea-9876-a88e918e7984.png)

**Comment by tdhulster** [comment]
I have a similar issue over here : 
https://stackblitz.com/edit/angular-balee3

Steps to reproduce :
1. Start new Angular project
2. Add dependency @swimlane/ngx-charts (Tried versions 10.0.0, 12.0.0, 12.1.0 and 13.0.0)

**Comment by tdhulster** [comment]
Might be related to this issue #1128 since ngx-charts depends on d3
