### ISSUE TITLE
Open typescript react apps from github. 

### ISSUE THREAD

**Issue by mddifilippo89** [stackblitz/core#1131]
I have been testing and trying to get dummy typescript react apps to launch in stackblitz with no luck. 

https://github.com/IgniteUI/testStackblitz/tree/master/my-app-stackblitz2

**Comment by mddifilippo89** [comment]
I used this command to create the project:

 npx create-react-app my-app-stackblitz2 --template typescript

**Comment by mddifilippo89** [comment]
sample is working standalone here:
https://stackblitz.com/edit/react-ts-b7h14h

**Comment by mddifilippo89** [comment]
Your competitor's are support typescript 
https://codesandbox.io/s/github/IgniteUI/testStackblitz/tree/master/my-app-stackblitz2

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
