### ISSUE TITLE
Generated components come without any html file when you reload your angular project

### ISSUE THREAD

**Issue by Roliver-Javier** [stackblitz/core#1134]
If your angular project is on a github repository and you're trying to generate a new component and then you push it to the repository and then you try to reload your project and load the last version you pushed, the component you created come without any html file!.

![bug1](https://user-images.githubusercontent.com/6831595/70573258-fbeea280-1b77-11ea-81e0-1789ed37aaf1.PNG)
![bug2](https://user-images.githubusercontent.com/6831595/70573259-fbeea280-1b77-11ea-8773-f8786b71ec70.PNG)

Then you reload your project after pushed your commits

![bug3](https://user-images.githubusercontent.com/6831595/70573284-09a42800-1b78-11ea-9b93-d33607566c08.PNG)

There's no html file!

**Comment by bezael** [comment]
I have the same issue

**Comment by arikanorh** [comment]
I can confirm this.
