### ISSUE TITLE
Can't install @fireflysemantics/slice

### ISSUE THREAD

**Issue by fireflysemantics** [stackblitz/core#1137]
Hi - I'm still getting installation errors on this package a lot - especially after it's published.  It installs fine in normal angular projects.

https://www.npmjs.com/package/@fireflysemantics/slice

**Comment by fireflysemantics** [comment]
Tested it again and now - a day later it installs fine. NPM throttling issue?

**Comment by fireflysemantics** [comment]
Oooops - never mind - at first it appears to go well, and then a few minutes later I get the message  `@fireflysemantics/slice` and it offers to install it, but can't.

**Comment by fireflysemantics** [comment]
I have had intermittent success.  Sometimes it works sometimes not.  And the version number is the same.  Today it is not working.  It says it's installed, and then it says it's not.  This is a screenshot:
![Screenshot from 2019-12-22 12-17-04](https://user-images.githubusercontent.com/25155787/71325653-5dd2d480-24b5-11ea-9fd7-673599836862.png)

**Comment by sulco** [comment]
Thanks for submitting the issue! We have experienced several problems with npm cache a while ago but this should be resolved already.
Closing, but please reopen if you'll still experience it!
