### ISSUE TITLE
GitHub Sync support timeline

### ISSUE THREAD

**Issue by jthegedus** [stackblitz/core#114]
Thanks for the amazing tool!

From the profile page we see:

> These are your StackBlitz projects. You'll soon be able to sync them to Github repos! [Learn more](https://github.com/stackblitz/core).

It would be good if the link actually linked to a roadmap or a timeline. Since I can't find the timeline I assume it's not public, but knowing it's not multiple months away would be nice.

Additionally, if you want help with documentation or anything I would gladly help! This project is SUPER :sunglasses:

**Comment by EricSimons** [comment]
@jthegedus thanks so much for the kind words!! And I totally agree :) So sorry about my delay here btw, I've been out with a nasty cold the past few weeks :sneezing_face: 

I'm writing up some documentation/roadmap stuff that should be out next week which will help explain what we're up to. Github integration should be landing before the end of the month btw, so it's def not multiple months out!

Also, we were totally unprepared for the amount of traffic/interest we got after the launch (esp considering we're just a 2 man team) — we really appreciate ya'll being patient with us as we're getting alll our stuff in order :)

**Comment by jthegedus** [comment]
No need to apologise @EricSimons!! Thanks very much for the update. :smile: I'm excited to see how we can all contribute!
