### ISSUE TITLE
Bug: ES6 class body not in strict mode by default

### ISSUE THREAD

**Issue by jostschmithals** [stackblitz/core#1141]
This code should output `undefined`, since the body of an ES6 class should be in `strict mode` by default:

```
class MyClass {
   constructor() {     
       (function() {
         console.log(this);
       })();
   }
}
new MyClass();
```

But in stackblitz `this` in the inner function of a class method points to `window`.

[https://stackblitz.com/edit/stackblitz-bug-strict-mode-in-classes](https://stackblitz.com/edit/stackblitz-bug-strict-mode-in-classes)

**Comment by sulco** [comment]
Thanks for taking time to report this and for the solid reproduction.
Thankfully it looks like it's no longer an issue :)
