### ISSUE TITLE
vscode default Theme

### ISSUE THREAD

**Issue by yunliang-ding** [stackblitz/core#1142]
What can I do to set the theme of vscode dark-plus?  thank you very much.

**Comment by yunliang-ding** [comment]
Use Prism 
// eg.
const result = classifications.map(classification => ({ // classifications  Prism-> Output
      range: new monaco.Range(
        classification.startLine,
        classification.start,
        classification.endLine,
        classification.end
      ),
      options: {
        inlineClassName: classification.kind
      }
}))
editorMonaco.deltaDecorations([], result);

**Comment by EricSimons** [comment]
Hey! StackBlitz already ships with darkplus by default. Closing for now but lmk if there's anything else I can help with-
