### ISSUE TITLE
Blitz naming conflicts

### ISSUE THREAD

**Issue by moniuch** [stackblitz/core#1143]
Occasionally I run into naming conflicts, even with names that are really random

![image](https://user-images.githubusercontent.com/681956/71249859-6a70f480-231e-11ea-8d91-d6ac8a58ebab.png)

I remember this occurring also when I am logged in, in which case I would expect the name to have to be unique only within my namespace.

**Comment by moniuch** [comment]
given that the project must be unique among all users - that's because of **[project-name].stackblitz.io** domain scheme - how about if logged-in users could have their own namespace - as in: **[project-name].[user].stackblitz.io**? That would then enforce uniqueness only within a user scope?

**Comment by AlexandreLon** [comment]
> given that the project must be unique among all users - that's because of **[project-name].stackblitz.io** domain scheme - how about if logged-in users could have their own namespace - as in: **[project-name].[user].stackblitz.io**? That would then enforce uniqueness only within a user scope?

Yes, i would have it !

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
