### ISSUE TITLE
Copy+Paste folders & files in sidebar pane

### ISSUE THREAD

**Issue by aramidefemi** [stackblitz/core#115]
Hello guys great job. but i noticed i can not copy a file or folder and paste them. i'd love to be able to do this thanks

**Comment by EricSimons** [comment]
@aramidefemi I totally agree — we're going to add this asap. Btw sorry about my delay here, I've been out sick with a nasty cold the past few weeks :sneezing_face:

**Comment by EricSimons** [comment]
This will require us to have "active" folders/files when you click them, including cmd/ctrl + click for multiple (similar to vsc)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by namastiy** [comment]
Hello guys great job. but i noticed i can not copy a file or folder and paste them. i'd love to be able to do this thanks

**Comment by namastiy** [comment]
![qrcode_stackblitz com](https://user-images.githubusercontent.com/96686544/147556978-dc7ce8c6-7077-443a-86a6-51a6742c2ca5.png)

**Comment by namastiy** [comment]
<?php
header("Content-Type: application/json; charset=UTF-8");
$ch = curl_init();
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
curl_setopt($ch, CURLOPT_ENCODING,"");
curl_setopt($ch, CURLOPT_MAXREDIRS, 10,);
curl_setopt($ch, CURLOPT_TIMEOUT, 30,);
curl_setopt($ch, CURLOPT_HTTP_VERSION, CURL_HTTP_VERSION_1_1,);
curl_setopt($ch, CURLOPT_URL,"https://www.instagram.com/".$GET['user'] ."/?_a=1");
$result=curl_exec($ch);
curl_close($ch);

if($_GET['user']){
echo $result;
}else{
echo "null";
}

**Comment by janosh** [comment]
Unless I'm missing something, it's still not possible to duplicate a file with copy paste? I think this issue was closed prematurely.
