### ISSUE TITLE
Service worker and Stackblitz

### ISSUE THREAD

**Issue by gspassky** [stackblitz/core#1150]
Dear friends, I'm making Progressive Web App using Stackblitz, but I can't figure out how to make it work. It seems that when building production project (and upload it to Firebase Hosting) Stackblitz ignores any unusual files, including static assets (images) and not commont scripts. So if I create a service worker script - it's being ignored. Even if I use @angular/service-worker package with correct settings in angular.json - nothing works. I've spend a couple of hours, but no docs about this... Please, help.

**Comment by gspassky** [comment]
There is a workaround - take a look at https://gist.github.com/puf/e00c34dd82b35c56e91adbc3a9b1c412 - it allows you to upload one file to Firebase Hosting without changing all other (which were uploaded by StackBlitz). In comments I've wrote some changes to code to make single-page apps work properly.

**Comment by Fritsl** [comment]
2025, Bolt.new send me here with a bug - what do I do now ?!?
