### ISSUE TITLE
Support two-way sync with Github repos

### ISSUE THREAD

**Issue by WajdiMakhlouf** [stackblitz/core#1151]
Importing a repo from github is a killer feature, but to make a change I need to get to my laptop, open my IDE, and make changes, and finally add, commit & push.
But what if I haven't my laptop.
forking my project will create the same project under a different name in stackblitz with the same content, and if I connect a repo, I need to provide a new repo name for stackblitz to add, commit & push.
So it would be very nice if I can have one github repo (which is the code’s source of truth) and make changes {add, commit & push} with either (laptop or stackblitz).
Thanks.

**Comment by EricSimons** [comment]
This is absolutely on our immediate roadmap! Should have a major upgrade for seamlessly committing & syncing w/ github repos in the next month or so. Will circle back here once it's live on prod 👍

**Comment by kc0tlh** [comment]
@WajdiMakhlouf This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
