### ISSUE TITLE
Is "wysywyg" Vanilla possible?

### ISSUE THREAD

**Issue by iliakan** [stackblitz/core#1152]
Is it possible to run create a sandbox with pure HTML/JS/CSS? No auto-bundling, shown "as is".

We need such functionality for JS courses.

P.S. As of now, I see StackBlitz scripts embedded into HTML, no matter how I create the sandbox, even `fork/js`.

**Comment by EricSimons** [comment]
Yes! Check this out: https://stackblitz.com/fork/web-platform

We haven't announced this (yet) but it should work :)

**Comment by iliakan** [comment]
There are developer scripts there:
![image](https://user-images.githubusercontent.com/349336/74313285-51f3e800-4d6b-11ea-8c9d-0f9d48d87595.png)

@EricSimons why there's no "as is" sandbox? Just plain "as entered", no bundling, no dev scripts, the simplest thing to do? =)

**Comment by EricSimons** [comment]
Those scripts are necessary for our devserver functionality to do page refreshes and expose console debugging info. Essentially the same sort of scripts req'd for doing live-reload or similar. Other than that, there is zero modification/transpilation happening to any of your source code in that project preset!

**Comment by iliakan** [comment]
- Page refreshes can be done without scripts inside the refreshed page. If something happens externally, `iframe.location.reload()` call or alike. Sandboxes like https://plnkr.co/ do that, without scripts.
- Console.debug will be indeed inactive.

For our tutorial JS examples at https://javascript.info, simple stuff like basic JS - it would be great to be able to run a page "as is". Currently we're using https://plnkr.co. We were thinking about moving to https://glitch.com/, as it's a newer sandbox and also allows "as is" pages (along with building something), but lacks API.

Looks like StackBlitz has importing API.
It would be nice to have "totally as is" functionality at StackBlitz.
