### ISSUE TITLE
Ionic 4 Starter

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [stackblitz/core#1154]
Is possible to update the Ionic Starter button on Stackblitz home page to include Ionic V4 instead of V3?

**Comment by fridoo** [comment]
I also think it should be updated. Meanwhile an example app was posted here: 
https://github.com/ionic-team/ionic/issues/16354#issuecomment-515100104

Example App: https://stackblitz.com/edit/ionic-v4-angular-tabs

**Comment by EricSimons** [comment]
Thanks for this info y'all- will update the starter on the homepage to Ionic 4 and circle back here once live on prod 👍

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
