### ISSUE TITLE
StackBlitz does not work in IE 11

### ISSUE THREAD

**Issue by kumaresan-subramani** [stackblitz/core#1155]
Stackblitz does not work in IE 11.

### Steps to reproduce:

- Open IE 11.
- Load the following URL - https://stackblitz.com/edit/angular-hq2qtu which is the default Angular template.

### Result:
Errors in the console and the sample isn't there.

### Expected:
We should have an editable sample.

### Screenshot:
![IE11](https://user-images.githubusercontent.com/36756050/71955339-03a07600-320e-11ea-8825-668662fd7126.PNG)

**Comment by kumaresan-subramani** [comment]
https://github.com/stackblitz/core/issues/914

**Comment by fvsch** [comment]
Hi @kumaresan-subramani, thanks for the report!

May I ask why you’d like to run StackBlitz in IE11?

We do not plan to support Internet Explorer at any time. IE11 doesn't support many of the Web APIs that we rely on, such as the [Service Worker API](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) which cannot be polyfilled.

Microsoft also does not update IE11, and will be ceasing all support for IE11 in less than a year:
https://blogs.windows.com/windowsexperience/2021/05/19/the-future-of-internet-explorer-on-windows-10-is-in-microsoft-edge/

**Comment by fvsch** [comment]
Closing this issue since we will not be supporting IE11. But any feedback will be appreciated. :)
