### ISSUE TITLE
unable to import from GitHub

### ISSUE THREAD

**Issue by robbinsjk** [stackblitz/core#1159]
I keep getting "The dependencies for this project couldn't be resolved." It would be nice if it would at least tell me which dependency is the problem. I'm testing by removing the more obscure items but even if I get it imported I doubt I'll be able to install the troublesome dependency on StackBlitz. 
I'm thinking of starting a new StackBlitz and installing these dependencies one at a time and see if anything fails. Here is my package.json.

Can anyone shed some light on this problem and how to resolve it? Thanks.

{
  "name": "club-members",
  "version": "0.1.0",
  "scripts": {
    "ng": "ng",
    "start": "npm-run-all -p client server db",
    "start-members": "npm-run-all -p client server db",
    "db": "json-server --watch db.json",
    "client": "ng serve --poll=2000",
    "server": "nodemon server.js",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/core": "~8.2.14",
    "@angular/flex-layout": "^8.0.0-beta.27",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "@swimlane/ngx-datatable": "^16.0.3",
    "angular-dropdown-menu": "^0.3.0",
    "bootstrap": "^4.4.1",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "dont-sniff-mimetype": "^1.1.0",
    "libphonenumber-js": "^1.7.30",
    "@uiowa/digit-only": "^1.2.3",
    "material-icons": "^0.3.1",
    "ngx-bootstrap": "^5.2.0",
    "nodemon": "^2.0.2",
    "npm-run-all": "^4.1.5",
    "popper": "^1.0.1",
    "popper.js": "^1.16.0",
    "rxjs": "^6.5.2",
    "tslib": "^1.10.0",
    "x-xss-protection": "^1.3.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.21",
    "@angular/cli": "~8.3.21",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Comment by robbinsjk** [comment]
I may have found the problem, at least, a problem. My package.json contains "@angular/material": "^8.2.3". I started to install each dependency into a new project and when I entered "@angular/material@8.2.3", I got a message that @angular/material" couldn't be found in npm. I then just entered "@angular/material" and it installed version 8.2.3. Can we not specify a version in a StackBlitz project? I'm going to keep adding them manually. I don't know how to fix my package.json so it will import the entire project. That would be nice to know.

**Comment by robbinsjk** [comment]
I'll keep responding to myself in case it helps someone else. The problem turned out to be a couple of import statements that had absolute paths instead of relative paths. So if you have errors importing your GitHub project, check for absolute paths anywhere in your code, especially imports.

**Comment by sulco** [comment]
Thanks, @robbinsjk for submitting the issue and documenting the resolution :)
