### ISSUE TITLE
Why not just start with monaco?

### ISSUE THREAD

**Issue by cwtuan** [stackblitz/core#116]
VS code is bundled with electron and is hard to get rid of it. For web-based IDE, the implementation of file explorer is different.

So why do you use VS code as base of stackblitz? How if you just use the monaco editor and implement file explorer by yourself. Then you may add some custom  functionality easily. Do VS code provide some functionality that is hard to implement in web?

**Comment by Toxicable** [comment]
Why start over when it works totally fine as is?

**Comment by cwtuan** [comment]
Could you tell me how to remove electron from vs code?

**Comment by EricSimons** [comment]
I'm writing up some documentation that should answer our technical choices, shooting to have it out sometime next week. Closing this issue for now!
