### ISSUE TITLE
Page not loading

### ISSUE THREAD

**Issue by bhavana-jain** [stackblitz/core#1164]
Trying to import project from GitHub but not working
 Pls help

**Comment by natrius** [comment]
A little bit less information? OS, Browser, Broserversion, what did you try? Is it maybe the same as my problem? https://github.com/stackblitz/core/issues/1104

Have you tried another browser already or even another OS?

**Comment by EricSimons** [comment]
Closing for now but feel free to comment w/ repro and I'll reopen!
