### ISSUE TITLE
Embed not working in Wordpress

### ISSUE THREAD

**Issue by esausilva** [stackblitz/core#117]
I recently created a project and embedded it into one of my blogs in Wordpress. I am not sure if it's my site or the embed feature really does not work well with Wordpress sites. The browser preview never displays the app.

This is my [blog entry](http://esausilva.com/2017/08/26/character-word-sentence-paragraph-counter-in-vanilla-javascript-and-react/), just scroll down to the bottom of the page.

**Comment by EricSimons** [comment]
Eek! I'm heading into our office now and will investigate once I get there - will report back asap! 😅

**Comment by EricSimons** [comment]
@esausilva it looks like a problem with the embed code wordpress is putting in — specifically, it lacks the 'allow-same-origin' flag on the sandbox attribute (you can see the error in the console). Are you able to modify the embed code at all? Also, would love to have more info about what version of wordpress/plugin/etc you're using so I can try and dig into on my end as well 👍

**Comment by esausilva** [comment]
Yeah, I noticed that in the console. Maybe because my site is not HTTPS? 

I just copied and pasted the embed url (https://stackblitz.com/edit/character-word-sentence-and-paragraph-counter?embed=1&file=index.js&view=preview) in the WYSIWYG editor, source view.

Wordpress Version: 4.8.1 (latest)
[Wordpress Plugins](http://i.imgur.com/2CiT3Hg.jpg)

**Comment by EricSimons** [comment]
No, it's actually because wordpress is adding the `sandbox` attribute to the iframe on the page but isn't including `allow-same-origin` :( 

Can you try adding the iframe tag manually in the non-WYSIWYG editor and see if that works?

**Comment by esausilva** [comment]
Ah, it works by adding the iframe manually. Thank you 👍
