### ISSUE TITLE
zlib_bindings error

### ISSUE THREAD

**Issue by blakep422** [stackblitz/core#1172]
Trying to create a simple stackblitz app using express-mung. Cant proceed because of this error:
Import error, can't find file:
./zlib_bindings

Any thoughts? I cant install that as a dependency.
thanks!

**Comment by blakep422** [comment]
Here is the app:  https://stackblitz.com/edit/js-3onnyf

**Comment by EricSimons** [comment]
Hey @blakep422 - right now we don't support backend nodejs projects on stackblitz but that will be changing soon :) I've tagged this issue so we can test our next gen toolchain against to ensure it works. Will circle back here once it's live on prod!

**Comment by blakep422** [comment]
Ok...thanks.... Didn't realize that

**Comment by nayfin** [comment]
@EricSimons I'm getting this when trying to use `angular-instantsearch` in a stackblitz project. I've filed a [issue](https://github.com/algolia/angular-instantsearch/issues/728) with their repo as well. I just wanted to report it here as well. If you you have any insight you can post to the issue to help them that would be amazing. 

Thanks for Stackblitz! I use it to provide living examples and docs for my Angular library

**Comment by Sunil-1997kumar** [comment]
Import error, can't find file:
./zlib_bindings

same thing am also getting in react js
