### ISSUE TITLE
not able to open angular repo from github

### ISSUE THREAD

**Issue by goodmite** [stackblitz/core#1175]
Link: https://stackblitz.com/github/goodmite/angular-popover-bug
github: https://github.com/goodmite/angular-popover-bug

**Comment by EricSimons** [comment]
@goodmite it looks like this repo is using a lot of custom tooling alongside the angular CLI which we don't (yet) support. I've tagged this issue to track against our next-gen toolchain that should be able to support this and will circle back once it's live :)

**Comment by goodmite** [comment]
@EricSimons can you tell me which custom tooling you are talking about? I don't think I am using anything out of the ordinary.
