### ISSUE TITLE
Cannot find Module class for lazy loaded module in Angular

### ISSUE THREAD

**Issue by sagarrchauhan** [stackblitz/core#1176]
I uploaded an Angular Project from my github repo which contains a feature for lazily loading a module which is not route based. The project runs fine on my local machine but throws an error:
Error: Uncaught (in promise): Error: Cannot find 'LinkModule' in 'src/app/modules/link/link.module'

This seems to be some kind of path issue in Stackblitz 

Here is my code repo: https://github.com/sagarrchauhan/angular-lazy-loading-components 
and stackblitz: https://stackblitz.com/edit/github-knpdp5

**Comment by mlc-mlapis** [comment]
@sagarrchauhan You should probably use the new dynamic `import` syntax instead of `NgModuleFactoryLoader` that is depreciated now already.
