### ISSUE TITLE
Images don't work

### ISSUE THREAD

**Issue by kgish** [stackblitz/core#1178]
In the header of my app, I include a logo 'assets/images/logo.png'.

For some reason, it is not loaded correctly, and only the broken placeholder is displayed.

**Comment by EricSimons** [comment]
Hey @kgish- can you post a link to your project here so I can debug?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
