### ISSUE TITLE
'@stackblitz/sdk' openProject dependencies not support tag

### ISSUE THREAD

**Issue by zombieJ** [stackblitz/core#1179]
Reproduce:
```jsx
import stackblitzSdk from '@stackblitz/sdk';

stackblitzSdk.openProject({
  // Other config
  dependencies: {
    antd: 'next',
  },
});
```

Only `antd: 'latest'` work. `next` will cause missing deps.

**Comment by zombieJ** [comment]
Related issue: https://github.com/ant-design/ant-design/issues/21317

**Comment by EricSimons** [comment]
We actually do support tags, but it looks like this error is because our npm registry is having trouble resolve `rc-tooltip@4.0.0-alpha.3`.

cc @apai4 - do we need to do a registry resync?

**Comment by EricSimons** [comment]
Looks like this should be fixed- closing for now but lmk if you run into any other issues!
