### ISSUE TITLE
Enable fonts and icons from node_modules

### ISSUE THREAD

**Issue by zergote** [stackblitz/core#118]
Hey, guys, 

I have tried to use react-fontawesome and react-icons libraries for managing icons. I couldn't because it gives me mistakes. 
When you can verify why I can't use them with your editor.

**Comment by EricSimons** [comment]
@zergote can you link your project here so I can repro?

**Comment by zergote** [comment]
Hello, it works, every time I try to use an icon I get an error and I did not reender the application.
I just tried and placed the bar icon.
Anyway here the app, I really like its editor.

https://app-tdg.stackblitz.io

**Comment by EricSimons** [comment]
@zergote sorry about my delay here, I've been fighting a nasty cold the past few weeks :sneezing_face: 

Are you including the fontawesome CSS stylesheets in external dependencies? If not, I don't think that the icons from these NPM packages will render properly.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by komarovalexander** [comment]
Hello, in my example https://stackblitz.com/edit/table-grouping-custom-cell-ts-rmagyp?file=Demo.tsx group icons are not shown, could you have a look at that please?
