### ISSUE TITLE
How to see How many number of people Viewed my project? in StackBlitz..? 

### ISSUE THREAD

**Issue by parthdevloper** [stackblitz/core#1181]
Hello Guyz,

**How many numbers of people Viewed my project in stackBlitz ?**. It would be great if you do this. It will _motivate the developer's in their own way_.

Thank you.

**Comment by sulco** [comment]
Hi @parthdevloper, thanks for submitting the question! You can see the views number:
1. in the "Info" panel in the sidebar (collapsed by default)
![image](https://user-images.githubusercontent.com/1511906/107367924-2facbb80-6ae0-11eb-97aa-31bfd42a5648.png)
2. in your dashboard:
![image](https://user-images.githubusercontent.com/1511906/107368001-49e69980-6ae0-11eb-8901-fdbc28713db2.png)
