### ISSUE TITLE
Unable to add files or folders in react-ts project 

### ISSUE THREAD

**Issue by dennis-c** [stackblitz/core#1184]
I seem to be unable to find any button to add a new file or folder after starting a new react-ts project from the stackblitz homepage

![Screenshot 2020-02-20 at 13 51 46](https://user-images.githubusercontent.com/1841343/74935201-2797cf80-53e8-11ea-970e-9c06e949c4fb.png)

**Comment by TheTiGuR** [comment]
Hover your mouse over the line that shows 'Files' - there will be icons that appear to the right side of that bar for file/folder creation

**Comment by dennis-c** [comment]
Looks like it has indeed been fixed recently (those buttons where not there when I reported the issue, I even did an inspect element). I'll close the issue.
