### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by vigu184** [stackblitz/core#1187]
The dependency could not be resolved. I have made a project using Angular CLI 9.0.3.
When I connect my repo to stackblitz and open in the given repository it is not able to open.

**Comment by TheTiGuR** [comment]
Do you have a link to your project we can look at in reference to this this? You might consider cloning your project locally and going through the build process to see if an ng serve will work for you.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
