### ISSUE TITLE
problem while opening file through stackblitz

### ISSUE THREAD

**Issue by rohitmishra199403** [stackblitz/core#1188]

**Comment by TheTiGuR** [comment]
As this is empty, would you please either update with the issue you have or close? Thanks!

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
