### ISSUE TITLE
Huge vendor.bundle and app.bundle size...

### ISSUE THREAD

**Issue by gspassky** [stackblitz/core#1189]
Hi there! Thank you so much for this awesome product - it really takes pain away while deploying Angular apps to Firebase! But there is a problem. 

My app uses rxjs, momentjs and angular material. After deploying to Firebase vendor bundle is 5.5 MB (!!!) and app bundle is 1.5 MB... Audit shows that processing of vendor bundle takes about 6-8 seconds on mobile devices. Loading time on mobile is also about 7-8 seconds... (Lighthouse says first load is even 17 seconds!) I've made everything I could to reduce loading time - used service workers (caching), lazy loading modules... But the problem is huge vendor bundle... Angular.json config is ignored in StackBlitz, so I can't make fine tune of compilation settings. For example, I can't divide vendor bundle in parts to lazy-load some dependencies... 

Also, to make service worker, I have to copy generated scripts in my local Firebase project and publish it again manually with "firebase deploy --only hosting". This is because StackBlitz ignores static assets and not standard scripts while compilation.

So, these 2 critical feature requests from me:
1. Ability to use all angular.json directives (including ability to use and configure custom webpack)
2. Ability to use static assets (and scripts)

Thanks! :)

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by gspassky** [comment]
hi there! these issues are critical. waiting for any solution in the near future...
