### ISSUE TITLE
Folders that include the same string

### ISSUE THREAD

**Issue by zergote** [stackblitz/core#119]
Hey, guys, 

Working with your editor I realized that by having folders in the same directory containing the same string in the same order, the contents of both are merged. For example:

/components
---sidebar
---sidebarLinks

**Comment by apai4** [comment]
@zergote Sorry about that! The file rendering logic was recently changed and that was definitely a regression on my end. A fix is now live so lmk if you run into any more issues & thanks for the reporting the bug!
