### ISSUE TITLE
couldn't load a project from github

### ISSUE THREAD

**Issue by eng-dibo** [stackblitz/core#1190]
I got the following error
```
The dependencies for this project couldn't be resolved.
```

and I already reviewed this answer and verified that this is not my case.
https://github.com/stackblitz/core/issues/370#issuecomment-378081411

my repo:
https://stackblitz.com/github/goblins-tech/almogtama3

**Comment by TheTiGuR** [comment]
Pulling down you repo locally, I get the following error when attempting to run ng serve. Presumably fixing this will resolve the error:
`Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(outputPath).`

**Comment by eng-dibo** [comment]
did you use `ng serve` without any parameters? anyway I don't use `ng serve` at all, and it is not included in my scripts.

@TheTiGuR

**Comment by TheTiGuR** [comment]
No parameters - Just reporting what I see when trying to build outside of Stackblitz. It may or may not be related, but it seems like it would be a good place to start.

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click your project link. We are unable to provide assistance without further information about the issue you are seeing without being to reproduce the issue and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

![Screen Shot 2021-05-23 at 1 22 25 PM](https://user-images.githubusercontent.com/49956513/119270275-ee8d7280-bbc9-11eb-9320-4bf6cd0cc10a.png)
