### ISSUE TITLE
Save doesn't always really save

### ISSUE THREAD

**Issue by kaljarv** [stackblitz/core#1192]
I hope I will be unable to reproduce the error but just lost 3 days of work. I had hit the save button frequently for the project and didn't see any errors. Today, however, when I was forced to reload the project, the last changes where from 3 days ago :(

One glitch had been recurring, though, the preview window showed quite often a missing dependency error prompting to install them, but the module name was just "https:". This always went away when I "saved" the project.

Using Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by purplem1lk** [comment]
Thank you for your patience - I'm sorry you lost progress on this project and we appreciate you bringing this to our attention. We hope you don't run into any more issues with the Save button, but if you do, please tag me to reopen this issue and provide your project link so we can work with you to debug this. Thank you! :)
