### ISSUE TITLE
Deployment to Firebase Issue

### ISSUE THREAD

**Issue by thaipokecard** [stackblitz/core#1199]
I tried to deployed angular application from stackblitz to firebase. I noticed that only 5 files were deployed and when I accessed the page, I only saw "loading." I didn't see any errors when I clicked deploy so I couldn't understand why it happened.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing or being able to reproduce this error and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
