### ISSUE TITLE
Is there a way to send a message trough postmessage to the stackblitz SDK?

### ISSUE THREAD

**Issue by titombo** [stackblitz/core#1202]
I want to send information to the VM Stackblitz hosted in my website and vice-versa, the only way I have found was creating a file, but when doing so the application is reloading. And I would like to have this communication for every second.

I tried something like this on the parent:

`this.vm.rdc.port.postMessage('dasdsa')
`
also I tried something like:

var myMessage = {data: {
      test:"test"
    }};

    var iframe = document.getElementById(inputName);
    if (iframe == null) return;
    var iWindow = (<HTMLIFrameElement>iframe).contentWindow;

    iWindow.postMessage(myMessage, "*");

And on the VM I tried to intercept it like:

```
  @HostListener('window:message', ['$event'])
  onMessage(e) {
    if (e.origin != "http://localhost:4200") {
      return false;
    }
    if (e.data.for == "user") {
      alert('here i am');
    }
  }
```

But I am not having any lucky on this communication. Is there any idea on how to do it?

**Comment by titombo** [comment]
I created a bounty in stackoverflow with 100 points for someone that knows this answer: https://stackoverflow.com/questions/60810084/how-to-send-a-message-to-stackblitz-vm-from-the-parent-window-using-angular

**Comment by fvsch** [comment]
Hi,

This is not possible and not planned.

If you still have a use case for this, feel free to open a new issue presenting your use case (what behavior or feature you're trying to achieve); there could be other options than having the editor window respond to arbitrary messages from the parent document (which is a security risk).
