### ISSUE TITLE
Can't find package w3c-keyname

### ISSUE THREAD

**Issue by PetarMetodiev** [stackblitz/core#1206]
Since version `2.2.3`, `w3c-keyname` does not seem to work in StackBlitz - https://stackblitz.com/edit/typescript-zw2hah?file=index.ts

This is what I get in StackBlitz:
![image](https://user-images.githubusercontent.com/6378306/78338367-57b3c000-759b-11ea-84b9-fbebbe71c6ea.png)

The previous version(`2.2.2`) seems to be ok - https://stackblitz.com/edit/typescript-t9ezwm?file=index.ts

These are the changes between `2.2.2` and `2.2.3` - https://github.com/marijnh/w3c-keyname/commit/6bb3aba1b762382ef1ae66f2812f20cfaeedab44

I am posting this here since locally everything seems to be working fine. Tested on MacOS and Windows - Chrome, Firefox, Safari.

[According to the package author](https://github.com/marijnh/w3c-keyname/issues/9#issuecomment-608297736) StackBlitz is unable to handle `.cjs` extensions.

**Comment by PetarMetodiev** [comment]
The issue is reproducible in the EditorComponents of both [`KendoUI for Angular`](https://stackblitz.com/edit/angular-cq61ng?file=app/app.component.ts) and [`KendoUI for React`](https://stackblitz.com/edit/react-6fj4xn?file=app/main.jsx).

**Comment by EricSimons** [comment]
Hey! This should be fixed as of 2 days ago- can you check on our end and lmk if all looks good?

**Comment by PetarMetodiev** [comment]
It seems to be working as expected.
Thanks for the quick reaction!
