### ISSUE TITLE
Angular Generator broken in Safari

### ISSUE THREAD

**Issue by juliusn** [stackblitz/core#1208]
Angular Generator menu is broken in Safari 13.1. The menu contents is bloated and has text "Enum" in it. Works fine in Chrome. 
![Screenshot 2020-04-09 at 18 16 27](https://user-images.githubusercontent.com/11663460/78911059-754ac300-7a8e-11ea-9aa8-ae8eebbfa569.png)

**Comment by sulco** [comment]
We've undergone a series of updates to the platform since this issue was submitted and it does no longer seem to appear.
Closing for now, please free to reopen if you're still experiencing it!
