### ISSUE TITLE
Can't add `aframe` npm package 

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#1209]
nor i can add minified js file

**Comment by nukadelic** [comment]
is this website dead ?

**Comment by EricSimons** [comment]
Can you link to the project in question please?

**Comment by nukadelic** [comment]
Any project really 
![image](https://user-images.githubusercontent.com/6582633/79674289-bfa90e00-820b-11ea-8ad5-41727c02a05a.png)
Try adding `aframe` to the dependencies
