### ISSUE TITLE
Can't import an angular package 

### ISSUE THREAD

**Issue by MattewEon** [stackblitz/core#121]
I can't import angular package in your online editor.
If you want to try it : https://angular-uf52ak.stackblitz.io

**Comment by EricSimons** [comment]
@MattewEon which packages are you having trouble importing? I'm looking at https://stackblitz.com/edit/angular-uf52ak and it seems to be importing all packages totally fine

**Comment by MattewEon** [comment]
Oh sorry, I though users were able to see the code. I want to include the package "ngx-heyl-progressbar" and I'm getting an error in the render window

**Comment by EricSimons** [comment]
@MattewEon the [package.json](https://unpkg.com/ngx-heyl-progressbar@3.2.5/package.json) from `ngx-heyl-progressbar` has a main field that points at a TS file (`index.ts`), not a CommonJS file :)

**Comment by EricSimons** [comment]
Closing this issue for now, but feel free to reopen if the problem persists!
