### ISSUE TITLE
Suggestion: Forbid changes without forking

### ISSUE THREAD

**Issue by JasonGoemaat** [stackblitz/core#1211]
It seems like if you go to someone's public project you can make changes, but not save them.  I had added several files and made changes to others and saw my changes, but couldn't save.  When I clicked fork I thought it might create a new project and include my changes, but it warned me that I had unsaved changes so I cancelled.  The spinner on the fork button kept spinning and I couldn't do anything and the preview stopped working.  I had errors in the console saying it couldn't find files "stackblitz://index.js" or something.

If it's not possible to save or fork after making changes and include the changes, it would be nice if changes weren't allowed, or if a warning was given that you were making changes you couldn't save.

**Comment by sulco** [comment]
Hi @JasonGoemaat, thanks for reporting this! I'm sorry for the inconvenience. Happy to report we have rolled out several updates to the forking workflow: now if you do some edits on a project that's not your own and try to save the changes, the project is automatically forked, saved – and includes your changes :)
