### ISSUE TITLE
Not able to run this angular app, which is working fine in local.

### ISSUE THREAD

**Issue by abhisheksarkar444** [stackblitz/core#1212]
I have uploaded an angular project in Github and tried to open it manually using stackblitz. Every time it is showing the error that not able to load and project has some errors.

This is the sample application created in Angular
https://github.com/abhisheksarkar444/Sample.git

**Comment by validity-check** [comment]
Hi,
I get this with my angular appas well, but only with Firefox. If I use, for example, Microsoft Edge, my application seems to run fine

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
