### ISSUE TITLE
package.json missing?

### ISSUE THREAD

**Issue by WHOISNVA** [stackblitz/core#1214]
I have this file in my repo however seems Stackblitz couldnt tell.

**Comment by jasarm** [comment]
Si el proyecto es de Ionic, ese es el problema, porque aun no hay soporte para Ionic.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without a project link or GitHub repository and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
