### ISSUE TITLE
app.firestore is not a function

### ISSUE THREAD

**Issue by mlpierce22** [stackblitz/core#1215]
I am developing a web development education platform that uses Stackblitz to host examples for people to practice what they have learned.

I keep experiencing an error that says `"app.firestore is not a function"` in the console.
<img width="443" alt="Screen Shot 2020-04-17 at 2 36 31 PM" src="https://user-images.githubusercontent.com/35623597/79616003-ddb22980-80b8-11ea-8efa-1439b21cb349.png">

The thing I have been struggling with is that I seem to get inconsistent results with commits that are very similar (borderline identical).

[Example of a working commit](https://stackblitz.com/github/tech4good-lab/compass/tree/a42b4fca4fa758e65de279f4866cbeb1615cffb3)

[Example of a broken commit](https://stackblitz.com/github/tech4good-lab/compass/tree/46fee6ae2b6c152f253cd2c03810333b267cf817)

The only difference between the two commits is this:
<img width="893" alt="Screen Shot 2020-04-17 at 2 31 46 PM" src="https://user-images.githubusercontent.com/35623597/79615666-2d442580-80b8-11ea-8325-0dd8af8ef399.png">

I thought it was a `package.json` issue, but `package.json` and `package-lock.json` are identical between the two commits. The main thing I noticed was that `package.json` on Stackblitz looks different than the one on our local repo (but not different between the two Stackblitz repos above)

Diff between two Stackblitz repos package.json: (left working, right broken)
[https://www.diffchecker.com/SymzwTIA](https://www.diffchecker.com/SymzwTIA)

 ** There is no difference between the package-lock.json files in either one**

Diff between local repo and Stackblitz: (left local, right stackblitz)
[https://www.diffchecker.com/6BWuikcg](https://www.diffchecker.com/6BWuikcg)

The one fix I have come up with (but is not feasible to use in our scenario because we hide the side menu from user so they don't get confused) is to refresh the dependencies like in the following video:

[https://www.youtube.com/watch?v=A7VTVqJEA9g ](https://www.youtube.com/watch?v=A7VTVqJEA9g )

I want to do this ahead of time because we can't have every user have to install all the packages that Stackblitz missed every time they want to try out an example.

This seems to be an internal Stackblitz issue... Any ideas?

**Comment by nayfin** [comment]
I'm having a similar issue when linking my repo to Stackblitz. I'm using firebase storage to demo a file uploader for a library I wrote and have been using Stackblitz as an playground to showcase the library. My issues only seemed to happen after adding firebase, though it works fine locally. 

Here is the stackblitz link https://stackblitz.com/github/nayfin/tft-documentation and here is the repo https://github.com/nayfin/tft-documentation
