### ISSUE TITLE
can not enable ivy (always compiling changes...)

### ISSUE THREAD

**Issue by vthinkxie** [stackblitz/core#1216]
when enable ivy with ng-zorro-antd in stackblitz, the project keeps compiling changes
repro link:
https://stackblitz.com/edit/ng-zorro-antd-ivy?file=src%2Fapp%2Fng-zorro-antd.module.ts

**Comment by Totati** [comment]
I have a similar problem. If you remove the "2" before the pipe the build stucks in compiling changes, and there's no way out. There's no clear indicator what's the problem, it's not working after finding & fixing it.
https://stackblitz.com/edit/angular-ivy-zsuzfz?file=src%2Fapp%2Fapp.component.html

**Comment by EricSimons** [comment]
Yikes, good find. Looks like the Ivy compiler crashes and can't recover. Sending this over to our folks now to debug

**Comment by Totati** [comment]
Now it's working correctly for me. 👍

**Comment by EricSimons** [comment]
Awesome, that's great to hear! Closing this out, let us know if you run into any other issues 👍
