### ISSUE TITLE
angular project - html file deleted automatically when reopened project.

### ISSUE THREAD

**Issue by baraskarharshal** [stackblitz/core#1217]
I had created a new angular project. here is the url. https://stackblitz.com/edit/angular-5s14gt. I pushed this project on github. When I reopened the project html files from my both components "sidebar" and "simple-ng-select" are missing. I lost  some of my work here. Can you let me know how come this happened and how can I avoid this in future?

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)!  

_Related issue #2473_
