### ISSUE TITLE
"Unable to resolve package" when package/version exists

### ISSUE THREAD

**Issue by andrewfulrich** [stackblitz/core#1218]
I'm trying to move some examples over to stackblitz but ran into this error installing `@bayer/ol-kit`
![image](https://user-images.githubusercontent.com/6819762/79922383-7c13f700-83f9-11ea-9c15-86e835bf6cc1.png)

Reproduction steps:

- add `ol@4.6.5` to dependencies to see that installs just fine by itself
- add `@bayer/ol-kit` to dependencies to see the error message

This looks similar to https://github.com/stackblitz/core/issues/286 and https://github.com/stackblitz/core/issues/175
but I don't see any malformations in the package.json at https://github.com/MonsantoCo/ol-kit/blob/v0.2.2/package.json

Why would it look for `ol@~4.0` when the dependency in the package.json specifies ol@4.6.5? Wouldn't it at least look for `ol@~4.6`?

**Comment by andrewfulrich** [comment]
oops, sorry I see that `ol@~4` exists, but not `ol@4.0`. But why is it looking for `ol@4.0` when the dependency in the package.json specifies `ol@4.6.5?`?

**Comment by EricSimons** [comment]
Hm, do any subdependencies of `@bayer/ol-kit` specify `ol@~4.6`? That's the most likely culprit. I can investigate this deeper but any additional info would be super helpful so I can get to the bottom of it quicker

**Comment by andrewfulrich** [comment]
You're right, `ol@~4.0` a dependency of  `@terrestris/ol-util@0.5.0` which is a dependency of `geostyler-openlayers-parser@0.21.0`. When I install it locally, it does `npm WARN` that this is an unmet peer dependency:
![image](https://user-images.githubusercontent.com/6819762/80034184-a32eff00-84b3-11ea-9c7e-32090deeb759.png)
 but it works fine locally despite the warning, since the peer dependency of ol-kit itself is `ol@4.6.5` and that gets installed. Is there any way for Stackblitz to ignore peer dependency warnings?

**Comment by kc0tlh** [comment]
@andrewfulrich, sorry for the delayed response! This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! If it doesn't work out of the box, try this command: _npm install --legacy-peer-deps_ and let us know!
