### ISSUE TITLE
Add "Find in files" functionality

### ISSUE THREAD

**Issue by mattblackdev** [stackblitz/core#122]
@EricSimons It would be nice to have a "find in files" feature like most IDEs. When you remove a package and have code that referenced it, right now I think the only way to fix that is to go through all your files and find the references. I don't know which files have references so I'd have to hunt through my whole code base one by one. I instinctively looked for errors in the console, but I don't see any when stackblitz shows this page:

![screen shot 2017-09-03 at 10 00 59 pm](https://user-images.githubusercontent.com/5210361/30009082-77300a2c-90f3-11e7-9b63-8d9092457e0f.png)

**Comment by EricSimons** [comment]
@mattblackdev I totally agree, thanks for pointing this out! Also, sorry about my delay here - I've been fighting a nasty cold the past few weeks :sneezing_face: 

I think enabling "find in files" + more detailed info about the detected packages should solve this nicely — will implement those asap!

**Comment by EricSimons** [comment]
This has been shipped onto prod for a while now- thanks for the suggestion!
