### ISSUE TITLE
Minor: Angular generator icon for components is tiny

### ISSUE THREAD

**Issue by rheimus** [stackblitz/core#1220]
Observed on:
Chrome 81
Firefox 75
Windows 10

![image](https://user-images.githubusercontent.com/12557419/80043147-fefd9480-8554-11ea-89a8-6384bd170327.png)

Presumably this is unintentional.

**Comment by sulco** [comment]
Thanks for submitting the issue @rheimus! 

Yes, definitely unintentional - this is fixed now :)
