### ISSUE TITLE
Dark theme not considered for console

### ISSUE THREAD

**Issue by niklas-wortmann** [stackblitz/core#1228]
I think it would be convenient to consider the theming preferences of the user in terms of light or dark theme and apply that styling to the console. 
I am using a windows machine and did not found any manual option for that, but also this should be handled automatically by using the `matchMedia` API IMO

**Comment by sulco** [comment]
Hi @niklas-wortmann! I'm happy to report that the console now respects the editor light/dark theme setting:

![2021-04-08 11 37 53](https://user-images.githubusercontent.com/1511906/114004387-e61dea00-985e-11eb-9330-881bac4a9152.gif)

The matchMedia option for themes is planned for later this year:)

**Comment by niklas-wortmann** [comment]
that's awesome. Thanks a lot for taking care of it

**Comment by DanielMadden** [comment]
Is it possible that the theme could be split? Or possibly lighten the default console log colors when dark theme is enabled? 
I love dark mode, but the default console logs for numbers and strings are extremely dark, making them illegible.

**Comment by dota2Pro** [comment]
Dark Theme Console, I can barely see the text
OS: Windows 10
Browser: Chrome 90.0.4430.212
![image](https://user-images.githubusercontent.com/48334588/119825542-aeedc000-bf14-11eb-909f-abe976b41fe4.png)

**Comment by thestroke82** [comment]
> Dark Theme Console, I can barely see the text
> OS: Windows 10
> Browser: Chrome 90.0.4430.212
> ![image](https://user-images.githubusercontent.com/48334588/119825542-aeedc000-bf14-11eb-909f-abe976b41fe4.png)
