### ISSUE TITLE
can't open private github repository

### ISSUE THREAD

**Issue by raymondzou** [stackblitz/core#1232]

**Comment by purplem1lk** [comment]
Thank you for your patience - You can run any public repo on GitHub by providing the username and repository name. Details are available in our documentation: https://developer.stackblitz.com/docs/platform/importing-projects/

We are currently considering other features related to private repositories in our upcoming roadmap. We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
