### ISSUE TITLE
Can't save when I upload 10+ files and folders

### ISSUE THREAD

**Issue by sorrycc** [stackblitz/core#124]
![cant-save](https://user-images.githubusercontent.com/35128/30040277-b089f5c2-920f-11e7-9be3-2f5caffcea45.gif)

**Comment by sorrycc** [comment]
![image](https://user-images.githubusercontent.com/35128/30040299-0c423ea6-9210-11e7-9fb7-59c3480eed9c.png)
I've found the problem, when I add a 181KB image, it failed to save.

**Comment by EricSimons** [comment]
Good catch - sorry about the confusion! Support for static assets is currently being worked on in https://github.com/stackblitz/core/issues/72, so I'm going to close this issue for now :)
