### ISSUE TITLE
Angular Generate not working

### ISSUE THREAD

**Issue by anandaknc** [stackblitz/core#1240]
![Screenshot 2020-05-16 at 2 22 09 PM](https://user-images.githubusercontent.com/30049540/82115552-1eb56080-9781-11ea-8517-9458a021aff2.png)

only Enum option being shown

**Comment by anandaknc** [comment]
this in in safari

**Comment by juliusn** [comment]
Earlier report of the same issue: https://github.com/stackblitz/core/issues/1208

**Comment by kc0tlh** [comment]
This issue has been resolved!
