### ISSUE TITLE
Firebase Deployment took FOREVER

### ISSUE THREAD

**Issue by weilies** [stackblitz/core#1241]
I noticed one of my main project stay in 'firebase deploy' stage
[Screenshot](https://media.discordapp.net/attachments/364486390102097932/711412103029850112/z9whpnCv8cNYwAAAABJRU5ErkJggg.png)
Project: https://stackblitz.com/edit/wcaw-82-8mrd3e

Really not sure what's causing the issue. I tried my other dummy project with only few component, it could deploy to firebase project within 30s. But my main project too took more than 10 mins and still stuck on the 'deploy' step.

The same project used to deployed to firebase, but not sure since when or which package upgraded causing the issue. Furthermore, there ain't any deploy/error log we could reference?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without a working project link or the ability to reproduce and will be closing this accordingly. We've noted on our upcoming roadmap to add better error handling messages for users to reference. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

![Screen Shot 2021-05-23 at 2 20 53 PM](https://user-images.githubusercontent.com/49956513/119272024-197bc480-bbd2-11eb-932e-86a7a048ef6f.png)
