### ISSUE TITLE
Light theme - Connect new GitHub Repository modal

### ISSUE THREAD

**Issue by amitpchigadani** [stackblitz/core#1242]
**Current Behavior:**
In Light theme, stylings are not proper for **Connect new GitHub Repository** modal. Looks like label and text colors are not changing.

**Expected Behavior:**
Text color needs to be dark so that it is clearly visible.

Screenshot
![stackblitz-light mode](https://user-images.githubusercontent.com/18300592/82322063-7eb33d80-99f3-11ea-8233-08ccbc85b735.png)

**Comment by sulco** [comment]
Thank you @amitpchigadani for submitting the issue! It should look better now :)
