### ISSUE TITLE
Firebase deploy doesnt deploy assets like images

### ISSUE THREAD

**Issue by arikanorh** [stackblitz/core#1245]
I've image files under assets. When i use deploy from stackblitz, the images are missing.

Local deploy works just fine

Note:Angular project v9

**Comment by purplem1lk** [comment]
This issue has been resolved and addressed in similar past issues so this will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
