### ISSUE TITLE
Nullish coalescing (??) support

### ISSUE THREAD

**Issue by garronej** [stackblitz/core#1247]
[nullish coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#nullish-coalescing) support would be nice.  

Best regads,

**Comment by arikanorh** [comment]
I'm using || for now

**Comment by sulco** [comment]
Thanks for opening the issue @garronej! We do support nullish coalescing in StackBlitz projects now :)
