### ISSUE TITLE
Feat: Featured workspace for Ionic-React

### ISSUE THREAD

**Issue by ar-daniel** [stackblitz/core#1249]
Please add a featured workspace template for __Ionic-React-TS__
The default Ionic-TS takes to an ionic angular setup.

Replicating a Ionic-React- TS from a plain React-TS template is a pain.
Thanks

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
