### ISSUE TITLE
Cannot open https://stackblitz.com/github/c4dt/service-drynx/tree/master/webapp

### ISSUE THREAD

**Issue by ineiti** [stackblitz/core#1251]
This might be something on our end that doesn't work. But when trying to open

https://stackblitz.com/github/c4dt/service-drynx/tree/master/webapp

It just fails, without a specific error message. Other repos from our org like

https://stackblitz.com/github/c4dt/omniledger/tree/master/webapp

at least open, even though we have some paths in there that (rightly) confuse stackblitz.

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

You can check it out for yourself here: https://pr.new/github.com/c4dt/service-drynx
