### ISSUE TITLE
jsdoc support

### ISSUE THREAD

**Issue by mariomui-viscira** [stackblitz/core#1255]
Would love something that could automatically pull up the /** **/ jsdoc support.
Just so i dont have to write all the params.
/**
*@param {object} weapon
*
*/
function jack(weapon) {
}

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
