### ISSUE TITLE
No Delete Button

### ISSUE THREAD

**Issue by fireflysemantics** [stackblitz/core#1256]
Hi,

I also asked about this on Stackoverflow:
https://stackoverflow.com/questions/62057010/delete-stackblitz-project

How do we delete projects now?

**Comment by artur-zaseev** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/37107439/85793036-14ea2a00-b73d-11ea-89ed-fa6373f736cb.png)

**Comment by sulco** [comment]
Thanks, @artur-zaseev for taking this one :)

You can also delete a project from the Dashboard by clicking the `⋮` button that shows this tiny menu:
![image](https://user-images.githubusercontent.com/1511906/106605750-8dca2380-6561-11eb-9637-a19da16cbb45.png)
