### ISSUE TITLE
Not able to iterate a Javascript Set in stackblitz?

### ISSUE THREAD

**Issue by krist-jin** [stackblitz/core#1259]
Hi,

I am having problems with iterating a Javascript Set using Stackblitz. Originally I thought it might my own problem so I posted it on Stackoverflow: https://stackoverflow.com/questions/62358215/not-able-to-iterate-a-javascript-set-in-stackblitz

So basically this is not working in Stackblitz but working in browser console:
```
for (const n of s) {
  array.push(n);
  console.log(n);
}
```

However as someone pointed out in the comment, it might be a transpilation setting error of Stackblitz so I thought it might be a good place to also posted it here.

Please refer to the stackoverflow post above for more details. And there is the Stackblitz that I reproduced the issue: https://stackblitz.com/edit/javascript-set-iterate?file=index.js

Thanks!

**Comment by sulco** [comment]
Hi @krist-jin, thanks for reporting this!
It should no longer be an issue :)
