### ISSUE TITLE
Slackblitz not working

### ISSUE THREAD

**Issue by raj2033** [stackblitz/core#126]
![image](https://user-images.githubusercontent.com/27882128/30062616-70547f54-9269-11e7-9edf-42fb85c74116.png)
Thanks for creating this wonderful platform. Lots of love from an Angular lover.
I get to know about your site today (5tth ssept) and i fell in love with the look and feel, but i could not edit any file. Waited for more than 5 min, but the app keep on bundling. 
Please resolve the issue asap.
Thanks.

**Comment by EricSimons** [comment]
@raj2033 I just opened that project on my computer and it seems to be working just fine — can you try refreshing your page perhaps?

**Comment by EricSimons** [comment]
Closing issue for now, but feel free to reopen if this issue persists!
