### ISSUE TITLE
User snippets don't work

### ISSUE THREAD

**Issue by artur-zaseev** [stackblitz/core#1260]
Hi,
I am having problems with custom user snippets using Stackblitz. 

![Screenshot_1](https://user-images.githubusercontent.com/37107439/85792775-b91fa100-b73c-11ea-962c-7d6e8282cb9f.png)

**Comment by kc0tlh** [comment]
This issue is resolved as of July 2021 ([blog post here](https://blog.stackblitz.com/posts/update-2021-07/))
