### ISSUE TITLE
Angular Generator Flexbox Issue

### ISSUE THREAD

**Issue by nobobo1234** [stackblitz/core#1262]
The Stackblitz Editors Angular Generator navbar seems to have some issues with how flexbox is configured. It seems like if the text in the `span` is too long it automatically enables `flex-shrink` for the navigation item to fit the text in the navbar, at cost of the icon before the text (see the image). Maybe the `flex-shrink` property should be disabled so that the icon doesn't get shrunk down
![image](https://user-images.githubusercontent.com/14055571/85952826-32510b00-b96c-11ea-871d-d885f7461c3a.png)

**Comment by sulco** [comment]
Thanks @nobobo1234 for reporting this! You're totally right about the reason too 😅
It's fixed now!
