### ISSUE TITLE
problem with 14. Angular: Nested Components

### ISSUE THREAD

**Issue by StanislawJakubowski** [stackblitz/core#1263]
massage:
The url to this repository is invalid.
Please make sure the folder path in the URL exists within the repo.
If you think this is a bug, please file an issue in our repo!

**Comment by genxcru** [comment]
I had the same issue and just reported it again :(
![NestedCompoents14](https://user-images.githubusercontent.com/66973668/96639697-0d541f80-12f0-11eb-86da-cc49a927da58.png)
