### ISSUE TITLE
Modern JavaScript difference b/w  let and var is not working!!!

### ISSUE THREAD

**Issue by Naveenpisher** [stackblitz/core#1265]
function run() {
  var foo = "Foo";
  let bar = "Bar";

  console.log(foo, bar);

  {
    let baz = "Bazz";
    console.log(baz);
  }

  console.log(baz); // ReferenceError
}

run()

In the above code, the reference error is not throwing.

**Comment by sulco** [comment]
Thanks @Naveenpisher for posting the issue. It's now resolved :) 
(see this reproduction https://stackblitz.com/edit/let-var-repro?file=index.js)
