### ISSUE TITLE
A Toolbar at the top prevents accessing some of the buttons like fork, share etc.

### ISSUE THREAD

**Issue by simonssspirit** [stackblitz/core#1266]
A Toolbar at the top prevents accessing some of the buttons like fork, share etc.

![image](https://user-images.githubusercontent.com/11087921/86317831-19c94500-bc39-11ea-9f00-3799e343778e.png)

**Comment by EricSimons** [comment]
Woah, this shouldn't be happening... @sulco any idea why the main headerbar would be rendering on the editor page?

**Comment by sulco** [comment]
Yeah, this view doesn't normally render the main headerbar. 

Could you provide steps to reproduce the issue? (Does that happen on every visit @simonssspirit? Do you go to this page from any other or visit it directly?)

**Comment by apai4** [comment]
This was a bug on our end from a recent update. I just deployed a fix so this shouldn't be happening anymore. @simonssspirit can you confirm that it's fixed for you?

**Comment by simonssspirit** [comment]
@apai4 @EricSimons @sulco I can confirm that it is **not** reproducible now.

Before it was reproducible every time for me and all of my colleagues.
