### ISSUE TITLE
The dependencies for this project couldn't be resolved

### ISSUE THREAD

**Issue by ahmedalatawi** [stackblitz/core#1267]
Hello,
Im getting this error when i try to import my repo from Github:

`This usually means that a dependency in your package.json is incorrect.`

Im not sure what dependency is causing this!

Thanks!

**Comment by sulco** [comment]
Hi @AhmedAlatawi, thanks for reaching out! Can you provide a link to the project where you run into this issue?

**Comment by AhmedAlatawi** [comment]
Sure thing. It's this project: [ngx-treant-js](https://github.com/AhmedAlatawi/ngx-treant-js)
I ended up deploying it to [CodeSandbox](https://codesandbox.io/), but I'd rather have it imported on Stackblitz. 
Any help would be appreciate it! Thanks!

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/bb030964-ad1f-4f9c-8a38-45885420ad37">
