### ISSUE TITLE
Adding a new file with external Keyboard on IPad Pro

### ISSUE THREAD

**Issue by mauricekraus** [stackblitz/core#127]
Hi:),
Thank you for your awesome piece of software:), apparently there is a possible bug. When I Try to add a new file with my onscreen Keyboard it works perfectly fine(just tapping the button, type hello.js and pressing return), but when i hook up my external iPad logitech keyboard or my Apple Wireless Keyboard and press return nothing Happens.. although the return key is working directly in the Editor perfectly fine :/ 
Thanks

**Comment by EricSimons** [comment]
Hey @mauricekraus - thanks for the kind words, we really appreciate it! :)

The core editing engine we're using from VS Code (Monaco) has known issues with iOS, but we're going to investigate possible fixes soon and see what we can do. Will keep you in the loop & thanks for letting us know about this!
