### ISSUE TITLE
Light theme has contrast problems

### ISSUE THREAD

**Issue by waynon** [stackblitz/core#1274]
The light theme has some contrast problems.
When I hover on a method, its tooltip is very light grey, which is not easy to recognize with white backgound.
![image](https://user-images.githubusercontent.com/57490099/87705298-47cd8e00-c7d0-11ea-963a-be827525de04.png)

**Comment by sulco** [comment]
Thank you @waynon for submitting the issue!
We've just pushed an update that should make this look better :)
