### ISSUE TITLE
tsconfig seems to ignore lib option

### ISSUE THREAD

**Issue by waterplea** [stackblitz/core#1278]
Hi there.

I've created an Angular stackblitz and wanted to use `Array.prototype.includes` method, but even though blitz gets created with `es2018` in `lib`, even changing `target` to `es2018` doesn't help, TypeScript complains about `includes` not being available for arrays. It compiles, but the error message is there :(

https://stackblitz.com/edit/angular-array-includes?file=src%2Fapp%2Fapp.component.ts

**Comment by EricSimons** [comment]
Hey @waterplea! This is a good find- we might not be respecting the lib field right now (I'm not sure though :). Looping in @apai4 @KwintenP here who should have a better idea + deploy a fix!

**Comment by daniel-way** [comment]
I tried to do essentially the same thing with String.prototype.trimStart(), adding the appropriate lib and target values, except mine won't compile...

**Comment by HeyGarrison** [comment]
👋 Thanks for the issue y'all!

Over the past few years we've been greatly improving our platform. It looks like we added support for this! ❤️
