### ISSUE TITLE
Yikes! Something went wrong with your request. ---why this?

### ISSUE THREAD

**Issue by redoy4546** [stackblitz/core#1279]
![Screenshot_2020-07-30-10-57-57-87](https://user-images.githubusercontent.com/67165159/88882340-8bee7300-d253-11ea-99af-46145ad87379.jpg)

**Comment by chcaru** [comment]
+1 Now I just see:
`500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.`

**Comment by joeskeen** [comment]
Deployment went wrong?

**Comment by VengateshManiraj** [comment]
I am also facing this issue
```
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.
```

**Comment by chengengliu** [comment]
Same issue here.

**Comment by SarathSri3233** [comment]
500 Internal Server Error
If you are the administrator of this website, then please read this web application's log file and/or the web server's log file to find out what went wrong.

i'm also facing this issue

**Comment by joeskeen** [comment]
Looks like it's back up - and the home page looks way different.  Perhaps it was a bad deployment after all.

**Comment by EricSimons** [comment]
Hey all- our Amazon RDS database ran into an issue last night which caused this error. It should be fixed as of ~9 hours ago. We're writing up a postmortem that we'll be sharing on our [twitter account](https://twitter.com/stackblitz) and have put relevant fixes in place to ensure this won't happen again. We're super sorry about the inconvenience! 😓
