### ISSUE TITLE
Can't install the material-ui@next and material-ui-icons@1.0.0-beta.5 packages

### ISSUE THREAD

**Issue by SergeyAlexeev** [stackblitz/core#128]
It isn't possible to install pre-release [material-ui package](https://www.npmjs.com/package/material-ui) using the `@next` postfix. But I can do it with the particular version like `material-ui@1.0.0-beta.8`.

The last version(1.0.0-beta.5) of [the material-ui-icons package](https://www.npmjs.com/package/material-ui-icons) isn't available, as well. I can install only v.1.0.0-beta.4

**Comment by apai4** [comment]
@SergeyAlexeev Sorry about that, the latest version of `material-ui-icons` should be installable now! I also just added `dist-tag` support so `material-ui@next` should install the tagged release. Try it out and lmk if you run into any more issues

**Comment by SergeyAlexeev** [comment]
Thank you for the quick reply! Now it works perfectly!
