### ISSUE TITLE
Page shows 'Yikes! The page you requested couldn't be found.' and not installing dependencies before this happened

### ISSUE THREAD

**Issue by jessfarr98** [stackblitz/core#1280]
I have not been able to use this software for about a month now. It automatically would install a dependency that was a version too high and then when I try to install a particular version of that dependency that had worked in the past the program would hang on 'Running NGCC' forever and never end up loading anything or even terminate the process. This occurred when downloading the particular dependency ngx-exharts. 

Now, today when I tried to get back on the whole page is down and display nothing but the message 'Yikes! The page you requested couldn't be found.' and a link to this github to file an issue.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing without a project link and/or GitHub repository to reference. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
