### ISSUE TITLE
Repo cannot be imported - complaining about missing package.json file though it exists in the repo

### ISSUE THREAD

**Issue by dprathyusha252** [stackblitz/core#1283]

**Comment by sulco** [comment]
Hi @dprathyusha252, thanks for reaching out! Can you provide a link to the project where you run into this issue?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
