### ISSUE TITLE
Not able to push repo from Stackblitz to Github, after I deleted stackblitz OAuth from Github. Please help!

### ISSUE THREAD

**Issue by tushar8133** [stackblitz/core#1284]
Hi Team, as stated in the title of this ticket - I am able to login using github but can't push any old or newly created project on stackblitz to my github account.

When I click on "Connect repository" in stackblitz project, it gives a popup with title "Connect new GitHub repository" and after clicking on button "Create repo and push" it shows a spinner, loading infinite.

I have tried with Chrome and Firefox without any extension or addon.

I also tried to delete my account on stackblitz and re-create it, but I couldn't find any option.

Kindly help me out. It could be just OAuth issue related to my account. Please reset. Please help!

Thanks a lot in advance.

**Comment by SoerenSofke** [comment]
same issue here on my side

**Comment by bzh4bzh** [comment]
This is still an issue for me as well

**Comment by kc0tlh** [comment]
Hi @SoerenSofke, @tushar8133 , and @bzh4bzh, Apologies for the delayed response! There are 2 paths you can all try:

1) Try the [Github importer](https://stackblitz.com/codeflow) from [our new VS Code editor](https://stackblitz.com/codeflow) to access your repos

2) Delete your StackBlitz account [from this link](https://stackblitz.com/settings/profile) and start fresh. Please note: this will result in any projects stored in your StackBlitz account being deleted forever, so I reccomend option 1!

_Related Issue: #2473_
