### ISSUE TITLE
Use private bitbucket repo (component library) in order to create an editable private sample

### ISSUE THREAD

**Issue by tachojelev** [stackblitz/core#1286]
### Description

Hello guys, I have a private angular component library in bitbucket. Is there any way I can use Stackblitz in order to create editable private sample applications for Angular by using my private bitbucket component library? The idea is to be able to create samples with repos that are not publicly available on npm and be able to view and use them only within my organization? Does stackblitz work with anything else than github as well?

**Comment by tachojelev** [comment]
Hello guys, any details on this?

**Comment by kc0tlh** [comment]
@tachojelev this is now supported in both StackBlitz Enterprise and our [new Teams Plan](https://stackblitz.com/beta-teams-signup) (in beta currently). Please reach out to enterprise@stackblitz.com for more information!
