### ISSUE TITLE
stackblitz doesnt support # private fields

### ISSUE THREAD

**Issue by crh225** [stackblitz/core#1287]
https://www.typescriptlang.org/docs/handbook/classes.html#ecmascript-private-fields
![image](https://user-images.githubusercontent.com/19475195/89221442-e7449c00-d598-11ea-9e60-bfe9a2a61b57.png)

https://stackblitz.com/edit/angular-ivy-udrnka?file=src%2Fapp%2Fapp.component.ts

![image](https://user-images.githubusercontent.com/19475195/89221421-deec6100-d598-11ea-85b8-d92b235943e1.png)

**Comment by sulco** [comment]
Thanks for reporting this @crh225!
It should no longer be an issue :)
