### ISSUE TITLE
Not able to move cursor (up/down/left/right)in the source code using arrow keys on ipad pro

### ISSUE THREAD

**Issue by whoispankaj** [stackblitz/core#129]
Using a logitech slim combo keyboard with ipad pro 12.9 (1st generation).I am not able to move up and down the source code using the arrow keys on my logitech keyboard.The keyboard works fine and works well with other online tools like codepen, plunkr etc.

**Comment by EricSimons** [comment]
Good catch -- this is actually a limitation of the editing engine from VS Code (Monaco). Will add to our to-do list and see if we can fix this :)

**Comment by noodlemind** [comment]
I believe there is another open issue for the same issue (again from 2017). Can you please help with a fix so that I can use it on my iPad .

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
