### ISSUE TITLE
Project editing in Dashboard e.g. edit name, toggle private...

### ISSUE THREAD

**Issue by mikegoodstadt** [stackblitz/core#1290]
The Home page Project List is great but currently the only management available is "Delete" in the ellipsis menu to the right. Other editing features that would be useful here are:
- [ ] Edit Project name
- [ ] Toggle Project privacy

Please up-vote these Feature Requests in the [Discord #feature-voting channel](https://discord.com/channels/364486390102097930/681532218908082239)!

**Comment by purplem1lk** [comment]
Thank you for your patience - These are great ideas! This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
