### ISSUE TITLE
Stackblitz preview doesn't work on Chrome 84.0.4147.135 x64, errors shown in webconsole

### ISSUE THREAD

**Issue by AdrianRyniecBritenet** [stackblitz/core#1294]
I'm trying to run preview of example [Angular web app](https://stackblitz.com/angular/vmgxnnvnjyr), but no preview appears.
"Allow all cookies" option is turned on.

Web console errors are:

```
Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://vmgxnnvnjyr.angular.stackblitz.io/') with script ('https://vmgxnnvnjyr.angular.stackblitz.io/_sw_.js'): Worker disallowed  _relay_:1 

GET https://cdn.mxpnl.com/libs/mixpanel-2-latest.min.js net::ERR_BLOCKED_BY_CLIENT  analytics.min.js:14

GET https://js-agent.newrelic.com/nr-1173.min.js net::ERR_BLOCKED_BY_CLIENT vmgxnnvnjyr:8
```

In Firefox 79.0 x64 and Edge 84.0.522.61 x64 the preview pane works good.

**Comment by EricSimons** [comment]
Thank you for this detailed error message! Can you try clearing your browser cache and see if that fixes this? It seems like the latest version of chrome may be having issues w/ cached service workers. :(

**Comment by AndyOGo** [comment]
Same here.
App won't start up in Chrome, but in Firefox.
