### ISSUE TITLE
Cannot import projects from GitHub

### ISSUE THREAD

**Issue by nicolasj9** [stackblitz/core#1296]
Hello there,

i cannot import my repository in stackblitz from github with https://stackblitz.com/github/{username}/{repo}.
What can i do, in this case ?

![Capture](https://user-images.githubusercontent.com/48394978/91017726-e975a580-e5ee-11ea-9bd8-7ce34e3b58b6.PNG)

nicolasj9

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without the project link or the GitHub repository to reference and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
