### ISSUE TITLE
Deleting files using right click / context menu

### ISSUE THREAD

**Issue by BerkinAKKAYA** [stackblitz/core#1299]
## Problem

When i right click a file from the side menu and click **Delete** button, i see the `Are you sure you want to delete this?` message. I confirm but nothing happens. But if i click the trash icon instead of right clicking, i can delete it.

## Reproducing

Create a project and try deleting a file using right click. (I am using Windows 10 & Google Chrome 85.0.4183.83) (I produced this error on a Svelte project but same happens on React as well.)

This error message pops up when i click the Delete button:

![Image](https://user-images.githubusercontent.com/32297518/91992884-57337700-ed3d-11ea-89db-37bf3d664d8f.jpg)

**Comment by EricSimons** [comment]
Yikes, good catch- was able to repro this on prod. Getting a fix prioritized for EOW w/ @sulco- will circle back once online!

**Comment by BerkinAKKAYA** [comment]
Good luck!

**Comment by sulco** [comment]
Hey @BerkinAKKAYA, we've just pushed an update and it should no longer be an issue.

Thank you for reporting this and providing a detailed description!

**Comment by BerkinAKKAYA** [comment]
> Hey @BerkinAKKAYA, we've just pushed an update and it should no longer be an issue.
> 
> Thank you for reporting this and providing a detailed description! 

Thanks, i'm glad if it helped!
