### ISSUE TITLE
Custom Keyboard Shortcuts

### ISSUE THREAD

**Issue by jorgebucaran** [stackblitz/core#13]
I often use Ctrl+P to move the cursor to the line above the current line. In StackBlitz this opens up the command bar.

**Comment by EricSimons** [comment]
Love this idea. Are there any other shortcuts that you'd want to be able to remap out of curiosity?

**Comment by jbucaran** [comment]
Me, personally, ctrl+{a,p,n,h,b,e} is all I need!

I don't know if these are the emacs default keybindings, but I think they also work out of the box in vscode (my editor of choice).

**Comment by pestopancake** [comment]
> Love this idea. Are there any other shortcuts that you'd want to be able to remap out of curiosity?

 ctrl/cmd+w to close files! I use it in stackblitz by habit and instead it closes the tab

**Comment by PeterPanTW** [comment]
I'm StackBlitz news someday...

I want to ask a question, StackBlitz keyboard shortcuts in Mac 

recovery is ⌘ + z 
then cancel recovery typically is ⌘ + ?

THX!

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of any keyboard errors. Thank you! :)

**Comment by jugglingcats** [comment]
@purplem1lk, are keyboard shortcuts customizable now? Cannot find anything in the documentation or other github issues. Would be good to keep this issue open until the feature is available. Thanks
