### ISSUE TITLE
Angular: Lazy-loaded modules do not work

### ISSUE THREAD

**Issue by LayZeeDK** [stackblitz/core#130]
When I try to lazy-load a module using `loadChildren` in a route config, StackBlitz fails.

See example:
https://stackblitz.com/edit/angular-lazy-loading?file=app%2Fapp.module.ts

**Comment by EricSimons** [comment]
Good catch — we haven't added lazy loading in yet 😅  I'll start digging into this!

**Comment by LayZeeDK** [comment]
Tell me some good news, @EricSimons :-) How is it looking?

**Comment by EricSimons** [comment]
@LayZeeDK I know how to fix it! I'll get a fix in for this early next week :)

**Comment by tjpeden** [comment]
Any update on this?

**Comment by EricSimons** [comment]
@tjpeden I'm so sorry to keep you waiting on this — we had this batched in with an upcoming feature which is taking a bit longer than we expected, but I just split out lazy loading support and put it on prod! Your original project that you linked now works: https://stackblitz.com/edit/angular-lazy-loading?file=app%2Fapp.module.ts

Lmk if everything looks good on your end!

**Comment by LayZeeDK** [comment]
This is great news, @EricSimons! Thank you very much for all the effort you put into StackBlitz!

I will be using StackBlitz for a introductory Angular workshop for developers in my workplace. This means that I will not have to spend time introducing NPM, Webpack, or the Angular CLI just to teach them the basics. The fact that lazy loading now works makes it a great tool for most presentations, even advanced ones.

**Comment by DrMabuse23** [comment]
Hi i run into the same Problem i see your stackblitz @EricSimons and i dont understand why this not running [lazy-angular-example](https://stackblitz.com/edit/lazy-angular-example) maybe anyone can have a look at this please ?
