### ISSUE TITLE
Could not added the dependency library.

### ISSUE THREAD

**Issue by siddhartha-shi** [stackblitz/core#1300]
https://webrtc.ecl.ntt.com/en/documents/javascript-sdk.html
npm install skyway-js

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without the project link or the GitHub repository to reference and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
