### ISSUE TITLE
New projects' previews not working due to weird CORS policy

### ISSUE THREAD

**Issue by Bubbler-4** [stackblitz/core#1303]
Preview page doesn't show anything, and gives this error message in the console:

> Access to fetch at 'https://c.staticblitz.com/assets/preview-a0919d8cf3e3ab60f983b.js' from origin 'https://flurry.stackblitz.io' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://ball-demo.stackblitz.io' that is not equal to the supplied origin. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Tried with blank TS/JS and Angular, and all give the same error. Looks like the file `preview-a0919<whatever>.js` is necessary and shared between all projects, yet it is only allowed to be loaded in the ball demo?!

**Comment by kc0tlh** [comment]
This issue has been resolved!
