### ISSUE TITLE
node app can't open

### ISSUE THREAD

**Issue by xeavier** [stackblitz/core#1304]
nodejs server not opening

**Comment by kc0tlh** [comment]
@xeavier Node.js servers are not supported in StackBlitz as of 5/18/2021. Please stay tuned to our blog https://blog.stackblitz.com/ for an upcoming product announcement... 

![Ohhhhh](https://user-images.githubusercontent.com/1532264/118705001-8d7e2d00-b7cc-11eb-831a-18d007081a8b.jpg)
