### ISSUE TITLE
Clarity design projects broken

### ISSUE THREAD

**Issue by rogerfar** [stackblitz/core#1305]
I was trying to build this project:
https://stackblitz.com/edit/clarity-v3-light-theme

But it doesn't output anything, nothing obvious in the console, except for: 
Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('https://clarity-v3-light-theme.stackblitz.io/') with script ('https://clarity-v3-light-theme.stackblitz.io/_sw_.js'): An unknown error occurred when fetching the script.

But no output nor a message that compiling is happening.

**Comment by EricSimons** [comment]
Hi! This link is working for me- what browser are you using? Are you in incognito mode? Do you have any adblock/other extensions turned on? A screenshot of any errors in your console would also be super helpful

**Comment by rogerfar** [comment]
Oh yeah odd, I tried with Chrome and it works.

But I'm using Edge stable 85.0.564.51, and there it's just a blank screen, no errors or anything:

![image](https://user-images.githubusercontent.com/1142915/94049921-ce838600-fd92-11ea-9ab5-837d533f9a03.png)

I have my ad blockers disabled, even tried removing the extension completely.

It's not an issue across all blitzes, but this it the only one I found to be broken.

Also when I click Open in New Window it just hangs on Connecting to dev server...

**Comment by duzenko** [comment]
@EricSimons Try Firefox 32-bit
Fails on _two_ computers for me

**Comment by rogerfar** [comment]
@EricSimons sorry for the kick, but is there an update on this? I would love starting to use Stackblitz, but the multiple failing templates are making it very difficult.

**Comment by Anutrix** [comment]
Same issue on latest firefox

**Comment by kc0tlh** [comment]
Should be resolved as of [February 2023 StackBlitz browser support guidelines](https://developer.stackblitz.com/platform/webcontainers/browser-support).
