### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by bhavyata242001** [stackblitz/core#1309]
is this file is  already in my repository then why through a error that "missing package.json" !!

**Comment by sulco** [comment]
Hi @bhavyata242001, thanks for reaching out! Can you provide a link to the project where you run into this issue?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
