### ISSUE TITLE
AngularFire2 doesn't seem to work on stackblitz

### ISSUE THREAD

**Issue by pucherico** [stackblitz/core#131]
There is a template reference in the official AngularFire2 [github page](https://github.com/angular/angularfire2) to test Firebase throught AngularFire, however, after configuring the Firebase access it doen't work:

> Unexpected token export
> Evaluating https://unpkg.com/angularfire2@4.0.0-rc.2/database/index.js
> 

This is the template: https://stackblitz.com/edit/angular-2ed5zx?

**Comment by tommyd2377** [comment]
I couldn't get it working either. I kept getting an error with "module.Obj" or something like that. I remember reading somewhere from the developer that it isn't working because of an error with the angularfire packaging. But an update on the issue would be nice.

**Comment by EricSimons** [comment]
Hey all - really sorry about the delay, I've been sick the past week or so :( I actually got this fixed with the AngFire folks earlier this wk - can you try again now? (Make sure AngFire installed version is the latest)

**Comment by Toxicable** [comment]
This is working fine now, no more build errros, see here for confirmation https://stackblitz.com/edit/angular-template-firebase

**Comment by pucherico** [comment]
Great! For me it is working too.
Closing issue!

**Comment by thiago-glauco** [comment]
It is very interesting... If I just fork your template everything works well. If I just install the firebase and angularfire2 packages nothing works.
