### ISSUE TITLE
Branch selector Not Working

### ISSUE THREAD

**Issue by toneware** [stackblitz/core#1310]
I created a private Angular project in StackBlitz (SB) (https://stackblitz.com/edit/macs-dashboard) using the following git flow:
master -> dev -> feature/ip-auth

I did the dev in SB using the feature/ip-auth branch. 
I pushed to the branch from SB. Github updated properly. 
I created a PR in Github to merge feature/ip-auth -> dev.
I did a squash & merge of feature/ip-auth -> dev.
I let Github delete the feature/ip-auth branch.
So far, so good.

Now, however, I cannot get SB to change branches -- it consistently stays on the feature/ip-auth branch. This was the current branch when I did the merge. 
![2020-10-06 10_22_07-macs-dashboard - StackBlitz](https://user-images.githubusercontent.com/16153437/95223971-c9c1c780-07bf-11eb-9fd0-c98205eb0cc6.png)

If I click on the dropdown, it *does* show the proper branches available (dev & master), and it allows me to select either option. It will not, however, toggle to the selected branch.
![2020-10-06 10_22_22-macs-dashboard - StackBlitz](https://user-images.githubusercontent.com/16153437/95223992-cfb7a880-07bf-11eb-826e-bd682b8a0449.png)

It gets even weirder, because it actually loads a working branch, and my app runs as designed. I can't tell *which* branch it has loaded, as dev and feature/ip-auth have the same code (the merge was successful). I tried selecting master, and it says that it's loading/compiling the branch, but the app that gets loaded has the dev|feature/ip-auth changes, and the branch dropdown *still* says feature/ip-auth.

I tried the following, to no avail:

- Close & re-open Chrome, nav to SB,
- Close & re-open Chrome, nav to Github , click on the "edit w/ SB" link.
- Close Chrome, open incognito (Chrome) window.

I don't have Firefox loaded on this box, and IE won't even load SB, so I didn't try either of those.

Edit: When I refresh the project, I see this pop up:

![2020_10_06_10_48_51_macs_dashboard_StackBlitz](https://user-images.githubusercontent.com/16153437/95225695-ab5ccb80-07c1-11eb-91b6-a3ac22282895.png)

Once again, the selector still shows feature/ip-auth

**Comment by toneware** [comment]
I found a workaround:

- Delete the StackBlitz project.
- Import the GitHub repo (in my case, I imported a new branch that I had created off of dev).

This is far from ideal, but I am able to get back to work.

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Full writeup in Github issue #2473
