### ISSUE TITLE
styled-components not working properly in functional components

### ISSUE THREAD

**Issue by dlaraf** [stackblitz/core#1311]
In a new react project, after adding the styled-components dependency and adding the css , for example( from the official styled-components web):
```

import React from "react";
import "./style.css";
import styled from "styled-components";

export default function App() {
  const Wrapper = styled.div`
    padding: 4em;
    background: papayawhip;
`;

  const Title = styled.h1`
    font-size: 1.9em;
    text-align: center;
    color: palevioletred;
  `;
  return (
    <Wrapper>
      <Title>
        Title 
      </Title>
      <h1>Hello StackBlitz!</h1>
      <p>Start editing to see some magic happen :)</p>
    </Wrapper>
  );
}
```
Only tags h1 and div are applied. The css inside the styled-component has no effect. This styled-component version is working properly with other online/offline IDEs so i guess is something wrong parsing the special characters ` ` 

Example:
https://stackblitz.com/edit/react-7qyd49

**Comment by sulco** [comment]
Hi @dlaraf, thanks for posting the issue, and for the reproduction! I've noticed it uses React 16.x, so I've updated these dependencies, and it seems to have solved the bug (https://stackblitz.com/edit/react-m9vmcy-repro?file=src/App.js), so I'm closing it for now, but please feel free to reopen if this is still an issue.
