### ISSUE TITLE
StackBlitz fails to push new project to GitHub - Private Mail in github

### ISSUE THREAD

**Issue by JuergenRB** [stackblitz/core#1312]
When linking a new project, the repository is created in github, but the code is not pushed.

You can see an error message in the browser console:

![image](https://user-images.githubusercontent.com/22403655/95266217-0bd82100-0833-11eb-8d84-e0c1d9a19976.png)

Is it possible or is it planned to set the "..@users.noreply.github.com" mail address in StackBlitz for the github related operations?

**Comment by kc0tlh** [comment]
This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
