### ISSUE TITLE
would be nice to have friendlier error msg with more details:)

### ISSUE THREAD

**Issue by beni20** [stackblitz/core#1313]
would be nice to have more friendly error msg with more details regarding the failure/import issue...
to reproduce click https://stackblitz.com/github/SAP/spartacus

**Comment by EricSimons** [comment]
Eek! Thanks for letting us know. Will take a look when I’m at my computer tomorrow

**Comment by coder-Av** [comment]
ok

**Comment by coder-Av** [comment]
what is your name

**Comment by coder-Av** [comment]
when u are free

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
