### ISSUE TITLE
Update react-scripts in the create-react-app template

### ISSUE THREAD

**Issue by romannurik** [stackblitz/core#1314]
I *think* CSS modules support is failing in my CRA app when run on StackBlitz because the version of `react-scripts` is outdated (under 2.0.0). Updating my own react-scripts version in package.json doesn't fix it, leading me to believe StackBlitz is using an older, hidden version of that package when running the dev server.

**Comment by romannurik** [comment]
Repro example here: https://stackblitz.com/edit/cra-css-modules-bug

**Comment by EricSimons** [comment]
Thanks for bringing this to our attention @romannurik! Looping in @KwintenP who can get this enabled asap 👍

**Comment by sulco** [comment]
Hi @romannurik, thanks for the reproduction! I've noticed it uses React 16.x, so I've updated these dependencies, and it seems to have solved the bug (https://stackblitz.com/edit/cra-css-modules-bug-repro?file=src/index.js), so I'm closing it for now, but please feel free to reopen if this is still an issue.
