### ISSUE TITLE
node-sass seems to be still in use for angular projects

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [stackblitz/core#1315]
There are differences in compilation when you use the dart-sass compiler instead of node-sass. The Angular CLI start to use dart-sass instead of node-sass to build your Sass files from version 8 onwards. It looks like the Stackblitz still relies on node-sass. 

While the Angular CLI allows to use either one of them (dart sass vs node sass), I don't know how to this in Stackblitz. I tried it, similar to the angular cli, by installing sass compilers as a dev dependency, but this doesn't seem to work. 

Reproduction: 
You can see the error at https://stackblitz.com/edit/sass-use?file=src/styles.scss

I also noticed a related issue (#966), that was easier to workaround, but likely caused by the same origin.

**Comment by tobi-or-not-tobi** [comment]
Also note that node-sass has been deprecated now and is no longer recommended by its maintainers. See https://sass-lang.com/blog/libsass-is-deprecated

**Comment by sulco** [comment]
Hi @tobi-or-not-tobi, thanks for filing this issue and for the reproduction.
We're now using dart-sass by default, to it should no longer be an issue.
