### ISSUE TITLE
Issue with mini-mat-table-filter i want to apply it on nested array with array of objects

### ISSUE THREAD

**Issue by RizwanaHakeem** [stackblitz/core#1316]
Issue with mini-mat-table-filter i want to apply it on nested array with array of objects

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without a project link or GitHub repository to reference and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
