### ISSUE TITLE
Static Apps not getting deployed correctly to firebase

### ISSUE THREAD

**Issue by utkarshtrivedi** [stackblitz/core#1318]
When deploying an unchanged/modified static template using in-app firebase deploy extension, the final app doesn't load correctly. It is always blank, possibly due to faulty build.

A sample:
 
Project: https://stackblitz.com/edit/utkarshtestsite
Deployed at:
https://helloworld-f2ef5.firebaseapp.com/?99901

**Comment by benjamin324132** [comment]
i had the same issue

**Comment by EricSimons** [comment]
Hey all- thanks for letting us know about this. It looks like our static template isn't wired up properly for firebase deploys right now. I'm going to investigate and see if I can get a fix in, will circle back here with updates

**Comment by AndyEst** [comment]
Any updates on this? I'm trying to deploy a JavaScript project and I get only my HTML, no JS or CSS deployed
