### ISSUE TITLE
StackBlitz unusable on Firefox 81

### ISSUE THREAD

**Issue by m93a** [stackblitz/core#1324]
I use StackBlitz for quite some time, but recently it stopped working in Firefox, due to a CORS error:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://v.staticblitz.com/files/standard-libs.json. (Reason: CORS request did not succeed).
```

Because of this error, the website preview doesn't show at all, even if it does in other browsers.

**Comment by sulco** [comment]
Hi @m93a, apologies for getting back to you only now - do you still experience this issue?

**Comment by m93a** [comment]
Hey!
I've tested it today in Firefox 84 and everything works as expected. Thanks for the fix! 😁️
