### ISSUE TITLE
StackBlitz does not work in IE 11

### ISSUE THREAD

**Issue by Lonli-Lokli** [stackblitz/core#1325]
Thats duplicate of https://github.com/stackblitz/core/issues/461 but nobody cares.

Stackblitz does not work in IE 11.

Steps to reproduce:

Open IE 11.
Load the following URL - https://stackblitz.com/edit/ie-11-test which is the default Angular template.

**Comment by purplem1lk** [comment]
Hey there - Thanks for your patience! I just confirmed with our dev team that we will not be supporting IE11 so this issue will be closed accordingly. Feedback is always appreciated. Thank you!
