### ISSUE TITLE
a simple {{ variable }} is not updating

### ISSUE THREAD

**Issue by shivamSharmaMWP** [stackblitz/core#1326]
a simple updating is not working.

https://stackblitz.com/edit/refresh-g3smfb

i have added a simple html thing {{ updating }} . and started a setInterval so that value keep on updating. but it is not reflecting this. on the console it is properly printing values but no on ui.

**Comment by sulco** [comment]
Hi, @shivamSharmaMWP! 

Because you are passing a `function` to the `setInterval`, when it runs, the [context](https://www.learn-js.org/en/Function_Context) is lost. You can fix it by changing the function to an arrow function, so replace this:

```javascript
constructor() {
    setInterval(function() {
      console.log(" running)");
      this.updating = Math.random();
    }, 500);
  }
```
with this:
```javascript
constructor() {
    setInterval(() => {
      console.log(" running)");
      this.updating = Math.random();
    }, 500);
  }
```
