### ISSUE TITLE
Angular generator not working in self created directory

### ISSUE THREAD

**Issue by ghost** [stackblitz/core#1327]
I wanted to create a component with angular generator inside a new self-created directory in e.g. app/test (test is my created directory). After entering the name of the component I wanted to press enter. But nothing happened. Creating new components in the pre created dirs app and pages worked fine.

I am using an iPad Pro with the magic keyboard and Safari.

**Comment by juliusn** [comment]
Tested on Mac OS. Issue is reproducable with Safari, not with Chrome.
