### ISSUE TITLE
Support linking to CSS files in index.html

### ISSUE THREAD

**Issue by ricky11** [stackblitz/core#133]
<link href="style.css" rel="stylesheet"/>

in a html file, when i link a css file(example above) the css doesn't work.  it seems to only work inline , but not from another file.

**Comment by EricSimons** [comment]
@ricky11 good catch! We actually don't support css imports in html files right now, but you can get around this by adding external dependencies to CDN urls or using `@import './file.css'` inside of an existing CSS file. Alternatively if you're building an Angular project, you can specify which CSS files in your project should be added to the page using the angular-cli.json (which you can see in action in the [base Angular project](https://stackblitz.com/edit/angular)).

**Comment by EricSimons** [comment]
We're working on adding normal CSS link tag support though, so I'm going to leave this issue open until we implement it 👍

**Comment by ricky11** [comment]
great thanks. unfortunately it is my own css file that is not listed on cdns...  so ill subscribe to this thread for updates.

**Comment by EricSimons** [comment]
@ricky11 what type of project is it for (react, angular)? Because both of them support importing local stylesheets in various ways - happy to help get you pointed in the right direction!

**Comment by ricky11** [comment]
it is a vue project, so im linking the the vue file from a cdn, but linking my css to a local file on stackblitz doesnt work as yet.

**Comment by AbelVM** [comment]
wow, still unresolved

**Comment by Neutrino-Sunset** [comment]
Yeah this is damn wierd. I fire up an online HTML editor and the most basic stuff imaginable doesn't work the way it should, and provides no indication of why not.

It's not a good experience. Surely this can't be that difficult to fix.

**Comment by AlfredGreem** [comment]
This is still unsolved

**Comment by printBvrtek** [comment]
Still waiting

**Comment by whoisYeshua** [comment]
Any updates?

**Comment by burrijw** [comment]
How is this not supported??

**Comment by hyper-pluto** [comment]
annnnnnnnnd i think i am done with stackblitz

**Comment by Guilherhast** [comment]
I've created a workaround to load the css:

```js
//This javascript should not exist.
//It is here because there is something wrong with the normal css

function injectCss(file = 'style.css') {
  fetch(file)
    .then((response) => response.text())
    .then((data) => {
      let stl = document.createElement('style');
      stl.innerHTML = data;
      document.head.appendChild(stl);
    });
}

function injectAll() {
  let links = document.getElementsByTagName('link');
  for (stl of links) {
    injectCss(stl.href);
  }
}

window.onload = injectAll;

```

It loads as an internal css. But if you just need to get it working thats maybe a good ideia.

**Comment by NITA-Ramesh** [comment]
> Support linking to CSS files in index.html [on 14 Sep 2017](#event-1247996979)

Still not working for me.

**Comment by NITA-Ramesh** [comment]
Ahh! it's 2022 and still this basic functionality is not there in stackblitz.

**Comment by geoyws** [comment]
You have to delete the `<DOCTYPE! html>` at the top and then it will work. But this isn't ideal for my case as I'm trying to teach kids how to code and this will confuse them.

**Comment by NITA-Ramesh** [comment]
> You have to delete the `<DOCTYPE! html>` at the top and then it will work. But this isn't ideal for my case as I'm trying to teach kids how to code and this will confuse them. Perhaps just let people type out the doctype but just remove it before compiling to show you know, as a temporary solution.

Ahh still not working ? can you just give me an example where is it working?

**Comment by Madmanden** [comment]
> You have to delete the `<DOCTYPE! html>` at the top and then it will work. But this isn't ideal for my case as I'm trying to teach kids how to code and this will confuse them. Perhaps just let people type out the doctype but just remove it before compiling to show you know, as a temporary solution.

Thanks, that worked for me!

**Comment by therealbluepandabear** [comment]
Ridiculous how this has not been implemented yet.

**Comment by vsreelekshmi** [comment]
Still unresolved

**Comment by phegorez** [comment]
> Still unresolved.
> 
> Found a solution that works. Import the CSS file in **index.js**. `import './style.css'; ` Working example: [https://counter18.stackblitz.io](https://stackblitz.com/edit/counter18?file=README.md,index.html,index.js,style.css)

Thank for solution that work for me.

**Comment by ofergoli** [comment]
Any updates on that?

**Comment by ricky11** [comment]
I started this thread 5 years ago. 

Eric congrats on SB became a big success.  

Looks like importing in to a .js is the way to go.` import './style.css'; `

Let's close the issue @EricSimons

**Comment by ofergoli** [comment]
5 years and still not resolved 🥴

**Comment by Neutrino-Sunset** [comment]
> Let's close the issue @EricSimons

How about flipping fixing it instead?

**Comment by samdenty** [comment]
If you use a template based on `node.new` (or one of the fullstack templates), then it should work

https://stackblitz.com/edit/static-node?file=package.json

**Comment by ofergoli** [comment]
@samdenty Thanks!

**Comment by daledesilva** [comment]
Holy moly. I just started switching from codesandbox because I liked StackBlitz better.... but how can it not support the most basic linking an html needs to do?

**Comment by BlazeBiz** [comment]
Ditto here. Looking to replace CodePen because there are more options for hiding things when I embed. But the length of this thread, which is asking for the most rudimentary fix, is a little scary for me. Is this product actually supported?

**Comment by burrijw** [comment]
@BlazeBiz -- I've just started using codesandbox instead. 🤷🏻‍♂️

**Comment by Lonli-Lokli** [comment]
Is it possible to use styles from node_modules?

**Comment by woodcock3** [comment]
I've been trying out Stackblitz for the last two days. It's ridiculous that this has not been fixed since 2017. This is a dealbreaker for me. I'm going to look elsewhere, which is shame as I like the rest of the DX.

**Comment by EricSimons** [comment]
Hey all- just want to share that this _is_ solved with our nodejs based project presets that came out in May '21. For example, if you go to [vite.new](https://vite.new) it'll spin up a new Vite based project where you can link CSS files & more.

Closing this accordingly- thanks for your patience everyone.

**Comment by Neutrino-Sunset** [comment]
The whole point of the thread is that it should work with plain HTML files.

**Comment by Lonli-Lokli** [comment]
@EricSimons can you please provide examples (or add to the documentation) samples of how to use scss/less/css files from node_modules for react/angular apps?

**Comment by Andrew-web-coder** [comment]
Does not work for me using vanilla template

**Comment by Neutrino-Sunset** [comment]
Don't waste your breath. Look when this was opened, 2017. They couldn't care less that it doesn't work.

**Comment by woodcox** [comment]
I actually got the css working with the new 11ty dev server. I wonder if you have to use a server built on Node?

**Comment by simonpai** [comment]
@EricSimons If we want it to work with vanilla template, should we create another issue for that?

**Comment by gokhantaskan** [comment]
One way to use CSS is by using the `javascript` template:

```html
<!-- index.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Title</title>
    <script src="./index.js"></script>
  </head>
  <body>
  </body>
</html>
```

```js
// index.js
import './index.css';
```

```css
/* index.css */
*, *::before, *::after {
  box-sizing: border-box;
}
```
