### ISSUE TITLE
Bad colors in the Share dialog (Light theme)

### ISSUE THREAD

**Issue by duzenko** [stackblitz/core#1331]
The input content is virtually invisible on 'regular' dim computer monitors

![image](https://user-images.githubusercontent.com/1481807/99142507-25ecf680-265e-11eb-8d24-6a4e00ac0611.png)

Compare to Dark theme:

![image](https://user-images.githubusercontent.com/1481807/99142502-19689e00-265e-11eb-831d-b7820e58bb81.png)

**Comment by sulco** [comment]
Thank you @duzenko for submitting the issue!
We've just pushed an update that should make this look better :)
