### ISSUE TITLE
Project not available

### ISSUE THREAD

**Issue by kewo22** [stackblitz/core#1333]
Below named project not available 
**angular-multiple-obj--key-filtering**

![image](https://user-images.githubusercontent.com/33512309/99882384-0d747180-2c46-11eb-84e0-ba8b0d6c6b40.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
