### ISSUE TITLE
On Angular projects, does tsconfig.json actually do anything?

### ISSUE THREAD

**Issue by Richardinho** [stackblitz/core#1334]
In Angular projects, the `tsconfig.json` is supposed to contain configuration for Typescript, but in some of my experiments, it doesn't appear to change anything. I also noticed that the `angular.json` file doesn't actually reference it - it references `tsconfig.app.json` instead.

This is my test code:
```
<input (input)="onChange($event.target.value)">
```
This fails with the error `Property 'value' does not exist on type 'EventTarget'.`
Testing the same code on an Angular install on my own machine, I get the same error when the angular compiler property `strictDomEventTypes` is set to true, and the error goes away with it is set to `false`. This is in accordance with Angular's documentation https://angular.io/guide/template-typecheck.
However, setting this value to `false` in the `tsconfig.json` file in a Stackblitz application makes no difference.
So is this file actually doing anything?

**Comment by fvsch** [comment]
Hi @Richardinho. Thanks for the report!

It seems you ran into this issue: #1856.
We'll address this problem as part of #1856, so I’ll close this one as a duplicate for now.
