### ISSUE TITLE
"Connect repository" action fails with 401 Unauthorized error

### ISSUE THREAD

**Issue by AvneeshSarwate** [stackblitz/core#1335]
When I try to create a new repository from Stackblitz, I get the 401 Unauthorized error, `Uncaught (in promise) HttpError: Bad credentials`. Furthermore, I used the Sign-in with Github feature when creating my account, and the associated Stackblitz app linked to my Github account only has permission to `Access user email addresses (read-only)`. I am on a free tier account.

**Comment by alannungaray** [comment]
Same issue with my account

**Comment by alannungaray** [comment]
I found a workaround, disable all restrict tracker of your browser, logout and create a new stackblitz project (As guess) and click on git  connect button then will appear an authorization windows and there you go.

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473
