### ISSUE TITLE
Repo not working

### ISSUE THREAD

**Issue by Danieliverant** [stackblitz/core#1338]
Hi, I had this repo working for a month now:
https://stackblitz.com/github/danieliverant/ng-dl

and now I get "The dependencies for this project couldn't be resolved."

I haven't changed anything except updating the version of my own package (that inside that project, also)

package json:
https://github.com/Danieliverant/ng-dl/blob/master/package.json

**Comment by sulco** [comment]
I've just checked the project you've linked and it doesn't seem to happen anymore.
Closing it for now but feel free to reopen if you still experience the issue.
