### ISSUE TITLE
Couldn't import public repo

### ISSUE THREAD

**Issue by Sudharma51879360** [stackblitz/core#1339]

**Comment by sulco** [comment]
@Sudharma51879360 can you provide the link to the repo?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
