### ISSUE TITLE
file missing

### ISSUE THREAD

**Issue by payalparate** [stackblitz/core#1340]
package.json file is shown missing inspite it is available there.

**Comment by sulco** [comment]
Hi @payalparate! Can you provide a link to the project where you run into this issue?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
