### ISSUE TITLE
Yikes! The page you requested couldn't be found.

### ISSUE THREAD

**Issue by Deepthi0904** [stackblitz/core#1341]
https://stackblitz.com/edit/react-c4ykfw?file=src%2Fcomponents%2Ffnlmultiboxes.js

This page im requesting is not found

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without a GitHub repository to reference the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link and corresponding GitHub repository. Thank you! :)
