### ISSUE TITLE
svelte basic examples do not work

### ISSUE THREAD

**Issue by spierala** [stackblitz/core#1344]
See simple hello world here:
https://stackblitz.com/edit/svelte-hello-world?file=components/App.html

Code is copy pasted from here:
https://svelte.dev/

But it does not seem to work:
![image](https://user-images.githubusercontent.com/1272446/102198282-7c9a5a00-3ec2-11eb-8c60-8bcb3f1ec537.png)

Is there something special about how the view data has to be provided?
I see in the default template of the stackblitz svelte this:
```
  export default {
    data() {
      return {
        count: 0
      };
    }
  };
```
It would be strange to be forced to provide the viewData like this.

codesandbox can do it as expected:
https://codesandbox.io/s/sweet-glade-55lfj?file=/App.svelte

**Comment by Marr11317** [comment]
This is because it's svelte 2 syntax. See #1048 for details
