### ISSUE TITLE
Vue and React Support

### ISSUE THREAD

**Issue by njokdan** [stackblitz/core#1345]
Hi! this is Daniel from Nigeria, discover this on twitter, runs well with Angular but you are yet to support Vue and React, I mean running code from Git hub repository.

Thanks

**Comment by EricSimons** [comment]
Hi Daniel- thanks for creating this issue! We're going to prioritize and address this for the team. I'm not sure about an ETA right now but I can circle back with an update asap.

**Comment by njokdan** [comment]
Hi Eric - Cool to hear from you. I will be expecting.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If you have any questions, feel free to tag me or ask to reopen this issue. Thank you! :)
