### ISSUE TITLE
Add Vue 3 with TypeScript 

### ISSUE THREAD

**Issue by carballosa** [stackblitz/core#1349]
Please add the option of using TypeScript in Vue 3 projects

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If you have any questions, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by kaokei** [comment]
It seems that it's still not work with Vue 3 and Typescript. 😞
