### ISSUE TITLE
Save project as draft initially

### ISSUE THREAD

**Issue by aneguzman** [stackblitz/core#135]
This tool is amazing, thanks!!

Every time I select a project type: Angular, React or Ionic, the app creates a new project into my account. It would be nice if this new project is only created as a draft and not as a real project since sometimes I only want to test something simple and do not want to have those changes in my account.

Thanks in advance!!

**Comment by EricSimons** [comment]
Thanks for the kind words @aneguzman, we really appreciate it :) 

Totally agree with your feedback here — we're actually working on a fix for this and it should be out within the next week or two!

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
