### ISSUE TITLE
"Error: Preset not sepcified in configuration" when trying to launch a public version

### ISSUE THREAD

**Issue by ondras** [stackblitz/core#1354]
Hi,

I do not seem to be able to launch the public hosted version of my app (https://piano-chords.stackblitz.io/). The console shows the error message mentioned in this issue's title (including the typo). Happens in Firefox and Chrome.

**Comment by purplem1lk** [comment]
Thank you for your patience - Attached is a screenshot of what I see when I click your project link. I ran this in Chrome and did not see any errors in the console. If this issue persists, feel free to tag me or ask to reopen this issue with your project editor link and a screenshot of your errors. Thank you! :)

![Screen Shot 2021-05-23 at 6 23 29 PM](https://user-images.githubusercontent.com/49956513/119278554-ff52de00-bbf3-11eb-8a93-4450718b0516.png)
