### ISSUE TITLE
Accidentally pulled from GitHub which results in deletion of my project files

### ISSUE THREAD

**Issue by abdul-rehman-2050** [stackblitz/core#1356]
I created some changes and new files in the project. Then I tried to commit to the GitHub. But if rejected with error. Then I pressed Pull button of the github repo. It changes my folder structure and take me to the old point(last commit). Now I had lost all my changes including new files. How can I recover or view the local project commits so that I could switch to the last commit? Or What is the other way to recover my files?

**Comment by yuwash** [comment]
The “undo” function might work (Ctrl + Z), but the unwarned discarding of local changes on a git pull does seem suboptimal

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473
