### ISSUE TITLE
Importing scss files from node_modules results with error

### ISSUE THREAD

**Issue by HristoP96** [stackblitz/core#1359]
### Description

Having scss @ import statement from a node_modules library results with **NoSuchMethodError: method not found: 'source' on null** 

### Stackblitz Project - [scss-nm-import-error](https://stackblitz.com/edit/scss-nm-import-error?file=src%2Fstyles.scss)

**Comment by apai4** [comment]
@HristoP96 sorry about this! We released an update yesterday made some changes to how scss was being compiled which introduced this issue. The update has been rolled back now and the node_modules scss imports should be working again. Sorry for any inconvenience this has caused, and thanks for reporting the issue!

**Comment by HristoP96** [comment]
@apai4 Everything seems to be fine now with the scss node_modules imports, thank you for the fast reaction :) !

**Comment by komarovalexander** [comment]
Hi I'm also facing with similar issue https://stackblitz.com/edit/table-export-ts?file=Demo.tsx 
`NoSuchMethodError: method not found: 'children' on null`

**Comment by ConnorAhern** [comment]
I'm also having this issue now.

**Comment by ConnorAhern** [comment]
I determined that the issue was that I was missing a package that I my project requires. My bad for bothering y'all.
