### ISSUE TITLE
NaN is "null" in console

### ISSUE THREAD

**Issue by MarsiBarsi** [stackblitz/core#1363]
Hey!

Here is an Angular StackBlitz:
https://stackblitz.com/edit/angular-nan-console-issue?file=src/app/app.component.ts

I log `NaN` into my console and get a `null` message.

![image](https://user-images.githubusercontent.com/10106368/104700030-a09cc580-5724-11eb-909e-6fb6e15250c0.png)

**Expected:**

I will see `NaN`

**Comment by kc0tlh** [comment]
This issue is resolved!
