### ISSUE TITLE
Highlighting of TS errors in the file explorer

### ISSUE THREAD

**Issue by willi84** [stackblitz/core#1365]
When you do an error and you are not in the file you can't see it like you usually do in VS Code with a red hightlihted file-name

**Problem:**
you will miss an error, when you do e.g. a renaming or delete sth. which is not always related to the output with an error

**wished behaviour:**
![image](https://user-images.githubusercontent.com/6207308/104737724-e9647680-5744-11eb-90f6-64107d3bb7fe.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If you have any questions, feel free to tag me or ask to reopen this issue. Thank you! :)
