### ISSUE TITLE
Something went wrong with this repository on attempted import

### ISSUE THREAD

**Issue by Tommy-Wilkinson** [stackblitz/core#1366]
I just committed from visual studio to github and tried to download into a stackblitz project. The window stuck at the Importing from Github animation for nearly 15 minutes. I refreshed because it's a relatively small project so it shouldn't take that long. Now I constantly get an error saying there is an issue with the repository. I know there isn't though because it's working just fine in visual studio code.

**Comment by kc0tlh** [comment]
This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
