### ISSUE TITLE
npm packages - @angular/material and @angular/cdk keeps reverting back to beta.8

### ISSUE THREAD

**Issue by brijmcq** [stackblitz/core#137]
I have a project here https://stackblitz.com/edit/angular-material-template. I updated this many times before to beta.10 and it just keeps reverting back to beta.8

**Comment by EricSimons** [comment]
@brijmcq I just tried updating your project deps to beta.10 and it seems to work fine - can you paste the following in the "install dependencies" field and lmk if it doesn't work? `@angular/material @angular/cdk`

**Comment by EricSimons** [comment]
Btw, we now support the angular-cli.json config for global styles + Sass support which allows you to theme Angular material live. Here's the demo project for it: https://stackblitz.com/edit/angular-material

**Comment by brijmcq** [comment]
@EricSimons  Yes it will update to beta.10, but after some hours ( or days if I need to fork from it ) it will revert back in beta.8 and that's what I experience in the last few days. Probably something to do with your updates on the project?

**Comment by brijmcq** [comment]
@EricSimons cool that you now have the angular-cli.json! 

Just check my other projects ( fork from my material template ) and it looks fine now. I'll probably monitor this for a few days just to be sure and will close this issue.

Thanks for the reply!

**Comment by brijmcq** [comment]
@EricSimons  just a quick question though, is it possible to reference the pre-built themes from @angular/material something like this @import '~@angular/material/prebuilt-themes/deeppurple-amber.css'; ?

**Comment by EricSimons** [comment]
@brijmcq yup that works! Though the path would need to include the package name it like this: `@import "~@angular/material/prebuilt-themes/indigo-pink.css";`
