### ISSUE TITLE
Let's bump Angular version in Ionic starter

### ISSUE THREAD

**Issue by MarsiBarsi** [stackblitz/core#1373]
If I choose Ionic in "New project" menu, I get a starter with Angular 5 that is 3 years old. Let's update it :)

**Comment by MarsiBarsi** [comment]
Maybe it can be useful for you. We solved all migrations problems and started Ionic with the actual Angular version here:
https://stackblitz.com/edit/taiga-ui-ionic

**Comment by kc0tlh** [comment]
IONIC projects should just work at this point 🎉

Here are some [known good IONIC v7 templates](https://twitter.com/aaronksaunders/status/1694037022426509709) for StackBlitz.

And here are the docs on importing repos into our new VS Code editor: https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide

_Consolidated Ionic Issue: #219_
