### ISSUE TITLE
No decent sans-serif monospaced editor font seems to work

### ISSUE THREAD

**Issue by Neutrino-Sunset** [stackblitz/core#1377]
I can't find a decent sans-serif monospaced editor font. Lucida Console is the only one I've managed to get to work at all, and it only works with `font-weight: normal` which is so heavy as to look practically bold.

Is this something that could be improved?

**Comment by sulco** [comment]
Hi @Neutrino-Sunset, thanks for opening an issue for this! You're totally right, there are some great monospace fonts out there, and we should allow at least some choice. I'm going to make sure we take care of adding it as soon as possible.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If you have any questions, feel free to tag me or ask to reopen this issue. Thank you! :)
