### ISSUE TITLE
React on Rails error for existing stackblitz 

### ISSUE THREAD

**Issue by hippee-lee** [stackblitz/core#1378]
We had some existing stackblitzes for various versions of our components [here](https://stackblitz.com/@clr-team).

When navigating to any one of them there is an error: 
![Screen Shot 2021-02-01 at 2 41 22 PM](https://user-images.githubusercontent.com/433692/106527328-f058ec00-649b-11eb-9f18-d2b1cca3ee76.png)

**Comment by JStuve** [comment]
Have the same issue when new and event existing projects.

**Comment by sulco** [comment]
Thanks for reporting @hippee-lee! Fix on is its way!

**Comment by sulco** [comment]
Should be better now – let me know @hippee-lee , @JStuve if the fix worked for you!

**Comment by JStuve** [comment]
@sulco it's back up! Thank you, much appreciated!
