### ISSUE TITLE
Need to run locally !

### ISSUE THREAD

**Issue by TheRakeshPurohit** [stackblitz/core#1379]
Can anyone help with how to use this repo on local machine ??

**Comment by kc0tlh** [comment]
![image](https://user-images.githubusercontent.com/1532264/118675880-cfe54100-b7af-11eb-802c-c4149a11fbb6.png)

You can download the project to local as demonstrated here ^

You will then need to ensure you have the local environment setup to run the project (for example you may need a Node.js server, an NPM package manager to resolve dependencies, etc.) If you need assistance with setting up a local environment for a specific framework, I recommend the forums (for example Vue.js has a great community here: https://forum.vuejs.org/).

**Comment by TheRakeshPurohit** [comment]
Thanks a lot!
