### ISSUE TITLE
feature-request: import from desktop or plunker

### ISSUE THREAD

**Issue by sreekumarp** [stackblitz/core#138]

**Comment by aat-antoine** [comment]
For Plunker an issue already exists ==> #38

**Comment by EricSimons** [comment]
Thanks for helping respond to issues @aat-antoine, I really appreciate it! :)

@sreekumarp would love to learn what you mean by "import from desktop" — we currently support dragging & dropping files/folders from desktop onto stackblitz, would be great to see if there's anything else we could do to make that easier!

**Comment by sreekumarp** [comment]
I think we can close this one...

@EricSimons : I was not aware of drag and drop a folder from desktop feature.
