### ISSUE TITLE
StackBlitz/GitHub Login/Auth error

### ISSUE THREAD

**Issue by KennyRay549** [stackblitz/core#1385]
Cannot log into GitHub from StackBlitz redirect: Get
"Sorry, that page is missing" error.
![StackBlitz_Login_Failure](https://user-images.githubusercontent.com/13022294/107149614-29231600-691f-11eb-8304-1a8c21729ec4.jpg)

**Comment by xenoplayed** [comment]
same here. I removed permission and tried it again, but get still the same error.

**Comment by sulco** [comment]
Thanks for reporting @KennyRay549 and sorry for your trouble. We are tracking this issue here #1369, so I'm closing this one as a duplicate.
