### ISSUE TITLE
css @import doesn't seem to work

### ISSUE THREAD

**Issue by mkkaushiksjce** [stackblitz/core#1386]
I'm trying to use @import url('https://fonts.googleapis.com/css?family=Roboto:300,400'); in a css/less file but it says 

Error: ENOENT: No such file or directory., '/is.com/css?family=Roboto:300,400'

**Comment by sulco** [comment]
Hi @mkkaushiksjce, I've just checked this on our various projects and it seems to work (for example: https://stackblitz.com/edit/google-fonts-import-repro?file=style.css)

Can you provide a link to your project where this is breaking? It will allow us to pinpoint the issue faster :)

**Comment by mkkaushiksjce** [comment]
Hello Sir,

Thanks for the quick reply, here is the link https://stackblitz.com/edit/hawkeye-task-manager?file=src%2FComponents%2FfloatingMenu%2FfloatingMenu.less

**Comment by mkkaushiksjce** [comment]
This is a react started project

**Comment by sulco** [comment]
Thank you for the repro!

Looks like in the case of importing CSS from a LESS file you need to use a slightly changed syntax:
```
@import (css) url(https://fonts.googleapis.com/css?family=Roboto:300, 400);
```
(notice the `(css)` prefix and the lack of quotes around the URL)

Here's the working fork of your project:
https://stackblitz.com/edit/hawkeye-task-manager-less-import-repro?file=src/Components/floatingMenu/floatingMenu.less

Let me know if that fixes your issue :)

**Comment by mkkaushiksjce** [comment]
Thank you so much. The changed syntax works

`@import (css)
  url(https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap);

* {
  font-family: "Roboto";
}`

**Comment by sulco** [comment]
Awesome! Glad it helped :)
