### ISSUE TITLE
Absolute references

### ISSUE THREAD

**Issue by JikkuJose** [stackblitz/core#139]
Please give ability to set absolute paths so that those folders can be accessed from anywhere within the project. Its pretty hard to provide relative urls like this:
```
import {
  Header,
  Footer
} from '../../../../Shared'
```

**Comment by EricSimons** [comment]
Totally - I'm thinking we can support this using ~ like webpack does (i.e. `~app/Shared`). What do you think?

**Comment by JikkuJose** [comment]
Won't it be better to have a field which will be injected to the package.json?

For instance `NODE_PATH` field can take in: `src/:src/assets` and inject into `package.json` like:

```
  ...
  "start": "NODE_PATH=src/:src/assets react-scripts start",
  ...
```

**Comment by JikkuJose** [comment]
Take a look at this project: https://stackblitz.com/edit/standard-template?file=Demo%2Fcomponents%2FView.js

Its very hard to have the relative paths done.

**Comment by EricSimons** [comment]
@JikkuJose fair enough — I'm gonna look into adding absolute path support :)

**Comment by Kolyunya** [comment]
Are there any docs for that new technology? It's not really clear how to use it.
