### ISSUE TITLE
Can't import `memoizee`

### ISSUE THREAD

**Issue by garronej** [stackblitz/core#1390]
Hi,

The famous library [`memoizee`](https://www.npmjs.com/package/memoizee) doesn't work on Stackblitz.

Example: [Blank project where only memoizee is imported](https://stackblitz.com/edit/typescript-aqaf5d?file=index.ts)

This is what we get: 

![image](https://user-images.githubusercontent.com/6702424/107986414-4bc2c800-6fcc-11eb-8d8b-bc6e518f8aad.png)

Thank you for your great work,

Best regards

**Comment by alexzuza** [comment]
The problem here is that `memoizee` has a dependency on `es5-ext` library.

`es5-ext` uses `#` path in its file structure.

https://cdn.jsdelivr.net/npm/es5-ext@0.10.53/string/#/

![изображение](https://user-images.githubusercontent.com/4223314/108589797-99975180-7379-11eb-928d-c23cad16af54.png)


Stackblitz tries to resolve path from this import

```
contains        = require("es5-ext/string/#/contains");
```

Which is basically request to https://cdn.jsdelivr.net/npm/es5-ext@0.10.53/string/#/contains.js

As you might notice we can't use `#` in url since it is considered as a hash so Stackbliz returns html from that page.

But js can't execute html string passed to `eval`

**Comment by valerii15298** [comment]
Hello, stil the same issue. I cannot import memoizee into my project, logs: `> node_modules/.pnpm/memoizee@0.4.15/node_modules/memoizee/normalizers/get-1.js:3:22: error: Could not read from file: C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.p
npm\es5-ext@0.10.53\node_modules\es5-ext\array\index.js#\e-index-of
    3 │ var indexOf = require("es5-ext/array/#/e-index-of");
      ╵                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/d@1.0.1/node_modules/d/index.js:7:30: error: Could not read from file: C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\es5-ext@0.10.53\node_mo
dules\es5-ext\string\index.js#\contains
    7 │   , contains        = require("es5-ext/string/#/contains");
      ╵                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~

error when starting dev server:
Error: Build failed with 2 errors:
node_modules/.pnpm/d@1.0.1/node_modules/d/index.js:7:30: error: Could not read from file: C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\es5-ext@0.10.53\node_modul
es\es5-ext\string\index.js#\contains
node_modules/.pnpm/memoizee@0.4.15/node_modules/memoizee/normalizers/get-1.js:3:22: error: Could not read from file: C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm
\es5-ext@0.10.53\node_modules\es5-ext\array\index.js#\e-index-of
    at failureErrorWithLog (C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:1451:15)
    at C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:1131:28
    at runOnEndCallbacks (C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:921:63)
    at buildResponseToResult (C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:1129:7)
    at C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:1238:14
    at C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:609:9
    at handleIncomingPacket (C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:706:9)
    at Socket.readFromStdout (C:\Users\valer\OneDrive\Desktop\projects\drawflow-vite\node_modules\.pnpm\esbuild@0.12.24\node_modules\esbuild\lib\main.js:576:7)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
 ERROR  Command failed with exit code 1.`
