### ISSUE TITLE
How to change a double quote to a single quote?

### ISSUE THREAD

**Issue by zyxbest** [stackblitz/core#1391]
Double quotes are now used by default.
But I prefer the single-quote code style.
How to use single quotes instead of double quotes in `stackblitz` settings?

**Comment by alexzuza** [comment]
Create a `.prettierrc` file like
```
{
  "singleQuote": true
}
```
and that's it.

For more options please refer the documentation https://prettier.io/docs/en/options.html

Here is an example https://stackblitz.com/edit/angular-ivy-3yxh5y?file=.prettierrc

**Comment by zyxbest** [comment]
@alexzuza Thanks a lot for your detailed reply!
