### ISSUE TITLE
Invalid hook call. Hooks can only be called inside of the body of a function component error. Works fine on Codesandbox

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/core#1392]
I have a project on Codesandbox → https://codesandbox.io/s/mobx-theme-color-change-p1j6r?file=/src/App.tsx

I tried porting it to Stackblitz → https://stackblitz.com/edit/mobx-theme-color-change?file=index.tsx

But it just doesn't run. It gives weird hooks error but I have basically copy-pasted it. Why it doesn't work?

On other note: An import from Codesandbox feature would be nice as I've noticed Stackblitz is superior in speed. Codesandbox feels too slow in comparison.

**Comment by sulco** [comment]
Hi @deadcoder0904! Thank you for reaching out, and for your kind words - we do focus on being as fast as it's technically possible :) I will take the issue to our team, see what can be done about it, and get back to you!
