### ISSUE TITLE
Importing a static project from github is not possible (missing package.json)

### ISSUE THREAD

**Issue by wisammechano** [stackblitz/core#1393]
I am trying to import a GitHub repo that has only HTML, CSS, and Markdown files to stackblitz.com using the link `stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}` but I get an error saying the project is missing package.json file

**Comment by thescientist13** [comment]
Same.  Having the option to have `npm init` would be super nice too, so you can just go right from a bare repo in GitHub to working directly in Stackblitz.  Otherwise (if being totally "browserfull") you would have to manually create the _package.json_ in GitHub first.
