### ISSUE TITLE
markdown files preview is not scrollable

### ISSUE THREAD

**Issue by wisammechano** [stackblitz/core#1394]
I have a markdown file that I am previewing but the pane that opens to preview has no scroll and all overflow is hidden

**Comment by fvsch** [comment]
Hi @wisammechano, sorry for the late reply! We're shipping a fix for this today.

And kudos to @shadeed for [the CSS tip](https://defensivecss.dev/tip/flexbox-min-content-size/) that helped us fix this cleanly.
