### ISSUE TITLE
Keyboard highlighting

### ISSUE THREAD

**Issue by 24hfish** [stackblitz/core#1395]
Recently i became baffled about my phones keyboard randomly presenting keys that have a highlighted color to them. I tracked down what it was and its a bug to do with a website visited through apple safari.  After thinking about it i determined that the demo sandbox on the angular.io website is what does it.  Im attaching image with the keyboard colors and a link to apple support where someone else is asking about this and they get told its website problem.    Im not sure if this is supposed to change colors when looking at sandbox and its not getting turned off, Or if its not supposed to happen at all.   Thought you would like to know

![A242093F-070A-4D0E-8756-FBFDFB830E0B](https://user-images.githubusercontent.com/79712239/109324967-9afdc980-7812-11eb-80fd-10051f21dffd.jpeg)
[appleLink](https://discussions.apple.com/thread/251739934)

**Comment by 24hfish** [comment]
So im visiting the tag page for angular on stackoverflow , and i should post this as a question ?  Just not sure how to post there

**Comment by SamVerschueren** [comment]
Can you provide a link to the demo sandbox so I can check? Not much we can do about it I'm afraid. The apple link does not tell what exactly can cause this, feels more like an iOS bug to me.

**Comment by 24hfish** [comment]
https://stackblitz.com/angular/jrqkrrdrxeg?file=src%2Fapp%2Fapp.component.ts This is the sandbox i was using and still play with.  I also have link giving a bit more description about this issue.  https://discussions.apple.com/thread/251739934 its the usual game of hot potato not my code problem.   And i mean that in the kindest joking way.

**Comment by SamVerschueren** [comment]
Unfortunately the thread doesn't give a reason or cause as to what specific things can cause this behaviour. 

A couple of more questions. Does it instantly happen if you land on the StackBlitz editor? Or do you have to go through a certain flow for it to trigger?

Does it happen at the TypeScript playground as well? https://www.typescriptlang.org/play
