### ISSUE TITLE
I can't use stackblitz on mobile

### ISSUE THREAD

**Issue by CaptainEboy** [stackblitz/core#1396]
[Current Error](https://stackblitz.com/edit/js-ensyfa?embed=1&file=index.html) 

`On` mobile once a code is written, it can't be deleted by pressing the cancel key.

It's just stuck there forever, so I can't practically write a real code/program with stackblitz on mobile.

From the link above, in the editor, I mistakenly typed  letter "a" and I can't delete it😢😢

**Comment by CaptainEboy** [comment]
Yeah, it does happen in the typescript playground

**Comment by CaptainEboy** [comment]
However, it is clearly stated that it isn't supported in web-browsers.

"


   - <https://microsoft.github.io/monaco-editor/index.html>
   - <https://microsoft.github.io/monaco-editor/api/index.html>
   - <https://microsoft.github.io/monaco-editor/playground.html>
   - <https://microsoft.github.io/monaco-editor/monarch.html>
   - <https://registry.npmjs.org/monaco-editor/-/monaco-editor-0.23.0.tgz>

About

The Monaco Editor is the code editor that powers VS Code
<https://github.com/Microsoft/vscode>. A good page describing the code
editor's features is here
<https://code.visualstudio.com/docs/editor/editingevolved>.

It is licensed under the MIT License and supports Edge, Chrome, Firefox,
Safari and Opera.

The Monaco editor is not supported in mobile browsers or mobile web
frameworks.

Find more information at the Monaco Editor repo
<https://github.com/Microsoft/monaco-editor>.
------------------------------
Download v0.23.0

The latest released version is 0.23.0.

Download with this direct download link
<https://registry.npmjs.org/monaco-editor/-/monaco-editor-0.23.0.tgz> or from
npm <https://www.npmjs.com/package/monaco-editor>:

npm install ***@***.***

------------------------------
Editor


------------------------------
Diff Editor
------------------------------

[image: Microsoft] <https://microsoft.com/>
© 2021 Microsoft
"

This therefore pose a limitation to stackblitz

**Comment by SamVerschueren** [comment]
Do you use Android or iOS? It seems to work fine on iOS (just with a quick test run).

So unless Microsoft adds specific support for mobile (which they probably won't), we can't fix this unless it's something small we can do on our side like we did for [older Safari](https://github.com/stackblitz/core/issues/1399) versions.

Going to close this for now as I don't see a path forward here.

**Comment by CaptainEboy** [comment]
I use android.

However, as a developer who have made my own editor(just like stackblitz)
for my coding community, I believe there are many other editors which
support Android.

I only stopped using my editor & tried using stackblitz cause I didn't
provide support for react as I was busy with other projects.

**Comment by CaptainEboy** [comment]
I would also want to add one more thing, as I believe stackblitz would have
been a very good option for upcoming developers especially in developing
countries where access to laptop is expensive.

If stackblitz is to accommodate more developers the issue I raised should
not be closed, but a way forward to enabling stackblitz supporting android
should be greatly looked into.

Without a working editor, stackblitz cannot be used by the category of
people i mentioned above.

There are lots of developers who wanted to use stackblitz but can't use it
due to this issue.

**Comment by frog-o** [comment]
I always hate it when people close things that they won't fix especially on open source projects( witch this project is not -->at least fully from what I can tell) the main problem I have right now as of today is the keyboard and terminal I think this could be work around with a Codeflow extension (by write your own terminal) I hope they will work on letting you work on vs code extension!
