### ISSUE TITLE
Editing commit message doesn't apply

### ISSUE THREAD

**Issue by shmool** [stackblitz/core#1398]
I uploaded my project to GitHub, so I have the option to commit. 
When I commit, there's an input with a default commit message, with a supposedly option to edit it.
However, after I edit the message and hit "commit", the commit on GitHub has the default message instead of my own.

Thanks :)

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
