### ISSUE TITLE
Add Vue support

### ISSUE THREAD

**Issue by sebastiancichos** [stackblitz/core#14]
As in subject pleas add Vue 2 support

**Comment by cannap** [comment]
https://medium.com/@ericsimons/stackblitz-online-vs-code-ide-for-angular-react-7d09348497f4

>We currently support creating & exporting Angular apps (based on @angular/cli) and React apps (based on create-react-app) with support for Vue & custom templates landing shortly.

**Comment by EricSimons** [comment]
In pipeline! Would be great to hear what everyone would expect to see on day 1 — ES6 and/or TS? How styles are handled (scoped, module, etc)?

**Comment by cannap** [comment]
Everything! 
ES6 / global styles / scoped maybe postcss support :O easy import from vue-cli webpack generate projects :P

nah dont know but would like to see es6 first

thanks for the awesome work!

**Comment by Rebolon** [comment]
es6 first, but ts is a must have for me

**Comment by sosensible** [comment]
ES6 here also. I would say this though, if TS made it happen faster, I would adjust. :)

**Comment by mimischi** [comment]
Is there any update on this?

**Comment by joaocarvalhowd** [comment]
Is there any update on this? Please

**Comment by SSmale** [comment]
Really interesting in having a go with this but Vue is the only framework I currently know. Can’t wait for the support

**Comment by EricSimons** [comment]
Hey all! Good news - we've actually had this running for a month or so now locally and we're planning on to pull of the wraps within the next few weeks! 🎉 

Would any of y'all be willing to beta test it once it's on staging?

**Comment by rszaloki** [comment]
Yesss!!!

**Comment by sosensible** [comment]
I would be willing also.

**Comment by SSmale** [comment]
Yes, let me know when it is up!

**Comment by mimischi** [comment]
I'd also be interested!

Am 22.12.2017 07:26 schrieb "Simon Smale" <notifications@github.com>:

>
> Yes, let me know when it is up!
>

**Comment by ansarizafar** [comment]
I would also be interested

**Comment by kotpal** [comment]
@EricSimons Count me in to beta-test Vue support

**Comment by minutuslausus** [comment]
Would like to test too.

**Comment by guylil** [comment]
I would like to test it

**Comment by lanthaler** [comment]
Sign me up too

**Comment by csells** [comment]
count me in!

**Comment by gvdonovan** [comment]
Count me in!

**Comment by JWO719** [comment]
Hi I would also be interested in beta testing :+1:

**Comment by bdo** [comment]
Hi @EricSimons sign me up as well please 😀

**Comment by jhanink** [comment]
@EricSimons +1 for beta testing!

**Comment by altitudems** [comment]
Very interested in this

**Comment by akarelas** [comment]
I'm interested in beta-testing vue, as well.

**Comment by wdbacker** [comment]
@EricSimons I'm interesting in beta testing Vue.js support too, thanks!

**Comment by milky2028** [comment]
Also interested in testing Vue support. Sidenote: loved your appearance on The Web Platform podcast as well.

**Comment by ibrahimBeladi** [comment]
Count me in!

**Comment by x3rAx** [comment]
Hey @EricSimons, I'd love to beta test this, could you sign me up please 😍

**Comment by JDrechsler** [comment]
I am really interested in this too. I would love to beta test and try it out as soon as possible. I had a lot of fun creating an app with quasar and vue. Can't wait to do that on stackblitz.

**Comment by elshazer** [comment]
Hello @EricSimons , I am interested in the beta test of Vue.js

**Comment by jaredp** [comment]
updank pls

**Comment by EricSimons** [comment]
Hey everyone! First of all, thank you so much for the kind words & encouragement and sorry about my delay on this thread- things have been nuts the past couple months over here 😅

As many of you prob know, Vue has a brand new version of their CLI coming (3.0) that's adding a ton of cool new functionality... which is also why we haven't shipped this yet. :) Because we want to have full support for this + a few other complex CLI's/loaders we're planning to add, we're currently starting a very major refactor to our bundler/dev server that I'm hoping to get online by the end of the month (def no later than April). The end result should be a blazing fast, super stable editing experience for even the largest applications (we're currently testing against massive codebases like [RealWorld Vue](https://github.com/gothinkster/vue-realworld-example-app)).

I'll keep posting in this thread as we make progress & we'd love to hear any q's/ideas/etc y'all have in our [Discord channel](https://discord.gg/stackblitz) too :) 🍻

**Comment by jprando** [comment]
wow, nice, very nice

**Comment by gvdonovan** [comment]
Do I hear drums?

**Comment by flacito** [comment]
looking forward to vuejs!

**Comment by imgwho** [comment]
i'm still wating....

**Comment by gvdonovan** [comment]
Codesandbox is a nice alternative while stackblitz is waiting on Vue to
release the new cli

**Comment by EricSimons** [comment]
Hey all! We've gotten most of the relevant Vue loaders running under the hood at this point. We're still waiting on some Vue CLI 3 stuff + need to roll out an update for our editor, but things are looking 👌

Out of curiosity, are there specific aspects of the Vue CLI that y'all are using frequently? Want to make sure we support the most commonly used func available on day 1 :)

**Comment by gvdonovan** [comment]
For starters the zero config with linting, Vue router, vuex would be great.
Being able to add PWA & SSR would be great too. I’d be willing to help test
as well.

**Comment by nukadelic** [comment]
@EricSimons I'm interested in beta testing, count me in.

**Comment by gkinsman** [comment]
I'm interested in testing Vue on stackblitz too, I use it with TS so could give it a good stress test :).

**Comment by FranzSkuffka** [comment]
Is this official here? https://stackblitz.com/fork/vue

Because it is broken.

**Comment by sosensible** [comment]
@FranzSkuffka , I hit the dependencies and refresh and it installed the Vue libraries and came right up.

**Comment by gvdonovan** [comment]
Is Vue supported now?

**Comment by EricSimons** [comment]
Vue CLI 3 is still in RC's I think, but the editor & bundler upgrades are still on track (after much delay :). The vue project linked above does work but is only for non-SFC's, whereas all of our work is around the experience of SFC's and the multitude of languages they can support (Sass, LESS, Coffeescript, TS, JS, Stylus, etc etc)

**Comment by cornflourblue** [comment]
I just created a Vue + Vuex example on StackBlitz at https://stackblitz.com/edit/vue-vuex-jwt-authentication-example

I was able to get it working with the following minor tweaks:

1. change the file extension of vue components from `.vue` to `.js`
2. move template html into the `template` property of the exported component (from outside the export in a single file component)

Full details and the original code that uses single file components is available at http://jasonwatmore.com/post/2018/07/06/vue-vuex-jwt-authentication-tutorial-example

**Comment by gkinsman** [comment]
Hi there,

Vue CLI has now been GA released, and it'd be great to know if there's been any progress on this 🙂.

Thanks!

**Comment by jprando** [comment]
> Hi there,
> 
> Vue CLI has now been GA released, and it'd be great to know if there's been any progress on this 🙂.
> 
> Thanks!

use https://stackblitz.com/fork/vuejs for test
and not https://stackblitz.com/fork/vue

**Comment by jprando** [comment]
> Hi there,
> 
> Vue CLI has now been GA released, and it'd be great to know if there's been any progress on this 🙂.
> 
> Thanks!

how can i test vuejs-cli in stackblitz?

**Comment by eladcandroid** [comment]
Any news about official Vue.js support?

**Comment by erwanv** [comment]
Hello @EricSimons , is there any update?
I love stackblitz, please keep doing this amazing work!

**Comment by kevin192291** [comment]
2019 now, Any updates?

**Comment by gvdonovan** [comment]
Doesn't look like this is happening :(

**Comment by cornflourblue** [comment]
I've ended up going with CodeSandbox for Vue stuff and StackBlitz for everything else. 

e.g. https://codesandbox.io/s/lyzjo07r7m

**Comment by snowdream** [comment]
i'm still waiting....

**Comment by gvdonovan-fs** [comment]
Gave up altogether and now use CodeSandbox for everything.

**Comment by JinpingMa** [comment]
Watingggggggggggggg

**Comment by JinpingMa** [comment]
Waiting...

**Comment by milky2028** [comment]
To anyone just looking for a simple Vue template, you can use this one:
[https://stackblitz.com/edit/vue-js-template](https://stackblitz.com/edit/vue-js-template)

**Comment by gvdonovan** [comment]
does SB support SFC (.vue files)?

**Comment by gvdonovan** [comment]
Any color on this - looking at stackblitz and codesandbox for our enterprise and require support for ng and Vue.

**Comment by dalkegama** [comment]
Any news about Vue.js support?

**Comment by ez-dev** [comment]
Sounds if Vue be added to StackBlitz, nothing lovely is missed then.

**Comment by MickaelBaye** [comment]
It's happening ! 😮😀

**Comment by zdravkov** [comment]
Hi all, 
Vue 3 is just around the corner - are there any nearby plans to add some support for SFC (.vue files) ?

Greetings,
Plamen

**Comment by stevewhitmore** [comment]
Any reason why this is still missing? This is a major missing piece in my opinion and evidently a lot of other people think so too. 

This ticket is over 3 years old and was only added as a To do back in November... nearly a year ago.

**Comment by niklas-dahl** [comment]
I don't think vue support will come in the near future. As far as I've heard the stackblitz team wanted to have this feature almost released 3 years ago. But since google got involved with angular and google cloud as sponsors, this topic has been hushed up. 
That it has something to do with google is just my impression I have no proof for it.
I think it is a real pity but stackblitz is still a great tool.

- just a stackblitz fan who is a bit sad

Translated with www.DeepL.com/Translator (free version)

**Comment by EricSimons** [comment]
Hey all- we actually have the latest Vue 3 RCs running on staging. We're coordinating with the vue team on launching the official starter project onto prod in tandem with their official Vue 3 announcement. They haven't given us a specific target launch date yet, but I'll circle back here and keep y'all in the loop.

I also want to apologize for the delay on shipping this feature. It originally looked like Vue 3 would ship a bit earlier, and as a small team we didn't want to duplicate work on making Vue 2 work in-browser if v3 was just around the corner.

Also has nothing at all to do with Google. StackBlitz is an independent company and sets its own priorities and agenda. Ultimately we made a bad call by not biting the bullet and taking the time to support Vue 2 in the interim. Fortunately Vue 3 is legitimately close to release at this point, and on behalf of our entire team, we're beyond excited to get this feature out the door :)

**Comment by EricSimons** [comment]
Today is a good day. 🙂

With Vue 3 [officially released](https://twitter.com/vuejs/status/1306992969728380930) a few hours ago, I'm excited to share that **our official support for Vue 3 is [now online](https://twitter.com/stackblitz/status/1307065248151728128)**!

**Check it out and let us know what you think: [stackblitz.com/fork/vue](https://stackblitz.com/fork/vue)**

Currently in beta for the next 1-2 weeks as we squash last bugs- please file issues on this repo of anything you run into.

On behalf of the entire StackBlitz team, thank you all for your patience on this and huge thank you to Evan and the Vue team for their amazing work! ❤️

And with that, I shall click the "Close Issue" button... and it will feel amazing. 😄
