### ISSUE TITLE
Sometimes external dependencies are loaded after application initialized which causes runtime errors

### ISSUE THREAD

**Issue by maxkoretskyi** [stackblitz/core#140]
I have [this project](https://stackblitz.com/edit/angular-fgrzjt) that depends on jQueryUI. Sometimes it works fine but sometimes it breaks with the error visible in console:

> TypeError: $(...).slider is not a function

Which means that jQueryUI wasn't loaded at the time of the code execution.

It's usually enough to reload the page several times to see the behavior. I tested it on several PC's. But since I believe it's some kind of race condition it make take more reloading attempts to notice the issue.

**Comment by EricSimons** [comment]
This is really interesting — we actually don't boot your application until all external resources have loaded, so this def shouldn't be happening. I haven't been able to repro this with the project you provided - is there anything in particular that I need to do to make it cause that error?

**Comment by EricSimons** [comment]
Also, can you try disabling any browser extensions and see if that has any effect?

**Comment by alexzuza** [comment]
@EricSimons Just opened link @maximusk providered and i can reproduce it.

**Comment by EricSimons** [comment]
@alexzuza thanks for confirming the repro -- I just tried on a lower powered machine and now I'm getting this error about 30% of the time. Will investigate asap and see what we can do to fix

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
