### ISSUE TITLE
Not able to login with my public GitHub account

### ISSUE THREAD

**Issue by kumardevsingh** [stackblitz/core#1404]
I have a **public GitHub account** and trying to **login** with the same and getting the error as the screenshot attached. 
I have tried on chrome, firefox, and other browsers. 

Please help me.

![image](https://user-images.githubusercontent.com/49704307/111425970-ede3e600-8719-11eb-9e80-d41578a5f8a7.png)

**Comment by SamVerschueren** [comment]
See my answer here https://github.com/stackblitz/core/issues/1402#issuecomment-800584651.

Closing in favour of #1402
