### ISSUE TITLE
Yikes! Something went wrong with your request.

### ISSUE THREAD

**Issue by derekowusubekoe** [stackblitz/core#1406]
When I try to sign to with GitHub account I get the error message below;

"Yikes! Something went wrong with your request.
If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core"

Please help.

Thanks

**Comment by juleksujak** [comment]
@derekowusubekoe I have the same message from yesterday.

**Comment by SamVerschueren** [comment]
Can you check my answer at #1402 and see if this could be the reason of the error? If so, I'd like to group everything together in that thread.

**Comment by SamVerschueren** [comment]
I posted an update in #1402. The error message is also improved now. Closing this as duplicate as I try to consolidate everything under #1402.
