### ISSUE TITLE
Cannot rename stackblitz project after forking

### ISSUE THREAD

**Issue by charlesr1971** [stackblitz/core#1409]
I want to change:

`https://stackblitz.com/edit/github-ifdh1d`

to:

`https://stackblitz.com/edit/rxjs-chat`

**It just won't let me change it**

**Comment by SamVerschueren** [comment]
The first link does not work for me, the second does. I'm not sure if the second one is your project? But it's not possible to have two projects with the same name off course.

**Comment by charlesr1971** [comment]
OK. I removed one of the entries in my package.json and the import succeeded. 

The naming issue is strange. I tried to name my project ‘rxjs-chat’ but the system rejected this. I then tried ‘rxjs-chat-1’, and this succeeded. 

The issue is, that I don’t already have a project named ‘rxjs-chat’?

**Comment by SamVerschueren** [comment]
Project slugs (which is what ends up in the url) are unique over the entire platform. So if another user already claimed rxjs-chat, you can't rename yours to that anymore.

We are looking at adding project titles which don't have to be unique at all (not even for the same user) and which are entirely disconnected from the unique project slug.

I can't give you information on when this is planned though. So for now you will have to name your project to something globally unique. For instance `<GitHub username>-rxjs-chat`.

Hopefully this answers your question.

**Comment by charlesr1971** [comment]
When I saw that the URL had no username in it, I assumed that StackBlitz was using a session variable to manage navigation. I then thought that there must be some kind of share URL with a username in it. Once I discovered that this was not the case, the penny dropped. The problem with not namespacing, using a username, is that it vastly reduces the amount of project names, available to each user. 

Just out of interest, why did StackBlitz decide to use this approach?

**Comment by EricSimons** [comment]
@charlesr1971 it's actually a bit funny... we chose this approach because we never thought that millions of developers would actually use StackBlitz every month 😅  But here we are! We're planning to switch to a title based naming system (instead of slug based) in April/May. We'll circle back here once that stuff is on prod and you can give it a whirl!

**Comment by charlesr1971** [comment]
OK. That’s actually a very honest answer and not one, I was expecting...
