### ISSUE TITLE
Dependencies autocomplete

### ISSUE THREAD

**Issue by gkiely** [stackblitz/core#141]
When I want to add a package, I type it into dependencies and add it.

But sometimes I can't remember the name exactly so I have to go to npm, search for it and then copy and paste it into stackblitz.

What would be great is if when typing in a dependency it shows you an autocomplete of possible names.
Bonus points for also showing or ordering by the the number of downloads.

**Comment by EricSimons** [comment]
Excellent idea — adding this to our roadmap now! Thanks :)

**Comment by sulco** [comment]
This seems like a duplicate of #46 - closing
