### ISSUE TITLE
console array logs in wrong order

### ISSUE THREAD

**Issue by bobadar** [stackblitz/core#1412]
i spent a good hour debugging why my code wasn't working properly.

it turns out the numbers arent even in the correct order in the logs

0,1,<ins>10</ins>,11,12,13,14,15,16,17,18,19,<ins>2</ins>,20

![image](https://user-images.githubusercontent.com/81293694/112280230-afe84400-8c7c-11eb-85c6-a26e6b6558c8.png)

**Comment by SamVerschueren** [comment]
It looks like the numbers are sorted in lexicographical order instead of numerical order. 

Thanks for reporting!
