### ISSUE TITLE
Latest TypeScript as dependency is broken: "Can't find package:perf_hooks"

### ISSUE THREAD

**Issue by chcaru** [stackblitz/core#1415]
Installing the latest version of TypeScript as a dependency breaks Stackblitz with the following error:
`Can't find package: perf_hooks`

Repro:
https://stackblitz.com/edit/typescript-dep-not-working?file=index.ts

Note:
Installing `perf_hooks` doesn't help.

**Comment by kc0tlh** [comment]
Update: This issue has been resolved. See #337 for additional context!
