### ISSUE TITLE
Delete a team member does not work

### ISSUE THREAD

**Issue by rubenrivera** [stackblitz/core#1417]
My friend Juan (he only speaks Spanish) added another user to the Stackblitz team. Clicking on **delete** doesn't work. He temporarily gave me his GitHub password in order to try on different computers / browsers (tried on Chrome OS, Windows 10, Chrome, Firefox, including Chrome in incognito mode)

![image](https://user-images.githubusercontent.com/24765478/112733010-0a92d180-8f03-11eb-89bd-4970439bee62.png)

**Comment by kc0tlh** [comment]
If this issue has not been resolved, please reach out to hello@stackblitz.com for suppport and a refund. Thanks!
