### ISSUE TITLE
Angular TS Dependencies are loaded incorrectly at page startup.

### ISSUE THREAD

**Issue by fedir-indutnyi** [stackblitz/core#1419]
Having Repo with project using Angular 5 dependencies. Created Stackblitz project connected to repo. 
When project page opens, dev servver starts and displays standard angular webpage running (dependencies loaded angular 11).
Hovever same time repo clones (synchronises) and after 30 seconds, files appear on the right side. 
Aftter repo is loaded, right side still shows Angular welcome page with magic to happen, and dependencies are Angular 11.
No magic happens.
Then if i navigate package.json, and add empty line on the top, and save file, Stacblitz believes file has changes, and reloads and installs correct dependensies (Angular 5).
After that, in 5-10 min - page ont the right side finally loads. It shows correct behaviour. Hourrah.
Clicking save. Can also click commit (to commit empty line to package json). 
Doesnt matter. 
Okey, now - 2 biggest bugs:
1. Fork button doesnt work (after clicking shows rolling wheel forever)
2. After page refresh, everything is lost and nothing saved, even empty line. Dependencies become Angular 11, Page becomes standard magic welcome.

Example:
https://stackblitz.com/edit/angular-ivy-pwe9nw
created directly from 
https://github.com/fedir-indutnyi/sfrontend

**Comment by fedir-indutnyi** [comment]
This seem to be clear bug

**Comment by EricSimons** [comment]
@fedir-indutnyi I can't seem to open those two links- are those the right ones?

**Comment by fedir-indutnyi** [comment]
> @fedir-indutnyi I can't seem to open those two links- are those the right ones?

hi,. yes, updated those links. 
Reproduction is simple. Connect repo, get it loaded then - dependencies wrong,no forf, no save,.
