### ISSUE TITLE
Support plain vanilla WebComponents

### ISSUE THREAD

**Issue by larsgk** [stackblitz/core#142]
Would it be possible to make a project version that doesn't modify the code when viewing?

e.g. https://stackblitz.com/edit/littleone didn't work

**Comment by EricSimons** [comment]
@larsgk I haven't done any testing for web components support yet, but I'll dig into this asap and figure out how to get them working :) Thanks a ton for digging into this & filing an issue!

**Comment by sulco** [comment]
We now support a no-transpilation mode as the `Static HTML/CSS/JS` preset
