### ISSUE TITLE
Deploy Issue

### ISSUE THREAD

**Issue by EgemenCiftci** [stackblitz/core#1420]
Stackblitz can not deploy my project to Firebase. It says "Success!" but nothing is deployed.
[https://stackblitz.com/edit/angular-firebase-rtdb](https://stackblitz.com/edit/angular-firebase-rtdb)

**Comment by EricSimons** [comment]
Hmm whats the firebase project URL associated with this?

**Comment by EgemenCiftci** [comment]
https://web-socket-server-e3604.firebaseapp.com/
