### ISSUE TITLE
Dependencies loading

### ISSUE THREAD

**Issue by ctamisier** [stackblitz/core#1424]
With this project:
https://stackblitz.com/edit/react-tag-input-1nelrc

We can see the UI like this:
![image](https://user-images.githubusercontent.com/766263/114676006-253db680-9d09-11eb-8685-4962f833bd30.png)

In package.json, if I upgrade `"react-dnd": "^5.0.0"`, (instead of `"react-dnd": "^2.6.0"`), the UI is broken and is like this:
![image](https://user-images.githubusercontent.com/766263/114677008-2a4f3580-9d0a-11eb-9389-a26de224118e.png)
(_why not_).

Now if I revert to `"react-dnd": "^2.6.0"`, the dependency is back to `2.6.0`
![image](https://user-images.githubusercontent.com/766263/114677046-3509ca80-9d0a-11eb-9a5a-693daa1f9bc1.png)

But the UI doesn't change (same UI that `5.0.0`)... It behaves like if the dependency is not internally put back to `2.6.0`.

I try to refresh/reload as I could but I can't find the way to have the `2.6.0` behavior without totally reloading in a brand new tab with the initial project url (https://stackblitz.com/edit/react-tag-input-1nelrc).

**Comment by purplem1lk** [comment]
Thank you for your patience - I've attached screenshots of what I see when the `react-dnd` dependency is `"react-dnd": "^2.6.0"` and `"react-dnd": "^5.0.0"`. It's possible that recent code changes have fixed this issue. If your issue persists or if the screenshots below do not show what you're expecting, feel free to tag me or ask to reopen this issue. Thank you! :) 

![Screen Shot 2021-05-24 at 1 07 34 PM](https://user-images.githubusercontent.com/49956513/119383294-24e1f500-bc91-11eb-80c2-d2f4da6edd2f.png)
![Screen Shot 2021-05-24 at 1 07 54 PM](https://user-images.githubusercontent.com/49956513/119383297-26132200-bc91-11eb-8373-27d77288c415.png)
