### ISSUE TITLE
Light theme is broken in embed mode

### ISSUE THREAD

**Issue by Finesse** [stackblitz/core#1425]
The light theme has some colors broken when used in an embedded iframe. Open https://stackblitz.com/edit/clarity-v3-light-theme?embed=1&theme=light and put the cursor in any place of the code. This is what it looks like:

![image](https://user-images.githubusercontent.com/9006227/114999597-583ca180-9ee5-11eb-859d-0fa626cc002f.png)

There are at least 3 issues:

- The selected code background is too dark
- The frame around the cursor line is black (the contrast is too high)
- The contrast of vertical 1px code block lines is too high contrast too

Meanwhile the light theme looks good in regular mode (not in an iframe).

**Comment by sulco** [comment]
Thanks for reporting this and for the repro @Finesse!
I'm adding it to my queue, and will let you know as soon as it's fixed.

**Comment by fvsch** [comment]
@Finesse This should be fixed now (as of today). Feel free to comment if something still looks wrong.
