### ISSUE TITLE
The onload and onerror attributes of HTML script elements are neglected

### ISSUE THREAD

**Issue by Finesse** [stackblitz/core#1426]
Try [a simple example](https://stackblitz.com/edit/js-qtrmoz?file=index.html):

```html
<script
  src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"
  onload="document.body.appendChild(document.createTextNode('loaded'))"
  onerror="document.body.appendChild(document.createTextNode('errorred'))"
></script>
```

It will work if you just save this code as an HTML file, but it won't work in StackBlitz. As far as I can see, StackBlitz parses the HTML code and loads the script manually; the problem is that it doesn't consider the original `onload` and `onerror` attributes, therefore the code doesn't work.

IMHO the best solution is let the browser parse and run the HTML code by itself.

My current workaround (put it into the `index.js` file):

```js
// Stackblitz breaks the `onload` attribute of the script: https://github.com/stackblitz/core/issues/1426
document.querySelectorAll('head + head script[src]').forEach(script => {
  const newScript = document.createElement('script')
  Array.prototype.forEach.call(script.attributes, ({ name, value }) => newScript.setAttribute(name, value))
  script.parentNode.insertBefore(newScript, script)
  script.parentNode.removeChild(script)
})
```

**Comment by sulco** [comment]
Hi @Finesse, thanks for reaching out!

Although at this point we can't change how the "JavaScript Blank Project" starter is being treated, we've also recently provided a "Static HTML/JS/CSS" starter that does exactly what you propose :) 

Here's your example working in that preset:
https://stackblitz.com/edit/web-platform-4wtdqc?file=script.js

**Comment by Finesse** [comment]
@sulco Awesome, thanks!

**Comment by Finesse** [comment]
@sulco Unfortunately, your example works neither in [fullpage mode](https://web-platform-4wtdqc.stackblitz.io), nor in [embed mode](https://stackblitz.com/edit/web-platform-4wtdqc?embed=1&file=index.html)

**Comment by sulco** [comment]
Eek, you're right, looks like we're handling static presets incorrectly in these cases. I've just created a [new issue for this](https://github.com/stackblitz/core/issues/1427) and I'll let you know when it's fixed!
