### ISSUE TITLE
Commit modal "cancel" button does not work

### ISSUE THREAD

**Issue by cofad** [stackblitz/core#1428]
When the "Commit" button is clicked a modal appears with a commit message and 2 buttons, "cancel" and "commit".

When I click the "cancel" button, the changes are committed instead of just closing the modal.

Desired behavior would be to just close the modal without committing the changes.

**Comment by EricSimons** [comment]
Oh woah, you're absolutely right about this. We're going to get a fix prioritized and will circle back once it's live. cc @sulco

**Comment by sulco** [comment]
Thanks, @cofad for reporting this – happy to report it's now fixed :)

**Comment by cofad** [comment]
Glad to help. I  just checked it out, and it's working! Awesome turnaround time.
