### ISSUE TITLE
Import from Github broken for Nrwl projects

### ISSUE THREAD

**Issue by Lonli-Lokli** [stackblitz/core#1439]
Open https://stackblitz.com/github/Lonli-Lokli/functional_programming_in_angular/tree/part_01_step_01?file=apps%2Fweather%2Fsrc%2Findex.html

Locally it compiles fine, Stackblitz does not:
Import error, can't find files:
/apps/weather/apps/weather/src/index.html
/apps/weather/apps/weather/src/polyfills.ts
/apps/weather/apps/weather/src/main.ts
/apps/weather/apps/weather/src/styles.scss

**Comment by markwhitfeld** [comment]
NX projects are supported in Stackblitz WebContainer projects only. Add `preset=node` to your import url to do this.
https://stackblitz.com/github/Lonli-Lokli/functional_programming_in_angular/tree/part_01_step_01?preset=node
