### ISSUE TITLE
Emmet autocomplete stopped working

### ISSUE THREAD

**Issue by drKnoxy** [stackblitz/core#144]
We used to be able to type and get autocompletion / expansion for jsx in .js files

ie.
```
span.pill*10 +tab
```

in the react starter template

**Comment by EricSimons** [comment]
Eek! The new version of Monaco changed how emmet works :( Will get this implemented asap - thanks for letting us know!

**Comment by drKnoxy** [comment]
Thank you!

**Comment by drKnoxy** [comment]
@EricSimons can i help with this at all, love the site but this loss of autocomplete is super painful

**Comment by danieldunderfelt** [comment]
Hey, any update on this? Just took StackBlitz for a test-drive and Emmet missing is definitely a bummer :(

**Comment by kotpal** [comment]
Is there an update for supporting Emmet in StackBlitz?

**Comment by SamVerschueren** [comment]
Yes there is. We just deployed improved emmet support for html, jsx, css, ...

![image](https://user-images.githubusercontent.com/1913805/114082678-51db7380-98ae-11eb-8d08-9b7d1b4a268c.png)
![image](https://user-images.githubusercontent.com/1913805/114082825-851e0280-98ae-11eb-96fd-cc0ec5e0feaf.png)

Sorry that it took a while to fix this ;).
