### ISSUE TITLE
Adding an array to imported json-file freezes compilation

### ISSUE THREAD

**Issue by KooiInc** [stackblitz/core#1440]
For the second time I noticed that adding an array to an existing json-file that is imported in the project freezes compilation. The server seems to hang, showing me the next image continuously. Moving the array out of the json-file subsequently did not help.

Not sure it's the array per se. Maybe it's just editing an existing json-file?

Project is [here](https://stackblitz.com/edit/js-fwg2db).

![image](https://user-images.githubusercontent.com/836043/117314099-baeee080-ae86-11eb-9f7c-446aafc3157f.png)

**Comment by EricSimons** [comment]
@KooiInc it appears the JSON in that file is invalid- if you try calling `JSON.parse` on it in the chrome console it fails out. Can you take a peek at that and lmk what you find?

**Comment by KooiInc** [comment]
Thx @EricSimons it was a _trailing comma_ (not allowed in json, but not detected as an error by the editor). So, issue resolved, thanks again.
