### ISSUE TITLE
Not able to upload files on stackblitz

### ISSUE THREAD

**Issue by Bikash01293** [stackblitz/core#1441]
Please help me out a i am getting error while uploading files in stackblitz from github.
![Screenshot from 2021-05-07 12-14-14](https://user-images.githubusercontent.com/48493235/117410162-b03c5600-af2f-11eb-92c4-fd4883f78858.png)

**Comment by kc0tlh** [comment]
This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
