### ISSUE TITLE
Escaping stackblitz demo on https://stackblitz.com/

### ISSUE THREAD

**Issue by ryderdaniel** [stackblitz/core#1449]
You can cause potentially undesirable behavoir on stackblitz.com by forking the demo then deleting the project repeatedly. I will demo what I mean in the gif below.

![problem_reduced](https://user-images.githubusercontent.com/67907352/118820131-9106d680-b8e8-11eb-87cc-ffff16073f72.gif)

The way I get the delete button in the settings bar to appear is by pressing Ctrl+s, as if I were saving the project after I make an edit. This forks the project and allows me to delete the project. Upon Deletion, the iframe is redirected to stackblitz.com again and the process is repeated until a crash of sorts happens. I don't know if this is intentional behavior so I'll just mention it anyways.

Sorry if this is not an important issue.

Best Regards,
Ryder

**Comment by fvsch** [comment]
Thanks for the report @ryderdaniel!

We revamped our home page recently and have removed this demo.
We also fixed the issue that could lead to accidentally forking an embedded project, so this issue shouldn't happen anymore.
