### ISSUE TITLE
Is it possible to import packages direct from github like in package.json?

### ISSUE THREAD

**Issue by SvenBudak** [stackblitz/core#145]
Hi. I have in my package.json files in every project this:

```
"dependencies": {
    "@devmonkeys/scss-elements": "git+https://github.com/DevMonkeysDE/scss-elements.git",
},
```

Is it possible to import a github repository in the same way in StackBlitz? Entering the URL in the Dependency input dont work.

**Comment by EricSimons** [comment]
@BamiGorengo we're working on implementing this! We're shooting to have it out in early October at the latest :)

**Comment by BamiGorengo** [comment]
Awesome! =) Its already now the best online Editor. I am so happy that im not any more forced to use plunker. :P

**Comment by sneckelmann** [comment]
I feel like this functionality has been demonstrated by the Stackblitz team.  Should this issue be updated?

**Comment by rupamroy** [comment]
Hi

Is this functionality implemented yet ?

**Comment by toniObject** [comment]
Please implement this feature. At least it should be possible to import github projects. Bitbucket and other sources would be nice too.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
