### ISSUE TITLE
Using a dark theme, the console is using black on a dark background

### ISSUE THREAD

**Issue by arobinson** [stackblitz/core#1450]
User settings:
```
{
  "editor.theme": "vs-dark",
...
```

Resulting console with the current stackblitz:
![image](https://user-images.githubusercontent.com/93213/119023033-89821480-b95e-11eb-880f-8e33b2ff29fb.png)

**Comment by arobinson** [comment]
[settings.txt](https://github.com/stackblitz/core/files/6517745/settings.txt)

**Comment by SamVerschueren** [comment]
Thanks for reporting this 🙏 ! We're revisiting all the theming changes we made recently and iron out all the bugs.

**Comment by purplem1lk** [comment]
Here is a temporary workaround from a user in #1460 while our devs work on this:

> @lovetingyuan you could use
> 
> ```js
>     console.log('%c YOUR_TEXT', 'color:white');
> ```

**Comment by willi84** [comment]
thanks wanted to file the same issue

**Comment by SamVerschueren** [comment]
This should be fixed now. Thanks to @fvsch 🎉 .

**Comment by fvsch** [comment]
Thanks everyone who reported this issue!
