### ISSUE TITLE
After opening it always opens _relay_

### ISSUE THREAD

**Issue by gbraad** [stackblitz/core#1453]
Any repo or project I open will load and then redirect/navigate to `[...]stackblitz.io/_relay_`. I am using the latest Vivaldi browser with almost no extensions (only a proxy changer).

**Comment by gbraad** [comment]
... when navigating back this does not happen again for the session (unless reloaded).

**Comment by KooiInc** [comment]
Same experience here. Project is loaded, but redirects to `/_relay_` . Back to previous page subsequently loads the project correctly.

**Comment by gbraad** [comment]
> Hold that: newest Vivaldi version works as expected

Will test

**Comment by Nisgrak** [comment]
I have the same issue! I see that in a private window didn't happen and 1 cookie es blocker (screenshot), any ideas?

![image](https://user-images.githubusercontent.com/19597708/146038718-d756c2e7-05fe-4f3c-91ef-d17286908f09.png)
![image](https://user-images.githubusercontent.com/19597708/146038739-8d991870-7780-4f6d-90f6-a5a722b25967.png)
![image](https://user-images.githubusercontent.com/19597708/146038754-efd8696d-92ac-4977-a0b1-5ecef84793ce.png)

**Comment by gbraad** [comment]
I gave up on StackBlitz, sorry.
________________________________

**Comment by gbraad** [comment]
[Duplicate of #1219](https://github.com/stackblitz/core/issues/1219)
