### ISSUE TITLE
Template for Nuxt.js

### ISSUE THREAD

**Issue by eladcandroid** [stackblitz/core#1455]
Hello,
I would like to ask you to add Nuxt.js template (with WebContainer)

Thanks!

**Comment by SamVerschueren** [comment]
Hi @eladcandroid, thanks for the feature request. Would you mind opening this in the webcontainer repository instead? https://github.com/stackblitz/webcontainer-core/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc That's where we track all the WebContainer related issues and feature requests.
