### ISSUE TITLE
UI Hangs while importing my public repo

### ISSUE THREAD

**Issue by nolram88** [stackblitz/core#1458]
[My Repo](https://stackblitz.com/github/nolram88/meleelight
)
I just get an error on subsequent attempts,

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473 

You can see it for yourself here: https://pr.new/github.com/nolram88/meleelight
