### ISSUE TITLE
Support importing (nested) nextjs projects from github

### ISSUE THREAD

**Issue by goleary** [stackblitz/core#1463]
I have a nextjs project [here](https://github.com/goleary/hcmst) (inside the `web` folder). 

When I try to access [this project  on stackblitz](https://stackblitz.com/github/goleary/hcmst) I get this error:

```
The repository is missing a package.json file.
```

It looks like [importing nextjs projects from github isn't supported](https://developer.stackblitz.com/docs/platform/importing-projects/#supported-project-types) to begin with, & doubly so since the project (`package.json`) lives in a nested folder.

Is there some other way to import this project to stackblitz?

**Comment by EricSimons** [comment]
It is possible! Just put the path in the importer URL to that folder and it should work: https://stackblitz.com/github/goleary/hcmst/tree/main/web

Closing for now but lmk if you run into any other issues!

**Comment by goleary** [comment]
nice, thanks @EricSimons!
