### ISSUE TITLE
Failing to import a public github repo

### ISSUE THREAD

**Issue by wizlee** [stackblitz/core#1468]
## Fail to import a public GitHub repo
The URL is https://stackblitz.com/github/wizlee/angular-marketplace.

## To reproduce the issue
Run the URL above, the import animation seems to keep running indefinitely. Not exactly sure how long I left the webpage running, estimation is >15 minutes. 

## Error message
After refreshing, the URL will show an generic error as shown below. 
![image](https://user-images.githubusercontent.com/9842499/119393541-ad997900-bd03-11eb-9bc0-e733fa90a54e.png)

## Debugging Attempts
- Is this issue due to the repo setting or perhaps even the size? Need help because don't know where to start debugging this. I try to use the new beta feature of webcontainer to start from a blank NodeJS project. However I am not skilful enough to download the repo manually and setup the environment that way =)
- After referring to #1159, I run through my repo to confirm if there's any absolute path and I didn't find any. One thing that is different maybe is the use of tsconfig.json paths? It don't use absolute path so shouldn't be an issue. Listing here as a reference
    ```json
    "paths": {
      "@cometchatComponents/*": [
        "src/cometchat-pro-angular-ui-kit/CometChatWorkspace/projects/angular-chat-ui-kit/src/components/*"
      ]
    },
    ```

## Environment
Browser: Edge Version 90.0.818.66 (Official build) (64-bit)

**Comment by pdhoward** [comment]
I am also having trouble with the import function.

I am new to stackblitz and trying out the features of this very cool and promising tool set.

I set up a new nodejs project, and then attempted to import a very simple public repo

1. the url
https://stackblitz/pdhoward/datagen produced this result

"Error: Could not resolve reference"
refs/heads/master

2. the url 
https://stackblitz/pdhoward/datagen/tree/main

produced a message that the repo could not be found

I noted that in the the sidebar that the branch appears to default to 'master'. I attempted to change it but it did not work

**Comment by pjtf93** [comment]
I'm having the same issue, haven't been able to import any repo with the default branch as main

**Comment by wizlee** [comment]
Unsure if bumping issue is a good practise, but doing it anyway to prevent bot to close this issue as stale 😉 

And I observed that issues reporting failing to import public GitHub repo are seemingly being not actively triaging. What are the common things and/or additional info that I should be providing to get this issue some eyeballs?

**Comment by wizlee** [comment]
There's a chance in my repository so I am now using a subfolder inside the branch instead of the whole repo - https://stackblitz.com/github/wizlee/angular-marketplace/tree/master/angular-marketplace-start. 

It might also due to there's already a fix in place. Either way closing this as not an issue anymore.
