### ISSUE TITLE
HttpError: Failed to fetch dependencies

### ISSUE THREAD

**Issue by wll8** [stackblitz/core#1469]
### **Description of Bug**
❯ npx mockm
HttpError: Failed to fetch dependencies

error Command failed with exit code 1

ERR!: Command not found mockm

error Command failed with exit code 1

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/http-server
2. Click on `Terminal`
3. Enter the command npx mockm
4. See error `HttpError: Failed to fetch dependencies`

### **Expected Behavior**
mockm runs successfully.

Looks like this:
![image](https://user-images.githubusercontent.com/28223260/119429340-3e427a00-bd41-11eb-822c-20a52f154477.png)

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/28223260/119428076-d12de500-bd3e-11eb-9f11-da6a69e4472a.png)

**Additional Context/Questions**
- [mockm](https://www.npmjs.com/package/mockm) is already registered on npmjs.com
- Google Chrome 90.0.4430.212 x64
- In China, I don't know if it is because of China's Great Firewall.
- You can successfully run this command `npx http-server` on stackblitz
- In the local environment, you can use the same command `npx mockm` to install and use normally.

**Comment by EricSimons** [comment]
Can you take a screen shot of your chrome JS console and network tab? I'm curious if requests are failing for some reason

**Comment by wll8** [comment]
![image](https://user-images.githubusercontent.com/28223260/119428657-e2c3bc80-bd3f-11eb-8195-7e89e8bc89c0.png)

![image](https://user-images.githubusercontent.com/28223260/119428739-11419780-bd40-11eb-8fdb-2159cbfb6d2b.png)

**Comment by donalffons** [comment]
...same [here](https://stackblitz.com/github/donalffons/opencascade.js-examples). Although, I'm getting different error messages in the console.

![image](https://user-images.githubusercontent.com/33040347/121772924-e5fcdc00-cb78-11eb-9a23-153b49d598a2.png)
