### ISSUE TITLE
Folder deleted

### ISSUE THREAD

**Issue by ghetolay** [stackblitz/core#147]
So I was playing with some code and I think I created an infinite loop so it froze a bit but then I could close the output and save.
I changed the code on the current file to avoid the infinite loop and reopen the output. That's when I got a file not found error and found out a complete folder was missing.

I have no idea when exactly the folder got removed. I thought maybe I did a miss click during the freezing but there is a modal to confirm deletion so it's unlikely.

I'm sorry I can't give more information but maybe you can investigate more. 
Here is the url : https://stackblitz.com/edit/angular-virtualscroll?file=app%2Fapp.component.ts

Also if you happen to have some kind of versioning, would be happy to find my code back :)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
