### ISSUE TITLE
No semicolon support

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/core#1473]
### **Is your feature request related to a problem? Please describe.**
I want to set no semicolons permanently, just like in VSCode

### **Describe the solution you'd like**
Probably uses Prettier

### **Describe alternatives you've considered**
Nope

**Comment by fvsch** [comment]
I’ll close this issue since it's a feature that we already support, but I’m definitely making a mental note that we need to make it more visible. Feel free to comment if you have other feedback on this topic.

**Comment by deadcoder0904** [comment]
@fvsch I need a global setting. No time to set up `.prettierrc` for every Stackblitz project I make.

Just provide us with a global Prettier config file like VSCode does so it solves all **prettier** related issues :)
