### ISSUE TITLE
BUG: Not able to import github project

### ISSUE THREAD

**Issue by markwhitfeld** [stackblitz/core#1479]
I receive an error when trying to import my github project:
https://stackblitz.com/github/ngxs/store

**Comment by midudev** [comment]
Same for https://stackblitz.com/github/midudev/midu.dev.

**Comment by eviltik** [comment]
Are you using LFS ? (big files) ?

**Comment by midudev** [comment]
Not using LFS in my case @eviltik. But it's true I'm storing some images on the repo.

**Comment by markwhitfeld** [comment]
No LFS for me either ;-)
Just click the link to reproduce 👍

**Comment by kc0tlh** [comment]
Both of these repos can be opened in [our new VS Code editor](https://stackblitz.com/codeflow)! Getting the repos up and running/the in-browser dev server working may be require additional troubleshooting, but the repos will import now!

**Comment by akvadrako** [comment]
LFS is still not supported, I take it?

**Comment by kc0tlh** [comment]
@akvadrako correct, GIT LFS is not supported in StackBlitz at this time.
