### ISSUE TITLE
Bootstrap Dependicy

### ISSUE THREAD

**Issue by kbbalukrishna** [stackblitz/core#148]
i have installed bootstrap dependency in project. 
but not possible to add in ".angular-cli.json" .
  "styles": [ 
      "styles.css"
      ]

help

**Comment by vinchauhan** [comment]
@kbbalukrishna - You can probably use the cdn for bootstrap.

**Comment by SarvM** [comment]
@kbbalukrishna - 

Below option may be used to access bootstrap.

1. Click on "Dependencies" accordion. 
2. Enter URL [ https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css ] in external resources option and click enter.
3. After few seconds "bootstrap.min.css" file name will get displayed. It confirms the bootstrap file has been added.

**Comment by jaydeepkarena** [comment]
**i am new to web development & learning angular**

`bootstrap.min.css`

but it doesn't show the effect of applied classes
i have applied card card-block classes

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue, if not already resolved so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
