### ISSUE TITLE
Angular Project Styles issue - critical - project is not starting. Easy to reproduce

### ISSUE THREAD

**Issue by fedir-indutnyi** [stackblitz/core#1481]
### **Description of Bug**
Here:
Error in src/styles.scss
Error: ENOENT: No such file or directory., '/dev/null'

https://stackblitz.com/edit/github-kayiva-mhtzhs?file=package.json
Hello Community and Devs. This issue was happening in past, however last time was resolved by manipulating with styles and modules, basically changing way styles are loaded.
But this time, issue occurs much more often, project cannot start with message:
Error in src/styles.scss
Error: ENOENT: No such file or directory., '/dev/null'

I know, that project is fully working, it works fine locally, in heroku and on production hosting.
But Stakblitz during loading messes something with styles and project fails to run. Please fix it, as i see its already higly often occurs at other users too.

Provide a concise description of your bug and your project link (if applicable).
https://stackblitz.com/edit/github-kayiva-mhtzhs?file=package.json

### **Steps to Reproduce**

1. Open Project
2. Wait until devserver starts
3. See error. 

### **Expected Behavior**
This error is only happens in Stackblitz (localhost, docker, heroku all green). 

### **Screenshots/Screencast**
Issue is self explanatory:
Error in src/styles.scss
Error: ENOENT: No such file or directory., '/dev/null'

**Additional Context/Questions**
none

**Comment by EricSimons** [comment]
@fedir-indutnyi what github repo did this come from? I think I may have a way to solve this if you can provide the repo URL

**Comment by fedir-indutnyi** [comment]
Hi, 
My repo is : https://github.com/fedir-indutnyi/sfrontend

**Comment by fedir-indutnyi** [comment]
Please let me know any findings. Project runs well on following: localhost on Win10 64x, Localhost Ubuntu, heroku, and Docker. Previously it was also able to run on Stackblitz, but since recent changes, doent work on stackblitz anymore.

**Comment by fedir-indutnyi** [comment]
> @fedir-indutnyi what github repo did this come from? I think I may have a way to solve this if you can provide the repo URL

Hi, any suggestions?
Best Regards, Fedir

**Comment by fedir-indutnyi** [comment]
Hi, our project still not working in StackBlitz

**Comment by PerryCodes** [comment]
I doubt leaving a comment each day is going to help your case.

**Comment by fedir-indutnyi** [comment]
Hi, sorry for reminding, does anyone looking into issue? 
I would like to move repo in the future and it will cause this bug here non reproduceable any more. 
@EricSimons, can we suggest any timing for resolving issues like it? I see many users are having same issue.

**Comment by EricSimons** [comment]
Hi- if you add ?preset=node to the end of the URL it should work: https://stackblitz.com/github/fedir-indutnyi/sfrontend?preset=node

**Comment by fedir-indutnyi** [comment]
Hi @EricSimons , 
Thank you very much for help. That resolves issue!!
Best Regards, Fedir
