### ISSUE TITLE
Can't view privately owned repository

### ISSUE THREAD

**Issue by victorbruce** [stackblitz/core#1483]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
adding "blitz" inside the URL that points to my personal private repository, I get the message

`Yikes! The page you requested couldn't be found.
If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core
`

### **Steps to Reproduce**

1. Go to a personal private repository
2. Add 'blitz' to the URL
3. See an error

### **Expected Behavior**
I was expecting to see the structure of my repository in the browser after adding "blitz" to the URL

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by jimmiefriberg** [comment]
Having the same issues at the moment

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
