### ISSUE TITLE
Create file system to manage and organize projects

### ISSUE THREAD

**Issue by RawZ06** [stackblitz/core#1486]
Hello, I suggest to implement a file system to organize projects into differents folders
I created figma design prototypes and I share to you
I redesign only the project list structure. 

Remember, actually is : 

![image](https://user-images.githubusercontent.com/44646690/120235270-f4cebf00-c259-11eb-9089-95841fff41f7.png)

Here is my suggestion :

![image](https://user-images.githubusercontent.com/44646690/120235188-cc46c500-c259-11eb-8a71-93564a1361a3.png)

The default page has two specific folders 
- Recents : This folder goes to all list of project, sort by updated date (like today)
- Favorites : This folder contains all favorite projects (for example, project in progress)

We can see a new folder created, "vuejs" with a description
Each projects has a new icon, a star, to favorite or not the project.

When we click to 'vuejs' folder, we are redirected inside the folder
![image](https://user-images.githubusercontent.com/44646690/120235487-6a3a8f80-c25a-11eb-8e52-87c038e013ca.png)

We have by default, '..' folder to come back home directory
We can create a new folder by clicking to "new directory"

![image](https://user-images.githubusercontent.com/44646690/120235529-8d653f00-c25a-11eb-9751-03f0552a4215.png)

And a popup appears and we can specify a name and description

To conclude, I suggest to add two elements in the more menu, "move project" and "rename project"
![image](https://user-images.githubusercontent.com/44646690/120235649-cef5ea00-c25a-11eb-859e-c0fc45eff55e.png)

This is a first version of design and maybe we can redesign it to have a better prototype, i'm not pixel perfect and some elements can be not aligned. Some colors can be review too.

**Comment by Pyrolistical** [comment]
this is an interesting idea. but i wonder if its more useful to just roll all the projects into the same webcontainer. then we can use the webcontainer filesystem to organize our projects

**Comment by RawZ06** [comment]
@Pyrolistical I don't know how will be used webcontainer, but we can have multiple projects that we share with diverses persons. 
I suggest that because it's more fast to fork a template than create a subdirectory in webcontainer and recreate project.

**Comment by Pyrolistical** [comment]
@RawZ06 ya, we can still share projects if everything was in one webcontainer filesystem. you would share folders containing projects like how mac/windows/smb file sharing works today, except its way easier as they will get a webcontainer link now

**Comment by d3lm** [comment]
@RawZ06 Interesting design ideas! And indeed better project organization is something we are working on and we'll keep you posted.

**Comment by EricSimons** [comment]
@Pyrolistical we've actually been toying with the idea of single FS as well- you may have noticed that the container mounts in the /projects folder atm. Our idea here is that we could have other projects existing in that same folder, so you could `cd` or orchestrate them more easily.

**Comment by Pyrolistical** [comment]
@EricSimons ya, multiple projects in one workspace is exactly how i setup my vs code locally.

in fact i have a rather cheeky folder structure. i create folders on where its stored.

so for example, for https://github.com/stackblitz/webcontainer-core, on my local computer, the git repo can be found at ~/github.com/stackblitz/webcontainer-core

**Comment by RawZ06** [comment]
@Pyrolistical Why not merge two methods, the first one is the home page can recognize all of projects to access one in particuliar and open a folder like a project with multiple project inside ?

We can add where there are "more" action, when it's a folder, the function "open as project" maybe ?
