### ISSUE TITLE
Get new project ID by creating new project or cloning new project

### ISSUE THREAD

**Issue by wonglok** [stackblitz/core#1487]
### **Is your feature request related to a problem? Please describe.**
Can I get new project ID by creating new project or cloning new project by using the JS API?
I want to be able to create new project using my code base and modify it programatically.  

### **Describe the solution you'd like**
is there a way to do this like:
let myNewProjectID = await SDK.createProject({ ...config })
let myClonedProjectID = await SDK.cloneProject({ ...config })

### **Describe alternatives you've considered**
i thought about embedding but it changes the template.

### **Additional context**
Add any context or screenshots about the feature request here.

https://www.instagram.com/p/CPZ541uDUW6/

**Comment by fvsch** [comment]
Hi @wonglok,

Sorry for the late reply.

The SDK cannot create content that is persisted on stackblitz.com, and we have no plans to make able to create persisted content at this time.

It does allow an end user to open or embed StackBlitz with content passed to the SDK's methods:
https://developer.stackblitz.com/platform/api/javascript-sdk#generate-and-embed-new-projects

And for embedded projects, the in-memory files can be modified or retrieved using the embed's `vm` object:
https://developer.stackblitz.com/platform/api/javascript-sdk-vm

But any persistence of data has to be a choice of end users on stackblitz.com (such as forking an embedded project), or managed by the page using the embedded StackBlitz editor (content will not be saved on StackBlitz).

**Comment by wonglok** [comment]
hi dear thank you for the update <3 wish u have a nice day :D
