### ISSUE TITLE
Google Pay payment sheet doesn't open in payment request window

### ISSUE THREAD

**Issue by socsieng** [stackblitz/core#1489]
### **Description of Bug**

Google Pay sample projects don't open the payment sheet in the payment request window as expected. Instead it opens up in a new window/tab.

Refreshing the preview window resolves the issue.
![image](https://user-images.githubusercontent.com/2647062/120361084-5294f280-c2be-11eb-8c4e-2ff824f0210c.png)

### **Steps to Reproduce**

Using Chrome:

1. Go to https://stackblitz.com/edit/google-pay-react
2. Click on the Google Pay button in the preview panel
3. Notice that the Google Pay payment sheet opens in a new tab (not expected)
4. Close the tab
5. Click the refresh button in the preview window
   ![image](https://user-images.githubusercontent.com/2647062/120361084-5294f280-c2be-11eb-8c4e-2ff824f0210c.png)
6. Click on the Google Pay button in the preview panel
7. Notice that the Google Pay payment sheet opens in the payment request window (expected) 

### **Expected Behavior**

Clicking on the Google Pay button (step 2) should open the Google Pay payment sheet in the payment request window.

**Additional Context/Questions**

I originally thought that this issue was due to a stray `;`, however, it doesn't appear to be the issue. See https://github.com/stackblitz/webcontainer-core/issues/49#issuecomment-848905302

The following example with webcontainers doesn't have the issue: https://stackblitz.com/edit/nextjs-nakdbt?file=pages%2Findex.js. The payment sheet opens in the payment request window as expected.

**Comment by SamVerschueren** [comment]
@socsieng I believe I finally managed to fix this correctly 😂 . Can you try it out and let me know 🙏 .

**Comment by socsieng** [comment]
Thanks @SamVerschueren. Can confirm that it's working.
