### ISSUE TITLE
npm package dependencies are not installed automatically

### ISSUE THREAD

**Issue by panick-carousel** [stackblitz/core#1495]
### **Description of Bug**
If an npm package is created that also has dependencies in its package.json file, then those dependencies are not installed in stackblitz.  

https://stackblitz.com/edit/react-wi4wgo?file=src%2Findex.js

### **Steps to Reproduce**
We have made a test npm package at https://www.npmjs.com/package/npm-ajv-test-stackblitz with a single dependency on ajv.  
Go to https://stackblitz.com/edit/react-wi4wgo?file=package.json and observe preview not showing, suggesting we install ajv as it is missing.

### **Expected Behavior**
Dependencies should be automatically installed.

### **Screenshots/Screencast**

**Additional Context/Questions**
Stackblitz is a much cleaner and smoother experience than codesandbox, but without this basic functionality being available consistently across all packages that we want to use on stackblitz, we cannot continue.

**Comment by kc0tlh** [comment]
@panick-carousel this issue has been resolved:

<img width="1436" alt="image" src="https://github.com/stackblitz/core/assets/1532264/65467a10-5f15-4325-9223-ecd0789df771">
