### ISSUE TITLE
Live demo not working on Firefox  80 nor 89.0

### ISSUE THREAD

**Issue by EliseoPlunker** [stackblitz/core#1496]
just the title indicate, live demo not working Firefox 89.0 
my FireFox:
89.0 (64-bit) for Windows 10 Home

**Comment by SamVerschueren** [comment]
Can you be more specific as to which project does not work for you? A link would be very helpful 🙏 .

**Comment by EliseoPlunker** [comment]
All, just create a new Angular, e.g. https://stackblitz.com/edit/angular-ivy-rvwqex

**Comment by fvsch** [comment]
Hi @EliseoPlunker. If you open the Console tab in Firefox DevTools and reload the project, do you see an error such as:

> Failed to register/update a ServiceWorker for scope ‘https://angular-ivy-rvwqex.stackblitz.io/’: Storage access is restricted in this context due to user settings or private browsing mode.

We’re currently having issues with Firefox’s “Third Party Isolation” feature (part of https://blog.mozilla.org/security/2021/02/23/total-cookie-protection/) which may block a feature we need for the StackBlitz editor and the preview page talk to each other.

One workaround is to disable Tracking Protection on stackblitz.com, by clicking on Firefox's "Shield" icon in the URL bar. Then the preview should work correctly:

![firefox-stackblitz-etp-off](https://user-images.githubusercontent.com/243601/121572896-ef752f80-ca24-11eb-9c6a-ca471c2e7811.png)

**Comment by fvsch** [comment]
In my tests with Firefox 89, you can keep Enhanced Tracking Protection *on* if it's on the "Standard" setting, and the preview should work:

![firefox-stackblitz-etp-standard](https://user-images.githubusercontent.com/243601/121573461-98238f00-ca25-11eb-85fa-173d46df6a8f.png)

If you're on the "Strict" setting, you will need to add an exception for StackBlitz and turn Enhanced Tracking Protection *off* for stackblitz.com.

**Comment by EliseoPlunker** [comment]
Sorry by delay and apologies my fault, (after go on your instructions not worked), but I delete the cookies of stackblitz and work perfect now. I imagine there're a limit about the cookies about the same direction acept Firefox. Many Thanks for your effort and time and I promise don't forget clean my cookies more frecuency.
