### ISSUE TITLE
Tooltip is not matching with the white theme

### ISSUE THREAD

**Issue by berakoc** [stackblitz/core#1498]
### **Description of Bug**
When I switched to the light theme, tooltips remains the same which reduces readability drastically.

### **Steps to Reproduce**

1. Choose the white theme from the bottom left corner.
2. Hover upon a function or method.

### **Expected Behavior**
A suitable tooltip for the white theme.

### **Screenshots/Screencast**
![Screen Shot 2021-06-07 at 20 44 02](https://user-images.githubusercontent.com/65181065/121065186-26eb9e00-c7d1-11eb-8ade-7664ea7b99d2.png)

**Comment by fvsch** [comment]
Thanks for the report @berakoc. This does look related to an issue we're seeing with the code editor colors in the light theme.

**Comment by fvsch** [comment]
@berakoc This should be fixed on stackblitz.com as of today. Feel free to comment if you still see something weird!
