### ISSUE TITLE
Stackblitz not working with angular 11 github repo

### ISSUE THREAD

**Issue by KostyaTretyak** [stackblitz/core#1499]
Although this example used to work, but now for some reason it does not work: https://stackblitz.com/github/KostyaTretyak/angular-example-simple-service

**Comment by Lonli-Lokli** [comment]
You are not alone,

https://github.com/stackblitz/core/issues/1481
https://github.com/stackblitz/core/issues/1479
https://github.com/stackblitz/core/issues/1468
https://github.com/stackblitz/core/issues/1462
https://github.com/stackblitz/core/issues/1458
https://github.com/stackblitz/core/issues/1439
https://github.com/stackblitz/core/issues/1437

Seems like maintainers prefer to focus on new features, unfortunately

**Comment by KostyaTretyak** [comment]
Oh, my repository was renamed, and that's probably why it stopped working.

**Comment by KostyaTretyak** [comment]
Now, with angular v12 its works.
