### ISSUE TITLE
Enable TypeScript in CRA preset

### ISSUE THREAD

**Issue by dlee** [stackblitz/core#15]
It would be nice to support Typescript for react projects like you do for Angular and Ionic.

**Comment by EricSimons** [comment]
This is actually already supported, it's just not linked from the homepage (yet :) — will add to homepage this wk! Till then, you can fork from here: https://stackblitz.com/edit/react-ts

**Comment by dwaq** [comment]
Is there a way to convert an existing project to support typescript?

For instance, I need to convert this file to typescript
![image](https://user-images.githubusercontent.com/1299430/29075393-3cc1f5ea-7c20-11e7-81ef-681f8df8e2b9.png)

but it doesn't allow me to change the file extension
![image](https://user-images.githubusercontent.com/1299430/29075422-50358d1c-7c20-11e7-9f81-be4bd056aebc.png)

I worked around this issue by forking your example above and importing my code, but that's bad UX.

**Comment by Meligy** [comment]
I'd suggest the following order:

![image](https://user-images.githubusercontent.com/171637/34338993-ee8fca76-e9c2-11e7-9a22-a3138fd37d43.png)

**Comment by OliverJAsh** [comment]
I was looking for a way to edit an existing React/JS project to enable TypeScript, but it doesn't seem possible. You have to start again with the provided fork.

**Comment by sulco** [comment]
React with TypeScript is now supported and available as one of the main starter projects on the homepage & dashboard.
