### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by lenpino** [stackblitz/core#150]
Trying to move an eclipse (webeclipse) project and compiles but doesn't run. The console error is:

preview-813c8235fc800996fae5.js:1 Error: reflect-metadata shim is required when using class decorators
  Evaluating https://angular-yrr1bg.stackblitz.io/tmp/appfiles/app/auth/auth.service.ts
  Evaluating https://angular-yrr1bg.stackblitz.io/tmp/appfiles/app/auth/auth-guard.service.ts
  Evaluating https://angular-yrr1bg.stackblitz.io/tmp/appfiles/app/app-routing.module.ts
  Evaluating https://angular-yrr1bg.stackblitz.io/tmp/appfiles/app/app.module.ts
  Evaluating https://angular-yrr1bg.stackblitz.io/tmp/appfiles/main.ts
  Loading app
i @ preview-813c8235fc800996fae5.js:1
preview-813c8235fc800996fae5.js:1 Uncaught (in promise) Error: Cannot parse given Error object
    at Object.parse (preview-813c8235fc800996fae5.js:1)
    at Object.<anonymous> (preview-813c8235fc800996fae5.js:1)
    at new Promise (<anonymous>)
    at Object.fromError (preview-813c8235fc800996fae5.js:1)
    at i (preview-813c8235fc800996fae5.js:1)
    at preview-813c8235fc800996fae5.js:1
    at <anonymous>

I really like your tool and I would like to use.

Thanks in advance

**Comment by EricSimons** [comment]
Are you importing polyfills.ts in your main.ts file? (This error usually happens when the polyfills are missing)

**Comment by lenpino** [comment]
I'm trying to just copy and paste a project from my eclipse (webeclipse from genuitec) to stackblitz. So far I'm amazed at how far I got but I found a weird problem and maybe it is a feature. 

It seems there is a limit on the size of things i can pour over. After a while my save button gives a status 413 and it won't save anymore (https://stackblitz.com/api/projects/webtgg 413 ())

is there a limit and I didn't read about it?

Thanks

**Comment by lenpino** [comment]
Status 413 was probably due to the fact that I was dragging and dropping an entire path (although the files weren't that many and their sizes small). Now I moved one directory at a time and the save button kept working. Until I tried to drag and drop image files.. then I got a status 500.

Thanks
