### ISSUE TITLE
Type autocomplete / tooltips don't work in .tsx files

### ISSUE THREAD

**Issue by tarngerine** [stackblitz/core#1500]
### **Description of Bug**
when a file is `.ts` everything works as expected, but `.tsx` files do not have things like tooltips when hovering over type definitions, or autocompleting based on type defs

https://stackblitz.com/edit/react-ts-czyg17?file=index.tsx

### **Steps to Reproduce**
see repro steps in project

you cant see my mouse but im hovering over AppState here
![image](https://user-images.githubusercontent.com/1629901/121262151-4a6a2380-c879-11eb-837f-dc8cd573feb8.png)

### **Expected Behavior**
see tooltip, can autocomplete

see how it works when file is named `index.ts`
![image](https://user-images.githubusercontent.com/1629901/121262120-3f16f800-c879-11eb-9a95-bc36636ef5e0.png)

**Comment by travislwatson** [comment]
Any update on this? Even basic suggestions such as keyword autocompletion do not work. This bug makes the React TypeScript template quite difficult to use.
