### ISSUE TITLE
Stackblitz does not work with components using react-jss

### ISSUE THREAD

**Issue by rvsia** [stackblitz/core#1501]
### **Description of Bug**

In our [Data Driven Forms](https://github.com/data-driven-forms/react-forms/) project we are using StackBlitz to show different versions of the same form using different design systems. Some of our packages are using [react-jss](https://github.com/cssinjs/jss/tree/master/packages/react-jss) to inject css, however, these projects cannot be run in StackBlitz: it shows an error: `Import error, can't find file: ./cjs/react-is.development.js`

### **Steps to Reproduce**

1. Go to https://data-driven-forms.org/provided-mappers/checkbox?mapper=blueprint
2. See the error in the example
3. Switch to PF4/Ant/MUI that are not using the react-jss packages
4. These examples work well

### **Expected Behavior**

No error

### **Screenshots/Screencast**

![Screenshot 2021-06-11 at 11 30 31](https://user-images.githubusercontent.com/32869456/121666715-d498ce80-caa9-11eb-8905-c779724e85f6.png)

**Comment by rvsia** [comment]
This done because `react-jss` import a wrong file in the bundle (`umd`) version.

Stackblitz should use `esm` (or `cjs` at least) build however.

**Comment by flashblaze** [comment]
Ran into this issue today

**Comment by rvsia** [comment]
@flashblaze I was able to fix it using a direct import of the requested module:

`react-jss` > `react-jss/dist/react-jss.{env}.js `

see https://github.com/data-driven-forms/react-forms/pull/1083/files

**Comment by flashblaze** [comment]
@rvsia thanks a lot for the quick response.
