### ISSUE TITLE
Error on attempt to create project by github link

### ISSUE THREAD

**Issue by akellbl4** [stackblitz/core#1505]
> Something went wrong with this repository.

Getting error when creating a project from the link https://stackblitz.com/github/akellbl4/next.js/tree/examples/with-bulma-pro-fix/examples/with-rbx-bulma-pro

**Comment by SamVerschueren** [comment]
It appears that the `package.json` is not correct. `react@17.0.3` and `react-dom@17.0.3` don't exist. You have to set them to `17.0.2` which is the latest. This should fix your problem.

![image](https://user-images.githubusercontent.com/1913805/121934040-15f9da00-cd47-11eb-846b-84859fc7d51c.png)

I'm adding some extra check that will allow opening it in StackBlitz if it's incorrect and then you should get a proper error message in the terminal.
