### ISSUE TITLE
Cannot use @material-ui/core in StackBlitz

### ISSUE THREAD

**Issue by anoop901** [stackblitz/core#1507]
### **Description of Bug**
When using @material-ui/core, StackBlitz prompts the user to install the @babel/runtime package. According to the [Material UI docs](https://material-ui.com/getting-started/installation/), this shouldn't be necessary. If the user installs @babel/runtime anyway, StackBlitz gives a "Invalid hook call" error, originating from what appears to be internal code (/turbo_modules/react@17.0.2/cjs/react.development.js).

### **Steps to Reproduce**

1. Create a TypeScript React project.
2. Add "@material-ui/core" library in the dependencies.
3. Use some components from it, like `<TextField />`.
4. StackBlitz prompts the user to install the @babel/runtime package. (This is already unexpected behavior.)
5. Click the button to install @babel/runtime.
6. See "Invalid hook call" error referencing /turbo_modules/react@17.0.2/cjs/react.development.js.

### **Expected Behavior**
The Material UI components should be usable, without a prompt to install additional libraries. Also, no errors should appear when the components are used correctly.

### **Screenshots/Screencast**
I encountered this issue while streaming. Here's the Twitch highlight: https://www.twitch.tv/videos/1056664818. The error is encountered near the end of the highlight, but I included extra for context.

**Additional Context/Questions**
When I tried the same thing in a local create-react-app setup with typescript, this issue did not occur.

**Comment by kc0tlh** [comment]
This issue has been resolved. Click the _Edit In StackBlitz_ link on any [Material UI Component](https://mui.com/material-ui/react-autocomplete/) to open immediately and begin prototyping!

<img width="1131" alt="image" src="https://github.com/stackblitz/core/assets/1532264/603acded-3779-4d79-86b4-da40ceb7e3d0">
