### ISSUE TITLE
i cant open this file https://stackblitz.com/edit/js-week4-2-hw-ltbjkd-juk7tq-iuvjg9

### ISSUE THREAD

**Issue by Tynai2005** [stackblitz/core#1513]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by purplem1lk** [comment]
Can you share how you got to this link/where you're copying this from? This would help us backtrack to figure out why you get an error. Thanks!

**Comment by Tynai2005** [comment]
thanks i have already solved this problem

чт, 29 июл. 2021 г., 23:28 Susan Ma ***@***.***>:

**Comment by purplem1lk** [comment]
Thanks for the update @Tynai2005! I will close this issue accordingly.
