### ISSUE TITLE
Cannot load tsx files

### ISSUE THREAD

**Issue by brianmhunt** [stackblitz/core#1519]
### **Description of Bug**
> Provide a concise description of your bug and your project link (if applicable).

Stackblitz doesn't import `.tsx` files in an ordinary Typescript project (non-React/Preact).

See: [tko-starter](https://stackblitz.com/edit/tko-starter)

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/tko-starter
2. See the error `Import error, can't find file: ./views/the-time`

### **Expected Behavior**
> A clear and concise description of what you expected to happen.

The `.tsx` file should be imported and run.

### **Screenshots/Screencast**
> If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/135528/124151013-1c36c880-da60-11eb-8ade-c3e543641c4e.png)

**Additional Context/Questions**
> Add any other context or questions regarding this bug.

Notes:
- `index.tsx` won't load, even when `package.json` has a `main` and `browser` of `index.tsx`.
- if it's possible, it's not clear where to specify these options in the documentation.
- `tsconfig.json` has `"jsx": "react"`, meaning `.jsx` and `.tsx` files will work fine locally
- manual building with e.g. `package.json` with `"start": "esbuild --bundle --serve=3000 index.tsx --servedir=."` with `esbuild` doesn't work (but yields different, entirely unrelated issues)
- I'd think there'd be a `startCommand` that would help, but I cannot find precedents or documentation to go on

**Comment by brianmhunt** [comment]
Noting that this would probably be closed by https://github.com/stackblitz/webcontainer-core/issues/8 i.e. esbuild or snowpack support. 

Esbuild/webpack isn't the only way this issue might be resolved because something like `ts-nodemon-dev` would probably work too, and that may be simplier/easier/faster than esbuild orsnowpack support.

**Comment by kc0tlh** [comment]
Here is a temporary solution from @apai4 while we work to improve the default behavior:

> You have to fork off of a react project to get JSX/TSX support, but we're missing a typescript feature that lets you customize the jsxFactory in tsconfig.json . I hacked around it by adding window.React = {createElement: tko.jsx.createElement} to one of the files (src/tko.ts)

https://stackblitz.com/edit/tko-starter-ghw4mk?file=src%2Fviews%2Fthe-time.tsx

**Comment by brianmhunt** [comment]
Thanks for the suggestion & cleanup @kc0tlh !
