### ISSUE TITLE
CORS error using StackBlizt

### ISSUE THREAD

**Issue by ThomasBurleson** [stackblitz/core#152]
See [Blitz Demo](https://stackblitz.com/edit/angular-http-observables-ase518?file=app/sw-people.service.ts)

![screen shot 2017-09-29 at 5 34 10 pm](https://user-images.githubusercontent.com/210413/31038472-9bbd55cc-a53c-11e7-80e4-d6f148bdc0f2.png)

**Comment by EricSimons** [comment]
It looks like starwars-api.com isn't an actual website — were you looking for https://swapi.co?

I updated the URL to point at it and the service's logic and it works: https://stackblitz.com/edit/angular-http-observables-9nchvz?file=app/sw-people.service.ts

**Comment by ThomasBurleson** [comment]
Okay, that was embarrassing. 
Sorry to submit an issue that I should have solved on my own. 

Regardless: Thank you.
