### ISSUE TITLE
Something went wrong with this repository - unexplained error

### ISSUE THREAD

**Issue by artart37** [stackblitz/core#1530]
After updating my Angular project to 12.1.0, all of a sudden I am receiving the below error on Stackblitz:
IMPORTING FROM GITHUB
artart37CandiAgents
Something went wrong with this repository.
If you think this is a bug, please file an issue in our repo!

Even after deleting the repository and relaunching it several times, I am still unable to deploy my project on Stackblitz and the error is unexplained.

**Comment by aziz52** [comment]
Facing same issue with my angular 12 repository.

Here's the link to the issue that I have created

https://github.com/stackblitz/core/issues/1528
