### ISSUE TITLE
How to import private repo?

### ISSUE THREAD

**Issue by juzhiyuan** [stackblitz/core#1531]
### **Description of Bug**

Hi, when I visit `https://stackblitz.com/github/{Username}/{repo}`, it shows:

![image](https://user-images.githubusercontent.com/2106987/124882007-8ae8c880-e002-11eb-82bc-8963dbbe53a2.png)

This is a private repo :)

**Comment by juzhiyuan** [comment]
Maybe not a bug, just don't support private repo? 🤔

**Comment by Damato** [comment]
If I sign-up using my Github Account then it is an auth request away from accessing the private Repository. GitPod does the same GitPod.io/{user}/{repo} - without issue. Using private repositories is what the paid tiers are about. Without it, the free tier is good enough, and the product offering falls short.

**Comment by purplem1lk** [comment]
Hey @juzhiyuan - Thanks for your patience! If you have the Astronaut or Commander membership, you have the ability to work with private repos. Here is a video that outlines how you can access a private repo: https://www.loom.com/share/54c9f65e05494b00b6aa1bb9e0bbe7ab

If your issue persists, please tag me so we can dive further. Thank you! :)

**Comment by juzhiyuan** [comment]
Hi, I just purchased with Commander membership, when I visit `https://stackblitz.com/github/juzhiyuan/blog` according to https://developer.stackblitz.com/docs/platform/importing-projects#import-from-github , it still shows

![image](https://user-images.githubusercontent.com/2106987/127790315-f1e5b6e4-82a6-4cb8-a56f-0bf49e1e859c.png)

**Comment by purplem1lk** [comment]
@juzhiyuan Could you try importing this through the instructions below and send me a screenshot of what you see?

1. Go to your dashboard and open a new JavaScript blank project
2. Click on 'Connect repository' on the top left
3. Click on the 'importing from an existing repository' link
4. Paste your full GitHub repo URL

Thank you!

**Comment by juzhiyuan** [comment]
sure

![image](https://user-images.githubusercontent.com/2106987/127802904-a06f8378-dbb2-43f8-bd1c-ed119961eea6.png)

![image](https://user-images.githubusercontent.com/2106987/127802923-c5e86389-e436-4c7b-984b-8b182b96beff.png)

**Comment by purplem1lk** [comment]
Hey @juzhiyuan - It looks like you created a new repository versus importing the existing repository. Does this work for your use case or were you wanting to import your existing repo? If you want to import an existing repo, make sure you click on the 'import an existing repository' link in the popup after you click "Connect repository", highlighted in green below:
 
![Screen Shot 2021-08-02 at 4 17 09 PM](https://user-images.githubusercontent.com/49956513/127918533-c1117f50-940e-4d82-9fb5-61cb1942f42e.png)

Let me know if this works for you!

**Comment by Damato** [comment]
@purplem1lk An excellent example of why a company needs a good UX team. That link is hidden completely, if that was the aim then the design was a success. 

Unless you hovered over it, it is as good as non existent :-D

**Comment by juzhiyuan** [comment]
> why a company needs a good UX team

🤣🤣 Our team is looking forward to a good UED team, we are working on Cloud-Native API Gateway.

http://apisix.apache.org/ and https://www.apiseven.com/

**Comment by juzhiyuan** [comment]
@purplem1lk Ya, it works when I click the `import` link 🤣🤣

**Comment by purplem1lk** [comment]
@Damato Thanks for the feedback! This is helpful for our team to add to our UX improvements. :)
