### ISSUE TITLE
Cannot find module './home/home.compoent'

### ISSUE THREAD

**Issue by TLKG** [stackblitz/core#1532]
### **Description of Bug**
StackBlitz unable to import

### **Steps to Reproduce**

1. Go to 'https://stackblitz.com/edit/angular-ivy-aercgm?file=src/app/app.module.ts'
2. Scroll down to line 9 and 10
4. See error highlighted for both lines

### **Expected Behavior**
Both `login` and `home` were generated via UI's Angular Generator, so they're inserted by Stackblitz, still show error.

![image](https://user-images.githubusercontent.com/22269729/124999183-74db0800-e002-11eb-949b-bfaf3bf674ba.png)

**Comment by purplem1lk** [comment]
Hey @TLKG - Thanks for your patience! Below is a screenshot of what I see with the StackBlitz project link you provided. Are you still getting the errors you posted? If so, can you post a screenshot of the error popup that shows up? Thank you! :)

![Screen Shot 2021-08-01 at 7 02 16 PM](https://user-images.githubusercontent.com/49956513/127787851-d4894bb5-596f-414c-9fbf-d954a0a56ecb.png)

**Comment by TLKG** [comment]
I'm all good now, appreciate it!
