### ISSUE TITLE
not able to upload project to stackblitz

### ISSUE THREAD

**Issue by srujankulkarni** [stackblitz/core#1533]

**Comment by TheTiGuR** [comment]
@srujankulkarni - Please provide some more information about what problems you are having, and the steps that can be taken to reproduce your issue. Thanks!

**Comment by purplem1lk** [comment]
Hello! This issue will be closed due to inactivity and insufficient info for us to investigate further. If your issue persists, please tag me and provide a StackBlitz project link and any relevant screenshots. Thank you! :)
