### ISSUE TITLE
embedGithubProject does not compile correctly

### ISSUE THREAD

**Issue by brianmhunt** [stackblitz/core#1536]
### **Description of Bug**
> Provide a concise description of your bug and your project link (if applicable).

`StackBlitzSDK.embedGithubProject` seems to not create the correct type of project.  In this case, it should create a React project (as a workaround to #1519)

- Noting #1519

I would imagine this issue would be fixed up with a number of ambitions that already appear on the Stackblitz roadmap (snowpack, esbuild).

### **Steps to Reproduce**

1. open the following HTML

```html
<html>
    <body>
        <div id='r'></div>
        <script src="https://unpkg.com/@stackblitz/sdk/bundles/sdk.umd.js"></script>
        <script>
        StackBlitzSDK.embedGithubProject('r', 'knockout/tko/tree/bmh/stackblitz-example/examples/stackblitz-starter')
        </script>
    </body>
</html>
```

2. Note that the behaviour is different from the otherwise seemingly identical project: https://stackblitz.com/edit/tko-starter-cqbfx8

### **Expected Behavior**
> A clear and concise description of what you expected to happen.

The github repo slug was created by downloading the project from Stackblitz.  One would expect items downloaded would be idempotent, but there seems to be some hidden config or creation parameter that causes the embed to use (or not) the React template.

### **Screenshots/Screencast**
> If applicable, add screenshots to help explain your problem.

Here's what the `index.html` with the embed shows (noting the output - ignore the editor):
![image](https://user-images.githubusercontent.com/135528/125203168-63ce0900-e245-11eb-9ff6-d2a5df19bc11.png)

Here's what I'd expect it to show:
![image](https://user-images.githubusercontent.com/135528/125203194-76e0d900-e245-11eb-8fd4-c752d593ce8a.png)

**Additional Context/Questions**
> Add any other context or questions regarding this bug.

You're doing great work here! 🥂 I hope this is something that'll be fixed up in the near term with items already on your roadmap.  Cheers & thanks

**Comment by Andrew-web-coder** [comment]
I believe this project is dead so I find it funny that you mentioned the roadmap.

**Comment by brianmhunt** [comment]
> I believe this project is dead so I find it funny that you mentioned the roadmap.

There are commits happening, support is responsive, and there are [recent and ambitious blog posts](https://blog.stackblitz.com/posts/update-2021-06/)

@Andrew-web-coder Why do you think this project is dead?

**Comment by Andrew-web-coder** [comment]
> There are commits happening, support is responsive

Where? Looks like I am blind, because I do not see any activity. Zero responses to issues, the last semi-meaningful commit was on Sep 26, 2020.

**Comment by brianmhunt** [comment]
@Andrew-web-coder https://github.com/stackblitz/core/issues/1519

**Comment by Andrew-web-coder** [comment]
So, they are randomly closing stupid issue posts and that indicates the activity? How do you explain 0 responses to #1497 ?

**Comment by kc0tlh** [comment]
Hey @apai4, FYI @brianmhunt is attempting to import the modified "stackblitz compatible" TKO starter from Github with the `StackBlitzSDK.embedGithubProject` function and it appears to not create a React project. Highlighting this for you/the team as I think it ties into the current Github workflow sprint.
