### ISSUE TITLE
Cant import project from github

### ISSUE THREAD

**Issue by Crispy-rw** [stackblitz/core#1538]
I cant import a project from github. It saying i cant import a project without a package.json and the project i want to import is html and css

**Comment by Damato** [comment]
How did you even get there, the link seems to be broken? 
`stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}`

**Comment by purplem1lk** [comment]
Hi @Crispy-rw - Thanks for your patience. Can you post the StackBlitz project link and/or GitHub repo so we can reproduce this, as well? :)

**Comment by kc0tlh** [comment]
This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! More info about the new integration in Github issue #2473
