### ISSUE TITLE
Not working on OpenWerewolf repo

### ISSUE THREAD

**Issue by ngrosso1** [stackblitz/core#1539]
Does not seem to work for https://github.com/JamesCraster/OpenWerewolf

**Comment by purplem1lk** [comment]
Hey @ngrosso1 - Thanks for your patience. I tried these steps and ended up with the errors in the screenshot below:

1. Open a JavaScript blank project
2. Click 'Connect Repository' on the top left
3. Click the 'import from an existing repository' link
4. Paste the whole GitHub repo link

Can you confirm if you are seeing this error, as well?

![Screen Shot 2021-08-01 at 7 36 24 PM](https://user-images.githubusercontent.com/49956513/127788617-66471989-b046-4b90-a38f-2e017c17e281.png)
