### ISSUE TITLE
Breaks without styles.css file

### ISSUE THREAD

**Issue by lazarljubenovic** [stackblitz/core#154]
Deleting `styles.css` file break the blitz. Super low priority issue, but would be nice if we could delete the file if we're not using it. It's nice to keep file numbers to minimum not to scare newcomers to frameworks, so I try to remove everything that's not relevant to the demo :smile:

**Comment by EricSimons** [comment]
@lazarljubenovic oh no! If you remove the `styles.css` from the angular-cli.json file, it should resolve itself. I think I have some ideas on how we could better alert users about this :)

**Comment by lazarljubenovic** [comment]
Whopes, my bad. I just assumed that it was referencing it somewhere in the "parent" markup that we don't see when editing. I think just prepending the error with the source of the error would clear things up a bit. Like, which package/process/whatever screams at you?

Anyway, thanks for the response!
