### ISSUE TITLE
Project cannot be pushed to new GitHub repository

### ISSUE THREAD

**Issue by peterph55** [stackblitz/core#1540]
### **Description of Bug**
If you delete GitHub repository which is used in Stackblitz project you are unable to push new repository and Errors are displayed.

### **Steps to Reproduce**

1. Create new Stackblitz project
2. Connect to GitHub, create new repository and push this project with Stackblitz
3. Delete repository on GitHub
4. When you open project on Stackblitz again _Error: HTTP Error: 404_ is shown and project is connected to unexisting repository. You are unable to create new repo.

### **Expected Behavior**
Stackblitz project should be disconnected from unexisting GitHub repo.
There should be an option to disconnect from GitHub repo.

**Comment by fvsch** [comment]
Hi @peterph55. We've added a "Disconnect Repository" option in the project's settings sidebar, which should let you pair your project to a different repository.
