### ISSUE TITLE
unable to use dart-sass new features

### ISSUE THREAD

**Issue by Aleksandyr** [stackblitz/core#1559]
### **Description of Bug**
Probably stackblitz does not support the new dart-sass compiler?

### **Steps to Reproduce**

1. Open the following [sample](https://stackblitz.com/edit/github-8suzpa)

### **Expected Behavior**
Should be able to take advantage of the latest dart-sass features

**Comment by markwhitfeld** [comment]
Hi @Aleksandyr 
We do support Dart SASS, and have done so since the beginning of the year.
I'm trying to figure out what the issue is with your StackBlitz project though. There is a weird reference in your `package.json` that is causing issues:
![image](https://user-images.githubusercontent.com/1948265/126966329-bdb05094-a544-4bdf-9861-af3dea3c65fe.png)
Do you have the original github repo that this is imported from?

**Comment by markwhitfeld** [comment]
I removed the strange import and got this error:
![image](https://user-images.githubusercontent.com/1948265/126969347-3b466b7c-300c-45a0-b6b0-4d6adcb34371.png)
Then I upgraded to `12.1.0-alpha.7` and it works great.
See this fork of your repo:
https://stackblitz.com/edit/github-8suzpa-iqxbyp?file=package.json

**Comment by Aleksandyr** [comment]
@markwhitfeld This is [Infragistics Angular UI Components](https://github.com/IgniteUI/igniteui-angular) suite where we are using some of the latest feature dart sass introduces in ^1.33.0v. like **div** func of **math** module.

In the latest version of Igniteui for Angular -alpha.7 we are introducing a [workaround](https://github.com/IgniteUI/igniteui-angular/pull/9905) which basically uses the divider symbol instead of **div** func if that function doesn't exist. That is why with the latest **alpha** everything works perfectly. 

Which version of dart sass you are using?

**Comment by markwhitfeld** [comment]
We are using `v1.30.0` at the moment.
I'll test against the `alpha-3` version and upgrade to `sass@1.36.0` to see if it works before your fix.

**Comment by Aleksandyr** [comment]
Great!

**Comment by Aleksandyr** [comment]
@markwhitfeld It seems that you have updated the **sass** version and all latest features are working. I assume that we can close that issue.
