### ISSUE TITLE
feature request: project template from github

### ISSUE THREAD

**Issue by airtonix** [stackblitz/core#156]
Let us store project templates on our github.

we could keep them private (only my stackblitz account), or publish them to a common library.

**Comment by EricSimons** [comment]
@airtonix what kind of project templates would you be storing on github? Just trying to get an idea of what your use case is :)

**Comment by beeman** [comment]
Since last week we have deployed the option to sync projects to GitHub, and you can also enable private projects!

![stackblitz-privacy](https://user-images.githubusercontent.com/36491/55047352-74c1c480-5012-11e9-9e0c-81d4ab3c5a2d.gif)
