### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by prashantkhade19** [stackblitz/core#1560]
whenever i opened my github repo with stackblitz it show error that  package.json file is missing

**Comment by purplem1lk** [comment]
Hey @erprashant9897 - Can you provide a StackBlitz project link, your GitHub repo link, and any associated screenshots with your error? This info will help us dive further into your issue. Thank you! :)

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
