### ISSUE TITLE
Next.js + TS template

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/core#1564]
I need a Next.js + TypeScript template instead of just JS.

I think most people start projects nowadays with Next.js instead of CRA as it's just so faster & simpler.

**Comment by purplem1lk** [comment]
Hey @deadcoder0904 - Thanks for reaching out. You can find the Next.js template (beta version, no TypeScript yet) in your dashboard. The team is actively working to fix any immediate bugs so if you have any questions when using this template, I recommend checking out the [webcontainer repo](https://github.com/stackblitz/webcontainer) for any updates/existing bug reports and feature requests. Thank you! :)

(I also see #1562 and we are working to debug and resolve this as soon as we can so thanks for your patience!)

![Screen Shot 2021-08-01 at 7 57 20 PM](https://user-images.githubusercontent.com/49956513/127789152-e17ec32b-93fb-442a-bc98-de35dbf16719.png)

**Comment by deadcoder0904** [comment]
Why is this closed?
