### ISSUE TITLE
I am trying to importing project from GitHub

### ISSUE THREAD

**Issue by patilshrikant77** [stackblitz/core#1565]
GitHub/patilshrikant77/microfrontend-control-center

Something went wrong with this repository.
If you think this is a bug, please file an issue in our repo!

GO BACK

**Comment by deadcoder0904** [comment]
Duplicate https://github.com/stackblitz/core/issues/1562

**Comment by kc0tlh** [comment]
The Github import functionality is now working in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
