### ISSUE TITLE
stackblitz can't find core-js and it won't successfully install it

### ISSUE THREAD

**Issue by webmandman** [stackblitz/core#1566]
### **Steps to Reproduce**
https://stackblitz.com/edit/angular-slemqj-x62ebw?file=main.ts

### **Expected Behavior**
it should compile the app and serve it.

**Comment by BenRacicot** [comment]
Just experienced this after reading that core-js is handled internally now in regards to the Angular CLI. 

<img width="1273" alt="Screen Shot 2021-12-14 at 1 12 57 PM" src="https://user-images.githubusercontent.com/1815385/146056238-b91649a0-2ae6-46f7-97bb-0a0696e5f1c9.png">

With or without core-js I cannot load the SB without error.
