### ISSUE TITLE
Standard template, gallery & forking first system

### ISSUE THREAD

**Issue by JikkuJose** [stackblitz/core#157]
It would be great to have some projects promoted like starter kits. Perhaps with some default packages and minimum setup so that people can easily fork and go about their work.

Look at CodePen's galleries for inspiration, I would assume a lot of their usage is coming from forking of existing projects.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
