### ISSUE TITLE
Now that ESM is supported, can ESM-using framework(s) be added to the home page list of examples?

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/core#1572]
### **Is your feature request related to a problem? Please describe.**

Now that ESM is supported, EmberJS now works with StackBlitz :tada: 

here is the URL: https://stackblitz.com/github/ember-cli/ember-new-output
 - this url is automatically updated with the output of `ember new` every release (every 6 weeks for the stable release train)

Since I want StackBlitz to be _the_ thing folks use for reproducing issues, reporting bugs, sharing ideas, etc, I think it'd be great to have a quick link to Ember from the home page.

### **Describe the solution you'd like**

 - link to ember stackblitz link on home page
 - default to having the terminal open
 - default to also running `npm start` once install finishes
 - default file: `application.hbs`: https://stackblitz.com/github/ember-cli/ember-new-output?file=app%2Ftemplates%2Fapplication.hbs
 
 I think this would need to be  fixed: https://github.com/stackblitz/core/issues/1571, but otherwise, I think this experience would be totally legit

### **Describe alternatives you've considered**

We could just share links around with folks, but then there isn't a "source of truth", ya know?
Like, one thing I want to do, (especially once firefox is supported), is change the ember codesandbox template to point at stackblitz saying that the codesandbox is deprecated.

### **Additional context**

I'm sure ya'll know this, but having an online environment for sharing _anything_ JS related that requires tooling has been a big pain, and Stackblitz looks like it's solving everything that open source communities need. <3

**Comment by purplem1lk** [comment]
Thanks for the kind words! This will definitely be added to our Examples page, which is going through a nice revamp at the moment. Thanks for all the info and we'll report back and close this issue once the revamp is done. Thanks for your support! :)

**Comment by fvsch** [comment]
Looks like we cannot currently run Ember.js, due to incompatibilities with WebContainers, in particular with the `esm` package. I’m going to close this issue in favor of https://github.com/stackblitz/webcontainer-core/issues/354 (technical support for Ember.js), since there's no sense in adding a starter that doesn't work. :)
