### ISSUE TITLE
Provide custom jsxImportSource to monaco-editor

### ISSUE THREAD

**Issue by modderme123** [stackblitz/core#1577]
### **Description of Bug**
`*.tsx` files don't seem to respect the jsxImportSource field, and instead shows `Cannot find name 'React'.(2304)` over JSX tags.
 
### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/solid-vite?file=src%2Findex.tsx
2. Hover over `<button`
4. See `Cannot find name 'React'.(2304)`

### **Expected Behavior**

I would expect the autocomplete to respect the JSX import source and show type completion instead.

**Additional Context/Questions**

Note that `npx tsc` returns no errors

**Comment by modderme123** [comment]
This looks to be fixed, thanks!

**Comment by SamVerschueren** [comment]
I couldn't find the issue anymore but I wanted to let you know that we fixed it :). If you run into other issues regarding `tsconfig.json`, feel free to create a new issue.
