### ISSUE TITLE
Ability to fully embed into the your application?

### ISSUE THREAD

**Issue by ktalebian** [stackblitz/core#1581]
I am using the following code:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
    <script src="https://unpkg.com/@stackblitz/sdk/bundles/sdk.umd.js"></script>
</head>
<body>
    <div id="foo"></div>
    <script>
        // Create the index.ts file
        const code = `document.getElementById('time').innerHTML = new Date();
        `;

        // Create the index.html file
        const html = `<h1>I was created on <span id='time'></span></h1>`;
        StackBlitzSDK.embedProject(
            'foo',
            {
                files: {
                    'index.js': code,
                    'index.html': html,
                },
                template: 'javascript',
            },
            {
                view: 'preview',
                hideExplorer: true,
                hideNavigation: true,
                forceEmbedLayout: true,
            }
            );
    </script>
</body>
</html>    
```

This results in the following:

![image](https://user-images.githubusercontent.com/2308915/129403024-5569fab2-aefc-4586-8f56-9bc22936b074.png)

This still contains the "browser" interface of Stackblitz - how do I embed this as a native component into my application? i.e. I just want to see the `I was created on Fri Aug 13 2021 11:23:14 GMT-0700 (Pacific Daylight Time)` text without any footer and URL header/browser.

**Comment by kc0tlh** [comment]
This feature is not, and will not be supported with the StackBlitz Classic editor _however_ you can accomplish this type of use case with the [WebContainer API](https://webcontainers.io/) or simply by integrating the functionality contained in your StackBlitz directly into your main application.
