### ISSUE TITLE
Top level await in TypeScript project does not work

### ISSUE THREAD

**Issue by pixelbucket-dev** [stackblitz/core#1582]
### **Description of Bug**
Despite configuring the tsconfig.json as described, the code still does not compile and puts out errors.

### **Steps to Reproduce**

1. Create a new project from the TS template.
2. Create a top-level await call (e.g. use a `Promise.resolve`).
3. The `await` keyword is highlighted in a red squiggly underline. The console shows an error 
> await is only valid in async functions and the top level bodies of modules
4. Configure your `tsconfig.json` with 
>  "target": "esnext",
    "module": "esnext",
    
    as advised by the error hint.
5. Above errors still occur and compilation fails.

### **Expected Behavior**
No errors. It should just compile.

### **Screenshots/Screencast**
<img width="654" alt="Screenshot 2021-08-14 at 12 04 41" src="https://user-images.githubusercontent.com/12937991/129444369-c7072fa0-1717-4d22-9759-a708093065ad.png">

**Comment by geromegrignon** [comment]
Here is a reproduction of the issue : https://stackblitz.com/edit/typescript-n6cabr?file=tsconfig.json
