### ISSUE TITLE
在工具中console出来的结果索引跟浏览器中console控制台打印的结果不相同？？？？

### ISSUE THREAD

**Issue by yaolifeng0629** [stackblitz/core#1588]
具体代码
//这个是获取到的数组，我这里写的空对象
let arr = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {}
];
let res = [];
for (let i = 0; i < arr.length; i = i + 8) {
  if (i + 8 < arr.length) {
    res.push(arr.slice(i, i + 8));
  } else {
    res.push(arr.slice(i));
  }
}
res.forEach(function(item) {
  return item.length === 8
    ? item.push({
        name: '张三'
      })
    : item;
});
let result = [].concat.apply([], res);
console.log(result);
问题：log出来的结果索引跟浏览器中的结果不相同？？？

**Comment by SamVerschueren** [comment]
My chinese is a bit rusty.

But if you mean this output:
![image](https://user-images.githubusercontent.com/1913805/130223501-a095dc21-72dd-4fd9-98eb-0a424b78f529.png)

Then yes, the order is incorrect. It's already tracked here https://github.com/stackblitz/core/issues/1412.

If that's not what you meant, please open a new issue in English, would make communicating a bit easier ;).
