### ISSUE TITLE
Github login / account recovery

### ISSUE THREAD

**Issue by tripsimian** [stackblitz/core#1590]
### **Description of Bug**
I recently converted my GitHub personal account to an organization.  It had the unintended side effect of breaking the OAuth login in Stackblitz.  I would like to recover or otherwise reset my login (Github user account is still tripsimian@gmail.com).  

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by kc0tlh** [comment]
@apai4 please delete [ani.expo10@gmail.com](mailto:ani.expo10@gmail.com) from StackBlitz.com completely and close this issue when complete. Thanks!

**Comment by kc0tlh** [comment]
@tripsimian your account was successfully reset in March! I will now close this issue.
