### ISSUE TITLE
sdas

### ISSUE THREAD

**Issue by fazliddin51998** [stackblitz/core#1592]

**Comment by purplem1lk** [comment]
Hello - This issue will be closed due to lack of description of the feature request or bug report that you are reporting. If you have an issue to share, please provide a clarifying issue for our team to look into. Thank you!

**Comment by fazliddin51998** [comment]
https://stackblitz.com/github/fazliddin51998/vue-testa

Hi! When I open this page (
Something went wrong with this repository.

If you think this is a bug, please file an issue
<https://github.com/stackblitz/core/issues/new> in our repo!
)
Show me what type of error why it is error but in my local comp it is worked
вт, 31 авг. 2021 г. в 18:11, Susan Ma ***@***.***>:
