### ISSUE TITLE
Refused to display 'https://stackblitz.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by Eonasdan** [stackblitz/core#1595]
### **Description of Bug**
Using the embed options from one of my projects I thought I could plop it into an Iframe on my blog. Unfortunately, I'm just getting the error in the title. :(

### **Steps to Reproduce**

1. Go to 'https://eonasdan.com/posts/creating-a-har-file-with-angular.html'
3. Scroll down to 'Angular'
4. See iframe error.

### **Expected Behavior**
Embedded StackBlitz magic.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/1006516/131942000-fa0917ec-aca1-4e54-84e2-482ebf8efe15.png)

**Comment by thescientist13** [comment]
@Eonasdan 
You might want to double check the `src` value of your `<iframe>`.  For example, I get a 404 from stackblitz.com if I try and open https://stackblitz.com/github/xoriavgxz just through the browser.
![Screen Shot 2021-09-03 at 11 33 01 AM](https://user-images.githubusercontent.com/895923/132031325-06a78e0f-aa06-4756-bcc9-5be636734231.png)

However, if I use the URL from your link that includes GitHub org + repo name (`https://stackblitz.com/github/Eonasdan/angular-har-generator?file=src/app/activity-watcher.ts`) it works (though you'll likely need to apply some CSS to expand the viewport of the `<iframe>`
<img width="1673" alt="Screen Shot 2021-09-03 at 11 34 19 AM" src="https://user-images.githubusercontent.com/895923/132031503-d6ccdbfd-d239-4ae2-8e2e-61b4d5f0ca76.png">

----

As a tip, you can append `?embed=1` for a "cleaner" wrapper around VSCode in the iframe
<img width="1126" alt="Screen Shot 2021-09-03 at 11 38 18 AM" src="https://user-images.githubusercontent.com/895923/132031744-dd7b492a-0b66-4798-8b2c-2a1973afd272.png">

**Comment by Eonasdan** [comment]
Looks like after that change and allowing the cookies it works. Bootstrap 5 has a nice `ratio ratio-1x1` that made the iframe play nicely. Thanks for the help.
