### ISSUE TITLE
Vue 3 starter uses old version of Vue 3

### ISSUE THREAD

**Issue by tony19** [stackblitz/core#1599]
### Describe the bug

The [official Vue 3 starter](https://stackblitz.com/fork/vue) currently uses `vue@3.0.0`, which has several bugs and is missing some interesting features that have since been added (including `<script setup>`). As of today, the latest release is [`vue@3.2.8`](https://github.com/vuejs/vue-next/releases/tag/v3.2.8). Can the blitz be updated to use `@latest`?

### Link to the blitz that caused the error

https://stackblitz.com/edit/vue-get-version?file=src/App.vue

### Steps to reproduce

1. Go to blitz
2. Observe the Vue version displayed in the preview window is 3.0.0 instead of the latest release (3.2.8 as of today).

### Expected behavior

The latest release of `vue` is used.

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84258812,
  "usedJSHeapSize": 76398200,
  "jsHeapSizeLimit": 4294705152
}
Hash = dd88a1655a6ea3f646b7279b57a2839a424ce920
```

**Comment by d3lm** [comment]
I have moved this issue from `webcontainer-core` because it's not related to WebContainer.

**Comment by tony19** [comment]
An easy workaround is to simply reinstall `vue` from the dependencies panel, which gets the latest version.
