### ISSUE TITLE
Next.js private repos with a custom branch don't clone properly - Not Found.

### ISSUE THREAD

**Issue by altechzilla** [stackblitz/core#1601]
### **Description of Bug**
Next.js private repos with a custom branch don't clone properly - it says Not Found.

### **Steps to Reproduce**

1. Create a new Next.js repo
2. Click the Connect to Repo, and then Import
3. Enter a private GitHub repo with a custom branch (tree/staging) (from the same organization as the user being logged in)
4. It says Not Found

### **Expected Behavior**
Should clone and overwrite the current project

### **Screenshots/Screencast**
https://share.getcloudapp.com/6quYJBDe

**Comment by geromegrignon** [comment]
@altechzilla  Can you update the title to `[Bug] Can't connect to a non default branch of a repository`(as it happens on public repos too)?

Here is the link to the staging branch of a public repo to reproduce the issue: https://github.com/geromegrignon/prisma-test/tree/staging
