### ISSUE TITLE
Yikes! It looks like there's already an account with your username or email

### ISSUE THREAD

**Issue by thorstenjung** [stackblitz/core#1602]
### **Description of Bug**
I want to sign in with my github account, but i only get following message: Yikes! It looks like there's already an account with your username or email

Day‘s ago i deleted my old github account and recreated it (don‘t ask why :-) ). Unfortunatley, i can‘t sign in on stackblitz.

On discord they said, that I‘ve to send an email to hello@stackblitz.com. I did, but i don‘t get a answer.

### **Steps to Reproduce**

1. Go to 'stackblitz.com'
2. Click on 'sign in with github'
3. See error: Yikes! It looks like there's already an account with your username or email

### **Expected Behavior**
I want to sign in without errors :-)

**Comment by pratheeshps** [comment]
> ithout errors :-)

**Comment by kc0tlh** [comment]
@thorstenjung this issue should now be resolved. See Issue #1402 for more info!
