### ISSUE TITLE
Can't find npm packages In stackblitz

### ISSUE THREAD

**Issue by nicoleoliveira** [stackblitz/core#1605]
### **Description of Bug**
Hi, can't find npm packages In stackblitz, even though it is present in npm website.
NPM registry: https://registry.npmjs.org/@animaliads/ani-switch
Error stackblitz:
![error](https://user-images.githubusercontent.com/17319734/133613278-35e5889b-8bf1-40b8-8dbd-e199af912ecf.png)

### **Steps to Reproduce**

1. Go to stackblitz project
2. Install package @animaliads/ani-switch

**Comment by vdolek** [comment]
I have the same problem with new npm packages and new versions.

**Comment by larscom** [comment]
Have the same.. i thought this issue was fixed recently.

![Screenshot_20211127_173750](https://user-images.githubusercontent.com/1215195/143689541-8cadf037-8b76-4eca-8128-2960fb9cfce1.png)

**Comment by markwhitfeld** [comment]
Hi @larscom. Would it be possible to provide a link to the project you are having the issue with?

**Comment by larscom** [comment]
@markwhitfeld see: https://stackblitz.com/edit/ngx-translate-module-loader

thanks!

**Comment by markwhitfeld** [comment]
@larscom Both of these issues are related to NG13 support (something we have been working hard on for the past month).
`@ngx-translate/core` has a dependency on NG13, and your `@larscom/ngx-translate-module-loader` package has been compiled with the new NG13 cli, so it has the new module and mjs formats (which will be supported with NG13).
Subscribe to issue https://github.com/stackblitz/core/issues/1657 for updates on that topic.
Hoping to successfully release support in the next few days.

**Comment by markwhitfeld** [comment]
This issue should now be resolved. As of the release yesterday there is no out of band syncing with the npmjs registry. It now happens on demand and is cached. Closing this issue.

Also FYI, StackBlitz now supports Angular 13:
> Great news! Support for Angular 13 has finally rolled out.
...
For the next day or two (until 12 December 2021), there is a possibility of an initial slow down in starting up the dev server or running NGCC (or potentially even timeouts) as the packages repopulate into the cache as they are used, but it should come right after a refresh or two if you do have any issues. Anything else should be reported as a new issue.

Related StackBlitz issue comment: https://github.com/stackblitz/core/issues/1657#issuecomment-989779722

**Comment by transunion-ui** [comment]
I am having problems with this as well with the @transunion-ui/tablejs library.  https://stackblitz.com/edit/getting-started-ivy
The library appears in NPM but does not seem to load on StackBlitz.
