### ISSUE TITLE
Import Error index.html and /app/main.ts for Ionic Project

### ISSUE THREAD

**Issue by aardrasystems** [stackblitz/core#1609]
Hi 

I am new to Stackblitz.

I am trying to get my Ionic Project working on the it.

But i am getting the following message, after syncing to my repo.

Import error, can't find files:
/index.html
/app/main.ts

What could the reason for this be?

**Comment by kc0tlh** [comment]
IONIC projects should just work at this point 🎉

Here are some [known good IONIC v7 templates](https://twitter.com/aaronksaunders/status/1694037022426509709) for StackBlitz.

And here are the docs on importing repos into our new VS Code editor: https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide

_Consolidated Ionic Issue: #219_
