### ISSUE TITLE
Failed to load package from npm

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [stackblitz/core#1616]
Hi! 
I published to npm  a new  package test-ngx-bootstrap-2@1.0.0
But i get error message  " Unable to find package test-ngx-bootstrap-2"  in the NPM registry.
![image](https://user-images.githubusercontent.com/83700465/134904586-b4fa0251-d675-4ce9-8e29-c1b764283cd5.png)

So, I double checked and i can see that my package exists!
https://www.npmjs.com/package/test-ngx-bootstrap-2/v/1.0.0
https://cdn.jsdelivr.net/npm/test-ngx-bootstrap-2@1.0.0/package.json
https://unpkg.com/test-ngx-bootstrap-2@1.0.0/package.json

it also exists on your side https://t.staticblitz.com/v9/test-ngx-bootstrap-2@1.0.0
https://stackblitz.com/edit/angular-ivy-athva6?file=package.json

**Comment by geromegrignon** [comment]
Hey @SvetlanaMuravlova, you should be able to test it again: Stackblitz is currently unable to find the newest packages on the registry.
