### ISSUE TITLE
ngcc failed to run on ngx-bootstrap@7.1.1  in Stackblitz with ivy

### ISSUE THREAD

**Issue by SvetlanaMuravlova** [stackblitz/core#1617]
Hi)
I can't run the project in ivy mode with library 'ngx-bootstrap@7.1.1'

`Error in ~/src/main.ts
ngcc failed to run on ngx-bootstrap@7.1.1.`

I am able to run and serve this project locally.
I can run this project with library 'ngx-bootstrap@7.1.1' but with

`"enableIvy": false`  on stackblitz

but i need be able to run this project with ivy mode on stackblitz with ngx-bootstrap library)
https://stackblitz.com/edit/angular-yxa8m3-rzpmwu?file=tsconfig.json

**Comment by geromegrignon** [comment]
Hey,

the bug is tracked with #1364
