### ISSUE TITLE
What's the license of stacblitz/core?

### ISSUE THREAD

**Issue by thorlacius** [stackblitz/core#1620]
webcontainer-core is licensed under MIT. Are the contents of this repository also available under the MIT license?

https://github.com/stackblitz/webcontainer-core/blob/main/LICENSE

**Comment by purplem1lk** [comment]
Hey @thorlacius! Yes, the contents of the core repository are also available under the MIT license. This has been updated accordingly: https://github.com/stackblitz/core/blob/master/LICENSE
