### ISSUE TITLE
Application URL is not working in IE11

### ISSUE THREAD

**Issue by altbdoor** [stackblitz/core#1625]
### **Description of Bug**

The application URL (not the editor) is not working in IE11. I had a number of projects before this which I made to test some stuff in IE11, so I am fairly sure it worked before. I could not be sure when this broke. Checking the [blog](https://blog.stackblitz.com/), I did not manage to find any information on deprecating IE11 for application URL as well.

### **Steps to Reproduce**

1. Login into Stackblitz
2. Under "Create a new project", click on "TypeScript"
3. A new TypeScript project will be created, and the editor will be displayed
4. In the `package.json` file, change the `target` to `es5`
5. Click on Share, and copy the "Application URL"
    - Example: https://typescript-kbsaeo.stackblitz.io
6. Open IE11, paste the "Application URL", and press enter to load the page
7. IE11 stays on a blank page, with errors in console

```
SCRIPT5009: 'Promise' is undefined
webcontainer.3e00eb9f21511f88f1bf57f5f6810512f74d871c.js (15,6749)
SCRIPT1002: Syntax error
preview-c5cf7181ff9ad51f1a3db.js (2,3458)
SCRIPT5009: '_preboot' is undefined
typescript-kbsaeo.stackblitz.io (12,23)
```

### **Expected Behavior**

IE11 will show a page, to confirm if the user wants to run the project.

### **Screenshots/Screencast**

![capture](https://user-images.githubusercontent.com/3540471/135610882-62369af0-e03d-4a94-bfbf-51c022d6d0de.jpg)

**Additional Context/Questions**

Understandably, supporting IE11 is a pain. So this is more of a question on, "is Stackblitz dropping support for IE11 in the application URLs?".

**Comment by kc0tlh** [comment]
Apologies for not getting this answered sooner. Yes, with Microsofts move to Edge (chromium engine), we are deprecating IE support.
