### ISSUE TITLE
Unable to resolve latest npmjs package

### ISSUE THREAD

**Issue by Frotty** [stackblitz/core#1629]
### **Description of Bug**
As has been the problem before (https://github.com/stackblitz/core/issues/624) stackblitz doesn't find the new versions of my npmjs package which I published.
The package https://www.npmjs.com/package/moots-datetime-picker
0.3.2-0 was released 10 days ago
0.3.2 was released 2 days ago
Both of them cannot be found by stackblitz.

### **Steps to Reproduce**

1. https://stackblitz.com/edit/ionic-5-angular-12-start-template-tabs-fz95lq?file=package.json
2. Change picker version to `0.3.2`
3. Error

### **Expected Behavior**
Stackblitz finds the latest version of the package I published on npmjs, at least after a couple days or so.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/1486037/136398548-e85c4074-d7d8-4f3f-9aab-5eb5cec7623a.png)

![image](https://user-images.githubusercontent.com/1486037/136398572-22dfbf40-84f8-4512-937e-e98c1ee22532.png)

**Comment by zdravkov** [comment]
We observe the same issue with the latest @progress/kendo-vue packages - https://stackblitz.com/edit/xtnjta?file=package.json
The version 2.5.1 and 2.5.2 versions are released days ago but are not found in Stackblitz.

**Comment by yigitfindikli** [comment]
There is the same problem with PrimeNG too. (v12.2.0-rc.1, v12.2.0, and v12.2.1)
