### ISSUE TITLE
Unable to load a dependent assembly to the Angular CLI project using StackBlitz

### ISSUE THREAD

**Issue by artem-kurchenko** [stackblitz/core#163]
Hi,

We have the devextreme-aspnet-data package which depends on our main devextreme package. However, after adding the these packages to the Angular CLI project I'm getting the following error: 
DevExpress is not defined
Evaluating https://unpkg.com/devextreme-aspnet-data@1.2.4/js/dx.aspnet.data.js
Evaluating app/app.component.ts
Evaluating app/app.module.ts
Evaluating main.ts
Loading app
You can check the issue in action here -  https://stackblitz.com/edit/angular-4je6uz

This logic works fine in a stand-alone Angular CLI application.  It looks like devextreme-aspnet-data was loaded earlier than devextreme. Is it possible to resolve this case out of the box, or any additional steps should be performed? 

Thanks,
Artem

**Comment by EricSimons** [comment]
@artem-kurchenko hmm, how are you bundling this package? Right now stackblitz can only support commonjs for the main field and [it looks like it's using AMD](https://unpkg.com/devextreme-aspnet-data@1.2.4/js/dx.aspnet.data.js) and not commonjs (or am I wrong)?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
