### ISSUE TITLE
Your stackblitz demo is not working

### ISSUE THREAD

**Issue by MayurMudliar** [stackblitz/core#1631]
![image](https://user-images.githubusercontent.com/40629150/136557783-3935497f-8bda-4255-83e3-d5393ebebfe2.png)

**Comment by kc0tlh** [comment]
This issue has been resolved: 
<img width="1439" alt="image" src="https://github.com/stackblitz/core/assets/1532264/66ca0d18-a560-4d04-aca7-b9b31e390dbe">
