### ISSUE TITLE
package.json error

### ISSUE THREAD

**Issue by shaiis1** [stackblitz/core#1635]
I've just uploaded my angular 10 project to git and when I'm trying to open it on stackblitz I'm receive the following error:
The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.

**Comment by EricSimons** [comment]
Can you link the github repo you're trying to open so I can repro?

**Comment by shaiis1** [comment]
Hi Eric,

Did you find anything?

**Comment by geromegrignon** [comment]
Hey @shaiis1,

Bootstrap needs @popper/core under the hood.
By creating a Stackblitz project from your repo, Stackblitz failed at resolving this dependency.
I forked your project and removed bootstrap, you can see the dependency installation in action here: https://stackblitz.com/github/geromegrignon/idomoo

Anyway, with an Angular project, I encourage you to use bootstrap thourgh ngx-bootstrap or ng-bootstrap libraries as there are designed for better compatibility with the framework.

**Comment by shaiis1** [comment]
Hi @geromegrignon ,

I've removed the bootstrap dependency, and still got the same error

**Comment by shaiis1** [comment]
[image: image.gif]

Hi @geromegrignon <https://github.com/geromegrignon> ,

I've removed the bootstrap dependency, and still got the same error




‫בתאריך יום ה׳, 14 באוק׳ 2021 ב-10:19 מאת ‪Gérôme Grignon‬‏ <‪
***@***.***‬‏>:‬

**Comment by geromegrignon** [comment]
I forgot another change I had to do to fix it.
Currently, Stackblitz only supports **master** git branch.
As your branch is named **main**, it won't work (even if the error message is about dependencies).
If you change it, please wait few minutes for GitHub to fully change the name of the branch for external resources.

**Comment by shaiis1** [comment]
Hi,

Changed it and still the same error.

Can you please check my repo again?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
Sender
notified by Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality6&>
14.10.21,
10:59:10

‫בתאריך יום ה׳, 14 באוק׳ 2021 ב-10:52 מאת ‪Gérôme Grignon‬‏ <‪
***@***.***‬‏>:‬

**Comment by kc0tlh** [comment]
This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow) for modern Angular repos!

Related Issue: https://github.com/stackblitz/core/issues/2473
