### ISSUE TITLE
Mobile friendly ide

### ISSUE THREAD

**Issue by BartNetJS** [stackblitz/core#164]
Are there plans to make the use of the ide mobile friendly?

It would be great to showcase or test quickly while on the road or to showcase a friend or colleague

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists or if you have other suggestions, feel free to tag me or ask to reopen this issue with screenshots of the error/suggestions. Thank you! :)
