### ISSUE TITLE
missing packet.jason?

### ISSUE THREAD

**Issue by mangadrawing123** [stackblitz/core#1640]
![Uploading image.png…]()

**Comment by fiazfqk** [comment]
Facing same issue

**Comment by geromegrignon** [comment]
Hey @fiazfqk, can you provide a link to your Stackblitz project?

**Comment by fiazfqk** [comment]
Here is the link of the repo: https://github.com/PacktPublishing/RESTful-Services-with-Delphi

**Comment by geromegrignon** [comment]
From [Stackblitz documentation](https://developer.stackblitz.com/docs/platform/supported-frameworks)
> The GitHub importer imports any projects with a package.json, but note that unsupported technologies will not run.

**Comment by fvsch** [comment]
I can confirm that we only run Node.js code in WebContainers at this time.
I don't think we have any plans to run Delphi short or medium term.
