### ISSUE TITLE
unable to run my git project in stackblitz 

### ISSUE THREAD

**Issue by imarunkumar** [stackblitz/core#1643]
**The dependencies for this project could [Project url](https://stackblitz.com/github/imarunkumar/warehousemanagement) n't be resolved. This usually means that a dependency in your package.json is incorrect.**

Repo url: https://github.com/imarunkumar/warehousemanagement

**Comment by imarunkumar** [comment]
Sorry I forgot to add the stackblitz url

https://stackblitz.com/github/imarunkumar/warehousemanagement

**Comment by imarunkumar** [comment]
> Hey @imarunkumar, please provide a Stackblitz sample to reproduce your error
Project link added

**Comment by fvsch** [comment]
Closing this issue because the example repository doesn't exist anymore.

For reference, here is our [Importing Projects documentation](https://developer.stackblitz.com/docs/platform/importing-projects/).
