### ISSUE TITLE
stackblitz stuck in" connecting to dev server"

### ISSUE THREAD

**Issue by ghost** [stackblitz/core#1649]
Go to this angular app in github:

https://stackblitz.com/github/ShieldsKey/pw-angular-interview/tree/routing-start

![image](https://user-images.githubusercontent.com/18215174/138771064-e2c88a61-e852-4adf-aa7f-235753d918b0.png)

This was working fine last week.

**Comment by AMANJOTSINGH14** [comment]
> This was related to npm resolution issues. This should be fixed now.

@markwhitfeld yeah they fixed it
