### ISSUE TITLE
Long project name moves the pencil and the project name cannot be edited

### ISSUE THREAD

**Issue by ddubrava** [stackblitz/core#1650]
### **Description of Bug**

If you provide a long project name, you can't edit this project name anymore as pencil is out of the viewport. 

When I was reproducing this error, I find that it's possible to change the settings width and you can click on the pencil. To be honest, didn't see it at the first time, when I faced with the problem, so had to use the devtools to change the title. IMHO, it's not obvious that you can drag the container.

### **Steps to Reproduce**

1. Create a project
2. Open settings tab
3. Click on the pencil to the right of the title
4. Write a long project name, e.g. very-very-very-very-very-very-very-long-project-name
5. Press enter
6. See error

### **Expected Behavior**

You see the pencil and can edit the project.
I think, if the title exceeds the limit, it's better replace end of the text with a few dots, so there is enough space to show a pencil.

### **Screenshots/Screencast**

![image](https://user-images.githubusercontent.com/22116465/139117409-a0356a46-ea9c-445a-93eb-9f1c553edc0e.png)

**Comment by fvsch** [comment]
Thanks for the report!

I’m closing this issue since we revamped the UI for editing the project URL, and it shouldn't have this problem.

![Screenshot of the new project metadata editing UI](https://user-images.githubusercontent.com/243601/177602774-7d1e2b45-fa88-4bb2-bd28-dbaf16e7a0ca.png)
