### ISSUE TITLE
Prevent auto-scroll to iframe

### ISSUE THREAD

**Issue by NetanelBasal** [stackblitz/core#1653]
### **Description of Bug**
When using the SDK it auto scrolls to the iframe.

### **Steps to Reproduce**
See it live on every page here https://ngneat.github.io/elf/docs/store

### **Expected Behavior**
Stop the auto-scroll.

**Comment by fvsch** [comment]
Hi again @NetanelBasal. We shipped an update which seems to fix the issue on https://ngneat.github.io/elf/docs/store and other pages using StackBlitz embeds. Can you give it a try and confirm?

As a side note, I think you can make a couple tweaks to your embedding code:

- We recently pushed an SDK update that lets you set `devToolsHeight: 100`. I saw that you were using `devToolsHeight: 99` as a workaround. Make sure you're using the latest SDK version.
- I would recommend using the `forceEmbedLayout: true` option, if you think that layout works for your use case. In a future major version of the SDK (likely 2.0), we’ll probably set the default value to `true` for that option.

**Comment by NetanelBasal** [comment]
Yes, it works perfectly. 

Great, I'll set the height to 100 and check the `forceEmbedLayout` option. 

Thanks!

**Comment by thescientist13** [comment]
Thanks for the fix!  We [just observed this issue](https://github.com/ProjectEvergreen/greenwood/issues/797) ourselves the other day and now it has gone away.  🙇‍♂️

**Comment by TheNightmareX** [comment]
The issue is not solved, it's back again. Checkout https://ngneat.github.io/elf/docs/store and you can see the page scrolls to the iframe again now!

**Comment by Enngage** [comment]
We are seeing the same issue, can you please add an option for disabling cursor focus?

**Comment by shhdharmen** [comment]
I am also facing same issue.

**Comment by kamranayub** [comment]
Can also confirm it's happening (in Chrome, Firefox seems okay). Exact same issue as above.

**Comment by thescientist13** [comment]
seems like this is happening again?

**Comment by NielsCodes** [comment]
> seems like this is happening again?

It was never fixed to begin with

**Comment by thescientist13** [comment]
can this issue please be re-opened?

And curious, the `forceEmbedLayout`, where is that added?  To the query string of the embed URL, or some file in the repo when the container loads?
