### ISSUE TITLE
GitHub sign in error

### ISSUE THREAD

**Issue by daniloraisi** [stackblitz/core#1659]
### **Description of Bug**
I'm trying to connect to Stackblitz using my GitHub account, but I'm constantly receiving the same error.

### **Steps to Reproduce**

1. Go to the website
2. Click on Sign In
3. See the error

### **Expected Behavior**
I want to be able to access my account linked with my GitHub.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/38328735/140737119-9c1c09da-7c92-408f-9205-dbb874850a5f.png)

**Comment by ShaharGrauman** [comment]
Same here

**Comment by daniloraisi** [comment]
Any updates on this?

**Comment by daniloraisi** [comment]
More than one year and no updates on how to get this working again? How can I use StackBlitz without access?

**Comment by daniloraisi** [comment]
As of June 2023, I could log in to the Stackblitz website using my GitHub account.
