### ISSUE TITLE
Can't import npm package

### ISSUE THREAD

**Issue by pliablepixels** [stackblitz/core#166]
hi, thanks for this excellent online IDE!

I have a local code working that I'm trying to replicate in stackblitz

the code is here https://stackblitz.com/edit/ionic-fzmkv7

I've added `angular-2-holder-js` to the npm packages, but I am not able to import it in app.module.ts
via `import { HolderjsDirective } from 'angular-2-holderjs/holderjs.directive';` - it can't find that path

Can you please advise on what I am doing wrong?

**Comment by pliablepixels** [comment]
I've worked around this situation by manually adding `holderjs.directive.ts` to my files instead of a package, but now it can't find Holder (a variable in holderjs) which I've also added in npm.

This makes me believe the packages I am adding via npm are not getting included.

Any idea?

https://stackblitz.com/edit/ionic-fzmkv7

**Comment by pliablepixels** [comment]
I've migrated the code to plunker and it works well, so I'm closing this given my need is met (which was to get a runnable web demo). Thanks.

**Comment by sree332** [comment]
I have the same issue I tried importing angular-bootstrap-md and when I tried to include in the app module ts file I see "Module Not found" Error ..

**Comment by hernandoh** [comment]
tambien tengo el mismo problema con angular-bootstrap-md
