### ISSUE TITLE
Unable To upload React-App to stactkbliz Preview

### ISSUE THREAD

**Issue by fradelycodes** [stackblitz/core#1668]
https://github.com/fradelycodes/React-Scoreboard-App

![Screen Shot 2021-11-22 at 4 59 57 AM](https://user-images.githubusercontent.com/60589096/142832210-c9129795-7b61-46e8-9dca-b7849153d61f.png)

**Comment by kc0tlh** [comment]
This issue is now resolved:

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/66f47d2c-799c-465c-afb1-154bdfddac13">
