### ISSUE TITLE
ng generate component command does not generate files in stated directory

### ISSUE THREAD

**Issue by agolec** [stackblitz/core#1671]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
https://stackblitz.com/edit/angular-xhybwh?file=src%2Fapp%2Fproduct-list%2Fproduct-list.component.html
Just the tutorial project on angular.io.

I am opening a second terminal window, and typing 'ng generate component <component-name>' in my terminal, to make a new component.

The terminal says that at a specific path in the directory, the component and it's files have been created, and my project updated successfully.

But no matter what I do, those files don't show up in my project, when I go through the project tree to look for them. They never render in the project itself.

### **Steps to Reproduce**

1. Opened a second terminal window
2. Typed in 'ng generate component <name of component>'
3. Terminal output will state ' src/app/product-alerts/product-alerts.component.spec.ts (676 bytes)', etc for all associated files.
4. When I check the project file directory, the component files aren't in the listed locations. Even if I refresh the page.
<img width="865" alt="Don't see component in directory" src="https://user-images.githubusercontent.com/30152085/143511103-1329522f-3bda-4daa-baa4-70eaf2c4c191.PNG">

### **Expected Behavior**
The component I tried to generate should be in my project's file directory where the terminal stated it was generated after running the command.

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by bzh4bzh** [comment]
For me the project throws an error after I try to use the component

**Comment by fvsch** [comment]
Hi @agolec, thanks a bunch for the detailed steps to reproduce!

I think this matches the known symptoms of a bug that @jrvidal fixed on Friday (same day you reported it). I’m trying out your steps to reproduce and things seem to work.

![working-angular-project](https://user-images.githubusercontent.com/243601/143920783-11060266-4d9c-4a00-8bee-210118c86e80.png)

Could you check if things work for you now?
Likewise @bzh4bzh, can you check if things are working on your side?

Thanks :)

**Comment by bzh4bzh** [comment]
@fvsch Confirming it works as expected now
