### ISSUE TITLE
Buffer not defined after creating new GitHub repo

### ISSUE THREAD

**Issue by six-edge** [stackblitz/core#1675]
### **Description of Bug**
After creating a simple **JavaScript blank project** from the dashboard and clicking on **Connect repository** it then displays **Error: Buffer is not defined**

### **Steps to Reproduce**

1. Go to **Stackblitz.com Dashboard**
2. Click on **JavaScript blank project** under **Create a new project** 
3. Click on **Connect repository** (GitHub Icon) and create a new project.
4. **master** branch appears and loader keeps spinning while an error appears... a red toastbar notification from the bottom displays... **Error: Buffer is not defined**
5. After checking my GitHub account, the repo is created but nothing was pushed.
6. After going back to the dashboard and reopening the project the same error occurs and spinner next to **master** just keeps spinning.

### **Expected Behavior**
1. Better error message and handling
2. GitHub repo was created and synced with my project seemlessly.

### **Screenshots/Screencast**
![tempFileForShare_20211128-094348](https://user-images.githubusercontent.com/42222405/143763987-71aed4b2-fa9e-4729-8ca9-e55eb0c99fbd.jpg)

**Additional Context/Questions**
Running stackblitz.com on a Samsung Galaxy Tab

**Comment by TomSmedley** [comment]
Looks like we reported the exact same bug at the exact same time https://github.com/stackblitz/core/issues/1676.

**Comment by shammlo** [comment]
@TomSmedley  and I have the same issue, I read your issue report as well.

**Comment by fvsch** [comment]
Hello @six-edge, and thanks for the detailed bug report!

We just shipped a fix for this issue. Can you verify that everything works for you?
