### ISSUE TITLE
Error: Buffer is not defined

### ISSUE THREAD

**Issue by TomSmedley** [stackblitz/core#1676]
### **Description of Bug**
I have used https://github.com/withastro/astro/tree/main/examples/with-tailwindcss and tried to connect it to a private repo and I get `Error: Buffer is not defined`

### **Steps to Reproduce**

1. Go to https://github.com/withastro/astro/tree/main/examples/with-tailwindcss 
2. Click on Open in StackBlitz
3. Folk it
4. Click "Connect repository"
5. Check "Make this repository private"
6. You get the error `Error: Buffer is not defined` and the repository will remain empty.

### **Expected Behavior**
To connect and push to the private github repository.

**Comment by fvsch** [comment]
Hi @TomSmedley, thanks for the detailed report!

We just shipped a fix for this issue, and in my tests it's working well now. Could you verify on your side?

**Comment by six-edge** [comment]
It's working now as expected and it pushed my changes... however I can't seem to work out where to do a commit?

Shouldn't there be a GitHub icon in the side menu with a commit dialog? similar to codesandbox?

**Comment by fvsch** [comment]
@six-edge Thanks for the feedback. For your other issue, do you see the “Commit” button in the toolbar in your project?

![commit-button](https://user-images.githubusercontent.com/243601/144011507-ca7762f9-f975-4709-b774-62e58ef02bc1.png)

**Comment by six-edge** [comment]
Ah yes thanks. I had to click on the stackblitz icon to see it. Perhaps a dedicated GitHub icon similar to vs-code GitHub integration would be great.
