### ISSUE TITLE
Firefox: preview not working for the web-platform template (Static HTML/JS/CSS)

### ISSUE THREAD

**Issue by jzabinski-dolios** [stackblitz/core#1679]
### **Description of Bug**
In Firefox only, live demo always shows the error "ENOENT: No such file or directory., '/~'".

### **Steps to Reproduce**

1. Open Firefox 94.
2. Navigate to https://stackblitz.com/edit/web-platform-spkpq6.

### **Expected Behavior**
Live demo should compile and run successfully.

**Additional Context/Questions**
Chrome and Safari compile and run successfully. Firefox can also open other project types (Angular, RXJS) almost all the time. (It randomly fails, but a refresh clears up the problem.) The problem seems to be limited to Web Platform projects.

**Comment by fvsch** [comment]
Thanks for the report @jzabinski-dolios. This is related to [an intervention shipped by Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1668408) to handle a different issue on StackBlitz, which is unfortunately breaking all projects that use the `web-platform` template. We're looking into whether we can get this intervention removed (since we shipped some relevant fixes on stackblitz.com).

**Comment by fvsch** [comment]
Hey everyone.

The HTML/CSS/JavaScript templates should work in Firefox again (as of late 2022):

- We shipped some fixes that made the Firefox shim removing Service Worker functionality on stackblitz.com unnecessary.
- The shim was removed from Firefox.
- HTML/CSS/JavaScript projects now work in Firefox when Service Workers are not blocked by specific user configuration (like “Enhanced Tracking Protection” set to “Custom” and to block all third-party cookies) or browsing mode (Private browsing tends to block Service Workers).

If you still have issues with Firefox for HTML/CSS projects, and/or if you have issues with Firefox and Node projects on StackBlitz, please check this documentation page:
https://developer.stackblitz.com/platform/webcontainers/browser-config#firefox-service-workers
