### ISSUE TITLE
NPM Package subdirectory modules not working as expected

### ISSUE THREAD

**Issue by giocodes** [stackblitz/core#168]
Hello! I'm trying to use 
`import Typography from 'material-ui/Typography';` 
on a React project but I get the following error: 
"Please check your import statements & ensure you're importing the correct module names."

I tried the solution mentioned in #149 but didn't work

**Comment by EricSimons** [comment]
@giocodes are you sure that's a valid import statement? Bc I can't find a `/Typography` folder or a file called `/Typography.js` inside of the material-ui package: https://unpkg.com/material-ui@0.19.4/ 🤔

**Comment by giocodes** [comment]
@EricSimons thanks for the quick response!
You are right, I was not including the correct package version, it was fixed by adding the package as `material-ui@next`

Also I can confirm that subdirectory modules get imported correctly as seen here
https://stackblitz.com/edit/material-ui

Hope this helps someone else! 🤙
