### ISSUE TITLE
Unable to import sass modules

### ISSUE THREAD

**Issue by dobromirts** [stackblitz/core#1681]
### **Description of Bug**
Can't successfully import sass modules with @use from maretial.io or other library to Angular 13 project and 'Sass Error: Can't find stylesheet to import' is displayed in the console.
https://stackblitz.com/edit/angular-i1jikx-vgkrod?file=src%2Fstyles.scss

### **Steps to Reproduce**

1. Create Angular 13 project
2. Import library with sass modules exports
3. Include the imports in the project styles.scss file

### **Expected Behavior**
To be able to import sass modules in both with WebContainers and in the standard version after Angular 13 support is released.

**Comment by markwhitfeld** [comment]
Angular CLI is using a currently unsupported WC api as an optimisation of SASS.

**Comment by markwhitfeld** [comment]
Angular CLI is using a currently unsupported WC api as an optimisation of SASS.
There is a PR in progress to fall back when using WebContainers:
https://github.com/angular/angular-cli/pull/22294

**Comment by markwhitfeld** [comment]
Related WebContainer issue tracked here: https://github.com/stackblitz/webcontainer-core/issues/456
Closing this issue in favour of that one.

**Comment by dobromirts** [comment]
@markwhitfeld After the Angular 13 release the issue with importing sass modules is still reproducible. Is it possible to import currently sass modules in this version without WebContainers? This is a sample reproducing the issue https://stackblitz.com/edit/angular-ivy-h8ko8h?file=src%2Fstyles.scss

**Comment by markwhitfeld** [comment]
Ok, this is definitely still a bug in NG13 regarding sass resolution. `sass` resolution needs to now make use if the `exports` in package json, which it currently doesn't do.

The WC version should be working since the 3.1.0 release of Angular:
https://stackblitz.com/edit/angular-i1jikx-jy8ix9?file=package.json

I'll reopen this as an issue for StackBlitz v1.

**Comment by markwhitfeld** [comment]
@dobromirts This is resolved now! 🎉 
Had to get `package.exports` resolution working for sass. 
Didn't even cross my mind to do this when I was adding ESM support.

cc @splaktar @zdrawku
