### ISSUE TITLE
Unable to create files/folders and ".<anyname>" folder 

### ISSUE THREAD

**Issue by aantipov** [stackblitz/core#1683]
### **Description of Bug**

I can't create files/folders under folders which name starts with dot.

After an attempt to create such a file the Explorer sidebar gets frozen and becomes unusable

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/vite-zmez77
2. Click on `.dotfolder`
3. Click on "Create File" or "Create Folder" icon (to the right of `.dotfolder`)

![image](https://user-images.githubusercontent.com/427621/144460403-2bb455c0-3879-4452-81e7-28a7fb8abfea.png)

4. Experience the frozen screen

![CleanShot 2021-12-02 at 17 19 07](https://user-images.githubusercontent.com/427621/144461152-2f7a452c-d859-4fe4-86f8-62dd7751d84e.gif)

**Additional Context/Questions**
I use Chrome browser `version 96.0.4664.55 (Official Build) (x86_64)`. The problem is reproducible in Incognito mode as well

**Comment by Agapurnis** [comment]
I'm still encountering this on Chrome `Version 110.0.5481.181 (Official Build) (64-bit)`, using ChromeOS. It also applies to the default `.vscode` directories.

You can actually create and edit folders/files within the hidden files by using `touch`, `mkdir`, `cd`, and `code`, but the changes don't seem to persist after saving the project.

If you use `mv` to rename to a dot-folder the folder will vanish on the UI and is successfully named. After saving and reloading, I noticed that if the folder was empty it is deleted, but if it is not then the folder persists as the name prior to the change, but remains invisible on the UI. This might be different if you're moving to another directory, as I only tested changing folders to dot-folders within the same parent directory.

There may be some additional information in the developer console, but I am unfortunately unable to check as of currently writing.

**Comment by shellscape** [comment]
@kc0tlh but definitely exists when folders/files are created on the command line.
