### ISSUE TITLE
Angular project stopped working "ngcc failed to run"

### ISSUE THREAD

**Issue by ceelian** [stackblitz/core#1688]
### **Description of Bug**

Existing and previously working Angular stackblitz project stopped working in the last days, without changes on the stackblitz project

Example: https://stackblitz.com/edit/cnc-angular-dynamic-module-loading

### **Steps to Reproduce**

1. Open the StackBlitz project: https://stackblitz.com/edit/cnc-angular-dynamic-module-loading
2. WAIT until the compiling and starting of the dev server is completed
3. Then it will show an error

```
Error in ~/src/main.ts
ngcc failed to run on @angular/material@11.2.13.
```

### **Expected Behavior**
Has worked a couple of days before, should still work.

### **Screenshots/Screencast**

![Screenshot 2021-12-09 at 11 55 32](https://user-images.githubusercontent.com/116299/145383733-c88d8520-9d2d-4697-860b-e64fadcc774e.png)

**Comment by markwhitfeld** [comment]
We have released a fix for this issue. 👍
