### ISSUE TITLE
cannot import json fiels

### ISSUE THREAD

**Issue by milanffm** [stackblitz/core#169]
when I Trie to import
`import * as  test from 'test.json';`
I get an error Module not found. Because I had to add 

`// Allow .json files imports`

`declare module '*.json';`

to typings.d.ts

but when I do this, an Error was thrown 
Can't find package:test.json

**Comment by EricSimons** [comment]
Your import needs to be relative (i.e. `import test from './test.json'`). Lmk if that fixes it!

**Comment by milanffm** [comment]
yeah this fixed it :-) awesome tool by the way 👍
