### ISSUE TITLE
Angular project that used to work is not compiling anymore

### ISSUE THREAD

**Issue by joaqcid** [stackblitz/core#1690]
### **Description of Bug**
I created this project a while ago, around a month ago i tried open it and got this error 

> Error in /turbo_modules/@grpc/grpc-js@1.3.4/build/src/call-stream.js (29:9)
Cannot destructure property 'HTTP2_HEADER_STATUS' of 'http2.constants' as it is undefined.

I tried several things to fix it, and ended up starting a new Angular template project and copying code over to get it up and running.

Today i opened the project again and im getting this error

![image](https://user-images.githubusercontent.com/6530160/146007094-b07a557c-eba7-4f0d-bf80-a0c3c3b44f64.png)

https://stackblitz.com/edit/ngxs-firestore-example-app

### **Steps to Reproduce**

1. Open stackblitz project https://stackblitz.com/edit/ngxs-firestore-example-app

### **Expected Behavior**
Stackblitz project to work

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by markwhitfeld** [comment]
It looks like it is trying to fetch some node libraries, so the package resolver may be picking up an incorrect entry point (a node one) for one of the packages. I will investigate.

**Comment by AndyEst** [comment]
I am experiencing a similar problem, also related to firestore.

https://stackblitz.com/edit/js-8gf3jw?file=index.js

![Screenshot - 2021-12-15T184420 606](https://user-images.githubusercontent.com/50149762/146298577-79e33d83-9721-4d31-abbd-580c769bc56e.png)

**Comment by markwhitfeld** [comment]
This issue should be resolved now. It was a regression from the NG13 update. Thank you for reporting it 👍
