### ISSUE TITLE
Failed to import from github

### ISSUE THREAD

**Issue by Nii-Addo** [stackblitz/core#1696]
The response return is "Something went wrong with this repository."

**Comment by geromegrignon** [comment]
Hey @Nii-Addo, please provide a link to your repository.

**Comment by Nii-Addo** [comment]
@geromegrignon https://github.com/Nii-Addo/gada

**Comment by geromegrignon** [comment]
I would try by removing the node_modules from the repository firstly.
It's uncommon to include node_modules in git history and it won't be useful with Stackblitz as it uses its own package manager for dependencies.

**Comment by Nii-Addo** [comment]
That worked. Thanks.

**Comment by geromegrignon** [comment]
Great! Please mind closing this issue as it's solved.
