### ISSUE TITLE
Can't clone my repo

### ISSUE THREAD

**Issue by AnzenKodo** [stackblitz/core#1697]
My repo link https://github.com/AnzenKodo/io-notes

![stackblitz com_github_AnzenKodo_io-notes](https://user-images.githubusercontent.com/50282743/146924335-dda7e2cf-3e2d-4fbe-812f-20dd45b7d5ab.png)

Console error: `Failed to load resource: the server responded with a status of 500 ()`

After cleaning the cookies then also it does not import the repo.

**Comment by AnzenKodo** [comment]
I changed the link of the repo now its working https://github.com/AnzenKodo/io-notes -> https://github.com/AnzenKodo/io-note

**Comment by geromegrignon** [comment]
Hey @AnzenKodo please mind closing this issue as it's solved.
