### ISSUE TITLE
react application is not building, giving dependency error 

### ISSUE THREAD

**Issue by nishikant007** [stackblitz/core#1699]
github link
https://github.com/nishikant007/reactCostCalculator/tree/main/react-cost-calculator

**Comment by markwhitfeld** [comment]
Hi @nishikant007 
Could you provide a stackblitz link to repro this issue?

**Comment by markwhitfeld** [comment]
The import works using StackBlitz v2 (WebContainers):
https://stackblitz.com/github/nishikant007/reactCostCalculator/tree/main/react-cost-calculator?preset=node&terminal=start

If you would like it to work in StackBlitz v1, then have a look at the folder structure for the StackBlitz react starter project and use a similar approach in your project.
