### ISSUE TITLE
To be able to toggle menu.

### ISSUE THREAD

**Issue by chpecson** [stackblitz/core#170]
Toggling menu will be a great help because it can be minimized which brings more room for coding.

**Comment by seveves** [comment]
I think that's a great idea. In vscode I use the shortcuts to toggle file explorer or console window very often. Keyboard shortcuts would be awesome 😻

**Comment by EricSimons** [comment]
Yup, this is coming! Shooting for May on this- will circle back when it's online 👍

**Comment by sulco** [comment]
Thanks for submitting the issue! We now have a "Zen" mode that allows focusing on the code :) 
![2021-02-09 13 09 49](https://user-images.githubusercontent.com/1511906/107361862-4c44f580-6ad8-11eb-9f93-39466a98327d.gif)
