### ISSUE TITLE
Setup environment error for vanilla app

### ISSUE THREAD

**Issue by shmbajaj53** [stackblitz/core#1700]
### **Description of Bug**
I created vanilla html+js project and post project creation, I am getting messaged 
`Error occurred:
Error: ENOENT: No such file or directory., '/~'
` 

### **Steps to Reproduce**

1. Create html+js vanilla app

### **Expected Behavior**
App to be in working state, by default.

### **Screenshots/Screencast**
![stackblitz-error-occured](https://user-images.githubusercontent.com/94983619/147462776-8b2dfe00-233f-42a3-ac99-b70a7786f30c.png)

**Comment by geromegrignon** [comment]
Hey @shmbajaj53, I can't reproduce it using the HTML/JS/CSS starter.
Can you provide a link to your project?

**Comment by shmbajaj53** [comment]
Hey @geromegrignon here is the link to app
[vanilla-js-app](https://js-learning-tic-tac-toe.stackblitz.io)

**Comment by geromegrignon** [comment]
@shmbajaj53, please provide the link to the project, not to the preview.

**Comment by shmbajaj53** [comment]
Hey @geromegrignon here is the link to github repo
[js-learning-tic-tac-toe/vanilla-js-app](https://github.com/shmbajaj53/js-learning-tic-tac-toe)

**Comment by geromegrignon** [comment]
It loads as expected for me:
![image](https://user-images.githubusercontent.com/32737308/147488456-b1f996ac-4f2e-4d19-a6e8-2d1395871f8b.png)

**Comment by shmbajaj53** [comment]
![Uploading image.png…](Recent screen shot fo web app)
 
Hey @geromegrignon I am still facing the same issue, what now I am supposed to do?

**Comment by shmbajaj53** [comment]
Hey @geromegrignon I am still facing the same issue, what now I am supposed to do?


![recent](https://user-images.githubusercontent.com/94983619/147496359-b489f222-e9ec-4608-86d2-a017fcbf0c02.png)

**Comment by geromegrignon** [comment]
Just click on run the project about the related screenshot.
About the error itself as I can reproduce it, please provide details about your browser.

**Comment by shmbajaj53** [comment]
Hey @geromegrignon I clicked on the `run the project` button and got this:

![connecting_dev_server](https://user-images.githubusercontent.com/94983619/147530575-3aafab77-fcd1-4bbd-a8d5-fcab88ef2e85.png)

**Comment by geromegrignon** [comment]
It doesn't answer my previous question.

**Comment by shmbajaj53** [comment]
I still facing the same issue.

Browser: Firefox 95.0.1 for Ubuntu canoical 1.0

**Comment by timsonner** [comment]
I'm guessing this is a browser specific issue and related to https://github.com/stackblitz/core/issues/1679

**Comment by kc0tlh** [comment]
Closing as duplicate of #1427
