### ISSUE TITLE
Error while adding project to stack blitz

### ISSUE THREAD

**Issue by MadhunikaA** [stackblitz/core#1701]
I was trying to open  the project using stack blitz but it was showing package.json is missing but it was there actually inside of the folder.

**Comment by geromegrignon** [comment]
Hey @MadhunikaA, please provide a link to your project.

**Comment by markwhitfeld** [comment]
@MadhunikaA I assume you are referring to this repo:
https://github.com/MadhunikaA/-Expert-Rec

The import works with this url to the sub folder:
https://stackblitz.com/github/MadhunikaA/-Expert-Rec/tree/main/nebular-start

It does look like your project is missing a dependency though. Closing issue.
