### ISSUE TITLE
Unable to run project from github

### ISSUE THREAD

**Issue by anmolsinha1793** [stackblitz/core#1702]
Error says the package.json file is corrupted

**Comment by geromegrignon** [comment]
Hey @anmolsinha1793, please share a link to your project.

**Comment by anmolsinha1793** [comment]
Hey @geromegrignon , https://github.com/anmolsinha1793/angular-d3-charts, you can use this link

**Comment by geromegrignon** [comment]
I would try to remove `save-dev` as it's an empty package.
I would also challenge the need of `-` as you don't use it.

**Comment by anmolsinha1793** [comment]
But the same works fine when i do an npm install, is this something specific to stackblitz?

**Comment by geromegrignon** [comment]
Stackblitz uses their own package manager named Turbo.
It might filter non-empty packages.
It would require an answer from the core team.

**Comment by anmolsinha1793** [comment]
Sure, thanks for the quick response, i will verify the application once after removing the packages and would then remove the same from repo and retry, thanks, will update soon

**Comment by anmolsinha1793** [comment]
Hey @geromegrignon , thanks for your suggestion, the solution works for me.

**Comment by geromegrignon** [comment]
Awesome!
