### ISSUE TITLE
"Can't find packages" error appearing for dependancies we don't have

### ISSUE THREAD

**Issue by kmcnellis** [stackblitz/core#1708]
### **Description of Bug**
Sometime between August 25th and December 23rd, the dependency resolution for plain Javascript projects changed.   

For previously-working projects, and for new ones that import the Firebase libraries, it's now throwing an error ```Can't find packages:
url tls http2 net dns zlib http events```. 

However, (1) none of those packages are used in the code, (2) they don't seem to be imported as dependancies though the package.json and (3) code compiled locally does not throw any errors about missing dependancies.  Furthermore, since zlib doesn't work on stackblitz (it gets `Import error, can't find file: ./zlib_bindings`), installing those packages doesn't help.

It appears that stackblitz is over-searching for dependancies inside npm packages, and erroring out even if those code paths never get called.

https://stackblitz.com/edit/firebase-gtk-web-start-pzsfoo?file=index.js
![image](https://user-images.githubusercontent.com/5566205/148143760-caaf33c2-d3de-4b75-9815-cd03654612c4.png)

### **Steps to Reproduce**

1. [Create a blank JS project](https://stackblitz.com/fork/js)
2. Add 
  ```
  import { getFirestore } from 'firebase/firestore';
  
  getFirestore();
  ```
3. Add firebase@9.6.1 to the dependancies

### **Expected Behavior**
There should be no error about missing packages, or the error is allowed to be skipped.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/5566205/148144321-ca1a1462-da2a-4f13-9e5d-b3ddb10ed082.png)
![image](https://user-images.githubusercontent.com/5566205/148144404-c70a2d42-05b7-4db1-ab0e-8eb8366831da.png)

**Additional Context/Questions**
gprc-js (imported by firebase/firestore) does reference zlib without importing it.  https://github.com/grpc/grpc-node/blob/fe5806171f6033c3988cdaf78ba9fd7940993652/packages/grpc-js/src/compression-filter.ts#L18

**Comment by 99JS** [comment]
Experiencing the same issue as @kmcnellis.

**Comment by puf** [comment]
I see this on many of my older StackBlitz projects too. For example: https://stackblitz.com/edit/life

**Comment by AndyEst** [comment]
I too have this issue, hope it can be resolved!

**Comment by fersucho** [comment]
Exactly the same issue. I have several Stackblitz projects that use Firebase libraries. For some months I haven't tested these projects in Stackblitz but now I need to create a new one and I find that all my projects fail. I have tested projects in several angular, angular/fire and firebase versions, all have failed. Even the sample template provided in: https://www.npmjs.com/package/@angular/fire fails, this is a link to a version of this project: https://stackblitz.com/edit/angular-fire-start-fsszah 
Help, please!

**Comment by sampath9875** [comment]
So, is this an issue with firebase or stackblitz environment? 

If anyone has a workaround for this, please suggest.

**Comment by markwhitfeld** [comment]
This should be resolved now with the latest release. This bug was unfortunately a side effect of the immense complexity that is node entry-point resolution (now with esm support). 
Please let us know if there are still any issues. I have tested all links provided above and they now work.

**Comment by fersucho** [comment]
Thanks, Mark, my projects are now working again.
