### ISSUE TITLE
template of vite svelte-ts cannot be opend

### ISSUE THREAD

**Issue by zhaobenx** [stackblitz/core#1709]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
https://vite.new/svelte-ts

### **Steps to Reproduce**

1. Open https://vite.new/svelte-ts
2.  As shown

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/23143530/148194596-1317b03d-8c75-4180-843a-75e528602dc8.png)

**Comment by timsonner** [comment]
I just opened a new svelte-ts template project no problem. Goto: Dashboard -> Create a new project -> Vite -> svelte-ts and it worked flawlessly. Steps to reproduce are vague, I see no bug here, works as it should.

**Comment by markwhitfeld** [comment]
Seems to be working now. Closing issue.
