### ISSUE TITLE
Angular Google Maps (@agm/core) - Unexpected token export

### ISSUE THREAD

**Issue by Alucardz** [stackblitz/core#171]
Getting the following error when testing simple example from https://angular-maps.com/guides/getting-started/ :

```
Unexpected token export
Evaluating https://unpkg.com/@agm/core@1.0.0-beta.1/index.js
```

Can test here: https://angular-google-maps-example.stackblitz.io

Could this be related to #131 ? Although I'm not using AngularFire2 in the above example.

Could possibly be related to SebastianM/angular-google-maps#1052 even though this is a more Angular Universal issue...

**Comment by Alucardz** [comment]
Any insight into this?

**Comment by EricSimons** [comment]
Hey @Alucardz! So sorry about my delay here, the past week or so has been nuts 😅 It looks like this is actually a problem with the package itself — specifically it doesn't have a main field that points to its CJS bundle. Instead, if you import `import { AgmCoreModule } from '@agm/core/core.umd';` (core.umd.js is the main bundle) everything works great! Here's a fork of your project that's working properly: https://stackblitz.com/edit/angular-google-maps-example-9neueh?file=app%2Fapp.module.ts

Lmk if that works for ya or if you run into any other troubles!

**Comment by Alucardz** [comment]
Wow that's awesome, kudos for the amazing platform and superb support!

**Comment by Alucardz** [comment]
Would there be any reason that 2 UMD modules included together, for example:

```
import { AgmCoreModule } from '@agm/core/core.umd';
import { AgmSnazzyInfoWindowModule } from '@agm/snazzy-info-window/snazzy-info-window.umd';
```

along with:

```
AgmCoreModule.forRoot({
      apiKey: environment.googleMapsAPiKey
}),
AgmSnazzyInfoWindowModule
```

would cause the same error but on BOTH umd files? 

```
Fatal error:
Unexpected token export
Evaluating https://unpkg.com/@agm/core@1.0.0-beta.1/index.js
Evaluating https://unpkg.com/@agm/snazzy-info-window@1.0.0-beta.1/snazzy-info-window.umd.js
Evaluating app/app.module.ts
Evaluating main.ts
Loading app
```

**Comment by EricSimons** [comment]
@Alucardz yup you're totally right about this — I think I've figured out a way to fix this from happening :) I've got it running locally right now but need to do some more testing before I send it to prod, shooting to have it on prod tmrw 😅  So sorry about the inconvenience!!

**Comment by EricSimons** [comment]
@Alucardz this is now live on prod — you also don't need to import from /core.umd anymore :)  Lmk if all looks good on your end!

**Comment by Alucardz** [comment]
@EricSimons It's working marvelously now, looks like you pushed the fix to prod :) Kudos to you sir!

**Comment by HighSoftWare96** [comment]
Not working for me... I'm getting this:
ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'AgmCoreModule' was called.

**Comment by EigenTheory** [comment]
This is happening again, does anyone have a solution?
