### ISSUE TITLE
Not able to open angular slickgrid respository in stackblitz

### ISSUE THREAD

**Issue by keertika-SP** [stackblitz/core#1713]
![errorrrr](https://user-images.githubusercontent.com/68580790/150074298-33afd475-864e-452d-9963-40ad47e34c8e.PNG)

**Comment by kenmorechalfant** [comment]
Also having this issue currently with [a React project](https://github.com/kenmorechalfant/unit-converter-react) I'm working on. Checked out your repo and the only top-level dependencies in common are Typescript and Jest, I believe. Hopefully they can fix this soon 😓
