### ISSUE TITLE
Can't start nuxtjs project (error page is shown)

### ISSUE THREAD

**Issue by lustremedia** [stackblitz/core#1715]
Looks like a backend issue.

For a new nuxtjs project (beta) I just get an error page:

https://stackblitz.com/fork/github/nuxt/starter/tree/stackblitz

**Comment by markwhitfeld** [comment]
It looks like the `stackblitz` branch in the nuxt starter project repo has been renamed to `v2-stackblitz`.
This doesn't work:
https://stackblitz.com/fork/github/nuxt/starter/tree/stackblitz
But this does:
https://stackblitz.com/fork/github/nuxt/starter/tree/v2-stackblitz

Our importer currently doesn't support following the github redirects. I'll chat to the team.
