### ISSUE TITLE
Not able to open my account

### ISSUE THREAD

**Issue by irbansin** [stackblitz/core#1719]
### **Description of Bug**
I have recently changed my Github account. I have moved all my repositories to my new account and deleted the old one. I had a stackblitz account in the old account. Now when I am trying to login, its telling that there is already an existing account to my email id.

This can be fixed if my old account is deleted from your servers. The account is "ani.expo10@gmail.com"

### **Steps to Reproduce**

1. Go to stackblitz.com
2. Click on 'Github login button'
3. Error: Yikes! It looks like there's already an account with your username or email
If you recently changed your username or email on GitHub, it's possible that your username or email was previously used at StackBlitz with another account. If you are in posession of the existing account on StackBlitz, sign in with that account first to update the GitHub profile, or change your email on GitHub, then sign back in with your new account.

### **Expected Behavior**
I should be able to create new account and delete old account

**Additional Context/Questions**
Please delepy my account from your servers so that I can create a new git account

**Comment by kc0tlh** [comment]
@apai4 / @HeyGarrison please delete [ani.expo10@gmail.com](mailto:ani.expo10@gmail.com) from StackBlitz.com completely and close this issue when complete. Thanks!
