### ISSUE TITLE
Mathjax not working

### ISSUE THREAD

**Issue by JayasriRamu** [stackblitz/core#172]
I am new to angular. Mathjax not working, tried all the options & possibilities. Firebase is working good. Help or example needed. But, the same MathJax working in plunker.

**Comment by JayasriRamu** [comment]
https://angular-mathjax-try.stackblitz.io
This is my app url. Any suggestions please.....

**Comment by EricSimons** [comment]
Hey @JayasriRamu! So sorry about my delay on this — can you link the working plunkr demo here so I can help debug what's going wrong?

**Comment by JayasriRamu** [comment]
Thanx for the reply:

https://plnkr.co/edit/IEgtWraWKllAZRzHPVJ1?p=preview

The above plunk i am doing for my small application. The mathjax is working in .html file as well as .ts also. (In my question textfield if i type with mathjax  eg. \(X^3 \) ), it is working.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
