### ISSUE TITLE
SDK typings building error

### ISSUE THREAD

**Issue by korytoff** [stackblitz/core#1721]
### **Description of Bug**
Error while building application written on typescript

### **Steps to Reproduce**

1. Install the latest SDK (v.1.5.4) by NPM  `npm install --save @stackblitz/sdk`
2. Build an application (Angular in my case)
3. See error on console

### **Screenshots/Screencast**
<img width="1440" alt="Screenshot 2022-01-25 at 7 41 49 PM" src="https://user-images.githubusercontent.com/9613581/151020259-74d95f8d-c8aa-45b5-a82c-79aed1d2385a.png">

**Additional Context/Questions**

Wrong path strings in `@stackblitz/sdk/typings/index.d.ts`

```
Error: node_modules/@stackblitz/sdk/typings/index.d.ts:3:61 - error TS2307: Cannot find module '../../../../../../../Users/florens/Code/stackblitz/core/sdk/src/VM' or its corresponding type declarations.

3     connect: (frameEl: HTMLIFrameElement) => Promise<import("../../../../../../../Users/florens/Code/stackblitz/core/sdk/src/VM").VM>;
```

**Comment by fvsch** [comment]
Thanks for the report @korytoff! Now this is embarrassing 🙈

We’ll have a patch release with a fix out tomorrow.
In the meantime you can also install the previous version, which should compile correctly:

```
npm install @stackblitz/sdk@1.5.3
```

**Comment by fvsch** [comment]
This was closed a bit early, because the npm package was not published yet. It should be live as of a few hours ago.
@korytoff You should be able to use @stackblitz/sdk@1.5.5 now.
