### ISSUE TITLE
Stackblitz fails to run a project using convert-units package because the dependencies couldn't be resolved.

### ISSUE THREAD

**Issue by kenmorechalfant** [stackblitz/core#1723]
![The dependencies for this project couldn't be resolved. This usually means that a dependency in your package.json is incorrect.](https://user-images.githubusercontent.com/4629022/151270106-f39c968a-1fc7-41c2-8771-483d0f3f425f.png)

I am not able to open a Github repo of mine due to a problem resolving the dependencies. 

I created a separate branch to narrow down the issue and removed most of the dependencies. Then I added them back one by one, opening each commit in Stackblitz. It failed add soon as I added `convert-units` back. 

The package in question: `convert-units@2.3.4`.

- [https://stackblitz.com/github/kenmorechalfant/unit-converter-react/](https://stackblitz.com/github/kenmorechalfant/unit-converter-react/)
- [Commit that fails: https://stackblitz.com/github/kenmorechalfant/unit-converter-react/tree/82e...](https://stackblitz.com/github/kenmorechalfant/unit-converter-react/tree/82e9b89dbb96ff730b1ee1d039ca7f91917d4f69)
- [The commit](https://github.com/kenmorechalfant/unit-converter-react/commit/82e9b89dbb96ff730b1ee1d039ca7f91917d4f69)
- [Issue on `convert-units` repo](https://github.com/convert-units/convert-units/issues/231#issue-1115637950)

**Comment by kenmorechalfant** [comment]
I noticed that the package on the NPM website still references the old repo name/URL. 

It changed maintainers and moved from: `github.com/ben-ng/convert-units` to `github.com/convert-units/convert-units` 

Could that be the issue?

**Comment by kc0tlh** [comment]
This issue is now resolved!
