### ISSUE TITLE
The link of "live example" hero editor in the Tutorials (https://angular.io/tutorial/toh-pt1) does not work

### ISSUE THREAD

**Issue by yinglieng** [stackblitz/core#1726]
### **Description of Bug**
The link (https://angular.io/generated/live-examples/toh-pt1/stackblitz.html) of "live example" hero editor in the Tutorials (https://angular.io/tutorial/toh-pt1) does not work

### **Steps to Reproduce**

1. Go to Tutorials https://angular.io/tutorial/toh-pt1
2. Click on "live example" in the words "For the sample application that this page describes, see the live example / download example." on that homepage.
3. It goes to a homepage, with the words:
"Yikes! Something went wrong with your request.
If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core"

### **Expected Behavior**
Expected it will open the project of "hero editor" in stackblitz.com

### **Screenshots/Screencast**
![Screen Shot 2022-02-02 at 4 33 04 PM](https://user-images.githubusercontent.com/71150296/152262419-8fd33d1b-7890-453d-9885-6c3e21283a5b.jpg)

**Additional Context/Questions**

Add any other context or questions regarding this bug.

**Comment by apai4** [comment]
Thanks for reporting this! This was an issue with a recent update, the live example is now working again.
