### ISSUE TITLE
Preview of Static Template does not work on Firefox

### ISSUE THREAD

**Issue by SRendonn** [stackblitz/core#1732]
### **Description of Bug**
Preview of Static Template does not work on Firefox

### **Steps to Reproduce**

1. On Firefox, go to the homepage (https://stackblitz.com/).
2. Create a new project from the Static template (HTML/JS/CSS)
3. See preview
4. See error: "Error: ENOENT: No such file or directory., '/~'"

### **Expected Behavior**
Project preview should load properly and display index.html.

### **Screenshots/Screencast**

Selected project template
![image](https://user-images.githubusercontent.com/22451946/152761205-a204bd47-db75-4623-9343-a9df72cff01f.png)

Behaviour on Chrome/Edge (Chromium-based)
![image](https://user-images.githubusercontent.com/22451946/152761359-38cccbc6-31a8-454d-919b-81f6a2c3c759.png)

Behaviour on Firefox
![image](https://user-images.githubusercontent.com/22451946/152760961-2d201ba0-1d01-4d95-86d2-3e2aecc7bcc5.png)

**Additional Context/Questions**
* Tested on different devices.
* Used both Strict and Standard Tracking Protection.

**Comment by jmrsuarez** [comment]
I also have the same issue, 
![imagen](https://user-images.githubusercontent.com/13615559/167071051-5a24c012-7a5b-4c7b-a5b7-141d033a18b0.png)

**Comment by tomsotte** [comment]
Same here on Firefox 100.0 on macOS 12.3.1

**Comment by fvsch** [comment]
Thanks @SRendonn for this excellent bug report!

I’m closing it as a duplicate in favor of the earlier https://github.com/stackblitz/core/issues/1679
