### ISSUE TITLE
Wrong description when you create a blank node app

### ISSUE THREAD

**Issue by genelorenzSarmiento0408** [stackblitz/core#1733]
### **Wrong description when you create a blank node app**
When I create a new node app the description says "A node project based on react and react-dom.". My project is not React-based

### **Steps to Reproduce**

1. Go to Stackblitz
2. Click on Node.js (blank project)
3. See error/bug

### **Expected Behavior**
I should expect "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine." or near to that

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/69145401/152905468-103f7f14-a9c8-4a83-ad00-d8c0bb0e6a8e.png)

**Additional Context/Questions**
Is this a bug or just a feature?

**Comment by EricSimons** [comment]
Great catch, thanks @genelorenzSarmiento0408! This is now fixed on prod 👍
