### ISSUE TITLE
File Manager/Tree Issue

### ISSUE THREAD

**Issue by MaskedMatters** [stackblitz/core#1734]
### **Description of Bug**
When I click to open a file from the file manager tree it does not open (specifically on a node.js project trying to open package.json)

### **Steps to Reproduce**

1. Make a new Node.js project
2. Click on the package.json file
4. See error (it does not open)

### **Expected Behavior**
I thought that it would actually open the file like it should

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by kc0tlh** [comment]
This issue has been resolved. Navigate to [node.new](https://node.new/) to validate!
