### ISSUE TITLE
Unable to create new project.

### ISSUE THREAD

**Issue by singhguri** [stackblitz/core#1736]
### **Description of Bug**
Unable to create a any new project, neither from backend nor from frontend.

### **Steps to Reproduce**

1. Go to 'https://stackblitz.com/'
2. Click on any technology to create new project.
3. The query parameters 'owner and provider' are coming undefined .

### **Expected Behavior**
I expected to get the project created in the desired technology.

### **Screenshots/Screencast**
![error](https://user-images.githubusercontent.com/61290735/153125100-44f29605-ea03-4e40-a26c-36dfdcb5cef1.png)

**Additional Context/Questions**
Please solve this ASAP.

**Comment by singhguri** [comment]
Unable to create a new project specifically when you are logged in via GitHub.

**Comment by SamVerschueren** [comment]
@singhguri Thanks for the report! This was an issue on our end and should be fixed now.

**Comment by singhguri** [comment]
Thanks
