### ISSUE TITLE
Referring to incorrect repository?

### ISSUE THREAD

**Issue by Cyburstud** [stackblitz/core#1738]
I'm not sure if the repository structure changed or they moved the template, but it appears that the Astro Docs template is not properly importing. The same is also happeening with the Astro Blog. I believe the correct repository might be the available templates under the following directory: 

withastro/snowpack/tree/main/create-snowpack-app/

![Screenshot 2022-02-09 15 16 10](https://user-images.githubusercontent.com/77064515/153292021-08c7db57-d4f3-425b-8b69-a74928ed3805.png)

**Comment by SamVerschueren** [comment]
Hi @Cyburstud ! Thanks for letting us know. Apparently the repo got an overhaul and the links didn't resolve. We fixed this on our end so it should work again.
