### ISSUE TITLE
Package Errors

### ISSUE THREAD

**Issue by jokeefe1** [stackblitz/core#174]
**When I added npm packages (react-router, react-history) to my project I received the following errors:**

Can't find modules:
fbjs/lib/warning (@0.8.16)
fbjs/lib/ExecutionEnvironment (@0.8.16)
fbjs/lib/emptyObject (@0.8.16)
fbjs/lib/invariant (@0.8.16)
fbjs/lib/emptyFunction (@0.8.16)
prop-types/factory (@15.6.0)
create-react-class/factory (@15.6.2)
fbjs/lib/shallowEqual (@0.8.16)
fbjs/lib/EventListener (@0.8.16)
fbjs/lib/getUnboundedScrollPosition (@0.8.16)
fbjs/lib/getActiveElement (@0.8.16)
fbjs/lib/performanceNow (@0.8.16)
fbjs/lib/containsNode (@0.8.16)
fbjs/lib/focusNode (@0.8.16)
fbjs/lib/camelizeStyleName (@0.8.16)
fbjs/lib/hyphenateStyleName (@0.8.16)
fbjs/lib/memoizeStringOnly (@0.8.16)
fbjs/lib/createNodesFromMarkup (@0.8.16)

Please check your import statements & ensure you're importing the correct module names.

**In the console I receive the following errors:**

g @ VM3061 preview-0b9c6928e245e63b2324.js:1
(anonymous) @ VM3061 preview-0b9c6928e245e63b2324.js:1
Promise resolved (async)
v.PREVIEW_INSTANTIATE_DIFF @ VM3061 preview-0b9c6928e245e63b2324.js:1
(anonymous) @ VM3061 preview-0b9c6928e245e63b2324.js:1
dispatch @ VM3061 preview-0b9c6928e245e63b2324.js:1
(anonymous) @ VM3061 preview-0b9c6928e245e63b2324.js:1
window.onmessage @ VM3061 preview-0b9c6928e245e63b2324.js:1
postMessage (async)
post @ client-f5d00ad53804b93d4f49.js:12
(anonymous) @ client-f5d00ad53804b93d4f49.js:12
post @ client-f5d00ad53804b93d4f49.js:12
dispatch @ client-f5d00ad53804b93d4f49.js:12
(anonymous) @ client-f5d00ad53804b93d4f49.js:12
x.(anonymous function) @ client-f5d00ad53804b93d4f49.js:60
(anonymous) @ client-f5d00ad53804b93d4f49.js:12
dispatch @ client-f5d00ad53804b93d4f49.js:12
(anonymous) @ client-f5d00ad53804b93d4f49.js:12
(anonymous) @ client-f5d00ad53804b93d4f49.js:12
Fetch API cannot load https://unpkg.com/react-router@4.2.0/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
/edit/react-57xnek?file=Pages%2FLayout.js:1 Fetch API cannot load https://unpkg.com/react-router@4.2.0/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
Fetch API cannot load https://unpkg.com/fbjs@0.8.16/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
/edit/react-57xnek?file=Pages%2FLayout.js:1 Fetch API cannot load https://unpkg.com/fbjs@0.8.16/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
Fetch API cannot load https://unpkg.com/prop-types@15.6.0/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
/edit/react-57xnek?file=Pages%2FLayout.js:1 Fetch API cannot load https://unpkg.com/prop-types@15.6.0/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
Fetch API cannot load https://unpkg.com/create-react-class@15.6.2/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
/edit/react-57xnek?file=Pages%2FLayout.js:1 Fetch API cannot load https://unpkg.com/create-react-class@15.6.2/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
Fetch API cannot load https://unpkg.com/react-history@1.0.0/?meta. Redirects to data: URL are allowed only when mode is "no-cors".
/edit/react-57xnek?file=Pages%2FLayout.js:1 Fetch API cannot load https://unpkg.com/react-history@1.0.0/?meta. Redirects to data: URL are allowed only when mode is "no-cors".

My project appears unrecoverable at this point. I tried unistalling the packages but still received the errors. I hope this can be fixed soon because I really like using your software.  Thank you in advance.

**Comment by EricSimons** [comment]
That's super weird! Can you link your project here so I can debug?

**Comment by jokeefe1** [comment]
Here is the link to the editor:
https://stackblitz.com/edit/react-57xnek

Let me know if you require anything else. Thank you for the quick reply.

J.

**Comment by EricSimons** [comment]
@jokeefe1 it seems to be working perfectly on my end actually — can you try disabling any browser extensions you have on and see if that fixes it? Sometimes people report that adblock will cause certain things to break. (Also, what browser are you using?)

**Comment by jokeefe1** [comment]
You solved it! It was my ad-blocker causing the issue. I disabled it for
the site and I am up and running again. Thank you for the quick reply and
solution.

By the way, I'm really enjoying the Stackblitz software -- thank you!

J.
