### ISSUE TITLE
"Unable to resolve package" for valid package and version

### ISSUE THREAD

**Issue by bengummer** [stackblitz/core#175]
Steps to repro:

1. Go to https://stackblitz.com/edit/react-bppyn3
2. Click "Install missing packages"

Expected result: demo rendered

Actual result:

![image](https://user-images.githubusercontent.com/1089897/31784602-2b27e6da-b4b7-11e7-8476-51e740abb3b1.png)

This same demo seems to work on codesandbox.io so not sure why @atlaskit/spinner is not resolving correctly.

**Comment by EricSimons** [comment]
@bengummer it looks like there's a dep package of `@atlaskit/spinner` than has a malformed package.json which was causing this; just put in a fix for it. Can you try refreshing the page & letting me know if it works?

**Comment by bengummer** [comment]
Looks good now thanks @EricSimons 👍
