### ISSUE TITLE
d3 dep and missing packages

### ISSUE THREAD

**Issue by albertosantini** [stackblitz/core#176]
How to reproduce the issue:

- Use the angular template - https://stackblitz.com/fork/angular
- Add "d3" dep in dependencies (installed ok)
- Open "app/app.component.ts" file
- Add the line `import * as d3 from 'd3';`
- Just use d3 object adding `myD3 = d3;` in AppComponent class below `name`.

Now you see in the live window the following message:

```
Can't find packages:
url child_process fs http https
```

Repro link: https://stackblitz.com/edit/angular-bcqwa2?file=app%2Fapp.component.ts

If you use an external resource, the usual script, it works fine.
For instance, https://stackblitz.com/edit/angularjs-irc-starter-g6g1zi?file=app%2Fbarchart.component.ts

**Comment by EricSimons** [comment]
@albertosantini excellent catch on this — the browser is attempting to use the node version of D3 (which is what the main field points at), whereas we actually would want to run the versions listed in the unpkg/jsdeliver field. I'm going to put a fix in for this asap, but until then if you import `import * as d3 from 'd3/build/d3'` that should fix it :)

Will circle back once I've got this fixed!

**Comment by albertosantini** [comment]
Thanks for the details. :)
Nice workaround.

**Comment by seekheart** [comment]
ironically I didn't have that issue for my library that uses d3 in angular. Shameless [plug] (https://github.com/seekheart/ngz-charts)

**Comment by nclarx** [comment]
Try adding D3 to angular-cli.json:

```
{
   "scripts": [
      "pathToD3ScriptHere"
   ]
} 
```

See the @angular/cli wiki for more details: https://github.com/angular/angular-cli/wiki/stories-global-scripts

x-posted from Discord.

**Comment by EricSimons** [comment]
Hey all - just fixed this! Closing issue but lmk if you still have troubles 👍

**Comment by albertosantini** [comment]
@EricSimons Thanks, it works ok. :)

I add this note, just in case other users don't note any difference. 
If you land on the repro link above, you see the same error message, `install missing packages`.
You need to update `d3` package to bundle again the app.
