### ISSUE TITLE
Unable to import js-temporal/temporal-polyfill

### ISSUE THREAD

**Issue by 12wrigja** [stackblitz/core#1773]
Following https://developer.stackblitz.com/docs/platform/importing-projects/#import-from-github, I was attempting to setup a stackblitz showcasing the Temporal polyfill.

I tried navigating to

https://stackblitz.com/github/js-temporal/temporal-polyfill

and was met with an error message saying to file a bug.

**Comment by 12wrigja** [comment]
Friendly ping - We'd really like to include a Stackblitz link as part of our issue template, but this is still blocking.

**Comment by HeyGarrison** [comment]
👋 

Sorry for the delay here... I just tried to run your project and it looks like it's working as expected. Let me know if you need any additional help.

Thanks!

**Comment by 12wrigja** [comment]
Thanks for responding - I had honestly forgotten I had filed this. Things do seem to work now :)
