### ISSUE TITLE
Stackblitz Preview Is Not Working

### ISSUE THREAD

**Issue by ajanthiv** [stackblitz/core#1777]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
The preview experience of Hydrogen on Stackblitz is broken

### **Steps to Reproduce**

1. Go to 'https://hydrogen.new/'

### **Expected Behavior**
Stackblitz should load, the project should install and compile, and the store preview should load

### **Screenshots/Screencast**
![Screen Shot 2022-03-08 at 5 17 14 PM](https://user-images.githubusercontent.com/6493584/157335221-72301d6b-b0f2-4d44-9184-563c27dbdf57.png)

**Additional Context/Questions**
N/A

**Comment by fvsch** [comment]
Hi @ajanthiv, sorry for not replying earlier. Are you still seeing this issue?
We can't reproduce it on our end, and wonder if that was just a temporary server glitch.
