### ISSUE TITLE
Dependencies for this project couldn't be resolved

### ISSUE THREAD

**Issue by nadvolod** [stackblitz/core#1778]
I'm trying to open the following url https://stackblitz.com/github/nadvolod/comprehensive-testing-js/ and seeing this error. Not sure why it's happening as I can install everything locally.
<img width="579" alt="Screen Shot 2022-03-09 at 1 38 20 PM" src="https://user-images.githubusercontent.com/2136245/157509046-2737832e-c942-4a8b-bea3-2df4a4a36f0f.png">

**Comment by HeyGarrison** [comment]
👋 

It looks like this is working now!

Over the past few years our platform has changed a lot for the better. We've been shipping a ton. Glad we resolved this issue!
