### ISSUE TITLE
Prinda wigidgindawng

### ISSUE THREAD

**Issue by prindawigidgindawong** [stackblitz/core#1784]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.
[Hey,  I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.  Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).  StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!  Interested to learn more?  Cheers, Alex Berger  Head of Enterprise Growth @StackBlitz P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.  If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:  StackBlitz, Inc. 2443 Fillmore Street #380-16814 San Francisco, CA 94115 United States](Hey,  I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.  Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).  StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!  Interested to learn more?  Cheers, Alex Berger  Head of Enterprise Growth @StackBlitz P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.  If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:  StackBlitz, Inc. 2443 Fillmore Street #380-16814 San Francisco, CA 94115 United States)

**Comment by prindawigidgindawong** [comment]
<div class="divbody_mr_css_attr" style="overflow-wrap: break-word; color: rgb(0, 0, 0); font-size: 15.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; margin: 0px; outline: none; padding: 0px; font-family: arial; line-height: 1.1; width: 328px; background: rgb(255, 255, 255); text-align: center;">

Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitzP.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitzP.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States
-- | -- | -- | -- | -- | -- | -- | --
Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitzP.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States
Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz
Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz | Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz
Hey,I saw you took a look at the Google case study a few days back - thanks! We were really excited to share their success with our users.Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!Interested to learn more?Cheers,Alex BergerHead of Enterprise Growth @StackBlitz
P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States
P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States | P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States
P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can unsubscribe.If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:StackBlitz, Inc.2443 Fillmore Street #380-16814San Francisco, CA 94115United States

</div><img src="https://proxy.staticmy.com/?email=aek351116%40gmail.com&amp;e=1647424335&amp;h=ulSafQZ0iOsr_Ds3O8pTDg&amp;url171=c3RhY2tibGl0ei5sdC5lbWxuazEuY29tL1Byb2QvbGluay10cmFja2VyP25sPTEyJmM9MzYmbT0xNzg3JnM9NWQzMTE2ZmQwZDU4ZjAxNjYwYzhlNDg1ZWI3NjkwNzMmbD1vcGVuJmFjY291bnQ9c3RhY2tibGl0ei5hY3RpdmVob3N0ZWQuY29tJmE9NjcwNTI5NjI~&amp;is_https=1" border="0" width="1" height="1" style="overflow-wrap: break-word; display: block; color: rgb(0, 0, 0); font-family: helvetica; font-size: 15.3333px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; border: 0px; overflow: hidden; width: 1px !important; min-width: 1px !important; max-width: 1px !important; height: 1px !important;"><br class="Apple-interchange-newline">Hey,

I saw you took a look at the [Google case study](https://stackblitz.lt.emlnk1.com/Prod/link-tracker?redirectUrl=aHR0cCUzQSUyRiUyRmUuc3RhdGljYmxpdHouY29tJTJGZ29vZ2xlLWNhc2Utc3R1ZHk=&sig=GEoKkR268Cg6kE97GiytWWoHfTRkdFKVzfU5Ff9gkbsT&iat=1647164958&a=%7C%7C67052962%7C%7C&account=stackblitz%2Eactivehosted%2Ecom&email=pSR6%2FNu4wBc9P5pM%2F1xSkUzkASpiHornD%2Fz2wZTd1jg%3D&s=5d3116fd0d58f01660c8e485eb769073&i=36A1787A12A240) a few days back - thanks! We were really excited to share their success with our users.

Newly remote engineering departments are struggling with collaborating asynchronously and onboarding new developers to their design systems/best practices. Difficulty in setting up new dev environments is one of the leading causes of frustration (especially with the corporate VPN & unstable residential internet connections).

StackBlitz Enterprise helps make collaboration seamless again (just like peeking over a colleagues shoulder in the office), reduces frustration for new developers, and gets collaborative projects moving at in-person speed again!

Interested to learn more?

Cheers,
Alex Berger

Head of Enterprise Growth [@StackBlitz](https://stackblitz.lt.emlnk1.com/Prod/link-tracker?redirectUrl=aHR0cHMlM0ElMkYlMkZ0d2l0dGVyLmNvbSUyRnN0YWNrYmxpdHo=&sig=13JAyfsgdGimUKorJvDnM4uDGBt5LuTo5495cHhyvw9C&iat=1647164958&a=%7C%7C67052962%7C%7C&account=stackblitz%2Eactivehosted%2Ecom&email=pSR6%2FNu4wBc9P5pM%2F1xSkUzkASpiHornD%2Fz2wZTd1jg%3D&s=5d3116fd0d58f01660c8e485eb769073&i=36A1787A12A241)
P.S. If you would prefer to not receive awesome emails from me, here's a handy dandy link where you can [unsubscribe](http://stackblitz.activehosted.com/proc.php?nl=12&c=36&m=1787&s=5d3116fd0d58f01660c8e485eb769073&act=unsub).

If you prefer snail mail, feel free to send us miscellaneous trinkets, marriage proposals, or anything else to our corporate address:

StackBlitz, Inc.
2443 Fillmore Street #380-16814
San Francisco, CA 94115
United States

**Comment by prindawigidgindawong** [comment]
#
![Uploading FHM_UUID.jpg…]()

**Comment by purplem1lk** [comment]
If you have any questions regarding this email, please reply to the email and we're happy to talk. Thanks!

**Comment by prindawigidgindawong** [comment]
prindaaek@gmail.com​
