### ISSUE TITLE
Several node projects not working

### ISSUE THREAD

**Issue by morauszkia** [stackblitz/core#1789]
### **Description of Bug**
I noticed recently that most of my node projects are not working: clicking on the links I only get an empty page. Url is ok.
Projects that are not working:
https://stackblitz.com/edit/node-6l9yzb
https://stackblitz.com/edit/node-922m3y
https://stackblitz.com/edit/node-ui1qyt
https://stackblitz.com/edit/node-uafv9p

Interestingly this works: https://stackblitz.com/edit/node-s9zukz

React and Vue project work ok.

### **Steps to Reproduce**
Open projects from dashboard or entering url.

### **Expected Behavior**
Webcontainer starts and I can access the files belonging to the project and run .js files.

### **Screenshots/Screencast**
https://drive.google.com/file/d/16Y2bnVOhbeZzKyxYQz-rrW9iP6bz1T5a/view?usp=sharing

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by fvsch** [comment]
Thanks for the report @morauszkia. I cannot reproduce the issue with Chrome — which seems to be the browser you’re using in your screen recording.

Could you check:

- If your Chrome version is up-to-date.
- If those projects load correctly when opened with a new Chrome profile or in a Guest session? (i.e. with default browser settings and no extensions)

**Comment by morauszkia** [comment]
Dear Florens,

Thanks for your reply. It seems that the issue was somehow resolved, at
least the projects seem to be working now.


Florens Verschelde ***@***.***> ezt írta (időpont: 2022. máj.
8., V, 10:15):
