### ISSUE TITLE
Support for just vanilla JS/TS

### ISSUE THREAD

**Issue by seekheart** [stackblitz/core#179]
wanted to ask if there will be support for nodeJS/ES6/TS and the likes in the future?

**Comment by EricSimons** [comment]
Vanilla [JS](https://stackblitz.com/fork/es6) and [TS](https://stackblitz.com/fork/typescript) are actually available right now :) We're working on Node support but that will likely be at least a few months out!

**Comment by seekheart** [comment]
@EricSimons is there a way to make one off the homepage or how did you make those?

**Comment by justinfagnani** [comment]
I can't seem to load modules from unpkg with the vanilla JS project linked above: https://stackblitz.com/edit/es6-2gvijl?file=index.js

A few questions/thoughts:

- Is there a way to turn off compiling of modules?
- Why does there need to be a loader configured?
- Importing non-JavaScript files, like CSS, isn't supported by browsers. If the default template allows this and uses it, they'll never be able to use native modules.

**Comment by seekheart** [comment]
I just ended up using the React setup

**Comment by ashclarke** [comment]
A vanilla ES6 "empty" project would be great.

**Comment by kamilmysliwiec** [comment]
@EricSimons are there any plans to bring typescript & node.js support in the near future?

**Comment by bileschi** [comment]
@EricSimons Vanilla ES6 apps are buildable and runnable right now, but apparently they can not be imported from GitHub just yet?  Only angular apps can be imported right now?  Am I understanding correctly?  Is there a timeline / roadmap for when/if non-angular repos would be supported?

**Comment by sulco** [comment]
Since the original question seems to be resolved, I'm closing this one, but please feel free to file a new issue if there are some other types of projects/configurations you'd like to address.
