### ISSUE TITLE
Using an Angular Material Custom Theme causes an Error involving .mjs exports and the @angular/material package

### ISSUE THREAD

**Issue by edezekiel** [stackblitz/core#1792]
### **Description of Bug**

Stackblitz does not compile Angular v13.2 projects when the app contains a custom material theme.  The error `Missing "./fesm2015/material.mjs" export in "@angular/material" package` is displayed in the browser. The same repository runs as expected on a local machine (Node v16.14.0).

Commenting out "@use" in the styles.scss file seems to avoid the error.

### **Steps to Reproduce**

Go to https://stackblitz.com/github/edezekiel/dark-theme?file=src%2Fstyles.scss

### **Expected Behavior**

The page should load, displaying a button with the label 'Click'.

### **Screenshots/Screencast**

- Screenshot showing stackblitz error:
![Screen Shot 2022-03-16 at 9 52 33 AM](https://user-images.githubusercontent.com/19419310/158620891-6cb268eb-d1e7-4f37-977e-a558d02b6cc3.png)

- Example of project running locally
![Screen Shot 2022-03-16 at 9 52 54 AM](https://user-images.githubusercontent.com/19419310/158620865-b771f5f6-8033-4d65-8e9e-e48f39405815.png)

- Example of using the Angular CLI to generate a Custom theme
![Screen Shot 2022-03-16 at 10 06 42 AM](https://user-images.githubusercontent.com/19419310/158622123-0845b742-3226-4176-9887-1178b7401127.png)

**Additional Context/Questions**
The styles.scss file was populated automatically by the Angular CLI after running `ng add @angulal/material` (see the screenshot above).

**Comment by mifloma** [comment]
Same problem here: [https://stackblitz.com/edit/ngx-mat-backdrop-demo](https://stackblitz.com/edit/ngx-mat-backdrop-demo). Commenting out "@use" in the styles.scss file seems to avoid the error.  

Code works fine on localhost.

**Comment by moefinley** [comment]
I've hit the same problem using the Material team's component issue boilerplate https://components-issue-vjbtsz.stackblitz.io

**Comment by markwhitfeld** [comment]
This issue should now be resolved. It was resolved quite a while ago, but we missed this related issue.
Please re-open the issue if you are still experiencing this problem.
