### ISSUE TITLE
`strarsis/ionic-breadcrumbs-title-overlap-issue`: `The dependencies for this project couldn't be resolved.`

### ISSUE THREAD

**Issue by strarsis** [stackblitz/core#1795]
Trying to run https://github.com/strarsis/ionic-breadcrumbs-title-overlap-issue in Stackblitz:
https://stackblitz.com/github/strarsis/ionic-breadcrumbs-title-overlap-issue

Error while preparing:
````
The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.

If you think this is a bug, please [file an issue](https://github.com/stackblitz/core/issues/new) in our repo!
````

I can install the dependencies using `npm` or `yarn`, current `node` `LTS` version (`v16.14.0`).
It would be very helpful if more details can be shown, e.g. what command went wrong with what error.

**Comment by kc0tlh** [comment]
IONIC projects should just work at this point 🎉

Here are some [known good IONIC v7 templates](https://twitter.com/aaronksaunders/status/1694037022426509709) for StackBlitz.

And here are the docs on importing repos into our new VS Code editor: https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide

_Consolidated Ionic Issue: #219_
