### ISSUE TITLE
any way to use @types in angular template

### ISSUE THREAD

**Issue by chgc** [stackblitz/core#18]
I am wondering if there is any way to use @types/jquery and declare it in tsconfig types section

**Comment by doggy8088** [comment]
I met the same issue as well.  I'd like to provide something like `jQuery` intellisense in the editor by using `@types/jquery` package but I couldn't configure `tsconfig.json` at this time.

**Comment by EricSimons** [comment]
You can! All you need to do is just install the relevant @types package and we'll automatically import the definitions :)

**Comment by EricSimons** [comment]
@chgc @doggy8088 were ya'll able to get this working? Lmk!

**Comment by chgc** [comment]
@EricSimons  No Sir. I had no luck.
I added these 2 dependencies.
![](http://i.imgur.com/JoWEAd1.png)
and I got this error warning
![](http://i.imgur.com/ANW29qT.png)

Is there anything I done wrong?

**Comment by EricSimons** [comment]
You just need to import jQuery:

```
import $ from 'jquery';

$('.container').text('hello')
```

**Comment by chgc** [comment]
@EricSimons I tried your code. jquery can work, but I still got no intellisense for jquery.

**Comment by Scoutlebest** [comment]
Nice one guys

**Comment by seveves** [comment]
@chgc any update on this? If it's working we would be happy to close this issue to tidy up the issue tracker a bit 😄

**Comment by chgc** [comment]
@seveves Yes, it works great now.
