### ISSUE TITLE
module date-fns import

### ISSUE THREAD

**Issue by Gi972** [stackblitz/core#180]
Hello,

I  use a module  who don't import date-fns, but the editor want to import it
Once it works, once not.

the links : https://stackblitz.com/edit/react-drip

Thanks

**Comment by EricSimons** [comment]
@Gi972 I think I know what might be causing this; will dig in over the weekend and report back!

**Comment by Gi972** [comment]
Thanks Eric :+1:  :-)

**Comment by EricSimons** [comment]
Okay this should be fixed now! Can you see if it's working on your end and lmk?

**Comment by Gi972** [comment]
Hello @EricSimons ,

All is ok , if I found a other error similar I will reopen this issue.

Thanks
