### ISSUE TITLE
Can't contribute to docs

### ISSUE THREAD

**Issue by SteveALee** [stackblitz/core#1807]
### **Description of Bug**

I was going to make a quick PR for the docs but couldn't figure out how to.

Eg docs at https://developer.stackblitz.com/docs/platform/what-is-stackblitz.

### **Expected Behavior**

Feedback box on pages or link to docs GH repo.

The docs folder in core repo (linked to in docs page header) says docs have moved but does not give the new repo, just the live URI.

I searched the repos list for the word "docs" and searched the org for some text in the docs, neother gave me a repo to work with.

**Comment by sulco** [comment]
Hi @SteveALee, thanks for reporting that! I'm happy you care enough to be willing to help :)) We want to do a little bit of cleaning up for the docs repository first, but I think we should be good to open-source them in a couple of weeks, and well definitely welcome contributions!

**Comment by SteveALee** [comment]
Oops, seems I was making an assumption too far! :)

**Comment by kc0tlh** [comment]
@SteveALee our docs repo is now open source: https://github.com/stackblitz/docs. The easiest way to begin a contribution is by navigating to [https://pr.new/github.com/stackblitz/docs](https://pr.new/github.com/stackblitz/docs)
