### ISSUE TITLE
stackblitz issue

### ISSUE THREAD

**Issue by js08** [stackblitz/core#1808]
Hi,

I tried to import the below project in stackblitz but I am getting an issue. can you tell me how to fix it?

https://stackblitz.com/github/jbellizzi/timelapse-visualization/tree/01-building-useTimer

The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.

If you think this is a bug, please [file an issue](https://github.com/stackblitz/core/issues/new) in our repo!

**Comment by kc0tlh** [comment]
This issue is resolved:

<img width="721" alt="image" src="https://github.com/stackblitz/core/assets/1532264/d8936657-9ec1-4f17-9741-43cfd9dcf1d9">
