### ISSUE TITLE
Angular apps are broken in Microsoft Edge

### ISSUE THREAD

**Issue by LayZeeDK** [stackblitz/core#182]
When running an Angular app, the following message is shown in the live area when browsing with Microsoft Edge 15 or 16:
```
Fatal error:
Permission denied.

Evaluating https://unpkg.com/core-js@2.4.1/modules/_export.js
Evaluating https://unpkg.com/core-js@2.4.1/modules/es6.reflect.apply.js
Evaluating https://unpkg.com/core-js@2.4.1/es6/reflect.js
Evaluating polyfills.ts
Evaluating main.ts
Loading blitzapp
```

Example:
https://stackblitz.com/edit/ng-component-state

**Comment by EricSimons** [comment]
@LayZeeDK I just clicked the link and it seems to work fine for me 🤔  What browser/OS are you using?

**Comment by LayZeeDK** [comment]
I'm on Windows 10 64-bit build 1709. The problem does not occur in Chrome 64-bit, but occurs on Microsoft Edge versions 15 and 16.

**Comment by LayZeeDK** [comment]
Are you able to reproduce the issue, @EricSimons?

**Comment by apai4** [comment]
Sorry for the delay @LayZeeDK, we pushed a fix for this last week. Are you still having issues with this on Edge?

**Comment by LayZeeDK** [comment]
That is quite alright, @apai4. Confirmed working in Edge version 16.16299.
