### ISSUE TITLE
Error: Something went wrong with this repository

### ISSUE THREAD

**Issue by akvadrako** [stackblitz/core#1827]
I am trying to import this repo: https://stackblitz.com/github/akvadrako/site-xyz

And I only get the error message:

> Something went wrong with this repository.
>
> If you think this is a bug, please [file an issue](https://github.com/stackblitz/core/issues/new) in our repo!

**Comment by kc0tlh** [comment]
This issue is resolved:

<img width="723" alt="image" src="https://github.com/stackblitz/core/assets/1532264/768ca863-cadd-4bed-a14f-a3efd3372249">
