### ISSUE TITLE
Resolving imports from barrel files fails

### ISSUE THREAD

**Issue by RoxKilly** [stackblitz/core#183]
I have a root `AppModule` with the following routes (imported from an `AppRoutingModule`):

    const routes:Routes = [
        {path:'', redirectTo:'/home', pathMatch:'full'},
        {path:'home', loadChildren:'./home/home.module#HomeModule'},
     ];

The `AppComponent` has a `<router-outlet>`. The `HomeModule` has the following routes (imported from a `HomeRoutingModule`):

    const routes:Routes = [
      {
        path:'',
        component: HomeRootComponent,
        children: [
          {
            path:'',
            component: DashboardComponent
          }
        ]
      }
    ];

The `HomeRootComponent` has a `<router-outlet>`.  

When I navigate to the empty route, the router correctly redirects to the `/home` route and the `HomeModule` is instantiated (I log from the constructor). I expected the dashboard to be displayed within the `HomeRootComponent` outlet, itself within the `AppComponent` outlet.  However, neither the `HomeRootComponent`, nor the `DashboardComponent` gets instantiated. There is no error in the console.

The setup looks like it ought to work; that's why I suspect a possible Stackblitz issue. Am I missing something? Here is [a live demo](https://stackblitz.com/edit/pfx-ng-zkcy7h?file=app%2Fapp-routing.module.ts)

**Comment by RoxKilly** [comment]
The problem has to do with how I was importing/exporting my classes. I used a barrel file such as this:
```
export * from './home-routing.module';
export * from './home.module';
export * from './home-root.component';
export * from './dashboard/dashboard.component';
```
And I in turn imported from the barrel file. If instead, I import directly from the file exporting the relevant classes, the code works. [Here is a fixed version](https://stackblitz.com/edit/pfx-ng-zkcy7h-nobarrel?file=app%2Fhome%2Fhome.module.ts).

**Comment by EricSimons** [comment]
I just exported to local and ran with Ang CLI and it seems like it's doing the same thing, so I don't think this is a stackblitz specific issue 🤔  Glad to hear you got it resolved though!

**Comment by RoxKilly** [comment]
@EricSimons then I think this could be closed. That'll teach me to try being clever with my barrel magic.
