### ISSUE TITLE
 Object doesn't support property or method 'includes' in IE 11

### ISSUE THREAD

**Issue by yogeshgadge** [stackblitz/core#184]
Go to https://stackblitz.com/ in IE 11
The main page shows the following:

> ` Object doesn't support property or method 'includes' `

and
> `Unhandled promise rejection Error: Cannot parse given Error object` in the console

I can't edit the files to uncomment those es6 polyfills.ts.

![angular_demo](https://user-images.githubusercontent.com/2423608/32509922-d8f25462-c3bc-11e7-8bd7-ba2a6f800ef1.png)

polyfill.ts changed for IE 11.
For this I had to use Firefox (as stackblitz is broken in Chrome as well) to edit polyfill.ts and add dependencies to load it back into IE 11. Same issue.

**Comment by yiochen** [comment]
I think the editor is not supporting IE 11. but the preview should. I launch the empty react project in preview in IE11 and get the same error of
> Object doesn't support property or method 'includes'

I believe this could be fixed by just including a polyfill for `include`.

cc @EricSimons

**Comment by apai4** [comment]
@yogeshgadge @yiochen @SargoDarya just added the polyfills required for the editor to run in IE11, lmk if you guys run into any issues!

**Comment by purplem1lk** [comment]
The resolution for this issue has been addressed by @apai4 and will be closed accordingly. Feel free to tag me regarding any information about this issue. Thank you!
