### ISSUE TITLE
Compiling Changes Last Forever

### ISSUE THREAD

**Issue by strawstack** [stackblitz/core#1842]
### **Description of Bug**

When I make some basic changes to a Javascript ReactJS app, it says "Compiling Changes" forever at the bottom of the editor and the preview never updates. I'm on Windows 11 in Chrome.

### **Expected Behavior**
Hot reload should just work as it normally does.

### **Screenshots/Screencast**
![compiling](https://user-images.githubusercontent.com/3249652/164499831-e708811b-8b20-41a8-8856-e6cdadffadf7.png)

**Comment by praveencodeeasy** [comment]
facing the same issue

**Comment by markwhitfeld** [comment]
I cannot reproduce this issue, please could you provide a link to an example project with this issue?
Closing until a repro link and reasonable reproduction steps are provided.
