### ISSUE TITLE
New account created with same email address

### ISSUE THREAD

**Issue by ayoubkhan558** [stackblitz/core#1845]
Hi, I forget 2FA on Github so I have to create a new account with the same email & same username.

So it was a different account but the same email so I was unable to login into stackblitz. 

Please resolve this.

![image](https://user-images.githubusercontent.com/99708427/164910830-cd7d391d-cff8-4cb2-a537-ad5a512dc975.png)

**Comment by betcorg** [comment]
Same problem! 

Yikes! It looks like there's already an account with your username or email
If you recently changed your username or email on GitHub, it's possible that your username or email was previously used at StackBlitz with another account. If you are in posession of the existing account on StackBlitz, sign in with that account first to update the GitHub profile, or change your email on GitHub, then sign back in with your new account.

If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core

How can i fix that?

**Comment by kc0tlh** [comment]
Hi @betcorg & @ayoubkhan558 sorry for your inconvenience! This is indeed a known issue (progress towards permanent resolution tracked at #1402). 

Unfortunately we will need to delete your old StackBlitz accounts to allow you to log back into the application. Do either of you have important projects on the old accounts that you need to save? 

When you are ready for the account deletion/reset to occur, please email us (hello@stackblitz.com) OR respond here with the email addresses associated with your Github/StackBlitz accounts and we will delete the old accounts, allowing you to log back in with your new github accounts!

**Comment by betcorg** [comment]
Hi @kc0tlh! . Thanks for answering. Of course you can delete my old account, no problem. Thanks again for your help!
My email asociated is betcorg@gmail.com

**Comment by kc0tlh** [comment]
@betcorg I will shoot you a confirmation when the request has been processed!

**Comment by ayoubkhan558** [comment]
Hi @kc0tlh! . Please delete my old account, no problem. Thanks again for your help!
My email asociated is [ayoubkhan558@hotmail.com](mailto:ayoubkhan558@hotmail.com)

**Comment by kc0tlh** [comment]
@ayoubkhan558 and @betcorg, both of your accounts have been deleted. Let me know if you have any additional issues!

**Comment by nomorejalapenos** [comment]
I have the same problem. Can someone delete my old account? nomorejalapenos@gmail.com

**Comment by lucskyost** [comment]
Hi @kc0tlh . Please delete my old account, no problem. Thanks for your help!
My old account is lucskyinfosec. My email asociated is nguyencongluc.82@gmail.com
