### ISSUE TITLE
Unable to clone repository: "Something went wrong..."

### ISSUE THREAD

**Issue by genemars** [stackblitz/core#1848]
I am trying to open the following project

https://stackblitz.com/github/zuixjs/news-blog

but it got stuck saying "Cloning repo from GitHub".

Closing and reopening the browser the following error message is reported:

![Schermata da 2022-04-26 05-50-58](https://user-images.githubusercontent.com/6654265/165217439-c41d1a16-8e2c-4b6a-ac74-3f447320dd96.png)

 I think it was working a couple of days ago.

**Comment by HeyGarrison** [comment]
👋 

Over the past few years our platform has rapidly improved. One of our improvements was our next gen editor which we're in the process of flipping everything over to. For now, you might try and work around this issue pr.new.

Here are the docs for the feature: https://developer.stackblitz.com/codeflow/using-pr-new#frontmatter-title

And this is the link to your repo directly: https://stackblitz.com/~/github.com/zuixjs/news-blog
