### ISSUE TITLE
Add external js files in angular4 

### ISSUE THREAD

**Issue by nkarmaani** [stackblitz/core#185]
I am unable to add external js files that will render as script tags in main index.html file

**Comment by nkarmaani** [comment]
Actually i am using "external resources" tab to get my external js in index.html.

and they are also rendering but

still jquery is not firing.

**Comment by nkarmaani** [comment]
Check this is my demo project 

https://nkangularapp.stackblitz.io/Home

**Comment by sulco** [comment]
Since there's no recent action on this, and the project seem to work at this moment, I'm closing it but feel free to reopen if you are still experiencing this issue.
