### ISSUE TITLE
Multiple entry point packages unable to import in code

### ISSUE THREAD

**Issue by barelyhuman** [stackblitz/core#1852]
### **Description of Bug**
Unable to import packages that only have a `exports` field to define entry points
eg: `zustand` , `valtio` , `@barelyhuman/useless`

The simplest code that can re-produce this would be the following 
```js
import React from 'react';
import { proxy, useSnapshot } from 'valtio';

const s = proxy({ c: 1 });
export default () => {
  const snap = useSnapshot(s);
  return <h1>c:{snap.c}</h1>;
};
```
or even if we specify a browser / umd /esm path 

```js
import { proxy, useSnapshot } from 'valtio/esm/index.mjs'; //infinite loader
import { proxy, useSnapshot } from 'valtio/umd/index.production'; //infinite loader
```

### **Steps to Reproduce**

1. Go to 'https://stackblitz.com/'
2. Click on 'React TS templte'
3. Add in one of the above mentioned packages and try to execute them
4. Either see an infinite loader or `Cannot use import statement outside a module` 

**Additional Context/Questions**

I'd like to know how turbo is handling the `exports` field or is it something that needs to be configured specifically in template, either way, if you can help me debug, we can add the needed fix to the above mentioned packages. 

Reference Issue: https://github.com/pmndrs/valtio/issues/448

**Comment by lynxife** [comment]
Any progress? It's a long time since the bug reported..

**Comment by markwhitfeld** [comment]
@barelyhuman @lynxife This issue should now be resolved. It is resolved for your reproduction and other variants of the same issue. Please re-open the issue if you are still experiencing this problem.
