### ISSUE TITLE
Update devDependencies when calling openProject SDK method

### ISSUE THREAD

**Issue by iKrishnaSahu** [stackblitz/core#1854]
Is there a way to update devDependencies when calling [openProject](https://developer.stackblitz.com/docs/platform/javascript-sdk/#sdkopenprojectproject-opts) SDK method?

Also I am seeing existing devDependencies in my dynamic stackblitz project. Not sure from where exactly it is coming.

FYI, I am using private stackblitz instance.

**Comment by fvsch** [comment]
Hi @iKrishnaSahu.

I’m not sure what you mean by “update devDependencies”, could you clarify?
Do you have an example project or repository showing what you're trying to do?

**Comment by EricSimons** [comment]
@iKrishnaSahu if you pass along a package.json file with the devDependencies set in it (via the SDK's `files` parameter) that should do the trick!

**Comment by iKrishnaSahu** [comment]
> Hi @iKrishnaSahu.
> 
> I’m not sure what you mean by “update devDependencies”, could you clarify? Do you have an example project or repository showing what you're trying to do?

Hi @fvsch,
In package.json, almost everyone will have two sections in which they mention dependencies. One is `dependencies` and other is `devDependencies`.
I can update the `dependencies` using [dependencies](https://github.com/stackblitz/core/blob/bc4c6754457ae4dfc33ed6b526409dbe1232de80/sdk/src/interfaces.ts#L28) field.
So my question is - is there any field/way to update `devDependencies`?

FYI, I am working a private repo.

**Comment by iKrishnaSahu** [comment]
> @iKrishnaSahu if you pass along a package.json file with the devDependencies set in it (via the SDK's `files` parameter) that should do the trick!

@EricSimons I tried this. This does not work in case of EngineBlock. 
Passing package.json in sdk's `files` field will only work for WebContainer based Stackblitz application as stated [here](https://github.com/stackblitz/core/blob/bc4c6754457ae4dfc33ed6b526409dbe1232de80/sdk/src/interfaces.ts#L25).

**Comment by iKrishnaSahu** [comment]
@EricSimons, @fvsch do you have any updates for me?

**Comment by EricSimons** [comment]
Hi @iKrishnaSahu - your analysis here was 100% correct, thanks for all the help on isolating the issue. We've been discussing internally how we should go about addressing this and are planning to ship an update to both .com and EE to remedy. I'm not sure yet on exact timeframe but I'll touch base with the team on Monday and circle back here with a clear timeframe in which we expect to ship it!

**Comment by iKrishnaSahu** [comment]
Great. Thanks for the update @EricSimons

**Comment by EricSimons** [comment]
@iKrishnaSahu unfortunately a couple of our team members were out this week which has delayed this conversation. I'm touching base with them on Tuesday though to get this sorted. Thanks for your patience here and I'll circle back here on Tuesday with the plan of action

**Comment by apai4** [comment]
@iKrishnaSahu what @EricSimons suggested with providing a `package.json` should work, see this example: 

https://stackblitz.com/edit/sdk-create-angular-project?file=templates%2Fangular.ts

You can modify the `devDependencies` for the `package.json` on a given payload and those changes will be reflected in the newly generated project. If a `package.json` is provided for an EngineBlock project, that will be used as the base for the project.

EngineBlock projects won't throw errors when there are mismatching `devDependencies` though, so when providing a `package.json` the caller needs to ensure the set of `devDependencies` are valid if the code is being run elsewhere.

The `dependencies` option for the SDK still remains the source of truth for the dependencies that get resolved for EngineBlock projects see further below in the example where you can try out the behavior when both  `dependencies` and a `package.json` are provided.

**Comment by iKrishnaSahu** [comment]
@apai4 this seems great but as a workaround.

**Comment by fvsch** [comment]
We have more information about managing dependencies when using the SDK in this documentation page:
https://developer.stackblitz.com/platform/api/javascript-sdk-dependencies

**Comment by kc0tlh** [comment]
This fix was shipped months ago. Closing this issue as resolved!
