### ISSUE TITLE
iPad Pro GitHub repository cloning not working

### ISSUE THREAD

**Issue by mikhael28** [stackblitz/core#1858]
Hi there, I run an open-source project which is somewhat popular https://GitHub.com/mikhael28/paretOS and which is a reasonably complex react application, though not too complex. When importing it on my account, it just says ‘One of your npm dependencies is incorrect’ which essentially makes your solution unusable for me on my iPad Pro (Safari, latest iPadOS). Hard for me to recommend your product until then, though I would love to. I guess I will try GitHub’s Codespaces

**Comment by HeyGarrison** [comment]
@mikhael28 you might try using pr.new to open your repo in our next gen editor. Check that out here: pr.new/mikhael28/paretOS.

Also, see the docs here: https://developer.stackblitz.com/codeflow/using-pr-new#frontmatter-title

**Comment by mikhael28** [comment]
@HeyGarrison thanks for responding! I gave up trying to code on an iPad, though I may take up the challenge again sometime soon. I will look into your next gen editor then, thanks again!
