### ISSUE TITLE
Storybook CRA Stackblitz not working

### ISSUE THREAD

**Issue by oscard0m** [stackblitz/core#1862]
**Storybook CRA (main branch)**
https://stackblitz.com/github/storybookjs/repro-templates/tree/main/cra?preset=node
![image](https://user-images.githubusercontent.com/2574275/167269682-a5259bbc-f7c8-47a8-8355-3a01bea69664.png)

**Storybook CRA (next branch)**
https://stackblitz.com/github/storybookjs/repro-templates/tree/next/cra?preset=node
![image](https://user-images.githubusercontent.com/2574275/167269671-25db7682-6b0f-47ae-95bd-7e31691e6d1e.png)

Repository:
https://github.com/storybookjs/repro-templates/

Causes https://github.com/storybookjs/repro-templates/issues/2

**Comment by EricSimons** [comment]
Just investigated- this appears to be an issue with the Storybook repo itself: https://github.com/storybookjs/repro-templates/issues/2#issuecomment-1120292993

Closing for now, but can reopen if there's something wrong on our side!
