### ISSUE TITLE
vite's "open in editor" creates a new file instead of jumping to the correct pos in the existing file

### ISSUE THREAD

**Issue by dominikg** [stackblitz/core#1870]
### **Description of Bug**
Vite contains a middleware that allows you to open files in an editor. The main use for that is clickable links in stack frames of error overlays.
It works by sending a request to `__open-in-editor?file=filename.ext:line:col`. 

vite-plugin-svelte uses this for it's builtin inspector mode that is similar to vite-plugin-vue-inspector.

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/vitejs-vite-2daevy
2. when the dev page shows, click on the top-right inspector button (svelte-logo with a pointer)
3. cursor turns into the same icon, move it over HELLO WORLD, the tooltip reads `App.svelte:8:3`
4. leftclick
5. a new file `App.svelte:8:3` is opened with empty content

### **Expected Behavior**
It should open `App.svelte` and place the cursor on line 8 column 3

**Additional Context/Questions**
- vite uses launch-editor to open the editor: https://github.com/yyx990803/launch-editor
- vite-plugin-vue-inspector uses a different internal implemenation that also works with sb: https://stackblitz.com/edit/vitejs-vite-svedqw.

**Comment by dominikg** [comment]
cc @SamVerschueren . 

According to [twitter](https://twitter.com/stackblitz/status/1519690972329820160) you built the integration for vite-plugin-vue-inspector. Any idea what's missing here?

**Comment by SamVerschueren** [comment]
Thanks for reporting. I'll have a closer look in a bit. I quickly skimmed through the code and it looks like it should work correctly, so not sure what goes wrong. Will keep you posted!

**Comment by SamVerschueren** [comment]
Found the issue. I'll fix it and keep you posted when it's released.

**Comment by SamVerschueren** [comment]
I just made a new release and it seems to work now 🎉 !
