### ISSUE TITLE
Clicking on "Fork on StackBlitz" navigates to incorrect link

### ISSUE THREAD

**Issue by liby** [stackblitz/core#1887]
### **Description of Bug**

Creating projects with the SDK, load a project from GitHub that points to specific branch. 
Click on `Fork on StackBlitz` to navigates to `main` branch.

Project link: [src/pages/examples/[[...slug]].tsx](https://github.com/contentlayerdev/website/blob/main/src/pages/examples/%5B%5B...slug%5D%5D.tsx#L81)

### **Steps to Reproduce**

1. Go to 'https://www.contentlayer.dev/examples/nextjs'
2. Click on `Fork on StackBlitz`
3. See `contentlayerdev/next-contentlayer-example/tree/main` branch

### **Expected Behavior**

Expect to see the specified branch. It should be `contentlayerdev/next-contentlayer-example/tree/stackblitz-demo` here.

#### `contentlayerdev/next-contentlayer-example/tree/stackblitz-demo`
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/38807139/172045743-37d38405-8fd9-4b6f-9127-d4219c08f22c.png">

#### `contentlayerdev/next-contentlayer-example/tree/main`
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/38807139/172045763-fd02bfd1-b29f-4d8e-b421-401a02af6f85.png">

**Additional Context/Questions**
Links like `/remix-run/react-router/tree/main/examples/basic`, clicking on `Fork on StackBlitz` will see error page.
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/38807139/172045886-64d2922e-3f99-4660-abfb-ae5506f0e2cc.png">

**Comment by fvsch** [comment]
Thanks a bunch for the report! I can confirm the bug.
