### ISSUE TITLE
Dependency AngularFire2

### ISSUE THREAD

**Issue by pacozevallos** [stackblitz/core#189]
Is there a problem with Angularfire2? I do not recognize dependency.
`import { AngularFireAuthModule } from 'angularfire2/auth';`

**Comment by EricSimons** [comment]
I just tried this myself and it seems to work 🤔 Can you link the project here that this isn't working in?

**Comment by enesyalcin** [comment]
@EricSimons I know you are probably very busy, would be awesome if you could have a look at the /auth issue :)

https://stackblitz.com/edit/angular-t1stmf

In hello.component.ts line 21 I get 

> Property 'auth' does not exist on type 'AngularFireAuthModule'.

I faced the same problem when I imported it to my app.module.ts. As i added it to NgModel imports it vanished and I got the right path.

> module "node_modules/angularfire2/auth/index"

**Comment by EricSimons** [comment]
@enesyalcin np! You're importing the wrong module — it should be `AngularFireAuth`, not `AngularFireAuthModule` :)

**Comment by EricSimons** [comment]
Here's a working example from another StackBlitz user: https://stackblitz.com/edit/ionic-angularfire-starter?file=pages%2Fauth%2Fauth.ts

**Comment by enesyalcin** [comment]
shame on me, thanks a lot.
