### ISSUE TITLE
Copy shortcut only works on MacOS

### ISSUE THREAD

**Issue by rayfoss** [stackblitz/core#1892]
### **Description of Bug**
Currently the copy from terminal shortcut is not mapped to the defacto standard Control + Shift + C keyboard shortcut, it's mapped to Command + C. This doesn't work on Windows as this will launch Microsoft Teams or Windows Clock. On ChromeOS there is no "Super" key. And on Linux the Super key is often missing, such as it is in the Ubiquitous IBM Model M or captured by the OS.

### **Steps to Reproduce**

1. Use ChromeOS, Windows or Linux
2. Try to copy text from the terminal without right clicking

### **Expected Behavior**
- `Control + Shift + C` should copy, like it does on Ubuntu, ChromeOS Crostini, SteamDeck, Terminator, Windows Terminal...
- On MacOS the default is shift-command-C not Command-C, as Command-C is often mapped to the interrupt signal SIGKILL on iTerm or Karabiner. Google Docs takes this approach, mapping Control + C to Command + C if you are using MacOS.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/876076/172957402-a62f308e-4a4d-4cad-a915-0143f5a8543b.png)
![e31b53767fad646fc635271d1192fe13](https://user-images.githubusercontent.com/876076/172959795-cf87cf59-eba4-446e-8ea4-300c2bcd3d46.jpg)
![iljisch-model-m-8a](https://user-images.githubusercontent.com/876076/172959965-b7f930a8-c421-40b4-8d8a-f7e83abb90d0.jpg)
![chromebook-2048px-7273](https://user-images.githubusercontent.com/876076/172959968-e12f32ed-c587-4947-a755-5bc918e5197c.jpg)

**Additional Context/Questions**
Alternative, copy on select is common on Linux and is possible on MacOS and ChromeOS Crostini default terminals. As such using Chrome/Firefox's Lenient Copy API may be a faster alternative. From experience it has to be triggered on a user input event, and there is deviation between browser vendors on which kinds of events are acceptable and on which input fields.

**Comment by SamVerschueren** [comment]
Hey @rayfoss, thanks for the feedback!

I guess this is only an issue for copy, right? Not for paste? Paste is just Ctrl + V?

**Comment by fvsch** [comment]
Hi @rayfoss, we're shipping a fix today to enable copy in the Terminal with `Ctrl + Shift + C` on Windows and Linux.

**Comment by sylwiavargas** [comment]
Also, I love the setup pics you've submitted to help anyone understand the issue better 💕 Appreciate it!

**Comment by rayfoss** [comment]
Confirmed fixed in ChromeOS, Linux (Firefox flatpak in Crostini) and Windows 11.

- Ad Astra
