### ISSUE TITLE
Bad link for StackBlitz in playground

### ISSUE THREAD

**Issue by devbens** [stackblitz/core#1896]
### **Description of Bug**
Bad link for  **Open in StackBlitz** in '[withastro/astro/tree/latest/examples/integrations-playground](https://github.com/withastro/astro/tree/latest/examples/integrations-playground)'

### **Steps to Reproduce**

1. Go to '[withastro/astro/tree/latest/examples/integrations-playground](https://github.com/withastro/astro/tree/latest/examples/integrations-playground)'
2. Click on '**Open in StackBlitz**'
3. You got error

### **Expected Behavior**
I got this error on StackBlitz
> Please make sure the folder path in the URL exists within the repo.

### **Screenshots**
[Error Screenshot](https://i.snipboard.io/noDuBg.jpg)

**Comment by fvsch** [comment]
Thanks for the report @Devbaze. This is an issue on Astro's side, but we can probably make a quick PR to fix it.
