### ISSUE TITLE
Support loading type declarations from lib/index.d.ts with `types: "lib/"` in package.json

### ISSUE THREAD

**Issue by rayfoss** [stackblitz/core#1898]
### **Description of Bug**
Types are not read if the types directory defined in package.json contains only an index.d.ts

https://stackblitz.com/edit/vitejs-vite-7b24qq?file=src%2Fmain.ts

### **Steps to Reproduce**

1. load a package that only defines types in lib/index.d.ts 

### **Expected Behavior**
load my types

### **Screenshots/Screencast**
Intellisense broken on StackBlitz:
![Screenshot (15)](https://user-images.githubusercontent.com/876076/174455649-77cde508-ebf2-4e44-beb9-8f3d628f4e19.png)

Here's that same thing running on CodeSandbox, with intellisense:
![Screenshot (18)](https://user-images.githubusercontent.com/876076/174460779-b2d30bb9-3039-40f8-98bf-6cad18df38f8.png)
https://codesandbox.io/s/shite-shat-m74coo?file=/client.ts

**Additional Context/Questions**
https://unpkg.com/browse/@feathersjs/feathers@5.0.0-pre.23/package.json
https://unpkg.com/browse/@feathersjs/feathers@5.0.0-pre.23/lib/

Similar issue: https://github.com/stackblitz/core/issues/1444

**Comment by SamVerschueren** [comment]
I looked at the issue and found the bug. Thanks for reporting 🙏 . I'll keep you posted once this is released on production.

**Comment by SamVerschueren** [comment]
This if fixed and deployed 🥂 .
