### ISSUE TITLE
Easy ways to significantly boost UI user-friendliness

### ISSUE THREAD

**Issue by RoxKilly** [stackblitz/core#190]
I am a huge fan of your application, but as my work grows it's also growing increasingly frustrating in one respect. Consider this chain of events:

1. I use Stakblitz to generate several demos used to answer questions on StackOverflow or do some other work that I don't want linked to my github account
2. I later log into Github on Stackblitz to work on my saved work projects.
3. Stackblitz automatically associate my github account with the demos from step 1
4. Over time this has the effect of drowning out my work projects, making them harder and harder amidst the demos.

When the demos are just for me this isn't a problem as I can delete them,  but when I need to keep them online because others are relying on them... 

Please consider offering any of the following:
1. The ability to unlink a project from the user account. This would return the project to its pre-linked state, rather than delete it.
2. The ability to add tags to projects and a filter so I can choose which tagged projects to see. This would allow a quick un-clutter operation. An alternative might be to add folders and allow projects to be placed in them. Then the project list would show a list of folders instead.
3. If both of the above are too much work, at a minimum allow sorting the projects by name, so that I can add different prefixes ("demo_", "work_" etc...) that would prevent my work projects from being lost amongst all those demos.

Thanks again for sharing this tech with us.

**Comment by EricSimons** [comment]
@RoxKilly so sorry about my delay here — past month has been crazy w/ the new tech we just released 😓 

Totally agree on all points here — we're doing a _major_ overhaul of the surrounding UI/func to the editor which are designed to solve these pain points. Would love to run them by you actually and hear your thoughts; are you in our [discord channel](https://discord.gg/stackblitz) by chance?

**Comment by mikegoodstadt** [comment]
See Feature: private, unlisted and categories #134 : In particular my link to the their [Discord feature-voting channel](https://discord.com/channels/364486390102097930/365955135773474816)...

**Comment by kc0tlh** [comment]
This has been resolved based on your 2nd suggestion @RoxKilly! More info in Github issue #120
