### ISSUE TITLE
Error "Failed to load SWC binary for linux/x64 " in every Nextjs project

### ISSUE THREAD

**Issue by vedantnn71** [stackblitz/core#1904]
### **Description of Bug**
There is an error `Failed to load SWC binary for linux/x64` in every nextjs project. See the below screenshot 

### **Steps to Reproduce**
![stackblitz com_edit_vitest-dev-vitest-ytdowh_file=__tests__%2FHome test tsx initialPath=__vitest__ (1)](https://user-images.githubusercontent.com/70624701/174724613-677f9d99-8e73-4b90-ab7f-286bf8519113.png)

1. Go to [this example nextjs repo](https://stackblitz.com/edit/vitest-dev-vitest-ytdowh) or create your own
2. Spin up the server
3. Click on terminal
5. See the error

### **Expected Behavior**
Run the server without any errors.

**Comment by adamconn** [comment]
I encountered the same problem when I was committing `package-lock.json` to my repo. When I stopped committing that file - and let the web container generate it - the SWC packages don't cause a problem.

**Comment by vedantnn71** [comment]
> I encountered the same problem when I was committing `package-lock.json` to my repo. When I stopped committing that file - and let the web container generate it - the SWC packages don't cause a problem.
Worked for me also, thanks!
