### ISSUE TITLE
Feature to update project dependencies

### ISSUE THREAD

**Issue by Chan4077** [stackblitz/core#191]
There's currently no possible way to update project dependencies other than manually typing the dependency again which probably checks for the latest version available.

**Comment by vinchauhan** [comment]
Yes must have been something like it is in Scrimba platform

**Comment by julianobrasil** [comment]
That would be a nice feature.

**Comment by Chan4077** [comment]
@julianobrasil This feature has been added a while back. To access the feature, click on the "Refresh" icon when hovering over the "Dependencies" panel. See the image below for more info:

![Refresh icon](https://user-images.githubusercontent.com/20047125/49338243-a03b3080-f66a-11e8-83f0-b0535748444c.jpg)
