### ISSUE TITLE
template-vue-ts error

### ISSUE THREAD

**Issue by MMmaXingXing** [stackblitz/core#1912]
<img width="669" alt="image" src="https://user-images.githubusercontent.com/25543909/177358385-073f8f2d-fab4-4f77-9a01-5e1d0de6e4b3.png">

maybe you can use this link: fork/github/vitejs/vite/tree/main/packages/create-vite/template-vue-ts

**Comment by HeyGarrison** [comment]
@MMmaXingXing it looks like this is working now!

Just as a cheat code as well you can do... https://vite.new/vue
