### ISSUE TITLE
Cannot create svelte project

### ISSUE THREAD

**Issue by yannickh2** [stackblitz/core#1915]
Hi there,

I am just clicking on create at the full stack tab on Svelte and getting this error 

`forkgithubsveltejskit-template-default
Something went wrong with this repository.
If you think this is a bug, please [file an issue](https://github.com/stackblitz/core/issues/new) in our repo!`

![image](https://user-images.githubusercontent.com/38760521/178837364-286d84ba-e729-4b81-aced-138ce7534237.png)

**Comment by 416d72** [comment]
This happened to me as well, I tried using different browsers, but still can't create a new svelte project!!

**Comment by amr3k** [comment]
This was fixed a while ago, @yannickh2 feel free to close this issue.
