### ISSUE TITLE
React Server Components w/ streaming are not working with Next.js 12

### ISSUE THREAD

**Issue by plondon** [stackblitz/core#1919]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
Interacting with pages built with React Server Components w/ streaming on Next.js 12 result in error:
```
TypeError: bindings.parse(...).then is not a function
```

### **Steps to Reproduce**

1. Go to https://stackblitz.com/github/vercel/next-react-server-components
2. Click on "RSC + HTTP Streaming"

### **Expected Behavior**
Here is the same repo in codesandbox https://codesandbox.io/s/goofy-shape-u8od6h

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by EricSimons** [comment]
@plondon this appears to unfortunately be a bug in Next.js itself where they are trying to load a native version of SWC instead of the WASM variant. Can you post this over in their repo and link back here? I've also sent this issue to their team so they can debug further
