### ISSUE TITLE
Bootstrap 4.0.0-beta.2 scss parsing error

### ISSUE THREAD

**Issue by Alucardz** [stackblitz/core#193]
Hi @EricSimons,

When using the mentioned bootstrap version, stackblitz gives the following error:

`Error: Invalid CSS after "...ript inside `#{": expected expression (e.g. 1px, bold), was "}`.*/"
        on line 2 of sass/bootstrap/scss/_root.scss
>>   /* Custom variable values only support SassScript inside `#{}`.*/
   --^
`

in reference to this file: https://unpkg.com/bootstrap@4.0.0-beta.2/scss/_root.scss

example repo: https://angular-coreui.stackblitz.io

**Comment by apai4** [comment]
@Alucardz I just pushed a fix for this, your project looks like it's working now. Lmk if you run into any more issues!

**Comment by Alucardz** [comment]
@apai4 works like a charm now, thanks!
