### ISSUE TITLE
Preview page is always blank

### ISSUE THREAD

**Issue by guilhermedeandrade** [stackblitz/core#1934]
I've tried multiple templates but the preview page renders nothing. I'm using Brave [Version 1.41.100 Chromium: 103.0.5060.134 (Official Build) (64-bit)](https://brave.com/latest/) on a W11 machine. 

However, this also happed on my M1 Air accessing, which was using the same browser and internet connection.

![image](https://user-images.githubusercontent.com/8797405/180896617-c35145c6-0b65-4e17-832e-edbbe1cfc740.png)

**Comment by guilhermedeandrade** [comment]
Nevermind, this was actually a "protection" from Browser and an easy fix. Sorry!

![image](https://user-images.githubusercontent.com/8797405/180897219-2346b643-ffc7-4aa6-b9ae-1b179220fef5.png)

**Comment by donmckenna** [comment]
We also have a page documenting the how and why of Brave Shields + StackBlitz if it helps you or anyone else :) 
https://developer.stackblitz.com/docs/platform/brave-support/

**Comment by guilhermedeandrade** [comment]
> We also have a page documenting the how and why of Brave Shields + StackBlitz if it helps you or anyone else :) [developer.stackblitz.com/docs/platform/brave-support](https://developer.stackblitz.com/docs/platform/brave-support/)

Thanks!
