### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by codexguajil** [stackblitz/core#1937]
Page went blank and doesn't change upon reload.

**Comment by m93a** [comment]
Trying to open an [RxJS example](https://rxjs.dev/guide/observable) in StackBlitz, I get a blank screen and these errors in the console:
[stackblitz.com-1659369117028.log](https://github.com/stackblitz/core/files/9235288/stackblitz.com-1659369117028.log)

All requests to https://c.staticblitz.com/assets/ fail for some reason, even though opening the same adress in a new tab loads the css / javascript just fine.

I'm using Brave 1.41.96 based on Chromium: 103.0.5060.114 with all shields turned off for stackblitz.com

**Comment by kc0tlh** [comment]
As of February 2023 this should be resolved. You can read more about our [browser support here](https://developer.stackblitz.com/platform/webcontainers/browser-support).
