### ISSUE TITLE
Optional Peer Dependencies are required.

### ISSUE THREAD

**Issue by MadeStoel** [stackblitz/core#1941]
When installing a package, optional peer dependencies cannot be denied for installation.

`{
"peerDependencies": {
    "react": "^16.8.0",
    "vue": "^3.0.0"
  },
  "peerDependenciesMeta": {
    "vue": {
      "optional": true
    },
    "react": {
      "optional": true
    }
}`

**Comment by macbem** [comment]
I've encountered this as well. This completely blocks any attempt to use the `jotai` package (React state management) on Stackblitz.
