### ISSUE TITLE
Unable to load project

### ISSUE THREAD

**Issue by johnrbaur** [stackblitz/core#1952]
### **Description of Bug**
The following message is displayed when trying to open https://stackblitz.com/edit/vitejs-vite-evjhwk:

"Yikes! Something went wrong with your request.
If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core"

All other projects seem to work.

**Comment by skryukov** [comment]
Hey, @johnrbaur, thanks for the issue! The project should work now ❤️

**Comment by johnrbaur** [comment]
Working now - thanks!
