### ISSUE TITLE
Vue3.2 setup语法糖

### ISSUE THREAD

**Issue by checkwoodson** [stackblitz/core#1953]
当我使用setup语法糖的时候，报无效的script， vue3.2的版本 为啥不能用

**Comment by kc0tlh** [comment]
@checkwoodson Vue 3.2 appears to be functioning normally. You can get a clean starter project here:
https://stackblitz.com/fork/vue 

Best of luck with your project.

**Comment by checkwoodson** [comment]
#  I mean: use setup on script
![image](https://user-images.githubusercontent.com/33786022/186093390-8deade34-b37b-48fd-979b-d1596a65759e.png)
```js
<script setup></script>
```
这个样子的~
