### ISSUE TITLE
Can't find package, but works fine when downloading the project

### ISSUE THREAD

**Issue by H3AR7B3A7** [stackblitz/core#1954]
I created a project that depends on a package that I published to npmjs, here:

https://stackblitz.com/edit/angular-ivy-mxj7mi?file=src%2Fapp%2Fapp.component.html

When I run the project in the browser, I keep getting this error:

Can't find package: @h3ar7b3a7/spin-anything

However, when I download the project and serve it locally everything works just fine.
Is this a bug, or how can I fix this please?

**Comment by fvsch** [comment]
Could it be because the `"main"` field in this package's `package.json` points to a file that doesn't exist?

See https://unpkg.com/browse/@h3ar7b3a7/spin-anything@0.0.25/package.json

```jsonc
{
  "name": "@h3ar7b3a7/spin-anything",
  "version": "0.0.25",
  "description": "Spin text, images or anything else easily.",
  "main": "karma.conf.js",
  "author": "h3ar7b3a7",
  "license": "ISC",
  // …
}
```

**Comment by H3AR7B3A7** [comment]
That was indeed the issue, it was my mistake. So this wasn't a bug.
Thank you very much for looking into it.
