### ISSUE TITLE
The Horizontal and Vertical scroll bars of grid in pagination are not realigning to original position.

### ISSUE THREAD

**Issue by chandrasekharjakkula** [stackblitz/core#1959]
The scroll Bars are not realigning to its original position when we move to next page in the grid data.
Before going to next Page:-
![image](https://user-images.githubusercontent.com/106232411/183390860-50afcee6-e0c6-489c-a7cb-c1c43ea7eace.png)

After going to Next Page:- 
![image](https://user-images.githubusercontent.com/106232411/183391320-c3b934c7-5601-4c9c-a129-76039ef53112.png)

Tried to realign using the onChange Event by using the scrollTo . Then  we were able to realign the horizontal scrollbar But the vertical scrollbar is not realigned.

**Comment by fvsch** [comment]
Hi @chandrasekharjakkula.

It looks like this is a bug report for a specific frontend library (a table or pagination library maybe?), which you were maybe trying out in StackBlitz? In that case, this bug report should be filed with that specific library or project, and not on `stackblitz/core`.
