### ISSUE TITLE
Error occurred: Cannot access 'it' before initialization

### ISSUE THREAD

**Issue by aarnadlr** [stackblitz/core#1961]
When I spin up a new Vanilla HTML/CSS/JS workspace, I am suddenly getting "Error occurred: Cannot access 'it' before initialization" error rendered in the window.

**Comment by christian-valadez** [comment]
+1 - getting this too

**Comment by apai4** [comment]
This for reporting this! This was caused by a recent release, the change has been reverted and the Vanilla HTML/CSS/JS projects are working again.
