### ISSUE TITLE
Realm.App is not a constructor - cannot use the 'realm-web' dependency (Angular template)

### ISSUE THREAD

**Issue by sis0k0** [stackblitz/core#1968]
### **Description of Bug**

Cannot use the external dependency [realm-web](https://www.npmjs.com/package/realm-web) within the Angular template.  

### **Repro Project**

https://stackblitz.com/edit/angular-balnpm?file=src%2Fapp%2Fapp.component.ts

### **Steps to Reproduce**

1. Create a new project using the Angular template
1. Add the 'realm-web' dependency
1. Replace the `app.component.ts` with:

```
import { Component } from '@angular/core';
import * as Realm from 'realm-web';

@Component({
  selector: 'my-app',
  styleUrls: ['./app.component.css'],
  template: `
    App Users:
    {{ app.users | json }}
  `,
})
export class AppComponent {
  app: any;

  constructor() {
    console.log(Realm);
    this.app = new Realm.App('');
    console.log(this.app);
  }
}
```

### **Expected Behavior**
Invoking `Realm.App` with `new` should instantiate an object. It looks like the imported `Realm` object is empty (check the logs in console).

**Comment by markwhitfeld** [comment]
Thank you for the issue report and reproduction. A fix is on its way!

**Comment by markwhitfeld** [comment]
We have deployed a fix that should resolve this issue. Your repro is now working 👍
