### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Dinudash** [stackblitz/core#1969]
HttpErrorResponse {headers: {…}, status: 0, statusText: "Unknown Error", url: "https://dummyjson.com/products"…}
error: ProgressEvent
headers: HttpHeaders
message: "Http failure response for https://dummyjson.com/products: 0 Unknown Error"
name: "HttpErrorResponse"
ok: false
status: 0
statusText: "Unknown Error"
url: "https://dummyjson.com/products"
__proto__: HttpErrorResponse

**Comment by fvsch** [comment]
Hi @Dinudash. We’ll need more information about this issue, in particular:

- What you are trying to do
- What is failing (and in which browser(s))
- A link to a StackBlitz project that shows your issue

Without this information, there is nothing we can do to help.

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information.
