### ISSUE TITLE
Is the Angular AoT compiler supported?

### ISSUE THREAD

**Issue by voithos** [stackblitz/core#197]
Specifically, in `main.ts`, I'd like to use `platformBrowser().bootstrapModuleFactory(AppModuleNgFactory)` instead of `platformBrowserDynamic().bootstrapModule(AppModule)`.

**Comment by EricSimons** [comment]
Sorry about the delay on this! We're working on it now actually- will report back once it's online in a week or so :)

**Comment by voithos** [comment]
Great to hear! :)

**Comment by darthmolen** [comment]
Any updates on this?

**Comment by bob-lee** [comment]
Have some issue on Angular animation which seems to occur only on production build. Would be great if aot is possible on Stackblitz.. @EricSimons can you update please?

**Comment by ThomasBurleson** [comment]
+1 for this feature.

**Comment by dicbrus** [comment]
+1

**Comment by ninopetrovic** [comment]
Are we any closer to AoT support? It's been 2 and a half years.

**Comment by EricSimons** [comment]
This is already shipped on prod. If you start a new angular project from the homepage it by default uses the AoT Ivy compiler.

**Comment by EricSimons** [comment]
Direct link here: https://stackblitz.com/fork/angular-ivy

**Comment by ninopetrovic** [comment]
Oh. The issue wasn't closed so I did not know that. Thanks.
