### ISSUE TITLE
Add option to allow cross-domain iframe access

### ISSUE THREAD

**Issue by Manuel-Suarez-Abascal** [stackblitz/core#1979]
### **Is your feature request related to a problem? Please describe.**

I have embedded the StackBlitz SDK in my React app's frontend. I'm trying to access an HTML element inside the iframe. However, when I try to access the HTML element, I get the following error: `Uncaught DOMException: Blocked a frame with origin "http://localhost:3000" from accessing a cross-origin frame.`

### **Describe the solution you'd like**

Can you add an option to remove the `cross-domain` error? I know this is Chrome security & it's not related to stackblitz. But it would be nice to have the option to "trust" this iframe's source.

### **Describe alternatives you've considered**
- Serving the content through my local server.
- Disabling Chrome web security or finding a browser that allows cross-domain

**Comment by fvsch** [comment]
Hello @Manuel-Suarez-Abascal,

Even if we wanted to allow cross-domain access to the StakBlitz editor (embedded in an iframe), I don't think we'd have a way to do that. Browsers disallow it, and there is no opt-in "please disregard this important security measure".

But also: we definitely do not want to do that, it would be a huge security flaw enabling cross-site scripting attacks, and would endanger our user's data.

Could you describe what the result you’re trying to achieve looks like? Maybe we can accommodate this use case in a safer way.

**Comment by Manuel-Suarez-Abascal** [comment]
Long story short, I embedded the `iframe` in my own React application & now I want to access the `iframe` HTML elements, but I can't due to `cross-domain` errors. I wrote a Stackoverflow question [here](https://stackoverflow.com/questions/73358687/stackblitz-blocked-a-frame-with-origin-http-localhost3000-from-accessing-a?noredirect=1#comment129551712_73358687) for better context. What are your thoughts?

**Comment by fvsch** [comment]
@Manuel-Suarez-Abascal I don't think we can help much here.

It looks like you are trying to access the preview document, which is two levels deep. Even if you could access the embedded project in the top-level iframe (which again would be a huge XSS problem), you would then have to access the preview iframe in _that_ document, which hosts a preview window on yet another origin.

We only have very limited postMessage-based communication between the editor document and the preview document, mostly for handling page refreshes, and we don't have plans for executing code in the preview document from the SDK (two levels up) at this time.
