### ISSUE TITLE
[feature] Stylus CSS preprocessor support

### ISSUE THREAD

**Issue by oktav777** [stackblitz/core#198]
Any plans to support Stylus?

**Comment by fvsch** [comment]
We do not have plans to support Stylus at this time (and it looks like Stylus [might be discontinued](https://github.com/stylus/stylus/issues/2575)?).

But if you have projects using Node.js and Stylus, you might be able to run it using our beta technology, WebContainers:
https://blog.stackblitz.com/posts/introducing-webcontainers/
