### ISSUE TITLE
Add "duplicate line" shortcut

### ISSUE THREAD

**Issue by JesusTheHun** [stackblitz/core#1981]
I often use stackblitz to create issue repro, for that I use dumb data which means I c/p a lot, and duplicating line is a nice to have.
Obviously this is a top priority request and I will need you to work this week-end to ship it asap 😄

**Comment by fvsch** [comment]
Hi @JesusTheHun,

So it looks like we support the same keyboard shortcut as VS Code for this.

In my tests in macOS, Shift+Alt+ArrowUp or Shift+Alt+ArrowDown duplicates the line (before r after).

Another method is to use the copy and paste shortcuts (Control+C and Control+V, or Command+C and Command+V on macOS) without selecting text, just placing the editor cursor inside the line you want to duplicate. That works as well to duplicate a line, but it will add the contents of that line to your clipboard.

Between those two methods, I think this feature request is already covered. Feel free to re-open if I missed something!

**Comment by JesusTheHun** [comment]
Hi @fvsch , I looked at the [doc](https://developer.stackblitz.com/docs/platform/keyboard-shortcuts/) and didn't find it ! Good to know it exists 👍

**Comment by fvsch** [comment]
I think it's documented as "Copy line down/up" in that documentation page.
