### ISSUE TITLE
Provide standard height readme badge SVG

### ISSUE THREAD

**Issue by janosh** [stackblitz/core#1988]
The Open in [StackBlitz badge](https://developer.stackblitz.com/docs/guide/open-from-github/#the-open-in-stackblitz-button) is too tall. Inlining it with other badges looks bad:

![Screen Shot 2022-08-17 at 11 34 02](https://user-images.githubusercontent.com/30958850/185216811-3f877214-9454-4c80-bc0d-9d9cac2afb9b.png)

Would be nice if StackBlitz could offer a 2nd SVG that conforms to the height of other badges.

The closest thing looking like a StackBlitz badge I was able to get from shields.io currently misuses the Pytorch Lightning logo:

```md
[![Open in StackBlitz](https://img.shields.io/badge/Open%20in-StackBlitz-darkblue?logo=pytorchlightning)](https://stackblitz.com/github/janosh/periodic-table)
```

[![Open in StackBlitz](https://img.shields.io/badge/Open%20in-StackBlitz-darkblue?logo=pytorchlightning)](https://stackblitz.com/github/janosh/periodic-table)
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/github/janosh/periodic-table)

Related: shields.io uses [simple icons](https://github.com/simple-icons/simple-icons) as its icon source. I submitted an issue to add the StackBlitz icon to their collection at https://github.com/simple-icons/simple-icons/issues/7681. I assume there are no objections to being listed there?

**Comment by donmckenna** [comment]
Thanks for bringing this up. We'll be updating this soon 👍

**Comment by donmckenna** [comment]
We've now added a smaller badge to the docs.
https://developer.stackblitz.com/docs/guide/open-from-github/#the-open-in-stackblitz-button

<img width="471" alt="Screen Shot 2022-08-19 at 3 17 53 PM" src="https://user-images.githubusercontent.com/22125230/185708516-b0bd0d77-95f4-4a3c-bdd4-8cdb618e836a.png">

Closing this issue. Thanks for the feedback!

**Comment by janosh** [comment]
Thank you very much! Is there any interest in submitting the StackBlitz logo to `simple-icons` to close https://github.com/simple-icons/simple-icons/issues/7681?

**Comment by LitoMore** [comment]
> Thank you very much! Is there any interest in submitting the StackBlitz logo to simple-icons to close https://github.com/simple-icons/simple-icons/issues/7681?

Working in progress now: https://github.com/stackblitz/core/issues/1988

You may need to wait for the simple-icons to release this change, then wait for the shields.io to apply this change.

**Comment by LitoMore** [comment]
It's available now!

Here are some examples:

![](https://shields.io/badge/Open_in_StackBlitz-1269D3?logo=stackblitz)
![](https://shields.io/badge/Open_in_StackBlitz-1269D3?logo=stackblitz&labelColor=555)
![](https://shields.io/badge/Open_in-StackBlitz-1269D3?logo=stackblitz)
![](https://shields.io/badge/StackBlitz-Try_It-1269D3?logo=stackblitz)
![](https://shields.io/badge/StackBlitz-Try_It-eee?logo=stackblitz&labelColor=1269D3)

```markdown
![](https://shields.io/badge/Open_in_StackBlitz-1269D3?logo=stackblitz)
![](https://shields.io/badge/Open_in_StackBlitz-1269D3?logo=stackblitz&labelColor=555)
![](https://shields.io/badge/Open_in-StackBlitz-1269D3?logo=stackblitz)
![](https://shields.io/badge/StackBlitz-Try_It-1269D3?logo=stackblitz)
![](https://shields.io/badge/StackBlitz-Try_It-eee?logo=stackblitz&labelColor=1269D3)
```

**Comment by janosh** [comment]
I saw it yesterday. 👍 

Been using it on [`svelte-multiselect`](https://github.com/janosh/svelte-multiselect), [`svelte-toc`](https://github.com/janosh/svelte-toc) and others. 😄
