### ISSUE TITLE
Collapsible methods

### ISSUE THREAD

**Issue by Znow** [stackblitz/core#199]
Hi,

Awesome editor, really great job!

Would be nice with collapsible methods in the editor, as in original VS Code.

Regards

**Comment by sulco** [comment]
Hi @Znow, thanks for posting this!

We now have collapsible code blocks - hover over left margin with mouse to see the icon that enables you to do it :) 
![image](https://user-images.githubusercontent.com/1511906/106156958-74506280-6182-11eb-9c21-7be0936a304f.png)
