### ISSUE TITLE
Console is not loading even after the project compilation is successful

### ISSUE THREAD

**Issue by nsridatta** [stackblitz/core#1995]
Console is not loading even after the project compilation is successful

**Comment by kc0tlh** [comment]
The console is available in Engineblock projects, whereas the new WebContainer projects have a terminal. Of course in most browsers, you can always access the console via the browser Dev Tools, regardless of what type of StackBlitz project you are using. More details on our various environments [can be found here](https://developer.stackblitz.com/guides/user-guide/available-environments).

**Comment by Totati** [comment]
Calling `console.log` does not log to terminal, hovever acessing dev tools is not available on mobile browsers, and even on desktop browsers it requires opening dev tools and it takes up way more space than the intgrated console does. This is a loose-loose situation.
