### ISSUE TITLE
Not Saved

### ISSUE THREAD

**Issue by djsport4** [stackblitz/core#1998]
worked on project for 4 hours only to find that none of the changes were saved :-(

**Comment by HeyGarrison** [comment]
@djsport4 do you happen to have a link to the project or reproduction steps?

**Comment by djsport4** [comment]
Yes thank you for your help....

stackblitz/edit/react-x4nkcl

or

https://stackblitz.com/edit/react-x4nkcl?file=src%2FApp.js
[https://social-img.staticblitz.com/projects/react-x4nkcl/d0d4cfd18417d3e298409fc20b855fc5]<https://stackblitz.com/edit/react-x4nkcl?file=src%2FApp.js>
React BlackJack - StackBlitz<https://stackblitz.com/edit/react-x4nkcl?file=src%2FApp.js>
A create-react-app project based on react and react-dom.
stackblitz.com

but it seems that none of my projects are updated permanently anymore

Thanks,
Don

________________________________

**Comment by djsport4** [comment]
seems to work now though...

________________________________
