### ISSUE TITLE
Export does not include all source files

### ISSUE THREAD

**Issue by cramhead** [stackblitz/core#2]
When I press export the source files are missing. The zip includes index.html, package.json and README.md. To reproduce go to the balldemo and press export.

**Comment by EricSimons** [comment]
Hmm I just tried exporting the ball demo and it seemed to work fine — is anyone else running into this issue?

**Comment by cramhead** [comment]
That's totally odd. I'm using the url https://stackblitz.com/edit/ball-demo. I'm logged in with my github creds. When I tried again, I had the same result.

**Comment by CristhianUNSa** [comment]
@cramhead Try unzipping files. When zipped I see those files too. After unzip I can see .ts files (Windows 10)

**Comment by cramhead** [comment]
This is what I see when I extract
![capture](https://user-images.githubusercontent.com/386035/28940629-37503a06-784a-11e7-86c0-344f3786a394.JPG)

**Comment by cannap** [comment]
i found something i tried export and opened with winrar

https://i.gyazo.com/78767b5d3e90c084e0e43bd9cfbb4d4a.png

**Comment by EricSimons** [comment]
@cannap excellent find. I'm going to dig into the export code and see where this might be happening!

**Comment by EricSimons** [comment]
@cramhead does export work properly for you on the default [Angular](https://stackblitz.com/edit/angular) and [React](https://stackblitz.com/edit/react) projects?

**Comment by cannap** [comment]
i know you did not ask me but they looks fine for me

**Comment by cramhead** [comment]
I think I've discovered something of relevance. 
When I export the projects via the url https://stackblitz.com/edit/angular, and similar, it exports correctly. Including all the files. When I export the balldemo, it does *not* include all the files.

![capture](https://user-images.githubusercontent.com/386035/28997263-5a00c29c-79c5-11e7-83db-a84b36191fc5.JPG). The files exported from the /edit/framework urls.

**Comment by StandishMan25** [comment]
I am encountering the same behavior on TypeScript projects (only one's I've played in). 
https://stackblitz.com/edit/typescript-ag-grid-vue

**Comment by airarrazaval** [comment]
@cannap I can confirm that all folders and files (aside from index.html, package.json and package-lock.json) in a project have a back slash prefix (they are named as absolute path).  Extracting all files automatically (selecting extract all) strips absolute path spec and make all files and directories visible. If you open the zip file manually you will not be able to see all files.

**Comment by EricSimons** [comment]
I think we fixed this one a while back, but feel free to reopen otherwise 👍
