### ISSUE TITLE
Support "Vim Mode"

### ISSUE THREAD

**Issue by flipjs** [stackblitz/core#20]
An editor settings would be nice, and have an option to set vim-mode. I know most code playgrounds such as jsbin, codepen, etc. have this option. Thanks!

**Comment by tgoyer** [comment]
In addition, .editorconfig support would be amazing.

**Comment by EricSimons** [comment]
We'd love to have Vim actually; biggest blocker is that no one has created a Vim extension for Monaco yet: https://github.com/Microsoft/monaco-editor/issues/182

Tbh I don't think we'll have time to personally implement Vim ourselves, but if someone else creates a Monaco Vim extension we will absolutely implement it!

Regarding .editorconfig — I LOVE this idea. Definitely putting on the roadmap 👍

**Comment by andregomars** [comment]
need it, seriously!

**Comment by bennypowers** [comment]
https://github.com/brijeshb42/monaco-vim

**Comment by irek02** [comment]
@EricSimons , any plans to incorporate monaco-vim from @bennypowers ?

**Comment by jpstone** [comment]
@EricSimons any plans for the above?

**Comment by fuzzthink** [comment]
@EricSimons It's almost a year since bennypowers added the extension. Please add?

**Comment by comc49** [comment]
Vim would be great 👍

**Comment by richarddevers** [comment]
+1

**Comment by lozandier** [comment]
Any update on this?

**Comment by comc49** [comment]
Please!! This would be so awesome

**Comment by ashnur** [comment]
Who we have to convince for this to happen?

**Comment by diffractometer** [comment]
+1 I would love this feature but probably too lazy to do it

**Comment by yanghu** [comment]
+1

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by josepot** [comment]
@purplem1lk  congratulations on the launch of the new editor! Truly mind-blowing, I'm super impressed! However, I can't find a way to setup "vim mode", could you please let us know how to set it up with the new editor? :pray:

**Comment by ashnur** [comment]
Maybe it's a paid feature? I was unable to locate it as well.

**Comment by SamVerschueren** [comment]
Here an update from the StackBlitz side ⚡ . This issue was closed by mistake. No harm done I hope :).

I saw @bennypowers suggesting `monaco-vim` and I forwarded it internally as it looks pretty promising.

**Comment by luisherranz** [comment]
Do you plan to support [3rd party VS Code extensions](https://github.com/stackblitz/core/issues/3#issuecomment-830316016)? If so, then I guess people should be able to use things like https://github.com/VSCodeVim/Vim, shouldn't they?

**Comment by qoobes** [comment]
Any updates on vim mode? 
It's a make or break feature for a lot of developers, so it'd be great for this to get added!

**Comment by jugarpeupv** [comment]
Any updates on vim mode? Once you know vim, coding without it, is just horrible xD

**Comment by kennethcassel** [comment]
another +1 for vim mode please :)

**Comment by elijahrdorman** [comment]
Let me add another vote to this too. I prefer to do things quickly with the keyboard.

**Comment by tatupesonen** [comment]
Yes please! This would be a gamechanger.

**Comment by marr** [comment]
bump

**Comment by DKavaliou-by** [comment]
+1

**Comment by jankergg** [comment]
I realy enjoy the performance that StackBlitz offers,  but I have to use codesandbox instead, because of the absence of `VIM 
 mode`

**Comment by Deerhound579** [comment]
Really impressed by the awesome performance. I use https://github.com/VSCodeVim/Vim every day, and it's great. Is there anything we can help to make this happen?

**Comment by Hoofoo-WHU** [comment]
+1

**Comment by ashnur** [comment]
Probably nothing will happen until monaco will support it. https://github.com/microsoft/monaco-editor/issues/182

**Comment by tatupesonen** [comment]
> Probably nothing will happen until monaco will support it. [microsoft/monaco-editor#182](https://github.com/microsoft/monaco-editor/issues/182)

Already exists 
https://github.com/brijeshb42/monaco-vim

**Comment by lkj4** [comment]
checking this thread every other month and _still_ no vim mode?! 🙄

**Comment by ashnur** [comment]
Every other year* now.

**Comment by jeremytchang** [comment]
+1 
This issue is 5 years old now. :D

**Comment by ashnur** [comment]
> This issue is 5 years old now. :D
at this point I am rooting it to grow up so it can drive a car, maybe even drink alcohol

**Comment by rayfoss** [comment]
There is are options that might work for some people.

1. local projects (very very alpha)
2. Edit the code in vscode.dev, commit it then load it on SB for actual running.
![Screenshot 2022-07-02 12 26 09](https://user-images.githubusercontent.com/876076/177010764-fdb6c07b-c631-4c15-a5bf-19453dcd0b52.png)
3. There are chrome and firefox extensions for vite editor shortcuts... which should work on the IDE part, but not the terminal.

**I'm glad to see so many people treat StackBlitz as a serious IDE...** I wish this was the norm.

**Comment by CarpentersKeys** [comment]
+1

**Comment by subfuzion** [comment]
I think StackBlitz really hits the sweet spot in so many area, but truly, not having vim support holds me back from true ❤️. It's the one thing that disappoints me with our own Cloud Shell Editor, but at least I can use vim in the terminal, which is not an option with StackBlitz. I really want to use StackBlitz for edstem.org course I'm developing, but I spend the beginning of the course introducing vim as part of the toolkit, so I don't then want to send students to an online environment that doesn't support it.

It does look like VIM keybindings for Monaco were created by @brijeshb42 a while back. Any chance of leveraging this work?
* repo: https://github.com/brijeshb42/monaco-vim
* demo: https://editor.bitwiser.in/

@EricSimons, I don't intend for this to come across as being flippant, but perhaps migrating to CodeMirror 6, like the folks at replit (@masad-frost: [Ace, CodeMirror, and Monaco: A Comparison of the Code Editors You Use in the Browser](https://blog.replit.com/code-editors)), might be worthwhile (and not just for [vim support](https://codemirror.net/5/doc/manual.html#vimapi))?

**Comment by lkj4** [comment]
> VIM keybindings for Monaco were created by @brijeshb42

yeah, there are avail forever, i guess they have other priorities and/or no vim users

**Comment by roskee** [comment]
Tried stackblitz for the first time today. Not for me without vim!

**Comment by MarsOrBust24** [comment]
Not sure if anyone has thought of this... but turning webcontainers into a VSCode extension, with support for vscode.dev... would make a lot of people happy.

We containers could manifest as a virtual OS with /home/ containing all your stackblitz projects. upon access they would hydrate. 

The result is being able to use your stackblitz account as a Saas with any VSCode extensions and being able to code Node projects without Filesystem access or OS dependencies. It wouldn't matter if VSCode is running on the web or if it's the Snap version, or if you don't have admin privileges, it could just work.

**Comment by GGORG0** [comment]
Any updates on this?

**Comment by samdenty** [comment]
This is supported out the box in Stackblitz CodeFlow https://stackblitz.com/codeflow

**Comment by javaroc** [comment]
Nearing up on this issue's 6th birthday! :partying_face: :cake:

**Comment by devloos** [comment]
Dang would really love this!

**Comment by subfuzion** [comment]
Thanks to @samdenty for pointing out this works in Stackblitz CodeFlow: https://stackblitz.com/codeflow ... just add the vim extension! So far I'm liking what I see! :)

**Comment by nasso** [comment]
why is this still open? i just installed `vscodevim.vim` in Stackblitz and it just works!

**Comment by ashnur** [comment]
@nasso can you please provide a link to the documentation of the extensions. The gif is useful, but not as useful perhaps as clear instructions to the solution would be ;)

**Comment by nasso** [comment]
you mean, https://marketplace.visualstudio.com/items?itemName=vscodevim.vim ? it's just a single, regular VS Code extension, that i installed using the regular extension browser in Stackblitz

**Comment by ashnur** [comment]
And where can I find this "regular extension browser in Stackblitz"? :D I am sure you are not talking about some paid feature or the beta github codeflow integration, right?

**Comment by nasso** [comment]
oh damn it looks like i was using the beta github codeflow integration without knowing it...?

all i did was open a repository, i had no idea stackblitz had a separate editor JUST for github repositories... 😶

**Comment by samdenty** [comment]
Closed the issue as suggested by @nasso, vim & vscode extensions are supported out the box in Stackblitz CodeFlow https://stackblitz.com/codeflow.

This is the new editor experience that we're working on. We actively working on enabling stackblitz projects to be opened in the new editor.

**Comment by ashnur** [comment]
Closing this without actual support is a bit of fake news.

**Comment by ctretyak** [comment]
Why is it closed? You are not agreed that stackblitz vanilla needs this feature, and it won't be implemented ever?
