### ISSUE TITLE
Firefox, frontend static template not working

### ISSUE THREAD

**Issue by filipw01** [stackblitz/core#2000]
After opening the frontend static template it's displaying the following error in Firefox 103. It works correctly in chrome
```
Error occurred:
Error: ENOENT: No such file or directory., '/~'
```
Link to example https://stackblitz.com/edit/web-platform-3pf78s?file=index.html

**Comment by filipw01** [comment]
What a round issue number 😄

**Comment by alexhampu** [comment]
The same thing happens to me on a new Web Platform fork on Firefox 103.0.2

**Comment by andsheterliak** [comment]
Duplicate of #1679

**Comment by fvsch** [comment]
Closing as a duplicate of #1679.
