### ISSUE TITLE
Support option to hide the "edit on StackBlitz" link

### ISSUE THREAD

**Issue by kagklis** [stackblitz/core#2002]
### **Is your feature request related to a problem? Please describe.**
I have embedded a StackBlitz demo in a blog post. Every StackBlitz has an "edit on StackBlitz" link, which opens a new tab on StackBlitz. But I want readers to stay on the blog post page and not "guide" them elsewhere in any way.

### **Describe the solution you'd like**
Have an option to hide the "edit on StackBlitz" link in the Emded tab like the existing options, such as "Click to load", "Hide the preview URL", etc.

**Comment by donmckenna** [comment]
We're looking at adding this functionality to a future paid version of the product, but unfortunately isn't something we currently offer.
Thanks for the feedback! This is on our radar.
