### ISSUE TITLE
"Yikes! The page you requested couldn't be found" after Collection renamed

### ISSUE THREAD

**Issue by rsorrt** [stackblitz/core#2005]
### **Description of Bug**
After renamed a Collection I can't open it anymore: "Yikes! The page you requested couldn't be found"

### **Steps to Reproduce**

1. Go to my 'Dashboard'
2. Click on the Collection named 'React EXERCISES'
3. See error: "Yikes! The page you requested couldn't be found"

I noticed the url is "https://stackblitz.com/@rsorrt/collections/exercises"
but the "slug" is "exercises ",  there's  a final space !!!!

So if i change url in 
     https://stackblitz.com/@rsorrt/collections/exercises%20
it becomes reachable !!!

The problem is the final space in slug name, could you plz delete it ?

thanks
bye

**Comment by rsorrt** [comment]
I solved mySelf...

Inspecting the HTML of Collection's Delete-Button I saw:

<a href="https://stackblitz.com/@rsorrt/collections/exercises" data-method="DELETE" data-confirm="Are you sure you want to delete the &quot;React EXERCISES&quot; collection? This can't be undone.

Note: Projects inside of the collection will not be removed." class="Menu-module-button-xEMJr Menu-module-button_negative-x_29A"><svg width="1em" height="1em" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg" class="vscode-icon"><path fill-rule="evenodd" clip-rule="evenodd" d="M10 3h3v1h-1v9l-1 1H4l-1-1V4H2V3h3V2a1 1 0 011-1h3a1 1 0 011 1v1zM9 2H6v1h3V2zM4 13h7V4H4v9zm2-8H5v7h1V5zm1 0h1v7H7V5zm2 0h1v7H9V5z" fill="#C5C5C5"></path></svg>Delete</a>


so I changed the url adding a %20: 
<a href="https://stackblitz.com/@rsorrt/collections/exercises%20"
and the Collection disappered !!!!

You have a problem with final space in slug names.

byee

**Comment by kc0tlh** [comment]
Similar, but different collections naming/slug issue: #2161. Commenting to link for future review!

**Comment by kc0tlh** [comment]
Eng team confirmed these projects can be deleted now! Closing the issue.
