### ISSUE TITLE
intelli sense not working properly?

### ISSUE THREAD

**Issue by seekheart** [stackblitz/core#201]
I'm doing some typescript stuff and I noticed lately the intelli sense isn't detecting my imports of custom classes nor the private setter/getter methods correctly.

snippet: https://stackblitz.com/edit/class-example

**Comment by apai4** [comment]
Looks like in `app/car.ts` https://stackblitz.com/edit/class-example?file=app%2Fcar.ts you should be importing from `./color` on the first line instead of `./car`

**Comment by seekheart** [comment]
I made some changes but now in hello.component.ts intelli sense is buggin out.

**Comment by apai4** [comment]
Looks like it's working for me, I see red underlines but those are things you need to fix in your code, you're passing a single object into your constructors when you specified multiple arguments for them.
