### ISSUE TITLE
Support Install scripts

### ISSUE THREAD

**Issue by sayantan300** [stackblitz/core#2011]
### **Is your feature request related to a problem? Please describe.**
Since I am not using npm to install the dependencies, I need to run a custom script (postinstall script that is written in js, ran by node, that downloads some js files in this case).

### **Describe the solution you'd like**
Have a way to allow running postinstall and other scripts that are currently blacklisted due to wasm limitations and stuff...

### **Describe alternatives you've considered**
Running the script by going into node modules folder

**Comment by MarsOrBust24** [comment]
using postinstall on your own package.json does work...

**Comment by kc0tlh** [comment]
@sayantan300 closing this as resolved. Feel free to re-open if @FossPrime's answer does not work for your use case!
