### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by gsoftconsulting** [stackblitz/core#2014]
After forking Angular project preview pane does not render the new project. New tab in the browser does render the project after clicking "Run" button.

**Comment by fvsch** [comment]
Hi @gsoftconsulting. Do you have a link for this project?

**Comment by gsoftconsulting** [comment]
Yes, sorry I did not include the details.
I was trying to fork Angular template from Getting Started section.
https://angular-ivy-ttmqyv.stackblitz.io/
I forked this template on my account. The preview pane is blank.

**Comment by gsoftconsulting** [comment]
May be this link be any use to you. https://stackblitz.com/edit/angular-ivy-wpn8nt?file=src%2Fapp%2Fapp.component.ts

**Comment by gsoftconsulting** [comment]
Angular template is on StackBlitz Most Popular template page.
Click this template and fork it. 
This project renders on outside tab but no on preview pane.

**Comment by fvsch** [comment]
Hi @gsoftconsulting. Do you still have an issue with this?

In my tests it's working for me with Chrome, Firefox and Safari.

Could you perhaps give more information on:

1. If it works in some browsers but not others.
2. When it's not working in a specific browser, does it work with extensions turned off or with a new user profile (with a Guest profile in Chrome, or using Troubleshoot Mode in Firefox)?
3. If there are some errors reported in the browser's Console?

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information.
