### ISSUE TITLE
E-mail privacy restrictions via GitHub: Can't commit due to author e-mail being set to something unacceptable.

### ISSUE THREAD

**Issue by mjulstein** [stackblitz/core#2019]
This is probably already an issue, but I used the report bug link in the app so I'm not bothering to check 👼 
I'm just trying this thing out, so I expected it to just work with my GitHub when creating a repo through the stackblitz editor.
It's public, but I have restrictions on the email I'm sharing.
Could be useful to not have to figure out how to set the git config e-mail myself?

**Comment by AleksandrSl** [comment]
Hi, thank you for the issue. Am I correct that this is the same as [this one](https://github.com/stackblitz/core/issues/190)?

**Comment by mjulstein** [comment]
Hi.
Yes, that is correct :)
I'm going to close it now :)
