### ISSUE TITLE
Preview Pane / Dev server not loading

### ISSUE THREAD

**Issue by TheAlmightyDada** [stackblitz/core#2023]
### **Description of Bug**

Seems to only be in Chrome...

Starting a fresh React application and the right-hand pane (Dev Server / Preview) just showing a blank white page and not the:

`<div>
      <h1>Hello StackBlitz!</h1>
      <p>Start editing to see some magic happen :)</p>
   </div>`

### **Steps to Reproduce**

1. Go to '[stackblitz.com](https://stackblitz.com/)'
2. Click on the React TypeScript app
3. The dev server never loads

**Comment by devmachiine** [comment]
Same here, chrome on mac.

**Comment by kc0tlh** [comment]
This issue has been resolved:
![image](https://github.com/stackblitz/core/assets/1532264/e02acc2e-8b83-4299-9a2b-10f95bec8e87)
