### ISSUE TITLE
We should be able to duplicate a project. 

### ISSUE THREAD

**Issue by mayordwells** [stackblitz/core#203]
I'm using Stackblitz to create a tutorial for a blog post on a Wordpress website. #117 solved an issue I had with integrating into a Wordpress post. 
But I think we should be able to duplicate a project and then be able to add more code to the duplicated so as to display changes in the new one. Instead of having to create an entirely new project, copy paste the old code before adding the new code. 
Is there a feature like this hidden somewhere on Stackblitz? 
If not, is there a plan to create a feature like this?

**Comment by KurtGokhan** [comment]
Isn't 'Fork' what you are looking for? It is at the top of the editor page.

**Comment by mayordwells** [comment]
@KurtGokhan Oh thanks for pointing that out. You are right, 'Fork' is exactly what i'm looking for.

**Comment by FBalazsBme** [comment]
Who calles this fork?! This is quite counter-intuitive. They should name it clone or copy.

**Comment by TLKG** [comment]
Can't agree more!
I spent some times on "how to copy existing project into a new project" but https://stackblitz.com/docs doesn't say anything about.
