### ISSUE TITLE
Changing 'lib' compiler option doesn't make a sense for `Object.fromEntries`

### ISSUE THREAD

**Issue by Eugeno** [stackblitz/core#2030]
> Property 'fromEntries' does not exist on type 'ObjectConstructor'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2019' or later.

component:
```typescript
obj = Object.fromEntries(this.arr.map((ar) => [ar.a, ar.b]));
```

tsconfig.json:
```json
{
  "compilerOptions": {
    "module": "esnext",
    "target": "es2019",
    "lib": [
      "es2020",
      "dom"
    ]
  }
}
```

**Comment by Pdzoc** [comment]
I have the same problem - changing lib and target option doesn't solve it. 
@Eugeno Did you find another way to handle it?

**Comment by Eugeno** [comment]
Nope, created an object without `Object.fromEntries`

**Comment by johnrbaur** [comment]
I'm having the same problem trying to use `flatMap()`. I can't use lodash as a workaround because of #2618.
