### ISSUE TITLE
[alt] + commit click doesn't work on macOS

### ISSUE THREAD

**Issue by darasus** [stackblitz/core#2034]
### **Description of Bug**
When automatic commit message enable, pressing `[option] + commit` click doesn't show commit message prompt

### **Steps to Reproduce**

1. Go to any new project
2. Connect to Github repository
3. Make changes
4. Save
5. Click commit and checkmark automatic commits
6. Make more changes 
7. Press `[option] + commit` click

### **Expected Behavior**
Should see initial dialog with input for commit message

**Comment by fvsch** [comment]
Thanks for the report @darasus! We're shipping a fix for this bug right about now.
