### ISSUE TITLE
[Homepage] Support create-react-app-typescript as a project type on the homepage

### ISSUE THREAD

**Issue by mindjuice** [stackblitz/core#204]
This should be similar to the `create-react-app` JS project....but...for TypeScript.

**Comment by KurtGokhan** [comment]
You can actually create a Typescript project. It is just not on the home page. See #15.

**Comment by mindjuice** [comment]
Thanks, yes, I know.  I don't want a plain Typescript project though.  I want a `create-react-app-typescript` project to mirror the `create-react-app` project.

**Comment by EricSimons** [comment]
@mindjuice we actually have a project for CRA TS but I haven't put on homepage yet - here's the link: https://stackblitz.com/edit/react-ts

Will add this to homepage asap!

**Comment by EricSimons** [comment]
Note: Prereq for this is fixing https://github.com/stackblitz/core/issues/205

**Comment by Mydeen-SN** [comment]
any response for this

**Comment by sulco** [comment]
Done!
(sorry for taking so long to respond to this🥲)
