### ISSUE TITLE
Remove and Bulk Remove projects from Dashboard

### ISSUE THREAD

**Issue by 4javier** [stackblitz/core#2041]
Deleting projects is currently far from being user friendly

- I'd like a button available into the dashboard letting the user delete a project without opening, like it was mentioned in this ticket https://github.com/stackblitz/core/issues/1256 but it's not available anymore.
The only option I get from the three dots menu is add/remove from collection
- Add a checkbox to every project item and a general "Remove checked projects" button, considering that SB is often used as issue reproduction platform, so people tend to fork a project for very little changes to suggest solutions to original author, and then forget to drop it. (I currently have 146 projects, and just 2 I care about. I should open 144 of them one at a time just to delete them)

**Comment by FossPrime** [comment]
Alternatively, let us throw all new forks to a drafts folder and publish them to our Library like an email, RunKit, or other code sand boxes.

This would greatly cut down on low quality and repetitive forks on the examples page.

https://stackblitz.com/examples/package?q=pinia

**Comment by 4javier** [comment]
Awesome.
Exactly what I was expecting.
Thanks a lot.
