### ISSUE TITLE
Cannot import '.ts' files in React Typescript projects

### ISSUE THREAD

**Issue by KurtGokhan** [stackblitz/core#205]
In a React Typescript project, if I have a file named 'model.ts' and I try to import it:

```typescript
import { model } from './model.ts';
```

I get the error: 

> Fatal error:
> Unable to dynamically transpile ES module
> A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
> Instantiating models/hello.ts
> Loading index.tsx
> Loading blitzapp

Currently working alternative is to save '.ts' files as '.tsx'. Adding '.ts' to default extensions in SystemJS  would help.

**Comment by EricSimons** [comment]
@KurtGokhan great catch - we need to update our config settings to allow bare .ts files I think. Will dig into this & report back once the fix is in!

**Comment by CharlBest** [comment]
Hi @EricSimons Is this still being looked at as I'm having this problem in my Angular project as well.

**Comment by sulco** [comment]
This should be fixed now in React+TypeScript projects, so I'm closing the issue.

@CharlBest if you are still experiencing the issue with an Angular project feel free to open a new issue. Also adding a link to the broken project would help us find what's wrong.
