### ISSUE TITLE
why the `Infinity` is displayed as the `null`

### ISSUE THREAD

**Issue by iamrealmarsel** [stackblitz/core#2051]
Hi there!
Can you tell me, please, why the `Infinity` value is displayed as the `null` value in console ?

https://stackblitz.com/edit/js-rdq74t?file=index.js

![Screen Shot 2022-09-13 at 9 38 27 PM](https://user-images.githubusercontent.com/20097612/189983576-dde30dd9-5a25-4960-98b9-d41861896d03.png)

**Comment by fvsch** [comment]
Thanks for the report @iamrealmarsel. We have a fix for this in the works.
