### ISSUE TITLE
open terminal

### ISSUE THREAD

**Issue by bgbruno** [stackblitz/core#2054]
**issue**

steps
1. I choose "Project / Frontend / any"
2. click to "Connect repository"
3. overwrite with my code with "Import an existing repository"

I cannot open "terminal"
terminal is open only if I start "project server"

--

**solution**

on "Dashboard" add button "Create blank with your imported repository"

**Comment by qlniu** [comment]
I have the same problem, I hope the project created under Project / Frontend / any can add terminal, so that I can create and use terminal

**Comment by kc0tlh** [comment]
@bgbruno and @qlniu I just answered both your questions over in issue #2655. Cheers!
