### ISSUE TITLE
terminal remove

### ISSUE THREAD

**Issue by bgbruno** [stackblitz/core#2056]
**issue**
cannot remove all files in "terminal"

`rm -R *`
`rm: cannot remove '*': No such file or directory`

--

**solution**
allow it

**Comment by kc0tlh** [comment]
I believe this issue is resolved in [our new editor (currently in beta)](https://stackblitz.com/codeflow).

I had to run rm -R .* to get rid of the files that had a . prefix (.gitignore, etc).
