### ISSUE TITLE
[New sidebar] Add ability to collapse files panel

### ISSUE THREAD

**Issue by amcdnl** [stackblitz/core#206]
I'd like the ability to collapse the file tree panel.

**Comment by thesobercoder** [comment]
Absolutely +1 this.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
