### ISSUE TITLE
Preview not showing-up for one user, and not reloading after "no such dependency" error for another user

### ISSUE THREAD

**Issue by avrahamsakal** [stackblitz/core#2067]
We were using a plain React.js project. Speficially, [https://stackblitz.com/edit/react-ts-jsafpw?file=App.tsx](https://stackblitz.com/edit/react-ts-jsafpw?file=App.tsx).

**Comment by kc0tlh** [comment]
This issue has been resolved:

<img width="1439" alt="image" src="https://github.com/stackblitz/core/assets/1532264/78f92d36-670a-4567-be68-264ed731c777">
