### ISSUE TITLE
Can not connect to private repo on Github

### ISSUE THREAD

**Issue by veritas-laser** [stackblitz/core#2073]
Having an issue where Stackblitz is not connecting to my private Github project. I have tried opening it using the url that specifies user id, repo, and branch without success, it states that I need a membership account. Which I have. I am logged in correctly on both Github and Stackblitz. In Stackblitz I get a forbidden error in the Network tab when the site tries to ping Github.

**Comment by skryukov** [comment]
Hey @veritas-laser thanks for the issue, have you tried importing a private project via the ["import an existing repository" flow](https://developer.stackblitz.com/docs/platform/importing-projects/#importing-private-projects)?

**Comment by veritas-laser** [comment]
The project was connected last week and was working properly, but now it's not connecting. I don't see anywhere that I can reconnect to it. Do I need to create a new stackblitz project and connect to the repo in github again?

**Comment by veritas-laser** [comment]
Resolved the issue. For whatever reason popups ended up getting blocked for stackblitz in my browser. I just noticed a really quick message indicating that was the case. Once I enabled popups again for stackblitz it was able to log into github properly
