### ISSUE TITLE
Problem with static websites

### ISSUE THREAD

**Issue by juliancwirko** [stackblitz/core#2078]
### **Description of Bug**
Static websites are getting `Cannot access 'At' before initialization`, Even the newly forked empty template. This is with Chrome, with Firefox I am getting: `Error: ENOENT: No such file or directory., '/~'`

Examples:
- https://stackblitz.com/edit/web-platform-d4rx5v?file=index.html
- https://stackblitz.com/edit/web-platform-wbimtj

![stackblitz_problem](https://user-images.githubusercontent.com/4427985/191679301-d9f37ca0-5bbe-4502-a27e-34be5e45687f.png)
?file=index.html

**Comment by mcgarry** [comment]
Having the same issue. https://web-platform-zdhe6n.stackblitz.io

![Capture](https://user-images.githubusercontent.com/3899142/191744811-b5f0399a-0825-4ada-a5ba-0bee72302b89.PNG)

**Comment by TheTiGuR** [comment]
@juliancwirko @mcgarry - Would you both look at your projects? This appears to have been fixed and both seem to be working now.

**Comment by juliancwirko** [comment]
yes, now it works, thanks

**Comment by mcgarry** [comment]
Working now thanks

**Comment by fvsch** [comment]
Hi everyone! We had a small regression here (well a big one, since it broke all “Static HTML” projects). We reverted the faulty change yesterday indeed. Thanks for the reports and for your patience! 🙏
