### ISSUE TITLE
Data Table Skeleton not working

### ISSUE THREAD

**Issue by BobbyGannard** [stackblitz/core#2081]
I was trying to use the example given on the site for a table skeleton. I could not get it working.
` <p-table [value]="products">
    <ng-template pTemplate="header">
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Category</th>
        <th>Quantity</th>
      </tr>
    </ng-template>
    <ng-template pTemplate="body" let-product>
      <tr>
        <td><p-skeleton></p-skeleton></td>
        <td><p-skeleton></p-skeleton></td>
        <td><p-skeleton></p-skeleton></td>
        <td><p-skeleton></p-skeleton></td>
      </tr>
    </ng-template>
  </p-table>`
  I decided to look at the StackBlitz and found that it was also not working on there either. 
  https://stackblitz.com/edit/primeng-skeleton-demo?file=README.md

**Comment by fvsch** [comment]
Hi @BobbyGannard,

It looks like this might be an issue to bring up with the PrimeNG team on the https://github.com/primefaces/primeng repository instead. Unless there's something specific not working with StackBlitz that is working when working locally with the Angular CLI in this instance?
