### ISSUE TITLE
Starting dev server - No result shown

### ISSUE THREAD

**Issue by cmd89** [stackblitz/core#2090]
Trying stack blitz for first time, used angular template and the default works fine.

As soon as I add angularfire2 dependency, show message at bottom compiling application and starting dev server and in browser it keeping showing "Starting dev server" without any result waited for more than 30 mins.

Using Chrome Brower

**Comment by donmckenna** [comment]
`angularfire2` has been deprecated for a few years and replaced with `@angular/fire`
https://github.com/angular/angularfire

Using the official `@angular/fire` library with `ng add` may be a better bet.

![image](https://user-images.githubusercontent.com/22125230/192852151-827dd6fb-3e40-40c4-b814-6c75b4d86e6b.png)

**Comment by donmckenna** [comment]
Closing, as the issue may be due to the deprecated library.
If using `@angular/fire` doesn't help, feel free to reopen :)
