### ISSUE TITLE
Cannot access or delete collection if slug contains leading `/` character

### ISSUE THREAD

**Issue by ctangney-tulip** [stackblitz/core#2095]
### **Description of Bug**
Unable to access or delete a collection which was given a slug that contains a leading `/` character. Additionally, these collections cannot be deleted.

I stumbled upon this inadvertently, and now I cannot delete these collections 🙃

### **Steps to Reproduce**
1. Create a new collection
2. Save the collection
3. Edit the collection slug to a string which contains a leading `/` character. Example: `/a-test-slug`
4. Observe that you are correctly redirected to a _URL encoded_ version of the slug.
5. Navigate back to the dashboard.
6. Try to navigate to the collection again.
7. Observe that you are incorrectly redirected to a _non-URL encoded_ version of the slug (resulting in `some.url//a-test-slug`)
8. Navigate back to the dashboard and attempt to delete the collection.
9. Observe that you are redirected to an error page and that the collection still remains on the dashboard.
10. Finally, observe that providing the correct URL encoding to the slug enables you to visit the collection (`some.url/%2Fa-test-slug`)

### **Expected Behavior**
I can correctly navigate to / delete / interact with collections which may contain a leading `/` character.

**Additional Context/Questions**
The collection in question: https://stackblitz.com/@ctangney-tulip/collections/%2Fa-test-slug
The broken link in question: https://stackblitz.com/@ctangney-tulip/collections//a-test-slug

This could be handled in a number of ways
- Leading `/` characters are stripped from the slug
- Since the initial edit to the slug works, correct encoding on subsequent requests to the slug.
- This could be related to the following issue: #2005

**Comment by ctangney-tulip** [comment]
Any effort on this would enable me to remove the broken collection(s) from my dashboard 🙏

**Comment by ctangney-tulip** [comment]
Pinging this again, since looking at the additional collections on my dashboard makes me sad 😞

**Comment by kc0tlh** [comment]
@ctangney-tulip I'm combining this with #2161 for easier tracking. Please shoot an update there if you are still unable to delete!
