### ISSUE TITLE
Changes disappear when connected to Git, though saved

### ISSUE THREAD

**Issue by prompttp** [stackblitz/core#2098]
If you connect your Stackblitz project to Git repo, you have a problem: you need to push to git, otherwise all your changes are lost, even if you hit "Save" button.

How to reproduce (very easy):

- Create a StackBlitz project (I used TypeScript blank project)
- in "index.ts" add a line to the bottom: `// I will be saved`
- click "Save" button (upper left corner)
- reload. You can see your modifications. It is saved
- now click "Connect repository", follow the instructions, wait until it's settled
- in "index.ts" add a line `// I'm gonna vanish`
- click "Save" button. Notice, Stackblitz says "saved"
- reload the page, despite the warning
- now you can see how your last line disappears right in front of you 

Of course there is a warning. But what if my browser was killed by force? It happened to me and I lost 1 hour work. Not much, but it's frustrating anyway. I'm not the only person, whos browser froze and was force quit, many other developers might get caught by this seemingly easy to fix problem.

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473
