### ISSUE TITLE
Add confirmation dialog for deleting files

### ISSUE THREAD

**Issue by ofirrifo** [stackblitz/core#21]
Thanks for this great online editor.

1. delete file is immediately remove without show me any alert that I'm going to lose this file
2. is it possible to automatically add an import?
    for example in angular  when I write  @Component({}) it will suggest to add the relevant import
3. since the angular project use angular cli can I create new component with the angular cli command?

**Comment by EricSimons** [comment]
Thanks for the kind words! Regarding your points:

1. Good point — I'll add in a confirmation dialog!
2. We don't currently do this; which editor/plugin do you use locally that automatically does that?
3. Not yet, but we're adding that in soon :)

**Comment by EricSimons** [comment]
This is now live on prod! Had lots of other difficult bugs ahead of this one, sorry about the delay 😅

**Comment by ofirrifo** [comment]
Thanks :)
