### ISSUE TITLE
Awesomeblitz!

### ISSUE THREAD

**Issue by lelong37** [stackblitz/core#210]
Thanks awesome tool for jedi prototyping, thanks team! Is implementing a terminal and run commands e.g. angular/cli commands for generating.

Saw on issues that github integration is quite the feature request already, +10

If we could pull from github and actually use stackblitz for an IDE, would be killer.

**Comment by EricSimons** [comment]
@lelong37 you can actually do this already! Just right click on any folder and it gives you a list of the generators you can run :)
