### ISSUE TITLE
Collections missing from add/remove dialog

### ISSUE THREAD

**Issue by iessa-pragg-ctct** [stackblitz/core#2101]
### **Description of Bug**
Add to collection from the three dots menu on the home page only shows filtered collections as options.

### **Steps to Reproduce**

1. Go to home page dashboard
2. Have more than three collections
3. Click on a projects three dots menu
4. Click on "Add or remove from collections"

### **Expected Behavior**
All collections are available to choose from.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/38093909/194415911-ec0b3166-673f-43f7-b5d4-79714d68216f.png)
![image](https://user-images.githubusercontent.com/38093909/194415833-a44d7645-9581-4e2f-b81b-e61a83ade571.png)
![image](https://user-images.githubusercontent.com/38093909/194416057-9e751084-50b4-486b-a7a1-328c123e331e.png)

**Comment by kc0tlh** [comment]
Closing this issue as this functionality has been deprecated.
