### ISSUE TITLE
Initializing git repository spinner continually spins, even though the repo is available & there are no changes.

### ISSUE THREAD

**Issue by raddevus** [stackblitz/core#2103]
In the upper left hand side the "Initializing git repository" continually spins. 
I saw this behavior once a couple of days ago after I first added the project to the Git repo, but then when I refreshed the browser it was fixed.
Now, every time I load the project it shows this wait cursor.

## Here's a snapshot...
![image](https://user-images.githubusercontent.com/16722666/194649226-66e474e2-00b3-440d-9f18-47e75d031661.png)

## What I've Tried
I run Ubuntu 22.04 & FireFox.
I've made a change to the file and saved again.  No effect.
I've refreshed the page a number of times.  No effect.
Tried it on another machine (on another network even). No effect.  - Used FireFox on Windows 10
All of those attempts were with FireFox.

### Tried MS Edge
I also tried MS Edge and loaded the project and the problem still occurs.

### Tried Downloading Project
I tried downloading the project -- since it is located in the same widget area.  No effect.
I've tried going to Dashboard and loading project again.  No effect. 

## Also Noticed
I also noticed that if I make a change and save the >Commit button never becomes available again.
That is probably a clue to the problem -- I guess it cannot reach my repository.

Here's the URL of the project on stackblitz: [https://stackblitz.com/edit/allstory](https://stackblitz.com/edit/allstory)
Here's the URL of the git repo: [https://github.com/raddevus/allstory](https://github.com/raddevus/allstory)

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473
