### ISSUE TITLE
Tried to import 2 different repos via URL and they both fail

### ISSUE THREAD

**Issue by liana-p** [stackblitz/core#2107]
I tried importing a "starting template" part of my monorepo with the url [https://stackblitz.com/fork/github/liana-p/narrat-engine/tree/main/demo-template](https://stackblitz.com/fork/github/liana-p/narrat-engine/tree/main/demo-template) but cloning lasts infinitely and fails

I then tried moving that base template to its own repo as a test and importing [https://stackblitz.com/github/liana-p/narrat-demo-game](https://stackblitz.com/github/liana-p/narrat-demo-game) (tried with and without url parameters or the fork mode)

Neither work and I eventually get to the "something is wrong with this repo" error

![image](https://user-images.githubusercontent.com/32243840/195199613-737ef4c7-a984-41d3-94d4-bd441863ae5d.png)

Could it have a problem with specific file types?

For example there are a few webp files, mp3 files and `.nar` files.  The files are still pretty small though and there's less than 1MB of data to clone anyway. They're just needed for the template to work.

This was on Firefox 105.0.3. I also tried Chrome

**Comment by HeyGarrison** [comment]
👋 

It looks like this one is working now!

Our platform has changed in the last year. We've been shipping a ton of new features. One thing you might checkout is our next gen editor. Check out how to use here: https://developer.stackblitz.com/codeflow/using-pr-new

Thanks for the issue!
