### ISSUE TITLE
StackBlitz is filtered

### ISSUE THREAD

**Issue by saadati-mohammad** [stackblitz/core#2109]
Hello
StackBlitz is my favorite editor cause I am not able to run angular in my weak PC.
within these weeks I'm unable to connect stackblitz and it's necessary to turn on VPN first ( which is not good for coding ) .
Is it possible to solve this issue completely? so programmers in Iran would become very thankful for your excellent coding service.
 thanks for your attention

Mohammad Saadati,

**Comment by HeyGarrison** [comment]
Hey Mohammad,

Thanks for the issue. Could you reach out to support@stackblitz.com for this?

Not sure there is much we can do, but happy to chat more via email.

Thanks!
