### ISSUE TITLE
Infinite loop if break condition in while not set

### ISSUE THREAD

**Issue by mdrobynin** [stackblitz/core#211]
I tried to write a while loop in my angular service, and before i even can write an exit condition my browser hanged not responding to any actions
something like
let a=0;
while (a<50) {}

**Comment by 1j01** [comment]
There's this library which could be used https://github.com/jsbin/loop-protect
Although it apparently doesn't use an AST, so it's got stupid bugs
There's a version that does use an AST: https://github.com/nathanhammond/loop-protect-esprima 
The trade-off being weight of the dependencies, and probably speed

**Comment by EricSimons** [comment]
Thanks for the issue & for the relevant links! We're gonna knock this out - will report back once implemented 👍

**Comment by nauzilus** [comment]
As a work around, could the project be persisted to local storage, even if it's just every few minutes? I know that's probably much easier said than done, but at least work could potentially be restored to a semi-recent state

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
