### ISSUE TITLE
Can't handle relative imports inside `.less`-files of published library

### ISSUE THREAD

**Issue by nsbarsukov** [stackblitz/core#2112]
### **Steps to Reproduce**

1. Open Angular Stackblitz starter
<img width="1260" alt="00-select-angular-template" src="https://user-images.githubusercontent.com/35179038/195788485-03ad2fad-98b3-4fbe-bb7c-9a9988a7f361.png">

2. Add these deps to `package.json` and press "Save"
```json
"@taiga-ui/core": "3.6.0",
```
3. Also install proposed peer deps of this new package
<img width="1789" alt="01-installPeerDeps" src="https://user-images.githubusercontent.com/35179038/195788600-52e94a0d-4fbd-4af2-85f6-6eb0639672dc.png">

4. Rename `app.component.css` => `app.component.less` (don't forget to change `styleUrls` inside `app.component.ts`)
<img width="1789" alt="02-cssToLess" src="https://user-images.githubusercontent.com/35179038/195789121-e23f5c92-5bbc-40d6-afd0-9385b7969f47.png">

5. Add this line inside `app.component.less`:
```
@import '@taiga-ui/core/styles/taiga-ui-theme.less';
```

It throws error
```console
Error in turbo_modules/@taiga-ui/core@3.6.0/styles/theme/dialog.less (1:0)
Could not import ../mixins/mixins.less from /~/src/app/app.component.less
```
<img width="1789" alt="03-error" src="https://user-images.githubusercontent.com/35179038/195788753-2b5019d0-c1bf-4bf3-9dc9-ab9e35dde70b.png">

### **Expected Behavior**
No error :)

**Additional Context/Questions**
- Final reproduction can be found here:
https://stackblitz.com/edit/stackblitz-less-imports-bug?file=src%2Fapp%2Fapp.component.less

- Source files of `@import '@taiga-ui/core/styles/taiga-ui-theme.less'`:
https://github.com/Tinkoff/taiga-ui/blob/main/projects/core/styles/taiga-ui-theme.less

**Comment by nsbarsukov** [comment]
I am not sure, but possibly it can be the same issue as https://github.com/stackblitz/core/issues/1828 (or maybe not).
Anyway, I hope that I provide clear enough way to reproduce problem.

We are looking forward to bug fix because we actively use Stackblitz inside our [Taiga UI](https://taiga-ui.dev).
We will really appreciate if you can handle this.

**Comment by markwhitfeld** [comment]
The fix has been deployed. Closing this. Let us know if you experience the same issue again.
