### ISSUE TITLE
How to enable preview on codeflow

### ISSUE THREAD

**Issue by abmehmet** [stackblitz/core#2119]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
Hi stackblitz team. i want to preview mode on codeflow screen. But i can try many times i can not this feature active. So for examle i can create blank type script project. Everything well, preview runs awesome, but i change throw codeflow, i can not see preview. how to do this function. thanks for everything, best regards

**Comment by kc0tlh** [comment]
@abmehmet this issue has been resolved. The preview will now open automatically upon loading your project in our [new VS Code editor](https://stackblitz.com/codeflow).
