### ISSUE TITLE
Save current state of app as a default template (support multiple templates)

### ISSUE THREAD

**Issue by moniuch** [stackblitz/core#212]
Let have the functionality of saving an app at its current state, as a default one, ie. a starting point for next one. Something like a template in Word or Google Drive, where you can later choose "Create new with..."

We can start with one, but eventually it be great to be able to save multiple default instances (eg. one with ngrx store, another with router and a couple of pages, etc...)

A template could be:
- public - to share with everyone using StackBlitz,
- protected - to share it with anyone who knows an url (would that be feasible?)
- private - only within a registered account.

Obviously, you should be able to edit/update your template. It would be awesome, if this scenario could be covered:
- you save a template
- you then create an app based on it
- you realize that you just made a change that you would like to incorporate into the template
- you select: Edit Template.

**Comment by EricSimons** [comment]
@moniuch thanks for the detailed writeup! We'll start working on this asap :)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
