### ISSUE TITLE
Preview in new window not starting

### ISSUE THREAD

**Issue by tlntechno** [stackblitz/core#2123]
When running an embedded version of stackblitz, the "preview in a new window" feature does not work. 

Everything inside of the embedded stackblitz works fine, and the dev server starts up as usual, but when I open the preview URL in another window, it's stuck on "Starting dev server" infinitely.

It has worked before, so I don't think this is an issue regarding the embedding of the VM.

**Comment by geromegrignon** [comment]
Hi @tlntechno, please provide a link to your project to test it.

**Comment by kc0tlh** [comment]
I was able to confirm this feature is currently working under normal circumstances:

<img width="1437" alt="image" src="https://github.com/stackblitz/core/assets/1532264/611241f3-aef6-4f1a-823c-afb49b14aba8">
_WebContainer based project on https://contentlayer.dev/_

If you have a working repro of the issue feel free to share and I can re-open this issue!
