### ISSUE TITLE
Can't open share URL. 

### ISSUE THREAD

**Issue by teru-mi** [stackblitz/core#2128]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

I want to share URL. But it's not opening.

https://typescript-pusapr.stackblitz.io

### **Screenshots/Screencast**
1. 
<img width="739" alt="スクリーンショット 2022-10-25 0 10 49" src="https://user-images.githubusercontent.com/74748029/197561167-0485cb84-b445-44e4-81ca-45b756494f6a.png">
2. 
<img width="634" alt="スクリーンショット 2022-10-25 0 11 54" src="https://user-images.githubusercontent.com/74748029/197561419-81cd18b5-eb83-4e04-a1bc-8b31f242ba4b.png">
3.
<img width="1523" alt="スクリーンショット 2022-10-25 0 12 15" src="https://user-images.githubusercontent.com/74748029/197561487-a72b5226-f1b9-4664-b30f-df3307f93fd4.png">

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by geromegrignon** [comment]
Hi @teru-mi,

You need to share this URL: https://stackblitz.com/edit/typescript-pusapr
Your previous URL is from the rendered application, but as there is nothing to render, it renders a blank page (you can still see your log outputs by opening the devtools of your browser.

**Comment by teru-mi** [comment]
Thanks😊
