### ISSUE TITLE
Dependency not installing

### ISSUE THREAD

**Issue by Bellowrld** [stackblitz/core#2129]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by fvsch** [comment]
Hi @Bellowrld. Could you open a new issue and fill out the issue template?

As it stands, just a title like "Dependency not installing" is not actionable information that we can use to identify the problem you're facing.
