### ISSUE TITLE
[Schematics?] Provide a way to import components easily

### ISSUE THREAD

**Issue by moniuch** [stackblitz/core#213]
Pertains to Angular, don't know how usable it would be for other frameworks

I would wholehartedly welcome a functionality of importing (or linking to) components, pipes, directives, etc. into an app.
I would imagine being able to:
- work on a component in StackBlitz, and then save it
- import a set of files that constitute a component (a folder/zip with html, ts, css/scss files)
- import a gist or any platform-based "solution".
You should be able to save the components and build your own library within StackBlitz, to be later shared, just like templates descibed in #212.

**Comment by EricSimons** [comment]
@moniuch this kinda sounds like the new schematics stuff the ang team is working on - have you looking into that at all? We're planning on building in full schematics support w/ custom config, which I _think_ would solve this!

**Comment by moniuch** [comment]
Hi,
I have heard the term but never followed up on it. Glad this idea sounds
reasonable.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
