### ISSUE TITLE
The preview is not loading

### ISSUE THREAD

**Issue by looh2** [stackblitz/core#2139]
The preview is not loading

**Comment by kc0tlh** [comment]
Please make sure [your browser is configured properly with 3rd party cookies enabled](https://developer.stackblitz.com/platform/webcontainers/browser-config) and ad-blockers disabled (as described in issue https://github.com/stackblitz/core/issues/162) and test your project on a different browser.

If you are still experiencing this issue, please share a link to your project, what browser/version you are on, and I will re-open this issue for further investigation!
