### ISSUE TITLE
Run a GitHub-Bitbucket Angular project

### ISSUE THREAD

**Issue by moniuch** [stackblitz/core#214]
Provide URL
Install dependencies
Run

**Comment by EricSimons** [comment]
@moniuch this is already supported for github actually! Any angular-cli project you can just go to stackblitz.com/github/GH_USERNAME/REPO_NAME 

For ex, here's the [RealWorld Angular](https://stackblitz.com/github/gothinkster/angular-realworld-example-app) repo 🎉

**Comment by alta8** [comment]
my issue is a little bit different.
The angular-project I'm trying to run is with in a github repo that contains two angular-projects. (https://github.com/FabianGosebrink/AngularDays-Testing is the repo and tests the angular-project).
So the package.json is not directly under the github repo but one directory further down. (stackbliz message: 'The repository is missing a package.json file')
Is there a way to tell stackbliz to load an angular-project that is within a certain directory? Like stackblitz.com/github/GH_USERNAME/REPO_NAME/NG_PROJ Obviously this is not working. I tried it. But is there something like that?
