### ISSUE TITLE
Extensions not working in Codeflow

### ISSUE THREAD

**Issue by michaelrkn** [stackblitz/core#2140]
Using Codeflow, when on the Extensions view, clicking Refresh gives the error "No extension gallery service configured." 61 extensions are listed as installed, but searching for any other extensions gives "No extensions found."

<img width="345" alt="Screen Shot 2022-11-01 at 1 17 02 PM" src="https://user-images.githubusercontent.com/1266530/199308175-955abc32-0496-4f15-9efc-916fd76feaaf.png">

**Comment by samdenty** [comment]
Hi @michaelrkn, I'm not able to reproduce this. What browser are you using?

https://user-images.githubusercontent.com/13242392/199312015-ed42609a-1777-4e4d-9aee-c797e5536d04.mp4

**Comment by michaelrkn** [comment]
I'm on latest Chrome (Version 106.0.5249.119 (Official Build) (arm64)). But I just tried again and didn't get the error, so I'll close out.

In the demo video, it said that extensions are supported - I didn't realize that it was just the preinstalled ones. Looking forward to support for extension registries! Codeflow is really awesome.
