### ISSUE TITLE
[Question] Unable to build SDK

### ISSUE THREAD

**Issue by hoangpq** [stackblitz/core#2147]
I tried to build `sdk` package but got this error
<img width="756" alt="image" src="https://user-images.githubusercontent.com/5939997/200499333-00eb92a0-8df6-4169-8aeb-087d96172e6d.png">

Working fine after adding **es2020** compile option to **lib**
```json
{
  "compilerOptions": {
    "module": "es2015",
    "target": "es2020",
    "lib": ["es2020", "DOM"],
    "noImplicitAny": true,
    "strictNullChecks": true,
    "outDir": "./dist/",
    "declaration": true,
    "declarationDir": "./typings/",
    "removeComments": false,
    "sourceMap": true
  },
  "include": ["./src/"],
}

```
<img width="704" alt="image" src="https://user-images.githubusercontent.com/5939997/200500930-ffaddf9d-9323-4bf1-a861-eff08039a712.png">

Is this bug or am I missing something? @EricSimons

**Comment by fvsch** [comment]
Hmm the issue we're having is that `sdk/package.json` and the root `package.json` in the repository are for completely different projects. Sometimes around version 8.4, the `npm` CLI decided that running `npm install` in the `sdk` directory should also install dependencies in the root directory. So we need to bypass it with:

```sh
npm install --no-workspace
```

Long term, if we want to keep the SDK in `stackblitz/core`, we may need to turn this repository into a proper monorepo setup.

Alternatively we could move the SDK to a different repository, namely `stackblitz/sdk`. We would lose some Git history but we do have a proper changelog for the SDK now, so I’m okay with that.

**Comment by hoangpq** [comment]
Got it. Thanks for clarifying @fvsch.
