### ISSUE TITLE
angular14 project with scss support brings error on styles.css

### ISSUE THREAD

**Issue by myonara** [stackblitz/core#2152]
I've created a project by importing from [Github-test-scrollpanel](https://github.com/myonara/test-scrollpanel) iinto the following project: [Stackbilitz project](https://stackblitz.com/edit/angular-ivy-bfhptk?file=src/index.html).
It is a brand new angular project with scss support as correctly entered in the angular.json.

The display is showing the error "Import error, can't find file: /src/styles.css".

**Comment by HeyGarrison** [comment]
👋 

Over the past year we've shipped a ton of improvements to the platform. It looks like somewhere along the way we solved this problem!

Feel free to open up a new issue if you run into any issues!

Thanks!
