### ISSUE TITLE
Nightly Typescript features not applied correctly

### ISSUE THREAD

**Issue by Darkmift** [stackblitz/core#2159]
Hello,

**_This might not be a bug as much as it may be a missing feature or required update._**

In the following code example the registration and highlighting of the `satisfies` operator do not apply correctly.
the solution in Vscode is a plugin:

https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next

```typescript
type City = CityName | CityCoordinates;
type CityName = 'New York' | 'Mumbai';
type CityCoordinates = { x: number; y: number };

type User = { birthcity: City; currentCity: City };

const user1:User = {
  birthcity: 'New York',
  currentCity: { x: 1, y: 2 },
};

user1.birthcity.toUpperCase();

const user2 = {
  birthcity: 'New York',
  currentCity: { x: 1, y: 2 },
} satisfies User; //the satisfies operator is improperly registered as a variable

user2.birthcity.toUpperCase();
```

**Comment by wycats** [comment]
Now that this feature is in TypeScript 4.9, it's even more glaring that this still doesn't work.
