### ISSUE TITLE
Suggestion: Auto close tag for HTML/JSX tags 

### ISSUE THREAD

**Issue by guigaoliveira** [stackblitz/core#216]
I don't know if I can put extensions on the site, but particularly like https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag extent and I would suggest that implementation.

**Comment by EricSimons** [comment]
I dig it! I'll look into implementing something similar in Jan :) Thanks a ton!

**Comment by khaki32** [comment]
Was this implemented? How do I use this?

**Comment by HummingMind** [comment]
+1

**Comment by Eric-Musa** [comment]
+1
