### ISSUE TITLE
Cant remove collectons

### ISSUE THREAD

**Issue by PhilipBrodovsky** [stackblitz/core#2161]
### **Description of Bug**
I try remove collection (https://stackblitz.com/@PhilipBrodovsky/collections/realtime/lesson1)
I see its my collection list bug got error after try to delete.
**** error:

Yikes! The page you requested couldn't be found.
If you think this is a bug/problem on our end, please file an issue over at https://github.com/stackblitz/core
****

### **Steps to Reproduce**
I am not remember the steps that create this bug 

### **Expected Behavior**
success to delete collection

**Comment by kc0tlh** [comment]
@PhilipBrodovsky I was able to create a similarly named collection and delete it from my dashboard successfully:

<img width="1035" alt="image" src="https://github.com/stackblitz/core/assets/1532264/27fc7bbd-b66e-4afb-8c1f-58646e04d64e">

Going to mark this as resolved for now, but feel free to re-open if you are still experiencing this issue!

**Comment by kc0tlh** [comment]
Eng team confirmed these projects can be deleted now! Closing the issue.
