### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Residental** [stackblitz/core#2167]
When I opened my project. Everything was gone. All my data was lost. What should I do? Please Help!!!

**Comment by HeyGarrison** [comment]
Hey @Residental - so sorry to hear this.

Unfortunately, if you didn't save your project there isn't much we can do.

Moving foward I'd recommend you use our new git integration for version control. I suspect that would've helped to prevent this problem.

See the docs here: https://developer.stackblitz.com/codeflow/using-pr-new#frontmatter-title

Again - sorry about this. Please do let us know if it happens again.
