### ISSUE TITLE
I am getting CSS import error in react module

### ISSUE THREAD

**Issue by girish1729** [stackblitz/core#2168]
Please look at screenshot for details.

![react](https://user-images.githubusercontent.com/6890469/202753166-750bf35b-af7a-406e-bc92-fead5f7e4cf7.png)

It is working fine on my laptop. How are you losing first 20 characters?

**Comment by girish1729** [comment]
This is my repo.

https://stackblitz.com/edit/react-ts-iscadj?file=index.tsx

**Comment by HeyGarrison** [comment]
👋 

We've shipped a ton of improvements to StackBlitz over the past year. It looks like this is resolved!

If you have any other issues feel free to open a new issue.

Thanks!
