### ISSUE TITLE
Code editor scrolling broken in Edge

### ISSUE THREAD

**Issue by boarder2** [stackblitz/core#217]
The code editor doesn't scroll in Edge while using a precision touchpad or touch screen on a Surface device.

It does work with a mouse scroll wheel in Edge.

Scrolling works in Firefox and Chrome with the touchpad and touch screen.

**Comment by EricSimons** [comment]
@boarder2 thanks for reporting this! We'll investigate & fix asap 👍

**Comment by boarder2** [comment]
@EricSimons Awesome!  For what it's worth, it looks like this may be an issue with Monaco/Edge.  Take a look at https://github.com/Microsoft/monaco-editor/issues/325 which references https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/

Perhaps there's not much you can do about it :(

**Comment by SamVerschueren** [comment]
Closing this as Edge switched to Chromium under the hood and I believe it should be fixed.

We can't do much about it if it's a monaco issue.
