### ISSUE TITLE
Error: ENOENT

### ISSUE THREAD

**Issue by libdc** [stackblitz/core#2171]
Every time I load my project I keep getting "Error: ENOENT: No such file or directory., '/~'" in the console and preview window I am unable to load my project inside the preview window at all. This is also happening for new project forks as well this seems to be happening under Frontend > Static HTML / CSS / JS

**Comment by satyam-mishra-pce** [comment]
> Every time I load my project I keep getting "Error: ENOENT: No such file or directory., '/~'" in the console and preview window I am unable to load my project inside the preview window at all. This is also happening for new project forks as well this seems to be happening under Frontend > Static HTML / CSS / JS

Same Issue

**Comment by kc0tlh** [comment]
@libdc & @satyam-mishra-pce can you please share a link to a public project where you are experiencing this issue?

**Comment by satyam-mishra-pce** [comment]
> @libdc & @satyam-mishra-pce can you please share a link to a public project where you are experiencing this issue so I can take a look? In the meantime, I am closing this as a suspected duplicate of #1427 or #162.

Sure, here is the link of my project: https://stackblitz.com/edit/the-pizza?file=styles.css
