### ISSUE TITLE
Dashboard: mitigate page jumping

### ISSUE THREAD

**Issue by moniuch** [stackblitz/core#2172]
I find dashboard to be very difficult to manage:

1. When I'm on a page X of the table, any deletion brings me back to page 1.
2. When deleting a project on page 1, the page jumps back to top.

It would be helpful to do persist page and scroll position.

**Comment by kc0tlh** [comment]
@moniuch thanks for this excellent product feedback!  The team resolved this in the dashboard redesign ✨
