### ISSUE TITLE
Package add issue

### ISSUE THREAD

**Issue by DevAIMastery** [stackblitz/core#2178]
Cannot add Dependency/package on Android tablet devices..  fix this..

**Comment by frog-o** [comment]
@DevAIMastery
I have a lot of problems on mobile also but I found out it just
Some of them. I know it not to much help but you might want to try a bear
Minimum package.conf and see what works.

 I also know you posted this about a year ago, so maybe  this is working better now then when you originally reported. 

If anyone 
Need info on steps to reproduce.
Run yarn(or your own package manager)

1.) Create a new project doesn't matter 
2.) Run yarn(or your own package manager) installs

Works fine 👍 good other wise you see my 👉 point 
3.) Trying  yarn install better-docs
It return a link error complaining core-js is to old or something like that
