### ISSUE TITLE
3rd party library does not load.

### ISSUE THREAD

**Issue by peymanebrahimi** [stackblitz/core#218]
An angular [project ](https://stackblitz.com/edit/angular-jalali-datepicker) which does not work in stackblitz, but works locally.
source code are also available on [github](https://github.com/peymanebrahimi/AngularMaterialJalaliDate).
It says ` TypeError: jmoment is not a function `.
The 3rd party [library](https://github.com/fingerpich/jalali-moment)  is added as dependency but is not recognized by the stackblitz.

Can someone help me with this dependency?

**Comment by EricSimons** [comment]
@peymanebrahimi this is because you're importing the module namespace, not the default export. Instead of `* as jmoment` it should just be `import jmoment from 'jalali-moment'. Just confirmed that works :)
