### ISSUE TITLE
once we freze the project, and fork it. Project shows as freezed but it works as inversly.

### ISSUE THREAD

**Issue by Yuvaraj-2001** [stackblitz/core#2183]
![image](https://user-images.githubusercontent.com/62696754/204141813-2c0772fe-6f3f-4bee-8948-3abeff6d9070.png)

![image](https://user-images.githubusercontent.com/62696754/204141853-f46988f0-a7aa-4ec3-a2af-64855e1a840e.png)

**Comment by HeyGarrison** [comment]
👋 

We've shipped a ton of improvements over the past year. It looks like this is fixed.

Feel free to create a new issue if anything else pops up!
