### ISSUE TITLE
help

### ISSUE THREAD

**Issue by legndarycryst** [stackblitz/core#2198]
IMPORTING FROM GITHUB
forkgithubwebpackwebpack.js.orgtreemasterexamplesgetting-started
Specified branch/tag/commit not found
Check that your URL pattern is correct:
.../github/{GH_USERNAME}/{REPO_NAME}/tree/{BRANCH|TAG|COMMIT}/{OPTIONAL_PATH}

If you think this is a bug, please [file an issue](https://github.com/stackblitz/core/issues/new) in our repo!

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
