### ISSUE TITLE
About forked project in Stackblitz

### ISSUE THREAD

**Issue by NguyenAnhTuan1912** [stackblitz/core#2199]
Hello everyone, I have two questions.

- I have a project that is connected to github. When I save my project, a dialog show up and recommend me to save changes in a new fork. Then a have a forked project, so how can I merge the forked with the original one?

- When I reload Stackblitz, a prompt show up and warning about my changes may lost although the project save changes successfully.
Thanks

**Comment by elepner** [comment]
I've got the same problem. It seems there's no solution yet. See [this issue](https://github.com/stackblitz/core/issues/371).

**Comment by HeyGarrison** [comment]
👋 

Sorry this is happening... In the past year we've updated our product significantly. I'd recommend using one of our new features called pr.new. You can checkout the docs here:

https://developer.stackblitz.com/codeflow/using-pr-new#frontmatter-title
