### ISSUE TITLE
How to run stackblitz core on my own website?

### ISSUE THREAD

**Issue by ide5kllc** [stackblitz/core#2206]
I'm looking for something to provide a 100% in-browser typescript IDE that I can run on my own website.

So far, I'm looking at https://www.typescriptlang.org/play?#code -- it's almost everything I want, except for the inability to support multiple files.

I'm wondering if there are instructions anywhere on running stackblitz/core on MY OWN WEBSITE ?

Thank you.

**Comment by SamVerschueren** [comment]
The typescript lang playground just uses the [monaco editor](https://microsoft.github.io/monaco-editor/). I think that should already get you quite far without the need of running anything like WebContainers.

**Comment by kc0tlh** [comment]
@ide5kllc you should also checkout out our [Webcontainers.io](https://webcontainers.io/) API that allows you to build a fully custom experience on top of our WebContainers technology.

For a simpler approach, you can use [our SDK](https://developer.stackblitz.com/platform/api/javascript-sdk) to embed the StackBlitz editor inside your site.
