### ISSUE TITLE
If github username changes, profile breaks

### ISSUE THREAD

**Issue by EricSimons** [stackblitz/core#221]
See https://stackblitz.com/@briangallag whose username is now https://github.com/adenosineantagonist

**Comment by tplk** [comment]
Same here, would be nice to be able to update my stackblitz username.

**Comment by apai4** [comment]
@tplk Just pushed a fix for this, your username should be updated the next time you log in. Lmk if it works for you!

**Comment by tplk** [comment]
@apai4 It works, thanks!
