### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by marysonthego** [stackblitz/core#2211]
Today I received this error for the first time on a project that had not changed in 2 months.  You can see the public project here: https://stackblitz.com/edit/react-tqwgrp?file=src%2Findex.js,src%2FApp.js,src%2FList.js,src%2FPosta.js,src%2FPostb.js

It uses react-router-dom v6. The project was embedded in a blog post, but I had to remove it due to the error. I did a direct copy/paste of my files to CodeSandBox here: https://codesandbox.io/s/v6routertests-rzq9me?file=/src/Posta.js, where it is working fine. Please take a look. The problem appears to be on your end.  Thank you!

**Comment by Srisrinivasa** [comment]
Same with my project too: https://retro-app-py86lx.stackblitz.io/taskmanager
On refresh having any routed paths then the issue is happening.

**Comment by HeyGarrison** [comment]
👋 

This appears to be working for me, but with that said I would recommend using our Vite based starters like this: https://vite.new/react.

Thanks for the issue!
