### ISSUE TITLE
I am using Static HTML/CSS/JS project with face-api.js models are not able to load

### ISSUE THREAD

**Issue by PVSPReddyWork** [stackblitz/core#2216]
I am using Static HTML/CSS/JS project with face-api.js models are not able to load, I have models and respective JSON files in a folder, the JSON files loads properly and when the project tries to load the models it throws 404 not found error. Is this an expected error like, stackblitz doesn't have support for this or any other suggestions. I am blocked with this issue. Please help, if you have any idea. the same project is working in my localhost server(in my pc).

**Comment by kc0tlh** [comment]
This issue should be resolved in [our new VS Code editor](https://stackblitz.com/codeflow)!
