### ISSUE TITLE
git doesn't detect changes when angular component is generated via folder menu

### ISSUE THREAD

**Issue by mirvel** [stackblitz/core#2217]
Repro:
1. Import github repository
2. Right click on `app` folder and generate new `component`
3. Click `Commit` button to push changes to github

Expected:
@2 `Commit` button should become enabled (meaning detect changes)
@3 Only some files of new component got pushed to remote github repository. (In my case it was missing .html file)

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Full writeup in Github issue #2473
