### ISSUE TITLE
[Upgrade d&d importing] Importing projects into StackBlitz

### ISSUE THREAD

**Issue by jcalderaio** [stackblitz/core#222]
I'm trying to import a current React project (that uses webpack) into StackBlitz. Do I just drag ALL of my files (including index.html with <script src="/bundle.js"></script>, webpack.config.js, and package.json)? Because I tried that and it didn't work.

**Comment by EricSimons** [comment]
@jcalderaio you just want to drag the source files themselves (i.e. index.js and all other files it imports). I'm rewriting our import logic though which will prompt you for how to handle the dropped files!
