### ISSUE TITLE
Angular github project dev deps mismatch

### ISSUE THREAD

**Issue by lukasmatta** [stackblitz/core#2223]
Hello,
it seems there is an issue with the angular dev dependencies. 

When one try to open stackblitz from the Angular's github - https://stackblitz.com/github/angular/angular/tree/main/aio/content/demos/first-app in the stackblitz `package.json` it shows version 11.0.4 for some angular dev deps, whereas in the `package.json` inside the Angular repo versions are 15.0.1. https://github.com/angular/angular/blob/main/aio/content/demos/first-app/package.json

**Comment by kc0tlh** [comment]
This issue has been resolved:

<img width="974" alt="image" src="https://github.com/stackblitz/core/assets/1532264/d13a019e-86b3-4d1b-bb84-edbe618e2a0d">
