### ISSUE TITLE
Format Document works only when reloading whole site. Not when creating new files.

### ISSUE THREAD

**Issue by zetti-caletti** [stackblitz/core#2225]

**Comment by fvsch** [comment]
Hi @zetti-caletti. In my tests the Format Document button does work for newly created files. Do you know about precise steps that can be used to reproduce your issue?

**Comment by zetti-caletti** [comment]
@fvsch Actually it was wrong. It works for newly created files but not for existing ones. Actually the whole formatting is really weird at me. Sometimes it works, sometimes not. Sometimes it only formats some lines. Can you tell me what settings I have to put in the settings.json to have a 4 spaces indentation? In my own VSCode I use editorconfig and there everything works. Also putted a .editorconfig file inside stackblitz, but doesn't work. Do I have to install a plugin?
Maybe you can help me. Thank you.
