### ISSUE TITLE
Stuck on "starting dev server"

### ISSUE THREAD

**Issue by noradroid** [stackblitz/core#2227]
Trying to load a ng-bootstrap demo but stuck on loading
![image](https://user-images.githubusercontent.com/75635291/208835926-1f2e58e0-68cb-4dc6-b933-6196df72907f.png)

This is the demo link address in question: https://ng-bootstrap.github.io/stackblitzes/toast/howto-global/stackblitz.html

Has been stuck in loading screen for the past 10 minutes.

**Comment by kc0tlh** [comment]
This issue is now resolved:

<img width="1439" alt="image" src="https://github.com/stackblitz/core/assets/1532264/27909ce1-1d3e-4a8f-8a38-e8c73facebb2">
