### ISSUE TITLE
bug fix

### ISSUE THREAD

**Issue by omprakash96** [stackblitz/core#2228]
Error in /turbo_modules/react@18.0.0/cjs/react.development.js (1625:21)
Cannot read properties of null (reading 'useRef')

**Comment by fvsch** [comment]
Hi @omprakash96.

Can you provide more information about your issue, especially:

1. a link to a StackBlitz project where this problem occurs
2. and ideally a description of how this project was created (from scratch, from one of our starter projects, or from a documentation example on another website?)

Thanks.

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information.
