### ISSUE TITLE
process.env (or other globals) support

### ISSUE THREAD

**Issue by Vanuan** [stackblitz/core#223]
Node, Webpack and React communities adopted the use  of `process.env` to setup build time variables.

Examples:

```
process.env.PUBLIC_URL = 'https://react-something.stackblitz.io'
process.env.NODE_ENV = 'production'
```

Is there a way to configure those automatically?

**Comment by Vanuan** [comment]
Current workaround:

```
// index.js
window.process = {
  env: {
    NODE_ENV: 'production',
    PUBLIC_URL: 'https://react-something.stackblitz.io'
  }
}
```

**Comment by EricSimons** [comment]
@Vanuan excellent point — I'm going to think about how we can implement this. How do you usually config the env object in your local projects btw?

**Comment by Vanuan** [comment]
Usually I use webpack.

**Comment by Vanuan** [comment]
Specifically DefinePlugin: https://webpack.js.org/plugins/define-plugin/

**Comment by Vanuan** [comment]
[Webpack's `-p` option](https://webpack.js.org/api/cli/) is an alias for 
```
--optimize-minimize --define process.env.NODE_ENV="production"
```

**Comment by xiaoqiang730730** [comment]
@EricSimons I also need it. I want to know, Whether my optimization can work in the "production" environment.

**Comment by EricSimons** [comment]
Process is actually now enabled for all projects! This has been online for a while, just forgot to circle back to this issue :)

Closing for now, but lmk if you run into any troubles 👍

**Comment by tugal** [comment]
Hi,
Not working on my side..

i have an .env file (ROOT)
- REACT_APP_NAME=Building XX

and "undefined" is displayed on my console...

**Comment by goleary** [comment]
@EricSimons I'd like to configure a sensitive env variable for use in a node (nextjs) project on stackblitz.

What's the best way to do this?

I can't find anything in the docs about providing env variables to the node environment.

**Comment by EricSimons** [comment]
@goleary you can set any env variables in the shell like normal when you execute the command/script. While in beta we don’t have any way to persist this across page loads though, so you’ll need to bring those secrets each time. Curious if you have any thoughts on ideal ways we could implement this!

**Comment by goleary** [comment]
I see, thanks!

This is where I initially looked to see if I could set them:
![image](https://user-images.githubusercontent.com/16123225/119439074-72348580-bcd6-11eb-85fb-a0c79780342a.png)

Perhaps an "Environment Config" section that enables setting env variables?

**Comment by beatfactor** [comment]
> @goleary you can set any env variables in the shell like normal when you execute the command/script. While in beta we don’t have any way to persist this across page loads though, so you’ll need to bring those secrets each time. Curious if you have any thoughts on ideal ways we could implement this!

Hey, I also need this feature and I think it's a very common request. Is there a way maybe to import secrets/environments from Github for the repository?

**Comment by diarmuidoconnor** [comment]
Hi,
Concerning the declaration of custom environment variables, I require to declare an API key value for a React app. When using the create-react-app tool on localhost, the typical solution is to use the .env file. This approach does not work on the template React app environment created by Stackblitz, which uses the EngineBlock model (as opposed to Web Container), as I understand it. 
When running on localhost, the keys declared in .env are accessed by a React component using the process.env object. This object is also present in the StackBlitz environment and has one default property, NODE_ENV. However, any variables declared in .env are not added to process.env. 

Has anyone come up with a workaround for this problem? Tks

**Comment by yusuf-kaleem** [comment]
why this issue is closed? do we have any solution for this ?

**Comment by rehanqasimk** [comment]
@EricSimons 

The issue doesn't seem to be resolve. Any idea ?

**Comment by devdavedotdev** [comment]
I use settings>variables, when i spin up my project, a .env file is auto populated with the key value, but usage in code does not work, 
'process is not defined'

**Comment by basarat** [comment]
Still doesn't work. 
This standart nextjs project works locally (see `.env` commited): https://github.com/basarat/course-nextjs/blob/main/lessons/static-site-generation_multiple/.env
But not in stackblitz: https://stackblitz.com/github/basarat/course-nextjs/tree/main/lessons/static-site-generation_multiple?file=src%2Fapp%2Fproduct%2F[name]%2Fpage.tsx (note that it fails to fetch the `.env` file from GitHub)
