### ISSUE TITLE
Github Integration Issue

### ISSUE THREAD

**Issue by johnaweiss** [stackblitz/core#2231]
i clicked the "x" next to one of the organizations listed in the github integrator. Instead of that item getting removed, i got a help file. When i closed the helpfile, instead of returning to the github integrator, the integrator closed, and the IDE displayed "Authorizing" apparently forever. 

![image](https://user-images.githubusercontent.com/53209681/209472899-61dae307-2d8c-412b-b25a-115948a374df.png)

![image](https://user-images.githubusercontent.com/53209681/209472930-6e1c42db-d118-46d0-83a7-19c915f71c09.png)

![image](https://user-images.githubusercontent.com/53209681/209472963-2f3a9b77-46fb-4246-802b-a5b25b0c5edf.png)

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
