### ISSUE TITLE
Additional entrypoints

### ISSUE THREAD

**Issue by Vanuan** [stackblitz/core#224]
It looks like by default StackBlitz loads index.js and bundles it into _sw_.js

Is it possible to configure additional entrypoints, e.g. for dynamic imports/code splitting?

**Comment by EricSimons** [comment]
@Vanuan we don't have this available (yet) - would love to hear more about your use case for this!

**Comment by Vanuan** [comment]
Another example is service workers:
https://developers.google.com/web/fundamentals/codelabs/debugging-service-workers/img/dabccb06c7231b3e.png

To register a service worker you must load it asynchronously.

**Comment by Vanuan** [comment]
Here's how you register it:
https://cdn-images-1.medium.com/max/1600/1*3dZ4MSZgeHorZSU546AfjA.jpeg

**Comment by Vanuan** [comment]
It looks like I have to comment out service worker registration in stackblitz environment. Is there a way to detect stackblitz apart from domain name?

**Comment by kc0tlh** [comment]
Multiple subdirectories & start scripts are now supported in [our new VS Code editor, available here](https://stackblitz.com/codeflow)!
