### ISSUE TITLE
Images from github do not load

### ISSUE THREAD

**Issue by codely-bcn** [stackblitz/core#2247]
Additionally, I try to upload images myself by drag-n-drop but they don't who up.
I paid for the membership because it said I could upload stuff but I can't see any option really...

**Comment by fvsch** [comment]
Hi @codely-bcn.

Sorry to hear that you're having issues with StackBlitz. Could you link to a StackBlitz project which shows the problems you're having, and give a bit more information:

1. Could you break down what you're trying to do in a few steps, and highlight where things are going wrong?
2. Do you mind sharing what operating system and browser(s) you are using?

**Comment by fvsch** [comment]
Hi @codely-bcn,

I'm closing this issue since it does not have actionable information currently.

If you're still having problems, feel free to create a new issue with a bit more information (as described above).
