### ISSUE TITLE
Forking from GitHub when signed in breaks

### ISSUE THREAD

**Issue by conshus** [stackblitz/core#2251]
### **Description of Bug**
Hi. When I'm signed into StackBlitz and click the "Open in StackBlitz" button in a GitHub repo that I'm working on / owner of, I get an error. (Please see screenshot).
When I'm not signed into StackBlitz and click the same button in the same GitHub repo, everything works fine. It loads the project properly.

### **Steps to Reproduce**
1. Go to https://github.com/opentok/web-components/tree/main/examples/vue
2. Click on "Open in StackBlitz" button in the ReadMe
3. Should point to https://stackblitz.com/fork/github/opentok/web-components/tree/main/examples/vue

When I'm signed into StackBlitz, I get an error, see screenshot.
When I'm not signed into StackBlitz, it works fine and loads the GitHub repo properly.

### **Expected Behavior**
To properly load the GitHub repo when I'm signed into StackBlitz as when I am not signed into StackBlitz.

### **Screenshots/Screencast**
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/212875/211657293-a63e4392-ff96-4ff7-8e2a-8977e799e996.png">

**Additional Context/Questions**
Not sure if the error has to do with me also working on/the owner of the GitHub Repo.

**Comment by skryukov** [comment]
Hey, @conshus thanks for the report, will fix this in coming days.

**Comment by skryukov** [comment]
Hey, @conshus! Stackblitz should now detect the problem and ask you to reauthenticate the token.

**Comment by conshus** [comment]
👍🏾 Looks like it works. Thanks @skryukov!
