### ISSUE TITLE
Running NGCC Doesn't Finish

### ISSUE THREAD

**Issue by eastcoastdeveloper** [stackblitz/core#2253]
Certainly not a big upgrade—just Angular 14 to 15. Have tried multiple times from different browsers, and it refuses to update : [
Haven't experienced this before. Any ideas?
Here's the url: https://stackblitz.com/edit/angular-dynamic-sidebar?file=README.md
Chrome, Safari, Brave, and AVG all behaved the same.

Thanks,
Eric

**Comment by mvdluit** [comment]
It appears to happen to every Angular stackblitz. Just tried to update dependencies of a newly created project from 15.0.4 to 15.1.0 and NGCC never finishes running.

**Comment by eastcoastdeveloper** [comment]
<img width="1148" alt="Screen Shot 2023-01-11 at 6 57 49 PM" src="https://user-images.githubusercontent.com/58962475/211965278-0d5bfa75-6154-47f9-a60f-1459d78bf567.png">

Have you seen this error?

**Comment by markwhitfeld** [comment]
Thank you for reporting this. We are looking into it.

**Comment by mvdluit** [comment]
Fyi, I was able to update my stackblitz templates to the latest version just now. cc. @eastcoastdeveloper

Thanks for looking into this issue @markwhitfeld

**Comment by eastcoastdeveloper** [comment]
Awesome. Thank you @markwhitfeld & @mvdluit!

**Comment by markwhitfeld** [comment]
Fix was released on Monday and there has been no recurrence.
This should be resolved now. Closing issue.

**Comment by eastcoastdeveloper** [comment]
Thanks so much for the update!
Unrelated, does Stackblitz have have plans to create an API containing views, forks, etc?
I'm using the numbers in various places on my site (growing rapidly) and need to update them manually.
