### ISSUE TITLE
Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by iKrishnaSahu** [stackblitz/core#2258]
### **Description of Bug**

Facing following issue in latest version of angular - `Cannot use 'import.meta' outside a module`
Seems like this issue is coming from web-container code
Application works fine when we run the same application in local.

```
Uncaught (in promise) SyntaxError: Cannot use 'import.meta' outside a module (at webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:5474)
    at eval (<anonymous>)
    at Qt (webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:30145)
    at webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:38799
    at U (webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:13565)
    at webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:13207
    at Object.eval (typescript.ts:43:25)
    at eval (typescript_translator.ts:33:1)
    at eval (typescript_translator.ts:33:1)
    at eval (<anonymous>)
    at Qt (webcontainer.bfee0704b2dee6f4f820d00343609f2869551d0f.js:15:30145)
```

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/angular-ivy-6qh2wm?file=package.json
2. Open console and see the error

### **Expected Behavior**
App should compile and run in stackblitz

### **Screenshots/Screencast**

<img width="953" alt="image" src="https://user-images.githubusercontent.com/34937515/212253128-8714f573-daab-4095-8061-71038d4e14ea.png">

**Comment by peterblazejewicz** [comment]
same, happens on new project when adding anything that install new dependency, or forked ones. For example try to add @ng-bootstrap/ng-bootstrap to new angular project. Thx!
(tested with NG 15.1)

**Comment by iKrishnaSahu** [comment]
Seems like this is fixed for public instance.
