### ISSUE TITLE
installing dependencies since yesterday

### ISSUE THREAD

**Issue by ghost** [stackblitz/core#2259]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/121100044/212330611-c06bfc3a-fe86-42a4-96f3-24ca70eaf7c4.png">

**Comment by markwhitfeld** [comment]
Most likely related to #2253 and #2265 .
Fix was released on Monday and there has been no recurrence.
This should be resolved now. Closing issue.
If it is something different then please reopen an issue with more details and a reproduction.
