### ISSUE TITLE
Angular Title Not Showing in Dashboard

### ISSUE THREAD

**Issue by eastcoastdeveloper** [stackblitz/core#2269]
Hello, Please see screenshot.
<img width="1223" alt="Screen Shot 2023-01-16 at 6 37 59 PM" src="https://user-images.githubusercontent.com/58962475/212797822-79fc6eea-12f7-41a7-9fa2-e83f2e6a95a2.png">

**Comment by fvsch** [comment]
Thanks a bunch for the report @eastcoastdeveloper!

Definitely a bug, we're going to revert the faulty change in a moment.

**Comment by fvsch** [comment]
We’re currently deploying a fix, should be live in a few minutes.
