### ISSUE TITLE
auto reload not working in html/css/js 

### ISSUE THREAD

**Issue by gitkrishnaa** [stackblitz/core#2274]
when i change or text somthing in stackblitz it get reloat to see the result but this time this is not working

**Comment by jmcooper** [comment]
I'm experiencing this as well. This was working not long ago. I've also tried multiple reload mechanisms/settings. This is on a vanilla Html5 app. Here is a sample blitz: https://stackblitz.com/edit/web-platform-7avjmk?file=index.html,script.js

**Comment by jmcooper** [comment]
I have written up a more complete bug report here: [Issue #2292](https://github.com/stackblitz/core/issues/2292).

**Comment by mrc2709** [comment]
The console.log is not working too.

**Comment by fvsch** [comment]
Hi @gitkrishnaa,

There was a regression that made its way to prod ~10 days ago, and we shipped a fix for that today. This feature should be working as usual now. Sorry for the inconvenience!
