### ISSUE TITLE
Help ! Firebase deploy is broken :(

### ISSUE THREAD

**Issue by El-Sio** [stackblitz/core#2275]
Since yesterday I was building and deploying my project to firebase with 0 issues, but now everytime I click on deplay, I end up with a broken version on Firebase, with 0 files and the live website has the following error : 

Uncaught SyntaxError: Unexpected token '<'
app.bundle.js?1674115174707:1 Uncaught ReferenceError: WebContainer is not defined
    at app.bundle.js?1674115174707:1:342689

And the source code of the app page looks like this 

<html><head>
  <script src="undefined"></script>
  <script src="/vendor.bundle.js?1674115174707"></script>
  <script src="/app.bundle.js?1674115174707"></script>
</head><body></body></html>

My project works fine on the dev server in Stackblitz.

I have tried logging off firebase and stackblitz, adding a package to force NGCC update, change code, nothing is working anymore :(

What changed ??

**Comment by fvsch** [comment]
Hi @El-Sio and thanks for the report!

So sorry that this bug slipped by us. We've shipped a fix for this issue today, and Firebase deploys should now work as before.
