### ISSUE TITLE
Using the project from GitHub public repo, Gives error after compiled, 

### ISSUE THREAD

**Issue by YashPindiwala** [stackblitz/core#2276]
Error: NG0908: In this configuration Angular requires Zone.js

**Comment by YashPindiwala** [comment]
Works perfectly fine on localhost

**Comment by fvsch** [comment]
Hi @YashPindiwala.

Could you give more information about your issue?

- Link to a StackBlitz project that shows your problem.
- Share other information that might be relevant: which browser(s) you're using, screenshots, etc.

Thanks.
