### ISSUE TITLE
developer server is not running

### ISSUE THREAD

**Issue by Bazil-cp** [stackblitz/core#2278]
all i can see isa white screen and the devolepment server is not running

**Comment by fvsch** [comment]
Hi @Bazil-cp.

Could you give more information about the problem you're facing?

- Could you give the URL of the StackBlitz project that you're trying out or working on?
- What browser(s) are you using?
- Could you share a screenshot?

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information.
