### ISSUE TITLE
Cannot load my repository from Github

### ISSUE THREAD

**Issue by leomayer** [stackblitz/core#2281]
Cannot load my repository from Github. It runs locally on my Eclipse IDE. 

https://stackblitz.com/github/leomayer/1korn-leo/

It is executed properly on my Github-Page:

https://leomayer.github.io/1korn-leo/

Any ideas why the import/load fails?

**Comment by HeyGarrison** [comment]
I'd recommend trying pr.new!

See docs here: https://developer.stackblitz.com/codeflow/using-pr-new#frontmatter-title
