### ISSUE TITLE
Cannot find my public repo

### ISSUE THREAD

**Issue by paradingwolves** [stackblitz/core#2285]
I am using this stackblitz link: https://stackblitz.com/github/paradingwolves/Jus_Brierley_WEB601Assignments_Baseball
I am trying to access this repo: https://github.com/paradingwolves/Jus_Brierley_WEB601Assignments_Baseball

My repo is public, stackblitz still won't recognize my repo

**Comment by paradingwolves** [comment]
I meant to delete my post as right after I posted this, I realized exactly what you had just told me. I appreciate the comment regardless:)

**Comment by fvsch** [comment]
Thanks for circling back!
