### ISSUE TITLE
'angular/platform-browser/animations';  not found

### ISSUE THREAD

**Issue by newschapmj1** [stackblitz/core#229]
Has bug 30 & 53 returned?
I'm a Angular newbie so I could be doing something sillly.

Editor highlights  '@angular/platform-browser/animations'; with error "cannot find module"

main.ts
import './polyfills';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import {BrowserModule} from '@angular/platform-browser';
**import {BrowserAnimationsModule} from '@angular/platform-browser/animations';**
import {NgModule} from '@angular/core';
import { AppModule } from './app/app.module';

**Comment by EricSimons** [comment]
If you use the browseranimationsmodule variable it should automatically install the subpackage- is it not working for you? If so, link to project would be 👍

**Comment by ChuiSauCE** [comment]
Update @angular/core and the rest youll be good to go

**Comment by thw0rted** [comment]
How was this ever working with `import {whatever} from ''`?  The right path, as I understand it, should be

    import { BrowserAnimationsModule } from "@angular/platform-browser/animations";

I can't get it to work either for some reason, and it's keeping me from making a demo of an animation bug I want to ask about on Angular's tracker...

**Comment by EricSimons** [comment]
This is just a UI bug on our end- once you actually use the `BrowserAnimationsModule` variable it will download the corresponding type definitions and remove the red underline. We're going to get a fix in for this tho, should be ready in a couple of weeks :)

**Comment by BryanWilhite** [comment]
yes, in addition to what @EricSimons is saying is the following workaround: set up the import for `BrowserAnimationsModule` and save; then reload the entire page: the red squiggly should go away

**Comment by BryanWilhite** [comment]
yeah, um, my previous workaround is not always working all of the time; now i'm back to this (with [a different animation project](https://stackblitz.com/edit/angular-rx-angular-firebase-com-animations-multi-state?file=src%2Fapp%2Fapp.module.ts)):

![image](https://user-images.githubusercontent.com/5226627/45120359-b2acd900-b112-11e8-8750-88617e6142e7.png)

![image](https://user-images.githubusercontent.com/5226627/45120401-d5d78880-b112-11e8-8afe-2c2da6f921ff.png)

but still works fine in [my first animation project](https://stackblitz.com/edit/angular-rx-angular-firebase-com-animations-pop-over?file=src%2Fapp%2Fapp.module.ts):

![image](https://user-images.githubusercontent.com/5226627/45120477-159e7000-b113-11e8-9945-16abb1a25208.png)

![image](https://user-images.githubusercontent.com/5226627/45120502-26e77c80-b113-11e8-9ab2-fb05e2d2c22f.png)
