### ISSUE TITLE
Error while Compiling application and starting dev server

### ISSUE THREAD

**Issue by kasual1** [stackblitz/core#2290]
https://stackblitz.com/edit/angular-ivy-wmhf3p?file=README.md

Compiling application and starting dev server takes forever and then crashes.

Console errors:
jsonWorker.js:7 Fetch API cannot load stackblitz:/node_modules/%40angular/cli/lib/config/schema.json. URL scheme "stackblitz" is not supported.
o @ jsonWorker.js:7
l.staticblitz.com/b/v1/angular-ivy-wmhf3p/92295f66e17:1          Failed to load resource: net::ERR_FAILED
l.staticblitz.com/b/v1/angular-ivy-wmhf3p/92295f66e17:1          Failed to load resource: net::ERR_FAILED
preview-b7cef1f2522ea.js:2 TypeError: Failed to fetch
    at Te (preview-b7cef1f2522ea.js:2:593112)
    at window._preboot (preview-b7cef1f2522ea.js:2:594338)
    at (index):9:11
(anonymous) @ preview-b7cef1f2522ea.js:2
preview-b7cef1f2522ea.js:2 Uncaught (in promise) Error: Error fetching cached project bundle for preview.
    at preview-b7cef1f2522ea.js:2:593345

**Comment by fvsch** [comment]
Hi @kasual1,

The project you linked to is not public or was moved or deleted. Are you still running into this issue, and do you have a visible project that you can share?

Any other information, such as web browsers you tried, is welcome. :)

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information.
