### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow'

### ISSUE THREAD

**Issue by dmitriy-tka4** [stackblitz/core#2291]
The page does not load to the end, an error in the console:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://web-platform-3za1vo.stackblitz.io') does not match the recipient window's origin ('https://stackblitz.com').

My draft:
https://stackblitz.com/edit/web-platform-3za1vo?file=index.html

**Comment by fvsch** [comment]
Hi @dmitriy-tka4, and thanks for the report.

The error message you quoted is a different known issue and shouldn't break your project.

Are you having this problem with a specific web browser? Testing your project, it worked well for me in Chrome, Firefox and Safari.

Note also that static HTML/CSS/JS projects rely on [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) being enabled in your browsers. Some browsers may disable Service Workers in Incognito/Private Browsing windows, or when turning on specific security and privacy settings.

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information.
