### ISSUE TITLE
Auto-Reload is Broken for Vanilla Static Projects

### ISSUE THREAD

**Issue by jmcooper** [stackblitz/core#2292]
### **Description of Bug**
When I create a new Project from the Vanilla -> Static template, auto-reload does not work regardless of what "Reload mechanism" or "Page reload trigger" I have selected. 

### **Steps to Reproduce**
See Stackblitz Project: https://stackblitz.com/edit/stackblitz-issue-2292?file=index.html

1. From the StackBlitz Dashboard, Click on "Vanilla" in the "Create a New Project" section
2. Click on Static (HTML/JS/CSS)
3. Change the text inside the `<h1>` in index.html 
4. Click Save
5. Notice that the embedded browser does not refresh. Refresh it manually to see your changs.

### **Expected Behavior**
Auto-refresh of the embedded browser should occur on edit or save.

### **Screenshots/Screencast**
![image](https://user-images.githubusercontent.com/1505427/214699505-8850dd6b-2893-4921-a92a-f753c2c858d7.png)

**Additional Context/Questions**
Here is a sample StackBlitz that is not working: https://stackblitz.com/edit/stackblitz-issue-2292?file=index.html

**Comment by fvsch** [comment]
Hi @jmcooper and thanks for the detailed report!

We shipped a fix on stackblitz.com a couple hours ago which should have fixed this issue. It works well in our tests, but could you take a look and check that it works well for you too?
