### ISSUE TITLE
Feature Request: Live collaboration for remote pairing

### ISSUE THREAD

**Issue by christemple** [stackblitz/core#23]
I really like this editor and think it has  a lot of potential to aid remote pairing.

The current screen sharing solutions are too heavy and slow (ScreenHero, Teamviewer), things like Tmate/Tmux isn't very user friendly.  This is a very frustrating problem that this app can solve.

**It would be great if this online IDE had similar live collaboration as Google Docs, Sheets etc.**

There would be no need for screen sharing at all if we could pair together and see each others cursors making live changes to the code, as well as seeing those changes live reloading.

I appreciate this is a big feature, one that I'd be happy to help with and also pay for.

Thought it'd be worth creating this issue just to see if there's more demand for this feature than just myself.  If you _need_ this, not just interested, give this a 👍 

Thanks for a great online IDE :)!

**Comment by facundomedica** [comment]
+1 to this. It would be **THE** code editor.

**Comment by EricSimons** [comment]
Check out @portstrom's comment in https://github.com/stackblitz/core/issues/22 — looks like great minds think alike! :)

I love love LOVE this idea. It's been a very consistent piece of feedback we're getting, so we're exploring what this might look like. Would love to bounce ideas off ya'll after we brainstorm internally this week/weekend :)

**Comment by ravihugo** [comment]
Our team would likely pay for a feature like this, primarily to do remote interviews. If there would be a way to have one member be a guest collaborator?

**Comment by yveslange** [comment]
Would be very cool to have when collaborating. I would love to use it while presenting stuff or doing a live coding presentation !

**Comment by salvoASK** [comment]
Very good idea!!!

**Comment by EricSimons** [comment]
Closing because https://github.com/stackblitz/core/issues/22 is identical- we're working on this feature! :)

**Comment by Davydx7** [comment]
few years later, Codesandbox has now implemented this

**Comment by timothyallyndrake** [comment]
This is very unfortunate. The marketing site led me to believe that I would be able to collaborate but it would seem as though this is Visual Studio Code within a Web browser. It is a really neat concept but I will need to go somewhere that supports this. Good luck!
