### ISSUE TITLE
Save an app snapshot to a separate URL

### ISSUE THREAD

**Issue by moniuch** [stackblitz/core#230]
It'd be awesome to be able to save a snapshot of an app state under a specific URL.
Especially when I run into an Angular problem and want to share my case study with someone else, but still be able to keep on fiddling around in a different "branch", so to speak. Pretty much what jsfiddle.net does when saving a fiddle.

**Comment by maxmarkus** [comment]
@moniuch I guess you can use the fork mechanism for your usecase. So you can use a fork as your "branch". And once one found a (partial) solution, you can fork his branch again.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
