### ISSUE TITLE
Vue and axios@1.2.6

### ISSUE THREAD

**Issue by benixal** [stackblitz/core#2303]
When I try to install axios for a vue app
It seems that there is a problem and this message appears
```
Can't find packages:
http ,https ,zlib ,events ,debug
```

And when I click on Install Missing Packages, another error occurs :

```
Error in turbo_modules/axios@1.2.6/lib/adapters/http.js
The entrypoint for 'https' could not successfully be resolved. The file '/turbo_modules/https@1.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.
```

At first, I thought that there is something wrong with axios@1.2.6, but when I installed axios@1.2.6 on a vue app on my computer, I did not see any problems

and also axios@0.27.2 and axios@0.21.0 does not have this problem with stackblitz

live DEMO : https://stackblitz.com/edit/vue-qtqkzc

**Comment by fvsch** [comment]
Hi @benixal.

It looks like `axios` or some other package is trying to use Node.js's built-in libraries, which are not npm packages and cannot be installed as npm packages.

The project you are running is using our EngineBlock runtime, which supports installing npm packages but not using Node.js or Node.js libraries. For that, you will want to use WebContainers, which do support Node.js libraries.

We have a few starter projects that use WebContainers and have Vue already set up:

- Vue + Vite: https://vite.new/vue
- Vue (with TypeScript) + Vite: https://vite.new/vue-ts
- Nuxt 3: https://stackblitz.com/fork/github/nuxt/starter/tree/v3-stackblitz

More info about EngineBlock and WebContainers differences:
https://developer.stackblitz.com/guides/user-guide/available-environments
