### ISSUE TITLE
Firebase deployment of Angular v15 app seems to be broken

### ISSUE THREAD

**Issue by mczul** [stackblitz/core#2304]
The DevTools show errors after deployment of an Angular app (even with your unmodified project stub):

<img width="727" alt="image" src="https://user-images.githubusercontent.com/8385209/215475427-e6957fdc-3ef1-48c7-9054-34c62eb55c88.png">

<img width="420" alt="image" src="https://user-images.githubusercontent.com/8385209/215475601-f0b16f11-599e-4672-b640-9d8118475c8e.png">

**Comment by mczul** [comment]
Seems to be a duplicate of https://github.com/stackblitz/core/issues/2275

**Comment by fvsch** [comment]
Hi @mczul and thanks for the report!

We shipped a fix for this issue a couple hours ago, and it should now work as before.

Our apologies for the inconvenience.

**Comment by mczul** [comment]
Thanks for the excellent support!
