### ISSUE TITLE
Angular (Standalone) project indefinite loading

### ISSUE THREAD

**Issue by yongshun950824** [stackblitz/core#2306]
When I try to import some modules and add some code, the project keeps loading and never ends. 

[Sample](https://stackblitz.com/edit/angular-h6sr4d?file=src/main.ts)

Checked the browser console, and it seems something is broken:

![image](https://user-images.githubusercontent.com/29250581/215623695-83afd946-2158-4f00-9b93-324db589439c.png)

Please assist the issue.

Thank you in advance.

**Comment by fvsch** [comment]
Hi @yongshun950824,

This project seems to be working now. It looks like it was trying to use a npm package that had just been published to the npm registry a couple hours earlier, and my guess is that our proxy hadn't managed to pick up that package version yet.

Can you confirm if it works for you?

**Comment by yongshun950824** [comment]
Hi @fvsch, thanks for assisting. Now it works. I close this issue as solved.

Thank you.
