### ISSUE TITLE
Css not responding

### ISSUE THREAD

**Issue by kodeddy** [stackblitz/core#2309]
It doesn't recognise my css file. I've gotten the file path correctly, but it doesn't pick it up. The code works fine on my laptop, but on stackblitz  it doesn't.

**Comment by consman** [comment]
A related problem may be that not all changes to CSS are rendering in the UI pane ( like removing styles for an element). I changed div to span on line 23 of main.ts in [this project]( https://stackblitz.com/edit/at-css-animation?ck_subscriber_id=1985435216 ) but the div still has the property.
