### ISSUE TITLE
Some recommendation

### ISSUE THREAD

**Issue by nzhtrtlc** [stackblitz/core#231]
First of all, this project is the best online react,angular,ionic editor i ever seen. Thanks for that.

### Recommendations
1 - Optinal hot reloading
2 - Highlight updates (just like react dev-tools able to do it)
3 - Allow multiple tabs on code editor.

**Comment by sulco** [comment]
Thanks! 
Since we don't plan to interfere with the running applications you build, updates highlighting are outside of the scope of the platform.

On the bright side we already support the point 1. and 3. :)
