### ISSUE TITLE
Error in turbo_modules/axios@1.3.1/lib/adapters/http.js

### ISSUE THREAD

**Issue by kpripper** [stackblitz/core#2312]
Just installed the dependencies

Error in turbo_modules/axios@1.3.1/lib/adapters/http.js
The entrypoint for 'https' could not successfully be resolved. The file '/turbo_modules/https@1.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

https://stackblitz.com/edit/js-uj1tu2?file=index.js

**Comment by luisjunco** [comment]
Seems to be an issue when installing axios v.1.x on stackblitz.

I've created this issue with further details: #2463 .

While this is fixed, you can uninstall axios + install any version prior to v.1 (ex, `axios@0.27.2`).

Example: https://stackblitz.com/edit/js-vwnfdg?file=index.js

**Comment by meeowngit** [comment]
Thanks @luisjunco it solves my issue! 

I was also facing the same issue :(

**Comment by kartikgupta321** [comment]
thank you solved the issue
