### ISSUE TITLE
*minor: window resized instantly when editor hidden results in single column editor text

### ISSUE THREAD

**Issue by mattdanielmurphy** [stackblitz/core#232]
![screen shot of the issue](https://user-images.githubusercontent.com/18738486/34732002-ee7f5cb6-f531-11e7-9eb6-87cde864cf13.png)

The issue occurs when the window is resized instantly using a window manager (am using Magnet.app for MacOS) from a width which hides the editor pane to a width which reveals the editor pane.

The issue is corrected when the window is manually resized; The issue does not occur if the editor pane is shown before instantly resizing the window.

**Comment by sulco** [comment]
Thanks for submitting this issue!
Closing since it doesn't seem to appear anymore, but feel free to reopen if you stumble upon it again.
