### ISSUE TITLE
React app not showing preview

### ISSUE THREAD

**Issue by Anami01** [stackblitz/core#2340]
I have created a new react app, but it is not showing any output in the preview pane. But when I open it in the new browser window, it is showing output as expected. I don't know what's the issues over here.

**Comment by kc0tlh** [comment]
@Anami01 please make sure [your browser is configured properly with 3rd party cookies enabled](https://developer.stackblitz.com/platform/webcontainers/browser-config) and ad-blockers disabled (as described in issue #162) and test your project on a different browser.

If you are still experiencing this issue, please share a link to your project, what browser/version you are on, and I will re-open this issue for further investigation!
