### ISSUE TITLE
It is not possible to view folders whose name begins with a dot

### ISSUE THREAD

**Issue by zharinov-nikita** [stackblitz/core#2342]
I have a package for npm that creates a folder when the `npx create-snippet --init` `.create-snippet` command is called. The folder is being created, but I don't see it. The folder is created using nodejs.

<img width="940" alt="Screenshot_1" src="https://user-images.githubusercontent.com/101789452/219290106-9ff9d265-88d8-40b4-9ec7-4c8a278d4e65.png">

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)!
