### ISSUE TITLE
Reactive Form giving error: jit_nodeValue_4(...).$any is not a function

### ISSUE THREAD

**Issue by expert26111** [stackblitz/core#235]
Thanks for the awesome tool but I got a strange bug.  

Here is the stackBlitz to reproduce. 

https://stackblitz.com/edit/angular-jfthqk

Browser : Chrome on Windows 10
I tried to reproduce the issue with angular/cli and got no error there.

**Comment by EricSimons** [comment]
I just bumped all deps to latest versions and that fixed the problem - looks like it's something on the framework side 🤔 Closing issue for now but lmk if that doesn't work on your end!
