### ISSUE TITLE
/github URLs with . in the name do not load

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/core#2350]
I tried to load: https://stackblitz.com/github/emberjs/ember.js
but the screen was _just white_ / empty?

**Comment by NullVoxPopuli** [comment]
This got the page loaded: https://stackblitz.com/github/emberjs/ember%2Ejs

probably because `.` has meaning in URLs 🙃 (file extension / format / etc)

**Comment by fvsch** [comment]
Hi @NullVoxPopuli. Thanks for the report! Looks like we have a routing issue. We're going to ship a fix for that today.

**Comment by fvsch** [comment]
This is now fixed on stackblitz.com.
