### ISSUE TITLE
Unable to Delete Forked Project

### ISSUE THREAD

**Issue by manthanank** [stackblitz/core#2352]
No delete button to forked projects

**Comment by fvsch** [comment]
Hi @manthanank,

Could you describe your issue a bit more?

- Were you logged in to StackBlitz when forking a project?
- What steps did you follow to fork a project?
- Any screenshot you can share?

**Comment by manthanank** [comment]
![image](https://user-images.githubusercontent.com/50883320/220319486-2e4b0d67-338d-4db6-bc72-bad9c26a76ef.png)
Forked Repo⤴️ 
- It has no delete button.

**Comment by manthanank** [comment]
![image](https://user-images.githubusercontent.com/50883320/220319821-791318d3-7636-4d41-8c66-4d0540584e3f.png)
Under project setting there delete button
