### ISSUE TITLE
2fa not worked properly

### ISSUE THREAD

**Issue by muhammad-muneeb-qenta** [stackblitz/core#2353]
few days ago i use this implementation it worked fine but now its not worked correctly as 1 scan QR code it give different code then get Code from the secret key

**Comment by fvsch** [comment]
Hi @muhammad-muneeb-qenta,

We don't offer 2FA authentification on StackBlitz directly. Currently we only offer authentification with GitHub accounts. You can add 2FA on your GitHub account directly, but that's not handled by StackBlitz.

Is there a specific feature of StackBlitz you were referring to? Can you share the relevant web page's URL, and/or a screenshot (if they don’t contain private information)?

**Comment by fvsch** [comment]
Closing this issue since it does not have actionable information.
