### ISSUE TITLE
BUG: Can't change branch of repo from master to main

### ISSUE THREAD

**Issue by bdombro** [stackblitz/core#2355]
**Describe the bug**

**Link to the blitz that caused the error**
https://stackblitz.com/edit/http-server-m8vf6v

**To Reproduce**
1. Go to 'editor'
2. Click on 'repo select'
3. Scroll down to 'main'
4. See that nothing happens

**Expected behavior**
The selector should change to 'main', and the files should switch to that branch

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 62182718,
  usedJSHeapSize: 57563038,
  jsHeapSizeLimit: 4294705152
}
```

**Additional context**

**Comment by kc0tlh** [comment]
@bdombro and @jimbuck, this issue is now resolved! Full writeup in Github issue #2473
