### ISSUE TITLE
StackblitzFsGit statusList err ResolveRefError: Could not resolve reference "refs/heads/master".

### ISSUE THREAD

**Issue by masx200** [stackblitz/core#2356]
### Describe the bug
```
ResolveRefError: Could not resolve reference "master".
GitWorkerService: cloned https://github.com/masx200/nextjs-masx200-home.git master
StackblitzFsGit addAll err ResolveRefError: Could not resolve reference "refs/heads/master".
StackblitzFsGit statusList err ResolveRefError: Could not resolve reference "refs/heads/master".
Uncaught (in promise) 
T
a: null
code: "auth/network-request-failed"
message: "A network error (such as timeout, interrupted connection or unreachable host) has occurred."
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-l44aph

### Steps to reproduce

import github Repository
https://github.com/masx200/nextjs-masx200-home/

This repository does not have a "master" branch. It only has a "main" branch.

### Expected behavior

There should be no errors.

### Screenshots

![image](https://user-images.githubusercontent.com/34191203/129843984-f698badc-96d8-45ef-9d59-ac896efd30a4.png)
![image](https://user-images.githubusercontent.com/34191203/129844080-1cb2f1a5-e894-471f-8d45-6acd1bd2c12d.png)

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.73
performance.memory = {
  "totalJSHeapSize": 48599937,
  "usedJSHeapSize": 45783917,
  "jsHeapSizeLimit": 2172649472
}
Hash = f91df8ee833f18bedf806af681eeaccd3addac72
```

**Comment by HeyGarrison** [comment]
Based on https://github.com/stackblitz/webcontainer-core/issues/195 it looks like this issue is resolved!
