### ISSUE TITLE
Change default branch name, from master to main

### ISSUE THREAD

**Issue by mishrasatyam** [stackblitz/core#2357]
### Describe the bug

If I import an existing github repository, stackblitz tries to import master branch, instead of main branch.

Ideally you should make me choose from my branches.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-8hpys9

### Steps to reproduce

1.Go to stackblitz.com
2.Start a new node js project
3. Try importing a repo

### Expected behavior

Give me option to choose branch , instead of defaulting to master branch

### Platform

```
Browser name  = Chrome 
Full version  = 93.0.4577.82
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 70923140,
  "usedJSHeapSize": 58372484,
  "jsHeapSizeLimit": 2172649472
}
Hash = fa2fa735bbb029186c23972eb56445ed5c5fdef5
```

**Comment by HeyGarrison** [comment]
Looks like this is a duplicate of https://github.com/stackblitz/webcontainer-core/issues/195.
