### ISSUE TITLE
I have to fork to run changed code

### ISSUE THREAD

**Issue by codergautam** [stackblitz/core#2358]
### Describe the bug

I have a github repo connected to a nodejs stackblitz project. When I change some code in stackblitz and try to run in WebContainer, it runs the previous code before the change. I have to press fork and reconnect my github repo for the changes to work. Help how do I make it so that it runs the latest code.  

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-xv6zt6-neumwt?file=dist%2Fmain.js

### Steps to reproduce

1. Open stackblitz
2. connect a existing github repo
3. change some code
4. run it
5. It will run the old code

### Expected behavior

It runs the code that is currently on the stackblitz

### Platform

```
Browser name  = Chrome 
Full version  = 93.0.4577.107
Major version = 93
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; CrOS x86_64 14092.77.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.107 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 142372096,
  "usedJSHeapSize": 103951744,
  "jsHeapSizeLimit": 2031878144
}
Hash = eb19bc088249a645473767848622a1d98c51b8f3
```

**Comment by HeyGarrison** [comment]
👋 Heya - over the past few years our platform has changed a lot. Specifically, we launched a new git integration, which you can check out here: https://developer.stackblitz.com/codeflow/using-pr-new#frontmatter-title

I think that should resolve this problem!
