### ISSUE TITLE
Project forgets that it has an associated Github repo, losing my work because I can't push my changes

### ISSUE THREAD

**Issue by scott-cornwell** [stackblitz/core#2363]
### Describe the bug

If I am working in a project for a few hours, it will suddenly say it's not connected to a repo when I go to the Source Control tab. I'm not able to find any way to push my changes when this happens. I have to reload the page, resulting in the loss of all of my work.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/scott-cornwell/grid-core-solid

### Steps to reproduce

Make changes to a project, then stay in that project for several hours (not sure of exact timing/regularity). The source control tab will stop showing changes and say you need to initialize a repo (when you have already done so and made commits). It will come back when you refresh the page, but you have lost all your changes.

### Expected behavior

Your project should remain connected to the repo at all times and allow you to push your work, changes branches, etc... without having to refresh the page to get it to reconnect (losing all of your work).

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 3f0da22fd4d64ee969b596d789da2142b5d54de9
WebContainer = 79ba5d6ed4650f43d3d2f1721ce6e5bef04fff66

Browser name  = Chrome
Full version  = 107.0.0.0
Major version = 107
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87196713,
  "usedJSHeapSize": 78775873,
  "jsHeapSizeLimit": 4294705152
}
```

### Additional context

This is not applicable when running on my local as it's a specific feature with the Github integration on Stackblitz. Please tell me if there is any workaround for this, to get it to reconnect without refreshing the page. It would be great if this was just fixed though, I'm afraid to use Stackblitz now because I've lost so much work, but other than this bug it's been pretty great.

**Comment by HeyGarrison** [comment]
👋 

Over the past year we've shipped a ton of improvements to StackBlitz. It looks like this issue is solved by our next gen git integration. Read more about how to use that here: https://developer.stackblitz.com/codeflow/using-pr-new#frontmatter-title

Thanks for the issue!
