### ISSUE TITLE
API to add resources

### ISSUE THREAD

**Issue by jnizet** [stackblitz/core#237]
I'm trying to generate examples in StackBlitz for ng-bootstrap, in a way similar to the one used by the angular material documentation (see https://material.angular.io/components/datepicker/examples for example, which has links "Edit in StackBlitz"), using a form submitting to `https://run.stackblitz.com/api/angular/v1/`

I have no problem adding tags, description and files, but I have no idea how to generate an external resource (to the bootstrap css). How to do that? Is this API documented somewhere?

Additional request: Why are the images in https://stackblitz.com/angular/kbpdmobvaom?file=app/carousel-basic.html not loaded?

**Comment by jnizet** [comment]
Followup question: Is [this logo](https://pbs.twimg.com/profile_images/915330961558179842/cJXxqfah.jpg) freely usable as an icon to link to StackBlitz, or is there any other/better icon that is free to use, as an icon on a white background?

**Comment by EricSimons** [comment]
@jnizet awesome to hear! I would link to the bootstrap CSS file on a cdn in the index.html as you normally would. You can also do `@import '~bootstrap/dist/bootstrap.css'` (or or whatever the right path is) in styles.css but you'd need the bootstrap package to be installed w/ the project, so the former is prob easier.

Regarding the images - they redirect to http URLs, and the preview domains are on HTTPS. If you pop open your console you should be able see the requests getting dropped because of it

**Comment by jnizet** [comment]
Thanks for the reply @EricSimons 

I tried to link to the CDN directly in index.html, but AFAIK, there is no way to add this link in the head, and adding it in the body causes issues (that I can't explained), because the styles generated by angular seem to come before the default bootstrap styles. 

See https://stackblitz.com/angular/byapgnmvndd?file=index.html for example, where clicking on the button at the right of the text box doesn't work as expected. Whereas the same example, where the CSS is referenced using an external resource works as expected: https://stackblitz.com/edit/angular-khdu6j?file=index.html.

Regarding the use of an import in the styles.css, I tried that too, and miserably failed. See https://stackblitz.com/edit/angular-w1ohxz?file=styles.css

If you can help, that would be awesome. BTW even if one the other two techniques work, I still would like to know how to use the API to create an external resource: out of curiosity, first, and also because our plnkr examples use an external resource, and using the same technique in StackBlitz could be desirable.

An answer regarding the usability of the logo would be welcome, too.

**Comment by EricSimons** [comment]
@jnizet sorry about my delay here! It looks like you were both importing the CSS file and including it in the index.html — if you remove the HTML css link, it seems to work: https://stackblitz.com/edit/angular-w1ohxz-pnscdf?file=styles.css

Regarding the image, for sure! Feel free to use any of our image assets. Perhaps [this one](https://github.com/gothinkster/realworld/raw/master/media/edit_on_blitz.png?raw=true) might of interest? I've also attached a PNG of our logo here:


![blitz_mod_logo](https://user-images.githubusercontent.com/556934/35019940-752bf8da-fade-11e7-95fd-4b5e9ac2e6b1.png)

**Comment by jnizet** [comment]
Oh right. Thanks. I would still prefer using an external resource, because we have a hard time already explaining that jQuery and popper.js are not needed and shouldn't be used with ng-bootstrap, since it's a complete replacement of the bootstrap JavaScript that doesn't rely on jQuery, but StackBlitz forces us to install those unneeded peer dependencies. It would also be aligned with our plunkr examples.

Regarding the logo, thank you. I tried using the attached PNG, but when reduced to the size of an icon (24x24), the inner white lightning becomes invisible and all we see is the blue brackets, making the icon look weird. So I'll try using the one on a gray background.

**Comment by gyoshev** [comment]
I am hitting exactly the same problem with the Kendo UI for Angular demos. We use some of the bootstrap CSS in the demos, but none of the JS. Adding the `bootstrap` module requires `jquery` and `popper.js` peer dependencies, which sends the wrong message that the components use jQuery.

Alas, including the CSS files in the `index.html` places them after the bundled scripts, and this appears to delay their loading until after the application is rendered.

It would be very convenient if the bundled assets are inserted at the end of the `<head>` element, or if external dependencies can be specified through the post API.

**Comment by EricSimons** [comment]
@gyoshev I actually just pushed an update for this yesterday where all script/link tags in your index.html's head tag will get loaded before the rest of the application! Can you try using that and lmk if it works for you?

**Comment by gyoshev** [comment]
@EricSimons hm, for some reason it does not do it. Here is an application that [places the styles in the `index.html`](https://stackblitz.com/edit/angular-tvljcf?file=index.html) and one that [imports the styles in `styles.css`](https://stackblitz.com/edit/angular-krzgh2?file=styles.css). I want to prevent the flash of unstyled content -- I guess that it happens because of the order of the scripts and stylesheets in the rendered page.

**Comment by EricSimons** [comment]
@gyoshev good catch- I just fixed proper asset load order for stylesheets in the head tag! Your first link is now working properly for me, lmk if all looks good on your end too 🍻

**Comment by gyoshev** [comment]
@EricSimons works beautifully, thanks for resolving it so fast! 🏃 💨

**Comment by baolocdo** [comment]
How about having images? I got into similar problem when trying to reference an image with the src to an external URL. Please help. Thanks

**Comment by dammiepaul** [comment]
Hi Eric,

I'm currently working on a basic angular app for encrypting and decrypting text. See https://stackblitz.com/edit/encrypt-decrypt-app.

I added crypto-js as an npm package but I don't know how to import and use it in my AppComponent file.

Please help me.

Thanks.

**Comment by purplem1lk** [comment]
Resolution is provided by @EricSimons above so this issue will be closed accordingly. f this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
