### ISSUE TITLE
Fork buttons is too close to Save

### ISSUE THREAD

**Issue by csayers112** [stackblitz/core#2379]
### Describe the bug

When I am moving fast, I have continuously hit the Fork button, when I'm trying to hit the save button. It would be great if there wasn't such an important button next to save that changes the project your working on and forces you to pause and fix the Fork issue. This is something that's happened multiple times, so I think it's something that not only myself has struggled with. 

I think you could either move the share button next to Save, since that action isn't as destructive. Or, add a prompt to confirm that you want to Fork your project. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/quasarframework-owcs7c?file=README.md

### Steps to reproduce

1. Want to save your project
2. quickly move your mouse to the actions in the upper left
3. aim for the save button
4. you click the fork button instead
5. ugh...

### Expected behavior

I can save my project without forking it. 

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 110.0.0.0
Major version = 110
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 130900066,
  "usedJSHeapSize": 115814226,
  "jsHeapSizeLimit": 4294705152
}
Hash = ef7f0d70f39ab5f9fc227428923cdc2c94d52fe4
```

**Comment by HeyGarrison** [comment]
👋 thanks for the input! We'll definitely take this into consideration in our next series of releases.
