### ISSUE TITLE
The file menu stopped responding on dragging a file

### ISSUE THREAD

**Issue by tobiadiks** [stackblitz/core#2380]
### Describe the bug

On creating an empty javascript file in a subfolder, while i tried moving it,the menu stopped responding.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nextjs-u1jtmy?file=pages%2Fcomponents%2FPriceCard%2FPriceCard.js

### Steps to reproduce

1. create a subfolder 'a'
2. add an inner subfolder in 'a' called 'b'
3. create an empty javascript file in 'b'
4. drag the new file into 'a'

### Expected behavior

The file menu stops responding on any clicks

### Parity with Local

- [X] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 86.0.4240.198
Major version = 86
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.400
performance.memory = {
  "totalJSHeapSize": 87000123,
  "usedJSHeapSize": 81362875,
  "jsHeapSizeLimit": 2086404096
}
Hash = d4ed89204e54de5c40d109298317e6dc4d60aef7
```

**Comment by HeyGarrison** [comment]
👋 - Over the past few years our platform has changed a lot. We've been shipping like crazy. Thankfully, it looks like those efforts have fixed this issue! Feel free to open up a new issue if anything else comes up!
