### ISSUE TITLE
Switching to another branch hangs

### ISSUE THREAD

**Issue by perpetual-education-personal** [stackblitz/core#2382]
### Describe the bug

When we switch from `main` to `stackblitz` branch, it never loads.

We've had other projects that switched smoothly.

https://stackblitz.com/edit/vitejs-vite-zogxkh (doesn't switch)

https://stackblitz.com/edit/vitejs-vite-x5m55p (switches)

Tried on Chrome, FireFox, and Chrome Canary

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-zogxkh?file=README.md

### Steps to reproduce

1. Go to project
2. Switch branch
3. (doesn't load)

### Expected behavior

We expect the branch to change.

(Sidenote: we also expect to be able to link to that branch, or send a link to the stackblitz with that branch active and also embed a stackblitz with the chosen branch)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="370" alt="CleanShot 2023-02-23 at 20 36 45@2x" src="https://user-images.githubusercontent.com/56655339/221093180-39875f71-5f21-46ec-a478-8be5bf496c22.png">

### Platform

```
Browser name  = Chrome
Full version  = 112.0.0.0
Major version = 112
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 62178142,
  "usedJSHeapSize": 59551842,
  "jsHeapSizeLimit": 4294705152
}
Hash = ef7f0d70f39ab5f9fc227428923cdc2c94d52fe4
```

**Comment by HeyGarrison** [comment]
👋 Hey there!

I'd recommend using pr.new instead of our classic editor git integration (we actually just migrated all of this functionality to our next gen editor. Here is a docs page for you: https://developer.stackblitz.com/codeflow/using-pr-new

Hope that helps!
