### ISSUE TITLE
GitHub pull crashes with 'alert is not defined' popup

### ISSUE THREAD

**Issue by SteveALee** [stackblitz/core#2383]
### Describe the bug

I've hit a problem with the GitHub integration when I pull having added a file to the repo. I just get an "alert is not defined" error. And the new file does NOT appear in the file list.

Is there a way to get some visibility on the problem?

### Link to the blitz that caused the error

https://stackblitz.com/edit/opendir-audio-test

### Steps to reproduce

1. create project
2. create a new repo using the stackblitz integration (didn't let me select my organisation)
3 Add a file to the repo (GitHub web app drag n drop)
4. try to pull using the little icon

### Expected behavior

New file added to the repo appears in the file list

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/618922/159337719-29f9753c-cd3f-4f39-865b-0c149e672622.png)

### Platform

- OS: windows 11
- Browser: Chrome
- Version: Version 99.0.4844.74 (Official Build) (64-bit)

### Additional context

Just exploring StackBlitz but it rocks!!

I had to chec k"I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue. * But I did not

**Comment by kc0tlh** [comment]
This issue should be resolved in our [new VS Code editor](https://stackblitz.com/codeflow)! Full writeup in Github issue #2473
