### ISSUE TITLE
web-platform automatic refresh error

### ISSUE THREAD

**Issue by Invecticus** [stackblitz/core#2385]
### **Description of Bug**
When editing any file on the Pure HTML / CSS / JS. It does not automatically refresh and it gives this error in the console: Uncaught TypeError: window.WebContainer is not a constructor.

### **Steps to Reproduce**

1. Go to 'https://stackblitz.com/fork/web-platform'
2. Edit any of the files in the file list.
3. Page does not automatically refresh, when any edit has been made to any of the files.

### **Expected Behavior**
The preview page on the right should automatically refresh but it is not.

**Comment by 0xMoad** [comment]
Have the same problem

**Comment by fvsch** [comment]
Thanks for reporting this @Invecticus. We’re looking into it.

**Comment by fvsch** [comment]
We have a fix in review, it should go live later today. Will keep you posted.

**Comment by fvsch** [comment]
Hi all. This is now fixed on https://stackblitz.com.

Sorry for the disturbance, and thanks again for the reports.

**Comment by Invecticus** [comment]
> Hi all. This is now fixed on https://stackblitz.com.
> 
> Sorry for the disturbance, and thanks again for the reports.

I can confirm that this has been fixed. It is working correctly now.
