### ISSUE TITLE
Unable to fork. Because of long title. No message shown.

### ISSUE THREAD

**Issue by AhsanAyaz** [stackblitz/core#2397]
### Describe the bug

When trying to fork the [Stackblitz example of Angular Material](https://stackblitz.com/run?file=src/app/tooltip-auto-hide-example.ts). The fork button spins for a while then stops without any error. 
I can see in the network request that this is the response we get:
```json
{"errors":{"title":["is too long (maximum is 100 characters)"]}}
```

And there's no way to specify title while forking. So there's no way around it.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src%2Fapp%2Ftooltip-auto-hide-example.html

### Steps to reproduce

1. Go to https://stackblitz.com/run?file=src%2Fapp%2Ftooltip-auto-hide-example.html
2. Click the Fork button

### Expected behavior

We should be able to fork such repositories.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9844254/162744001-6b926f58-d43e-49a6-8d7f-11707c4e6601.png">

### Platform

```
Browser name  = Chrome
Full version  = 100.0.4896.75
Major version = 100
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 98618173,
  "usedJSHeapSize": 93812537,
  "jsHeapSizeLimit": 4294705152
}
Hash = 31afbfcfe1b0985e8cbdb27d44e16766166a118e
```

**Comment by HeyGarrison** [comment]
👋 

I tried to click these links to reproduce this, but I wasn't able to end up reproducing it. Our platform has changed a lot over the past few years so I'm also hoping this was resolved one way or another. Would definitely appreciate more info if it's still an issue.

Thanks!

**Comment by msmallest** [comment]
Reproduction:
~~https://stackblitz.com/edit/stackblitz-starters-nbicus?file=src%2Fmain.ts~~

edit: this one now, ironically I had to fork the previous one properly and managed to do so after renaming some stuff, but I made this new one to be breakable
https://stackblitz.com/edit/stackblitz-starters-v37hcn?file=src%2Fmain.ts

Tried forking a project from a different account of mine, getting this in the console.

>Uncaught (in promise) Error: {"errors":{"title":["is too long (maximum is 100 characters)"]}}
    at b.<anonymous> (client-8fb1f2410619a.js:2:1296328)
    at t.emit (client-8fb1f2410619a.js:2:474265)
    at t.onreadystatechange (client-8fb1f2410619a.js:2:1300170)
    at XMLHttpRequest.nrWrapper (VM18 stackblitz-starters-nbicus:2:17817)

**Comment by andreww2012** [comment]
Hello, this issue can still be observed. If you fork a project with a name that would exceed 100 characters limit if ` (duplicated)` is appended (which is what exactly happens when you fork) this error happens silently.
