### ISSUE TITLE
Support require statements

### ISSUE THREAD

**Issue by kenyk7** [stackblitz/core#24]

**Comment by EricSimons** [comment]
Right now we only support the ES6 spec, but I'll add in require support (shouldn't be too difficult)

**Comment by allenhwkim** [comment]
Year later, waiting for this feature :)

**Comment by bcherny** [comment]
It would be incredibly useful to have this feature, so that I can add Playground links for people browsing the Undux docs in ES5 mode - https://undux.org/#quick-start.

**Comment by EricSimons** [comment]
This shipped a while back! 👍
