### ISSUE TITLE
BUG: Importing project from Git failed at booting WebContainer

### ISSUE THREAD

**Issue by EmmyMay** [stackblitz/core#2403]
---
name: Bug report
about: Create a report to help us improve
title: 'Spinner Issue when existing repo is imported from GitHub'
labels: ''
assignees: ''

---

**Describe the bug**
When I tried importing an existing repository into a 'node' project, the spinner wouldn't stop spinning even after the repo files had been imported. 
The repository was a Vue project.
**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-t6wlbv?file=src%2Fmain.js

**To Reproduce**
1. Go to 'connect repository'
2. Click on 'import existing repository'
3. See error

**Expected behavior**
Repository is expected to be imported and the spinner is expected to stop.

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Screenshots**
![image](https://user-images.githubusercontent.com/31524469/119065062-a48f6b80-b9d4-11eb-82f1-61dc47226243.png)

**Desktop (please complete the following information):**
Browser name  = Edge
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.62
performance.memory = {
  totalJSHeapSize: 93067694,
  usedJSHeapSize: 88421094,
  jsHeapSizeLimit: 2172649472
}

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473
