### ISSUE TITLE
All local changes lost

### ISSUE THREAD

**Issue by Aftabnack** [stackblitz/core#2411]
I have a stackblitz env where I had made a lot of changes.
But when I refreshed the URL all changes were lost completely.

Here's the stackblitz URL: https://stackblitz.com/edit/react-ts-jfsrh9

This one was linked to a github project. But I had not yet committed the changes.

**Comment by HeyGarrison** [comment]
@Aftabnack I hate to hear that you lost your changes... Sorry about that!

Unfortunately, if your changes weren't saved / committed then they are indeed lost. So sorry about that.
