### ISSUE TITLE
_gitignore should be .gitignore

### ISSUE THREAD

**Issue by Rolanddoda** [stackblitz/core#2412]
### Describe the bug

I created a new Vite Vue 3 project. Without changing anything, I downloaded the project, unzipped it, and opened it in my IDE.

I ran git init and then I saw that folders and files are not gitignored.
And that was because the file name has an underscore instead of a dot.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-laxgwz?file=index.html&terminal=dev

### Steps to reproduce

1. Create a new project
2. See the gitignore file being `_gitignore` instead of `.gitignore`

### Expected behavior

gitignore file name should be `.gitignore`.

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.110
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 OPR/82.0.4227.43
performance.memory = {
  "totalJSHeapSize": 194611804,
  "usedJSHeapSize": 170876576,
  "jsHeapSizeLimit": 4294705152
}
Hash = 4bc445b0bf2f24de41719bcf76515e3a7b66a071
```

**Comment by kc0tlh** [comment]
This issue is now resolved in our [new VS Code editor](https://stackblitz.com/codeflow)! Additional details around our new git functionality in Github issue #2473.
