### ISSUE TITLE
Angular project fails to run locally

### ISSUE THREAD

**Issue by pavankjadda** [stackblitz/core#2413]
I created Angular project https://stackblitz.com/edit/angular-sjutwd and it fails locally. I see couple of issues with generated project

- It's missing`"tsConfig": "src/tsconfig.app.json"` line in angular.json architect-->build-->options-->tsConfig
```
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/demo",
            "index": "src/index.html",
            "main": "src/main.ts",
            "assets": [],
            "styles": ["src/global_styles.css"],
            "scripts": [],
            "tsConfig": "src/tsconfig.app.json"
          },
```
- And did not generate polyfills.ts

When I fixed both issues, it works as expected

**Comment by phalgunv** [comment]
Also, typescript version was incorrect.

**Comment by JeanMeche** [comment]
@sulco The issue is with your base Angular project !

Typescript should be updated with the latest 4.9

**Comment by sulco** [comment]
Hi! I think I've applied the changes right, but I'm still having some issues when trying it locally. That being said, I rarely install stuff locally these days, so there might be something off with my setup.

Can you check [this project](https://stackblitz.com/edit/angular-64tyzi?file=angular.json,package.json) and see if it works for you? 

If not, it would be super helpful if could you fork it (or the base starter), apply the correct changes and send it our way :)

**Comment by JeanMeche** [comment]
@sulco Thank you, you can copy that fork : https://stackblitz.com/edit/angular-tbf56q 👍

**Comment by sulco** [comment]
Thank you! I've just confirmed it with the Angular team and updated https://stackblitz.com/edit/angular. Can you confirm it works on your end, @pavankjadda and @JeanMeche?

**Comment by JeanMeche** [comment]
There is one last thing, is it possible to remove the 2 `polyfills.ts` entries in `tsconfig.app.json` & `tsconfig.spec.json` ? 

The files are not visible on stackblitz but present when download the archive.

**Comment by phalgunv** [comment]
Did anyone get a chance to progress this?
