### ISSUE TITLE
When something is Saved but not Saved?

### ISSUE THREAD

**Issue by mort666** [stackblitz/core#2421]
### Describe the bug

Numerous times now on a project I've saved changes to the project but not committed the changes to the attached git repo, but then either refreshed the browser window or closed the window  or it has crashed. To then come back and on restoration of the session and reloading the project the last version committed it synced down and not the previously saved work in the process overwriting the current changes and requiring the changes be redone? As at the same time the newly trashed project from git is saved automatically on loading leaving no obvious way to recoved potentially hours of work. Wasting time and effort.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-einyjq

### Steps to reproduce

Hard to say as this has happened randomly multiple times, the last instance the web session seemed to crash and hang after a save and build with the git commit button staying as a constant spinning thing. Hit save and that seemed to work, closed the window and went back to the dashboard to reload, on opening the last git saved version was downloaded from several hours ago, not the version that had been edited and save just a few minutes earlier.

### Expected behavior

Saved work to be loaded and not destroyed

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 104.0.5112.81
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 331307085,
  "usedJSHeapSize": 322217333,
  "jsHeapSizeLimit": 4294705152
}
Hash = 1f021b18268b32e6c6b2095e039ac8c9f88b0d52
```

**Comment by kc0tlh** [comment]
This issue is now resolved! Full writeup in Github issue #2473
