### ISSUE TITLE
Hamburger menu nav icon overlaps with dashboard nav icon

### ISSUE THREAD

**Issue by coding-tomato** [stackblitz/core#2424]
### Describe the bug

After opening a fresh Codeflow editor, I noticed the dashboard button is overlapping the hamburger menu icon, which now I can't click.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/stackblitz/docs

### Steps to reproduce

1. Open any Codeflow editor in Firefox.
2. The bug is shown.

### Expected behavior

The buttons should not overlap and be accesible, just like in Chrome.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://user-images.githubusercontent.com/24487667/224484760-87d9f1d7-b8cf-4749-9116-a06da37bab78.png)

### Platform

```
Version = 1.72.0
Hash = 4834bd8ad19bb193d99a5ec83835ba168fb94958
WebContainer = 9bdac2de468a4854f7bacb85c771c93d5676829b

Browser name  = Firefox
Full version  = 110.0
Major version = 110
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
performance.memory = undefined
```

**Comment by fvsch** [comment]
Hi @coding-tomato, thanks for the report!

This is a known issue in Firefox because it does not currently support [the `:has` CSS selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has).

We plan to fix this soon by hiding this element in browsers that don't support `:has`.

**Comment by fvsch** [comment]
Update: we're shipping a fix for this today.

- In browsers that don't support `:has` (Firefox, currently), the StackBlitz bolt icon will be hidden.
- In other browsers, we fixed an edge case where the icon could be overlayed on top of the VS Code Menu Bar.
