### ISSUE TITLE
Allow limiting hot reloads to saves (in a setting), maybe even a setting to disable it sometimes

### ISSUE THREAD

**Issue by babakness** [stackblitz/core#243]
Sometimes it gets messy when the app breaks as you are typing and can sometimes even have really bad effects when working with remote apis that keep getting called every time you type a key.

It would be better if this behavior could be limited to manual saves in settings, because you are consciously done composing a piece of code.

Also, it could also be helpful to be able to just disable hot-reloads in some situations. What would be useful is a short-cut trigger a hot-reload independent of either typing or saving.

**Comment by sulco** [comment]
Makes sense! This is now possible to configure in the Settings 
![image](https://user-images.githubusercontent.com/1511906/106162335-49690d00-6188-11eb-9302-12d072d2d0ee.png)
