### ISSUE TITLE
Make stack blitz embedable

### ISSUE THREAD

**Issue by josephworks** [stackblitz/core#244]

**Comment by gyoshev** [comment]
A sample can be embedded through the **Share** menu (or by adding `?embed=1` to the URL)

![image](https://user-images.githubusercontent.com/90405/35504251-3fad36a8-04eb-11e8-8ff3-f5f4b28cb539.png)

**Comment by EricSimons** [comment]
As @gyoshev mentioned this is already possible with our share dropdown! We also have a new API/SDK in beta that makes it even easier, if desired: https://gist.github.com/EricSimons/72017ec7ba068a5b492ee39f9e3a7f32

**Comment by josephworks** [comment]
ok thx
