### ISSUE TITLE
the web view is not showing anything for react next

### ISSUE THREAD

**Issue by DeepakisDemigod** [stackblitz/core#2458]
the webview for stackblitz is not working

**Comment by fvsch** [comment]
Hi @DeepakisDemigod,

Could you give more information about this issue?

1. Can you provide the URL of a StackBlitz project showing your issue, and detail the steps to reproduce the issue (if any).
2. What do you mean by "react next"? What version of React are you trying to use?

**Comment by DeepakisDemigod** [comment]
https://stackblitz.com/edit/react-project-55cg8a?file=App.js

btw, I haven't tested on desktop yet, this problem is in mobile version of your app.
I was trying do an react project it wasn't showing anything i tried on nextjs also but still got the se issue. hope  problem is not on my end (°•°)

**Comment by DeepakisDemigod** [comment]
the stackblitz,

i was spinning up react project in stackblitz in my android chrome
everything was working fine but first I made the changes in my App.js file
i saved it , then went for preview it was not showing anything because it
was in the loading state there was option to cancel the loading but even
clicking it doesn't work i tried doing everything in desktop mode also
doesn't work.

after which i copied the link provided in the preview and pasted to new
android chrome tab and it worked, i made made some changes saved but after
refreshing the same copied link doesn't work it was showing the result for
state when it was copied. then i copied the new link from preview , and it
worked again. That's what happen i didn't checked on desktop devices.

React and Next was i was creating new reactjs and nextjs projects both of
which didn't work. i also tried doing with static html it also didn't
worked on mobile.

the way stackblitz's editor is the most agile thing I've ever seen for
coding and deployment to 🔥 firebase damn, man it was all done in ~7-8 secs.

hope you fix the issue soon.

DeepakisDemigod

**Comment by willi84** [comment]
I have the same issue with a normal JS project:

https://js-7bvob9.stackblitz.io/

its not running on my samung galaxy S20 mobile browser

its just showing that its starts the dev server

![image](https://user-images.githubusercontent.com/6207308/231211081-a11eb74d-a1cc-4644-ac2c-57dd2cbb5613.png)
