### ISSUE TITLE
Support `assets` property in `.angular-cli.json`

### ISSUE THREAD

**Issue by SamVerschueren** [stackblitz/core#247]
Probably related to https://github.com/stackblitz/core/issues/72. It would be nice to have support for the `assets` property in `.angular-cli.json`. I can't get my library to run without this feature.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
