### ISSUE TITLE
Export and import to github, gitlab or pagure.

### ISSUE THREAD

**Issue by catafest-work** [stackblitz/core#2473]
### **Is your feature request related to a problem? Please describe.**

I want to export my project to GitHub , GitLab or Pagure , also will be great to import from my accounts from github, gitlab or pagure.

### **Describe the solution you'd like**
Will be great if you can create a gui for export the project to  github, gitlab or pagure.
I don't know your project but this cannot be very difficult if you create this big project.

### **Describe alternatives you've considered**
Basically, the solution is to use these steps:
Create a new GitHub repository.
Open your StackBlitz project and go to File > Download Project. This will download a .zip file of your project.
Extract the contents of the .zip file to a local folder.
Initialize a new Git repository in that folder using the command git init.
Add the contents of the folder to the Git repository using the command git add ..
Commit the changes using the command git commit -m "Initial commit".
Add your GitHub repository as a remote using the command git remote add origin <repository-url>, where <repository-url> is the URL of your GitHub repository.
Push the code to GitHub using the command git push -u origin master.

### **Additional context**
Add any context or screenshots about the feature request here.

**Comment by kc0tlh** [comment]
For years we've had a partial git integration in our Classic Editor. It had a number of issues and inconsistencies that you can read all about in all of the linked issues on this thread if you're so inclined.

<img width="673" alt="image" src="https://github.com/stackblitz/core/assets/1532264/2137778e-81d2-4752-8acf-72c92bf09b54">

Thankfully, all of that has now changed...

Full Github.com integration is now available in our new VS Code editor! You can [check out the open beta for yourself here](https://stackblitz.com/codeflow)!

![image](https://github.com/stackblitz/core/assets/1532264/0ffe380d-3a1d-40cf-a673-91481cdd5d3d)

You can use git from the GUI or Terminal as shown below:
<img width="1013" alt="image" src="https://github.com/stackblitz/core/assets/1532264/c89756d0-480d-4586-adac-e884db539780">
