### ISSUE TITLE
only half of the screen is showing

### ISSUE THREAD

**Issue by kysong0925** [stackblitz/core#2478]
why is the screen only half filled?

**Comment by kysong0925** [comment]
<img width="1158" alt="Screen Shot 2023-04-16 at 10 06 10 PM" src="https://user-images.githubusercontent.com/112201766/232383548-b9065bcc-c77a-4609-81c3-619df949d760.png">

**Comment by fvsch** [comment]
Hi @kysong0925, thanks for the report.

This should now be fixed. See #2480 for details.
