### ISSUE TITLE
The layout is unusually uncomfortable.

### ISSUE THREAD

**Issue by kode-zon** [stackblitz/core#2480]
![image](https://user-images.githubusercontent.com/77818936/232403777-ef158d4d-e651-4a96-84f1-fe388b1237df.png)

I see a lot of space at bottom of window and cannot drag to reduce it, 
Is this a deliberate design?

**Comment by kode-zon** [comment]
> ![image](https://user-images.githubusercontent.com/77818936/232403777-ef158d4d-e651-4a96-84f1-fe388b1237df.png)
> 
> I see a lot of space at bottom of window and cannot drag to reduce it, Is this a deliberate design?

After I noticed the chrome update button, I pressed update.

After that, there were no more symptoms.

**Comment by fvsch** [comment]
Hi @kode-zon, thanks for the report.

It looks like an issue with Chrome 107 not supporting the CSS `dvh` unit. Updating to a stable Chrome version fixes the issue.

We just shipped a fix for people who are still in slightly outdated browser versions.

**Comment by fvsch** [comment]
As a side note: we recommend updating your browser when the "Update" button appears, if only to make sure you have the latest security updates.
