### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by conao3** [stackblitz/core#2488]
Hi, thanks for this project!

I'm facing this error, I cannot solve it. Please help me?
```
Cannot use import statement outside a module
```

maybe this is related to #2296, #2280?

This is my project that produces this error.
https://stackblitz.com/edit/react-ts-8xtbvq?file=App.tsx

**Comment by conao3** [comment]
I want to use react-spectrum and App code comes from its [getting-started](https://react-spectrum.adobe.com/react-spectrum/getting-started.html)

**Comment by fvsch** [comment]
Thanks for the reproduction project @conao3.

Looks like this is likely to be an error on our side.
