### ISSUE TITLE
I hate this feature

### ISSUE THREAD

**Issue by pickle69420** [stackblitz/core#2495]
Your prettier format on save is so annoying, and there is no way to disable it. Whenever I disable the "editor.formatonreload" value it just changes nothing. It feels so wierd having your code suddenly edited every time you save. Plus, of course, there is a bug.

Lets say this is my json:
```javascript
var tags = {
      'color': {
        'style': 'color',
        'preset': false,
      },
      'bg-color': {
        'style': 'background-color',
        'preset': false,
      },
      'bold': {
        'style': 'font-weight: bold',
        'preset': true,
      },
      'italic': {
        'style': 'font-style: italic',
        'preset': true,
      },
    };
```
Prettier formats it into this weird mess:

```javascript
var tags = {
      color: {
        style: 'color',
        preset: false,
      },
      'bg-color': {
        style: 'background-color',
        preset: false,
      },
      bold: {
        style: 'font-weight: bold',
        preset: true,
      },
      italic: {
        style: 'font-style: italic',
        preset: true,
      },
    };
```

Please fix this now, because having simple Json just not work because of the editor is a new level of ideocracy.

**Comment by fvsch** [comment]
I don't understand what the bug is supposed to be.

Both the input and output are valid JavaScript with the same exact semantics, unless I’m missing something.

**Comment by magoerlich** [comment]
@pickle69420 are you by any chance confusing javascript objects with json objects?
These are not the same.
If you want this to be json you have to either make it a static string or convert the Javascript Object you got there with JSON.stringify....

**Comment by NG235** [comment]
The first example you provided is a JavaScript object, not JSON. Prettier formatted this correctly into a readable format that is standard. A JSON file needs to have the extension `.json` and be formatted as JSON (double quotes around keys and string values).

JavaScript objects are not the same as JSON or JSON objects.

**Comment by pickle69420** [comment]
Well im very sorry, but javascript compiler does not seem to have a problem with this, in fact, it works fine!

**Comment by magoerlich** [comment]
@pickle69420 Javascript doesn't even have a compiler....
A well-meant tipp: I'd recommend you reading a book, or two about the stuff you're doing there.....or keep on acting like an arrogant prick who knows better.....i actually don't care, but maybe you should
