### ISSUE TITLE
Add emmet support

### ISSUE THREAD

**Issue by kenyk7** [stackblitz/core#25]

**Comment by stevermeister** [comment]
I would change the title to just "add emmet"

**Comment by EricSimons** [comment]
Love it! Will investigate how we can do this & circle back 👍

**Comment by drKnoxy** [comment]
emmet is now in vscode/core and was working in blitz (monaco bug), i think this ticket is stale.
vote close as duplicate

**Comment by stevermeister** [comment]
I still don't see it in blitz, what button should I press. Does not work for [TAB]

**Comment by markpritchett** [comment]
Looks to be supported now.  I'm on Windows.

![image](https://user-images.githubusercontent.com/1267889/36415458-db107914-161d-11e8-8f4a-5060b9f808fe.png)

**Comment by learnwell** [comment]
> for me its `Ctrl+E` on windows

`cmd+e` on mac

**Comment by EricSimons** [comment]
This actually shipped a while back- closing for now!

**Comment by webenadam** [comment]
I see it's working, but it doesn't show to autocomplete options like in vs, which is very helpful, it would be nice!

Btw - do you have a desktop app also?

**Comment by ntubrian** [comment]
2023 still have no idea how to enable emmet settings 
and no more blogs or docs mentioned how to do that

**Comment by DrJKL** [comment]
Could you add `.vue` (inside the `<template`) as a supported filetype for Emmet?
