### ISSUE TITLE
Starting an Angular project with @angular/material on 2nd start-up won't load as it can't find theme files

### ISSUE THREAD

**Issue by Asheq096** [stackblitz/core#2500]
When you first load the project (loading from a GitHub repo), it loads up fine. If you close the browser and re-open the project, you get the following error:
```
Import error, can't find file:
/@angular/material/prebuilt-themes/deeppurple-amber.css
```
The files are correctly imported in global_styles.css (@import '\~@angular/material/prebuilt-themes/indigo-pink.css';) and in angular.json ("styles": ["@angular/material/prebuilt-themes/deeppurple-amber.css","src/global_styles.css"],). Have tried with and without "~", and referencing node_modules and even reinstalling the @angular/material package and even different versions. Have also tried creating a new fork, same error, and even on different machines and browsers. Have also tried pulling from current branch again. The only way I've got it to work is to create a new project and re-load from repo. But next time I close my browser, I have the same issue again.
package.json file attached.
[package.json.txt](https://github.com/stackblitz/core/files/11365879/package.json.txt)

**Comment by Asheq096** [comment]
it seems issue was  that StackBlitz wouldn't save anything after connecting to a repo... opening new ticket for this issue...

**Comment by scottishsmile** [comment]
I am having the same issue, what is the fix?

**Comment by Asheq096** [comment]
I don’t remember exactly but if you fork it and don’t connect a repo you’ll recover the file. Idk if they have fixed it but connecting to a repo was what caused the issue, didn’t connect to any repo after all.
