### ISSUE TITLE
‘Require’ is not a function 

### ISSUE THREAD

**Issue by ashika786** [stackblitz/core#251]
Hello,

I created a brand new angular 5 project. Following line in type script app.component.ts is giving error that Require is not a function.  I get same issue when running it in chrome. Copied the code from a tutorial:
var MongoClient = require(‘mongodb’).MongoClient.

Spent hours searching, removing and reinstalling dependencies. 

Please assist ASAP. 

Thanks
Ashik

**Comment by vegarringdal** [comment]
Have you tried 
`ìmport * as mongo from 'mongodb'`
or 
`import mongo from 'mongodb'`

and checked whats in mongo variable?

?

**Comment by ashika786** [comment]
Hi Vegar.

Thank you for attending my query.

I tried 'import mongo = ' syntax. Will try what you suggested and let you
know how it goes.

*Require* is everywhere. Will adding some package help?

Thank
Ashik

**Comment by ashika786** [comment]
Hi Vegar,

Tried both these syntax. It says import is only valid for namespace or
module.

Can you please share something that works.

Stackblitz looks  great tool but I am not able to get past road blocks.
Still searching.

Thanks
Ashik

**Comment by EricSimons** [comment]
@ashika786 you can't use mongoose in stackblitz- we only support frontend JS libraries/etc (i.e. libs that can run in-browser). Working on backend support though :)
