### ISSUE TITLE
Firebase Hosting doesn't work

### ISSUE THREAD

**Issue by ghost** [stackblitz/core#2512]
### **Description of Bug**
So I click on 'Sign in with Google', give full access to my google account, and after it's done and pop-up closed nothing happens.
I am still seeing Sign in button. I click again and it takes me through the same allow access process. 

### **Steps to Reproduce**

1. Go to 'create-react-app js fork > Firebase Hosting'
2. Click on 'Sign in With Google'

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by HeyGarrison** [comment]
Duplicate of #2933
