### ISSUE TITLE
Connect error on connect to project

### ISSUE THREAD

**Issue by Mahad-lab** [stackblitz/core#2518]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Steps to Reproduce**

1. Go to 'https://stackblitz.com/github/vercel/next.js/tree/canary/examples/with-iron-session?file=README.md'
2. Click on 'Open in New Tab'
2. Click on 'Connect to Project'

### **Expected Behavior**
There must be a page for connecting to the project instead of this page
https://stackblitz.com/connect-error?reason=not-found&appId=aonimnjprgithub-si0k

### **Screenshots/Screencast**
![Screenshot from 2023-05-14 22-46-40](https://github.com/stackblitz/core/assets/56235065/1da36a10-a667-4478-91f3-b7cc3b96b829)

**Additional Context/Questions**
Add any other context or questions regarding this bug.
In connect error page the **Dashboard** link have typo of stacklitz.com missing b

**Comment by kc0tlh** [comment]
This issue has been resolved. The Open in New Tab button successfully opened the preview in a tab.
