### ISSUE TITLE
[Bug] angular export project throws cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by JWO719** [stackblitz/core#252]
The default angular project throws following error when you try to start the project with "npm start":

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\jwo\Downloads\angular-v97urp\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

The error didn't occur if you upgrade to the newest angular cli version.

**Comment by EricSimons** [comment]
@JWO719 interesting - just so I understand correctly, your computer had an older version of the CLI installed which caused this error?

**Comment by JWO719** [comment]
No the exported package.json referenced an older Version of the CLI which seems to throw the error. What I mean I just exported a project from stackblitz, installed all dependencies and executing the npm script to build the project. This throws the error above. I didn't used the global installed CLI. Sorry for explaining it that complicated :D still don't know if I explained the problem understandable :D

**Comment by seveves** [comment]
That is a common problem with the latest angular-cli version and you should be able to fix this easily with installing the missing peer dependencies yourself (`npm install --save-dev @angular-devkit/core@0.0.29` ... of course with the right version)

**Comment by frederikprijck** [comment]
@seveves @EricSimons  The correct solution appears to be to upgrade `@angular/cli`

- Create a new Angular stackblitz
- Export the starter project
- `yarn install` & `yarn build` result in the error mentioned by the OP
- Upgrade `@angular/cli` from `1.5.4` to `^1.6.0`
- `yarn install` & `yarn build` now works fine

**Comment by seveves** [comment]
@frederikprijck thx for testing this out. So can we close this issue @JWO719 ?

**Comment by frederikprijck** [comment]
@seveves I'm not sure we can. As the exported project still fails when building. We still need to manually change the project dependencies. Imho it would be a good idea if a project exported from stackblitz works without any manual intervention.

**Comment by EricSimons** [comment]
Thanks so much to @frederikprijck for submitting the PR that fixes this! Lmk if anyone still has any issues with this 🙏

**Comment by royeradames** [comment]
> Thanks so much to @frederikprijck for submitting the PR that fixes this! Lmk if anyone still has any issues with this 🙏

I'm having a similar issue: https://stackblitz.com/edit/jasmine-in-angular-jdugq6?file=package.json
