### ISSUE TITLE
Unable to add popular React state manager Zustand to default React project — Error in /turbo_modules/zustand@4.3.8/index.js (3:15) Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by AdamMescher** [stackblitz/core#2520]
### **Description of Bug**

Attempts to use Zustand (https://github.com/pmndrs/zustand) latest version 4.3.8 within newly cloned React project throws error.

Error Message: 

```
Error in /turbo_modules/zustand@4.3.8/index.js (3:15)
Cannot use 'import.meta' outside a module
```

### **Steps to Reproduce**

[StackBlitz Issue Recreation Project](https://stackblitz.com/edit/react-skkfd9?file=src%2FApp.js)

1. Fork new React starter project via provided Frontend templates
2. Add Zustand project dependency via dependencies section on sidebar
3. Add Immer via unmet peer dependency modal
4. Add `create` import from `zustand` and create a simple store via boilerplate found [from Zustand introduction docs](https://docs.pmnd.rs/zustand/getting-started/introduction#first-create-a-store)

```jsx
import { create } from 'zustand';

const useStore = create((set) => ({
  bears: 0,
  increasePopulation: () => set((state) => ({ bears: state.bears + 1 })),
  removeAllBears: () => set({ bears: 0 }),
}));
```

### **Expected Behavior**
User should be able to use Zustand project dependency without import errors.

### **Screenshots/Screencast**

**Error Message**
<img width="491" alt="Screen Shot 2023-05-15 at 1 24 32 PM" src="https://github.com/stackblitz/docs/assets/6540117/ce33335e-a60f-403b-b772-4f35219c1c7e">

**Unmet Peer Dependency Modal**
<img width="596" alt="Screen Shot 2023-05-15 at 1 29 07 PM" src="https://github.com/stackblitz/core/assets/6540117/f81ea019-85c2-4c6c-ab3d-6c2cf22c9470">

**Project Dependencies**
<img width="379" alt="Screen Shot 2023-05-15 at 1 21 03 PM" src="https://github.com/stackblitz/docs/assets/6540117/0a9948a8-048f-4d29-ad81-eaeef60cb7e2">

**Comment by AdamMescher** [comment]
Perhaps a useless callout, but I was able to add Zustand with success within CodeSandbox -- https://codesandbox.io/s/beautiful-sammet-phe0l4?file=/src/App.js

**Comment by markwhitfeld** [comment]
@AdamMescher  This issue should now be resolved. It is resolved for your reproduction and other variants of the same issue.
Please re-open the issue if you are still experiencing this problem.

PS. I tweaked your example from the docs page you referenced, and the counter example is working great:
https://stackblitz.com/edit/react-r7seg4
