### ISSUE TITLE
Stackblitz.com is redirecting to spam webpages

### ISSUE THREAD

**Issue by scottnath** [stackblitz/core#2523]
### Clicking `Dashboard` on error page redirects to spam

When not signed in on Stackblitz and viewing the `Connect Error` page, clicking `Dashboard` gets the user Phished to spam websites. The sites change each time

### **Steps to Reproduce**

1. When _not signed in_, Go to https://stackblitz.com/connect-error?reason=not-found&appId=anything
2. Click on `Dashboard`
3. See the redirect to not-stackblitz

bug: looks like you're redirecting to `stacklitz.com`

`<a href="https://stacklitz.com">Dashboard</a>`

### **Expected Behavior**
I'd see the dashboard

### **Screenshots/Screencast**

https://github.com/stackblitz/core/assets/216931/240ec6cd-5d7e-44db-adb3-860c212c9387

**Comment by fvsch** [comment]
Thanks a bunch for the report @scottnath! ❤️ 

Indeed we had a typo and ended up linking to a typosquatted site. 😬 
This should be fixed now.
