### ISSUE TITLE
 Good Work !!!!

### ISSUE THREAD

**Issue by sree332** [stackblitz/core#253]
Good work ! for the angular project when I install a npm module ( Material design bootstrap) I see an error in the  module.ts file - "module not found " , Could you help me out.

**Comment by sree332** [comment]
Please note I was able to install the module but when I include it in the app.module.ts file I see an error - "Module Not Found "

**Comment by EricSimons** [comment]
@sree332 can you link the stackblitz project here? Thank you for the kind words btw :)

**Comment by sree332** [comment]
Thanks for the response. I was using cloud9 editor for some time and I felt
this is much more responsive but when I was testing it I found this issue.
Attached is the URL :

https://angular-m2mefa.stackblitz.io

Thanks
Sree

**Comment by sree332** [comment]
and I think its happening for some of the third party modules, another one
I tried is the PrimeFacesNG. The module and dependencies are loaded from
the NPM registry but when we use it in the code,  we are seeing this No
Module Found Error.

Thanks
Sree

**Comment by EricSimons** [comment]
These errors are happening for the same reason as https://github.com/stackblitz/core/issues/254#issuecomment-362647936 - closing issue for now 👍

**Comment by brianmuks** [comment]
I am  now able to quickly create and test features . Thanks for the project.
