### ISSUE TITLE
404 at https://stackblitz.com/settings/membership/billing

### ISSUE THREAD

**Issue by bstro** [stackblitz/core#2531]
### **Description of Bug**
404 when trying to change my billing info.

### **Steps to Reproduce**
1. Go to Account Settings > Billing `/settings/billing`
2. Click on "Change billing method"
3. Experience a 404

### **Screenshots/Screencast**
<img width="363" alt="image" src="https://github.com/stackblitz/core/assets/627290/9f75d941-b9f9-4acc-887f-a1fb8a14a7c0">

<img width="1080" alt="image" src="https://github.com/stackblitz/core/assets/627290/f9021aa9-78a8-4e96-a0f5-3539b9c462a5">

**Comment by AleksandrSl** [comment]
Hi, @bstro. Thank you for reporting this, should be already fixed. Can you confirm?

**Comment by bstro** [comment]
works, thanks!
