### ISSUE TITLE
RuntimeError {code: 908}

### ISSUE THREAD

**Issue by ReneMarotBDBA62** [stackblitz/core#2535]
Hi.
On my site https://stackblitz.com/edit/angular-hsmg7u (**Lab3**) I have a **RuntimeError {code: 908}** message in the console and can't figure what the problem is.
I have the message even if my index.html does not include <myapp-root></myapp-root> to call the Angular app I am developping.
HTML rendering seams OK.

**Comment by kc0tlh** [comment]
@ReneMarotBDBA62 unfortunately, given that we have millions of free users, we are unable to help troubleshoot specific code projects that are not StackBlitz tech issues. I recommend posting on Stack Exchange!
