### ISSUE TITLE
Doesn't render with incognito window

### ISSUE THREAD

**Issue by leesjensen** [stackblitz/core#2536]
This [app](https://stackblitz.com/edit/stackblitz-starters-rgpcav?file=src%2FApp.js) doesn't render when I open it in an incognito window. No errors are displayed, and the `iframe` is empty.

Repo steps:

1. Open an incognito window with the Chrome browser
2. paste `https://stackblitz.com/edit/stackblitz-starters-rgpcav` in the URL bar.
3. **Observe**: No content is rendered.
4. Repeat steps 1 & 2 in a non-incognito window.
5. **Observe**: Content is rendered.

**Comment by kc0tlh** [comment]
StackBlitz often does not work in incognito mode due to lack of 3rd party cookies, a required feature for us. See issue #162 for additional details.

**Comment by leesjensen** [comment]
@kc0tlh thanks for taking the time to respond. I read through #162 and didn't find a explanation as to why we have to reduce security in order for StackBlitz to work. What exactly is it about 3rd party cookies that is so important for an embedded sandbox to work?

**Comment by kc0tlh** [comment]
@leesjensen great question:

StackBlitz uses a combination of browser technologies, including [Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) and [WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly), across several domains. Each running project has its own domain for the preview pane (custom_subdomain.webcontainers.io)and needs to install a Service Worker for that domain to work properly, while your browser tab is pointed at a different domain (stackblitz.com).

In some browsers, this feature is blocked by “third-party cookie” or “third-party storage” restrictions. These are legitimate restrictions when the third-party domain is an ad server or a tracking server, but in the case of StackBlitz projects the third-party domain is where your project code runs.

**Comment by leesjensen** [comment]
That makes sense. Thanks for taking the time to respond.
