### ISSUE TITLE
Create file in a dot prefixed folder

### ISSUE THREAD

**Issue by Marklb** [stackblitz/core#2538]
### **Description of Bug**

Creating a file in a folder with a the name starting with a dot (ex. `.folder/`), the new file UI breaks.

### **Steps to Reproduce**

1. Try to create a new file in any folder where the name starts with a dot. You can use the icon or right click and select "New File"
4. The files treeview will dim and be unable to click anything.

### **Expected Behavior**
The filename editor should open, allowing the file to be named and created.

**Additional Context/Questions**
I ended up finding a work around, but it is not obvious.

Workaround steps:

1. When the files tree dims, you can click the "New File" icon on the "Files" bar above the treeview, which will correctly try to create a file at the root of the project and fix the treeview.
2. You can then click escape to cancel that file creation.
3. In the dot folder, where you tried to originally create a file, there will be a placeholder file with no name. This file can't be deleted.
4. Edit the name of the placeholder file. Giving it a name will creating the file, pressing escape without naming the file will delete it.

**Comment by kc0tlh** [comment]
This appears to be resolved. More details in #1683. Feel free to re-open if you are still able to recreate the issue!
