### ISSUE TITLE
Stackblitz overwrites README file content when connecting to github

### ISSUE THREAD

**Issue by eslachance** [stackblitz/core#2540]
### Describe the bug

I had just spent over an hour writing a README.md file for a template project I intended to share. I wrote witty and funny things, important bits of information, links, and I was ready to publish. 

But when I clicked `Connect repository`, wrote in a name for a new repository and hit `Create repo & push`, the entire content of README.md was replaced with two lines : a title, and an "Edit on Stackblitz" link. 

I'm fuming. The README.md file is green, indicating it might be uncommited, I think, but there's no git command on stackblitz' terminal. 

**Thankfully**, using CTRL+Z in my open editor tab for the readme file worked. I didn't actually lose all my work. *This time*. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-fekf8s?file=README.md

### Steps to reproduce

1. Create a new repository (I use a vite/react javascript template)
2. Create a `README.md` file in this project
3. Write something in the file.
4. Click `Connect Repository` (connect with github if not already done)
5. Click `Create repo & push` 

### Expected behavior

README.md should not be overwritten by a default stackblitz 2 line readme, when connecting to github.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![panik](https://github.com/stackblitz/webcontainer-core/assets/643344/a52769bf-fd7d-49a4-8de0-5082d7226b59)

### Platform

```
Browser name  = Edge
Full version  = 113.0.1774.50
Major version = 113
```

**Comment by fvsch** [comment]
Well that is embarassing. Thanks a bunch for the report @eslachance!

We should definitely check if there is no README file already before creating one.

**Comment by eslachance** [comment]
I'm just happy ctrl-z worked! I absolutely adore Stackblitz, I want more of it, and I wouldn't want anyone to ragequit because of this 😅

**Comment by fvsch** [comment]
Super glad ctrl-z worked too!

I have a fix for that, it'll probably ship early next week (don't want to ask for reviews on a weekend ^^).

By the way, our GitHub integration in the classic StackBlitz editor is a bit limited and not actively maintained (outside of clear-cut bugs like this). To work on a GitHub repository with better Git support, you can use our beta Codeflow IDE: https://stackblitz.com/codeflow

**Comment by eslachance** [comment]
Oh that's good to know! I'm not sure I've been properly exposed to codeflow before, I am *definitely* going to pay more attention now. This looks a lot more like a real vscode installation. I like it :D
