### ISSUE TITLE
Got MIME type errors in a JS module which runs on localehost in strict mode w/o probs

### ISSUE THREAD

**Issue by BarbWire-1** [stackblitz/core#2547]
[link to project](https://stackblitz.com/edit/js-9xgl9v)

**Comment by fvsch** [comment]
Hi @BarbWire-1,

Our JavaScript starter does not support arbitrary HTML such `<script src="…"></script>` tags in the `index.html` file.

It automatically builds `index.js` and its dependencies and injects the result in the HTML page.

Things like using `fetch` to request project files (such as HTML templates for components) over HTTP is probably not going to work either in the JavaScript starter.

You can use the HTML/CSS/JS starter as a base instead. It uses Service Workers to serve project files over HTTP, which should work better with the way you're loading code. I reuploaded your project files in a HTML/CSS/JS project and it seems to work, after fixing some incorrect URLs in your files (beware of capitalization: if your folder is named `Component1`, the URL should not have `component1`):
https://stackblitz.com/edit/web-platform-i78bj2

**Comment by BarbWire-1** [comment]
Thanks so much!!!  You made me day. 
Also for finding my "capital" mistakes ;) Now I know this structure only works if bundled, as the css variables don't get applied in my corrected copy.
