### ISSUE TITLE
Custom NPM Registry

### ISSUE THREAD

**Issue by mattdsteele** [stackblitz/core#255]
Is there a way to use a custom NPM registry located behind a corporate firewall?

We're publishing custom modules to our internal NPM registry (which also proxies registry.npmjs.org); as such our modules aren't available on StackBlitz.

This might also require us hosting a separate StackBlitz instance on-premises, which maybe is a separate conversation?

**Comment by EricSimons** [comment]
@mattdsteele it's def possible for us to support custom registries, but as you mentioned would likely require hosting StackBlitz on-prem. Would love to chat about this! Can you drop me a note at eric@esft.com? Looking fwd to hearing more about your use cases & how we can help 🍻

**Comment by canda** [comment]
We have similar needs. We have an npm registry that can only be accessed be accessed via vpn. We publish private packages there for internal use. The only solution I can think of is hosting our own instance of stackblitz.

**Comment by juanmendes** [comment]
I am also looking for this feature. We use artifactory internally and would like to be able to point to these internal packages within our stackblitz examples. Is this a dupe of https://github.com/stackblitz/core/issues/313?
