### ISSUE TITLE
package.json file missing

### ISSUE THREAD

**Issue by Ragava2002** [stackblitz/core#2551]
package.json file is missing in the repository. so, i cannot open the project in stackblitz. Please resolve it.

**Comment by fvsch** [comment]
Hi @Ragava2002,

I suspect you are talking about an error shown when trying to import a GitHub repository?

Currently, with our classic editor, we do not support importing a repository or a subfolder of a repository which does not contain a `package.json` file. This may change in the future, but that's a known restriction at this time.

We do support importing any GitHub repository, regardless of its contents, when using the Codeflow IDE (currently in beta): https://stackblitz.com/codeflow
