### ISSUE TITLE
Specified branch/tag/commit not found

### ISSUE THREAD

**Issue by NatholDallas** [stackblitz/core#2553]
i have an error message 
Specified branch/tag/commit not found
.../github/{GH_USERNAME}/{REPO_NAME}/tree/{BRANCH|TAG|COMMIT}/{OPTIONAL_PATH}
please check 
i dont know what happened

**Comment by fvsch** [comment]
Hi @NatholDallas,

Can you share the URL that gives you this error message?

It looks like you might be trying to import a GitHub repository that doesn't exist or is private, or a specific branch or commit that doesn't exist.

**Comment by fvsch** [comment]
Thanks for the update. Looks like the tutorial you were following has an outdated hyperlink indeed. Feel free to notify them.
