### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by vegarringdal** [stackblitz/core#256]
Love your work btw.
Really hope you make starter kits for just typescript and js too.

Ive created this with a small/hobby framework Ive made.
https://stackblitz.com/edit/mframejs-nav

Is is possible to get jquery/boostrap js to work when preview not in own window ?

And how can I use a normal css file ? trying to load the styles,css, but it does not work without having the angular.cli json

**Comment by EricSimons** [comment]
@vegarringdal we do have a starter kit for TS: https://stackblitz.com/edit/typescript :)

For jquery/bootstrap, use the external resources field in the dependencies tab. In angular projects, the only way to apply global stylesheets is with the angular-cli.json.

Lmk if you have other q's!

**Comment by vegarringdal** [comment]
Thx, found it yesterday :-)

But bootstrap and jquery to work when preview is not running in own window, is that possible?

**Comment by EricSimons** [comment]
@vegarringdal they should be running in their own window... can you link the project here so I can repro?

**Comment by vegarringdal** [comment]
https://stackblitz.com/edit/mframe-nav?file=index.ts

Been trying again, looks like it just work sometimes after I refresh...really weird
Maybe I just dont know how bootstrap/jquery works, but this have always worked locally when its jquery/bootstrap is loaded in header

![image](https://user-images.githubusercontent.com/2901416/35694992-6b8e0d7a-0783-11e8-83bc-05609169a98b.png)

**Comment by vegarringdal** [comment]
@EricSimons 

Here is a video(animated gif) when it suddenly worked
if it wasnt because Ive never seen this then I would have though it was my `mframejs` hobby framework messing it up, but dont see how it could atm... but so much I dont know :-)

Your online editor is sooo good compared to anything else Ive seen, really amazing how much fun its been to use :-)

https://stackblitz.com/edit/mframe-nav?file=index.ts

![supercool](https://user-images.githubusercontent.com/2901416/35695339-7aaec41a-0784-11e8-9d5b-2bb9ca2c189a.gif)

**Comment by vegarringdal** [comment]
@EricSimons  did it work for u ?

**Comment by EricSimons** [comment]
@vegarringdal that's super weird that it only works sometimes— I'm thinking it might be a race condition on our end or something 🤔 Will investigate today and report back!

**Comment by vegarringdal** [comment]
@EricSimons 

Did you find out anything yesterday ?

**Comment by vegarringdal** [comment]
@EricSimons can we re-open this issue until u get time to look at it?
Kinda feel its getting lost atm :-)

**Comment by EricSimons** [comment]
Hey sorry I ended up getting tied up in some other bugs on Fri & then was out over the weekend! Reopening & will dig into this tmrw- promise :)

**Comment by vegarringdal** [comment]
@EricSimons
Np, dont have time atm to work on my weird mframejs project next weeks anyways :-)

But having this working when I get time will be fun :-)

Thx for reopening the issue.

**Comment by vegarringdal** [comment]
@EricSimons 

looks like some update you added where the index.html needs `<template></template>` tag fixed the bootstrap issue

**Comment by vegarringdal** [comment]
Been testing it on 2 computers, my nav sample with bootstrap and mframejs works every time 👍

**Comment by EricSimons** [comment]
Woot! Yeah I just pushed a major update for all this stuff yesterday, forgot to circle back in here and let you know :) Lmk if you run into any other troubles!
