### ISSUE TITLE
If you have your project connected to a github repo, and you refresh or the navigator crashes, you loose your changes

### ISSUE THREAD

**Issue by dservidie** [stackblitz/core#2562]
To reproduce:

1. create a project from a github repo
2. make some changes in your code
3. save them but dont commit
4. close the browser to reproduce a crash

Result: You will loose the changes you made since the last commit, even if you hitted the button save

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
