### ISSUE TITLE
tsconfig.json in subfolder does not work

### ISSUE THREAD

**Issue by freehuntx** [stackblitz/core#2564]
### Describe the bug
I tried to setup an monorepo with yarn. One package is a nextjs package with typescript.
The tsconfig.json sits in this subfolder.
In my local vscode this tsconfig.json gets picked up but in stackblitz not.
So the stackblitz IDE shows me jsx errors which shouldn't happen.

### Link to the blitz that caused the error
https://stackblitz.com/edit/stackblitz-starters-vduifs

### Steps to reproduce
1. Let the project install all dependencies (using yarn)
2. Open viewer/pages/_app.tsx
3. See jsx errors

### Expected behavior
No jsx error (because the tsconfig.json in the viewer folder is respected.

### Parity with Local
* [x]  When i open the project in my local vscode IDE (no custom user settings) i dont see this issue

### Screenshots
![image](https://github.com/stackblitz/webcontainer-core/assets/12412020/de8ab866-e6a4-4864-aa2a-764b35a698bf)

### Platform
```
Browser name  = Chromium
Full version  = 105.0.5195.125
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  jsHeapSizeLimit: 4294705152,
  totalJSHeapSize: 105866230,
  usedJSHeapSize: 100015778
}
```

### Additional context
None

**Comment by kc0tlh** [comment]
This issue is resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! I recommend storing this project in Github and using our new editor.
