### ISSUE TITLE
Doesn't Work Template Driven for name Bob

### ISSUE THREAD

**Issue by SeniorFlacko** [stackblitz/core#257]
Validator for Template Driven Form doesn't work if I write Bob on Name.

**Comment by EricSimons** [comment]
@SeniorFlacko can you link the stackblitz project here?

**Comment by SeniorFlacko** [comment]
https://stackblitz.com/angular/byyynkdrode

**Comment by EricSimons** [comment]
This is a bug in the example itself, not stackblitz. They forgot to add the directive tag `appForbiddenName` to the input tag. Change to this and it works:

```html
<input id="name" name="name" class="form-control"
               required minlength="4" appForbiddenName forbiddenName="bob" [(ngModel)]="hero.name" #name="ngModel" >
```
