### ISSUE TITLE
File tree indentation needs fixed

### ISSUE THREAD

**Issue by JasonGoemaat** [stackblitz/core#2570]
### Describe the bug

The way it looks is absurd and it is unintuitive to figure out what folder a file belongs in.  In this example, what folder do you think '+layout.svelte' is in?   It's to the right of the > for 2022, but that's not it because 2022 isn't even open.  It's way to the right of 'advent', but that's not it either.  It's actually in the 'routes' folder.  Working on a project with a complex directory structure and with the same file name in different directories is a nightmare.

![image](https://user-images.githubusercontent.com/114062/210261044-448fee58-d03e-478f-89ad-f5831c3b4ed7.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/sveltejs-kit-template-default-cpxiic?file=README.md,src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2Fadvent%2F2022%2F%2Bpage.svelte,src%2Froutes%2Fadvent%2F2022%2Fday-1%2F%2Bpage.svelte,.vscode%2Fsettings.json&terminal=dev

### Steps to reproduce

1. Create directories
2. Create files
3. Try to identify the parent directory for a file

### Expected behavior

The parent directory for a file should be immediately apparent when you glance at the tree.  In my perfect world, the icons for files would line up with the collapse indicator for the directory.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

On Stackblitz, the file icons are indented past an entire subdirectory indicator making it difficult to tell what folder a file is in.

![image](https://user-images.githubusercontent.com/114062/210261714-2ff6d2a7-5cf5-4cbb-983d-18d8044cf216.png)

VS Code, file icons are lined up with folder expansion icons, it's easy to tell what file is in what directory.  When hovering over the file tree, it even shows lines to show indentation.

![image](https://user-images.githubusercontent.com/114062/210261616-ca057e3f-ef67-4846-a88a-da319817dbba.png)

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 141084517,
  "usedJSHeapSize": 131872285,
  "jsHeapSizeLimit": 4294705152
}
Hash = 6ebe18b1e1db1833797e3e4eb6ff802c375ee61b
```

**Comment by HeyGarrison** [comment]
👋 Thanks for the input @JasonGoemaat. We're actually in the process of flipping over everything to our next gen editor. I think you'll like that. So be on the look out!

For now, I'm gonna close this issue as it'll likely be resolved by that work. Thanks again for the issue!
