### ISSUE TITLE
Refresh/Reload on Edit or saving the file is not working properly

### ISSUE THREAD

**Issue by RoboXGamer** [stackblitz/core#2572]
### **Description of Bug**
See the title
The bug is that that the refreshh not working properly the old code is working even after reload but if i refresh many times and then 1 in 20 attempts to refresh it works with the new code
I think it is a caching problem not everything is in sync pls fix this as it is very hard to see the changes if reload does not work more than half the times

### **Expected Behavior**
When i press refresh button or it automatically refreshes on save the correct preview is updated it should not be using the old code to preview

**Comment by fvsch** [comment]
Hi @RoboXGamer,

Can you share a link to a StackBlitz project which shows this issue, and a list of steps to reproduce the issue? For the steps to reproduce, something like:

> 1. Go to <project_url>
> 2. Open the file `some/file.js`
> 3. Change line 10 to `some code`
> Expected result: the preview iframe shows the result of the updated code

**Comment by RoboXGamer** [comment]
Not able to reproduce again might be one off thing.
