### ISSUE TITLE
Environment variable support (in general)

### ISSUE THREAD

**Issue by perpetual-education-personal** [stackblitz/core#2579]
### **Is your feature request related to a problem? Please describe.**
We're not sure how to deal with .env situations. One example is that we have a vue/firebase project that we want to share with students and get code review on. 

### **Describe the solution you'd like**
After connecting a repo to StackBlitz, we would like to be able to add secret .env files (any type really) to that project that only exist for the StackBlitz instance and the owner to see. These could be just like creating any file - but wouldn't be connected to the repo and might live in their own interface.

### **Describe alternatives you've considered**
We created a second firebase just for the StackBlitz instance of the app. We also created a .env file in StackBlitz that is ignored in the main repo but aren't sure how that will all work out (Still trying things)

### **Additional context**
<img width="600" alt="image" src="https://github.com/stackblitz/core/assets/56655339/736c6b3a-8ac1-4090-bc81-773c199533ca">

**Comment by samdenty** [comment]
we're actively working on environment secrets, and hope to ship this quarter

**Comment by HeyGarrison** [comment]
We shipped environment variables! See doc here: https://developer.stackblitz.com/codeflow/environment-variables
