### ISSUE TITLE
Visualizar 

### ISSUE THREAD

**Issue by Mikelucass** [stackblitz/core#2582]
Não consigo visualizar meu código

**Comment by ggdaltoso** [comment]
Bom dia, @Mikelucass. Tudo bem?

Você poderia nos fornecer mais informações para que possamos entender melhor o seu problema?
Você tem um link para reprodução? Um repositório, talvez?

**Comment by fvsch** [comment]
Closing this issue due to missing information.

If you're still running into a problem, feel free to create a new issue — preferably in English — with more detailed information about your problem.
