### ISSUE TITLE
Support for requesting more vs code extensions

### ISSUE THREAD

**Issue by liana-p** [stackblitz/core#2585]
### **Is your feature request related to a problem? Please describe.**
It would be good to have a way to add new vs code extensions to Stackblitz, or at least a process for how to suggest/request new ones. As I understand it, there is still a limited list of pre-enabled extensions.

I'm also curious if there's any possibility of adding some kind of advanced mode that lets us use any extension, at the risk of getting crashes? I'd prefer being able to try than not being allowed to.

Some background info on why I'm requesting this:

I have projects that require a [new extension](https://marketplace.visualstudio.com/items?itemName=NarratEngine.language-narrat) that isn't on Stackblitz. My project is a game engine so any users of that game engine would ideally need this extension to be able to try it on stackblitz. 

You can see an example of how I'm letting people use Stackblitz with the buttons in the [readme](https://github.com/liana-p/narrat-engine#getting-started), or on the [website](https://narrat.dev). Except the lack of syntax highlighting for my custom scripting language makes it a lot less useful, since the vs code extension can't be installed.

### **Describe the solution you'd like**
Being able to install any extension, or having a clear process for adding new ones to the system

**Comment by samdenty** [comment]
We are in the middle of doing a refactor of how extensions work, that allows users to sideload any VSIX and will use a stackblitz instance of openvsx, which will let people upload extensions so that they show up in search for other users to install (without having to sideload)

**Comment by dfreeman** [comment]
@samdenty that's awesome news! Do you have any estimate for when you expect the new system to roll out? Even just rough guidance like "later this {month,quarter,year,decade}" would be super helpful just to know what to expect 🙂

**Comment by samdenty** [comment]
@dfreeman we’re currently finalising the security aspect of it, which is after discussion should be implemented next week. I would hope to get this out the door within the quarter, but no guarantees.

You can preview the extension sideloading (drag vsix into extensions pane) and openvsx store (which will be replaced with a compatibility based store), here:

https://pr-2505.dotcom.preview.stackblitz.com

Some stuff is broken, but this should let you play around with it before we release

**Comment by samdenty** [comment]
Update: We've tackled the security aspects and have a sorta-final version of it. We're going to use https://open-vsx.org/ instead of our own registry as it simplifies deployment. We will switch when codeflow is in GA though

**Comment by samdenty** [comment]
We now support openvsx and the ability to install custom VSIX

Here's me installing an extension from openvsx, and manually installing a custom VSIX that's not on the registry

https://github.com/stackblitz/core/assets/13242392/8dc50d29-6489-4333-abb8-99ff2525a5c5

**Comment by dfreeman** [comment]
That's fantastic! Thank you for keeping us posted on developments here, and congrats on going live with the feature! 🎉
