### ISSUE TITLE
Simple nextjs app hangs / endless loop 

### ISSUE THREAD

**Issue by mhrisse** [stackblitz/core#2587]
Hi! The dev-server startup hangs in an endless loop with this simple nextjs project, it all build well on vercel. Any suggestions appreciated.

https://stackblitz.com/edit/risse-website?file=README.md,package.json

**Comment by HeyGarrison** [comment]
Thanks for the issue! That project doesn't seem accessible. Could you provide an additional reproduction link?

**Comment by mhrisse** [comment]
Hi! This was reported 7 months ago during my trial. I can re-create the link if you are going to have a look at this now?

**Comment by HeyGarrison** [comment]
👋Heya @mhrisse - a working reproduction would definitely help a lot here! Happy to take a look at this if we can get one. Next JS has had some difficulty in the past for us so it really helps to be able to see which version you’re using etc. 

Also, appreciate the feedback on our bot closing the issue so quickly. How long do you think is appropriate? I just started my role as Product Advocate and am trying to get all of these processes in place! Definitely want to add in processes here, but not wanting to offend or anything.
