### ISSUE TITLE
Leak of the DevSkiller task - "JavaScript | Angular | Notepad App"

### ISSUE THREAD

**Issue by patrycjagorskadevskiller** [stackblitz/core#2589]
**[[ Please do not close this issue. If this is not the right place to report the leak please provide the correct email or website where we can receive help]]**

Dear name/Sir/Madam,

Following up on our email correspondence regarding task leaking (last email dated April 20). On your request, we have set up a trial account so that you will have the possibility to check the copyright of our task, which was published on your site without our permission.

Please contact us at dmca@devskiller.com for account credentials.

Kind regards,
Patrycja Gorska
[dmca@devskiller.com](mailto:dmca@devskiller.com)
DevSkiller.com

**Comment by patrycjagorskadevskiller** [comment]
Hello, any updates here?

**Comment by HeyGarrison** [comment]
Please reach out to support@stackblitz.com. Thanks you.
