### ISSUE TITLE
Angular packages won't install

### ISSUE THREAD

**Issue by prepr-io** [stackblitz/core#2593]
### Describe the bug

We have encountered a bug with Angular on Stackblitz when connecting to our github repository. It seems that some of our dependencies are not installed, thus producing errors.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-akfzl3?file=README.md

### Steps to reproduce

1. Go to the stackblitz project
2. On loading the project the following error will produce:
```
Error in src/queries/getArticles.ts (1:21)
Cannot find module 'apollo-angular' or its corresponding type declarations.
```

### Expected behavior

I would expect all the dependencies to be installed automatically, like is done with other frontend frameworks like react.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1870" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/132589018/d0053146-2ca6-4ed8-b0da-94c521c3dc5d">

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by kc0tlh** [comment]
@prepr-io it appears you have opened a Github repo inside the StackBlitz Classic editor. I recommend you try this same repo in [our new VS Code editor](https://stackblitz.com/codeflow)!

If you are still having issues, feel free to reach out to me directly (alex@stackblitz.com) and I can help troubleshoot. Additionally if you are interested in collaborating with your team inside StackBlitz I can get you setup with a free trial of our Teams plan, aimed at enabling this exact use case with a seamless Github integration!
