### ISSUE TITLE
Share application URL not working

### ISSUE THREAD

**Issue by CodeNextAdmin** [stackblitz/core#2594]
When I try to Share a project using the Application URL option, not the editor, I am unable to open that link to see the preview. Instead, an error appears:  {"syscall":"","errno":2,"code":"ENOENT","path":"/var"}

This happens after the Run the page button is pressed (which is there to prevent phishing attacks). 

Only if the editor is open in the same window, with that same application, will the preview open in its own tab. 
This was observed on mobile, desktop mac (latest chrome)  and with other users I shared the link with. Here is one such link: [](https://te-lab-12-semantic-example.stackblitz.io/
)

**Comment by CodeNextAdmin** [comment]
https://te-lab-12-semantic-example.stackblitz.io/

**Comment by kc0tlh** [comment]
_Tagging #443 as a related issue_

**Comment by kc0tlh** [comment]
@CodeNextAdmin please share a link to project in question and I will re-open this issue for troubleshooting. In the meantime, closing as a suspected duplicated of #1427
