### ISSUE TITLE
How do I import an existing visual code project on to stackblitz ? 

### ISSUE THREAD

**Issue by sree332** [stackblitz/core#260]

**Comment by EricSimons** [comment]
We have beta support for importing from github (stackblitz.com/github/GH_USERNAME/REPO_NAME) and you can also drag & drop folders and files into the editor. More coming soon though!

**Comment by brunolm** [comment]
Same. I clicked the button to "refresh" dependencies but I still got an error saying it couldn't find `node_modules/@angular/forms.ts`

**Comment by EricSimons** [comment]
@rockomatthews @brunolm can you guys link your repos/projects here so I can repro/debug? Best guess is that dep versions may have different dir structures but hard to say w/o seeing it

**Comment by brunolm** [comment]
@EricSimons https://github.com/brunolm/angular-how-to

**Comment by manishbjain** [comment]
I happened to check your ngconf video on youtube where you have demonstrated the ability to automatically create component on clicking the + Sign (It would automatically create all the files - html,ts,and css once you click + and name the component) but I dont seem to get that option in the stackblitz. Can you help me out ?

**Comment by jyotiprasadpal** [comment]
When I drag/drop files and folders to stackblitz, it does not work? How do I know I'm using BETA stackblitz?

**Comment by NadGu** [comment]
Any news? I'm having issue about the drag and drop from the folder project

**Comment by patbrennan** [comment]
Any updates on the drag/drop functionality? It's not working for me - I see a bunch of other issues regarding the same, and haven't been updated.

**Comment by kevin192291** [comment]
This would really help me right now, I kinda need this to work for stackblitz to be useful :(

**Comment by Nashorn** [comment]
Any update?

**Comment by kc0tlh** [comment]
This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
