### ISSUE TITLE
react 18 keeps getting triggered

### ISSUE THREAD

**Issue by ygmgbg** [stackblitz/core#2600]
Error in /turbo_modules/react@18.2.0/cjs/react.development.js (1618:21)
Cannot read properties of null (reading 'useContext')

**Comment by kc0tlh** [comment]
This issue appears to be resolved:

<img width="1439" alt="image" src="https://github.com/stackblitz/core/assets/1532264/82b16569-7bfd-47b5-917b-791561585b3a">

[Project Link](https://stackblitz.com/edit/react-ts-3tyfe3?file=index.tsx)
