### ISSUE TITLE
Stackblitz link to Astro not working.

### ISSUE THREAD

**Issue by khristos** [stackblitz/core#2605]
https://stackblitz.com/fork/github/withastro/astro/tree/latest/examples/docs

![image](https://github.com/stackblitz/core/assets/657950/ef198c1d-50f2-42e3-84b8-f4d80b13c5b8)

**Comment by TheOtterlord** [comment]
The Astro docs template no longer exists. Astro released a new docs solution, [Starlight](https://starlight.astro.build/), which is the new recommendation for docs. The Astro blog template (linked in the same panel) still works, or you can check out more over at [astro.new](https://astro.new)

**Comment by fvsch** [comment]
Hi @khristos and @TheOtterlord, thanks for the heads up!

We've updated the starter link to point to the basic Starlight example instead of the older Astro docs example.
