### ISSUE TITLE
Stackblitz freezing on this project 

### ISSUE THREAD

**Issue by SaroGFX** [stackblitz/core#2607]
This is a project I created recently, and I wanted to make some more changes, but I cannot open it anymore. I've tried on Safari and Chrome.

https://stackblitz.com/edit/ionic-react-routing-lduv79?file=src%2FApp.tsx

The UI becomes non-responsive and the application does not load anymore. It used to work fine yesterday. 

Console error: `Error: Constructor requires 'new' operator`

**Comment by kc0tlh** [comment]
I was unable to replicate the freezing issue. If you are still experiencing this on multiple different computers/browsers feel free to re-open the ticket, but for now I'm closing as it appears resolved!
