### ISSUE TITLE
Vue 3 example does not have terminal so how do I run tests?

### ISSUE THREAD

**Issue by dsheng3** [stackblitz/core#2608]
I am totally confused as to the Vue 3 starter project.

Unlike e.g. nuxt there is no terminal, so how would I trigger something like npm run test?

**Comment by fvsch** [comment]
Hi @dsheng3,

Currently our Vue 3 starter uses [the EngineBlock environment](https://developer.stackblitz.com/guides/user-guide/available-environments) which may boot a bit faster than WebContainers, but does not run Node.js code and tooling such as Jest or other test runners.

If you want to use the WebContainers environement, you can use one of Vite's templates for Vue:

- https://vite.new/vue
- https://vite.new/vue-ts

**Comment by kc0tlh** [comment]
Closing as resolved! Related issue: #2655
