### ISSUE TITLE
Stackblitz fails for all Angular.io examples

### ISSUE THREAD

**Issue by larsm11** [stackblitz/core#2609]
Error in /turbo_modules/@angular/common@16.1.3/fesm2022/common.mjs (74:155)
Cannot read properties of undefined (reading 'Injectable')

**Comment by fvsch** [comment]
Hi @larsm11,

I checked the angular.io site and so far have not found a failing example.
Can you point me to a page where the StackBlitz example fails?

**Comment by kc0tlh** [comment]
Closing due to lack of reproduction. All examples appear to functioning properly now!
