### ISSUE TITLE
Unable to use SWR library

### ISSUE THREAD

**Issue by dbwcooper** [stackblitz/core#2619]
Hi teams,
I created a react starter template. but the react app crashed after I added swr to the project.

see the project link: https://stackblitz.com/edit/stackblitz-starters-1tgkj4?file=src%2FApp.js
![image](https://github.com/stackblitz/core/assets/22339946/fb44aabc-b867-41fe-bdcd-c49d718a068d)

**Comment by markwhitfeld** [comment]
@dbwcooper This issue should now be resolved. It is resolved for your reproduction and other variants of the same issue.
Please re-open the issue if you are still experiencing this problem.
