### ISSUE TITLE
 Please integrate with bitbucket.

### ISSUE THREAD

**Issue by admario** [stackblitz/core#262]

**Comment by slanted** [comment]
Are there any plans for this? Love your product

**Comment by adev73** [comment]
+3!

**Comment by xAvarice** [comment]
I don't use Stackblitz, I would be constantly using and recommending it if it had this feature.

**Comment by Ben197** [comment]
Hi, I like using stackblitz, it would really be great when stackblitz integrates with Bitbucket.

**Comment by nilsleistner** [comment]
+4

**Comment by DmitriKarasev** [comment]
+5

**Comment by indrayanganguly** [comment]
+6

**Comment by dszwcz** [comment]
+12

**Comment by AceWealth** [comment]
+21

**Comment by EricSimons** [comment]
Hi all! This is now officially on our roadmap for Q1/Q2 of 2021 🎉 

Quick question- are y'all looking for public bitbucket.com support, or for on-prem enterprise bitbucket instances? (We'll be supporting both fyi)

**Comment by AceWealth** [comment]
> Hi all! This is now officially on our roadmap for Q1/Q2 of 2021 🎉
> 
> Quick question- are y'all looking for public bitbucket.com support, or for on-prem enterprise bitbucket instances? (We'll be supporting both fyi)

Public bitbucket support would be a game changer. Thanks for replying, can't wait to test it out next year!

**Comment by adev73** [comment]
> Hi all! This is now officially on our roadmap for Q1/Q2 of 2021 🎉

Yay!
 
> Quick question- are y'all looking for public bitbucket.com support, or for on-prem enterprise bitbucket instances? (We'll be supporting both fyi)

Public bitbucket for me. Many thanks for this, this will be really useful!

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
