### ISSUE TITLE
No Console in Vite Projects

### ISSUE THREAD

**Issue by shams-shimul** [stackblitz/core#2632]
I can't see any integrated console in any Vite projects that is normally there with other JS projects. To use the console, currently the output needs to be opened in a new tab and there the browser console can be used but this is a clear pain. Please consider enabling the integrated console for Vite projects as well.

**Comment by kc0tlh** [comment]
@shams-shimul thanks for the product feedback! We will keep this in mind as we have roadmap discussions.
