### ISSUE TITLE
Cannot create a new WebContainers project

### ISSUE THREAD

**Issue by Pauan** [stackblitz/core#2635]
### **Is your feature request related to a problem? Please describe.**

I am trying to create a new WebContainers project that uses `create-react-app` so I can run unit tests using Jest.

However, none of the existing templates work. They are either for a completely different framework (like Next), or they aren't using WebContainers.

### **Describe the solution you'd like**

Right now, whether a project uses WebContainers or not is hard-coded.

It should be possible to take an existing project and convert it to WebContainers.

In addition, when creating a new project, there should be an option to create the project as a WebContainers project.

**Comment by Nemikolh** [comment]
Hi @Pauan ! :wave: Thanks for the feedback and we agree!

We are currently working on improvements to both [our starters](https://github.com/stackblitz/starters) and the UX around starting new projects.

In the meantime I would advise you to use https://node.new to create a blank project based on WebContainer. From there in the terminal you can do something along the lines of:

```
npx create-react-app my-app
cd my-app
npm start
```

Note that if you want git support you should instead use CodeFlow, and to get an empty project you can use this URL: https://stackblitz.com/~/

`~/` will always get you to an empty project. It might prompt you to "apply changes" if you had any uncommitted files in a previous project created at that URL. Note that if you want your project to be persisted you really want to have it backed by a git repository on either github or gitlab at the moment. We're also working on improving this :)

If you already have a repository, then you can use `~/github.com/<owner>/<repo>` instead.

Let me know if that helps! :smiley:

**Comment by Pauan** [comment]
@Nemikolh Thanks! That does help. I was able to use `npx create-react-app .` to install it.
