### ISSUE TITLE
Plain-Old-Typescript-Project

### ISSUE THREAD

**Issue by nhrones** [stackblitz/core#265]
I'm not a big fan of bloated frameworks. Is there any way to start a project that only has a Typescript dependency?  I'm testing this on a Chromebook, and I'm very excited about developing on TS on ChomeOS.

**Comment by michaelbazos** [comment]
See https://stackblitz.com/fork/typescript

**Comment by nhrones** [comment]
Thanks. This is was very helpful.  I'd love to learn more about the basis for this tooling.  I've been using VSCode on WIN-10 and would love to work on Chromebook instead. Any suggestions as to where I might start?

**Comment by nhrones** [comment]
Looks like your using some kind of eval engine in an Iframe. Anyway, your sample completely ignores any tsconfig.json in the root, and I see no place to configure Typescript compiler options, and nowhere to examine the transpiled output.
