### ISSUE TITLE
not able to link css and js files to html template 

### ISSUE THREAD

**Issue by pdesai29** [stackblitz/core#2651]
I am opening html template and  not able to link CSS and js files into HTML file

is HTML template only able to work with a single HTML file and nothing else?

**Comment by kc0tlh** [comment]
I'm sorry to hear that you're having trouble linking CSS and JS files in your HTML template within StackBlitz.

StackBlitz definitely supports the inclusion of multiple CSS and JS files in an HTML project. Here are some common steps and checks you can follow to make sure your files are linked properly:

File Paths: Ensure that the paths to your CSS and JS files are correct in the HTML file. If the files are in the same directory as your HTML file, you can link them as follows:

```
<link rel="stylesheet" href="style.css">
<script src="script.js"></script>
```

File Names and Extensions: Double-check the file names and extensions to make sure they match exactly with what you have in your HTML link and script tags.

Correct Syntax: Verify that the syntax is correct in your HTML file. Missing closing tags or quotes could cause issues in linking the files.

Browser Cache: Sometimes, browsers may cache files, and you may not see the changes immediately. Try clearing the browser cache or perform a hard reload to see if that resolves the issue.

File Permissions and Availability: If you are referencing external files, make sure they are accessible and that permissions are set correctly.

Best of luck with your project!
