### ISSUE TITLE
Stackblitz angular material Error in src/styles.scss Error: EIO: Failed to fetch

### ISSUE THREAD

**Issue by natmallow** [stackblitz/core#2657]
When attempting to view any of the material angular (v12) components on Stackblitz we are receiving the following error. 
```
    Error in src/styles.scss 
    
    Error: EIO: Failed to fetch
```

to reproduce click here
https://v12.material.angular.io/components/autocomplete/examples
https://stackblitz.com/angular/xvdevmaojvo?file=src%2Fapp%2Fautocomplete-auto-active-first-option-example.ts
![image](https://github.com/stackblitz/core/assets/2702278/adf03c6e-ece9-48aa-83f2-8e7186c2bad5)
![image](https://github.com/stackblitz/core/assets/2702278/a8f87439-fcf3-4076-8428-bd3646c398cc)

**Comment by kc0tlh** [comment]
This issue has been resolved:

<img width="1439" alt="image" src="https://github.com/stackblitz/core/assets/1532264/3cc5f4a9-3927-4aac-a620-c5d39b8ec9af">
