### ISSUE TITLE
Stuck at starting dev server

### ISSUE THREAD

**Issue by mira-thakkar** [stackblitz/core#2659]
I tried to fork one of prime-react example in Stackblits, and it's keep saying Starting Dev Server

**Comment by melloware** [comment]
Whoops I just reported the same thing: https://github.com/stackblitz/core/issues/2660

**Comment by jahnli** [comment]
Always install

![image](https://github.com/stackblitz/core/assets/20943608/f55222d7-26a1-449b-8a41-a0410c98eb37)

**Comment by kc0tlh** [comment]
Closing as duplicate of #2660 which has been resolved.
