### ISSUE TITLE
PrimeReact Demos not working

### ISSUE THREAD

**Issue by melloware** [stackblitz/core#2660]
Go here: https://primereact.org/autocomplete/

Click on the Edit In StackBlitz Icon

![image](https://github.com/stackblitz/core/assets/4399574/0e35b15d-9d52-4509-b9fb-97a7e2e61596)

For me StackBlitz just spins and spins starting the container.  This was working last week and now all PrimeReact Examples have this same behavior.

**Comment by jahnli** [comment]
![image](https://github.com/stackblitz/core/assets/20943608/cea030eb-8749-4d9d-8173-2a695d8d2224)
Always install

**Comment by apai4** [comment]
Thanks for reporting this, @melloware! We've pushed a fix for this and the PrimeReact examples are working again.

**Comment by melloware** [comment]
Excellent thank you!
