### ISSUE TITLE
Bugs in Stackblitz VMs cause whole page refresh

### ISSUE THREAD

**Issue by hamzawii** [stackblitz/core#2666]
### **Description of Bug**
I created a new social media like facebook that is designed for coders, it allows code pasting directly into feeds thanks to stackblitz.
The bug i faced is that when a coder share a stackblitz post that contains bugs (bad code), it will affect all the social media and cause whole page refresh. 
This bug is detected on ios using safari browser.

### **Steps to Reproduce**
Register the my social media (on safari, ios, any version) here : https://thewide.com/
Share an angular post (hello world project, is auto generated).

### **Expected Behavior**
bugs, errors on a stackblitz VM should not impact the host application.

### **Screenshots/Screencast**
you can see this video :  [https://youtube.com/shorts/VYJs5qH_kyA?feature=share](https://youtube.com/shorts/VYJs5qH_kyA?feature=share)

**Comment by hamzawii** [comment]
up up please

**Comment by kc0tlh** [comment]
@hamzawii this behavior is not something I am able to replicate when embedding StackBlitz's in other websites besides your application. While I cannot deeply help troubleshoot your code, here is suggestions on where you might start:

There could be JavaScript code on the parent page causing the entire page (including the iframe) to reload. Here are some areas to investigate:

a. Window or Location Reload Functions: Look for any use of functions like window.location.reload() or location.href assignments. These can cause the entire page to reload.

b. Event Handlers: Check for event handlers, such as those tied to form submissions (onsubmit) or buttons (onclick), that might be triggering a refresh inadvertently. If a form submission isn't handled correctly, it can cause the entire page to refresh.

c. Timed Refresh: Look for any use of setTimeout or setInterval that might be calling a reload function at intervals.

d. Third-Party Scripts: Any third-party libraries or scripts running on the page may contain code that triggers a refresh.

Potential Solutions:

Debugging: Use debugging tools in your browser to set breakpoints or add console.log statements to trace the code execution. This can help you identify where the refresh is triggered.

Prevent Default Behavior: If an event handler is causing the refresh, you can try calling event.preventDefault() within the handler to stop the default behavior.

Review Third-Party Code: If you are using third-party libraries or widgets, ensure that they are configured correctly and not causing the refresh.

Investigating these areas should help you identify if JavaScript on the parent page is causing the unexpected refresh and provide you with the means to address the issue. Best of luck!
