### ISSUE TITLE
react-redux issue

### ISSUE THREAD

**Issue by ashserrao** [stackblitz/core#2668]
the react-redux installation is prolonging a lot and not getting completed in the latest version. Please help!!!

**Comment by kc0tlh** [comment]
I was able to install react-redux 8.1.2 in [our new VS Code editor](https://stackblitz.com/codeflow) without issue. I recommend you clear your browser cache and make another attempt.

<img width="664" alt="image" src="https://github.com/stackblitz/core/assets/1532264/404f9145-8da6-4a64-b1c5-cae5b75e0cd8">
