### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by 221286** [stackblitz/core#2669]
I cannot add my bootstrap in my react- navbar component

**Comment by kc0tlh** [comment]
I recommend checking out the [Bootstrap docs](https://getbootstrap.com/docs/5.3/getting-started/introduction/) and this example of [bootstrap with React running inside StackBlitz](https://stackblitz.com/github/twbs/examples/tree/main/react-nextjs?file=src%2Fpages%2Findex.tsx). Best of luck!
