### ISSUE TITLE
Problem with bootstrap

### ISSUE THREAD

**Issue by DeborahK** [stackblitz/core#267]
The new feature to automatically pull in github projects is AMAZING! But mine won't work. It generates: "Cannot find file: src/../node_modules/bootstrap/dist/css/bootstrap.css"

If I follow the instructions for adding bootstrap and remove it from my .angular-cli.json file, then my github won't work correctly with the common: `npm install`.

Is there an easy way to resolve this?

Here is the link to what I tried: https://stackblitz.com/github/DeborahK/MovieHunter

Thanks!

**Comment by EricSimons** [comment]
@DeborahK good catch! We need to support stuff in node_modules in the cli.json- will get a fix in for that asap :) Till then, if you move it to a CSS import in the styles.css file it will work:

```css
@import "~bootstrap/dist/css/bootstrap.css"
```

Will circle back once the cli.json fix is in though!

**Comment by DeborahK** [comment]
Excellent! That worked for now. Thanks!

**Comment by changhuixu** [comment]
Got the same problem. Now it works. Thanks.

**Comment by EricSimons** [comment]
Just deployed the fix for this onto prod! Lmk if y'all run into any more issues with linking to node_modules in angular-cli.json 🍻
