### ISSUE TITLE
error

### ISSUE THREAD

**Issue by devashishsonkusare** [stackblitz/core#2686]
FAILURE: UNSATISFIED VERSION RANGE
Unable to resolve package
ethereumjs-abi @ git+https://github.com/ethereumjs/ethereumjs-abi.git
Please try installing a different version or range.

**Comment by kc0tlh** [comment]
This repo is deprecated by the publishers and appears to not be compatible with the StackBlitz environment.

<img width="326" alt="image" src="https://github.com/stackblitz/core/assets/1532264/394c191f-0c20-48f4-a3ed-b0f97740a68a">

I recommend finding an updated repo.
