### ISSUE TITLE
Importing Axios for snippet testing

### ISSUE THREAD

**Issue by mini-wizbit** [stackblitz/core#2687]
The error message in the web view
//
Error in turbo_modules/axios@1.4.0/lib/adapters/http.js

The entrypoint for 'https' could not successfully be resolved. The file '/turbo_modules/https@1.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.
//
just testing axios out and it wouldn't compile.

I hope you guys can get this fixed as StatckBlitz is awesome.

**Comment by kubiak200** [comment]
Change the version in the package.json file and will automatilly download the modified version.  axios 0.16.2 version works fine.
