### ISSUE TITLE
There is no run button in the UI ?

### ISSUE THREAD

**Issue by TestCode2080** [stackblitz/core#2692]
How do I run the code? There is no "run" button in the UI. Or is it hiding somewhere deep? Whatever it is, but it doesn't look like good UX.

**Comment by TravisJones6** [comment]
Stackblitz automatically runs the code, it should appear in a frame on the right side of the window. If not, there is a button in the top right to open the panel or open in a new window. At the bottom of the panel there is a collapsable sub panel for the console. If you choose to open in a new window use the developer tools to view the console.

**Comment by TestCode2080** [comment]
See the attached screenshot, nothing in the window, nothing in the console. 

![image](https://github.com/stackblitz/core/assets/108724862/28123f53-1be9-41bd-a5fa-21083c529d1c)

**Comment by TravisJones6** [comment]
What browser are you using? Open the developer tools and view the console for any relevant errors.

**Comment by TravisJones6** [comment]
It's definitely something in your end, I just opened it in Safari on my iPad and it works fine. Might be your browser, possibly a browser extension. Try a different browser or incognito mode.

**Comment by kc0tlh** [comment]
@TestCode2080 as @TravisJones6 mentioned, Engineblock projects run themselves (whereas [WebContainer based projects](https://developer.stackblitz.com/guides/user-guide/available-environments) have a terminal).

I recommend clearing your browser cache, and/or trying on a new machine/new browser with [3rd party cookies enabled](https://developer.stackblitz.com/platform/webcontainers/browser-config).
