### ISSUE TITLE
errors.ts:30 ERROR Error: Uncaught (in promise): Error: Can't resolve all parameters for HttpParams: (?).

### ISSUE THREAD

**Issue by Ranindu15** [stackblitz/core#2696]
In my local machine this is working fine. Can someone please check this?  https://stackblitz.com/edit/stackblitz-starters-ggh39v?file=README.md

**Comment by Ranindu15** [comment]
Schema validation failed with the following errors:
  Data path "/polyfills" must be string.
What is this error?

**Comment by kc0tlh** [comment]
@Ranindu15 this project is utilizing Angular version . This is a very old and unsupported version of Angular (current version is 16).

While I would love to be able to help further, I am going to have to recommend that you either continue working with this project on local OR if StackBlitz support is critical, consider recreating the project using a supported version of Angular.

For more information on the versions of Angular that are still supported by Google, checkout their [Supported Versions page here](https://angular.io/guide/releases#actively-supported-versions).
