### ISSUE TITLE
NoSuchMethodError: method not found: 'source' on null 

### ISSUE THREAD

**Issue by Ranindu15** [stackblitz/core#2698]
This is working fine in local machine. Please can someone check.

**Comment by kc0tlh** [comment]
@Ranindu15 please provide a link to a publicly accessible StackBlitz project demonstrating the issue so we can tale a look for you!

**Comment by Ranindu15** [comment]
https://stackblitz.com/edit/stackblitz-starters-41vxw2?file=README.md @kc0tlh

**Comment by kc0tlh** [comment]
@Ranindu15 this project was generated using [Angular CLI](https://github.com/angular/angular-cli) version 12.1.4. This is a very old and unsupported version of the CLI (current version is 16.2.1. 

While I would love to be able to help further, I am going to have to recommend that you either continue working with this project on local OR if StackBlitz support is critical, consider recreating the project using a supported version of Angular/the CLI. 

For more information on the versions of Angular that are still supported by Google, checkout their [Supported Versions page here](https://angular.io/guide/releases#actively-supported-versions).

**Comment by Ranindu15** [comment]
I created this project for another issue. It's related to mat bottom sheet. In this angular version(v12) it was working fine, but in new angular version(v15) there is a problem. This is the issue link :  https://github.com/angular/angular/issues/51214#issuecomment-1691128223
