### ISSUE TITLE
Unable to use git commands

### ISSUE THREAD

**Issue by bishalkar10** [stackblitz/core#2703]
### **Description of Bug**
I choose the next.js template and tried to initialize a git repo. But I get this error : 'jsh: command not found: git'

### **Steps to Reproduce**

1. Go to homepage 
2. choose next.js template(let it install all the dependencies) 
3. Add a new terminal. 
4. Run command `git init`  

### **Expected Behavior**
A messege showing git repo initialized

### **Screenshots/Screencast**
![image](https://github.com/stackblitz/core/assets/112653391/a270b6b8-1662-488a-bc46-de327d369dca)

**Comment by Nemikolh** [comment]
Hey @bishalkar10! 

We have full support for `git` CLI in [Codeflow](https://stackblitz.com/~/).
However, you cannot initialize a repository from a starter in Codeflow — yet.

However, after having landed in the Classic Editor from a starter, you can click on the `Connect Repository`: this will initialize a repository for you in your account on github.

Once initialized you can navigate to:

```
https://stackblitz.com/~/github/bishalkar10/<project name>
```

And it will open it in Codeflow.

Let me know if you have any other questions!
