### ISSUE TITLE
optional peerDependencies forced to install

### ISSUE THREAD

**Issue by woodybriggs** [stackblitz/core#2706]
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta

peerDependenciesMeta offers the ability for library authors to specify if a peerDependant is optional or not. 
Currently stackblitz forces installation of peerDependants even if they are marked as optional in peerDependenciesMeta 

For a minimal repoduction of this. 

Start with:
[React Typescript Starter](https://stackblitz.com/fork/github/stackblitz/starters/tree/main/react-ts?title=React%20Starter&description=React%20%2B%20TypeScript%20starter%20project)

Try add package:
@tanstack/react-query

Note after installation message appears: `UNMET PEER DEPENDENCIES react-native @ *`

```json
"peerDependenciesMeta": {
    "react-dom": {
      "optional": true
    },
    "react-native": {
      "optional": true
    }
  }
```

**Comment by kc0tlh** [comment]
Closing as duplicate of #2624. Please follow there for updates!
