### ISSUE TITLE
Running git repo in browser does not recognize angular spec file

### ISSUE THREAD

**Issue by mayordwells** [stackblitz/core#271]
https://github.com/ivano33z/notworkingone
 Error in src/app/signup/signup.component.spec.ts: Declaration expected. (15:3)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
