### ISSUE TITLE
html pages that are opened by sharing links will not render properly. Always shows loading

### ISSUE THREAD

**Issue by ZJRui** [stackblitz/core#2713]
[projec](https://stackblitz.com/edit/web-platform-apciwd?file=index.html)

![image](https://github.com/stackblitz/core/assets/40123628/a065713e-0384-4ed7-9c12-9c805a20ae81)

**Comment by kc0tlh** [comment]
@ZJRui this project loads fine in Chrome on my computer:

<img width="1440" alt="image" src="https://github.com/stackblitz/core/assets/1532264/35fbc78b-117c-4d19-86bc-a9df14c52fcd">

I recommend reviewing our guide on [ensuring 3rd party cookies are enabled](https://developer.stackblitz.com/platform/webcontainers/browser-config#chrome-service-workers) and trying on another computer/browser combination. Cheers!
