### ISSUE TITLE
Code from material.angular.io not work. ERROR TypeError: Cannot read property 'firstDayOfWeek' of null

### ISSUE THREAD

**Issue by KorolevOl** [stackblitz/core#272]
Code from material.angular.io not work.
ERROR TypeError: Cannot read property 'firstDayOfWeek' of null

https://material.angular.io/components/datepicker/overview

https://stackblitz.com/angular/vqyxqooqedl

**Comment by Chan4077** [comment]
Shouldn't you report this on the [material2](https://github.com/angular/material2) repo? This repo is meant for **issues, as well as feedback with Stackblitz**.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists with StackBlitz, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
