### ISSUE TITLE
Unable to Resolve 'https' Entrypoint in axios

### ISSUE THREAD

**Issue by robertagr** [stackblitz/core#2722]
Hello,
I am writing to report a bug that I encountered while using axios in my StackBlitz project. Below are the details of the issue:

When using axios, I imported the package and attempted to make HTTP requests within my StackBlitz project. However, I encountered the following error:

Error in turbo_modules/axios@1.5.0/lib/adapters/http.js
The entrypoint for 'https' could not successfully be resolved. The file '/turbo_modules/https@1.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

I have verified that the issue is not related to my code, as the error message suggests a problem with the axios package's internal dependency resolution for 'https'. To further investigate, I copied the exact same code and dependencies into my local development environment using Visual Studio Code, and I did not encounter any issues. This indicates that the problem might be specific to the StackBlitz environment.

Thank you for your assistance!

**Comment by shravani-radhakrishnan** [comment]
Same issue Error in turbo_modules/axios@1.5.0/lib/adapters/http.js
The entry point for 'https' could not successfully be resolved. The file '/turbo_modules/https@1.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.

I appreciate your help!.Thanks

**Comment by shravani-radhakrishnan** [comment]
I guess it is an issue with the latest version of Axios I have changed the version to 0.16.2  it works fine for me.

**Comment by kubiak200** [comment]
Change the version in the package.json file and will automatilly download the modified version. As shravani said, 0.16.2 works fine.

**Comment by nerdyman** [comment]
I can repro this on one of my libs (AFAIK it's all published correctly).

https://stackblitz.com/edit/stackblitz-starters-mph2i6?description=React%20%20%20TypeScript%20starter%20project&file=package.json&title=React%20Starter

Fails on:

> The entrypoint for 'react-compare-slider' could not successfully be resolved. The file '/turbo_modules/react-compare-slider@3.0.1/dist/index.mjs' does not exist. Please log an issue with the package author or check for an updated version of the package.

I can confirm that `dist/index.mjs` does exist, as shown on unpkg: https://unpkg.com/browse/react-compare-slider@3.0.1/dist/index.mjs

Can also confirm everything works as expected in a Turborepo setup.

**Comment by HeyGarrison** [comment]
👋 Hey there!

If you use a project that's backed by Webcontainers is this still a problem? For instance, like https://vite.new ?

**Comment by manoharreddyporeddy** [comment]
After downgrading, below works for me, on stackblitz.com

```
{
  "name": "ht59ab--run",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@emotion/react": "11.11.4",
    "@emotion/styled": "11.11.5",
    "@mui/material": "5.15.21",
    "@types/react": "18.3.3",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "axios": "0.16.2"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  },
  "devDependencies": {
    "react-scripts": "latest"
  }
}
```
