### ISSUE TITLE
"Delete project" button not working when external resources defined

### ISSUE THREAD

**Issue by DenysVuika** [stackblitz/core#273]
Steps to reproduce:

1. Add any external resource URL
2. Expand the "settings" group
3. Click the "Delete project" button

Actual result: the "Settings" group collapses, the "Delete project" does not have "underline" style on hover, and does not handle clicks

Workaround:

4. Delete all external resource links
5. Expand the "settings" group
6. Click the "Delete project" button

Actual result: this time the link is clickable

**Comment by apai4** [comment]
Thanks for reporting this @DenisVuyka! I wasn't able to reproduce this behavior, can you link to a project that's doing this? What browser are you using?

**Comment by DenisVuyka** [comment]
I have attached a gif recording for the issue. Using latest Chrome

![stackblitz-issue](https://user-images.githubusercontent.com/503991/36275886-103191f2-1284-11e8-908a-f3542d656353.gif)

**Comment by DenisVuyka** [comment]
I have just narrowed down the issue. It appears only when the vertical scrollbar appears. If I collapse the "Files" group, everything works fine.

**Comment by purplem1lk** [comment]
Thank you for your patience and for helping narrow down the issue! This issue will be closed accordingly - If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
