### ISSUE TITLE
YOU KEEP BREAKING MY WHOLE COMPUTER!!!

### ISSUE THREAD

**Issue by Cesium72** [stackblitz/core#2742]
Every single time I try to make edits, the "compiling changes" thing at the bottom stops spinning, my browser closes, my mouse stops moving, and my screen goes black. I don't have any tabs open except for this editor, and yet this IDE just gives up on me.

**Comment by Nemikolh** [comment]
Hey @Cesium72! I'm really sorry to hear that. 😢

One of our current goal is to reduce memory usage such that experiences like the one you describe don't happen. It's going to be a long ride and will take a while.

Short term, I wonder if there's something you could do. Which OS are you on and in which browser did you experienced this crash?

Could you also share the amount of RAM that you have?

**Comment by Cesium72** [comment]
Hi, @Nemikolh , I have simply been hiding from the truth that ChromeOS and reposiories of 147 files don't do very well together. I tested Stackblitz with smaller projects, and it didn't even come close to lagging in any way.

Additionally, please know that I am sorry for my previous post. I simply felt a need to rage on the computer and I probably overused the shift key.

**Comment by Nemikolh** [comment]
Hey! No worries, believe me I know the feeling! 😊 Thanks for saying it though.

Is that repository public by any chance? If not, how big is the `.git` folder? 

Glad to hear that you had more success with other projects!
