### ISSUE TITLE
Stackblitz page not working on IE

### ISSUE THREAD

**Issue by amrutha1994** [stackblitz/core#275]
Stackblitz page is now not working on IE or Chrome or Firefox.
Earlier there was trouble with stackblitz in chrome and on IE it was working fine. 
I have done some projects last days and now I cant get that page.
Stackblitz home page is seen but when clicking on ionic, or any other options it just shows a blank black screen. 

 Please help me fix the issue.

**Comment by apai4** [comment]
Hey @amrutha1994, I just deployed a fix for IE which was missing a polyfill required for our latest update. Lmk if it's working for you!

**Comment by amrutha1994** [comment]
Yes its now working. Thank you..

**Comment by amrutha1994** [comment]
Thank you.. Its now working..
