### ISSUE TITLE
Ella Intelligent Global Network Inc

### ISSUE THREAD

**Issue by EllaMartinez1981** [stackblitz/core#2751]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by EllaMartinez1981** [comment]
> ### **Description of Bug**
> Provide a concise description of your bug and your project link (if applicable).
> 
> 
> ### **Steps to Reproduce**
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> 
> ### **Expected Behavior**
> A clear and concise description of what you expected to happen.
> 
> 
> ### **Screenshots/Screencast**
> If applicable, add screenshots to help explain your problem.
> 
> 
> **Additional Context/Questions**
> Add any other context or questions regarding this bug.
> 

![stackblitz-starters-fzjj2o.zip](https://github.com/stackblitz/core/files/12791695/stackblitz-starters-fzjj2o.zip)

![iella.1.-1.PDF](https://github.com/stackblitz/core/files/12791704/iella.1.-1.PDF)

![gitignore.txt](https://github.com/stackblitz/core/files/12791708/gitignore.txt)

![repository-open-graph-template.png](https://github.com/stackblitz/core/assets/136148460/966a6584-a621-4d95-8039-0db043a65063)

![Ella.public.roadmap.-.Board.tsv-1.xlsx](https://github.com/stackblitz/core/files/12791712/Ella.public.roadmap.-.Board.tsv-1.xlsx)

![OpenJS-Foundation-Trademark-List-2022-02-14-1.pdf](https://github.com/stackblitz/core/files/12791715/OpenJS-Foundation-Trademark-List-2022-02-14-1.pdf)

![rfc3561.txt.pdf](https://github.com/stackblitz/core/files/12791718/rfc3561.txt.pdf)

![My File.PDF](https://github.com/stackblitz/core/files/12791747/My.File.PDF)

![licenses creativecommons_230923_204044.pptx](https://github.com/stackblitz/core/files/12791748/licenses.creativecommons_230923_204044.pptx)

https://github.com/EllaMartinez1981/Ella-Intelligent-Global-Network/import

**Comment by SamVerschueren** [comment]
Closing this issue as it's unclear what goes wrong and none of the required details are filled in. Feel free to open a new issue and fill in all the necessary details so we have enough information to have a look ourselves. The more information we have, the better we can help you 🙏 .
