### ISSUE TITLE
off screen only showing

### ISSUE THREAD

**Issue by kuttralaganesh** [stackblitz/core#2752]
only showing off-screen only

**Comment by purplem1lk** [comment]
Hi @kuttralaganesh, can you provide a StackBlitz project link, screenshot, or screencast of what you're seeing We'll need more info in order to help debug. Thanks!

**Comment by fvsch** [comment]
Possible duplicate of #2755.

**Comment by fvsch** [comment]
This should now be fixed in older Chrome versions.

We do recommend using an up-to-date versions of Chrome, Firefox or Safari to use StackBlitz.

**Comment by kuttralaganesh** [comment]
Hi Florens, it is correct ,
I acknowledge the closure of issue #2752.
I update mac os after i update Chrome and all browser now working fine
 Thank you for your timely completion.

Best Regards,
Kuttrala Ganesh
