### ISSUE TITLE
Height of text editor

### ISSUE THREAD

**Issue by arturo-estrada-IPS** [stackblitz/core#2757]
The the text editor only shown in half of the screen
![Capture](https://github.com/stackblitz/core/assets/56322692/eb6abf45-f9e0-47f3-8d6f-badd8d3fb534)

**Comment by fvsch** [comment]
Hi @arturo-estrada-IPS.

Are you using an older version of Chrome, Firefox or Safari, by any chance?

We are using the `dvh` CSS feature, which is [supported in Chrome 108+, Firefox 101+, and Safari 15.4+](https://caniuse.com/mdn-css_types_length_viewport_percentage_units_dynamic).

We may be able to add a fallback value for older browsers, but we currently don’t officially support outdated browsers, so we recommend updating if possible.

**Comment by fvsch** [comment]
Related issue: #2755.

**Comment by fvsch** [comment]
This should now be fixed in older Chrome versions.

We do recommend using an up-to-date versions of Chrome, Firefox or Safari to use StackBlitz.
