### ISSUE TITLE
Files item background misplaced

### ISSUE THREAD

**Issue by zcyzcy88** [stackblitz/core#276]
Browse in IE 11 and Pale Moon

![image](https://user-images.githubusercontent.com/15178410/36208689-a487a6ee-11d4-11e8-885f-540d89123adb.png)

IMO using `.MenuItem::before` to implement background is bad.

**Comment by sulco** [comment]
Thanks for reporting! With the series of updates to our UI and specifically file tree implementation, this should not be an issue anymore, but please feel free to reopen if you stumble upon it again.
