### ISSUE TITLE
Problem connecting with my github repos

### ISSUE THREAD

**Issue by sergioxdev1** [stackblitz/core#2765]
I have this error when a try to connect my project with my repo.

![image](https://github.com/stackblitz/core/assets/50931929/26b19f20-3e31-40c9-a7ad-8afb079b63e9)

**Comment by AleksandrSl** [comment]
Hi @sergioxdev1
My guess here is that your repository is private, and your use our new authentication mechanism - GitHub App. You need to install it to your account and give access to the repositories you want to access from StackBlitz.
Documentation on this is in progress, and I will check why we don't show a suggestion to install the app for private repositories.

In the meantime you can go to [this page](https://github.com/apps/stackblitz), click configure button and then install app into your own account
![2023-10-09 12 56 04 github com 56d80d81ebfe](https://github.com/stackblitz/core/assets/15820496/28e3963b-3f76-46ac-8f6f-f91606760a9a)
