### ISSUE TITLE
Can't find module: angular-bootstrap-md/index (@5.2.0)

### ISSUE THREAD

**Issue by mcristiano** [stackblitz/core#277]
See my project!

[https://stackblitz.com/edit/my-mdbootstrap-study](url)

I'm trying to use these libraries, can anyone help me?
[https://github.com/mdbootstrap/Angular-Bootstrap-with-Material-Design](url)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so I will be closing this one accordingly. If this issue persists, feel free to tag me or reopen this issue. Thank you!
