### ISSUE TITLE
Open new tab to my project site stuck spinning forever

### ISSUE THREAD

**Issue by sbrockway** [stackblitz/core#2774]
I made a simple static html site from the template
The preview on the right looks good.
I copied the url from above the preview and pasted it in a new tab
Got a prompt to "Run this project" and accepted it.
Page shows blue loading spinner forever.
![image](https://github.com/stackblitz/core/assets/11443735/5485d00c-2137-42b0-bde9-bd304f02a57e)

**Comment by obiorjih-google** [comment]
I'm seeing the same issue as well.

**Comment by KananCoder** [comment]
Still Broken, Can share (copy/paste) URL either.  Tried multiple browsers too (Edge, Chrome).

**Comment by zzpzaf** [comment]
Same to me. It works OK, but not in a new tab. It stuck and after trying many times I got the error {"originalErr":{}}
