### ISSUE TITLE
Fatal error: Couldn't retrieve HTML template!

### ISSUE THREAD

**Issue by LayZeeDK** [stackblitz/core#278]
Today, viewing any file in any project with any browser on my home and work network, I get this error.

![image](https://user-images.githubusercontent.com/6364586/36259124-7064d2c2-125d-11e8-82bf-c2eb0a1c8088.png)
_From https://stackblitz.com/edit/ngx-global-component-configuration_

**Comment by vegarringdal** [comment]
Adding `<template></template>` to index.html fixes this

**Comment by EricSimons** [comment]
@LayZeeDK eek, this is from some code we pushed yesterday 😓 This problem only occurs when the index.html file is completely empty- will push a fix for this asap and circle back!

**Comment by EricSimons** [comment]
The fix for this is now live on prod- lmk if it's working again for you @LayZeeDK! Sorry about the inconvenience 😓

**Comment by LayZeeDK** [comment]
Thank you, everything is working again. You are right, my `index.html` file is empty.
