### ISSUE TITLE
Delete any anonymus project that got created without signIn

### ISSUE THREAD

**Issue by vasuajay** [stackblitz/core#2786]
Hello, 

I've been using stackblitz for learning purposes lately and have accidentally created a new angular project before signing in. I cannot take the ownership any longer and whichever changes we make are obviously not being saved since it's not a fork.

The problem is that I got some private information in a mock repository class that I'd not like to see on the wild.

Is there a way to either delete this project or simply the mentioned file ?

Sorry for posting this as issue, but I wasn't very lucky getting help somewhere else.

**Comment by HeyGarrison** [comment]
@vasuajay sorry that this is happening! Would you mind reaching out to support@stackblitz.com ? I'm not exactly sure what we can do, but it'll be a lot easier to work through this over email where you can provide the project url, etc.

**Comment by vasuajay** [comment]
@HeyGarrison Is there any immediate way to delete it?. Like a support number that i can talk to for the deletion of it?

**Comment by HeyGarrison** [comment]
Sorry for the late reply @vasuajay. Best way to handle this is to reach out to support. Unfortunately though it is a little tricky for us to deal with this.
