### ISSUE TITLE
unable to switch browser preview

### ISSUE THREAD

**Issue by Akash23536** [stackblitz/core#2791]
when we are checking preview of one html code and when we create a new file and try to check that file preview it does not show and their is no button to exit or open the preview of that file

**Comment by fvsch** [comment]
Hi @Akash23536.

The way you described your problem is a bit ambiguous. Could you link to an example project that shows this issue, and describe the precise steps to reproduce the issue (what you're doing at every step, what result you expect, and what result you're getting)?

**Comment by Akash23536** [comment]
i shared a google drive vedio link where i explain all about this bug  
https://drive.google.com/file/d/1OFvUutmImX0GJOpTq-hHg-kxYQ3uJd6M/view?usp=share_link
