### ISSUE TITLE
Add details to readme reg open sourcing the core tech

### ISSUE THREAD

**Issue by profnandaa** [stackblitz/core#28]
Hey team, good work on this one! 🔥 By any chance, are you open-sourcing the codebase?

**Comment by EricSimons** [comment]
Definitely! We're planning on open sourcing the core tech behind stackblitz (which is what this repo is for), but there's a lot that needs to happen between now & then. I'm going to fill out the readme a bit which should answer this in detail — will circle back shortly.

**Comment by ProfNandaa** [comment]
@EricSimons - you don't know how much good news this is to me! Started using this tool today, it's just off the hook! 🔥 Can't wait to contribute.

**Comment by mattblackdev** [comment]
@EricSimons @ProfNandaa Same here, really looking forward to contributing to this. Stackblitz let me build a static site for my wife in a day with React and styled-components. Super awesome!

**Comment by maks** [comment]
@EricSimons do you still have plans to open source parts of your work? 
Even publishing some notes or pointers on how you got VSC working in browser would go a long way towards helping myself and others for example with [this long standing issue of getting VSC running locally on Chromebooks](https://github.com/Microsoft/vscode/issues/1031)
Btw awesome work on getting in-browser npm working! [I've wanted to get this working for years](https://github.com/npm/npm-registry-couchapp/issues/108)

**Comment by elgalu** [comment]
It's been almost a year since the last update in this thread.

Can you guys clarify if this will be open source? thanks.

**Comment by dehru** [comment]
I'd love to get access to your core as open source.  I've got a project now to build a vs code style editor in the browser and it sure would be nice to be able to see how you did it and save a ton of time, if not build on-top of it.  Please please please.

**Comment by EricSimons** [comment]
Core npm tech was made OSS a while back- closing for now!

**Comment by TimeTravelersHackedMe** [comment]
@EricSimons Is the in-browser VS Code going to be open sourced? Can you post anything relevant to replicating stackblitz?

**Comment by profnandaa** [comment]
> 
> 
> Core npm tech was made OSS a while back- closing for now!

@EricSimons -- can give the link to the sources, can't seem to find it.
