### ISSUE TITLE
Turbo?

### ISSUE THREAD

**Issue by kokujin** [stackblitz/core#281]
I came here in a hurry after reading the article on  [Turbo](https://medium.com/@ericsimons/introducing-turbo-5x-faster-than-yarn-npm-and-runs-natively-in-browser-cc2c39715403).

Where exactly is the repo and documentation? Thanks

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. We are working on providing more detailed documentation for this feature as part of our upcoming roadmap. If an issue regarding Turbo and/or its documentation persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
