### ISSUE TITLE
please integrate the terminal in stackblitz frontend enviroment.

### ISSUE THREAD

**Issue by Nazeer19159** [stackblitz/core#2811]
I am facing an issue of terminal i see the integrated terminal is available on backend project but not in frontend project i humbly request to Stackblitz team to integrate the terminal for better experience.

**Comment by HeyGarrison** [comment]
👋 

Thanks for the issue! You're referencing the difference between our two environments, which you can find more about here: https://developer.stackblitz.com/guides/user-guide/available-environments#frontmatter-title

To resolve this problem we really recommend using Vite for all of your frontend projects.

Checkout https://vite.new/ {react|vue|vanilla}

Thanks!
