### ISSUE TITLE
Stackblitz is very confusing as a newcomer

### ISSUE THREAD

**Issue by codepleb** [stackblitz/core#282]
Not sure if this is the right spot to give feedback for that, but here is my situation:

I had a question and posted an example project from stackblitz to stackoverflow. People were telling me, that the project is empty and I need to save it first.

- Why do I get a "share" link, if the project isn't even saved?

After some minutes, I figured out, that I need to click on "fork" to "save" the project.

- Why do I need to click on fork? How can you fork a project, before it is being released? In git terms, this makes no sense at all, afaik.

If I misunderstand something, I would be glad to learn where I was wrong. :) Otherwise, I hope you can do anything with this feedback here.

Link to related SO-question: https://stackoverflow.com/questions/48840845/css-grid-how-to-center-content-without-shrinking-the-item-itself

Cheers!

**Comment by babakness** [comment]
I'm not personally confused by the fork idea. Not sure what you mean by "release" but you need to create your own copy of a project before you can save it; but you may not necessarily want to save it.

I agree that it would be useful if clicking "save" implied fork as well and did that for you automatically.

**Comment by codepleb** [comment]
@babakness Yeah I agree with you, but my problem was different. I started a "new" angular project and had to "fork" it. I didn't fork an existing one.

But this is where I was probably wrong. Not sure, since the "angular template" could be seen as an already existing project. I just think the terminology is a bit difficult to understand then, but from this point of view, it would make sense in a technical matter.

**Comment by benjamincharity** [comment]
> Not sure, since the "angular template" could be seen as an already existing project. 

Exactly this. They are just linking to an existing StackBlitz which is why you need to fork it. Possibly just a change to the homepage text `START A NEW PROJECT` could help clarify this.

**Comment by randallmeeker** [comment]
Agreed this is very confusing. I have distributed starter templates to others and they will make a lot of changes only to find out they have to get rid of their changes before they can actually save or share them. It very quickly forces people to dislike the platform.

**Comment by mlc-mlapis** [comment]
Isn't it true that if you start a new project, a new unique one is always instantiated (with unique URL), so it's not necessary to fork anything? I use this way since the very first days of Stackblitz was born.

**Comment by kc0tlh** [comment]
Thanks for your feedback @codepleb! [Our new editor](https://stackblitz.com/codeflow) integrates directly with Github and follows all git norms, eliminating this point of confusion.
