### ISSUE TITLE
How can I export links with the new Codeflow editor?

### ISSUE THREAD

**Issue by Croc-Prog-github** [stackblitz/core#2822]
With the new Codeflow editor (which solved the problem of the Repositories not loading), the other editors (WebContainer, Fullstack, etc.) are no longer able to import changes from the Repositories.
I want to use the function: "Share > Embed" to export my website online (to overcome problem #2218).
The new editor doesn't allow me to do this, is there any way to solve the problem?
Thanks in advance.

**Comment by HeyGarrison** [comment]
👋 

Thanks for the issue. Unfortunately, our next gen editor doesn't really allow for embeds. However, you can embed projects via an iframe and using this URL pattern: https://stackblitz.com/github/:ownerName/:repoName

Hope that helps!

**Comment by Croc-Prog-github** [comment]
Ok, thanks for your help.
