### ISSUE TITLE
html syntax highlighter is broken

### ISSUE THREAD

**Issue by zulfiqr** [stackblitz/core#2830]
HTML syntax highlighter is broken when there is a '@' character in href attribute

![bug html](https://github.com/stackblitz/core/assets/9796354/81dc7c6e-8cf6-4db2-beb7-c4dcfffbf9e4)

**Comment by fvsch** [comment]
Thanks for the report @zulfiqr!

This will be handled by this fix, which I need to test and deploy soon:
https://github.com/stackblitz/textmate/pull/9

**Comment by fvsch** [comment]
Hi @zulfiqr,

We've now deployed a fix for this issue.
