### ISSUE TITLE
Allow stylePreprocessorOptions - Includepaths

### ISSUE THREAD

**Issue by BrunoAMSilva** [stackblitz/core#284]
Being able to specify a folder of scss files to include in components is a major asset so we don't need to use relative paths to import a file with mixins.

`{
  "apps": [{
    "styles": ["styles.scss"],
    "stylePreprocessorOptions": {
      "includePaths": ["styles"]
    }
  }],
  "defaults": {
    "styleExt": "scss",
    "component": {}
  }
}`

In the styles folder there's a mixins file that I want to import in every component in my project, atm I need to use

`@import '../../styles/mixins.scss'` instead of `@import 'mixins'`

Keep up the great work!

**Comment by gjdev** [comment]
Without this option it's impossible to use scss based packages that reference other packages without prefixing the package name with '~'. This is quite common, for instance by the material-components-web team, see e.g. the imports in [material-components/material-components-web/blob/master/packages/mdc-card/_mixins.scss](material-components/material-components-web/blob/master/packages/mdc-card/_mixins.scss).

**Comment by xouqoa** [comment]
I ran into this trying to create a custom theme for Clarity inside of a Stackblitz app. 

The Bootstrap files that Clarity references in it's dependencies.clarity/components.clarity can't be loaded without this option being implemented.

`Can't find modules:
@clr/ui/src/utils/bootstrap/scss/media (@0.12.2)
@clr/ui/src/utils/bootstrap/scss/utilities (@0.12.2)
@clr/ui/src/utils/bootstrap/scss/images (@0.12.2)
@clr/ui/src/utils/bootstrap/scss/list-group (@0.12.2)
@clr/ui/src/utils/bootstrap/scss/close (@0.12.2)
@clr/ui/src/utils/bootstrap/scss/grid (@0.12.2)
@clr/ui/src/utils/bootstrap/scss/responsive-embed (@0.12.2)

Check your import statements & ensure you're importing the correct module names.`

**Comment by tonysamperi** [comment]
News on this?

**Comment by ackuser** [comment]
Any news???

**Comment by schallm** [comment]
Same issue with SyncFusion components.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
