### ISSUE TITLE
[Frontend][Angular][V17]Angular Routing Not Working in Frontend Anguar Project V17+

### ISSUE THREAD

**Issue by ksiranjeevi92** [stackblitz/core#2844]
The Angular Project router link not going anywhere
- No compilation error 
- Manual URI path change still working
- The stack blitz not allow the web page to route

**Comment by zoggi02** [comment]
try importing RouterModule. this works for me

**Comment by sohrabi** [comment]
@zoggi02 , thanks It works fine,

@ksiranjeevi92  just do it as follow: in your `AppComponent.ts`:
 
```
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss'
})
export class AppComponent {
}
```

Also you have to declare your links in `app.routes.ts` like this:
```
import { Routes } from '@angular/router';
import { DashboardComponent } from './dashboard/dashboard.component';
import { AboutComponent } from './about/about.component';

export const routes: Routes = [
    { path: 'dashboard', component: DashboardComponent },
    { path: 'about', component: AboutComponent },
];
````

then simply in your `app.component.html` declare two things:

1. router-outlet
2. the link to your component

```
<a class="nav-link" routerLink="dashboard">Dashboard</a>
<a class="nav-link" routerLink="about">About</a>
<div>
<router-outlet></router-outlet>
</div>
```

**Comment by igor-urdenko** [comment]
I am still experiencing the issue in Angular 17. All the code is here: [https://github.com/igor-urdenko/navbar-test](url)

My links in the menu are not active and not clickable.

**Comment by sohrabi** [comment]
@igor-urdenko I send a pull request for your github project,  I have forked it here: https://github.com/sohrabi/navbar-test , you can see the last commit in this repository.
You need to import `RouterOutlet` and `RouterModule` wherever you want to add links.
You can see my changes to figure out what am I talking about.

**Comment by igor-urdenko** [comment]
> @igor-urdenko I send a pull request for your github project, You need to import `RouterOutlet` and `RouterModule` wherever you want to add links. You can see my changes to figure out what am I talking about.

Thank you, that worked!

**Comment by thayllachristineo** [comment]
> @zoggi02 , thanks It works fine,
> 
> @ksiranjeevi92 just do it as follow: in your `AppComponent.ts`:
> 
> ```
> import { Component } from '@angular/core';
> import { CommonModule } from '@angular/common';
> import { RouterModule, RouterOutlet } from '@angular/router';
> 
> @Component({
>   selector: 'app-root',
>   standalone: true,
>   imports: [CommonModule, RouterOutlet, RouterModule],
>   templateUrl: './app.component.html',
>   styleUrl: './app.component.scss'
> })
> export class AppComponent {
> }
> ```
> 
> Also you have to declare your links in `app.routes.ts` like this:
> 
> ```
> import { Routes } from '@angular/router';
> import { DashboardComponent } from './dashboard/dashboard.component';
> import { AboutComponent } from './about/about.component';
> 
> export const routes: Routes = [
>     { path: 'dashboard', component: DashboardComponent },
>     { path: 'about', component: AboutComponent },
> ];
> ```
> 
> then simply in your `app.component.html` declare two things:
> 
> 1. router-outlet
> 2. the link to your component
> 
> ```
> <a class="nav-link" routerLink="dashboard">Dashboard</a>
> <a class="nav-link" routerLink="about">About</a>
> <div>
> <router-outlet></router-outlet>
> </div>
> ```

Tks, it's worked for me! :D

**Comment by gBhatt1998** [comment]
oh it really works thank for your effoert

**Comment by ujangaripin24** [comment]
> @zoggi02 , thanks It works fine,
> 
> @ksiranjeevi92 just do it as follow: in your `AppComponent.ts`:
> 
> ```
> import { Component } from '@angular/core';
> import { CommonModule } from '@angular/common';
> import { RouterModule, RouterOutlet } from '@angular/router';
> 
> @Component({
>   selector: 'app-root',
>   standalone: true,
>   imports: [CommonModule, RouterOutlet, RouterModule],
>   templateUrl: './app.component.html',
>   styleUrl: './app.component.scss'
> })
> export class AppComponent {
> }
> ```
> 
> Also you have to declare your links in `app.routes.ts` like this:
> 
> ```
> import { Routes } from '@angular/router';
> import { DashboardComponent } from './dashboard/dashboard.component';
> import { AboutComponent } from './about/about.component';
> 
> export const routes: Routes = [
>     { path: 'dashboard', component: DashboardComponent },
>     { path: 'about', component: AboutComponent },
> ];
> ```
> 
> then simply in your `app.component.html` declare two things:
> 
> 1. router-outlet
> 2. the link to your component
> 
> ```
> <a class="nav-link" routerLink="dashboard">Dashboard</a>
> <a class="nav-link" routerLink="about">About</a>
> <div>
> <router-outlet></router-outlet>
> </div>
> ```

thank you, it works on ^17.3.7 in june 2024

**Comment by elliotwesoff** [comment]
Ridiculous that this is still something you need to do in v18 when providing the `--routing` flag on `ng new`.

**Comment by Lo2aiAmer** [comment]
```
    this.router.navigateByUrl(
      `www.mywebsite.com/${environment.countryCode}/${this.selectedLangCode}/cat/${catalogIdentifier}`
    );
```

I'm trying to achieve this, which is totally navigating outside of the application, it's also not working!

as provided in the function above I used angular way, and window object native way, non of them is working.

would anyone help with this ?

**Comment by lpknv** [comment]
> @igor-urdenko I send a pull request for your github project, I have forked it here: https://github.com/sohrabi/navbar-test , you can see the last commit in this repository. You need to import `RouterOutlet` and `RouterModule` wherever you want to add links. You can see my changes to figure out what am I talking about.

> You need to import `RouterOutlet` and `RouterModule` wherever you want to add links.

This is what helped me! Thanks a lot!

**Comment by sonam-niit** [comment]
> > @igor-urdenko I send a pull request for your github project, You need to import `RouterOutlet` and `RouterModule` wherever you want to add links. You can see my changes to figure out what am I talking about.
> 
> Thank you, that worked in react version 19 as well!

**Comment by DushyantSinghChouhan** [comment]
How the same works for non-standalone apps which are migrating from angular 12 to angular 19 ?
