### ISSUE TITLE
Ipad keyboard issues

### ISSUE THREAD

**Issue by jasonbronson** [stackblitz/core#285]
Editor does not allow the arrow keys from an ipad pro to be used. 
Other characters seem to work okay. Including return key etc...

**Comment by jasonbronson** [comment]
Any idea why this is happening?

**Comment by OClement** [comment]
https://github.com/stackblitz/core/issues/32

**Comment by seveves** [comment]
Let's close this and track it over in #32 where @OClement already linked to 👍
