### ISSUE TITLE
Error message 'Could not start IDE' after clearing cache

### ISSUE THREAD

**Issue by ashleymays** [stackblitz/core#2856]
### **Description of Bug**
After clearing the cache with the built-in functionality on Stackblitz, I get an error message that says 'Could not start IDE'. I've tried several times to reload the page, and I've deleted and recreated my account on Stackblitz. But I've only started getting this error after clearni

### **Steps to Reproduce**

1. Go to <a href="https://stackblitz.com/~/github.com/ashleymays/workflow">https://stackblitz.com/~/github.com/ashleymays/workflow</a>
2. Wait until it stops displaying the loading screen with "Starting IDE" message

### **Screenshots/Screencast**
![Loading Screen](https://github.com/stackblitz/core/assets/82427430/f3403481-6faa-49ab-8769-da263c4c7118)
![Could not start IDE](https://github.com/stackblitz/core/assets/82427430/e6d67ab8-133a-4562-b972-6e347692a2de)

**Additional Context/Questions**
I've created and deleted my account a number of times due to small Git glitches in the app, but this issue only started happening after I cleared my cache in the app.

**Comment by ashleymays** [comment]
Tried the link again, and it works now. Thank you!

**Comment by samdenty** [comment]
👍 There's still the issue where clear cache breaks the site from loading which we'll fix
