### ISSUE TITLE
"Unable to resolve package" when package/version exists

### ISSUE THREAD

**Issue by christopherthielen** [stackblitz/core#286]
I'm trying to move some examples over to stackblitz, but ran into this error installing `@uirouter/angular-hybrid@4.0.0`.

<img width="775" alt="screen shot 2018-02-18 at 4 07 59 pm" src="https://user-images.githubusercontent.com/2053478/36358610-ea031930-14c5-11e8-9867-7f6166e61906.png">

Reproduction steps: 
- https://stackblitz.com/edit/angular
- add `@uirouter/angular-hybrid@4.0.0` to dependencies and see the error message

Note that version `4.0.0` exists: https://unpkg.com/@uirouter/angular-hybrid@4.0.0/
Also note if you install `@uirouter/angular-hybrid` (no version specification) it installs version `3.1.10`.

This looks similar to https://github.com/stackblitz/core/issues/175 , however the only [changes to package.json between `3.1.10` and `4.0.0`](https://github.com/ui-router/angular-hybrid/compare/3.1.10...4.0.0#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) was moving `@types/*` from `dependencies` to `devDependencies`, so I don't think this has the same cause (a corrupt package.json in a dependency as described in #175).

**Comment by apai4** [comment]
@christopherthielen thanks for reporting this issue! I just updated things on our end so you're now able to install the latest version of the package. Lmk if it works for you!

**Comment by christopherthielen** [comment]
Thanks, the 4.0.0 version of the package is installing now.  

As a library publisher,  is there a way for me to tell why my package was not installable?
