### ISSUE TITLE
Could not find any package installation setup

### ISSUE THREAD

**Issue by meeowngit** [stackblitz/core#2875]
### **Description of Bug**

I know earlier it was showing package name tab beneath the `Files` tab but now it invisible. How and from where to install any package if we want to?

### **Steps to Reproduce**

2. Click on ''

### **Expected Behavior**
It should be visible with some setup for installation. 

### **Screenshots/Screencast**

![Screenshot (424)](https://github.com/stackblitz/core/assets/109955100/7c76494b-dba7-4907-9c4b-f8075b51722b)

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by mkkaushiksjce** [comment]
Even I have observed the similar issue for the dependencies menu.

<img width="960" alt="issue1" src="https://github.com/stackblitz/core/assets/24917853/4affcfec-c361-4261-8861-9111df490690">

In my repository it is not available for some reason
<img width="237" alt="issue2" src="https://github.com/stackblitz/core/assets/24917853/809d103e-5d95-47ce-be57-ac7752ae41c3">

One of the possible work-around may be create a package.json file and use the Extensions: Install missing Dependencies
<img width="450" alt="issue3" src="https://github.com/stackblitz/core/assets/24917853/3dff2ec8-7475-44cc-b022-ba4e79ce17fb">

If any other solution is available I also want to understand :-)

**Comment by HeyGarrison** [comment]
Hey there!

It looks you're using a Webcontainer project, which doesn't have the UI that you're referring to. The good news is that Webcontainer projects do have a terminal so the way you can install a package is by just typing this in your terminal: `npm install --save ${packageName}`.

Hope that helps!
