### ISSUE TITLE
Can't sign in with GitHub account

### ISSUE THREAD

**Issue by LionInTheCity14** [stackblitz/core#2879]
### **Description of Bug**
I am not using incognito mode, yet can't sign in using my GitHub account.

### **Expected Behavior**
It should allow user  to sign in.

### **Screenshots/Screencast**
![image](https://github.com/stackblitz/core/assets/116134954/561e045a-4428-4d63-8d94-8710fc438b0f)

**Comment by fvsch** [comment]
Hi @LionInTheCity14,

It looks like you're trying to sign in to stackblitz.com embedded on a different website. This is something that we do not support at this time, and have no plan to support. The recommended solution is to go to https://stackblitz.com to work on your projects.

The StackBlitz projects embedded on https://hitesh.ai/jsprojects should be embedded with the `?embed=1` parameter in the URL. With this parameter, the StackBlitz editor UI will be tailored for embedding on other websites, which includes removing all login options and adding a button for forking the embedded project on stackblitz.com (where users can sign in).

In the future we may prevent embedding StackBlitz projects without the `?embed=1` parameter (using the [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) HTTP header).

You can relay this information back to the author of the https://hitesh.ai website, if you have a line of communication with them. I tried to find their contact info on their website, but their “Reach out” links also try to embed a third-party website in an iframe and that third-party website refuses to be embedded (using `X-Frame-Options`).
