### ISSUE TITLE
If the default branch name is not main, then repo is not created. 

### ISSUE THREAD

**Issue by Nikhil-Wagh** [stackblitz/core#2880]
I have `prod` as the default name in my Github settings. And when I try to create a Repo from Stackblitz, I get an error saying `Could not find main`. 

I believe base branch name should not be assumed, and hence this is a bug.

**Comment by mkkaushiksjce** [comment]
Please provide the repository URL so that we can find the possible solution

**Comment by Nikhil-Wagh** [comment]
@mkkaushiksjce I was trying to create a github Repo from Stackblitz. But since I was not able to create the Repo, because of the above error, I don't have the URL. 

But this should be fairly easy to reproduce imo. Just need to update the Github settings to name your base branch to something other than `main`, and try to create a new repo from Stackblitz.

**Comment by HeyGarrison** [comment]
@Nikhil-Wagh I think this should be resolved with our latest updates to github.

Close for now. ❤️
