### ISSUE TITLE
Unable to access site from Egypt anymore

### ISSUE THREAD

**Issue by MinaFayez9** [stackblitz/core#2892]
I am sorry if the title seems a bit silly, but I am struggling to access your website from Egypt, I contacted the ISP but they always say we have nothing about that site and you should contact them, the site is hardly loading as plain html with no JS or even images.
This scenario happens from different laptops and mobile phones on several location.
The site opens perfectly using VPN

Please advise

PS: I couldn't find an email to forward this request to, that's why I opened a GitHub ticket

**Comment by HeyGarrison** [comment]
Hey @MinaFayez9 feel free to forward this request to hello@stackblitz.com. Thanks!
