### ISSUE TITLE
Automatically trim spaces preceding file & folder names

### ISSUE THREAD

**Issue by joejordanbrown** [stackblitz/core#29]
When creating a file and it contains a space this doesn't get removed, spaces should be trimmed from the file name.

**Comment by EricSimons** [comment]
Good catch — I'm thinking we should tell the user that spaces aren't allowed in filenames? That way they wouldn't be confused by the filename "changing" when we strip the spaces out.

**Comment by EricSimons** [comment]
I'm actually not sure if this is an issue though — spaces are allowed in file names on your local fs; any reason SB should be different?

**Comment by joejordanbrown** [comment]
You can't import a file with spaces. So maybe a warning. It's common when copying things that spaces creep in so I tested copying a file name containing a space. Here is an example https://stackblitz.com/edit/angular-xmupz4

**Comment by EricSimons** [comment]
Nice! Thanks for including a nice repro of this btw, super helpful to see what you're describing in action. I'll add in a fix that ensures that files & folders can't _start_ with a space (but still allows spaces in between characters)
