### ISSUE TITLE
Feature request: opening a project from a subfolder in github repo

### ISSUE THREAD

**Issue by yfain** [stackblitz/core#291]
This blog describes a really cool feature https://blog.angular.io/run-angular-cli-repos-directly-in-your-browser-41332fd80901

But this requires the github repo to contain just the Angular project, but if a repo contains projects in subdirectories, stackblitz returns 404. For example, I have an Angular app in a subfolder of the repo https://github.com/yfain/mystore. 

Trying to open https://stackblitz.com/github.com/yfain/mystore/tree/master/myStore fails with 404.

**Comment by apai4** [comment]
Hey @yfain, we do support folders for Github imports! Your URL needs to be: https://stackblitz.com/github/yfain/mystore/tree/master/myStore

You'll have to update your placeholder images to use https, and in `src/app/product-detail/product-detail.component.ts` you'll need to remove the double slashes from your imports to get your repo running.

**Comment by purplem1lk** [comment]
Resolution is provided by @apai4 so this issue will be closed. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you!
