### ISSUE TITLE
Unable to destroy code

### ISSUE THREAD

**Issue by DronaNCHL** [stackblitz/core#2912]
I created an project quickly in Stackblitz to decode encrypted values. Since this is decoding my sensitive values, I want to destroy this repo.
But, seems like there is no way to delete repos generated without creating an account. Since. I wasn't warned about this, we are in trouble now. seeking help.
Thank you.

**Comment by fvsch** [comment]
If you sign in to StackBlitz using the same browser, the temporary project you created should be assigned to your StackBlitz account, and you can then delete it.
