### ISSUE TITLE
Functions in js file not available when using onclick in html element even when the function is declared in js file

### ISSUE THREAD

**Issue by utkarshraj1** [stackblitz/core#2924]
Not able to understand how to call js method in the template. How the js file is connected with the html.

**Comment by utkarshraj1** [comment]
<img width="955" alt="image" src="https://github.com/stackblitz/core/assets/68807205/becf098e-3832-47cb-9a01-1d0806766aaa">

**Comment by utkarshraj1** [comment]
<img width="960" alt="image" src="https://github.com/stackblitz/core/assets/68807205/714c5860-d15f-4635-96ec-e966e855330c">

**Comment by utkarshraj1** [comment]
https://stackblitz.com/edit/js-click?file=index.js

**Comment by fvsch** [comment]
Hi @utkarshraj1.

JavaScript files in StackBlitz projects are usually compiled before being injected in the page. That's how things like `import './style.css'` (which is not standard JavaScript) are made to work. It's similar to how toolchains like [Create React App](https://create-react-app.dev/) or bundlers like [Vite](https://vitejs.dev/) treat JavaScript.

One upside of this is that you avoid the issue of having all the functions and variables you declare in your JavaScript files polluting the global scope, and conflicting with each other if you reuse the same variable or function names in different JavaScript files.

If you want to make sure a function is available everywhere, you can assign it to the `window` object:

```js
function disparar() {
  alert('Me disparé');
}

window.disparar = disparar;
```
