### ISSUE TITLE
Node 18.18.0 breaks webpack. 

### ISSUE THREAD

**Issue by NullVoxPopuli** [stackblitz/core#2926]
### **Description of Bug**

This is the LibUV problem.

https://github.com/nodejs/node/issues/49911 (from Sept 2023)

Repro: https://stackblitz.com/github/nullVoxPopuli/polaris-starter/tree/webpack?file=.npmrc

(build never finishes)

---------

Just found: https://github.com/stackblitz/webcontainer-core/issues/560

**Comment by SamVerschueren** [comment]
Closing in favour of https://github.com/stackblitz/webcontainer-core/issues/1256.

**Comment by NullVoxPopuli** [comment]
oh I opened that :sweat_smile: thanks!
