### ISSUE TITLE
Please add ability to remember location between files (two feature request)

### ISSUE THREAD

**Issue by babakness** [stackblitz/core#293]
First feature request:

Currently, when jumping between files, the location in the file is forgotten. It would be very helpful if that position could be sticky. If I am scrolled halfway down some `app.js` file and switch to `state.js` then when I switch back to `app.js` I should be halfway down just as before and not at the top of the page.

Second feature request:

To go along with this feature request is a bookmark mechanism between files and the ability to switch between files to bookmark locations.

**Comment by babakness** [comment]
I've noticed there was no feedback on this (and it didn't get tagged). It would be super useful for online-driven development to be able to jump between files and maintain position of cursor and scroll per file.

**Comment by babakness** [comment]
@EricSimons What do you think!

**Comment by seveves** [comment]
Hi @babakness ... stackblitz is under heavy development and the guys are doing their best to fix open bugs and improve the user experience. The feature you are requesting is going into the same direction as #67 (maybe you should follow this issue instead for progress updates) and was tagged as 'enhancement'. So it's on the roadmap and I'm pretty sure they will implement it with a behavior similar to your descriptions.

So you have to be patient.

Sometimes I compare OSS with getting drinks in a bar. The loudest does not always get served first 😸

**Comment by kc0tlh** [comment]
We now have parity with VS Code functionality in this department via [our new editor available here](https://stackblitz.com/codeflow). Resolving this issue!
