### ISSUE TITLE
Importing Axios for snippet testing

### ISSUE THREAD

**Issue by darthleonard** [stackblitz/core#2937]
Refering from [2687](https://github.com/stackblitz/core/issues/2687)

_Axios_ & whateaver is _gaxios_ fail same way

Downgrading _axios_ to 0.16.2 does not work as commented on [2722](https://github.com/stackblitz/core/issues/2722)

Tested with the Angular starter project too, same issue

Failing code(commented and uncommented lines):
![imagen](https://github.com/stackblitz/core/assets/5916018/a7048581-9f69-4048-ac5c-8302e9b7c662)

StackBlitz project reproducing the issue:
[https://stackblitz.com/edit/ionic6-angular13-bb3xgm?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/ionic6-angular13-bb3xgm?file=src%2Fapp%2Fapp.component.ts)

**Comment by HeyGarrison** [comment]
👋 Hey there!

Could you try converting you project to a WebContainer project? Here is a starter: https://node.new

One thing to note is that external HTTP Requests inside of StackBlitz are kind of tricky. Most of the time the requests end up getting CORS errors. We're going to introduce a new feature for this soon, but for the time being it is a constraint.

Hope that helps!
