### ISSUE TITLE
Angular starter uses 17 for dependancies, but the CLI is 11.

### ISSUE THREAD

**Issue by straiforos** [stackblitz/core#2938]
Hello Stackblitz team,

I noticed when I was installing lodash and having issues, I created a repository and started to debug. I immediately got the error that npm install had a dependency error. Whats spooky is stackblitz seems to run the application. I confirmed the new Angular project has this as a preset and not something I caused through adding dependancies.

This project is for an interview. Which is supposed to be a simple thing, unfortunately I lost a good hour plus to this issue, and now I feel I have to either fix the starter to migrate all of my code to a new repo. 

I am happy to help repair the starter with the Stackblitz team with my resolution so others do not encounter this blocker.

Kind regards,

Stephen Traiforos

```json
{
  "name": "stackblitz-starters-dppekq",
  "version": "0.0.0",
  "private": true,
  "dependencies": { 
    "@angular/animations": "^17.1.1",
    "@angular/common": "^17.1.1",
    "@angular/compiler": "^17.1.1",
    "@angular/core": "^17.1.1",
    "@angular/forms": "^17.1.1",
    "@angular/platform-browser": "^17.1.1",
    "@angular/router": "^17.1.1",
  ...
  }
"devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.4",
    "@angular/cli": "~11.0.4",
    "@angular/compiler-cli": "~11.0.4",
  ...
  }
}
```

Error from exported repository:
`gitpod /workspace/stackblitz-phone-book (main) $ nvm install
Found '/workspace/stackblitz-phone-book/.nvmrc' with version <v18.19.0>
v18.19.0 is already installed.
Now using node v18.19.0 (npm v10.2.3)
gitpod /workspace/stackblitz-phone-book (main) $ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: stackblitz-starters-dppekq@0.0.0
npm ERR! Found: @angular/compiler@17.1.1
npm ERR! node_modules/@angular/compiler
npm ERR!   @angular/compiler@"^17.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/compiler@"11.0.9" from @angular/compiler-cli@11.0.9
npm ERR! node_modules/@angular/compiler-cli
npm ERR!   dev @angular/compiler-cli@"~11.0.4" from the root project
npm ERR!   peer @angular/compiler-cli@"^11.0.0" from @angular-devkit/build-angular@0.1100.7
npm ERR!   node_modules/@angular-devkit/build-angular
npm ERR!     dev @angular-devkit/build-angular@"~0.1100.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/gitpod/.npm/_logs/2024-01-28T16_54_28_447Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /home/gitpod/.npm/_logs/2024-01-28T16_54_28_447Z-debug-0.log `

**Comment by straiforos** [comment]
I fixed the issue in the exported repo and updated it in my stackblitz instance by generating a Angular 17 app locally and taking its dev dependancies as follows;

`  "devDependencies": {
    "@angular-devkit/build-angular": "^17.1.1",
    "@angular/cli": "^17.1.1",
    "@angular/compiler-cli": "^17.1.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.3.2"
  }`

**Comment by HeyGarrison** [comment]
Hey there! Sorry that you lost so much time to this problem. 

Could you include a reproduction link in this issue? It'll help me test and detrmine where the problem lies.

Thanks!

**Comment by straiforos** [comment]
Of course,

Thank you for your prompt response!

Here is a Stackblitz with the Lodash issue that prompted me to export the code into a repo and run it locally.
https://stackblitz.com/edit/stackblitz-starters-n3txsd?file=src%2Fmain.ts

The Angular starter, for me, is the more significant issue: it can not be exported since it does not have matching dev dependencies.
I just made an exported repo from the starter project since I fixed my dev dependencies in my Stackblitz instance, which caused issues for me.
https://github.com/straiforos/stackblitz-starters-n3txsd-dev-deps-angular-11-not-17/blob/main/package.json#L22
I use git pod to bootstrap repos quickly. I highly recommend it to debug the local environment scenario I am most concerned with.

**Comment by HeyGarrison** [comment]
Ok. I'm understanding now…

We actually have a change in flight for this to move all of our starters over to WebContainers. I should have an update for you in the next week or so!

**Comment by straiforos** [comment]
Thanks so much, I really appreciate your response. Often I don't hear back when I've file a ticket. It is refreshing. 

Take care,

Stephen

**Comment by straiforos** [comment]
Hey @HeyGarrison,

This looks to be resolved, thank you!

Yours in code,

Stephen
