### ISSUE TITLE
Unable to add css in .angular-cli.json 

### ISSUE THREAD

**Issue by royrakesh** [stackblitz/core#294]
Showing error 
```
Import error, can't find file:
bootstrap/dist/css/bootstrap.min.css
```
the code in .angular-cli.json 
```
{
  "apps": [{
    "styles": [
      "../node_modules/bootstrap/dist/css/bootstrap.min.css",  
      "styles.css"
      ]
  }]
}
```

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
