### ISSUE TITLE
NEXT JS EXAMPLE PAGE IS BROKEN

### ISSUE THREAD

**Issue by Palmlight** [stackblitz/core#2943]
![Screenshot 2024-02-01 at 11 16 59](https://github.com/stackblitz/core/assets/50970397/09c6d16d-098f-4a2b-9d1d-ccfc1f7bed86)

**Comment by wglee99** [comment]
The example tables are also not showing for the different libraries/frameworks.

**React**
![image](https://github.com/stackblitz/core/assets/79510234/f4499953-e73e-4267-a49c-c0d410ccc414)

**Vue**
![image](https://github.com/stackblitz/core/assets/79510234/3fba228a-42d5-4897-b28c-cc3830abde39)

I think the routes should be changed to ```tanstack/table/examples/react/basic``` and ```tanstack/table/examples/vue/basic``` instead.
