### ISSUE TITLE
Intellisense is using an old TS version

### ISSUE THREAD

**Issue by Andarist** [stackblitz/core#2944]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Steps to Reproduce**

1. Go to https://stackblitz.com/edit/typescript-8kdjxz?file=index.ts
2. See the error at line 41

### **Expected Behavior**

There should be no error there.

### **Screenshots/Screencast**

<img width="417" alt="Code with underline red squiggles indicating a reported error" src="https://github.com/stackblitz/core/assets/9800850/2bbb3f0d-f8b9-4362-970e-e6692a52725f">

**Additional Context/Questions**

The error is reported here because the builtin TS version doesn't recognize `const` type parameters that were introduced in TypeScript 5.0. It fails [here](https://stackblitz.com/edit/typescript-tncb6c?file=index.ts) with the very minimal code:
```ts
function identity<const T>(arg: T): T

const result = identity('foo')
```

**Comment by davidkpiano** [comment]
Would very much appreciate a fix for this, since we want to move to using StackBlitz as the default code exporter for XState template code.
