### ISSUE TITLE
Can't show an image

### ISSUE THREAD

**Issue by syanenko** [stackblitz/core#2945]
Hi !

May be I'am doing something wrong way, but I can't display image in this [my trivial project ](https://stackblitz.com/edit/js-5sxoad?file=logo_500x500.png). I am to sure that this is a bug, so please, point me to my mistake.

Thanks in advance.

**Comment by HeyGarrison** [comment]
This looks like a problem with the starter project. You might try using a Vite project instead. Try this one: vite.new
