### ISSUE TITLE
How to use ionic-cli ?

### ISSUE THREAD

**Issue by ANTONIOFC** [stackblitz/core#295]
Is there any way to use ionic-cli commands like "ionic generate page my-page" ?

For Angular-cli I've already seen that it was implemented (just right click and choose command).

**Comment by lolaswift** [comment]
Second this

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
