### ISSUE TITLE
Angular project: Open in New Tab: Error: Preset not sepcified in configuration

### ISSUE THREAD

**Issue by spierala** [stackblitz/core#2956]
### **Description of Bug**
It is impossible to open an Angular project in a new tab.
![image](https://github.com/stackblitz/core/assets/1272446/1a80342e-8aea-465d-9241-98907a885c0e)

The project seems to load forever, and the JS console shows just this error: 

`Uncaught (in promise) Error: Preset not sepcified in configuration`

![image](https://github.com/stackblitz/core/assets/1272446/31e824a9-da3e-453b-9ab1-325dc57aba64)

### **Steps to Reproduce**
1. Go to https://stackblitz.com/edit/stackblitz-starters-dqyksq?file=src%2Fmain.ts
2. Click on Open in New Tab
3. Open the JS console

### **Expected Behavior**
The project should open in a new browser tab.

I tried it in several Angular projects on StackBlitz. It seems to be always the same error.
FYI In a TS project the project loads as expected in a new tab.

**Comment by GRDtechlab** [comment]
True! I am also facing the same issue. Not opening angular project in new window. https://twitter.com/GaurangDhorda/status/1750536767491764238

**Comment by GRDtechlab** [comment]
Any solution? I`m still facing the same issue. Not able to open angular project into the new window. 
![image](https://github.com/stackblitz/core/assets/96564281/758e544a-418c-4a1c-8bba-1791760bfe4f)

**Comment by HummingMind** [comment]
It's not jsut Angular. Even a basic, static HTML/CSS/JS template throws the same error.
