### ISSUE TITLE
"It looks like you're attempting to sign in to your existing StackBlitz account using a different provider"

### ISSUE THREAD

**Issue by CTheCheese93** [stackblitz/core#2966]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
Cannot login to Stackblitz at all, only option is to login via GitHub which produces the titled error.

### **Steps to Reproduce**
1) Have an account that was not connected via GitHub but shares the same e-mail address as your GitHub account.
2) Attempt to login

### **Expected Behavior**
System should allow me to login, since there are no options for login beyond GitHub.

### **Screenshots/Screencast**

![image](https://github.com/stackblitz/core/assets/50987118/f30824f4-9852-4c5a-a6bc-4e8754659c1c)

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by HeyGarrison** [comment]
👋 Hey there - we only support authentication via GitHub. My suggestion would be to start over and log in via GitHub directly.
