### ISSUE TITLE
Your site does not work if third-party cookies are blocked

### ISSUE THREAD

**Issue by kdawg1406** [stackblitz/core#297]
Your site does not work if third-party cookies are blocked.

EVERYONE blocks third-party cookies.  They are blocked by default in most browsers.

I'm using Chrome, what can I do BESIDES turning on these cookies for all the other sites I visit?

Thank you!!

Karl

**Comment by apai4** [comment]
Hey @kdawg1406, you can add an exception to chrome to allow cookies from our preview domain `[*.]stackblitz.io` (see https://github.com/stackblitz/core/issues/162#issuecomment-357656965) so that you don't have to enable third party cookies globally.

**Comment by kdawg1406** [comment]
Thank you for a VERY fast reply.  Suggestion?  Add this to a link on your awesome site!

**Comment by sreekumarp** [comment]
I would like to reopen this issue.

I cannto add exception in chrome or adding exception is not working as my chrome settings are managed by the company.

3rd party cookies are blocked and there is no way that company is going to allow it.

Can't you make changes in stackblitz and make it work with out 3rd party cookies ?

**Comment by sreekumarp** [comment]
I wonder, how its working in firefox as firefox does not allow 3rd party cookies by itself.

**Comment by dews** [comment]
Although 3rd party cookies are blocked, you may still bypass it by,
chrome://settings/cookies
Find "Sites that can always use cookies", add  "[*.]stackblitz.com"

**Comment by sreekumarp** [comment]
I already mentioned above that company's group policy don't allow us to change the  cookie settings from chrome://settings/cookies.

Please consider this.
