### ISSUE TITLE
Axios Packages Error

### ISSUE THREAD

**Issue by abhisir003** [stackblitz/core#2972]
After installing axios we are getting error, even we already uninstalled, but still same error coming.

Error :

```
Error in turbo_modules/axios@1.6.7/lib/adapters/http.js
The entrypoint for 'https' could not successfully be resolved. The file '/turbo_modules/https@1.0.0/index.js' does not exist. Please log an issue with the package author or check for an updated version of the package.
```

**Comment by atsikov** [comment]
Here's a repro https://stackblitz.com/edit/stackblitz-starters-1hrkxg?description=React%20%20%20TypeScript%20starter%20project&file=src%2FApp.tsx&title=React%20Starter

Importing `axios@>=1` to a module requests additional packages to be installed, and adding these packages leads to the error mentioned in the original post
