### ISSUE TITLE
Broken code example

### ISSUE THREAD

**Issue by Maverick17user** [stackblitz/core#2982]
[https://tanstack.com/query/v4/docs/framework/react/examples/react/basic-graphql-request](https://tanstack.com/query/v4/docs/framework/react/examples/react/basic-graphql-request)

![image](https://uploads.linear.app/387f0a00-26f7-4ea0-9e81-817db5172f2e/e8b6ecf1-f0be-42d7-8914-030d00cb167a/c5172fe3-413a-4e3f-b663-52a464ae668e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM4N2YwYTAwLTI2ZjctNGVhMC05ZTgxLTgxN2RiNTE3MmYyZS9lOGI2ZWNmMS1mMGJlLTQyZDctODkxNC0wMzBkMDBjYjE2N2EvYzUxNzJmZTMtNDEzYS00ZTNmLWI2NjMtNTJhNDY0YWU2NjhlIiwiaWF0IjoxNzA4OTk4MTg4LCJleHAiOjMzMjc5NTU4MTg4fQ.IeB2l09h_JTC1YPZmKOh4g7QmeNhErJzF2n3aETufBI)

**Comment by HeyGarrison** [comment]
Hey there!

It looks like this is actually a bug in TanStack. I'd recommend filing this issue on the TanStack Query repo here: [https://github.com/TanStack/query](https://github.com/TanStack/query)
