### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by ashleymays** [stackblitz/core#2983]
### **Description of Bug**
The terminal does not provide an accurate screenshot of the branch it's supposed to be on, and it does not allow me to use any git commands (git checkout, etc.)

### **Steps to Reproduce**

1. Go to ['this repo'](https://stackblitz.com/~/github.com/ashleymays/piano-keyboard-simulator)
2. Open terminal
3. Type `git checkout master`

**Comment by HeyGarrison** [comment]
Hey there!

It doesn't look like I'm able to reproduce this on my side. Could you try clearing cache and seeing if the problem persists?

**Comment by ashleymays** [comment]
Hey @HeyGarrison thanks for your help. Clearing the cache did the trick! I'll go ahead and close this issue.
