### ISSUE TITLE
I'm unable to signin

### ISSUE THREAD

**Issue by wakechromium** [stackblitz/core#2984]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Screenshots/Screencast**
<img width="719" alt="Screenshot 2024-02-27 at 10 15 04 PM" src="https://github.com/stackblitz/core/assets/74657936/ccbd09ea-76fd-47f1-8e63-e330ffced71b">

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by HeyGarrison** [comment]
Hey there!

Could you email us at hello@stackblitz.com? It makes it a little easier to work out account details, etc.

Thanks!
