### ISSUE TITLE
Unable to see the preview of the code

### ISSUE THREAD

**Issue by Superlilosint** [stackblitz/core#2985]
The preview of the code shows a blank white page only.

![image](https://uploads.linear.app/387f0a00-26f7-4ea0-9e81-817db5172f2e/505e83cb-46ed-4965-9a31-ecb02068bd9f/7a10ac82-0185-401b-8534-12f52089f14b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM4N2YwYTAwLTI2ZjctNGVhMC05ZTgxLTgxN2RiNTE3MmYyZS81MDVlODNjYi00NmVkLTQ5NjUtOWEzMS1lY2IwMjA2OGJkOWYvN2ExMGFjODItMDE4NS00MDFiLTg1MzQtMTJmNTIwODlmMTRiIiwiaWF0IjoxNzEwMzU0Mjk1LCJleHAiOjMzMjgwOTE0Mjk1fQ.Md-5uJsSumhpJr7q8MvxmJFi7weQOUlVL6JuS3gx\_-M)

**Comment by HeyGarrison** [comment]
Hey there!

It looks like you're using EngineBlock, which is one of our first (aka legacy) environments. I'd recommend switching to Webcontainers by using something like[ https://vite.new/](https://vite.new/) or[ https://node.new/](https://node.new/).

You can read more about the available environments here: [https://developer.stackblitz.com/guides/user-guide/available-environments#frontmatter-title](https://developer.stackblitz.com/guides/user-guide/available-environments#frontmatter-title)

For now, I'll close this issue, but feel free to open a new issue if any problems arise with the Webcontainer project.
