### ISSUE TITLE
NPM REGISTRY CREDENTIALS scope input pattern wrong

### ISSUE THREAD

**Issue by SetupCoding** [stackblitz/core#2989]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).
When configuring NPM REGISTRY CREDENTIALS, the input for the scope has a wrong pattern `^@[\w]+(?:,@[\w]+)*$` which excludes scopes for packages like `@stihl-design-system`.

### **Steps to Reproduce**

1. Go to https://stackblitz.com/orgs/github/[your_org]/npm_registries
2. Click on 'Add'
3. Try to enter `@stihl-design-system` as scope

### **Expected Behavior**
The pattern on the scope input element should not filter out dashes `-`

### **Screenshots/Screencast**
![image](https://github.com/stackblitz/core/assets/46531415/94f27bed-043d-4717-acf5-1ae15f99fab6)

**Additional Context/Questions**
I was able to work around the error by removing the pattern in the frontend. The backend accepted the token request accordingly.

**Comment by HeyGarrison** [comment]
👋 Hey @SetupCoding!

Great catch here & thanks for reporting this. We have a fix coming imminently for this and I will update you once released!

Glad you were able to work around this by bypassing the frontend validation!

**Comment by HeyGarrison** [comment]
👋 Just following up on this issue - we shipped a fix a few weeks ago.

Let me know if you have any additional questions or need help!

Btw, @SetupCoding you can reach me at garrison at SB dot com - would love to hear more about what you're working on these days!
