### ISSUE TITLE
Stackblitz keeps state " importing  from Github"

### ISSUE THREAD

**Issue by vugar005** [stackblitz/core#299]
Hi
When trying to import the angular project to stackblitz it stucks on start up screen 
`"Importing from Github..."`

The link to the project : ( https://github.com/vugar005/TMIS-app)  
Thanks in advance

**Comment by L0MiN** [comment]
I have the same problem, did you already solved this?

**Comment by vugar005** [comment]
Unfortunately not.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
