### ISSUE TITLE
Can't use primeng

### ISSUE THREAD

**Issue by sbkpilot1** [stackblitz/core#300]
I've imported primeng@5.2.0 into the dependencies but when I import it in app.module.ts it says primeng/primeng cannot be found.

https://stackblitz.com/edit/test-primeng?file=app%2Fapp.module.ts

**Comment by EricSimons** [comment]
@sbkpilot1 it looks like the primeng import isn't in the appmodule- did you forget to save it by chance?

**Comment by micahwood** [comment]
I'm seeing the same issue, when you try to import anything from primeng it stays 'cannot find module'

https://stackblitz.com/edit/angular-1gs8ju?file=app%2Fapp.module.ts

**Comment by micahwood** [comment]
Actually, looks like I can still import and use it, despite the editor saying it cannot find that module.

**Comment by sbkpilot1** [comment]
@EricSimons it removes the import when I try to save it because it complains that it can't find it.

@micahwood thanks, will have to try it out, but looks like it is a bug?

**Comment by sree332** [comment]
I also ran in to the same issue , i see an module not found error but I can use some of the components but when i use the calendar then i see an error.

**Comment by caitlinrouille** [comment]
I am also running into the same issue, I cannot import any primeng modules in the app module file without getting the primeng red squiggily line.

**Comment by johnrnyquist** [comment]
FWIW, I'm having the same issue with primeng.

**Comment by SergiuTalnaci** [comment]
I have the same issue.

**Comment by shijithkm** [comment]
Any update here i am also facing the same issue 
[](https://stackblitz.com/edit/angular6-primeng)

**Comment by dicbrus** [comment]
somebody managed to solve or found workaround, I also faced the same issue.

**Comment by iaunzu** [comment]
Same thing happens with version 6

**Comment by dicbrus** [comment]
@Shrinivassab 
actually the issue is that you see red underline, nevertheless library is imported and available for injection, try it

**Comment by dicbrus** [comment]
@Shrinivassab 
it is not related to the import issue,
you need to add styles into angular.json file
```
            "styles": [
              "node_modules/primeng/resources/themes/omega/theme.css",
              "node_modules/primeicons/primeicons.css",
              "node_modules/primeng/resources/primeng.min.css",
              "src/styles/styles.scss"
            ],
```
here is the example https://primeng-list.stackblitz.io

**Comment by Shrinivassab** [comment]
@dicbrus thanks. I got it working.

**Comment by lodela** [comment]
I'm trying to upload a sample that I've made for a lecture that I'm planning to give to my organization... but simply I can't make primeng work properly... ie. sortable columns, won't work... prime icons, won't work the right way, we have to make an extra @import in styles... so, for me it does not work... we have to make ti work... instead the transparent way like in my local machine... or my prod server... or, google cloud (needless to say google it's the best cloud server.) ... too many bugs.

**Comment by lodela** [comment]
> @Shrinivassab
> it is not related to the import issue,
> you need to add styles into angular.json file
> 
> ```
>             "styles": [
>               "node_modules/primeng/resources/themes/omega/theme.css",
>               "node_modules/primeicons/primeicons.css",
>               "node_modules/primeng/resources/primeng.min.css",
>               "src/styles/styles.scss"
>             ],
> ```
> here is the example https://stackblitz.com/edit/primeng-list

still don't work... have several error look at the console... simply won't load styles... why?

**Comment by sulco** [comment]
With the updates to the platform, it's no longer an issue - just confirmed that with https://stackblitz.com/edit/primeng-list + a fixed reproduction of the original post https://stackblitz.com/edit/test-primeng-repro?file=app/app.module.ts
