### ISSUE TITLE
Hovering Over Color Palette over the Terminal Section.

### ISSUE THREAD

**Issue by karanjoshi260** [stackblitz/core#3000]
### Describe the bug

The color palette got closed when hovering over the terminal section.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-starters-73kp7t?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts,src%2Findex.html,src%2Fglobal_styles.css&template=node&title=Angular%20Starter

### Steps to reproduce

1. Open Style.css
2. Select any styling which includes color
3. Click on the color square box before the colorname/ colorcode
4. Make the color palette span the editor window and over lapping the terminal section of the editor
5. Hover over the color palette and try crossing the editor section towards terminal section
6. Doing so closes the color palette without choosing or selecting any color.

### Expected behavior

Color palette should be closed only when a color is selected or when hovering outside the palette.
![Screenshot 2024-03-07 021914](https://github.com/stackblitz/webcontainer-core/assets/16691102/92d41ad6-90bd-4669-bcdd-773feceaa9c7)

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![Screenshot 2024-03-07 021914](https://github.com/stackblitz/webcontainer-core/assets/16691102/a07fb360-40b3-4c8c-8bfd-f78f7272d8d6)

### Platform

```
Browser name  = Chrome
Full version  = 122.0.0.0
Major version = 122
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 112840573,
  "usedJSHeapSize": 101446969,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8e1c3ef8
```

### Additional context

In my first 5 attempt I failed to select the color I wanted to choose and also got confused if the issue is with my mouse.

**Comment by HeyGarrison** [comment]
Hey there!

Sorry about this bug - could you attach a working project URL? it looks like the one you linked might be private b/c I get a 404 when trying it.
