### ISSUE TITLE
i have a project i downloaded but deleted how do i get it back to stackblitz

### ISSUE THREAD

**Issue by AntoanJOnesTech44** [stackblitz/core#3005]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by HeyGarrison** [comment]
Hey there! You can simply create a new project at[ https://node.new](https://node.new) and drag and drop the files into the filetree.

Hope that help!
