### ISSUE TITLE
when ever I try to reload the page it lags all of the time some time it shows the page some time it's completely blank. For this reason it is very difficult to work in this platform

### ISSUE THREAD

**Issue by SomsubhroChakraborty** [stackblitz/core#3008]
### **Description of Bug**

when ever I try to reload the page it lags all of the time some time it shows the page some time it's completely blank. For this reason it is very difficult to work in this platform 

### **Expected Behavior**
shows the webpage updated with the changes I have done on it

### **Screenshots/Screencast**

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by fvsch** [comment]
Hi @SomsubhroChakraborty,

What page are you referring to?

**Comment by SomsubhroChakraborty** [comment]
https://stackblitz.com/edit/vitejs-vite-lnhouh?file=src%2FComponents%2FNavbar.jsx
This one

**Comment by Nemikolh** [comment]
Hey @SomsubhroChakraborty! :wave: 

Your component `Contact.jsx` has no default export. It's seems to be an empty file. The blank page is caused by react because you don't have an error boundary. See https://react.dev/reference/react/Component#catching-rendering-errors-with-an-error-boundary.
