### ISSUE TITLE
creating a new project from remix template breaks

### ISSUE THREAD

**Issue by lifeiscontent** [stackblitz/core#3015]
when creating a new Remix Project I see this error:

![Screenshot 2024-03-29 at 11 55 56 AM](https://uploads.linear.app/387f0a00-26f7-4ea0-9e81-817db5172f2e/ede3c1e8-de78-4253-812f-03211836a182/d5393f43-2b24-42d0-87b2-ec01f0c9dffb?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM4N2YwYTAwLTI2ZjctNGVhMC05ZTgxLTgxN2RiNTE3MmYyZS9lZGUzYzFlOC1kZTc4LTQyNTMtODEyZi0wMzIxMTgzNmExODIvZDUzOTNmNDMtMmIyNC00MmQwLTg3YjItZWMwMWYwYzlkZmZiIiwiaWF0IjoxNzE2Nzk5NDY4LCJleHAiOjMzMjg3MzU5NDY4fQ.9fbdZP0CUGlbGogUPEXVYjwo4xkTywhxfDn25CWllgY)

**Comment by apai4** [comment]
Thanks for reporting this! It looks like `templates/vite` was replaced in favor of `templates/remix` in https://github.com/remix-run/remix/pull/9152. We've updated to point at `templates/remix` so creating a new remix project should be working again.
