### ISSUE TITLE
Remix template is broken

### ISSUE THREAD

**Issue by unclejustin** [stackblitz/core#3016]
Steps to reproduce:

1. Create a new project
2. Select Remix
3. Be sad

![PixelSnap 2024-03-29 at 15 27 10](https://github.com/stackblitz/core/assets/1855233/a7cf06e3-6839-4186-bd90-715f82d98665)

**Comment by apai4** [comment]
Thanks for reporting this! It looks like `templates/vite` was replaced in favor of `templates/remix` in https://github.com/remix-run/remix/pull/9152. We've updated to point at `templates/remix` so creating a new remix project should be working again.

**Comment by saidakharbouchi** [comment]
so if i sa ve a problem concerning the lunch of my project  i  just have  to update the new version of stackblitz
