### ISSUE TITLE
We currently only support projects scaffolded with @angular/cli.

### ISSUE THREAD

**Issue by addyfreek** [stackblitz/core#302]
I am getting error while linking my github repo.

https://github.com/addyfreek/Product

![error while upload](https://user-images.githubusercontent.com/16472907/36577475-7e56f7cc-187d-11e8-9b99-c5e3bdd02d1d.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
