### ISSUE TITLE
Unable to format

### ISSUE THREAD

**Issue by crazyair** [stackblitz/core#3023]
### **Description of Bug**
Provide a concise description of your bug and your project link (if applicable).

https://stackblitz.com/edit/react-jnagw4?file=demo.tsx

### **Steps to Reproduce**

1. Right click
2. Click format document

### **Expected Behavior**

can format

### **Screenshots/Screencast**

![image](https://github.com/stackblitz/core/assets/7971419/66cef00d-5741-4720-bd49-bc4d7a423439)

**Additional Context/Questions**
Add any other context or questions regarding this bug.

**Comment by fvsch** [comment]
Hi @crazyair.

Thanks for the report! This is indeed an issue with the version of Prettier we're using for this feature. An update is planned.

**Comment by fvsch** [comment]
We shipped a fix for this issue yesterday.

The classic editor is now using Prettier `2.8.8` (instead of `2.4.0`), which supports most of the recent syntax additions in TypeScript 5.
