### ISSUE TITLE
JSPlumb not working

### ISSUE THREAD

**Issue by vishalbiradar** [stackblitz/core#303]
I have tried to integrate JSPlumb with Angular, But your Online editor is throwing an error for jsplumb.
Please have a look at the below code:

https://stackblitz.com/edit/angular-jsplumb

My actual code repo:
https://github.com/vishalbiradar/angular-jsplumb

Please help me.
<img width="1409" alt="screen shot 2018-02-24 at 12 56 02 pm" src="https://user-images.githubusercontent.com/29951629/36626970-3360a62e-1962-11e8-807e-378c127c376c.png">

**Comment by seveves** [comment]
Don't declare a var on top but use `import { jsPlumb } from 'jsplumb';` instead.

**Comment by vishalbiradar** [comment]
@seveves 
Thanks a lot.
Its working fine now.
