### ISSUE TITLE
Console.clear(), clears all global variable expose to window object

### ISSUE THREAD

**Issue by ravi-dhiman-tas** [stackblitz/core#306]
if you add something like this:
```
window.customFunction = () => { // some code }
```

and then try to execute `customFunction()` from console. It throw an error.

```
VM3581:1 Uncaught ReferenceError: customFunction is not defined
    at <anonymous>:1:1
```

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you!
