### ISSUE TITLE
Unable to fetch Nuxt layer GitHub dependencies in Codeflow (CORS error)

### ISSUE THREAD

**Issue by MexicanAce** [stackblitz/core#3077]
### **Description of Bug**
The [zksync-docs](https://github.com/matter-labs/zksync-docs) repo uses Nuxt Layers, and more specifically references other public GitHub repos ([see nuxt.config.ts file here](https://github.com/matter-labs/zksync-docs/blob/main/nuxt.config.ts#L3)). When opening the repo in Codeflow, the terminal will fail to run `npm install` and output the following error:

```log
> npm install
[...]
> zksync-docs@0.0.0 postinstall
> nuxt prepare


[10:36:59 AM]  ERROR  Failed to download https://api.github.com/repos/matter-labs/docs-nuxt-template/tarball/main: TypeError: fetch failed

  at eval (node_modules/giget/dist/index.mjs:78:11)
  at async sendFetch (node_modules/giget/dist/index.mjs:74:15)
  [... rest of stack trace ...]
```

After further investigation, it looks like this is due to a CORS error:
```log
Access to fetch at 'https://codeload.github.com/matter-labs/docs-nuxt-template/legacy.tar.gz/refs/heads/main' (redirected from 'https://api.github.com/repos/matter-labs/docs-nuxt-template/tarball/main') from origin 'https://zksyncdocs-a2ws.w-credentialless-staticblitz.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

### **Steps to Reproduce**

1. Go to https://pr.new/github.com/matter-labs/zksync-docs
2. Wait for `npm install` to automatically start and see the fetch failures

### **Expected Behavior**
`npm install` successfully completes

### **Screenshots/Screencast**
![image](https://github.com/stackblitz/core/assets/1890113/af20b8a9-865a-4657-8327-18732f2233de)

**Comment by samdenty** [comment]
We recently added support for Cors Proxy, which may fix this issue https://blog.stackblitz.com/posts/cors-proxy/. Though because it's coming from NPM, I'm not 100% sure

**Comment by MexicanAce** [comment]
@samdenty Good to know, I'm trying to use the new flag but I keep getting prompted with the following modal (I've upgraded my account today, so maybe it takes a while to reflect within the IDE?)
![image](https://github.com/stackblitz/core/assets/1890113/5abfe4cc-308e-4e67-99a2-bd59c62ba01b)

**Comment by samdenty** [comment]
Cc @d3lm @Nemikolh

**Comment by MexicanAce** [comment]
It's been over a week after I've upgraded my account, and I still get this popup. So doesn't look like an issue related to timing.

**Comment by kirjavascript** [comment]
> It's been over a week after I've upgraded my account, and I still get this popup. So doesn't look like an issue related to timing.

hi! We've looked into the issue and in the process of fixing it uncovered some other issues related to it. Once they are resolved we can deploy the fix.

It should be resolved soon!

**Comment by MexicanAce** [comment]
Hi @kirjavascript 👋 , any update on a fix?

**Comment by samdenty** [comment]
Hi @MexicanAce we have a fix merged but it's not deployed yet, i'll see to it that it's deployed now

**Comment by kirjavascript** [comment]
sorry for the delay, but the fix should be deployed now!
