### ISSUE TITLE
Embed Not Working

### ISSUE THREAD

**Issue by eastcoastdeveloper** [stackblitz/core#3096]
I'm embedding Stackblitz projects in a number of website posts and they are no longer working on mobile. I'm not sure when this began, but I noticed it yesterday. This is in Safari on an iPhone 14 I believe. Nothing shows. The space where the embed is, is just a blank white space.

**Comment by apai4** [comment]
Thanks for reporting this, @eastcoastdeveloper! We've released an update that addresses this issue, can you confirm embeds are working on your iPhone again?

**Comment by eastcoastdeveloper** [comment]
Looking good! That was super quick—thank you!!
