### ISSUE TITLE
Angular - head does not contain base element

### ISSUE THREAD

**Issue by Toxicable** [stackblitz/core#31]
Repo here: https://stackblitz.com/edit/angular-template-routing-edc7h3

You can see by checking the console it throws when trying to use the router
>Error: No base href set. Please provide a value for the APP_BASE_HREF token or add a base element to the document.

also by inspecting the DOM you can see this tag is indeed not present.
Usually the CLI generates a project with the `<base href="/">` in the head on the index.html, inserting this tag will solve this issue when trying to use routing

**Comment by EricSimons** [comment]
Good catch - were adding a meta tags config feature thats landing soon, but until then if you just use hashbang routing it should work! See https;//stackblitz.com/edit/angular-realworld for a running example

**Comment by EricSimons** [comment]
I put in a quick fix for this that's now live on prod — all previews now have `<base href="/">` set on them 👍
