### ISSUE TITLE
Support private NPM registries

### ISSUE THREAD

**Issue by EricSimons** [stackblitz/core#313]
We're working on this- feel free to subscribe to this thread for updates 👍

**Comment by cgatian** [comment]
@EricSimons I hope this is what I think it is. 
Are you talking about npm's [private scoped packages](https://docs.npmjs.com/private-modules/intro) or private package servers like [ProGet](https://inedo.com/proget)?

**Comment by awentzel** [comment]
@EricSimons the request was for NPM's Private scoped packaged.

**Comment by sereymonyros** [comment]
Whow - can't wait to see/use stackblitz && private scoped npm packaged together... thanks @awentzel  && @EricSimons

**Comment by padmkris123** [comment]
Any ETA on this?

**Comment by calebdwilliams** [comment]
Would the potentially work with jFrog's Artifactory as well?

**Comment by magikMaker** [comment]
Any news on this?

**Comment by juanmendes** [comment]
Are you still working on it. Do you need laborers? I'm willing to put in some hours! I really would like this so we can showcase internal UI component libraries

**Comment by AKrasovski** [comment]
Absolutely need this feature!

**Comment by edimitchel** [comment]
Any news about private registries? Is Web Containers allows to contact private registries using local network?

**Comment by vineshkumar87** [comment]
Any update on this one?
