### ISSUE TITLE
IE 11 sidenav select styling is off

### ISSUE THREAD

**Issue by crutchcorn** [stackblitz/core#318]
![image](https://user-images.githubusercontent.com/9100169/37045284-7003ca60-211a-11e8-8c78-7e5541fa8b33.png)

**Comment by seveves** [comment]
You are blessed. In my IE 11 it is not even loading 🤕

**Comment by crutchcorn** [comment]
@seveves It no longer loads for me as well. Is there a GH issue with this bug's behavior documented or shall I create a new one?

**Comment by seveves** [comment]
We should create a new one ... are you going for that? Thanks!

**Comment by crutchcorn** [comment]
#359

**Comment by purplem1lk** [comment]
Hey there - Thanks for your patience! I just confirmed with our dev team that we will not be supporting IE11, but have noted the styling for our UX designer to take a look at. This issue will be closed accordingly - Feel free to tag me if you have further questions. Thank you! :)
