### ISSUE TITLE
iOS - Arrow keys not working in Monaco

### ISSUE THREAD

**Issue by ateev** [stackblitz/core#32]
Hi !  Thanks for making this awesome editor in the browser. Because of this I can finally code in my iPad Pro :)

There’s one issue that i’m experiencing. I’m using the iPad Pro keyboard and the arrow keys don’t seem to work on the editor. Please look into this :)

**Comment by EricSimons** [comment]
This is actually a problem with VS Code's Monaco editing engine itself — they explicitly state that they don't 100% support mobile :( Will see if we can figure out workarounds for this though!
