### ISSUE TITLE
How to prevent some projects from autorun?

### ISSUE THREAD

**Issue by limonte** [stackblitz/core#320]
In some cases (e.g. application steals focus) it's not fun to return focus to the text editor after each change.

In jsbin there's an option to prevent live preview update on each change (checked by default):

![](https://i.imgur.com/uekn5ZX.png)

It would be nice to have the same for stackblitz

Thanks for the amazing sandbox for React!

**Comment by equinusocio** [comment]
<img width="306" alt="screen shot 2018-03-11 at 12 40 32" src="https://user-images.githubusercontent.com/10454741/37252868-6c021634-2529-11e8-85ec-961b3fc75763.png">

**Comment by limonte** [comment]
Thank you @equinusocio, this is exactly what I was looking for!

![](https://i.imgur.com/HPfs3qn.png)
