### ISSUE TITLE
Stackblitz can not find 'angularfire2/firestore'

### ISSUE THREAD

**Issue by rezolve** [stackblitz/core#321]
Please check out my stackblitz. 

https://stackblitz.com/edit/angular-xscicw?file=app%2Fapp.module.ts

It can not find the following, although I believe I have all the required dependencies installed? Do you have any advice?

import { AngularFirestoreModule } from 'angularfire2/firestore';

Thank you!
David

**Comment by seveves** [comment]
You were missing two dependencies (@firebase/app and @firebase/app-types).
See here: https://stackblitz.com/edit/angular-yxdevx?file=app/app.module.ts

**Comment by rezolve** [comment]
Awesome, thank you!
