### ISSUE TITLE
Can I preview Markdown ?

### ISSUE THREAD

**Issue by jagadeeshtechgeek** [stackblitz/core#322]
Can I preview Markdown?

PM:
This is really amazing IDE. I never ever felt this much comfort in online IDE. Thanks and Appreciated your efforts.

Soon expecting Github sync feature

**Comment by seveves** [comment]
Github Sync is already possible for angular-cli and create-react-app projects: See here: https://stackblitz.com/docs#import-from-github

Markdown-Preview is not yet a feature as far as I know ... @EricSimons possible/planned feature?

**Comment by jagadeeshtechgeek** [comment]
@seveves  Can I do `git push`?   **Stack Blitz** --to--> Github

**Comment by seveves** [comment]
Once created a project out of a github repo via the SDK (the link I've posted earlier) it stays in sync. At least that's what the docs say: 

> Whenever you push commits to Github, the corresponding StackBlitz project automatically updates with the latest changes — ensuring Github remains your code’s source of truth.

**Comment by jagadeeshtechgeek** [comment]
Thanks, @seveves  for the response. 
 My question was different **Stack Blitz** --to--> **Github**
- For example, I made a file change on Stack Blitz IDE,  I need that change to be available in my Github.
 `from **Stack Blitz** --to--> **Github**`

I belive document tells sync:  from **Github**  ---to--> **Stack Blitz** 

I tried importing from Github, it worked. But I cannot make any changes to Git, It can only store in Stack Blitz.  :disappointed:

**Comment by EricSimons** [comment]
Yup! We're working on both a markdown preview features AND committing back to github :)

Both of these will likely land in 1-2 months; will circle back once they're online 👍

**Comment by jagadeeshtechgeek** [comment]
That will be awesome!! eagerly waiting 😮

**Comment by fireflysemantics** [comment]
Any news on this?

**Comment by Dinkh** [comment]
I can preview a markdown file. But I need the preview to open by default. Currently I have to presss the preview button and then it will stay as preview.
I would prefer an empty md file to open in editor mode and a saved md file in reader mode.
It would be cool if this could be configured in the settings.

**Comment by enaros** [comment]
> I can preview a markdown file. But I need the preview to open by default. Currently I have to presss the preview button and then it will stay as preview. I would prefer an empty md file to open in editor mode and a saved md file in reader mode. It would be cool if this could be configured in the settings.

how do you do it?

**Comment by ggdaltoso** [comment]
Hey, @enaros 

You can use the built-in "Open Preview" pane to help you.

https://github.com/stackblitz/core/assets/6536985/d8b6df8e-4a1a-487c-bbeb-8994a0a34011

project: https://stackblitz.com/~/edit/node-ud6efz

**Comment by enaros** [comment]
Great! Sadly I think it isn’t available for the embedded option
