### ISSUE TITLE
material.angular.io examples not working on stackblitz.com - please help...

### ISSUE THREAD

**Issue by monetisedminds** [stackblitz/core#324]
Hello,

The examples on the materialangular.io site don't seem to work on stackblitz - which is annoying - please can this be fixed?

I tried using latest versions of Chrome, FireFox and Edge from Windows 10 - no joy...

https://material.angular.io/components/sidenav/overview

https://stackblitz.com/angular/gkmvlkvxvam?file=index.html

Thanks

**Comment by EricSimons** [comment]
@monetisedminds that example seems to load fine for me... can you send screenshots/errors in console/etc?

**Comment by arjunkneworld** [comment]
I couldn't see any example from io site works on stackblitsz. Here is the error I see on console.
```
Uncaught (in promise) TypeError: Cannot read property 'defaultExtension' of undefined
    at Object.generateConfig (engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:3)
    at Object.start (engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:3)
    at preview-011e8381add39bb8861c.js:1
```
Please help me.

**Comment by Splaktar** [comment]
They are working fine for me. There was an issue a few weeks ago with Firebase Hosting and the CDNs that may have caused this. That was resolved.

**Comment by james-yin** [comment]
I'm having the same error message (`Cannot read property 'defaultExtension' of undefined`) on a stackbliz project I'm working on. When you run the URL with stackblitz.com development UI (https://stackblitz.com/angular/gkmvlkvxvam?file=index.html), it works fine. But when you take the stand-alone url (https://vqvkrekvgga.angular.stackblitz.io in this case) and put that in another instance of the browser (not a tab, i.e. 'New incognito window'), then you will get the `Cannot read property 'defaultExtension' of undefined` error in the console.

This is frustrating as I could not just pass the stand-alone URL to the client for review.

**Comment by schaveyt** [comment]
Recommend closing this.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists with StackBlitz, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
