### ISSUE TITLE
Tech behind previewing 

### ISSUE THREAD

**Issue by gujiman** [stackblitz/core#326]
How does the tech behind previewing your project work? I understand you use SystemJs. Will you be open sourcing your preview code? 

I'm talking about these files:
https://c.staticblitz.com/assets/packs/preview-0b6b23eb5cf18b6ecbdebf7842839e39.css
https://c.staticblitz.com/assets/packs/common-6ae27974dbdb8229b256.js
https://c.staticblitz.com/assets/engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js
https://c.staticblitz.com/assets/packs/preview-011e8381add39bb8861c.js

Cheers!

**Comment by kc0tlh** [comment]
The best place to learn more about our technology is [blog.stackblitz.com](https://blog.stackblitz.com/). Cheers!
