### ISSUE TITLE
What is Stackblitz License?

### ISSUE THREAD

**Issue by thezillia** [stackblitz/core#327]
Hello, 

I see repo doesn't have License notice. 

May I ask what is the license of Stackblitz? 

Thank you,

**Comment by AbhinavAtul** [comment]
[**You may not modify, reproduce, republish, frame, download, transmit, distribute, rent, lease, loan, sell, assign, license, sublicense, reverse engineer, publicly display or create derivative works based on the Services, any of StackBlitz's Content in whole or in part, or the Site except as expressly authorized in writing by StackBlitz.**](https://stackblitz.com/terms-of-service)


Does this mean if you are learning some angular concepts on StackBlitz, you are not supposed to *create derivative works* for your own software, lol, I would appreciate if this is included in all code files as the © copyright/license notice cc @EricSimons

**Comment by AbhinavAtul** [comment]
thank you stack blitz, i will not visit you anymore until you plan to have a **Creative Commons license**

**Comment by purplem1lk** [comment]
Hey there! The core repository has been updated with the MIT license notice: https://github.com/stackblitz/core/blob/master/LICENSE
