### ISSUE TITLE
"edit on stackblitz" link broken in Embed 

### ISSUE THREAD

**Issue by ilyjs** [stackblitz/core#328]
When clicking "Edit stackblitz" button, it redirects to https://stackblitz.com/run instead of the the actual editor.
https://stackblitz.com/edit/sdk-create-project

**Comment by Hypercubed** [comment]
Not sure if this is the same issue but you can see this in their own demo project:

https://stackblitz.com/edit/sdk-create-project

If you click the "Open in new window" button it will open a new tab with an editor and the right content.  If you click the "Embed" button, then "edit on ⚡ stackblitz" link in the embedded view, you get the stackblitz homepage.

**Comment by erwanv** [comment]
Issue is still present. The edit on stackblitz link is broken

**Comment by sulco** [comment]
Thanks for reporting! With the series of updates to our UI and specifically file tree implementation, this should not be an issue anymore, but please feel free to reopen if you stumble upon it again.
