### ISSUE TITLE
The editor breaks when using .scrollIntoView();

### ISSUE THREAD

**Issue by ibenjelloun** [stackblitz/core#329]
When using `document.querySelector('#id').scrollIntoView();` the editor scrolls as long as the preview.
A right click in the editor will fix this behavior.

Example :
https://stackblitz.com/edit/angular-scroll-spy-routing?file=app%2Fhappy-scrolling.component.ts

Tested on chrome 62.0.3202.62 (Build officiel) (64 bits).

**Comment by ibenjelloun** [comment]
Not reproductible anymore on chrome "Version 69.0.3497.100 (Build officiel) (64 bits)" and the latest stackblitz version.

**Comment by gergelypap** [comment]
I could reproduce this! I found that the issue only appears when there are files opened in the editor.

Both the link provided by OP and my link: https://stackblitz.com/edit/js-hkegcb?file=index.js

OS: Mac OS Monterey 12.5
Chrome: Version 104.0.5112.79 (Official Build) (x86_64)
Firefox: 103.0.2 (64-bit)
MS Edge: Version 104.0.1293.54 (Official build) (x86_64)
Safari: it works, lol.
