### ISSUE TITLE
Buffer is not defined for create-hash which breaks crypto-browserify

### ISSUE THREAD

**Issue by abhishiv** [stackblitz/core#330]
Sample available here - https://stackblitz.com/edit/react-at1wsl?file=index.js

Offending file is [here](https://cdn.jsdelivr.net/npm/create-hash@1.1.3/make-hash.js), and it seems because of missing global called Buffer

**Comment by abhishiv** [comment]
Could be related to this SystemJS issue - systemjs/systemjs#1724

**Comment by abhishiv** [comment]
Update: played around with JSPM which also uses SystemJS and it seems it adds a global entry for Buffer

```{
  "main": "index.js",
  "format": "cjs",
  "meta": {
    "make-hash.js": {
      "globals": {
        "Buffer": "buffer/global"
      }
    }
  }
}```

@EricSimons any idea about this?

**Comment by EricSimons** [comment]
Thanks for the detailed info @abhishiv! Will investigate this tmrw/Fri and circle back once I've got it fixed 👍

**Comment by Brunomachadob** [comment]
Hey guys!

Any updates on this? This problem just happened to me, using Joi.
And it's also complaining about the net package.

Example:
https://stackblitz.com/edit/joi-error?file=index.js

**Comment by sulco** [comment]
Thanks for reporting! This should not be an issue anymore, but please feel free to reopen if you stumble upon it again.
