### ISSUE TITLE
HttpErrorResponse trying to read local json file

### ISSUE THREAD

**Issue by james-yin** [stackblitz/core#331]
I'm trying to read a local json file using Angular and got HttpErrorResponse in the browser. The same code and structure works outside of Stackblitz with just angular-cli. Is there something that I need to do additionally in Stackblitz to make it read a local json file?

Here's the link to the project - https://stackblitz.com/edit/angular-z6r1g6?file=app%2Fapp.component.ts

**Comment by sarangud** [comment]
I am facing the same issue..

**Comment by seveves** [comment]
Do you guys really need the static JSON asset or are you fine with using a plain javascript object instead?
You could use it that way (simulating the http fetch with some dely): https://stackblitz.com/edit/angular-vdjvbp?file=app%2Fdata.service.ts

**Comment by johnpapa** [comment]
i have the same issue. i like getting from a json file because it allows me to show people how to use http without involving patch code./

**Comment by seveves** [comment]
@johnpapa I see ... as a workaround you could fetch the json directly from github or any other file hoster (f.e. lite-server + now 🍻). I think we have to wait till #72 lands 😞

**Comment by EricSimons** [comment]
Yeah @seveves is correct, this is related to john's other issue https://github.com/stackblitz/core/issues/577#issuecomment-401465638

The past 2 months has been filled with hiring & onboarding for us (hence the delay on this), but we're now ramping up our eng so I'm pretty confident we'll have this online in July 🙂

**Comment by FatemeFazli** [comment]
try by moving that json in assets folder(Note: you have to reload stackblitz to make it working):
```http.get('/assets/data.json')```
[working demo](https://stackblitz.com/edit/angular-httpclient-local-data-18m62h).

**Comment by mohit1697** [comment]
There is a solution if you are just practicing, make a folder named **public** at the root level of your project and move the resource you want to access using ajax in it.
e.g resource: ./public/data.json
you can access it by:
`let request = new Request("/data.json"); // **do not** mention url as/public/data.json
 fetch(request)
 .then((data)=>{
      console.log(data);
      // your code
 });`

It will work as by default webpack provides access folder named publc(static content).
