### ISSUE TITLE
Can't add TypeScript to project

### ISSUE THREAD

**Issue by justinfagnani** [stackblitz/core#334]
I have a plain JS project, and if I try to rename a file to a .ts extension I get an error. How do I enable TypeScript for a project?

**Comment by EricSimons** [comment]
Right now you'd need to fork our typescript starter project if you want to use TS (https://stackblitz.com/fork/typescript). Curious about your use case here of mixing JS & TS- perhaps we could create a custom project template for it?

**Comment by justinfagnani** [comment]
The use case is that I started with a vanilla JS project and wanted to add in some TypeScript once I got that working. One of the best things about TypeScript is how easy it is to incrementally adopt to existing code :)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
