### ISSUE TITLE
How to find the TS version i'm using ? 

### ISSUE THREAD

**Issue by RoyiNamir** [stackblitz/core#337]
Is it possible to find the TS version currently being editing with ?

**Comment by seveves** [comment]
I couldn't find a way to find this out by code.
But I think it would be a neat feature to see the current TypeScript version used by stackblitz like you can see in vscode in the bottom statusbar.
What do you think?

**Comment by RoyiNamir** [comment]
@seveves  I think it would be great!
Besides , all modules that are loaded without being visible in the packages section , should be seen ( their version) somewhere.

Also , another thing ( I use stackblitz a lot) : please show a "saved" message when a A CTRL+s.  All you do is change the querystring without nothing being ack to the user.

Also , if you can change the default template of angular to a lazy loaded module template.

Great job

**Comment by seveves** [comment]
All the honor belongs to @EricSimons and not me but I'm also glad that you like stackblitz :)

When hitting CTRL+S the save button changes its color from blue to grey as an indicator for a successful save operation.

I'm not sure if we'll change the angular template or add another one in the future. The angular-cli has no option to create a new project with lazy routing (as you can see [here](https://github.com/angular/angular-cli/wiki/new)) and so we keep the template it simple at the moment :)

**Comment by ffMathy** [comment]
Why has this been closed? It hasn't been fixed, has it?

**Comment by RoyiNamir** [comment]
@ffMathy 4 month to add one line at the bottom ( TS version)..... I think they don't want to do that....
Too bad.... That's why I closed it

**Comment by EricSimons** [comment]
@royinamir we’re a 2 man team with limited resources. The past four months we’ve been working on large high priority upgrades, a handful of which are required to make this “one line” change work reliably (specifically allowing the user to install & use specific typescript versions).

Reopening so I can circle back once we implement this

**Comment by hadnet** [comment]
2022 and still this shi*. Unbelievable…

**Comment by ffMathy** [comment]
> 2022 and still this shi*. Unbelievable…

Unbelievable?

They already mentioned they are a 2-man team with limited resources.

It's an open source project with almost 500 open issues. You're welcome to make your own pull request. 

But in the meanwhile, unless you send a big donation their way, paying them for the excellent work they do, sit tight and relax, or start contributing.

**Comment by hadnet** [comment]
screw you. If you decide to offer a service, do it decently, If not prepare to hear complains. It's life. Now I know why it is free. Almost 3 years for this? Dont try to justify the unjustifiable.

**Comment by ffMathy** [comment]
> screw you. If you decide to offer a service, do it decently, If not prepare to hear complains. It's life. Now I know why it is free. Almost 3 years for this? Dont try to justify the unjustifiable.

Wow, I am speechless. Which part of it is unjustifiable? 2 people. 500 issues. Seems kind of justifiable to me.

You're using this for free without doing anything in return. The people behind this are not getting paid for working for you, and yet you complain about it taking time.

I wish you luck with that attitude. This turned hostile super quick - I'm out.

**Comment by hadnet** [comment]
screw you twice. Because of this I can't do nothing and it's worthlesss, just wasted my time because I thought I was doing something wrong just to figure it out this shi** one hour later. Thank God there is free market and other alternatives. I'm out of this.

**Comment by tannerlinsley** [comment]
Loving stackblitz and it's growth is outstanding! Keep the up the good work!

Just passing through but I thought I'd at least say that this issue should likely be locked to only maintainers, or at the very least @hadnet's unproductive and unhelpful comments be hidden.

@hadnet, I take open source etiquette very seriously, so in case you forgot, this is a professional open source website where your comments will be preserved forever. That said, if you insist on acting entitled, I request that you provide me with links to your own projects/products or even better any public source code that you've built or worked on. I'm sure others would like to try them out and offer you some of the same whiney complaints you have so rudely left here.

**Comment by hadnet** [comment]
> Loving stackblitz and it's growth is outstanding! Keep the up the good work!
> 
> 
> 
> Just passing through but I thought I'd at least say that this issue should likely be locked to only maintainers, or at the very least @hadnet's unproductive and unhelpful comments be hidden.
> 
> 
> 
> @hadnet, I take open source etiquette very seriously, so in case you forgot, this is a professional open source website where your comments will be preserved forever. That said, if you insist on acting entitled, I request that you provide me with links to your own projects/products or even better any public source code that you've built or worked on. I'm sure others would like to try them out and offer you some of the same whiney complaints you have so rudely left here.

FYI, everyone has the right to freedom of opinion and expression (so it's not only what you like or want, ok). It's not a crime to complaint (rudely or not). If my project takes YEARS to fix a simple issue, I well deserve a complaint you know (and btw, for sure I won't act like a snowflake like you).

**Comment by tannerlinsley** [comment]
It's definitely not a crime, but it is more than likely against this repo's code of conduct and likely in breach of what Github would want to allow on their system. Regardless, even if we entertain your notion that you're acting justified, it still doesn't do you any favors nor is it even the strategic choice for your own agenda to act this way, eg. your specific issue is now less likely to get fixed (if it does, it will because of the positive motivation of others) and anyone who happens upon this thread is less likely to want to work with you or indulge your requests in the future. I guess it's all trade-offs though, right? 🤷‍♂️

**Comment by Cacocoin** [comment]
> > Loving stackblitz and it's growth is outstanding! Keep the up the good work!
> > Just passing through but I thought I'd at least say that this issue should likely be locked to only maintainers, or at the very least @hadnet's unproductive and unhelpful comments be hidden.
> > @hadnet, I take open source etiquette very seriously, so in case you forgot, this is a professional open source website where your comments will be preserved forever. That said, if you insist on acting entitled, I request that you provide me with links to your own projects/products or even better any public source code that you've built or worked on. I'm sure others would like to try them out and offer you some of the same whiney complaints you have so rudely left here.
> 
> FYI, everyone has the right to freedom of opinion and expression (so it's not only what you like or want, ok). It's not a crime to complaint (rudely or not). If my project takes YEARS to fix a simple issue, I well deserve a complaint you know (and btw, for sure I won't act like a snowflake like you).

Are you paying to use StackBlitz? or are you assisting these 2 guys with development?
No? then you're entitled, like a snowflake.
You shouldn't throw your toys out of the pram because you didn't get your way, instead be grateful that you got the toys in the first place.

**Comment by EricSimons** [comment]
Thanks @tannerlinsley for the kind words and pointing this out- I think locking this thread & hiding some of the nasty comments in here is a good idea at this point. 🙏 

@hadnet two things I want to mention before locking:

1. Updates on finding/setting the TS version in StackBlitz

I’m happy to share that there’s a big upgrade coming out later this year that will enable this. Implementing this (and the functionality it’s associated with) in a way that doesn’t add a ton of ongoing maintenance work was/is a gigantic effort. I understand if you can’t wait any longer and need to find an alternative for the time being. For us, we have to think long term, and that means some things that appear simple won’t ship for long stretches, similar to the iPhone not shipping copy&paste for the first 4 generations of iOS. Fundamentally our job is to make hard trade offs like this. If we get most of them right, we get to keep making awesome products, and if we don’t, we’ll lose out to other solutions that do a better job. We take this responsibility seriously and I hope that’s clear from the sort of [years-long moonshot bets we’ve come to be known for](https://blog.stackblitz.com/posts/introducing-webcontainers/) all in pursuit of building the best development experiences possible.

2. Why be a hater, when you can be a lover?

The world is full of people that are stressed and struggling right now- perhaps you are even one of them. Spreading hate, anger, name calling… it’s a race to the bottom my friend. Not only does it bring down those around you, but it also takes you down with it too. I empathize if you’re going through difficult circumstances right now, but slamming doors in the face of good people is generally not a good strategy towards living a happy and fulfilled life with meaningful relationships. It costs nothing to adopt a happy & empathetic outlook when talking with other humans. I genuinely encourage you to seek out people in your life that you can talk to.

Further inflammatory comments on any StackBlitz owned repos will not be tolerated and may result in block/ban.

**Comment by kc0tlh** [comment]
**Update: This issue has been resolved!** 

**In Our [New VS Code Editor](https://stackblitz.com/codeflow):**
If you open a TypeScript file, the version is shown at the bottom right corner 

![image](https://github.com/stackblitz/core/assets/1532264/79260b34-281a-4f7c-a6a6-dae095932260)

VSCode also lets you pick the workspace version (IE the typescript version residing in your node_modules folder). This allows configuring the typescript versions on a per repo basis if desired!

**In Classic Editor Engineblock Projects:**
It is currently fixed to v4.9.5

**In Classic Editor WebContainer Projects:**
It is currently fixed to v5.1.6

For more information on these various environments, checkout [our docs page about them here](https://developer.stackblitz.com/guides/user-guide/available-environments)!
