### ISSUE TITLE
Property 'find' does not exist on type 'LoDashStatic'

### ISSUE THREAD

**Issue by whyld4900** [stackblitz/core#338]
Love this tool btw!

https://stackblitz.com/edit/typescript-yhvx4k

My issue is why is lodash not working ?
![lodashissue](https://user-images.githubusercontent.com/6947701/37425867-ee7eada0-2792-11e8-9a92-c80b7c193482.png)

**Comment by seveves** [comment]
Hi @whyld4900 
I would recommend `lodash-es` instead of `lodash`.
It's the same thing but properly exported as ES module and works perfectly with stackblitz as you can see [here](https://stackblitz.com/edit/typescript-qz2jk8?file=index.ts).

**Comment by whyld4900** [comment]
cool. ty!
