### ISSUE TITLE
Importing Modules to Ionic

### ISSUE THREAD

**Issue by Suhrawardy** [stackblitz/core#34]
I have tried to add angularfire2 but I get an error. The error is as following

_

> unexpected value 'object object' imported by module "appmodule". please add a @NgModule annotation. evaluating

_

**Comment by EricSimons** [comment]
@Suhrawardy AngularFire2 actually has an issue with their latest build that's getting fixed soon; more info here -> https://twitter.com/ericsimons40/status/892843081694715905

:)

**Comment by EricSimons** [comment]
Closing for now, but please reopen if the new version they're releasing of AngularFire2 doesn't work!
