### ISSUE TITLE
Allow .tsv file extension in angular-typescript project

### ISSUE THREAD

**Issue by kaushikparmar** [stackblitz/core#342]
I was trying to create line-chart component in angular project using d3.js library.

It loads data from .tsv file to dynamically generate a chart.

But could not create tsv file.

please allow such necessary file extensions.

**Comment by EricSimons** [comment]
Great suggestion- will add this to our todo list!

**Comment by fvsch** [comment]
I don't think we restrict file extensions at this time in StackBlitz projects.
Just tried creating a `data.tsv` file in a project, and it works file.
