### ISSUE TITLE
Can't resolve all parameters for <Service Name>

### ISSUE THREAD

**Issue by eeasss** [stackblitz/core#345]
Hi all,

I am trying to import the following project https://github.com/eeasss/ng-next-kuib and am facing a weird error when Angular starts to boot. Namely, I am getting `Can't resolve all parameters for ODataServiceFactory` for [this service](https://github.com/eeasss/ng-next-kuib/blob/master/src/app/core/data/odata-service-factory.ts).

Needless to say that this problem is reproducible only in Stackblitz. Stack trace is like this: Any ideas?

Error: Can't resolve all parameters for ODataServiceFactory: (?, ?).
  Evaluating https://angular-8gfqkl.stackblitz.io/tmp/appfiles/main.ts
  Loading blitzapp
Stack trace:
syntaxError@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:528:34
CompileMetadataResolver.prototype._getDependenciesMetadata@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15743:35
CompileMetadataResolver.prototype._getTypeMetadata@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15578:21
CompileMetadataResolver.prototype._getInjectableMetadata@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15558:16
CompileMetadataResolver.prototype.getProviderMetadata@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15918:35
CompileMetadataResolver.prototype._getProvidersMetadata/<@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15829:43
CompileMetadataResolver.prototype._getProvidersMetadata@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15789:9
CompileMetadataResolver.prototype.getNgModuleMetadata@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15357:45
CompileMetadataResolver.prototype.getNgModuleSummary@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15176:47
CompileMetadataResolver.prototype.getNgModuleMetadata/<@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15274:66
CompileMetadataResolver.prototype.getNgModuleMetadata@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:15252:13
JitCompiler.prototype._loadModules@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:34448:64
JitCompiler.prototype._compileModuleAndComponents@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:34409:31
JitCompiler.prototype.compileModuleAsync@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/compiler@5.2.8/bundles/compiler.umd.js:34303:32
CompilerImpl.prototype.compileModuleAsync@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/platform-browser-dynamic@5.2.8/bundles/platform-browser-dynamic.umd.js:270:34
PlatformRef.prototype.bootstrapModule@https://angular-8gfqkl.stackblitz.io/turbo_modules/@angular/core@5.2.8/bundles/core.umd.js:5605:16
execute@https://angular-8gfqkl.stackblitz.io/tmp/appfiles/main.ts:24:13
S@https://c.staticblitz.com/assets/engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:1:8161
_@https://c.staticblitz.com/assets/engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:1:7224
x@https://c.staticblitz.com/assets/engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:1:6532
t/</d.prototype[o.resolveInstantiate]/</<@https://c.staticblitz.com/assets/engineblock-c13ba99d8d070fecd8733495ceff2b583767e81295057f9635062c5fe737a0ea.js:2:7653
T/</<@https://c.staticblitz.com/assets/packs/common-6ae27974dbdb8229b256.js:1:41338
T/<@https://c.staticblitz.com/assets/packs/common-6ae27974dbdb8229b256.js:1:41208
a@https://c.staticblitz.com/assets/packs/common-6ae27974dbdb8229b256.js:1:31436

**Comment by EricSimons** [comment]
This usually means that one of the packages you're using has inconsistencies in their UMD bundles versus ESM modules. I can't get your repo to run rn though bc it looks like you're pointing at a git repo (we support pointing at git repos as long as it's via the https url) :(

**Comment by purplem1lk** [comment]
Thank you for your patience - The latest project link doesn't work so we are unable to move forward with this issue. We are launching new core technology into beta this month that should resolve this, though. If this issue persists, feel free to tag me or reopen this issue with an updated project link and/or screenshots of the error. Thank you! :)
