### ISSUE TITLE
[BUG] autoFocus on input in preview window steals focus from editor

### ISSUE THREAD

**Issue by Theo-** [stackblitz/core#347]
Hi all,

With the react framework, setting `autoFocus` on an input steals the focus from the text editor when the preview page is rendered.

Reproducible at: [https://stackblitz.com/edit/test-react-theo?file=index.js](https://stackblitz.com/edit/test-react-theo?file=index.js)

**Comment by EricSimons** [comment]
There's actually not much we can do about this. There are a couple of options to avoid this though:

1. Open the preview in a new window. This will ensure focus doesn't get hijacked, ever.
2. Set the dev server to only hot reload after you hit save (aka cmd+s). Your focus will still get hijacked, but only after you've made the desired edits.

Closing for now but lmk if you have any q's about this!

**Comment by httpJunkie** [comment]
This is a super annoying issue I have faced, I'd also like to ensure that we keep thinking about this and how to solve.
