### ISSUE TITLE
Stories multiple apps for angular

### ISSUE THREAD

**Issue by splincode** [stackblitz/core#348]
Documentation: https://github.com/angular/angular-cli/wiki/stories-multiple-apps

I use several applications in the repository 
Example: https://stackblitz.com/github/splincode/apper
https://github.com/splincode/apper

```json5
// .angular-cli.json
"apps": [
    {
      "root": "src1",
       ..
    },
    {
      "root": "src2",
       ..
    }
]
```

Why is it only launched src1?

It would be great to be able to run

https://stackblitz.com/github/splincode/apper?rootSrc=src1
https://stackblitz.com/github/splincode/apper?rootSrc=src2

**Comment by EricSimons** [comment]
We definitely want to support the ability to run multiple apps. Currently shooting for Q2/Q3 for this; will circle back once we start implementing this 👍

**Comment by johnpapa** [comment]
This would be awesome. I'm hoping to use this for my workshops and training.

**Comment by kc0tlh** [comment]
Multiple subdirectories are now supported in [our new VS Code editor, available here](https://stackblitz.com/codeflow)!
