### ISSUE TITLE
bug: creating new file or folder on blur

### ISSUE THREAD

**Issue by joejordanbrown** [stackblitz/core#35]
When starting to create a new file or folder and you have typed the name if you then click anywhere on the page and lose focus, the file or folder never gets created. Visual Studio Code works this way.

**Comment by EricSimons** [comment]
Are you saying that expected functionality is that clicking away would create the file/folder? Sorry if I'm misunderstanding :)

**Comment by joejordanbrown** [comment]
Yes, that is correct.
