### ISSUE TITLE
https://stackblitz.com/github/gauravsharma0916/NG-2

### ISSUE THREAD

**Issue by gauravsharma0916** [stackblitz/core#351]
unable to run this url.

**Comment by gauravsharma0916** [comment]
https://stackblitz.com/github/gauravsharma0916/NG-2

**Comment by seveves** [comment]
Hm you've checked in `node_modules` into your github repo. That is never a good idea IMHO. May you try it without this directory?

If you can't, just let me know and I will try to create a fork asap.

**Comment by purplem1lk** [comment]
Thank you for your patience - Looks like the latest project link is no longer working so this issue will be closed accordingly. We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
