### ISSUE TITLE
github username changed

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#352]
So I have changed my Github username last month, but it doesn't seem to be updated on your website yet, and every time I logout & login it displays the old username and an empty picture.

**Comment by apai4** [comment]
@nukadelic Just pushed a fix for this, your username should be updated next time you log in. Lmk if it works for you!

**Comment by siwalikm** [comment]
@apai4 can you share the commit link here for more info on this fix ?

**Comment by nukadelic** [comment]
@apai4 Amazing, it worked, thanks for the quick fix!
