### ISSUE TITLE
for...of loops don't work correctly

### ISSUE THREAD

**Issue by tomscuhda** [stackblitz/core#353]
https://stackblitz.com/edit/generator-loop

Checking the console in the example you can see no values are logged from the `for (let value of create())` statement. Setting a breakpoint you can see in the compiled output of the `for...of` loop that length is undefined, skipping the loop. 

![image](https://user-images.githubusercontent.com/6563979/37691762-780f40b0-2c8a-11e8-9c51-2ec4a83893d3.png)

**Comment by EricSimons** [comment]
Wow, that's super weird. I think this is a bug with the typescript compiler/loader. Will investigate when I'm back in office tmrw/Fri and circle back here. Thanks for reporting this! 🥂

**Comment by specialkk** [comment]
Hey, just reporting that this is still an issue. Was there any progress made since this was last looked at?

**Comment by hil400k** [comment]
Hi, it is still an issue

**Comment by ciarancourtney** [comment]
Just hit this issue, you need to enable the tsconfig compiler setting `--downlevelIteration` as per https://github.com/Microsoft/TypeScript/issues/13440

Can we edit tsconfig.json or any translation settings?

**Comment by dgreensp** [comment]
Ran into this wondering why `for (const v of map.values()) { ... }`didn't iterate over anything.

Workaround is `for (const v of Array.from(map.values())) { ... }`.

**Comment by ch3coohlink** [comment]
Still not fixed, thanks to dgreensp's workaround.

**Comment by blinkcat** [comment]
```js
const m = new Map([[1, 2], [3, 4], [5, 6]]);

for (const t of m.keys()) {
  console.log("t=>", t);
}
```
javascript blank project, Nothing is logged.

**Comment by sulco** [comment]
Thanks everyone for reporting this issue and providing examples!
Yeah, it was confusing..

Thankfully it should no longer be an issue :)
