### ISSUE TITLE
Something went wrong with this repository

### ISSUE THREAD

**Issue by benjamincharity** [stackblitz/core#354]
I've been using StackBlitz for demos and have been loving it. I just retooled one of our library repos with the hope of utilizing the new GitHub import feature but I'm just getting the message `Something went wrong with this repository`. I'm not sure how to track down the issue with so little info.

Repo causing break: https://stackblitz.com/github/GetTerminus/terminus-ui

I have another repo that should be set up exactly the same that _does_ work using the GH method: https://stackblitz.com/github/GetTerminus/ngx-tools

Any direction is appreciated!

Very much looking forward to using this feature!

---

Update: It now just hangs at the `Importing from Github...` screen with no error.

**Comment by EricSimons** [comment]
This is super weird- sorry about the inconvenience! @apai4 can you check the server logs and see why the first repo is failing out?

**Comment by tdeschryver** [comment]
Same problem here [https://stackblitz.com/github/ngrx/platform/](https://stackblitz.com/github/ngrx/platform/). Worked fine a couple of days ago, seems like the new release broke it?

**Comment by benjamincharity** [comment]
Looks like NGRX issue was a dependency that pointed to a bare git repo:

> It looks like the package.json has a dep that points to a bare git repo, specifically:

I've checked my repo and don't see any of my dependencies that specify a repo. Is it possible that a dependency of a dependency is pointed to a bare repo? Any idea how I could confirm/disprove this?

**Comment by shahmirn** [comment]
Same thing is happening with my repo.

https://stackblitz.com/github/shahmirn/boggle

**Comment by antonshevyrin** [comment]
Same error for this repo as well:
https://stackblitz.com/github/aviabird/angularspree

**Comment by benjamincharity** [comment]
Still nothing here? Even a direction to begin looking? 😞

**Comment by EricSimons** [comment]
@benjamincharity sorry about the delay on this, the past few months have been nuts for us :(

Is your repo ejected from Angular CLI? If yes, I think that might be the problem. I'll need to check with @apai4 when he gets into the office though.

**Comment by benjamincharity** [comment]
I can only imagine! No worries at all, just really wanting to use SB for demos.

It is not ejected. I am building a library and a cli app in the same repo (for local development). So possibly it has to do with some odd tsconfig paths? My CLI project should be set up like a default CLI project. When SB announced the GitHub import I actually started a whole new project to make sure of that.

**Comment by getsetbro** [comment]
My react repos were working until I ejected.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue, if it hasn't already been resolved so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by hamed-shojaei** [comment]
@purplem1lk 
https://stackblitz.com/github/hamed-shojaei/IranMap
Something went wrong with this repository.
☹️☹️☹️☹️😡😡😡😡😡😡😓😓😓😓😓

**Comment by hamed-shojaei** [comment]
> Same thing is happening with my repo.
> 
> https://stackblitz.com/github/shahmirn/boggle

Create Index.html File

**Comment by hamed-shojaei** [comment]
Create Index.html in git repository

**Comment by hamed-shojaei** [comment]
# To use stackblitz, be sure to use **index.html** in your repository root and do not forget **package.json** 😊💕
