### ISSUE TITLE
Don't show errors for repos lacking type definitions

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#355]
I'm trying to use the kinematics npm package, but it seems that none of my attempts are working so far. What is the correct path to the modules folder within an Angular project ? 

My script is located at top level scripts folders `script/ImportTest.ts` and here all my import attempts so far ( none of them seems to work ):

```
import Kinematics from 'kinematics';
import Kinematics from './kinematics';
import Kinematics from '../kinematics';
import Kinematics from '../../kinematics';
import Kinematics from '../node_modules/kinematics';
import Kinematics from '../node_modules/kinematics/src';
import Kinematics from '../node_modules/kinematics/src/index.js';
import Kinematics from '../node_modules/kinematics/src/kinematics.js';
import { Kinematics } from 'kinematics';
import { Kinematics } from './kinematics';
import { Kinematics } from '../kinematics';
import { Kinematics } from '../../kinematics';
import { Kinematics } from '../node_modules/kinematics';
import { Kinematics } from '../node_modules/kinematics/src';
import { Kinematics } from '../node_modules/kinematics/src/index.js';
import { Kinematics } from '../node_modules/kinematics/src/kinematics.js';
import * as Kinematics from 'kinematics';
import * as Kinematics from './kinematics';
import * as Kinematics from '../kinematics';
import * as Kinematics from '../../kinematics';
import * as Kinematics from '../node_modules/kinematics';
import * as Kinematics from '../node_modules/kinematics/src';
import * as Kinematics from '../node_modules/kinematics/src/index.js';
import * as Kinematics from '../node_modules/kinematics/src/kinematics.js'; 
```

**Comment by EricSimons** [comment]
The kinematics package doesn't appear to have any type definitions in its repo, hence why you're probably seeing the red squiggly under it. The code itself will actually work in the preview.

**Comment by seveves** [comment]
Hey @nukadelic ... maybe you can work with this workaround: https://stackblitz.com/edit/typescript-kinematics?file=index.ts

**Comment by nukadelic** [comment]
@EricSimons Didn't think to try and use the module while there been errors visible in the editor. Since that is the case, it's not an issue for me. Will be waiting to check out the fix for display of module errors.

**Comment by nukadelic** [comment]
@seveves thanks, that sure removes the annoyance for the meantime.

**Comment by kylecordes** [comment]
This isn't specific to StackBlitz though. Long before @EricSimons dreamed of blitzing, to consume an untyped package without warnings or errors in your non-web-based IDE it was necessary to do something like an old-fashioned require instead of a TypeScript import.

It would be great if both Blitz and off-line IDEs would display a more helpful message when this happens. Something about "I found the code but no types, click here to switch to a different kind of import suitable for the situation if you cannot find types".

**Comment by seveves** [comment]
TBH when using Typescript you should be aware that you need type defs. If there are none then go and contribute to the project or add some to the @types project.
I won't investigate that further or at least set its priority to very low :)

**Comment by nukadelic** [comment]
Would it be possible to add a build in [data type generator](https://github.com/Microsoft/dts-gen) for typescript projects ? Or at least a way to install our gist's via npm with a simple `npm install gist:fd9ca7...` like shown in this [example](http://dev.edenspiekermann.com/2016/03/02/gists-as-npm-packages/)
