### ISSUE TITLE
IE 11 Editor Never Loads

### ISSUE THREAD

**Issue by crutchcorn** [stackblitz/core#359]
Previously, the editor would run under IE11. Now, when I try to start a new project, I simply get the grey screen and it never loads. There are no errors in the console.

**Comment by seveves** [comment]
btw the preview on stackblitz.com main site is working in IE11

**Comment by apai4** [comment]
@crutchcorn Sorry about that, IE11 should be working now! Lmk if it's working again for you

**Comment by seveves** [comment]
@apai4 works again

**Comment by tsvetomir** [comment]
There's currently an `'Analytics' is undefined` error when opening projects in IE11.

**Comment by purplem1lk** [comment]
Thank you for your patience - We will be closing this issue and posting updates in #1155 to consolidate the resolution. If your issue persists, feel free to tag me or ask to reopen this issue with a recent project link, description and screenshots of the error. Thank you! :)
