### ISSUE TITLE
Install packages that are hosted on github

### ISSUE THREAD

**Issue by ThomasBurleson** [stackblitz/core#36]
I want to use the nightly build of `@angular/flex-layout`.  

Normally I can do one of these:

*  `npm -i github.com/angular/flex-layout-builds`, or
*  `npm -i angular/flex-layout-builds`

None of these seem to work in the StackBlizt IDE. 

![screen shot 2017-08-05 at 6 56 27 pm](https://user-images.githubusercontent.com/210413/28999555-d6a858ec-7a0f-11e7-8934-15b603bd3a52.png)

> Our deployment repos is  www.github.com/angular/flex-layout-builds

**Comment by EricSimons** [comment]
We currently only support importing from NPM, but we do have (basic) import from github working in local builds. However, it's gonna require a lot of testing & love to ensure it plays nice with our dep resolver, which is important bc we def don't want dep mismatches throwing errors in your console that you normally wouldn't get locally.

(PS - I just saw/responded to your tweet about this! 🍻)

**Comment by ThomasBurleson** [comment]
Understood. FYI.

Plz consider this an important feature: developers will use StackBlitz to test and demo... often with libraries recently fixed (e.g. nightly builds).

> Consider me a volunteer for testing. ;-)

**Comment by ThomasBurleson** [comment]
@EricSimons - If you guys need extra help with StackBlitz, ping me (I would love to get involved).

**Comment by EricSimons** [comment]
> Plz consider this an important feature: developers will use StackBlitz to test and demo... often with libraries recently fixed (e.g. nightly builds).

Excellent point, I hadn't even considered this. I'm gonna bump the priority on this feature to ensure it's in prod by EOM 👍 

Def would love to have you get involved with SB! I'm putting together a list of things we could use help with actually, hoping to get it posted on the repo this week. Also just followed you on twitter so we can DM :)

**Comment by ThomasBurleson** [comment]
@EricSimons - ping me on email (github profile), let me when/how I can help. Cheers.

**Comment by ThomasBurleson** [comment]
@EricSimons - I am still blocked with this. I would like to help resolve this one!

**Comment by EricSimons** [comment]
@ThomasBurleson so sorry about the delay here! Past month or so has been insane 😓  I'm going to start working on this today and will have it out early tmrw. Will post back here once it's live!

**Comment by ThomasBurleson** [comment]
@EricSimons - wonderful news. Consider me a fan and a resource !

**Comment by EricSimons** [comment]
@ThomasBurleson it's live on prod! You can simply enter `https://github.com/angular/flex-layout-builds` (or for a specific version, `https://github.com/angular/flex-layout-builds#2.0.0-beta.9-e461d17`) to install from github :)

This is definitely a beta feature so lmk if you run into any issues! There are also some limitations right now (it won't resolve nested sub-packages in the github repo, etc) but lmk if that's a req for you and I'll prioritize some time to put in a fix for it.

PS - we're still getting our ducks in a row for the next week or two, but keep an eye out for an email from me reg getting involved w/ stackblitz :)

**Comment by ThomasBurleson** [comment]
@EricSimons - I so admire professionalism and communication. Kudos to you for both. I will try this beta feature today. Thank you.

**Comment by ThomasBurleson** [comment]
@EricSimons - Your fix(es) work wonderfully. 

Here is a blitz with the latest code in our nightly build:

https://stackblitz.com/edit/angular-pu8pc6?file=app%2Ftest.component.ts

![screen shot 2017-09-28 at 10 46 06 am](https://user-images.githubusercontent.com/210413/30976406-52d20c7a-a43a-11e7-90fb-3599b3762b3a.png)

Closing as fixed!

**Comment by EricSimons** [comment]
@ThomasBurleson No problem at all! Thanks for the kind words :) It's great to see everything is working well for the flex-layout demo. Btw I put the final touches on the resolution logic today (per https://github.com/stackblitz/core/issues/149#issuecomment-332990936), so it's now possible to import SASS/CSS, nested packages, etc from github repos as well (here's a demo of the latest GH build of Ang Material w/ a custom theme: https://stackblitz.com/edit/angular-m9axcs?file=theme.scss)

**Comment by ThomasBurleson** [comment]
@EricSimons - So I get the `import SASS` feature. That is cool. What is a `import nested packages` example ?

**Comment by 100ideas** [comment]
@EricSimons this feature does not appear to be working. Here's a screenshot of the project you referenced: https://stackblitz.com/edit/angular-m9axcs?file=theme.scss

<img width="1639" alt="Screen Shot 2019-11-05 at 7 27 57 AM" src="https://user-images.githubusercontent.com/57006/68221204-ee089900-ff9d-11e9-8136-555b8459ef55.png">

**Comment by richardeschloss** [comment]
Hi this would be a very useful feature, is there any news on this?

**Comment by kc0tlh** [comment]
Tagging as related to #1195
