### ISSUE TITLE
jsdelivr cdn fallback

### ISSUE THREAD

**Issue by accomazzo** [stackblitz/core#360]
I work at a large enterprise which is blocking the cdn.jsdelivr.net domain. Specifically cdn.jsdelivr.net/npm/monaco-editor@0.10.1/min/vs/loader.js is blocked which breaks the functionality of the stackblitz editor. This issue is probably not unique to my organization. I'd like to suggest a fallback or alternative for loading this script. Thank you.

**Comment by yenoh2** [comment]
I am experiencing the same issue.  Several other domains are work.  Would it be possible to use any of these?  
https://microsoft.github.io/monaco-editor/node_modules/monaco-editor/min/vs/loader.js
https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.10.1/min/vs/editor/editor.main.js
https://unpkg.com/monaco-editor@0.10.1/min/vs/loader.js

**Comment by MartinKolarik** [comment]
Do you guys happen to know what website blocking solution/software is used by your organization?

**Comment by yenoh2** [comment]
Unfortunately, I'm not able to provide that information.

**Comment by jyarbro** [comment]
> https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.10.1/min/vs/editor/editor.main.js

This path makes the most sense as stackblitz is already using this for these other files, so there's the highest chance of getting either a complete experience or a failed experience. The current setup results in a partial experience that leads the user to think things are fine until you try to tell Angular to generate a new X, and then only in dev tools does it show that the monaco editor failed to load.

```
<link href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/6.0.0/normalize.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/intro.js/2.5.0/introjs.min.css" rel="stylesheet">
```
