### ISSUE TITLE
My repo has a package.json file but I am getting an error when I try https://stackblitz.com/github/clane/clane-ng5-a11y-repo

### ISSUE THREAD

**Issue by clane** [stackblitz/core#361]
My repo has a package.json file but I am getting the error 

"The repository is missing a package.json file"

when I try https://stackblitz.com/github/clane/clane-ng5-a11y-repo

**Comment by apai4** [comment]
@clane There isn't a package.json in the root of your repo so you'll have to link to the folder that contains the app: https://stackblitz.com/github/clane/clane-ng5-a11y-repo/tree/master/ng5-a11y

**Comment by clane** [comment]
Thanks that worked!

**Comment by purplem1lk** [comment]
The resolution has been posted by @apai4 above so this issue will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)

**Comment by charlesVeneau** [comment]
Hello,
I'm having the same issue.
https://stackblitz.com/github/charlesVeneau/Charlesveneau_6_08092021
My repo
https://github.com/charlesVeneau/Charlesveneau_6_08092021

it's a static project that doesn't require a package.json

![image](https://user-images.githubusercontent.com/47984439/136178170-daf5950e-6c86-49b1-8184-3d29829eb9a0.png)
