### ISSUE TITLE
Referencing function does not recognize 'this' keyword 

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#362]
I have noticed this many times in the past in few of my TypeScript projects. Now i am facing the same issue with Angular project as well. Not sure if this is happening due to my little experience in typescript or it's a bug in the editor, but I though to put it here anyway ( please let me know if that is a stackoverflow issue/question instead )
Here is an example: 
```
class A {
  value = 4;
  callBack = null;
  constructor() {}
  updateOnFrame() {
    if( this.callBack ) this.callBack( this );
  }
}
class B {
  value_b = 11;
  constructor() {
    var a = new A();
    // case 1 : Does not work
    a.callBack = this.listener;
    // case 2 : Seems to fix my problem   
    a.callBack = (x) => this.listener( x );
  }
  listener( a:A ) 
  {
    // in case 1 , 'this' keyword will reference class A ? 
    // case 2, works just fine
    console.log( this.value_b + a.value );
  }
} 
```

**Comment by seveves** [comment]
This is not related to stackblitz. Feel free to ask for help at SO or somewhere. I would prefer using `bind` here. You can read more about it [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind). If you need any further help, feel free to message me in the discoord channel 😄 

May we close this issue?

**Comment by nukadelic** [comment]
Yes of course, thank you for the link.
