### ISSUE TITLE
Setting Firefox network.cookie.cookieBehavior to 1 will prevent Angular Tutorial of Heroes from loading.

### ISSUE THREAD

**Issue by RobRoseKnows** [stackblitz/core#364]
I enable [this](http://kb.mozillazine.org/Network.cookie.cookieBehavior#0) config setting in order to block cookies not coming from the originating server. This breaks [the tutorial](https://stackblitz.com/angular/nlvrooxxdvy) from loading as reported in [this issue](https://github.com/angular/angular/issues/22938) in Angular's repository. I'm aware setting this config option may break things, but I don't know if that's necessary in this case.

**Comment by apai4** [comment]
See https://github.com/angular/angular/issues/22938#issuecomment-375801179, although we aren't using cookies on our preview domains, browsers apply the same permissions for other APIs like `localStorage` so you'll have to add an exception for `https://stackblitz.io` if you want to keep blocking 3rd party cookies

**Comment by RobRoseKnows** [comment]
@apai4 Damn I didn't realize they were different domains. Adding an exception for stackblitz.io fixed it. Thanks!
