### ISSUE TITLE
paper-js not working

### ISSUE THREAD

**Issue by michaelb-01** [stackblitz/core#367]
For some reason I can't get paper-js to work in Stackblitz.. I've added 'paper' and '@types/paper' and I don't get any errors in the editor but the constructors don't seem to work. I've made a similar project with angular-cli on my localhost which works fine so i'm not sure what i'm missing (maybe a tsconfig.json file..?) 

Here's a simple stackblitz example:

https://stackblitz.com/edit/mlb-angular5-paperjs?file=.angular-cli.json

**Comment by EricSimons** [comment]
@michaelb-01 super odd- this seems like an issue with how SystemJS is evaluating that module. Will investigate first thing tmrw morn!

**Comment by michaelb-01** [comment]
Thanks! And thanks for getting back so quick!

**Comment by seveves** [comment]
I fixed it for you: https://stackblitz.com/edit/mlb-angular5-paperjs-zv76qj?file=app/paper/paper.component.ts

**Comment by nukadelic** [comment]
Had similar issue a while back, so i ended up adding the minifed js file instead. https://paperjs.stackblitz.io

**Comment by seveves** [comment]
There is no need to add an external minified script as you can see in the project I've linked. Sometimes you have to read through the type definitions because there is more than one way to declare a module in typescript.

**Comment by michaelb-01** [comment]
Thanks @seveves ! What was the problem? Was it a typescript issue? Or I just wasn't initializing the canvas correctly?

**Comment by seveves** [comment]
I just browsed through the paperjs docs and saw that `Project` has no constructor. So I thought there must be another way and found the `setup` method. With that method it worked as expected. I also changed the lifecycle hook `OnInit` to `AfterViewInit` because that's the proper one when using `@ViewChild`.

I'm glad that I could help. So we can close this issue, right?

**Comment by michaelb-01** [comment]
Ah, good to know how to debug these issues too! Usually I run into something like that and just get stuck!

Yep feel free to close the issue (do I have to do that?).

Thanks again for your help!
