### ISSUE TITLE
tsconfig.json aliases do not work

### ISSUE THREAD

**Issue by sinedied** [stackblitz/core#368]
Here is the project: https://stackblitz.com/github/ngx-rocket/starter-kit

and the error displayed:
![image](https://user-images.githubusercontent.com/593151/37903564-ab817c8e-30f8-11e8-97f2-ceda74a6113a.png)

This is due to this `tsconfig.json` path aliases, works fine with "real" angular-cli project (and considered as a best practice ;) ):
```json
    "paths": {
      "@app/*": ["app/*"],
      "@env/*": ["environments/*"]
    }
```

Would love to see it fixed on stackblitz!

**Comment by seveves** [comment]
Duplicate of #220

**Comment by seveves** [comment]
I'll close this. Let's track the progress in the other issue, please 🙏

**Comment by sinedied** [comment]
Sorry I missed the previous one!

**Comment by seveves** [comment]
That's ok @sinedied 👍
