### ISSUE TITLE
Files/Folders lost when drag & drop parent into child or itself

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#369]
Steps for magic trick: 
1. Make sure folder has a sub-folder 
2. Expend folder tree to see parent & child
3. Drag & Drop parent into child
4. Whoosh ! Both of them are gone now. 

This happened to me accidentally while working on an ng-app, were i have dragged the entire project logic `app` folder into it's sub-folder accidentally. Fixing that was easy ... I just refreshed the page. Also I just tried that trick on a new ng app and saved it, seems like the damage became permanent.

**Comment by seveves** [comment]
Why are you doing this? 😸  Nice find!

**Comment by nukadelic** [comment]
Don't judge, I'm using a touch-pad. Aaaand I just lost another folder, this time it didn't involve a second folder, I just drag and dropped it onto into itself
And another thing, seems like it's impossible to move a file from a folder back to the top level location ( root folder ? )

**Comment by seveves** [comment]
I hope your lost folders are in a better place now 🙏 

Sorry for that inconvenience. I'm pretty sure there will be a bugfix as soon as possible.

**Comment by EricSimons** [comment]
Yeah our drag and drop logic needs to be updated - sorry for the inconvience @nukadelic 😅 will add this to our todo list!

**Comment by nukadelic** [comment]
No worries, i like your editor, keep up the good support :+1:

**Comment by tonysamperi** [comment]
It happened to me too! 
Anyway I noticed that after moving a folder to another, the view is updated, but the compiler can't actually find those file...
They are visible in the tree...and if I open each one, edit a line and save, they start appearing again...
Why don't you add a button to refresh the folders tree??

**Comment by EricSimons** [comment]
Sorry! Just a stupid bug on our end- will be fixed with a major UI refactor & upgrades within the next few weeks :)

**Comment by sulco** [comment]
Thanks for reporting! With the series of updates to our UI and specifically file tree implementation, this should not be an issue anymore, but please feel free to reopen if you stumble upon it again.
