### ISSUE TITLE
Allow saving in projects imported from GitHub

### ISSUE THREAD

**Issue by howardchung** [stackblitz/core#371]
Currently, projects imported from GitHub have a "Fork" button instead of a "Save" button.  In order to persist changes made to the opened project, the project first needs to be forked.  Perhaps trying to save a GitHub project should automatically do this?

Optimally, the editor would allow saving on the originally opened project (to preserve the link to the GitHub repo), as well as allowing the currently applied diff to be "exported" to GitHub as a pull request/commit on the opened repo (perhaps this is in the works?)

**Comment by EricSimons** [comment]
@howardchung I love this idea! We're currently working on committing back to github & should be live in 1-2 months, will circle back to this issue once it's online 👍

**Comment by itsjaganr** [comment]
@EricSimons StackBlitz is awesome. I can bring Github repos to StackBlitz. If I have new work(which is not in github) saved in StackBlitz, how do I save it to Github?
