### ISSUE TITLE
The share url for projects imported from github is wrong

### ISSUE THREAD

**Issue by ocombe** [stackblitz/core#372]
I've imported a project from github, and the share urls are wrong, they point to an error page instead:

![image](https://user-images.githubusercontent.com/265378/38027912-82e5b3f4-3291-11e8-9c57-803e113be746.png)
![image](https://user-images.githubusercontent.com/265378/38027916-85f70b24-3291-11e8-8bce-ba5f51d8e7f7.png)

**Comment by seveves** [comment]
This could be related to #371 ... does the URL work after forking it?

**Comment by ocombe** [comment]
Yes! Once forked it takes the url that was displayed in "share", and the url works

**Comment by purplem1lk** [comment]
Resolution is provided by @seveves so this issue will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
