### ISSUE TITLE
div hidden by *ngIf break the page when revealed

### ISSUE THREAD

**Issue by WizardPC** [stackblitz/core#373]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

Nothing particular
![before](https://user-images.githubusercontent.com/11718892/38036823-e1205b20-32a7-11e8-84a9-24e63c64a37e.PNG)

#### What is the current behavior?

A big grey block appear 
![after](https://user-images.githubusercontent.com/11718892/38036830-e98cce56-32a7-11e8-8237-8f33095ede34.PNG)

#### What are the steps to reproduce?

[https://stackblitz.com/edit/sb-issue](https://stackblitz.com/edit/sb-issue)

**Comment by seveves** [comment]
Hm works fine for me in latest Chrome. I'm clicking the checkbox and an input field appears.

**Comment by WizardPC** [comment]
I'm on Chrome, version 65.0.3325.181.

**Comment by seveves** [comment]
Do you have this issue only in the editor view or also when opening the app in its own window (by clicking 'open in new window')?

**Comment by WizardPC** [comment]
Only in the editor.

![div](https://user-images.githubusercontent.com/11718892/38081429-59445ae2-3344-11e8-8725-b8b3fdd615fb.PNG)

**Comment by sulco** [comment]
We've undergone a series of updates to the platform since this issue was submitted and it does no longer seem to appear.
Closing for now, please free to reopen if you're still experiencing it!
