### ISSUE TITLE
Search page for projects

### ISSUE THREAD

**Issue by splincode** [stackblitz/core#376]

**Comment by EricSimons** [comment]
Yup totally! We're adding a search page pretty soon here :)

**Comment by nukadelic** [comment]
+1

**Comment by seveves** [comment]
@nukadelic I'm happy you actively contribute to this repository but please do not post '+1' comments. Adding an [emoji reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) is enough and looks way better 😸

**Comment by sliceofbytes** [comment]
I would also like the search feature for projects and an ability to show all projects on a single page. I find the current style quite difficult for project pruning / management / renaming etc. I would also find it very useful to be able to filter by if a project has a default random name or custom name. For an even more advanced search it would be awesome to filter by angular version or even by npm packages etc...

**Comment by oleersoy** [comment]
Sweet - This is sorely needed!

**Comment by sulco** [comment]
This is now available for logged in users on the dashboard (https://stackblitz.com)

**Comment by lulunac27a** [comment]
I can't search from the community, it searches only my projects.
