### ISSUE TITLE
Webpack Build Issue for AngularJS

### ISSUE THREAD

**Issue by SweetCodingInc** [stackblitz/core#381]
Hi All,

Please take a look at [this small AngularJS project](https://stackblitz.com/edit/angularjs-2yxhf1?file=common%2Fcomponents%2Fmain-component%2Fmain-component.component.js) I created.

In `main-component.component.js`, go ahead and edit value of `this.name`.
The build breaks with following error.

```
Error: [$compile:multidir] Multiple directives [mainComponent, mainComponent] asking for new/isolated scope on: <main-component>
http://errors.angularjs.org/1.6.9/$compile/multidir?p0=mainComponent&p1=&p2=mainComponent&p3=&p4=new%2Fisolated%20scope&p5=%3Cmain-component%3E
    at eval (VM226 angular.js:116)
    at assertNoDuplicate (VM226 angular.js:10394)
    at applyDirectivesToNode (VM226 angular.js:9582)
    at compileNodes (VM226 angular.js:9171)
    at compileNodes (VM226 angular.js:9183)
    at compile (VM226 angular.js:9052)
    at eval (VM226 angular.js:1960)
    at Scope.$eval (VM226 angular.js:18542)
    at Scope.$apply (VM226 angular.js:18641)
    at bootstrapApply (VM226 angular.js:1958)
```

It is trying to recreacte the component `mainComponent` thus resulting in this error.
If I, however, refresh the page, it works as expected.

Could be great if this can be fixed.

I'm also willing to contribute this fix. Please let me know.

PS:
In settings section, if I set set `Reload mechanism` to `Page reload`. It works as expected. I'd definitely like to see this working even in case of `Hot reload`

**Comment by seveves** [comment]
As far as I know, HMR is not supported by angularjs. I found this related issue: https://github.com/angular/angular.js/issues/15938
