### ISSUE TITLE
Angular Webpack Boilerplate

### ISSUE THREAD

**Issue by dgvozd** [stackblitz/core#383]
Please add support for this repo https://github.com/DevTeamHub/angular-webpack-boilerplate

**Comment by splincode** [comment]
Soon there will be a search for templates (pen)

**Comment by kc0tlh** [comment]
Closing this issue as Angular 5 is no longer supported by the Angular team.
<img width="839" alt="image" src="https://github.com/stackblitz/core/assets/1532264/a1e096c7-6db8-4532-93d4-e62ed42dc331">
