### ISSUE TITLE
Don't show the Navbar (filename, preview button, ...) in embedded mode if requested.

### ISSUE THREAD

**Issue by pawsaw** [stackblitz/core#384]
I'd like to use StackBlitz for embedding **code snipplets** in my Blog (medium, wordpress, others, ...).

In this case it's not necessary to have the filename as well as the buttons/ toggles "preview" and "editor" visible.

While sharing/ creating an embedded URL there should be an option to disable this.

Take a look on this screenshot: 
![navbar](https://user-images.githubusercontent.com/2669826/38239923-70766c1c-372e-11e8-820f-ca19bc4cdf8b.jpeg)

Kind Regards
Pawel

p.s. Many thanks for this great tool.

**Comment by kc0tlh** [comment]
Thanks for the product feedback @pawsaw! This is now the default behavior for embeds:

<img width="1000" alt="image" src="https://github.com/stackblitz/core/assets/1532264/ae527b56-62c9-4e69-ba4a-867c2b29dffb">
