### ISSUE TITLE
TSLint analyze online

### ISSUE THREAD

**Issue by splincode** [stackblitz/core#387]
Lazy-loading not working in Angular 5.2.8 on StackBlitz

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
![image](https://user-images.githubusercontent.com/12021443/38312605-d9d591d6-382a-11e8-83cb-6513d810f769.png)

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-uotzgd?file=app/app.module.ts

<pre><code>
Angular version: 5.2.8

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/38315191-9dff9052-3830-11e8-83cd-bd07f03cf8a5.png)

For an hour I could not understand what was going on

**Comment by splincode** [comment]
Please, add online tslint on stackblitz ))

**Comment by splincode** [comment]
https://github.com/stackblitz/core/issues/160

**Comment by seveves** [comment]
Should we close this as this is tracked in #160?
