### ISSUE TITLE
Question: is it possible to run `npm install` so that it will import all package.json dependencies?

### ISSUE THREAD

**Issue by avidanyum** [stackblitz/core#388]

**Comment by seveves** [comment]
Stackblitz resolves all dependencies automatically of the the associated template (f.e. when importing from github). You can manually add further npm dependencies if some are missing.

Normally you don't have a package.json in a stackblitz project. What do you want to do?

**Comment by avidanyum** [comment]
i have an existing angular project on github with package.json and many dependenies in that file i wanted to import to stackblitz couldn't find how to do that.

**Comment by seveves** [comment]
It's in the docs: https://stackblitz.com/docs#importing-projects

**Comment by avidanyum** [comment]
freaking and amazing... I missed that.  thanks.
