### ISSUE TITLE
Remount component so componentWillUnmount() runs

### ISSUE THREAD

**Issue by philholden** [stackblitz/core#39]
I am experiencing problems with `setInterval()`. This is because `componentWillUnmount()` is not getting called when the view is refreshed on key presses. I am making a network request every minute on `setInterval`. But a new request is being created every minute for every key stroke in the editor.

I had the same problem in ReactPlaygroundStyled and got round it by unmounting the root before re-eval:

```javascript
ReactDOM.unmountComponentAtNode(this.mountNode)
```

https://github.com/ncredinburgh/react-playground-buble/blob/master/packages/react-playground-bare/src/components/react-playground-bare.js

**Comment by EricSimons** [comment]
Good catch — I actually implemented this a while back but it must've gotten overridden 😅 Will fix asap!

For the time being, here's a working example that you can fork off of that will do this properly: https://stackblitz.com/edit/unmount-react?file=index.js
