### ISSUE TITLE
code search support

### ISSUE THREAD

**Issue by howardchung** [stackblitz/core#391]
Currently I use `ag` liberally to look for things in a project.  Looks like StackBlitz has support for searching in a single file but not across all of the files, (similar to ctrl+shift+F in Visual Studio/VS Code)

**Comment by EricSimons** [comment]
@howardchung love it! Will get this added to our short-term todo list 🥂

**Comment by purplem1lk** [comment]
Thank you for your patience! This feature has been implemented and users can search across all files (see screenshot below). You can use the same ctrl+shift+F keyboard shortcut for this feature. This issue has been resolved and will be closed accordingly. Thank you! :)

<img width="1438" alt="Screen Shot 2021-04-22 at 10 30 46 PM" src="https://user-images.githubusercontent.com/49956513/115809598-65143600-a3ba-11eb-89ff-88690f85b2e8.png">
