### ISSUE TITLE
says there is something wrong with the repository 

### ISSUE THREAD

**Issue by debugmodedotnet** [stackblitz/core#392]
There is something bad with this repository error

**Comment by seveves** [comment]
Can you share your repository or stackblit project?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
