### ISSUE TITLE
Allow importing of private github repos

### ISSUE THREAD

**Issue by DiMilan** [stackblitz/core#393]
"Yikes! The page you requested couldn't be found."
Repo is private. Pretty basic functionality, Angular + Firestore. 2 components.
Did some changes however to be able to run heroku. (which also doesn't work btw) Followed this tutorial: https://www.youtube.com/watch?v=0bOJjAUXjhI

**Comment by EricSimons** [comment]
@DiMilan we currently only support public github repos (as we're using the public github API to suck down the projects). We're going to enable private repos in 1-2 months though, so I'll circle back to this issue once that's online 👍

**Comment by michalmw** [comment]
Hey.

If you don't support private repository then is another way of using stackblitz for a private project.
I try to find a way to replace vs code.

**Comment by vip20** [comment]
Please add a provision to add a access token to access private repos. As in Octotree browser extension for github

**Comment by Xipooo** [comment]
Ugh, 10 months later and still no private repo access.  I truly need this feature since it's preventing me from doing any actual work with Stackblitz.

**Comment by rajibhalder** [comment]
Hi Team, Eagerly waiting to import Github private repo into stackblitz.

**Comment by Local9** [comment]
Same here, I'd love to use this but only with Private Repos

**Comment by daviddsingleton** [comment]
I subscribed and still can't import private repos

**Comment by Local9** [comment]
I found I had to make it public, import it, then make it private.

**Comment by nigellima** [comment]
@Local9 are you able to push code to the private repo after importing?

**Comment by ecteodoro** [comment]
The lack of this feature is preventing lots of paid customers. It should be 🔝  priority.

**Comment by tdekoekkoek** [comment]
This is the only way I would be using Stackblitz for my development.  Please allow importing private repos!

**Comment by glue-eng-core** [comment]
I'm evaluating options and this is something codesandbox has figured out. Stackblitz and codepen are still lacking in this regard.

**Comment by jasonverber** [comment]
@EricSimons I just signed up for a membership thinking I'd be able to import private repos -- is there any update on this, or any way I can get involved in helping make sure this gets built in a way that works for real use cases? Thanks!

**Comment by etavener** [comment]
Shizer. I just upgraded my membership thinking I could import my private repo (it clearly said supported Private Github accounts). Now I find out I can't import existing github repos. Mis-sold!

**Comment by entruv** [comment]
I just pay a 1 month membership, and no private repository sync is possible!

**Comment by Mearman** [comment]
I'd love to start using StackBlitx, lacking this feature is what's stopping me.

**Comment by GeoITManagement** [comment]
We too facing the same problem.. I can't make my code as Public to use Stackblitz... Need a workaround to make the Stackblitz to work on Private Repository

**Comment by amevents** [comment]
I just upgraded my membership thinking I could import my private repo (it clearly said supported Private Github accounts). Now I find out I can't import existing github repos.

**Comment by jbratu** [comment]
Ditto.

**Comment by AKrasovski** [comment]
Access to private repo is really needed. We cannot use Stackblitz with our project for this reason.

**Comment by FXschwartz** [comment]
Same here, mislead by membership saying it supported it. Canceled right after I realized it wouldn't.

Our company cannot use this platform until this feature is built and released.

**Comment by viktorasLipinskis** [comment]
if private repos is not working, than please get my money back!

**Comment by n0mer** [comment]
@EricSimons can you please share whether there are any updates regarding importing private GitHub projects for paid customers?

**Comment by EricSimons** [comment]
@iakashsrivastava is the project you're trying to sync with either React or Angular based? If so, if you click "connect repository" and then click "import an existing repository" on a base React or Ang project that will allow you to import.

**Comment by vinagreti** [comment]
Isn't this problem solved?

I've just cloned a private (angular) repo by clicking in "connect repository" and then clicking in "import an existing repository" on a fresh new stackblitz Angular project.

![stackblitz-private-repo-clonning](https://user-images.githubusercontent.com/1353905/102948756-67ff2880-44a5-11eb-9f9f-69de8880c7a7.gif)

**Comment by purplem1lk** [comment]
> Isn't this problem solved?
> 
> I've just cloned a private (angular) repo by clicking in "connect repository" and then clicking in "import an existing repository" on a fresh new stackblitz Angular project.
> 
> ![stackblitz-private-repo-clonning](https://user-images.githubusercontent.com/1353905/102948756-67ff2880-44a5-11eb-9f9f-69de8880c7a7.gif)

Thank you for your patience - This issue has been resolved with the comment above. In addition, we are launching new core technology into beta next month that should address supplemental issues so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
