### ISSUE TITLE
Stackblitz seems to have issues finding type defs from npm packages unless they are at the root?

### ISSUE THREAD

**Issue by gmurray81** [stackblitz/core#394]
Please see:
https://stackblitz.com/edit/angular-buy7v5

Note, that while the sample works, the red squigglies don't seem to be able to find the type definitions.

**Comment by gmurray81** [comment]
import { IgxCategoryChartModule } from 'igniteui-angular-charts/ES5/igx-category-chart-module'; 
results in a "can't find module: igniteui-angular-charts/ES5/igx-category-chart-module" even though the actual compilation has obviously been able to find this.

**Comment by gmurray81** [comment]
For reference, no such error exists in CodeSandbox with the same config: https://codesandbox.io/s/382kj3yo75

Isn't as nice to use as StackBlitz though ;-)

**Comment by EricSimons** [comment]
Yeah, this is actually related to https://github.com/stackblitz/core/issues/386. Our typings tracer was designed to look at the package's `typings` field and trace all other types included from there; while this allowed us to shake out a lot of unused type files, many packages don't specify entrypoints so we're upgrading our tech to take a more aggressive approach.

We should have a fix for this within the next week or two & will update https://github.com/stackblitz/core/issues/386 once it's live. Thanks for reporting this @gmurray81!

**Comment by gmurray81** [comment]
Awesome, thanks!
