### ISSUE TITLE
How Do I Import JS Files in Angular Component File in StackBlitz?

### ISSUE THREAD

**Issue by dammiepaul** [stackblitz/core#395]
@EricSimons  Hi Eric,

I'm currently working on a basic angular app for encrypting and decrypting text. See https://stackblitz.com/edit/encrypt-decrypt-app.

I added crypto-js as an npm package but I don't know how to import and use it in my AppComponent file. What do I do?

Please help me.

Thanks.

**Comment by seveves** [comment]
I checked your stackblitz project and it works, doesn't it?

**Comment by dammiepaul** [comment]
@seveves Yeah, it now works. I had to share the issue on Discord. A colleague there gave me a suggestion that helped me resolve it. Thank Severin!
