### ISSUE TITLE
Meta tags for ogp.me don't work

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#397]
I have tried to add an image preview to this [project](https://stackblitz.com/edit/asteroidz?file=index.html).  But when I try to: share the link on twitter/whatsapp, or check it with [this tool](http://opengraphcheck.com). The open graph information seems to be missing. 

Does it mean everything i can inspect in developer console is generated after the page had been loaded ? If  so could you add a tiny input text box to add image preview for our projects that will work when sharing links ? 

Cheers

**Comment by kc0tlh** [comment]
@nukadelic Thanks for the product feedback! Social previews have been added. You can checkout [the blog post here](https://blog.stackblitz.com/posts/introducing-collections-and-social-previews/).
