### ISSUE TITLE
Import error, can't find files: index.html index.js

### ISSUE THREAD

**Issue by a1nb0** [stackblitz/core#398]
Hi, i guess i am doing something wrong, could anyone be so kind to tell me what am i missing?
![screen shot 2018-04-08 at 10 09 23 pm](https://user-images.githubusercontent.com/37039235/38471454-f93b7002-3b79-11e8-9069-a761294f7921.png)

https://stackblitz.com/edit/js-evsn16

**Comment by zia8** [comment]
I am also facing this issue . how you fixed that issue?
https://stackblitz.com/edit/angular-firebasenew-01?file=src%2Fapp%2Femployees%2Femployee-list%2Femployee-list.component.ts

**Comment by rodrake1** [comment]
> I am also facing this issue . how you fixed that issue?
> https://stackblitz.com/edit/angular-firebasenew-01?file=src%2Fapp%2Femployees%2Femployee-list%2Femployee-list.component.ts

Hi! I just opened your app on stackblitz and it's working. I'm getting the" Import error, can't find file:
/index.html" error too. How did you fix it?

**Comment by Atticus29** [comment]
Why was this issue closed?

**Comment by radubartan** [comment]
Initially my **index.html** was inside the **public** folder and my **index.js** was in the **src** folder.
Moving those to the root of the application solved the error.
