### ISSUE TITLE
Support for projects scaffolded with angular cli 6  [ Request ]

### ISSUE THREAD

**Issue by william-lohan** [stackblitz/core#404]
I went to https://stackblitz.com/github/gatimus/my-angular-cli6-project and got:

> This project type is not yet supported

**Comment by seveves** [comment]
Angular v6 is not yet released. Not sure if stackblitz should have support for alpha/beta/rc releases.

**Comment by gatimus** [comment]
That makes sense, but version 6 is already in rc and its [tentative resale date](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md#tentative-schedule-until-april-2018) has already passed so it could be released and day now. It'd be nice to have support for it in the works.

**Comment by EricSimons** [comment]
v6 support is def in the works- will be out before (or shortly after) v6 officially lands. Will circle back here once it's online!

**Comment by urish** [comment]
@EricSimons thanks! Any chance it will be out this week? @alexcastillo and plan on using StackBlitz for the demos in our ng-conf talk, and we'd love to be able to use Angular 6

**Comment by EricSimons** [comment]
@urish I'm gonna get this online today- will report back once it's up!

**Comment by urish** [comment]
:heart: :heart:  :heart: 

Thank you so much!

**Comment by EricSimons** [comment]
Okay this is now live on prod! Definitely a bit "beta" though :) Can y'all test it out and & lmk if you run into any issues?

**Comment by urish** [comment]
Lovely!
I'm in my way to SLC now, hope to be able to check it in a few hours.

By the way, do you have some workaround for setting up code snippets with
StackBlitz? I found a Chrome extension called ProKeys, it works but not
very realiably....

**Comment by EricSimons** [comment]
I'm actually not sure how most ppl do code snippets right now w/ stackblitz (perhaps someone in our discord channel might have a good solution) but it's a feature that we're planning to ship within the next 1-2 months though!

**Comment by urish** [comment]
@EricSimons import seems to work - but assets do not serve correctly :(

compare this - Angular 5, works well:
https://stackblitz.com/github/urish/vr-hero-aframe/tree/stackblitz

with this one - Angular 6, assets do not load:
https://stackblitz.com/github/urish/vr-hero-aframe/tree/stackblitz-angular6

you can see the console errors when it fails to load the gifs and invader.obj.txt assets.

**Comment by apai4** [comment]
@urish assets are now being served for Angular 6! Your repo looks like it's running properly now, lmk if you run into any more issues 😃

**Comment by urish** [comment]
Wow, you are simply amazing :)

If you have a few more moment to assist here, there are two more things that prevent our [master](https://stackblitz.com/github/urish/vr-hero-aframe) from importing directly into stackblitz:

1. `obj` assets are not imported (these are our 3D models). Right now, my workaround is to simply rename them to `.txt`.
2. npm packages that are imported from github do not work. This prevents loading `aframe` from npm, as it has `debug@github:ngokevin/debug#noTimestamp` as a dependency. The workaround is to load aframe [from CDN](https://cdnjs.cloudflare.com/ajax/libs/aframe/0.7.1/aframe.js) instead of the npm package.

These two issues are not roadblocks - as we have some workaround for both. Just nice to have for us :-)

**Comment by gatimus** [comment]
Works for me. Thank you!

**Comment by purplem1lk** [comment]
> @urish assets are now being served for Angular 6! Your repo looks like it's running properly now, lmk if you run into any more issues 😃

Resolution has been provided by @apai4 and confirmed - This issue will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
