### ISSUE TITLE
Debugging in Stackblitz

### ISSUE THREAD

**Issue by zlasa** [stackblitz/core#405]
Is it possible to debug and put breakpoints when editing code online on stackblitz.com? If so, how? I did not see any sourcemap files

**Comment by usersaurus** [comment]
U can open the browser in a new window, inspect it and use the sources tab :) ("open in new window" button).

Sadly, that's not a good option in, for example, this project https://react-ts-jsfu6a.stackblitz.io/

**Comment by Akshar11** [comment]
Can't stackblitz do something to enable debugging.Surely, it is an awaited feature.

**Comment by SamVerschueren** [comment]
So I'm wondering... You can just add `debugger` statements where you want and open Chrome devtools... It will stop and you can continue and step through everything. Anything I miss here?

![image](https://user-images.githubusercontent.com/1913805/114090654-0037e680-98b8-11eb-8e47-83e623e572c6.png)

**Comment by sathish869** [comment]
> So I'm wondering... You can just add `debugger` statements where you want and open Chrome devtools... It will stop and you can continue and step through everything. Anything I miss here?
> 
> ![image](https://user-images.githubusercontent.com/1913805/114090654-0037e680-98b8-11eb-8e47-83e623e572c6.png)

Thanks man! working perfectly

**Comment by mirabilos** [comment]
It doesn’t work if you want to set a breakpoint in a dependency.

**Comment by Satya0427** [comment]
actually i am notable to debug my angular project while i am usin stackblitzm,source code is not available in chrome dev tools,could you please help me

**Comment by servefast-cto** [comment]
Such an awaited feature :)
