### ISSUE TITLE
Angular not using scripts in angular-cli.json?

### ISSUE THREAD

**Issue by JasonGoemaat** [stackblitz/core#407]
I don't think scripts are loading from `angular-cli.json`.  I tried to add jquery, popper, and bootstrap js and they aren't available.  Also I can change them to invalid paths and get no errors...

https://stackblitz.com/edit/angular-bhzy2y?file=app%2Fapp-tooltip.directive.ts

**Comment by seveves** [comment]
Stackblitz does not support all the features of `angular-cli.json`. And linking from `node_modules` is not working because stackblitz does not have this folder. What you can do is adding jquery, popper and bootstrap (f.e. from a CDN) via `external dependencies` right below the npm packages in the left side menu.

**Comment by pamo** [comment]
@seveves is there somewhere we can see which `angular-cli.json` features are currently supported by StackBlitz?

**Comment by Antoniossss** [comment]
But including styles via angular.json#styles works (../node_module/----/somestyles.css), so I would expect for stripts to work as well.

**Comment by markstein** [comment]
@Antoniossss  are you sure that it work so? For me, with styles that don't work too.

**Comment by romelgomez** [comment]
I trying to add intlTelInput in angular.json and don't work for me

```
option 1
   
            "scripts": [
              "../node_modules/intl-tel-input/build/js/utils.js",
              "../node_modules/intl-tel-input/build/js/intlTelInput.js"
            ]

            "scripts": [
              "/node_modules/intl-tel-input/build/js/utils.js",
              "/node_modules/intl-tel-input/build/js/intlTelInput.js"
            ]

            "scripts": [
              "node_modules/intl-tel-input/build/js/utils.js",
              "node_modules/intl-tel-input/build/js/intlTelInput.js"
            ]
```

`Error: intlTelInput is not defined`

**Comment by abhilash1in** [comment]
> Stackblitz does not support all the features of `angular-cli.json`. And linking from `node_modules` is not working because stackblitz does not have this folder. What you can do is adding jquery, popper and bootstrap (f.e. from a CDN) via `external dependencies` right below the npm packages in the left side menu.

I don't see  "`external dependencies` right below the npm packages in the left side menu." ([screenshot](https://imgur.com/a/grNAYBK))

Has something changed?

**Comment by kc0tlh** [comment]
This should be possible in [our new VS Code editor, available here](https://stackblitz.com/codeflow)! Feel free to re-open if I am mistaken.
