### ISSUE TITLE
Cannot find module '@angular/common/http' with dependencies 5.2.8

### ISSUE THREAD

**Issue by sajeetharan** [stackblitz/core#409]
import { HttpClient, HttpHeaders } from '@angular/common/http';

Throws an error 

Cannot find module '@angular/common/http' with dependencies 5.2.8

Reproduceable [Demo](https://stackblitz.com/edit/angular-w8grut?file=app%2Fdataservice.ts)

**Comment by EricSimons** [comment]
@sajeetharan eek yeah this is a known bug with type definitions in sub-packages, we have a fix coming for it soon. That code will actually work in the preview btw, it's just the red underline is incorrect!

**Comment by sajeetharan** [comment]
Thanks :)
