### ISSUE TITLE
Errors when importing `glamorous` in tsx

### ISSUE THREAD

**Issue by luke-john** [stackblitz/core#41]
*Expected behaviour*:

Importing glamorous works

*Actual behaviour*:

Importing glamorous causes the preview to break with 
```
Fatal error:
Cannot read property 'moduleObj' of undefined
Loading index.tsx
Loading app
```
And after refreshing the preview
```
Fatal error:
Cannot read property 'isRequired' of undefined
Evaluating https://unpkg.com/glamorous@4.1.0/dist/glamorous.cjs.js
Evaluating index.tsx
Loading app
```

*Reproduction*:

https://stackblitz.com/edit/react-ts-u9qiu6

**Comment by EricSimons** [comment]
You need to install the `prop-types` package from npm :)

**Comment by EricSimons** [comment]
@kentcdodds included a note in the [installation section](https://glamorous.rocks/basics/#installation) about this:

> NOTE: If you're using React v15.5 or greater, you'll also need to have prop-types installed: npm install --save prop-types

**Comment by luke-john** [comment]
Ahh, thank you very much for that.

Really loving the look of stackblitz 👍 .

**Comment by EricSimons** [comment]
Thanks man!! Lmk if you run into any other problems — I'm going to clean up the error handling a bit tmrw, as the `Cannot read property 'moduleObj' of undefined` shouldn't have ever shown up (it's a bug on our side of things)

**Comment by luke-john** [comment]
will do thanks, very excited about being able to share typescript playground showing off the 
 glamorous typings ❤️.

**Comment by EricSimons** [comment]
FYI the fix for these errors is now live on prod 👍
