### ISSUE TITLE
This project type is not yet supported.

### ISSUE THREAD

**Issue by acedesigns** [stackblitz/core#410]
`https://stackblitz.com/github/500tech/angular-tree-component`

![screen shot 2018-04-16 at 14 59 47](https://user-images.githubusercontent.com/8522707/38810556-66ecfa9a-4187-11e8-9107-ddacc7e6cd29.png)

**Comment by seveves** [comment]
It seems like that your project is not a angular-cli project. Only angular-cli (and create-react-app) projects are currently supported.

**Comment by belighH** [comment]
it's an angular-cli project but a new version of cli not released yet.
i have a config file named angular.json (version 6.0.0.rc3) instead of .angular-cli.json (version 1.7.x)

**Comment by belighH** [comment]
Duplicate of #404

**Comment by seveves** [comment]
Should be live on prod now as stated in #404 ... I'll close this. Let's track progress over there ☺
