### ISSUE TITLE
Rename file keybinding

### ISSUE THREAD

**Issue by realtomaszkula** [stackblitz/core#417]
I have a very small feature request. That is, to rename the files in the sidebar by selecting the file and pressing the `F2` key. It is the goto key for renaming files in most IDEs and operating systems.

I know it is debatable whether or not `F` keys should be hijacked by the web apps, but since stackblitz is advertised as `online IDE for web applications` maybe you can make an exception? :pray:  :pray:  :pray:

**Comment by seveves** [comment]
Issues leading in to the same directions are #13 and #170

**Comment by kc0tlh** [comment]
@realtomaszkula thanks for the product feedback! This has been implemented along with a whole host of [other keyboard shortcuts](https://developer.stackblitz.com/guides/user-guide/keyboard-shortcuts).
