### ISSUE TITLE
Can Stackblitz be serializable and deserializable?

### ISSUE THREAD

**Issue by linonetwo** [stackblitz/core#419]
Just like we can serialize [rich text editor](https://docs.slatejs.org/walkthroughs/saving-to-a-database)'s result to a JSON, and load this JSON back into the editor.

Can Stackblitz serialize its metadata (like dependencies) and code into a JSON or so, and this JSON can be stored in a database or [IPFS](https://ipfs.io/).
Later, we can use Stackblitz to load this JSON and restore the whole project, even you open an embedded Stackblitz project in a notebook likes Quip or Notion or JupyterNotebook, when you are offline.

Now Stackblitz can deserialize by ```sdk.openProject``` and serialize by ```vm.getFsSnapshot``` but how can they work together?

**Comment by linonetwo** [comment]
Ok, I think this is not so useful. Because if you open an embedded project in your notebook app offline, you won't be able to download the dependencies, so project won't run.

**Comment by Eonasdan** [comment]
@linonetwo Idk if you're still interested in this or not but I built some features for my date picker docs that uses [lz-string](https://stackblitz.com/edit/js-wpnd4a?file=index.js) to compress an json object. On the page that I embed a stackblitz project I decompress this object and use it to update the embedded projects files. You can see it working on [my docs site](https://getdatepicker.com/6/repl.html)
