### ISSUE TITLE
typescript: autocomplete missing on some things

### ISSUE THREAD

**Issue by luke-john** [stackblitz/core#42]
**Expected behaviour**:

Glamorous component factory style arguments autocomplete the same as they do in vscode.

![vscode-autocomplete](https://user-images.githubusercontent.com/848525/29012376-671fbeb4-7b7e-11e7-88c9-0d331c24e5f9.gif)

**Actual behaviour**:

Glamorous component factory style arguments do not autocomplete the same as they do in vscode.

![stackblitz-autocomplete](https://user-images.githubusercontent.com/848525/29012385-7a6a07ae-7b7e-11e7-9f4d-3d905842912d.gif)

**Reproduction**:

The screenshot for the stackblitz behaviour was captured from the following project.

https://stackblitz.com/edit/react-ts-u9qiu6?file=components%2FApp%2FApp.glamorous.tsx

**Comment by luke-john** [comment]
Possibly it's to do with the version of typescript, Glamorous makes use of some 2.4+ features. I couldn't find what version of typescript stackblitz uses to confirm.

**Comment by EricSimons** [comment]
Thanks for reporting this! We're on TS 2.4.1, but I think I might know what's causing this though — will dig in tmrw with @apai4 and report back 👍

**Comment by luke-john** [comment]
hey @EricSimons I had some time to look into this this morning and worked out this is likely an issue with the version of typescript that monaco is using under the hood.

It appears to be pre 2.2 which is when typescript inroduced support for extending interfaces from types. https://github.com/Microsoft/TypeScript/pull/13604

A simple reproduction is available at the following link.

https://stackblitz.com/edit/react-ts-n3tizf?file=index.tsx

So it looks like this may be fixed with the next update to the version of `monaco-editor` that's being used under the hood by stackblitz.  

Notes: monaco editor pulls in typescript via `monaco-typescript` https://github.com/Microsoft/monaco-typescript/blob/master/package.json

**Comment by luke-john** [comment]
Just checked it out and everything now seems to all work great :)

Thanks so much for all the work that's been put into stackblitz 💖

**Comment by EricSimons** [comment]
@luke-john I totally forgot to circle back and let you know we bumped the monaco version earlier this week, so sorry about that! 😅  No problem at all, thanks a ton for all of your help in tracking down this bug (+ others) - we seriously appreciate it!!
