### ISSUE TITLE
it's Awesome tool

### ISSUE THREAD

**Issue by arkoleini** [stackblitz/core#422]
I never seen any online IDE much responsive, comprehensive and fully functional even better than desktop application that covers all scenarios of web development specifically in Angular frame work, 

you did great job, I introduced you web site to my colleagues to start using it for practice and learn.

you are doing great !!!

**Comment by urish** [comment]
Agreed! 

Also, in case you haven't watch this yet, they had [an amazing session about StackBlitz](https://www.youtube.com/watch?v=EBzoTnX6LzU) in ng-conf last week.

**Comment by seveves** [comment]
Gonna close this ... the team really appreciate your feedback. I can't wait to see what's coming next ☺
