### ISSUE TITLE
Mobile Preview optimization

### ISSUE THREAD

**Issue by willi84** [stackblitz/core#423]
attached I have the idea, how to make it possible to see if the mobile editing was successfull by using a small preview (like the code preview). If you want to switch, you just drag the screen in and out. Like in Youtube. And maybe for later, you could also provide a preview for the bash, too see if no errors occured.

If you have the small preview you don't need to change on every change.

![180420-stackblitz](https://user-images.githubusercontent.com/6207308/39029519-7ce00982-445c-11e8-90bf-1f6dde6d0cfa.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
