### ISSUE TITLE
Feature request: Change owner of project to anonymous

### ISSUE THREAD

**Issue by CurtisDS** [stackblitz/core#425]
I would like to keep the projects that are attached to my account curated.

I often fork projects a lot as I am working on things for testing purposes or to show examples of things on Stackoverflow. I don't want to just delete these projects as it would break the links that I have previously shared out. But I also don't want all these wayward projects to fill up my profiles project list. 

So I would like the ability to remove a project from my account and convert it to anonymous or at least be able to archive/hide them from my profile.

Thanks.

**Comment by kc0tlh** [comment]
The ability to organize your projects into folders or "collections" as we decided to call them is now available! See our [blog post on here](https://blog.stackblitz.com/posts/introducing-collections-and-social-previews/)!

**Comment by charlesr1971** [comment]
> The ability to organize your projects into folders or "collections" as we decided to call them is now available! See our [blog post on here](https://blog.stackblitz.com/posts/introducing-collections-and-social-previews/)!
> 
> _Related Issue: #2043_

This is great, but we can’t hide Collections from the General Public and potential employers, who might wish to look at our profile projects. 

Please allow us to hide/show both Collections and Projects. Thanks 😊
