### ISSUE TITLE
Remember scroll position for large files 

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#427]
Edit: 

When changing files the scroll position will always get reset to 0, it would be nice to see it save the last active line. This could save tons of time when dealing with large files and improve productivity.

**Comment by seveves** [comment]
As always: Please add a proper description that explains your issue

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month so if your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
