### ISSUE TITLE
Proposal: when forking, persist reload strategy

### ISSUE THREAD

**Issue by emilio-martinez** [stackblitz/core#430]
Currently, the reload preference not respected when forking. It always defaults to Hot reloading, which isn't desirable for all use cases. If a project is set to do page reloads, it would be good if forks of that project would follow suit rather than falling back on the default every time.

**Comment by sulco** [comment]
Thanks for reporting this!
With our latest updates, this should no longer be an issue, so I'm closing it (but feel free to reopen if you do stumble upon it again - in such case please provide a link to the project so we can reproduce)
