### ISSUE TITLE
Projects won't save

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#431]
I have noticed this issue several times already, this happens whenever I leave my laptop running overnight. At first everything seems fine... I do some changes, hit save, and the preview reloads and the save button becomes dim gray. But if you would to reload the editor page, all those changes will fall back to the last save point from the previous day. So every-time before closing the editor tab I tend to check the project in new incognito tab. Similar results will be present if checking on the phone with different IP address ( mobile data ). At first I used to copy everything to sublime and restore my code via clipboard, but recently I tried to fork the project and it just seemed to fix that issue. I don't know why or how the save sync is failing as there are no out of the ordinary console outputs in the browser.

**Comment by MarkStruik** [comment]
i have the same thing but only when i add additional packages : like adal-angular4

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
