### ISSUE TITLE
Posting to StackBlitz

### ISSUE THREAD

**Issue by ElijahAdams** [stackblitz/core#440]
Hey, 

Not really and issue more so of a question. 
Can you post to stackblitz? With http post? for [example](https://blog.codepen.io/documentation/api/prefill/) code pen allows you to prefill the editor with post. 

**The scenario** : Say for instance I have a component library like angular material and I have a button for each of my examples. When click that button it will export my example code/data  for my component to stack-blitz.

Is there a way to intercept that data or create stackblitz's dynamically?

Thank you

**Comment by tiliev** [comment]
@ElijahAdams, yes, you can - please check the [StackBlitz POST API docs](https://stackblitz.com/docs#required-form-fields).

**Comment by purplem1lk** [comment]
Thank you for your patience! The resolution provided by @tiliev above so this issue will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
