### ISSUE TITLE
Cannot read property 'end' of undefined

### ISSUE THREAD

**Issue by justinfagnani** [stackblitz/core#441]
We're hitting a compile error on https://unpkg.com/@webcomponents/shadycss@1.1.3/src/custom-style-interface.js

This file works correctly in browsers with native module support.

See the reproduction here: https://stackblitz.com/edit/js-ajeufg?file=index.js

**Comment by justinfagnani** [comment]
FYI, ultimately we're working towards reproducing this error we're seeing with some samples:

```
Unexpected identifier
Evaluating https://unpkg.com/@webcomponents/shadycss@1.1.3/src/custom-style-interface.js
Evaluating https://unpkg.com/@webcomponents/shadycss@1.1.3/entrypoints/custom-style-interface.js
Evaluating https://unpkg.com/@polymer/polymer@3.0.0-pre.12/lib/elements/custom-style.js
Evaluating https://unpkg.com/@polymer/polymer@3.0.0-pre.12/polymer-legacy.js
Evaluating https://unpkg.com/@polymer/paper-checkbox@3.0.0-pre.12/paper-checkbox.js
```

The problem seems to be with a default export that also has a name, like:

```
export default class Foo {}
```

but this isn't reproducible in a project that just uses two project-local modules, so something seems dependent on the module coming from a dependency.

**Comment by EricSimons** [comment]
@justinfagnani it looks like the typescript compiler itself is hitting an error, which is causing the output to essentially be blank, thus leading to the runtime error. Digging into what's causing tsc to break now

**Comment by EricSimons** [comment]
@justinfagnani looks like this was an issue in previous versions of TS; bumping to latest seems to fix this. Will deploy to prod and circle back once online 👍

**Comment by EricSimons** [comment]
@justinfagnani fixed on prod! Let me know if all looks good on your end as well
