### ISSUE TITLE
Teleport serializer not working as intended

### ISSUE THREAD

**Issue by colinricardo** [stackblitz/core#448]
StackBlitz code is [here](https://stackblitz.com/edit/react-tppyox?file=index.js).
JSFiddle code is [here](https://jsfiddle.net/69z2wepo/182969/).
CodeSandbox.io code is [here](https://codesandbox.io/s/lpx697lv07).

There seems to be inconsistent output between the three. Namely, Stackblitz gives something like:
`[null, Object, Object, "mango"]`
while JSFiddle and CodeSandbox gives instead:

`[undefined, undefined, undefined, "mango"]`

Not sure why this would be. I'm using Google Chrome Version 66.0.3359.117 (Official Build) (64-bit).

Relevant SO post is [here](https://stackoverflow.com/questions/50091213/why-is-this-array-filled-this-way/50091303?noredirect=1#comment87198844_50091303).

**Comment by EricSimons** [comment]
This might be related to some code we just shipped for our new Teleport feature- wil investigate & circle back. Thanks for reporting this 🙏

**Comment by EricSimons** [comment]
This should now be fixed on prod- can you take a look and lmk if all looks good on your end?
