### ISSUE TITLE
Removed package-lock.json , still an issue persists

### ISSUE THREAD

**Issue by dharmendra1234** [stackblitz/core#450]

**Comment by seveves** [comment]
May you provide a link to the stackblitz project?

**Comment by dharmendra1234** [comment]
Yes, I did. Thank you!

>> Sincerely,
>> Dharmendra 
>> 470-809-3327
Email is best way to get in touch with me.              Sent from my iPhone

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month so if your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
