### ISSUE TITLE
Console.time is not supported

### ISSUE THREAD

**Issue by qetr1ck-op** [stackblitz/core#451]
Have just figure out that `stackblitz console` doesn't support the API - https://developer.mozilla.org/en-US/docs/Web/API/Console/time.
Would be nice to have or at least give a hint where to adjust for PR.

**Comment by kc0tlh** [comment]
@qetr1ck-op thanks for the product feedback! This feature has been implemented. You can see it in action in [this example project](https://stackblitz.com/edit/console-time-demo?file=index.js) I put together.
