### ISSUE TITLE
Loading my project from GitHub breaks Stackblitz' UI 

### ISSUE THREAD

**Issue by beeman** [stackblitz/core#453]
Loading this project results in chaos 😲

https://stackblitz.com/github/beeman/angular-elements-chat-widget

The project is built with the RC's of Angular 6 and Angular CLI 6.

![image](https://user-images.githubusercontent.com/36491/39513077-b2842acc-4db8-11e8-9fd4-01674ed49732.png)

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/39518046-649af050-4e0a-11e8-8d25-f44be988f471.png)
