### ISSUE TITLE
Highlights an error on the valid result of the decorator

### ISSUE THREAD

**Issue by splincode** [stackblitz/core#454]
https://stackblitz.com/edit/typescript-tp32jg

![image](https://user-images.githubusercontent.com/12021443/39517742-70c56ab4-4e09-11e8-86a6-66bf47380ecf.png)

The syntax is valid, why is it suspended in red?

**Comment by seveves** [comment]
You don't have to add a decorator for get/set each. It is enough to set it once before the get for example.
I tried to compile your code with Typescript/tsc on my local machine without stackblitz and the result is the same (Decorators are not valid here). So this is no issue with stackblitz but your typescript code, right?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month so if your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
