### ISSUE TITLE
Writes an error when importing the module

### ISSUE THREAD

**Issue by splincode** [stackblitz/core#455]
https://stackblitz.com/edit/typescript-9vv9kg

![image](https://user-images.githubusercontent.com/12021443/39517825-be1e92f4-4e09-11e8-9fe7-00a606dd1113.png)

Valid and working imports, why are they highlighted in red?

**Comment by sanjibani** [comment]
this issue comes for me too, for modules already declared

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
