### ISSUE TITLE
github integration

### ISSUE THREAD

**Issue by DatsGawas** [stackblitz/core#460]
Hi 
  I have integrated my public repo FirstApp with stackblitz.
[https://stackblitz.com/github/DatsGawas/FirstApp](https://stackblitz.com/github/DatsGawas/FirstApp)

now I want redirect my repo to preview page directly like this
[https://rlmikpmz.github.stackblitz.io/](https://rlmikpmz.github.stackblitz.io/)

so how I can create "https://rlmikpmz.github.stackblitz.io/" this url.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month so if your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
