### ISSUE TITLE
stackblitz - Fetch returns empty response

### ISSUE THREAD

**Issue by alexfrize** [stackblitz/core#462]
```
    fetch('https://jsonplaceholder.typicode.com/posts')
      .then(res => console.log(res))
      .catch(err => console.error(err));
```

response is:
```
Response {}
__proto__: Response
```

while in local machine it works fine in the same environment (VS Code + create-react-app)

**Comment by EricSimons** [comment]
The fetch request was actually working just fine, our console just wasn't showing the non-enum properties on it :) Just deployed a fix for it to prod- lmk if all looks good on your end!

**Comment by alexfrize** [comment]
Yes! Now it's perfect! Thank you!
