### ISSUE TITLE
Stackblitz freezes and crashes when using intellisense on object

### ISSUE THREAD

**Issue by mattiLeBlanc** [stackblitz/core#464]
Hi,

I am doing a coding exercise and my stackblitz freezes in Chrome, Safari and FF.
Check out my example:
https://stackblitz.com/edit/angular-xty9np?file=src%2Fapp%2Fcomponents%2Fapp-header%2Fapp-header.component.ts

Issue occurs when I start to to type in the `ngOnInit()` under line 18:
`this.richList.pageTitleH1`

Then Stackblitz reports an error in Console
```
preview-f7ee91afae34ebb1ae11a.js:1 ERROR TypeError: Cannot read property 'pageTitleH1' of undefined
    at AppHeaderComponent.ngOnInit (VM60 app-header.component.ts:36)
    at checkAndUpdateDirectiveInline (VM175 core.umd.js:10189)
    ...
```
which is correct, but it does make Stackblitz crash and freeze and subsequently lose code.
The editor doesn't allow you to change anything anymore.

When I put an `if ( this.richList )` around the new line it doesn't crash. Of course I am making a programming error here but I didn't release my mistake because the browsers freezes.

Is this something that can be looked at?

Cheers.

**Comment by EricSimons** [comment]
@mattiLeBlanc so sorry about this! An error logging lib we're using seems to be the culprit here; just deployed a fix to prod. Can you test on your end and see if all is working fine now?

**Comment by mattiLeBlanc** [comment]
mate, you don't have to apologise. I love Stackblitz. It is spectacular!
Thanks for fixing.
