### ISSUE TITLE
unable to run the app on stackblitz

### ISSUE THREAD

**Issue by rahulz-wasnik** [stackblitz/core#465]
Hey Team,

I tried using stackblitz for the first time for a very light weight app that computes tax. It runs successfully on my local but i got the following error when i tried running it on stackblitz - 

Yikes! The page you requested couldn't be found.

URL - https://stackblitz.com/github/rahulz-wasnik/ng-tax-calculator

Please advise.

**Comment by apai4** [comment]
Hey @rahulz-wasnik looks like you're trying to import a repo that doesn't exist or is private on GitHub. For now we can only import repos that are public, but we should have private repo support coming next month!

**Comment by kkotak** [comment]
Hi @apai4 - What's the ETA on private repo support?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
