### ISSUE TITLE
Importing service in constructor of a component freezes window tab and stackblitz app crashes

### ISSUE THREAD

**Issue by DrNio13** [stackblitz/core#466]
Please note also that creating a new service by using the menu that appears after right-click on a folder creates a singleton service **without** metadata `{providedIn: 'root' }`. Also, the service is injected into the `providers` array of the module.  

<img width="161" alt="screen shot 2018-05-05 at 13 47 06" src="https://user-images.githubusercontent.com/11769448/39662964-d2031c0a-506a-11e8-9274-52193771e6a3.png">

I tried to use `{providedIn: 'root' }` in the service and remove it from the `providers` array of the module to see if that would fix the freeze/crash of the window tab when trying to import the service in the component and didn't work - window tab freezed again.

I am using macbook pro 13' with macOS Siera 10.12.6 (16G29)
Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by DrNio13** [comment]
I found what was the problem. In the service I didn't initialise a property with `new Subject<number>();`. After trying many times to import the service and making the changes line-by-line and saving an error appeared from the service and after fix this the window didn't crash.

**Comment by EricSimons** [comment]
@DrNio13 so sorry about this! An error logging lib we're using seems to be the culprit here; just deployed a fix to prod. Can you test on your end and see if all is working fine now?

**Comment by DrNio13** [comment]
No worries :) As long as i found the workaround it was not a problem :) 
Thanks for the fix. Tested it and it seems that everything is working nice and smoothly 👍
