### ISSUE TITLE
Missing stackblitz ?

### ISSUE THREAD

**Issue by RoyiNamir** [stackblitz/core#467]
I had many addresses like : 
https://stackblitz.com/edit/angular-http-client-nu5lim?file=app/app.component.ts
And not it's all gone ? 

Why is that ?
I had so many others...
How can I revert it ?

**Comment by apai4** [comment]
Hey @RoyiNamir I couldn't find a project with that name in our database, which means if it did exist at some point it has now been renamed. Could this be the one you're looking for?

https://stackblitz.com/edit/angular-http-client-nu5lim-with-timeout

**Comment by RoyiNamir** [comment]
Indeed! Thank you for the quick response!!!
