### ISSUE TITLE
Angular Generate Component does not respect SCSS or inline template settings with Angular CLI v6

### ISSUE THREAD

**Issue by Splaktar** [stackblitz/core#468]
You can see in [this example](https://stackblitz.com/edit/github-w1njoy?file=angular.json) that component `inlineTemplate` is `true` and `styleext` is `scss`, but when I generated the `add-child` component it used CSS and did not create the template inline. Here's [the component](https://stackblitz.com/edit/github-w1njoy?file=src%2Fapp%2Fapp-routing.module.ts).

I'm trying to run a workshop on 5/10 which features Angular v6 and Stackblitz. It's focused on rapid prototyping, styling, and theming with Angular Material, so having inline templates and SCSS is important.

**Comment by dvdvnl** [comment]
I can confirm that this issue persists as of today. Even though it is configured correctly in `angular.json`
```
"schematics": {
  "@schematics/angular:component": {
    "styleext": "scss"
  }
},
```
the generated file is a `css` file and the value of `styleUrls` in the component declaration points to it - the `css` file. Angular CLI on the desktop does it correctly with the same configuration.

**Comment by alisaduncan** [comment]
Confirming inline template settings in _angular.json_ is not respected yet. Updating worksheet for ngGirls workshop and ran into this problem. The following config works on local development.

```markup
 "schematics": {
    "@schematics/angular": {
      "component": {
        "inlineTemplate": true
      }
    }
  }
```
