### ISSUE TITLE
Not able to get react native to be working

### ISSUE THREAD

**Issue by ishan123456789** [stackblitz/core#469]
I tried adding react-native as a dependency in my app and there I got error that all the dependencies are not installed so when I clicked install missing dependencies I still keep on getting the error

![screen shot 2018-05-07 at 1 22 06 pm](https://user-images.githubusercontent.com/23247168/39691037-cd747cca-51f9-11e8-8ade-4649d30956e5.png)
![screen shot 2018-05-07 at 1 22 14 pm](https://user-images.githubusercontent.com/23247168/39691038-cdaebaa2-51f9-11e8-93b1-6860937db96c.png)

**Comment by realappie** [comment]
Since when does react native work in the browser ?

**Comment by ishan123456789** [comment]
My bad being noob
