### ISSUE TITLE
"New Project" button in editor UI

### ISSUE THREAD

**Issue by faceyspacey** [stackblitz/core#47]
so you can create new blitzes without having to go back to the homepage.

**Comment by EricSimons** [comment]
Interesting — is this a common workflow for you? Would love to hear more about your use case here

**Comment by faceyspacey** [comment]
Lol how else do u create new apps. U want people creating lots of these right

**Comment by EricSimons** [comment]
That's fair lol

**Comment by jfelixdev** [comment]
Also, getting back and forth from the projects view to the Editor view should be more explicit-- so like, an explicit action to make a new project, and an explicit action to go to the projects page...

**Comment by EricSimons** [comment]
@jfelixdev this is a really good point — do you have any thoughts reg UI/UX for how you'd like to see this work? Also, when you say "projects page" do you mean your profile or the homepage?

**Comment by sulco** [comment]
With the last year introduction of Dashboard, we now have an explicit way of going to it from the Editor, and creating new project. We've opted to leave the "New Project" button from the Editor screen at this time, but might get back to the idea in the future. Closing for now.
