### ISSUE TITLE
File contents will not be shown if mixpanel.com is blocked

### ISSUE THREAD

**Issue by sushruth** [stackblitz/core#470]
File contents aren't shown at all if the analytics domain is blocked. This is what the console says : 

![Imgur](https://i.imgur.com/m8PhSZT.png)

**Comment by apai4** [comment]
The mixpanel calls *should* fail without affecting the rest of the site, but it looks like the error is actually coming from loader.js failing to load. Are you blocking the domain https://cdn.jsdelivr.net?

**Comment by sushruth** [comment]
@apai4 Looks like that is it.

**Comment by seveves** [comment]
So this issue can be closed because it is no error of stackblitz, right?

**Comment by sushruth** [comment]
Yes. Thanks.
