### ISSUE TITLE
Please support project created by Vue-cli

### ISSUE THREAD

**Issue by Yangfan2016** [stackblitz/core#474]
Please support project created by Vue-cli,Thx a million

**Comment by airarrazaval** [comment]
Any ETA on Vue support? I'm very interested in this as well.

**Comment by nukadelic** [comment]
Seems like it's coming very soon ( see https://github.com/stackblitz/core/issues/14#issuecomment-395514038 ) ask Eric to add you for beta testing

**Comment by seveves** [comment]
So as @nukadelic already stated, this framework request is already tracked in #14, So let's track the progress over there and I'll close this one 😎
