### ISSUE TITLE
Angular: Support for es2015 compilation for CustomElements

### ISSUE THREAD

**Issue by lacolaco** [stackblitz/core#475]
Angular projects are compiled to es5. but `window.customElements.define` takes only native ES2015 Class. 
So I'd like to set TypeScript compilation target to `es2015`.

repro: https://stackblitz.com/edit/angular-x6gyei

```
Error: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
```

**Comment by robwormald** [comment]
As a workaround, you can add this shim to the external resources list: https://unpkg.com/@webcomponents/webcomponentsjs/custom-elements-es5-adapter.js

**Comment by lacolaco** [comment]
@robwormald It works! Thank you for the information!

**Comment by WebReflection** [comment]
alternatively, this is what basically landed in Babel 7
https://github.com/WebReflection/babel-plugin-transform-builtin-classes

**Comment by seveves** [comment]
does this still needs a fix or can we live with the workaround @lacolaco?

**Comment by justinfagnani** [comment]
This isn't just an Angular issue. The TypeScript project compiles to ES5 also. We should be able to configure the compiler for this and other settings (like presumably which decorators spec to use in the near future).

**Comment by matthewp** [comment]
I'm running into this issue as well outside of Angular. It seems that stackblitz can't be used for vanilla custom element projects.

Ideally it would be possible to disable the ES5 compilation. The % of users using a browser without ES2015 support is quite small at this point. A simple checkbox in Settings would suffice. Thanks!

**Comment by franktopel** [comment]
A workaround for this:

`npm install document-register-element@1.8.1`

That is a custom elements v1 polyfill which actually enforces polyfilling even on existing native implementations. Starting with 1.9.0 it no longer enforces polyfilling, so don't upgrades as long as you need this working (as long as Stackblitz is still stuck on Babel 6.x).

**Comment by nrtkrishna** [comment]
I got the same error but when I implement ngDoBootstrap() in app.module.ts, everything is working fine.

  ngDoBootstrap(){
    const el = createCustomElement(YourCustomComponent, {injector: this.injector});
    customElements.define('my-custom-component', el);
  }

**Comment by waterplea** [comment]
Related issues: https://github.com/stackblitz/core/issues/923 https://github.com/stackblitz/core/issues/1064
