### ISSUE TITLE
Support npm package semver / update installed packages

### ISSUE THREAD

**Issue by e111077** [stackblitz/core#478]
We are having issues where installing a package `@latest` or `@^3.0.0` will install the dependency correctly (e.g. 3.0.1), but if a new version of that package is released, on page load the installed dependency stays stuck at the previous version.

e.g. at the time of creation we have `@polymer/polymer@^3.0.0` it will install `@polymer/polymer@3.0.1`. If we add another package, namely a webcomponent that must be singleton, that relies on `@polymer/polymer@^3.0.0` after `@polymer/polymer@3.0.2` has been released, it will install both `@polymer/polymer@3.0.1`, and `@polymer/polymer@3.0.2` when they should both resolve to `3.0.2`

This use case is common when we publish a stackblitz and share it with our users.

**Comment by e111077** [comment]
👍👍👍
I think we can make that work; we will shortly have things on `@latest` Which can work with that solution

**Comment by e111077** [comment]
I think this fixes our problem for now; there's some weird stuff going on when i use packages with weird version numbers, but it gives us a workable solution for our use case.

Can you please elaborate a bit on the button's functionality? Does it just update to `@latest` or to `^X.0.0` where `X` is the last-installed major version?

**Comment by sulco** [comment]
If anyone stumbles upon this post, the answer is: it updates to the `@latest` 

Closing for now as it seems that the original issue was resolved
