### ISSUE TITLE
Keyboard not getting triggered In mobile and tablets

### ISSUE THREAD

**Issue by bhaveshvyas007** [stackblitz/core#480]
I guess touch/click events are stopped in the app? This leads to issue of keyboard not showing up in touch screen devices...

However it shows sometimes for the first time then after switching back from preview tab.. touching or select on code text doesn't trigger device keyboard

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists or if you have other suggestions, feel free to tag me or ask to reopen this issue with screenshots of the error/suggestions. Thank you! :)
