### ISSUE TITLE
Ionic App - not starting?

### ISSUE THREAD

**Issue by jagadeeshpalaniappan** [stackblitz/core#481]
Hi Team,

**Step1:**
https://stackblitz.com/
Created 'Ionic App' in Stackblitz, Ionic App is Running in stackblitz.

**Step2:**
Exported that same ionic running app from stackblitz
From my local machine, created new GitHub repository, added those ionic app files 
https://github.com/jagadeeshtechgeek/ionic-stackblitz

**Step3:**
In Stackblitz, I am trying to import from GitHub **(It is not working)**
https://stackblitz.com/github/jagadeeshtechgeek/ionic-stackblitz

**Comment by seveves** [comment]
At the moment there is only support for project that have been created with `angular-cli` or `create-react-apps`

**Comment by kc0tlh** [comment]
Importing IONIC projects from Github should just work at this point 🎉

Here are some v7 templates running inside StackBlitz: https://twitter.com/aaronksaunders/status/1694037022426509709

And here are the docs on importing repos into our new VS Code editor: https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide

_Related Issue: #219_
