### ISSUE TITLE
Custom typescript version

### ISSUE THREAD

**Issue by SimonMeskens** [stackblitz/core#483]
How do we select our version of TypeScript? From testing, I think it uses some pretty old version like 2.6.2 by default, which obviously means it's not very usable for advanced users. I can't figure out how to make it use another version though.

**Comment by michaelbuller** [comment]
Under dependencies, when you add your package... if you put typescript@2.8.2 for example, it adds that version.  Does that help?  Or are you asking about the version that Stackblitz is using for compilation on their side?

**Comment by SimonMeskens** [comment]
For example:

```ts
type Test<T> = T extends never ? true : false;
```

This is a valid type for TypeScript 2.8+. StackBlitz gives me an error that clearly shows it's not using TS 2.8+ to compile this code. If I add a dependency to a new version of TS, the error stays, so the dependency isn't actually used to compile the code.

**Comment by ffMathy** [comment]
I could really use this too!

**Comment by solenya-group** [comment]
Was going to log a new issue, but seems this might be the reason StackBlitz complains about TypeStyle code:
https://stackblitz.com/edit/typestyle

This works fine in VS Code.

What version of typescript is StackBlitz using for its code editor?

**Comment by ChuckJonas** [comment]
this would be great! 

Or if they just kept it up-to-date with the latest version of typescript that would be fine as well... I'm wanting to use 3.4 features!

**Comment by rdeneau** [comment]
Current version seems to be `2.6.2`, according to this [package.json @ Line 26](https://github.com/stackblitz/core/blob/master/sdk/package.json#L26).
→ Is there a way to get TS 3.5?

**Comment by mattwilson1024** [comment]
Has anybody found a way around this? When I view package.json in devDependencies I see `"typescript": "~3.1.1"` (regardless of what I list for devDependencies in my actual project). That's quite an old version and means I can't open any project that uses optional chaining syntax from TypeScript 3.7 because I get an error in the preview

**Comment by lazarljubenovic** [comment]
😢

**Comment by kc0tlh** [comment]
Update: This issue has been resolved. See #337 for additional context!
