### ISSUE TITLE
Support JPEG from GitHub Import

### ISSUE THREAD

**Issue by YukiDayDreamer** [stackblitz/core#484]
I imported my project from GitHub, and all my JPG files are successfully imported but none of JPEG files.

**Comment by seveves** [comment]
May you provide your stackblitz project or github repo so others can reproduce your error?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month so if your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
