### ISSUE TITLE
Interval not cleared when code change

### ISSUE THREAD

**Issue by csleead** [stackblitz/core#486]
For example, when you write`setInterval(() => console.log('123'), 1000)` and then change to `setInterval(() => console.log('456'), 1000)`, you can see the first interval still running

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month so if your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
