### ISSUE TITLE
When export a project to local machine, there is no git integration. 

### ISSUE THREAD

**Issue by Jalalhejazi** [stackblitz/core#49]
It will be nice to use git side-by-side with stackblitz. Let me help you with that. 

Kind regards
Jalal Hejazi
Instructor

**Comment by EricSimons** [comment]
What do you mean by no git integration? As in, there isn't a repo already set up in the exported projects?

**Comment by Jalalhejazi** [comment]
Thank you for the reply :-) continue the good work.




Jalal Hejazi

https://about.me/jalalhejazi




2017-08-07 21:47 GMT+02:00 Eric Simons <notifications@github.com>:
