### ISSUE TITLE
can not install latest version after published in npm

### ISSUE THREAD

**Issue by vthinkxie** [stackblitz/core#491]
Hi , I just publish an new version of my package, but when I install it in stackblitz, it tall me unable to resolve package.
https://www.npmjs.com/package/ng-zorro-antd here is the latest version 0.7.0
and here is what happened when install it in stackblitz
<img width="487" alt="2018-05-15 5 05 38" src="https://user-images.githubusercontent.com/1506722/40048103-ede4f2f8-5863-11e8-80e9-d36446efaae1.png">

**Comment by lorenzofox3** [comment]
Same here (with smart-table-ng@0.0.5 stuck at 0.0.4). It may be related to latest [npm incident though](https://status.npmjs.org/incidents/238t55n6f03f). But the issue is apparently solved on other cdns such [unpkg](https://unpkg.com/smart-table-ng@0.0.5/bundles/smart-table-ng.umd.js)

**Comment by vthinkxie** [comment]
we just publish 0.7.1 version, but can only install 0.7.0 version at stackblitz
