### ISSUE TITLE
Auto-import Angular project via URL error  

### ISSUE THREAD

**Issue by arangates** [stackblitz/core#492]
i tried to import angular project from github repo via url
https://github.com/akveo/ngx-admin/tree/starter-kit
like https://stackblitz.com/github/akveo/ngx-admin/tree/starter-kit
and it says
 
`The dependencies for this project couldn't be resolved.`

**Comment by seveves** [comment]
Looks like a bug to me ... can you find out which dependency couldn't be resolved?

**Comment by nnixaa** [comment]
Hey @seveves, but how can we? As the error page doesn't provide us with any additional info:

![image](https://user-images.githubusercontent.com/230527/42091631-c88f9152-7bae-11e8-9f1a-9483116011d8.png)
`npm i` works perfectly fine on my local machine.
Please let us know what additional information you need to investigate this one.
Thanks!

**Comment by nnixaa** [comment]
Hey @seveves, still no news?
