### ISSUE TITLE
Test angular6

### ISSUE THREAD

**Issue by nrabearison** [stackblitz/core#493]

**Comment by nrabearison** [comment]
Test angular6

**Comment by madurimanoj** [comment]
what is the issue? the project seems to be running smooth.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month so if your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
