### ISSUE TITLE
The dependencies for this project couldn't be resolved

### ISSUE THREAD

**Issue by luchoman08** [stackblitz/core#496]
Scuseme, that is the output when i try to import my angular 5 project to stackblitz, is no more output in the error message, and this is the repo https://github.com/luchoman08/asignacion_frontend

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
