### ISSUE TITLE
Unable to import .ts file in .tsx files.

### ISSUE THREAD

**Issue by adityaparab** [stackblitz/core#497]
Hello, I generated a react typesript project and I am unable to import my redux module's index.ts file in the project's main file `index.tsx`

Here is a snapshot of the error

![image](https://user-images.githubusercontent.com/5561498/40162033-383b706c-59d0-11e8-9ff7-0db3c4f3cde7.png)

Link where the error can be reproduced - https://stackblitz.com/edit/adityaparab-react-redux-ts?file=index.tsx

**Comment by sulco** [comment]
Thanks for submitting the issue! I've just checked the repro - it's not fixed :)

**Comment by mindplay-dk** [comment]
> it's not fixed :)

He said, and closed the issue. 🙂?

**Comment by sulco** [comment]
@mindplay-dk yup, that's cold.
Sorry, I meant: "now". It's fixed now 😅
