### ISSUE TITLE
Save Changes on Fork

### ISSUE THREAD

**Issue by spottedmahn** [stackblitz/core#498]
If I have pending changes, and I make a fork, those changes are lost 😢

All the other actions like navigate to stackblitz home or go to my profile provide a prompt:

![image](https://user-images.githubusercontent.com/14079228/40200894-7adfd370-59eb-11e8-8c5e-5bcb643fbf07.png)

**Comment by ctaleck** [comment]
I'm having the same problem. I'm behind a corporate proxy. Could that be related?

**Comment by kc0tlh** [comment]
Thanks for reporting! This issue has been resolved.

**Comment by spottedmahn** [comment]
thanks @kc0tlh!
