### ISSUE TITLE
Support System.import() and import()

### ISSUE THREAD

**Issue by faceyspacey** [stackblitz/core#50]
Currently `System.import('./Foo')` returns an empty object. 

Ideally that would also work with dynamic expressions like this: ```System.import(`./${page}`)```

And super ideally, `import()` would be transpiled to `System.import()`, so users could still use their babel-based code even though it's running in a SystemJS environment :)

Unfortunately that means I won't be able to supply the React Universal Component demo. I mean I could do what I did in the Redux-First Router demo and make it using static imports and a hash, but in this case that would defeat the purpose. It's all good though. You've done tremendous work here and you got other fish to fry.

I'll leave this issue here for when it becomes priority.

PS. though, if at least the `System.import()` taking a static string worked, then it would make sense to supply the RUC demo. If it accepted dynamic expressions, well that's great--it shows *Universal* also working in a SystemJS environment (though without the server synchronous rendering aspects).

**Comment by faceyspacey** [comment]
I actually found a reasonable solution:

https://stackblitz.com/edit/react-pnzphy?file=components%2FApp.js
> mock `import()` to be `Import()`

**Comment by EricSimons** [comment]
@faceyspacey totally agree — I'm on it! Will enable support for both System.import as well as import()
