### ISSUE TITLE
Not able to fork or save my work now

### ISSUE THREAD

**Issue by yaswanthkata** [stackblitz/core#503]
getting a 500 in console
![not able to svae or fork my work](https://user-images.githubusercontent.com/3971157/40301280-4482539a-5d09-11e8-98a4-e604c466501d.JPG)

**Comment by EricSimons** [comment]
Hm... I was just able to fork that same project w/o any issues. What browser are you using?

**Comment by yashwanthkata** [comment]
chrome.I saved it,still lost all my work.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
