### ISSUE TITLE
Preview in editor is different from when opened as app

### ISSUE THREAD

**Issue by AbakumovAlexandr** [stackblitz/core#505]
Here is an [editor link](https://stackblitz.com/edit/angular-cdk-table-test-5spdk3) and here is an [app link](https://angular-cdk-table-test-5spdk3.stackblitz.io/).

As you can see, they are different for some reason.

**Comment by AbakumovAlexandr** [comment]
Ok, that was for a few minutes only. After that it became fine.

**Comment by AbakumovAlexandr** [comment]
Actually, it works only in one of my browsers - Opera. In all others (IE 11, Edge, Chrome, FF) it still shows differently.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
