### ISSUE TITLE
Ant Design Pro is not supported

### ISSUE THREAD

**Issue by JoeyKo** [stackblitz/core#506]
[https://stackblitz.com/github/ant-design/ant-design-pro](https://stackblitz.com/github/ant-design/ant-design-pro)

**Comment by seveves** [comment]
As [the docs say](https://stackblitz.com/docs#importing-projects) you can only import `create-react-app` and `angular-cli` projects at the moment. Custom webpack config project will be supported one day hopefully.

**Comment by aliustaoglu** [comment]
I am using Ant Design with create-react-app and I did not eject. Only time you need to customise ant.design is when you want to import styles. Ant design uses a babel plugin which apparently you cannot configure in stackblitz (but you can configure in create-react-app). But you can still manually import styles. Check below example:

https://stackblitz.com/edit/react-rwf8pw?file=style.css

But you cannot import that project from GitHub as it uses webpack.
