### ISSUE TITLE
Find widget shows up in console when console is focused

### ISSUE THREAD

**Issue by magikMaker** [stackblitz/core#510]
When the focus is in the (custom stackblitz) console and ⌘+F is used to open the find widget, the widget shows up inside the console instead of in the editing aread.

See screenshot with two find widgets
<img width="1532" alt="screen shot 2018-05-24 at 10 43 22" src="https://user-images.githubusercontent.com/905811/40474567-accfd714-5f3f-11e8-96d1-f184e2e9f240.png">

**Comment by sulco** [comment]
Thanks for reporting this! We have undergone massive rewrites since it was an issue, and it looks like it's not happening anymore. I'm closing it, but please reopen if you still experience it!

**Comment by magikMaker** [comment]
Thanks, I noticed the rewrite(s). Awesome work!! 💪
