### ISSUE TITLE
The dependencies for this project couldn't be resolved.

### ISSUE THREAD

**Issue by flocela** [stackblitz/core#513]
I don't know why I'm getting this error. This is my repo https://stackblitz.com/github/flocela/CollectionsQuestion/tree/master

Sorry to bother you. It does work on my computer. I don't know what could be wrong.

-Flo

**Comment by nisheeRai** [comment]
Facing the same issue.
The dependencies for this project couldn't be resolved.

**Comment by ersaab** [comment]
Did anybody got the answer?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or reopen this issue with an updated project link, description, and screenshots of the error. Thank you! :)
