### ISSUE TITLE
can I close the bracket like file tree in code area？

### ISSUE THREAD

**Issue by jun58** [stackblitz/core#514]
![image](https://user-images.githubusercontent.com/20509429/40530637-253f481e-602c-11e8-8dcd-67623094846b.png)
=======>  
![image](https://user-images.githubusercontent.com/20509429/40530676-48b07f5c-602c-11e8-976e-d8e4aad1f4bb.png)

I want to close bracket in code area so that I can see more other code , just like I can close the file tree above, so what should I do?

**Comment by tiliev** [comment]
@jun58, It seems this is not currently supported. Marking it as enhancement.

**Comment by purplem1lk** [comment]
Thank you for your patience! Users are able to close code blocks in the editor (see screenshot below). This issue will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)

<img width="269" alt="Screen Shot 2021-04-24 at 11 22 39 AM" src="https://user-images.githubusercontent.com/49956513/115963926-c4279700-a4ef-11eb-9bda-a6e300e89272.png">
