### ISSUE TITLE
Live load GitHub repo's specific commit

### ISSUE THREAD

**Issue by bytech-ca** [stackblitz/core#515]
We're able to load a GitHub repo by appending the user and repo name to stackblitz.com/github. A cool feature would be to load specific commits.

The url structure for GitHub commits is /github_user/repo_name/commit/hash_of_commit, and hopefully this addition would be very easy to implement.

**Comment by seveves** [comment]
@bytech-ca it seems like that it is already possible to use a specific commit. Check out the docs at https://stackblitz.com/docs#import-from-github

**Comment by bytech-ca** [comment]
Ahhh, I was trying /commit instead of /tree. The documented path does indeed work. Thank you - consider this issue solved.
