### ISSUE TITLE
variable defined with a let works outside the block

### ISSUE THREAD

**Issue by ekdev2** [stackblitz/core#516]
the below is working in the editor when it shouldn't:

let x = function(){
  if(true){
    var v = 2;
    let l = 1;
  }

  console.log(v);
  console.log(l);
}

x();

**Comment by ekdev2** [comment]
this works as well when it shouldn't

const c;

c = 2;

console.log(c);

**Comment by seveves** [comment]
This works in the official [Typescript playground](https://www.typescriptlang.org/play/index.html) but you get a warning in the editor (same in Stackblitz).
Stackblitz compiles the Typescript to ES5 and there is no such concept of `const` or `let`.
You can see this when you inspect the compiled code in the dev tools:
```javascript
(function(System, SystemJS) {System.register(["./style.css"], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    var x, appDiv;
    return {
        setters: [
            function (_1) {
            }
        ],
        execute: function () {
            x = function () {
                if (true) {
                    var v = 2;
                    var l = 1;
                }
                console.log(v);
                console.log(l);
            };
            x();
            // Write TypeScript code!
            appDiv = document.getElementById('app');
            appDiv.innerHTML = "<h1>TypeScript Starter</h1>";
        }
    };
});

})(System, System);
//# sourceURL=https://typescript-3cknuw.stackblitz.io/tmp/appfiles/index.ts
```
But when you are using the javascript template there is no such warning in the editor.
IMHO this should be fixed.
