### ISSUE TITLE
Angular 5.2.10 app runs locally, but fails in StackBlitz

### ISSUE THREAD

**Issue by catull** [stackblitz/core#519]
This repo addresses issue 287 reported against `angular2-json-schema-form`:

https://github.com/catull/angular2-json-schema-form-issue-287

However, when loaded from Stackblitz
     https://stackblitz.com/github/catull/angular2-json-schema-form-issue-287

```log
Uncaught (in promise) TypeError: Cannot read property 'defaultExtension' of undefined
    at Object.generateConfig (engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3)
    at Object.start (engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3)
    at me (preview-1f727e0cbae2a3ba41a0a.js:1)
    at preview-1f727e0cbae2a3ba41a0a.js:1
```

This is on crome 66.
Already checked the configuration of chrome://serviceworker-internals/, but the error above persists.

**Comment by tiliev** [comment]
I tried your sample in Chrome, Version 67.0.3396.87 (Official Build) (64-bit) and it is working correctly. Do you still experience this error?

**Comment by catull** [comment]
Nope, the error is still visible in the console log.

Uncaught (in promise) TypeError: Cannot read property 'defaultExtension' of undefined
    at Object.generateConfig (engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3)
    at Object.start (engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3)
    at me (preview-fe7237b13d780dbf847da.js:1)
    at preview-fe7237b13d780dbf847da.js:1

The progress bar is almost through at the top, but the spinner is still circling.

This is with Chrome Version 67.0.3396.79 on macOS X 10.13.5.
I saw it on macOS X 10.12.6 before when I reported the error originally.

**Comment by catull** [comment]
Latest Firefox gives me a different error by the way:

Unhandled promise rejection 
TypeError: r.scriptLanguage is undefined
Stack trace:
generateConfig@https://c.staticblitz.com/assets/engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3:13655
start@https://c.staticblitz.com/assets/engineblock-bc7b07e99ec5c6739c766b4898e4cff5acfddc137ccb7218377069c32731f1d0.js:3:22715
me@https://c.staticblitz.com/assets/preview-fe7237b13d780dbf847da.js:1:23893
[1262]/window._preboot/<@https://c.staticblitz.com/assets/preview-fe7237b13d780dbf847da.js:1:24408
u@https://c.staticblitz.com/assets/common-dd6c1ca1865a48151a33a.js:1:23777
T/<@https://c.staticblitz.com/assets/common-dd6c1ca1865a48151a33a.js:1:23899
f@https://c.staticblitz.com/assets/common-dd6c1ca1865a48151a33a.js:1:26604
common-dd6c1ca1865a48151a33a.js:1:24134

**Comment by catull** [comment]
@tiliev Out of curiosity, which OS are you using ?

**Comment by tiliev** [comment]
That's strange, I have it working on FF and Chrome without errors. My OS is:
![winver](https://user-images.githubusercontent.com/6439482/41417165-3b186c1e-6ff5-11e8-8eb3-9ccced470a90.PNG)

**Comment by catull** [comment]
I do not have Windows OS at my disposal.

I did check the service worker configuration and stopped, unregistered everything.
It did not help.

**Comment by atalantus** [comment]
Any updates on this?

**Comment by atalantus** [comment]
This might help: https://stackoverflow.com/questions/53086352/angular-testing-cannot-read-property-name-of-undefined

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
