### ISSUE TITLE
Not able to run angular-cli project from github import

### ISSUE THREAD

**Issue by yashnarang16** [stackblitz/core#520]

**Comment by tiliev** [comment]
@yashnarang16, please provide the GitHub repo which you are unable to import so we could further investigate.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
