### ISSUE TITLE
[Feature Request] React Native Template

### ISSUE THREAD

**Issue by Meligy** [stackblitz/core#526]
Dear super awesome people who created this super amazing tool,

Can we please extend awesomeness to React Native as well?

The official React Native docs use http://dabbott.github.io/react-native-web-player
Which uses React Native Web to render React Native stuff in the browser.

The only thing I miss from that is NPM packages.
I know most likely not every NPM package will be usable in web, but even limited support will be great.

Is that possible?

Thanks heaps.
Cheers,

**Comment by cjmling** [comment]
As this is still under suggestion for more than half a year.  May be try codesandbox for now?

Starter template for react-native : https://codesandbox.io/s/q4qymyp2l6

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
