### ISSUE TITLE
Unable to install web3

### ISSUE THREAD

**Issue by zidzid1234** [stackblitz/core#527]
Hi, could you resolve this issue on the web3 package? when I tried to install web3, I got this: "Unable to resolve package. bignumber.js @ git+https:github.com/frozeman/bignumber.js-nolookahead.git Please try install a different version or range"
I even can install that on my local computer using NPM... So please resolve this. Thank you.

**Comment by jakobrosenberg** [comment]
Also getting this error on a git linked dependency. Any status update?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
