### ISSUE TITLE
Order of external resources/dependency loading

### ISSUE THREAD

**Issue by pshihn** [stackblitz/core#528]
I'm using web components, and I need to load a polyfill for Firefox. I added the polyfill as one of the external resources. Now there's a race condition when the polyfill is loaded vs when the web component code from the npm package is loaded. 

For example: https://stackblitz.com/edit/wired-elements?file=index.html
This, in Firefox, may create an error 'customElements is not defined' i.e. no polyfill. 
But if you hit the reload button in the preview panel, sometimes it loads fine. 

Is  there a more reliable way to ensure proper polyfill loading?

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
