### ISSUE TITLE
Add a test runner window

### ISSUE THREAD

**Issue by markwhitfeld** [stackblitz/core#529]
I am really loving this tool but what it really needs is a way to run the tests in another window and/or pane similar to the way that the serve window runs.

I mainly work in Angular so I am thinking about the karma jasmine html runner opened by `ng test` but I'm sure it would be useful for React and Vue to also have their testing story covered too.

👍 to vote for this issue.

**Comment by kc0tlh** [comment]
Merging this with issue #226
