### ISSUE TITLE
Support for angular 6 workspace with libraries

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [stackblitz/core#530]
Since angular 6 we're able to create and maintain embedded libraries. Those libraries might be published eventually, but during development the whole idea is to have them available right away. 

I've tried to [open such a project in stackblitz](https://stackblitz.com/github/tobi-or-not-tobi/lipstick-css), but it fails as it doesn't seem to understand the structure. It seems to try to fetch the internal project from somewhere, which obviously fails as I haven't published it yet (and I'd like to work on the development version). 

It would be great if this can be supported – great job on this project!

**Comment by changhuixu** [comment]
Related to issue #220

**Comment by tobi-or-not-tobi** [comment]
Closed as I created #533 as well.
