### ISSUE TITLE
Improved Mobile Support

### ISSUE THREAD

**Issue by milky2028** [stackblitz/core#531]
I just wanna throw my hat in the ring and put in another vote in for improved mobile support. There are already a number of issues that address some of the problems in using Stackblitz on mobile, including:

#480
#349
#164
#100
#32

I also understand that lots of these issues are related to the Monaco editor itself.

I believe there is a strong use case for mobile editing, as it would allow us to develop and test on the same platform we're deploying to, especially considering that mobile is now the primary way our apps are consumed. There's a strong community of iPad coders out there who might also use Stackblitz as their go-to IDE. 

I want to praise the mobile UI itself and say that I do think this is the ideal interface for editing, it's just that the editor itself is too buggy for everyday use at this time.

The number of great editors available on mobile is basically none (at least on Android, the situation might be better on iOS). I believe that, as an easily accessible web app, great mobile support could be a differentiator for Stackblitz. 

[Screencap Showing Usage](https://drive.google.com/file/d/1Ej6v5XOYkF7D5sHGFSWxP7LdojWHS-PD/view?usp=sharing)
Tested on OG Google Pixel, Android P Beta, Chrome 66

Specific Feature Requests:
* Add to home screen support (this also has added benefits for desktop)
* Ability to add npm packages on mobile
* Larger touch target for console drawer on mobile, as I frequently end up hitting the 'Edit on Stackblitz' button when I'm trying to open the console drawer. 

Asides: 
* I would pay about $7 - $12 for Stackblitz use a month. 
* I'm willing to help make this a reality. I currently work as an Angular Front End Dev.

**Comment by charlesr1971** [comment]
Yes. And that irritating panel keeps popping up in the editor, which makes it impossible to select anything on my iPhone. In fact, StackBlitz is unusable on mobile Safari, which is astonishing, considering the engineers have put quite a lot of effort into the mobile UI. At least, give us a setting to disable the pop up panel in the editor!

**Comment by EricSimons** [comment]
@charlesr1971 what pop up panel are you talking about? And we absolutely do have a save button for mobile view- here’s a [screenshot](https://i.imgur.com/Buh9z5c.jpg)
)

**Comment by charlesr1971** [comment]
OK. I am going to send you some screenshots. I am using iOS12 on an iPhone 7...

**Comment by charlesr1971** [comment]
![99d9a947-b907-4d92-855c-e95b142c0692](https://user-images.githubusercontent.com/827046/48973693-d6126080-f03d-11e8-8436-951e6ee835c5.png)
![9217e7ad-3e93-4156-abd5-7e61e7ffd1f6](https://user-images.githubusercontent.com/827046/48973694-d6126080-f03d-11e8-9d04-0c6e3b0bb30e.png)

**Comment by charlesr1971** [comment]
When I click on the branch icon, it shows the following dialog. But, as I said, there is no way for me to save my changes?
![89fedd06-b7ea-43aa-a2c9-1b0df70857ea](https://user-images.githubusercontent.com/827046/48973727-a57ef680-f03e-11e8-9589-7d983a8628c3.png)

**Comment by charlesr1971** [comment]
Whenever, I click in the editor and try and select text, a black panel pops up with lots of actions on it with short cuts, as you can see in the 2nd image. Why am I seeing shortcuts anyway on an iPhone? It makes it impossible to use the editor...

**Comment by charlesr1971** [comment]
And here is what happens when I preview the index.html file of my Angular project...

![bb100b33-6b7d-4930-8bc6-5bc75ec74f98](https://user-images.githubusercontent.com/827046/48973839-d8c28500-f040-11e8-9e3a-75790b55906a.png)

**Comment by EricSimons** [comment]
@charlesr1971 what iPhone model/OS are you using?

Regarding the pop-up, that's from VS Code itself. Their stuff isn't optimized for mobile usage, so we'll have to hack it to be better touch optimized. Certainly not intentional UX from our end.

**Comment by charlesr1971** [comment]
iOS12 on an iPhone 7

**Comment by charlesr1971** [comment]
Personally, I don’t think there is enough space on a smart phone for that panel, so it would be great, if you could just get rid of it. Maybe, this is not possible, if you have no control over the VSCode editor?

**Comment by charlesr1971** [comment]
Anyway. I appreciate your help on this. I really would use StackBlitz a lot, if I can use the editor & the preview properly. I spend a lot of time coding on my mobile, mainly using Coda IDE App. But, it has its limitations.

**Comment by rom1504** [comment]
I completely agree having stackblitz working on mobile could make it the first usable ide on mobile.
Would be great to be able to code on mobile.

**Comment by charlesr1971** [comment]
I did actually talk to a StackBlitz engineer about this issue & he said he would try to fix the problems. This was 6 months ago. He actually said it was VSCode's fault. Apparently, VSCode is essentially embedded into StackBlitz and VSCode is obviously not optimized for the mobile. However VSCode is written in TypeScript & therefore it could easily be optimized for the mobile.

**Comment by bretbas** [comment]
I have the same isure.
I can't paste/copy in the stackblitz editor. I want use stackblitz on my android phone

**Comment by charlesr1971** [comment]
Try codesandbox.io It is like StackBlitz but with better mobile support. It uses the same VSCode plugin, but you can paste into the editor.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists or if you have other suggestions, feel free to tag me or ask to reopen this issue with screenshots of the error/suggestions. Thank you! :)

**Comment by charlesr1971** [comment]
Having said that, **StackBlitz** is a better overall product, due to its fantastic Git integration. I actually don’t bother to use either **CodeSandbox** or **StackBlitz** on the mobile, anymore.
