### ISSUE TITLE
Maintain (and build?) angular apps with embedded projects

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [stackblitz/core#533]
I've used the angular-cli to generate an app with some embedded projects. I'd love to experiment StackBlitz with this project, but I unfortunately run into an error when I load https://stackblitz.com/github/tobi-or-not-tobi/lipstick-css. StackBlitz shows the error:

> Can't find package:sample-components

(where sample-components is one of my embedded projects).

I've already seen #404 (which is fun ticket number given my error...), but I'm uncertain if I should follow that ticket to get full support. 

In addition, I'd like to bring the following to the discussion, interesting to see how that should work in StackBlitz:
- by default the development workflow for embedded projects requires a build of those projects (using ng-packagr) in order to reference components from those projects
- I've tried to inspire for a smoother dev experience at https://github.com/angular/devkit/issues/730, and although my workaround works fine during development, the potential risks of using different build systems is fair. 

Based on this, I'm wondering if StackBlitz is planning to build the embedded projects? Ideally with a watch mode (although that's not yet provided by the CLI, so fair to wait for that).

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
