### ISSUE TITLE
Integrate with VSCode

### ISSUE THREAD

**Issue by michaeljota** [stackblitz/core#534]
Hi! Thanks for this amazing editor. 

Giving this is an online editor, and even when we are living in a always-connected generation, it would be really awesome if you can setup a local project in VSCode and open it online with Stackblitz. Or, likewise, create a project in Stackblitz and continue working offline with VSCode.

**Comment by MrJmpl3** [comment]
I work to this extension , but i dont have time for finish ..

https://github.com/MrJmpl3/vscode-extension/tree/develop

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
