### ISSUE TITLE
[Bug] Angular 6 project doesn't work

### ISSUE THREAD

**Issue by luchillo17** [stackblitz/core#535]
I think it might be because i just updated everything to latest, or that i removed jasmine deps to replace with jest, here's what `ng version` has to say about the project.
![image](https://user-images.githubusercontent.com/9698639/40941993-59c156d4-6812-11e8-8338-efb0c1acdc44.png)

**Comment by luchillo17** [comment]
Had to revert the update of deps, the specific commit is this (may or may not be useful): https://github.com/luchillo17/AVLTreeDemo/commit/0f5ebd7a4a826ca793030c6b2d2a72f47e58c632

**Comment by tiliev** [comment]
@luchillo17, you can provide a StackBlitz sample for easier troubleshooting.

**Comment by luchillo17** [comment]
Here's the example with the GitHub repo linked before, one with the branch that works & the other is the one that breaks after deps update:
Branch with error (master): https://stackblitz.com/github/luchillo17/AVLTreeDemo
Branch with deps update revert: https://stackblitz.com/github/luchillo17/AVLTreeDemo/tree/StackBlitzCompatibility

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
