### ISSUE TITLE
Sample throws an error

### ISSUE THREAD

**Issue by wpayze** [stackblitz/core#536]
Opening https://stackblitz.com/angular/lkkypkdoeae?file=app%2Fsidenav-overview-example.ts results in

Error in /turbo_modules/@angular/compiler@5.2.11/bundles/compiler.umd.js (529:34)
Unexpected value 'undefined' exported by the module 'DemoMaterialModule'
Evaluating main.ts
Booting application

**Comment by tiliev** [comment]
Hello, this appears to be not related to StackBlitz. When I open the sample through the material [website](https://material.angular.io/components/sidenav/overview) it works - https://stackblitz.com/edit/sb-core-536.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or reopen this issue with a description and screenshots of the error. Thank you! :)
