### ISSUE TITLE
External resources (HTML5 media sources) fail to load

### ISSUE THREAD

**Issue by friday** [stackblitz/core#537]
https://stackblitz.com/edit/js-l4tufz?file=index.html

It's only working in Firefox's "Private Window", (not Chrome's "Incognito Mode" or normal windows)

It seems to be due to service workers:

![screen shot 2018-06-06 at 16 24 04](https://user-images.githubusercontent.com/515120/41044236-1567863a-69a6-11e8-9804-501cab24ebe3.png)

The same example works in any other environment I've tried. Example (jsfiddle): https://jsfiddle.net/e49nrtb7/

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or reopen this issue with screenshots of the error. Thank you! :)
