### ISSUE TITLE
Modify Package.json ssh dependencies

### ISSUE THREAD

**Issue by huyle93** [stackblitz/core#542]
1. Is there a way that we can see and modify the actual package.json file instead of using dependencies tab on the left of the app? (on browser)
2. I try to find a way to add ssh dependencies from git repo ssh. I tried to add it into the external resources tab but I believe it won't add the ssh url into the package.json. Sample ssh dependency (Angular project) that i want to add looks like this `"@xx-comps/action-button": "git+ssh://git@github.com/username/repo.git#1.0"`. We can do this in VScode or any code editor.

Tks,
Huy

**Comment by kc0tlh** [comment]
StackBlitz now supports standard package.json behavior.
