### ISSUE TITLE
Allow for arbitrary file types in projects

### ISSUE THREAD

**Issue by justinfagnani** [stackblitz/core#543]
I was trying to create a demo that requires an external SVG file and the UI wouldn't let me create a file with an .svg extension.

**Comment by tiliev** [comment]
Hello, @justinfagnani,
Currently StackBlitz does not support images and static assets. The team is working on this. You can take a look at this issues - https://github.com/stackblitz/core/issues/72 & https://github.com/stackblitz/core/issues/45.
You can workaround this by uploading your images elsewhere and referencing them in StackBlitz or using GitHub - https://github.com/stackblitz/core/issues/45#issuecomment-375162006.
