### ISSUE TITLE
Make this a Progressive Web App?

### ISSUE THREAD

**Issue by nebrelbug** [stackblitz/core#544]
I only recently found out about StackBlitz, and I love it! I like the offline "dev server" functionality especially, because there's nothing more annoying than having a temporary internet crash and your playground crashing.

One problem with StackBlitz, though, is that when you can't get onto the editor page in the first place without internet. If it were a Progressive Web App, it would theoretically load faster (at least on Chrome) and work offline (at least on Chrome). One example is [StackEdit](https://stackedit.io/), a Markdown editor I use all the time. Even when I'm offline, I can still access it because it's a PWA.

Would this be a good idea, inside the project's bounds, or even feasible?

**Comment by purplem1lk** [comment]
Thank you for your patience - Great suggestion! We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by Vixeliz** [comment]
Sorry for commenting on this however it appears the pwa still won't initially work offline. So if I am out and about without internet I can't launch stackblitz in the first place offline
