### ISSUE TITLE
Can't find package: @app/app.module

### ISSUE THREAD

**Issue by loktionov129** [stackblitz/core#545]
Can you add a support `compilerOptions.paths` from tsconfig.json ?
```JavaScript
{
  "compilerOptions": {
    "baseUrl": "src",
    "paths": {
      "@app/*": ["app/*"]
    }
  }
}
```
<img src="https://sun9-5.userapi.com/c840524/v840524906/74f44/7viyr1RWKrc.jpg" />

**Comment by tiliev** [comment]
Duplicate to https://github.com/stackblitz/core/issues/220.
