### ISSUE TITLE
import from github

### ISSUE THREAD

**Issue by geronimoooooooo** [stackblitz/core#548]
Hi, great IDE.
But one should be able to import a project from github :/.

**Comment by tiliev** [comment]
@geronimoooooooo,
You can import from GitHub, please take a look at the documentation how to achieve it - https://stackblitz.com/docs#import-from-github.

**Comment by geronimoooooooo** [comment]
Ahhh that is awesome! Maybe place a button, or a piece of information, somewhere in the IDE so one can see that feature. Was looking for 2 mins and assumed that the feature is not implemented.

**Comment by ukon1990** [comment]
Yeah, it should be more obvious that you can do so.
And it would also be nice if it just found your current repositories, so you could just clone them directly.

https://api.github.com/users/{username}/repos provides this information.

They also have one for fetching private repos also I think.

https://developer.github.com

**Comment by kkotak** [comment]
@tiliev Thanks for that tip about Github projects. Though I don't see a way to commit/push changes back to Github from Stackblitz. Also, I don't see the changes made to Github by other means being synced to Stackblitz. Am I missing something?

**Comment by himnsuk** [comment]
Can we push code to github from stackblitz too ?

**Comment by damonquire** [comment]
any word on pushing code to github from stackblitz?

**Comment by Local9** [comment]
@damonquire from what I've seen [here](https://www.youtube.com/watch?v=i01V52I56TA) you can push to GitHub but I can only gather that it cannot import private repos? can someone correct me on this?

**Comment by tdekoekkoek** [comment]
It is still very unintuitive.  Coming to this discussion a year later, and I can't see how to import a github project.

**Comment by ShilpaLalwani** [comment]
I found one extension Github to Stackblitz . Add this extension to your chrome rowser and when you open your repo in github you will get a button to open your repo directly in stackbliz.
![image](https://user-images.githubusercontent.com/23742088/60002720-0b0b8380-961e-11e9-9edd-90632b175557.png)

**Comment by tdekoekkoek** [comment]
thanks!  That looks promising

**Comment by KwintenP** [comment]
Url with the documentation has been updated to:
https://developer.stackblitz.com/docs/platform/importing-projects/#import-from-github

**Comment by purplem1lk** [comment]
> Url with the documentation has been updated to:
> [developer.stackblitz.com/docs/platform/importing-projects/#import-from-github](https://developer.stackblitz.com/docs/platform/importing-projects/#import-from-github)

This issue has been resolved and will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
