### ISSUE TITLE
Add project type support for React

### ISSUE THREAD

**Issue by awentzel** [stackblitz/core#549]
I tried to follow the documentation listed [here](https://stackblitz.com/docs#overview) to import our organization's mono repository (Lerna).  

```
stackblitz.com/github/{GH_USERNAME}/{REPO_NAME}
```

and I was shown this dialog.

![screen shot 2018-06-12 at 2 25 03 pm](https://user-images.githubusercontent.com/16669785/41318239-78df8be0-6e4c-11e8-8908-46db5a5c1059.png)

I would like to host direct integration with my GitHub repository so all of our examples are in the same collection from Microsoft or our FAST-DNA repository.

**Comment by ryanpcmcquen** [comment]
@tiliev, here is an example:
https://stackblitz.com/github/SurLaTable/slt-ui/tree/develop

**Comment by tiliev** [comment]
@ryanpcmcquen, as stated in the [documentation](https://stackblitz.com/docs#import-from-github) regarding importing from GitHub:
> We currently support projects using `@angular/cli` and `create-react-app`. Support for Ionic, Vue, and custom webpack configs is coming soon!

**Comment by ryanpcmcquen** [comment]
@tiliev, this should work then:
https://stackblitz.com/github/facebook/create-react-app

But it doesn't.
![stackblitz_react](https://user-images.githubusercontent.com/772937/45625113-fa9bfc00-ba40-11e8-9c90-aa760be8f4a6.png)

**Comment by ryanpcmcquen** [comment]
@tiliev, any update here?

**Comment by tiliev** [comment]
@ryanpcmcquen, you should create a React app using the `create-react-app` [npm package](https://www.npmjs.com/package/create-react-app). What you posted is the `create-react-app` package repository. Please follow the steps for creating an application in the description of the [repo](https://github.com/facebook/create-react-app#quick-overview). The created app would be importable in Stackblitz.

**Comment by purplem1lk** [comment]
> @ryanpcmcquen, you should create a React app using the `create-react-app` [npm package](https://www.npmjs.com/package/create-react-app). What you posted is the `create-react-app` package repository. Please follow the steps for creating an application in the description of the [repo](https://github.com/facebook/create-react-app#quick-overview). The created app would be importable in Stackblitz.

This issue has been resolved and will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
