### ISSUE TITLE
Import error, can't find file: src/app//app-routing.module.ts

### ISSUE THREAD

**Issue by geronimoooooooo** [stackblitz/core#550]
Hi,
I tried to copy&paste the project and also tried to import from github, but I get always the same error: 
**Import error, can't find file: src/app//app-routing.module.ts**

https://gyazo.com/e05f41dba28b9dee08d8a32a79151b99

This is the project I tried to import: https://stackblitz.com/github/geronimoooooooo/wwwquiz2

How to solve the problem?

**Comment by tiliev** [comment]
@geronimoooooooo,
You haven't referenced `app-routing.module.ts` in `app.module.ts`  correctly.
Currently it is like that:
`import { AppRoutingModule } from './/app-routing.module';` 
It should be:
`import { AppRoutingModule } from './app-routing.module';` 
Let us know if this helps.

**Comment by purplem1lk** [comment]
> @geronimoooooooo,
> You haven't referenced `app-routing.module.ts` in `app.module.ts` correctly.
> Currently it is like that:
> `import { AppRoutingModule } from './/app-routing.module';`
> It should be:
> `import { AppRoutingModule } from './app-routing.module';`
> Let us know if this helps.

Thank you for your patience - This issue has been resolved and will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
