### ISSUE TITLE
Update for on-premise deployment

### ISSUE THREAD

**Issue by bcardi** [stackblitz/core#551]
Issue #202 regarding on-premise has been closed. Wondering if there's been an update for on-premise deployment. I would love to provide StackBlitz to my team, but it would have to be on-premise.

**Comment by areknow** [comment]
any news on this?

**Comment by turenc** [comment]
any news on this? :)

**Comment by CoryGH** [comment]
Also interested in this.

**Comment by 5jubsPRO** [comment]
I guess you refer to this: 
https://developer.stackblitz.com/enterprise/overview

**Comment by kc0tlh** [comment]
@bcardi, @areknow, @turenc, @CoryGH, and @5jubsPRO: we have a [mature enterprise offering](https://stackblitz.com/enterprise) that can be deployed behind the corporate firewall on-prem or in a VPC. It integrates with your existing SSO solution for auth, your private npm registry, and your enterprise git provider for version control.

You can reach out to enterprise@stackblitz.com to get a 1:1 call scheduled to chat with myself or one of my teammates about your specific use case and see if StackBlitz Enterprise Server might be a good fit for your organization!
