### ISSUE TITLE
Problem with TS.

### ISSUE THREAD

**Issue by RoyiNamir** [stackblitz/core#553]
Exact same code in stackblitz : 

https://stackblitz.com/edit/angular-r8xrl8?file=src%2Fapp%2Fstate.ts

And 

[Look at this playground of typescript](http://www.typescriptlang.org/play/#src=function%20Subject%3CT%3E(t%3A%20T)%3AT%20%7B%0D%0A%20%20%20%20return%20t%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20IState%20%7B%20%0D%0A%20%20%20%20key1%3A%20number%3B%0D%0A%20%20%20%20key2%3A%20string%3B%0D%0A%7D%0D%0A%0D%0A%0D%0Alet%20Store%20%20%3A%20IState%3D%20%20Subject%3CIState%3E(%7B%20%20%0D%0A%20%20%20%20key1%3A%20void%200%2C%0D%0A%20%20%20%20key2%3A%20void%200%2C%0D%0A%20%20%0D%0A%7D)%0D%0A%0D%0A%0D%0A%0D%0A%0D%0A%0D%0Afunction%20select%3CK%20extends%20keyof%20IState%3E(k%3A%20K)%3A%20IState%5BK%5D%20%7B%20%0D%0A%20%20%20%20return%20Store%5Bk%5D%3B%0D%0A%7D%0D%0A%20%0D%0Afunction%20set%3CK%20extends%20keyof%20IState%3E(name%3A%20K%2C%20statePart%3A%20IState%5BK%5D)%20%7B%0D%0A%20%20%20%20Store%3D%7B%0D%0A%20%20%20%20%20%20%20%20...Store%2C%0D%0A%20%20%20%20%20%20%20%20%5Bname%5D%3A%20statePart%20%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%20)

With TS , there is no error , but in the stackblitz  , there is : 

![image](https://user-images.githubusercontent.com/2842123/41357071-ffa60d20-6f2d-11e8-8980-3b05ae1f820b.png)

**Comment by RoyiNamir** [comment]
@tiliev Where do you see that i've asked a question ? I've reported a bug.
In plain typescript playground - there is no error.
Have you read it ?

**Comment by seveves** [comment]
The Typescript configuration of an angular-cli project does not allow everything possible in Typescript.
You can fix your issue like that maybe: https://stackblitz.com/edit/angular-l4hdp4?file=src/app/state.ts

**Comment by RoyiNamir** [comment]
@seveves  mmmm I disagree. 
ng-run.com  -  does that.
https://ng-run.com/edit/awMk87oM2fqkyyg9k340

it also uses   Typescript configuration of an angular-cli project (imho)

**Comment by seveves** [comment]
Maybe ng-run.com is using a newer version of Typescript or another Typescript configuration.
So let's label this a potential bug and we'll see what @EricSimons or @apai4 can do about it.

**Comment by RoyiNamir** [comment]
@seveves  Anyway - it is certainly not  a question. 
(edit : I see you 've removed it)
