### ISSUE TITLE
Auto refresh when writing for loops crashes page

### ISSUE THREAD

**Issue by LuLaValva** [stackblitz/core#554]
Using typescript, I was halfway through writing a for loop when the page auto-refreshed and it got stuck in an unresponsive infinite loop. It was a simple unfinished for loop:
`for(var i=0;i<10;){
  //some code
}`
Ideally, there would be some form of infinite loop protection to fix this issue.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
