### ISSUE TITLE
"pouchdb" package cannot be installed as a dependency

### ISSUE THREAD

**Issue by trendinglaw** [stackblitz/core#555]
I’m trying to work with Ionic and PouchDB, but when adding PouchDB I get “Unable to resolve package buffer-allow-unsafe@^1.1.0”.

FWIW, codesandbox.io can load pouchdb.

**Comment by JoshuaHD** [comment]
You can try to use pouchdb-browser

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
