### ISSUE TITLE
file lost

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#556]
I wrote 3 hours file at June 16 morning, I put new routes, new components, everything works fine, but when
I shut down for lunch, then come back everything did this morning are gone, why u system like this.

**Comment by EricSimons** [comment]
Can you link the project in question here? We autosave your work frequently, so maybe it’s possoble you accidentally deleted something?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
