### ISSUE TITLE
file lost again

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#557]
files I wrote around noon lost in part of them, please check your system

**Comment by EricSimons** [comment]
As I said in https://github.com/stackblitz/core/issues/556, please provide the project URL this happened on. Also, have you disabled any adblockers/etc that you’re running? These can sometimes cause issues with persistence.

**Comment by polo789** [comment]
project name: applicant1.stackblitz.co,the data/ files lost three times from Saturday, everytime, I finish it, then go to a break, shut down the browser, come back the project like last week work, nothing keep for today's work
    On ‎Saturday‎, ‎June‎ ‎16‎, ‎2018‎ ‎08‎:‎04‎:‎07‎ ‎PM‎ ‎MDT, Eric Simons <notifications@github.com> wrote:  
 
 
As I said in #556, please provide the project URL this happened on. Also, have you disabled any adblockers/etc that you’re running? These can sometimes cause issues with persistence.
