### ISSUE TITLE
 missing a package.json file.

### ISSUE THREAD

**Issue by Flyinbird** [stackblitz/core#558]
When i open the stackblitz.com page,i was told this error.

**Comment by tiliev** [comment]
@Flyinbird,
Did you try to open a project or you just opened https://stackblitz.com/? If you have an issue with a project, please share a link to it so we can further investigate. If you try to import a GitHub repo, please share a link to that repo.

**Comment by Flyinbird** [comment]
This problem occurred when i tried to open a project found on the GitHub on the stackblitz.com web page ,but i can get on the https://stackblitz.com successfully.For example,i find a project on GitHub and the link is https://github.com/fivethirtyeight/data,then i change the link to https://stackblitz.com/github/fivethirtyeight/data,but i will be told this orror.Thank you a lot for paying attention to my question.

**Comment by Flyinbird** [comment]
I might have known what the problem is.The stackblitz.com is only available for specific languages.

**Comment by patilsign** [comment]
https://stackblitz.com/github/patilsign/musicapp/tree/master/12-12skk


it is not working..i am getiing This usually means that a dependency in your package.json is incorrect...but when i try in local it is working fine

**Comment by purplem1lk** [comment]
> @Flyinbird, you do not have a package.json in this repo - [fivethirtyeight/data](https://github.com/fivethirtyeight/data). As stated here - [stackblitz.com/docs#open-and-embed-github-repos](https://stackblitz.com/docs#open-and-embed-github-repos), you should have a single Angular or React application in your repo and you'll be able to embed it successfully.

Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. Please consider the resolution provided above. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
