### ISSUE TITLE
Add support for Flow

### ISSUE THREAD

**Issue by bcherny** [stackblitz/core#562]
Hey there! I'm trying to use StackBlitz with Flow, and it doesn't seem to work. It would be really nice to have support for it!

I get an error: `'types' can only be used in a .ts file.`

Repro: https://stackblitz.com/edit/js-dedc8j

<img width="255" alt="screen shot 2018-06-19 at 6 25 12 pm" src="https://user-images.githubusercontent.com/1761758/41607265-4e2853b2-73ee-11e8-825d-1b47e06b3ff3.png">

This is the same issue as  https://github.com/stackblitz/core/issues/301

**Comment by seveves** [comment]
If this is the same issue as #301 then maybe we should close this one and track the progress over there. I will label it as a 'feature request'
