### ISSUE TITLE
Custom components selector names should contain hypen

### ISSUE THREAD

**Issue by arikanorh** [stackblitz/core#563]
According to angular style guides and custom component specs, selector name should contain hypen. 

When we create a new angular project, the hello.component's selector is _hero_

`@Component({
  selector: 'hello',
`

**Comment by purplem1lk** [comment]
without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
