### ISSUE TITLE
support simple JavaScript projects import from GitHub

### ISSUE THREAD

**Issue by vlukashov** [stackblitz/core#564]
I'd like to use the [Import from GitHub](https://stackblitz.com/docs#import-from-github) feature of StackBlitz. It's awesome for Angular-based repos, but I want to use it for simple JS projects.

I've created a [simple JavaScript project](https://stackblitz.com/edit/vaadin-router-starter) via the StackBlitz Web UI. It works fine, so now I want to host its source code on GitHub and use the 'import' feature to keep the StackBlitz project always up to date. However, after I've exported the project code from StackBlitz and uploaded it to GitHub, it does not any longer work:

https://stackblitz.com/github/vlukashov/stackblitz-demos/tree/master/vaadin-router-starter gives me "This project type is not yet supported" error:
![image](https://user-images.githubusercontent.com/22416150/41653137-cc3fb296-748d-11e8-868c-1a456f776bbc.png)

**Comment by seveves** [comment]
So you are trying to import a plain Javascript project, right?
At the moment stackblitz only supports projects generated by `angular-cli` or `create-react-app`.
So even if the project was initially created with stackblitz it's no guarantee that you can import it after uploading to github. I know this would be a very cool thing but right now it is not yet supported.
Stackblitz is hiring, so maybe you can apply and implement this feature for @EricSimons 😄

**Comment by vlukashov** [comment]
Hi! I did read in the docs that at the moment StackBlitz only supports projects scaffolded with `angular-cli` or `create-react-app`. This issue is more of a feature request - it would be awesome if StackBlitz was also able to support simple JS projects. That would open up lots of interesting use cases and make StackBlitz useful for a wider audience.

I'm glad to see that external contributions are welcome. Is there a contributors guide / getting started / roadmap? It would help a lot to know what kind of contributions are expected.

**Comment by seveves** [comment]
Ah ok @vlukashov ... then I misunderstood you. So it's more of a framework request/enhancement and I think this ticket is related to #340 and it looks like that they are working on it. At least it is labeled as 'on deck'.

**Comment by vlukashov** [comment]
#⁠340 looks like the same feature request to me. I will close this ticket and follow that one instead. Thanks!
