### ISSUE TITLE
ng generate component

### ISSUE THREAD

**Issue by foxjazz** [stackblitz/core#565]
tried ng generate component in terminal. Error was result.

**Comment by seveves** [comment]
Hey @foxjazz ... in what console did you try to run the `ng generate component` command? As far as I know you can't run `angular-cli` commands in stackblitz. But you coudl right-click in the file explorer (for example right-click on the `src` folder) and then there you can click on `component`. It's quite the same as typing the command.

**Comment by foxjazz** [comment]
I see. I had just used the console on the right. Thanks for the help. closing.

**Comment by senseijames** [comment]
AMAZEBALLS!!!

**Comment by senseijames** [comment]
> right-click in the file explorer (for example right-click on the `src` folder) and then click on `component`. It's quite the same as typing the command.

AMAZEBALLS!!!

**Comment by krishi-vb** [comment]
> Hey @foxjazz ... in what console did you try to run the `ng generate component` command? As far as I know you can't run `angular-cli` commands in stackblitz. But you coudl right-click in the file explorer (for example right-click on the `src` folder) and then there you can click on `component`. It's quite the same as typing the command.

I am unable to do this now. By right-clicking I see only 

- new file
- new folder
- rename
- delete

Is there a different way to do this now?
