### ISSUE TITLE
Error in src/app/components/dashboard/weather-report/weather-report.component.ts 

### ISSUE THREAD

**Issue by gelliravi** [stackblitz/core#566]
App (dashboard-app-angular5) described at https://stackblitz.com/@madhavmahesh1969 displays the following error:

Error in src/app/components/dashboard/weather-report/weather-report.component.ts (7:0)
Exporting is not a function
Evaluating src/app/components/dashboard/weather-report/weather-report.component.ts
Evaluating src/app/routes/app.routes.ts
Evaluating src/app/app.module.ts
Evaluating src/main.ts
Booting application

URL: https://stackblitz.com/edit/dashboard-app-angular5

looking forward to resolve the following error.

Error snapshot:
![image](https://user-images.githubusercontent.com/320806/41699150-007897da-74e8-11e8-96c9-feaac3663b36.png)

**Comment by seveves** [comment]
It seems like this is a problem with the highcharts library but when using the following code to import `highcharts` in `weather-report.component.ts` it works fine for me:
```typescript
import { Component, OnInit } from '@angular/core';
import Highcharts from 'highcharts';
import { routerTransitionToLeft } from '../../../animations/router.animations';
// Load the exporting module.
import Exporting from 'highcharts/modules/exporting';
// Initialize exporting module.
Exporting(Highcharts); 
...
```

**Comment by purplem1lk** [comment]
> It seems like this is a problem with the highcharts library but when using the following code to import `highcharts` in `weather-report.component.ts` it works fine for me:
> 
> ```ts
> import { Component, OnInit } from '@angular/core';
> import Highcharts from 'highcharts';
> import { routerTransitionToLeft } from '../../../animations/router.animations';
> // Load the exporting module.
> import Exporting from 'highcharts/modules/exporting';
> // Initialize exporting module.
> Exporting(Highcharts); 
> ...
> ```

This issue has been resolved and will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
