### ISSUE TITLE
Something went wrong with this repository.

### ISSUE THREAD

**Issue by kasparov112000** [stackblitz/core#567]
May anybody please give a more descriptive issue on why I can't run my repo in stackbllitz, I get the following eror: 

Something went wrong with this repository.

here is my repo:

https://stackblitz.com/github/kasparov112000/newbio2

**Comment by seveves** [comment]
I can't see an error on your site. The repo looks fine as far as I can see. Maybe you shouldn't mix several  versions of @angular/* packages. Also checking in the `dist` folder is not always a good idea.
But IMHO if your repository can be built locally with the `angular-cli` then it should also work in stackblitz.

**Comment by kasparov112000** [comment]
thanks, ran ng serve --aot=false and my app is crashing...it runs with aot=true....that must be the problem

**Comment by seveves** [comment]
Sorry clicked the wrong button ... can you fix this and try the import again?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
