### ISSUE TITLE
Importing UMD modules

### ISSUE THREAD

**Issue by wszymanski** [stackblitz/core#569]
Hello,

I have problems with loading our internal [UMD module](https://github.com/handsontable/handsontable/tree/master/languages) created by webpack. It doesn't work when using a simple example in [your IDE](https://stackblitz.com/edit/js-cvddnh?file=index.js). However, everything is working good when I run a very similar example in [CodeSandbox](https://codesandbox.io/s/jzjjkvokkw). Moreover, when [equally simple example](https://stackblitz.com/edit/angular-t9tgwt?file=src%2Fapp%2Fapp.component.ts) was created for Angular using your IDE, after downloading it runs **locally** without problems.

I import a UMD module by `import 'handsontable/languages/pl-PL'` statement. As the effect, we can see a not loaded language pack in our application. Could you suggest what's going on? Maybe I'm doing something wrong?

To reproduce use case:

1. Please right-click on the cell.
2. The menu should be translated (as you can see on the CodeSandbox and on the below image)

![screen shot 2018-06-26 at 10 16 54](https://user-images.githubusercontent.com/141330/41898356-1d0bda9c-792a-11e8-990c-6cb43bcb06ed.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
