### ISSUE TITLE
Error when coping files to directory with drag and drop..

### ISSUE THREAD

**Issue by aaronksaunders** [stackblitz/core#57]
https://stackblitz.com/edit/angular-v124bf

This project is in a weird state where I cannot access it any longer. I don't need it but thought it would be a valuable reference for your team so I did not delete it

![screen shot 2017-08-08 at 2 14 54 pm](https://user-images.githubusercontent.com/524953/29087651-996ac226-7c44-11e7-878a-8426fd4c2e8c.png)

**Comment by EricSimons** [comment]
Thanks for keeping it so we can debug :) What did you drag & drop into it specifically? Any big files/folders?

**Comment by aaronksaunders** [comment]
it was a folder of files -  i was using the angular-cli generators and then
dragging over the folders for the components it created  





On Tue, Aug 8, 2017 2:44 PM, Eric Simons notifications@github.com  wrote:
Thanks for keeping it so we can debug :) What did you drag & drop into it
specifically? Any big files/folders?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.




--

Aaron K. SaundersCEO Clearly Innovative Inc - Luma Lab - In3
aaron@clearlyinnovative.com
www.clearlyinnovative.comwww.In3DC.com



This email message and any attachment(s) are for the sole use of the intended
recipient(s) and may contain proprietary and/or confidential information which
may be privileged or otherwise protected from disclosure. Any unauthorized
review, use, disclosure or distribution is prohibited. If you are not the
intended recipient(s), please contact the sender by reply email and destroy the
original message and any copies of the message as well as any attachment(s) to
the original message.
