### ISSUE TITLE
interval for rxjs

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#570]
which library should use or add to dependency for use it.
I use it from 'rxjs/add/observable/interval', but it not work

**Comment by seveves** [comment]
That's more of a rxjs question. In the latest rxjs version you are fine importing the `interval` method like `import { Observable, interval } from 'rxjs';`. Then you can call it like `interval(1000).pipe(...)`

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
