### ISSUE TITLE
saving not working: 500 error code

### ISSUE THREAD

**Issue by husseinelhussein** [stackblitz/core#571]
**Hello
thanks for this amazing tool, i would like to start using it but when i upload files and hit save this is what i get:**

PATCH https://stackblitz.com/api/projects/ionic-jjbgwr 500 ()

**when i try to see the error from the preview in the network tab, it's just html page:**

![error-1](https://user-images.githubusercontent.com/26087677/41887013-96a4729c-7907-11e8-82c7-67f3b463e00a.PNG)

**and these are the request headers:**

:authority: stackblitz.com

:method: PATCH

:path: /api/projects/ionic-jjbgwr

:scheme: https

accept: */*

accept-encoding: gzip, deflate, br

accept-language: en-US,en;q=0.9,ar;q=0.8

cache-control: no-cache

content-length: 762672

content-type: application/json

**Maybe the content is too large but it's all html files, typescript files, fonts and few icons, all of them are 615 KB**

**Comment by husseinelhussein** [comment]
ok i figured if i remove the assets folder  it works, so it might not save the project when a folder has an image

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
