### ISSUE TITLE
Doesn't work with scripts with custom types

### ISSUE THREAD

**Issue by nebrelbug** [stackblitz/core#572]
Example: In index.html,
```
<script id="source" type="text/x-handlebars-template">
  <p>{{hi}}</p>
</script>
```

 throws error: `Unexpected token <`

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
