### ISSUE TITLE
[Post api] template type for React with typescript(tsx) 

### ISSUE THREAD

**Issue by Mydeen-SN** [stackblitz/core#573]
Currently, we are unable to create react typescript project using POST API for [project template]. Searched all possible scenarios unable to find the solution for this.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
