### ISSUE TITLE
[POST API] Support for React TypeScript in POST API Project Template

### ISSUE THREAD

**Issue by judeleander** [stackblitz/core#574]
No support for React TypeScript App in the POST API's Project Template is available as far as my Analysis. If any, point me in the right direction by providing correct Project Template.

**Comment by dflorey** [comment]
Still nothing?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
