### ISSUE TITLE
Can't install some packages with npm ( Missing built-in Node modules on stackblitz? )

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#575]
Got this error after including the package `crypto`
```
Can't find module:
crypto/index (@1.0.1)
Check your import statements & ensure you're importing the correct module names.
```
If you visit [unpkg@1.0.1](https://unpkg.com/crypto@1.0.1/) it will be missing the index.js file. 
Also I had noticed on the [npm website](https://www.npmjs.com/package/crypto) it seem to be deprecated:
```
This package has been deprecated
Author message:

This package is no longer supported. It's now a built-in Node module. 
If you've depended on crypto, you should switch to the one that's built-in.
```

**Comment by fanidamj** [comment]
I've the same issue. How should I resolve it?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
