### ISSUE TITLE
assets are pulled in from angular.json, but not served?

### ISSUE THREAD

**Issue by johnpapa** [stackblitz/core#577]
I added `src/api` to my assets for an angular app. Stackblit pulled them in, but when I try to access the files via http in angular, i get an error. It returns a status code of 200 as it brings in the `index.html`.

```
            "assets": [
              "src/api",
              "src/favicon.ico",
              "src/assets"
            ],
```

I am trying to hit it with code like this:

```
  getCharacters(storyId: number) {
    return this.http
      .get('api/characters.json')
      .map((response: Response) => response.json().data);
  }
```

How can I add a folder like this?

**Comment by aitboudad** [comment]
you should try with:
```patch
    return this.http
-      .get('api/characters.json')
+      .get('assets/api/characters.json')
      .map((response: Response) => response.json().data);
```

**Comment by johnpapa** [comment]
It is in the `assets` folder now. and I tried `.get('assets/characters.json')` ... but it is not working for me

again, it works locally.

**Comment by aitboudad** [comment]
can you provide me the stackblitz link

**Comment by johnpapa** [comment]
Yes. But first, I was able to get that working form the `assets` folder by doing 2 things:

1. push the `.json` file to the github repo in the `assets` folder 
2. clear the service worker / pwa data in the stackblitz browser session

Then when I reload it works from `assets`. 

This series did not work ...

1. `.json` file is in `/api` and it is set up right in the `angular.json` file
2. all is in github and stackblitz loads
3. it is unable to see `api` folder

Nor does this series ...

1. once in stackblitz, move the `.json` file to `assets` folder and change http call to point there. 
2. stackblitz is unable to see the file change and still returns the index.html

All of this was a pain to resolve. I'm still hoping i can use another folder besides `assets`

**Comment by EricSimons** [comment]
Hey all- sorry about my delay here, I just got back from travel 😅

@johnpapa you're totally correct, we currently have partial support for static assets from angular's config. We've been working on this w/ the angular folks and full support is expected to land later this month.

I'm really sorry about the confusion & pain points around this- we're working super hard to get it over the finish line!

**Comment by djtahl** [comment]
Any updates on the topic ? this is a real pain that will prevent more and more users from using stackblitz no ?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by janstadt** [comment]
I've seen this response with regard to another issue but i still dont have this functionality. When is this happening?

**Comment by pct-cclausen** [comment]
I seem to be running into this as well, is this not fixed?
