### ISSUE TITLE
lost file

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#578]
lost file on project name: worldcup, there is a component detail gone, and the player component list gone,
just about an hour after dinner back.

**Comment by chendachao** [comment]
Encountered the same issue here, if I open a new tab and force refresh, then everything is back, but if edit something in the previous tab and save, then I lost many files permanently

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
