### ISSUE TITLE
Different behaviours locally and remotely

### ISSUE THREAD

**Issue by tonysamperi** [stackblitz/core#580]
I created this project
https://stackblitz.com/edit/ngx-mat-lib?file=app%2Fapp.module.ts

But I can't get it to work on stackblitz, while if I export the sources 
It works perfectly on my PC.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with a working project link and screenshots of the error. Thank you! :)

**Comment by tonysamperi** [comment]
Honestly I don't remember what this was about! 😂
I even deleted the blitz...
But thanks for letting me know! :)
