### ISSUE TITLE
serving static assets and index.html via github link

### ISSUE THREAD

**Issue by johnpapa** [stackblitz/core#581]
I'd like to link to some standard static sites in repos, not using angular v6. When will this be supported? Here are the scenarios below. User clicks a link to the github repo to open stackblitz. The repos contain

1. repo with just a index.html
2. repo with angularjs
3. repo with an index.html and a few other relative assets

**Comment by kylecordes** [comment]
I have also found that is at least not obvious how to bring in anything other than an Angular CLI project from a repo. A repo with something like an index.html and a trivial JavaScript file, for example, does not work; nor a repo containing the files that come out when exporting a AngularJS project created in StackBlitz.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by birkskyum** [comment]
> We are launching new core technology into beta this month that should resolve this issue

@purplem1lk , do you have a link to some resource on the technology you referred to?

**Comment by birkskyum** [comment]
Related to
- https://github.com/stackblitz/core/issues/2952
