### ISSUE TITLE
your system has problem

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#582]
my project 'worldcup' using angular routing to table and player pages, every time it should show a single page content, but when click the page 2nd times, the player page content show on table page, click 3rd times, both show 3 times on the same page, as click increase, the times increase,

**Comment by seveves** [comment]
Please provide a link to your stackblitz project having the issue.

**Comment by seveves** [comment]
Seems to be related to #587

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
