### ISSUE TITLE
Url not working

### ISSUE THREAD

**Issue by raviraj-bhalerao** [stackblitz/core#583]
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/compare/angular/component?bust=1530685963295

**Comment by seveves** [comment]
You're URL is wrong as you can see here (github also 404s): https://github.com/johnpapa/angular-first-look-examples/tree/cli/compare/angular/component?bust=1530685963295
Try it with a valid github URL pointing to a supported project type (Angular CLI or create-react-app) and it will work. If not, feel free to open a new issue.
