### ISSUE TITLE
Posted applications have an invalid share URL prior to forking

### ISSUE THREAD

**Issue by gyoshev** [stackblitz/core#585]
After posting an application with the POST API, the interface in StackBlitz shows a Fork and Share buttons. Opening the Share menu shows invalid URLs that cannot be shared. Notice that the second link looks correct, however opening it fails to connect to a development server.

![image](https://user-images.githubusercontent.com/90405/42275491-23dec4fe-7f99-11e8-9fc6-ca9e3a59b41d.png)

Clicking on Fork before opening the share menu fixes the issue:

![image](https://user-images.githubusercontent.com/90405/42275659-ad879988-7f99-11e8-8ca5-9f716a2d26bb.png)

I think the UX can be improved if the application is automatically forked once the Share button is clicked. Not sure if this is a viable suggestion, though.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
