### ISSUE TITLE
Menus not opening

### ISSUE THREAD

**Issue by jungwook8580** [stackblitz/core#586]
Hi My Name is JUNGWOOK from south korea.
Some menus are not opened mentioning that URL is not invalid.
Can you see the URL in the 'AngularFirstLookHosted'?
Thanks.

**Comment by jungwook8580** [comment]
@Tihomir lliev, sure i will send you the link i can not accessed
yesterday...

First I go to into this page: http://angular2-first-look.azurewebsites.net/
And These are the URL that i can not accessed.

2.  AngularJS (v1) to Angular (v2+): Angular Component
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/compare/angular/component?bust=1530798239142

4. AngularJS (v1) to Angular (v2+): Angular Structural Directives
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/compare/angular/structural-directives?bust=1530798239142
6. AngularJS (v1) to Angular (v2+): Angular Two-Way Data Binding
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/compare/angular/two-way?bust=1530798239142
8. AngularJS (v1) to Angular (v2+): Angular Property Binding
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/compare/angular/property-binding?bust=1530798239142

Anyway, thanks for your coureses, i am such a fan of your courses!!! I
really appreciate it!
Thanks You!!!

2018-07-05 22:27 GMT+09:00 Tihomir Iliev <notifications@github.com>:

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
