### ISSUE TITLE
Object doesn't support property or method 'matches' in IE 11

### ISSUE THREAD

**Issue by npaunov** [stackblitz/core#587]
To reproduce:
1. Go to https://stackblitz.com/edit/toast-sample in IE 11
2. Click "SHOW TOAST" button.
3. Wait 4 sec.
4. Error: "Object doesn't support property or method 'matches'" is thrown
![toast](https://user-images.githubusercontent.com/11095014/42316578-e3242c5a-8052-11e8-8552-8f8011b65d97.png)

**NOTE:** **if at the end of polyfills.ts is added:**

if (!Element.prototype.matches) {
    Element.prototype.matches = Element.prototype.msMatchesSelector;
}

**no errors are thrown.**

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
