### ISSUE TITLE
Get an error when I import style in my CSS file

### ISSUE THREAD

**Issue by dxvladislavvolkov** [stackblitz/core#588]
When I import style in my CSS file I get the error:  "Import error, can't find file:
src/https://fonts.googleapis.com/css?family=Roboto:300,400,500"

You can see an example [here](https://stackblitz.com/edit/angular-wanf6z)

**Comment by gyoshev** [comment]
Not sure if this is helpful in your case, but you can workaround the issue by wrapping the URL in a `url()` declaration:

    @import url('https://fonts.googleapis.com/css?family=Roboto:300,400,500');

**Comment by dxvladislavvolkov** [comment]
@gyoshev Yes, it can help! However, I still have a problem when I have a dependency on a library where there is the same import approach

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
