### ISSUE TITLE
why not show properly

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#589]
project: worldcup.stackblitz.io is not show properly if log on this address.
the table show as default page, the player page show blank, then click the table page again
the table page become blank, I have to log in account on edit to see the pages work.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
