### ISSUE TITLE
Deep package dependency not resolved

### ISSUE THREAD

**Issue by gyoshev** [stackblitz/core#590]
[See demo](https://stackblitz.com/edit/angular-wrlbhv?file=app/app.component.ts).

At first run, the demo requires an installation of the `immediate` package, which is a 4th level dependency of `@progress/kendo-ooxml`:

```
 ─┬ @progress/kendo-ooxml@1.1.3
  └─┬ jszip@3.1.5
    └─┬ lie@3.1.1
      └── immediate@3.0.6
```

Is this a limitation on the depth of the dependency graph?

**Comment by tiliev** [comment]
@gyoshev, please take a look at this issue - https://github.com/stackblitz/core/issues/424. I guess it is the same.

**Comment by gyoshev** [comment]
@tiliev thanks for the reference! Seems that we are encountering similar problems :smile: We have found an alternative workaround &mdash; to include jszip in the package UMD bundle. I am still puzzled about the behavior, as `jszip` is listed as a dependency of `kendo-ooxml`.

**Comment by EricSimons** [comment]
@gyoshev sorry about the delay! This usually happens when a package is importing a dependency that it doesn't have explicitly listed in its dependencies field, even though it could be a sub-dependency from one of it's dependencies. Do you know if that's the case here? I can investigate further otherwise :D

**Comment by gyoshev** [comment]
@EricSimons Yes, this was the issue. @tiliev pointed us to the issue that the imported `jszip/dist/jszip` module used a `require` call to the `immediate` package, which is not its direct dependency. We resolved this by adding jszip (and its sub-dependencies) to our UMD bundle, so that the dependency is loaded. Thanks!
