### ISSUE TITLE
Stopped working!

### ISSUE THREAD

**Issue by kkotak** [stackblitz/core#591]
Hi,

Here's my blitz - https://kkotak.stackblitz.io. This code was working without issues, but now throws an exception for a method call that exists. How can I debug this?

Thanks,

-k

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description and screenshots of the error. Thank you! :)
