### ISSUE TITLE
Broken Example

### ISSUE THREAD

**Issue by mksolemn** [stackblitz/core#592]
Example link: https://lmmerkdjqvpa.angular.stackblitz.io

Error occurred:
Cannot read property 'match' of undefined
Instantiating app/form-field-custom-control-example.html
Loading app/form-field-custom-control-example.ts
Loading main.ts
Loading blitzapp

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
