### ISSUE TITLE
Editor URL - can't find files index.html and main.ts

### ISSUE THREAD

**Issue by sandeep20162017** [stackblitz/core#593]
Import error, can't find files:
index.html
main.ts
These files are in src folder, looks like application tries to find it in root folder.

Both files do exits.

**Comment by tiliev** [comment]
@sandeep20162017, please share a StackBlitz sample URL so we could further investigate.

**Comment by sandeep20162017** [comment]
Issue occurred due to error in my application.  You can close it. Thanks

**Comment by klimentru1986** [comment]
@StalinMazaEpn change "target" to "architect" in you angular.json
