### ISSUE TITLE
Set no text wrap?

### ISSUE THREAD

**Issue by LucaGabi** [stackblitz/core#595]

**Comment by tiliev** [comment]
@LucaGabi, can you share what your issue is in detail and provide a StackBlitz sample, if possible?

**Comment by tiliev** [comment]
@LucaGabi, am closing this issue. You can reopen it with better explanation. Thank you.

**Comment by LucaGabi** [comment]
Hi,

    How can I toggle word wrap?

**Comment by CodeSmith32** [comment]
@tiliev,
I'm having this issue too. To be completely, totally, clear for him, I'd expect to see the option to toggle / disable word wrap in the command palette here:

![Image](https://github.com/user-attachments/assets/9b7ac6f8-af5c-4bcf-8b82-832684b2fb95)

Why exactly is word wrap forcibly on? Do horizontal scrollbars not work or something?
