### ISSUE TITLE
Please can you explain on your web site how to create a project from an existing one

### ISSUE THREAD

**Issue by Zephilim** [stackblitz/core#598]
This is a great project. However, it is too confusing to use when you're just starting out. There simply isn't enough information to get started properly. I need to be able to upload sample code into a project so I share it with somebody else so I can get help with it. My code is not open source so its not on github. The things I have problems with
1) When you create a project, it creates a starter project for you. What about if I have an existing project? Do I have to create a project, manually delete everything and then drag and drop my existing files and folders. This seems a bit clumsy. I want to be able to create a blank project then simply dump by existing code in.
2) How do I add my existing dependencies? Shouldn't I be able to upload my package.json and be done with it? I can see a dependency list on SB and an edit box to add in packages. Really? Do I have to manually type in all my dependencies, and there doesn't appear to be a way to specify all the version numbers for each package, unless I also need manually add the version numbers, which would be really tedious. This is why I should just be able to upload my package.json (and maybe the lock file) and then the dependencies updated to reflect this. And what about dev-dependencies? I can't see where you add those.
3) My project has jasmine test-cases, but I can't see how to run them on SB.

I'm sure I'm missing something, and it's probably a lot easier than it seems, but at the moment its a mystery because there's not enough information. I hope you can help me with this, thanks.

**Comment by kylecordes** [comment]
@Zephilim I'm just a user of StackBlitz, but I can answer a bit of this. If you happen to be using Angular and Angular CLI, in most cases a Angular CLI project stored in GitHub can be easily launched into StackBlitz, it just automatically imports everything and runs.  I don't know how broadly other kinds of projects can be brought in this way.

**Comment by Zephilim** [comment]
Thanks for your reply, but my project is not on github. I paid for a starter project and as such, and because of this, I can't put it up as though it was open source.

**Comment by kc0tlh** [comment]
@Zephilim I appreciate your patience and kind words RE StackBlitz! Let me take a stab at these questions:

1. To create a new project from scratch/via drag and drop upload I recommend the templates in the "Vanilla" section of the StackBlitz dashboard [https://stackblitz.com/?starters=vanilla](https://stackblitz.com/?starters=vanilla)

2. We now support package.json files with dev dependencies!

3.  For Jasmine unit tests, I would recommend trying the [Node starter](node.new) project to ensure you are utilizing the [WebContainers](https://blog.stackblitz.com/posts/introducing-webcontainers/) technology, but I'm not 100% sure they will run inside StackBlitz yet.

Hope that helps!
