### ISSUE TITLE
Unable to load from git

### ISSUE THREAD

**Issue by spillaip** [stackblitz/core#599]
My project at https://github.com/spillaip/login_register is not loading in stackblitz with error missing package.json. But the file exists.

**Comment by tiliev** [comment]
I'm getting other error.

![capture](https://user-images.githubusercontent.com/6439482/42677124-751b2e16-8683-11e8-844b-b467af270ae0.PNG)

It is still strange, because this project seems to be scaffolded with Angular CLI.

**Comment by kc0tlh** [comment]
@spillaip I was able to import your repo, so I'm going to mark this issue as resolved. Don't hesitate to reach out if you are still unable to import!
