### ISSUE TITLE
Set Method is not Working

### ISSUE THREAD

**Issue by DominicAmal** [stackblitz/core#602]

**Comment by tiliev** [comment]
@DominicAmal, please reopen this issue once you provide more details about your scenario.

**Comment by DominicAmal** [comment]
`const array = [1,2,3,4,5];
var set = new Set([...array]);
console.log(set);`

the above code returns empty set when I am running in stackblitz.

**Comment by seveves** [comment]
Seems to be related with #546

**Comment by bockoblur** [comment]
I have the same issue, even without the spread operator:

    let mySet = new Set([1,2,3,3]);
    console.log(mySet);
    // Expected output: Set [1,2,3] 
    // Actual output: Empty set

**Comment by rmonterodev** [comment]
//Same happened
let nums = [1,2,2,3];
let a = new Set(nums);

console.log([...a]) // returns [1, 2, 3] ...does not work

**Comment by sulco** [comment]
Thanks for taking time to report this issue and provide all the examples!

This is now fixed and should no longer be an issue :)
