### ISSUE TITLE
why @angular/common/http can't be installed

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#603]

**Comment by tiliev** [comment]
@polo789, such package does not exist. You can search for packages [here](https://www.npmjs.com/search?q=%40angular%2Fcommon%2Fhttp). Perhaps you need `@angular/common`.

**Comment by purplem1lk** [comment]
This issue is unrelated to StackBlitz and will be closed accordingly. If you have any questions, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
