### ISSUE TITLE
https://github.com/tanggrapes/ionic-conference-app can't import

### ISSUE THREAD

**Issue by tanggrapes** [stackblitz/core#607]

**Comment by tiliev** [comment]
@tanggrapes, your project is not scaffolded with `angular/cli`.

**Comment by purplem1lk** [comment]
This issue has been resolved and will be closed accordingly. If your issue persists after using the recommendation above, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
