### ISSUE TITLE
can we change the user name with logged in user name instead of hard-coding ? 

### ISSUE THREAD

**Issue by AhammadAliPK** [stackblitz/core#608]
I can see that user name is hard-coded as **Miss Marple**

 CoreModule.forRoot({userName: 'Miss Marple'}),

can we change this user name with logged-in user's name ? or is it acting like a global constant of app ?

**Comment by tiliev** [comment]
@AhammadAliPK, please provide a StackBlitz sample. Also, is this connected to StackBlitz?

**Comment by AhammadAliPK** [comment]
Yes , its related to **stackBlitz** ,

url : **https://stackblitz.com/angular/yobxrdeqqom?file=src/app/app.component.ts**
