### ISSUE TITLE
Can't click cursor on the left side of the code window

### ISSUE THREAD

**Issue by nebrelbug** [stackblitz/core#609]
Clicking your mouse on the left side of the code window, right by the line-numbers but on top of the text, doesn't move the cursor. Maybe a z-index problem?

Thanks!

**Comment by nebrelbug** [comment]
Oops, just saw the "console" bar :)

**Comment by tiliev** [comment]
@nebrelbug, I cannot fully understand the scenario. Where do you click - on the numbers or on the code itself?

**Comment by nebrelbug** [comment]
When I click on the code, but on the letters right next to the line numbers. For example, I can't click to the beginning of a line of code. Also, highlighting is kind of weird... sometimes when I highlight I can't unhighlight by clicking immediately, I have to try a couple of times.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
