### ISSUE TITLE
Enable sourcemaps for user code

### ISSUE THREAD

**Issue by greggpatton** [stackblitz/core#61]
Is there a way to turn on inline-source-map for debugging ES6?

Thanks!

**Comment by EricSimons** [comment]
@greggpatton great idea — we actually had it turned on a while back, but Chrome's sourcemapping functionality won't update w/ the latest sourcemap on hot reloads (so you'd actually be seeing old versions of your files when you went into the debugger, etc).

I'm going to dig into this more and see if there's something we can do to force chrome to show the latest sourcemaps at all times. Would appreciate any pointers if folks know how one would go about doing this!

**Comment by AbakumovAlexandr** [comment]
Is there any updates on this? Source maps doesn't wprk for me at all - I can see only transpiled JS in Chrome DevTools.

**Comment by aeslinger0** [comment]
In the sources tab in DevTools, you can right-click and select "Add Source Map" and then specify a url, which may be enough, but where do we find the source maps?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
