### ISSUE TITLE
Angular First Look - John Papa - 2. A1 - A2 Angular 2 Component link not working

### ISSUE THREAD

**Issue by Owenet** [stackblitz/core#611]
Hi,

The second sample view button on the following page is not operational…

https://app.pluralsight.com/player?course=angular-2-first-look&author=john-papa&name=angular-2-first-look-m1&clip=2&mode=live

2nd View Sample button link source:
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/compare/angular/component?bust=1532098387574

As I am running through this course please could you investigate and fix.

Kind regards,

Jonathan

**Comment by tiliev** [comment]
@Owenet,
The link is wrong, it should be https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/projects/compare/angular/component.

I do not have an access to the course, but I guess @johnpapa left an email or other form of giving a feedback. You can use it and tell him he should update this link.

Regards,
Tisho.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
