### ISSUE TITLE
why not @angular/platform-browser/animations

### ISSUE THREAD

**Issue by polo789** [stackblitz/core#614]
why import {BrowserAnimationModule} from @angular/platform-browser/animations;
not works good as before, how can we do animate trigger in angular

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
