### ISSUE TITLE
Delete alert should contain the name of the project

### ISSUE THREAD

**Issue by jainanuj0812** [stackblitz/core#615]
While deleting any project from the profile results to a alert box asking for the sureity to delete the project with text “Delete Project”. It would be nice if that alert also contain the name of the project that user surely want to delete. That will help user that they have clicked on the right project that they want to delete.

Eg “Delete XYZ Project?

**Comment by kc0tlh** [comment]
@jainanuj0812 thanks for this excellent product feedback! It has been implemented:

<img width="355" alt="image" src="https://github.com/stackblitz/core/assets/1532264/9c1961a6-b512-4fdb-a8d8-5b1269d3b7d2">
