### ISSUE TITLE
Fetching Images or Json data from local folder assets/data/xxx.json

### ISSUE THREAD

**Issue by SuganNaickerf** [stackblitz/core#617]
Hi,

Firstly enjoying working with Stackblitz :-) thanks.

Noticed an issue with fetching files from local folder.

I created a folder assets and copied a jpg and copied an image plus created a folder assets/data/xx.json and emulator could not pick up either local jpg or xx.json file.

I created the same project manually (without stackblitz)  and project worked using for example : 

 this.http.get('../assets/data/xx.json').subscribe(data =>

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
