### ISSUE TITLE
Embedded apps never work

### ISSUE THREAD

**Issue by rmorrise** [stackblitz/core#619]
Whenever I see a Stackblitz example embedded in a blog or article, the embedded app never works.

The preview embedded in the article is always blank.

When I edit and open in a new window, the window hangs indefinitely with a loading indicator. In the console I eventually see this message:
`Service Worker termination by a timeout timer was canceled because DevTools is attached.`

An example I was just reading: [https://stackblitz.com/edit/adv-ng-patterns-06-use-template-refs?file=app%2Fapp.component.html](https://stackblitz.com/edit/adv-ng-patterns-06-use-template-refs?file=app%2Fapp.component.html)

I am on win64, Chrome Version 67.0.3396.79 (Official Build) (64-bit)

**Comment by apai4** [comment]
@rmorrise do you happen to have 3rd party cookies blocked? If so, see here for a potential solution: https://github.com/stackblitz/core/issues/162#issuecomment-357656965

While we don't use 3rd party cookies for our preview domains on StackBlitz, some of the API's we use for passing data between windows/frames can fall under the same policy, which can cause the previews not to load.

**Comment by rmorrise** [comment]
Duplicate of #162
