### ISSUE TITLE
min-document? I don't depends on it.

### ISSUE THREAD

**Issue by sorrycc** [stackblitz/core#62]
![image](https://user-images.githubusercontent.com/35128/29150378-c46f5fa4-7dac-11e7-9f60-4e6bd87e5fa2.png)

https://stackblitz.com/edit/react-kune7n?file=index.js

**Comment by EricSimons** [comment]
Investigating now — this typically means that one of your dependencies is trying to require it, but they don't have it listed as a dep

**Comment by EricSimons** [comment]
@sorrycc found the issue; the subdependency `global` is requiring it: https://unpkg.com/global@4.3.2/document.js

However, the package.json specified it as false for the browser field: https://unpkg.com/global@4.3.2/package.json

Will put in a fix tmrw for this — if you just click "install" it works fine though!

**Comment by EricSimons** [comment]
The fix for this is now live on prod 👍
