### ISSUE TITLE
ngx-datatable scrolling with an variable limit isn´t working

### ISSUE THREAD

**Issue by 42alex42** [stackblitz/core#620]
https://stackblitz.com/edit/ngx-datatable-scroll-with-limit

if start in stackblitz you see 5 rows with header and footer. I want to change the select-box above with the visible rows. if you select 15 it changes not directly the table. But if you resize the browser, then you get the right 15 rows with header and footer. WHY is this only after resize the browser?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
