### ISSUE TITLE
Web App Manifest (for even more PWA-ness)

### ISSUE THREAD

**Issue by ChristianWeyer** [stackblitz/core#621]
Are there already any plans to add ann app.manifest for Stackblitz?
I could try to submit a PR if this is something people want (and I surely want to add SB onto my desktop ;-) )

**Comment by nagarjundeepak** [comment]
yes, stackblitz still not supporting custom manifest.json file. h

**Comment by kc0tlh** [comment]
This has been implemented: 

<img width="338" alt="image" src="https://github.com/stackblitz/core/assets/1532264/572f28b6-54e7-4a56-84b7-26f6936fc808">
