### ISSUE TITLE
How to get ajax content in Stackblitz samples?

### ISSUE THREAD

**Issue by ajithr** [stackblitz/core#622]
I have tried to get a file content using Ajax request. But it doesn't get any content from the local file. How to get this done? 

https://stackblitz.com/edit/js-rsv4w3

**Comment by judeleander** [comment]
I'm also facing the same issue, I can't get content using Ajax request from local file as well as online link. Is there any other way to achieve the same.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
