### ISSUE TITLE
Crash with "angularfire2": "5.0.0-rc.11"

### ISSUE THREAD

**Issue by kylecordes** [stackblitz/core#623]
This is a bug report.

## Context

The current version of the package "angularfire2" is "5.0.0-rc.11".

If I create a new StackBlitz, and add angularfire2 using the UI, instead I get "5.0.0-rc.10".  This is interesting, because it means there is some code in there which understands it is currently compatible only with rc.10.  And yet...

## Current behavior

If I attempt to import a StackBlitz from GitHub which contains the dependency "angularfire2": "5.0.0-rc.11", StackBlitz crashes with an error about a problem with dependencies; but it gives no hint about the error or which dependency.

To reproduce this, just use any Angular CLI project that otherwise works with StackBlitz, add the dependency noted, and attempt to import.

## Expected behavior

* StackBlitz won't crash with any valid dependency that works with other NPM resolution, including this one.
* If there is an internal problem preventing StackBlitz from loading a dependency, the failure message should indicate **which** dependency - because even small examples that are typically worked with on StackBlitz, can contain dozens of dependencies.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with a project link and screenshots of the error. Thank you! :)
