### ISSUE TITLE
extending Array or Object class is bugy on stackblitz

### ISSUE THREAD

**Issue by stannesi** [stackblitz/core#627]
If try inheriting from a  base generic class like [Array] or {Object} a nasty error
**example:** Open a plain Javascrip file and add this script, and observer its behaviour.

```
class ArrayList extends Array {
  constructor(...items){
  super(...items);
}
add (item) {
  this.push(item);
  console.log("added an item to list. - " + item );
  }
}
//------------//
let obj = new ArrayList("1", "2", "3");
console.log(obj)
obj.add(4);
```
Result on a normal chrome console: [as it should be]
![screen shot 2018-07-31 at 12 09 18 pm](https://user-images.githubusercontent.com/718824/43475834-922c29b4-94bc-11e8-9b81-83c09bc6fc21.png)

and a result from statckbliz.io console:
![screen shot 2018-07-31 at 12 25 00 pm](https://user-images.githubusercontent.com/718824/43475915-c8620a94-94bc-11e8-8e78-36be2f98bb14.png)
![screen shot 2018-07-31 at 12 18 52 pm](https://user-images.githubusercontent.com/718824/43475858-a7c54fda-94bc-11e8-9f5c-68a36fe50497.png)
It appears not to recognize ny of its public functions, they equal `undefined`

hey are all undefined. 

**Weird possible Solutions, thats fixes it**
It works on 2 conditions
1. By removing its "**super()**" keyword; _[in other words by not calling its parent constructor]_. or
2. By making all it's the public functions an arrow function , like this
```
add = (item) => {
}
```
which is super weird
...I'm no expert, but using such techniques, make me wonder, 
_"...is  this even javascipt anymore"_

You experiment by adding another funtion using short arrow technique and see the result for yourself, like the one below, and one can call both `add()` and `remove()`. 
```
  remove = (item)=> {
    this.push(item);
    console.log("removed an item from list. - " + item );
  }
```
**Result:** On stackbliz - `add()` is undefiend while `remove()` works pretty well, but it's the exact opposite for chome console its give an arror like this
![screen shot 2018-07-31 at 12 37 07 pm](https://user-images.githubusercontent.com/718824/43476554-786d3ac0-94be-11e8-88bb-082d2ad4cc8a.png)

I hope this a resonable ticket that it helps improve stackblitz, because I think stackbliz is an amazing platform, I enjoy using it and will still continue to use it.

Thank you! 

_**Note:** I only tried it with Array, Object and Number -  Number seem to work pretty accurate._

**Comment by sulco** [comment]
Thanks for reporting the issue! I agree it was confusing. 
Thankfully with our latest updates, we should no longer have such issues, so I'm closing it (but feel free to reopen if you do stumble upon it again)

(here's the working repro based on your code: https://stackblitz.com/edit/js-jyyoyl-repro?file=index.js)
