### ISSUE TITLE
please solve these bugs

### ISSUE THREAD

**Issue by ravindragupta942** [stackblitz/core#629]
The repository is missing a package.json file.
![screenshot from 2018-08-01 14-52-57](https://user-images.githubusercontent.com/29068464/43513137-9a7a8bd6-959a-11e8-9ba3-43d91e0dc3ac.png)

**Comment by tiliev** [comment]
@ravindragupta942, currently supported Angular projects should use `@angluar/cli`. Your repo consists of two separate Angular applications. To run any of them, here how they should be imported:
- https://stackblitz.com/github/DeborahK/Angular-GettingStarted/tree/master/APM-Final
- https://stackblitz.com/github/DeborahK/Angular-GettingStarted/tree/master/APM-Start

**Comment by sulco** [comment]
The solution seems to work - closing
