### ISSUE TITLE
Generate Scaffolding command

### ISSUE THREAD

**Issue by prantikv** [stackblitz/core#63]
Hey there,

Using Ionic and Angular there is a generates command which generates components/providers and more.
Some thing as follows:
`ionic g page myPage` or `ng generate page myPage`

These commands are usually a big help while creating apps.
Would love to see something similar a button maybe that makes creating components easy.

Regards.

**Comment by EricSimons** [comment]
Definitely! We've been talking about this over in https://github.com/stackblitz/core/issues/17 actually :)

I'm thinking that maybe we put it in the drop down menu when you right click a folder? Would love to hear your thoughts on this though.

**Comment by janpio** [comment]
Just a note: `ionic g page` is on project level, not folder level.
