### ISSUE TITLE
Broken export for blank typescript project

### ISSUE THREAD

**Issue by MarenkovIgor** [stackblitz/core#630]
Steps to reproduce:

1. Create blank typescript project: https://stackblitz.com/fork/typescript
2. Click "Export" button
Actual result: archive do not include: index.ts, styles.css, package.json
Expected: archive with index.ts, styles.css, package.json

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
