### ISSUE TITLE
The dependencies for this project couldn't be resolved.

### ISSUE THREAD

**Issue by bamossza** [stackblitz/core#631]
https://stackblitz.com/github/bamossza/angular5-login-gmail-facebook-with-angularfire2

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)

<img width="1439" alt="Screen Shot 2021-04-27 at 9 26 52 AM" src="https://user-images.githubusercontent.com/49956513/116249332-b6b21d00-a73a-11eb-8b16-2026772a52e0.png">
