### ISSUE TITLE
Ionic Page Lazy Loading it doesn't work

### ISSUE THREAD

**Issue by salazarr-js** [stackblitz/core#632]
Using basic IonicPage structure doesn't work, the console returns a `Error: Uncaught (in promise): invalid link: HomePage` error, like in this [example](https://stackblitz.com/edit/ionic-page-lazy-loading-test?file=app/main.ts).

```javascript
// home.ts
import { Component } from '@angular/core';
import { IonicPage } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {
  constructor() {  }
}
```
```javascript
// home.module.ts
import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { HomePage } from './home';

@NgModule({
  declarations: [
    HomePage,
  ],
  imports: [
    IonicPageModule.forChild(HomePage),
  ],
})
export class HomePageModule {}
```
```javascript
// app.components.ts
import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';

@Component({
  templateUrl: 'app.html'
})
export class MyApp {
  rootPage: any = 'HomePage';

  constructor(platform: Platform) {
    platform.ready().then(() => {  });
  }
}

```

**Comment by 7martinelli** [comment]
Still waiting this fix to start moving all my projects to stackblitz. 😃

**Comment by erperejildo** [comment]
I can confirm it doesn't work

**Comment by mapicard** [comment]
Any news on this? Any fix/workaround?

**Comment by kc0tlh** [comment]
IONIC projects should just work at this point 🎉

Here are some [known good IONIC v7 templates](https://twitter.com/aaronksaunders/status/1694037022426509709) for StackBlitz.

And here are the docs on importing repos into our new VS Code editor: https://developer.stackblitz.com/guides/user-guide/getting-started#opening-a-github-repository-in-codeflow-ide

_Consolidated Ionic Issue: #219_
