### ISSUE TITLE
Styles from angular.json not used in stackblitz

### ISSUE THREAD

**Issue by riyadali** [stackblitz/core#633]
I created a simple project using ng new some-angular-project --style=scss. To this project I added the angular material design toolbar (https://mdbootstrap.com/angular/).  The setup instructions for angular material design (https://mdbootstrap.com/angular/5min-quickstart/) indicates that the following styles and scripts to the angular.json file
"styles": [
    "node_modules/font-awesome/scss/font-awesome.scss",
    "node_modules/angular-bootstrap-md/scss/bootstrap/bootstrap.scss",
    "node_modules/angular-bootstrap-md/scss/mdb-free.scss",
    "src/styles.scss"
],
"scripts": [
  "node_modules/chart.js/dist/Chart.js",
  "node_modules/hammerjs/hammer.min.js"
],

It worked when deployed locally to my machine.

I then imported this project to github and tried to used stackblitz to play with it.  First off I was getting various message about font-awesome modules not found.  After some research I was able to determine that for Stackblitz to work you need to use "~" for you node_module folder reference.  So I changed all my references.  So for example, the reference to the font-awesome scss file was changed to "~font-awesome/scss/font-awesome.scss".

Now, however, the tool bar shows but it has no styling applied.  I can explicitly add a css reference for an equivalent style to my index.html file and I would get it to style properly (at least display wise) but the the drop down menu button does not expand.  However, as I mentioned previously, all of this worked quite well when deployed locally on my computer.

So my question is why is stackblitz not picking up the scss styles from the angular.json file.

Below is a link to the project https://stackblitz.com/github/riyadali/townofbabylongoodtoolbar/tree/dev
Notice the styling is all messed up.  If you change index.html and add the style references explicitly, as shown below, it styles properly, but the dropdown button does not work

```<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>TownOfBabylonProject</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <!-- Add bootstrap core library for social media icons -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" 
         integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

<!-- Add font awesome icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
   <!-- Material Design Bootstrap -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">
</head>
<body>
  <app-root></app-root>
</body>
</html>

**Comment by riyadali** [comment]
Below is the full index.html file

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>TownOfBabylonProject</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" 
         integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
   
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">
</head>
<body>
  <app-root></app-root>
</body>
</html>

**Comment by bob-lee** [comment]
I think I have a similar problem. For some reason. styles on `src/styles.css` are not being applied:

https://stackblitz.com/edit/angular-lazyloading-animation?file=src%2Fstyles.css

It was old demo that was using an `angular-cli.json` and I updated them all ok but this issue.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
