### ISSUE TITLE
Broken export for blank javascript project

### ISSUE THREAD

**Issue by ishan123456789** [stackblitz/core#634]
There is no source no file except an index with some extension and a package file 
I've created two projects there but now not able to export them.
I'll need to do everything manually.
You can try by clicking export in this project of mine https://stackblitz.com/edit/breakout

**Comment by tiliev** [comment]
@ishan123456789, your project is exported correctly on my side. What is missing in the zip when you export?

**Comment by ishan123456789** [comment]
The export only downloaded 3 files which were index.html, package.json, and a Readme.md 
[breakout.zip](https://github.com/stackblitz/core/files/2273802/breakout.zip) I tried with npm install but didn't add any file

**Comment by tiliev** [comment]
It exports all of the files on my side:

![export](https://user-images.githubusercontent.com/6439482/44089797-c579dbee-9fd0-11e8-941f-0d7e182a2c24.PNG)

`package.json` is empty because you do not have any dependencies in the project.

**Comment by ishan123456789** [comment]
Is it browser dependent then? 

I'm still getting three files only. Can you please guide me @tiliev all I'm doing is clicking export is there anything else that I need to change like settings or anything else?

**Comment by ishan123456789** [comment]
Is anything wrong in my configuration @tiliev as seen in above gif

**Comment by vegarringdal** [comment]
Ive never manged to get the export to work either, just get a index.html, package.json and readme file
using window 10 64bit
I can start my vmware and test out ubunto on the same sample

https://stackblitz.com/edit/mframejs-weird

**Comment by vegarringdal** [comment]
jepp, ubuntu works
gets all other files too

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
