### ISSUE TITLE
URL Invalid issue.

### ISSUE THREAD

**Issue by SrinivasKummari** [stackblitz/core#636]
Unable to load the page

**Comment by tiliev** [comment]
@SrinivasKummari, can you provide the URL?

**Comment by SrinivasKummari** [comment]
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/compare/angular/component?bust=1533668347613


Thank you and have a wonderful time.

Sincerely,
Srinivas Kummari,
(617)710-7621.

**Comment by tiliev** [comment]
@SrinivasKummari, the project is not scaffolded with `@angular/cli`.

**Comment by purplem1lk** [comment]
> @SrinivasKummari, the project is not scaffolded with `@angular/cli`.

This issue has been resolved and will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
