### ISSUE TITLE
stackblitz name length

### ISSUE THREAD

**Issue by shahishani06** [stackblitz/core#638]
Current Behaviour : stackblitz name length is not more than 63
Actual Behaviour : stackblitz name length is maximum

**Comment by tiliev** [comment]
@shahishani06 Can you elaborate further on your suggestion? Do you need a StackBlitz sample name bigger than the current length and why?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a project link, description, and screenshots of the error. Thank you! :)
