### ISSUE TITLE
Awesome tool. too bad you can't debug it using break points

### ISSUE THREAD

**Issue by ohadperry** [stackblitz/core#64]

**Comment by seedy** [comment]
It's actually possible.
Console log from stackblitz : Pro Tip: Run & debug your app in its own window --> "xxx"

**Comment by zman13** [comment]
I know this is closed, but I think there's something wrong with debugging. I can't see a way to see the source code when in the chrome's dev tools so cant' set a breakpoint. The app structure is present under the sitename/tmp/appfiles/src even the files are all there with .ts suffixes, only they content seems to be the transpiled js not the ts. I've looked everywhere in the tree but dont see the actual .ts
