### ISSUE TITLE
[enhancement] Import simple JS/TS projects from github

### ISSUE THREAD

**Issue by mike-north** [stackblitz/core#641]
It would be nice if support for github import went beyond `@angular/cli` projects. At the very least, I'd expect that projects originally exported by Stackblitz to be importable.

**Comment by vegarringdal** [comment]
>  github import went beyond @angular/cli project

Yes, Ive been missing normal typescript projects

**Comment by vegarringdal** [comment]
@EricSimons 

Seen a few updates on Stackblitz lately.
Any chance we might get import for simple JS/TS projects from github very soon?
😄

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
