### ISSUE TITLE
Export doesn't download all the files that were shown in the online view

### ISSUE THREAD

**Issue by chandramuralis** [stackblitz/core#645]
I tried to export the URL https://stackblitz.com/edit/error-handling-in-angular-step2 and I don't see all the files that were originally shown in the url. Also the folder structure were different.
In the attached image left side is my downloaded copy and right side is the StackBlitz browser.

![image](https://user-images.githubusercontent.com/760056/44091788-9ca61bb2-9f9c-11e8-93e9-4119e58bd287.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - I was unable to reproduce this - If your issue persists after re-downloading, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
