### ISSUE TITLE
GET request on json file returns html page

### ISSUE THREAD

**Issue by robertou** [stackblitz/core#649]
Hi, not sure if i am ot, I've tried to make a GET request on this URL: https://angular-9kubuc.stackblitz.io/project1.json (I've created the file using the online editor) but unfortunately I receive an html response instead of the expected json file.
Am I missing something?

Thanks

Roberto U.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
