### ISSUE TITLE
Lost all my updated code

### ISSUE THREAD

**Issue by SuganNaickerf** [stackblitz/core#650]
Hi,

Progressed nicely on a test app yesterday. Saved and exit. Came in this morning and the version online is an old version... please help if possible. This is the 2nd time this as happened. Therefore I have been really cautious with saving.

Rgs

Sugan

**Comment by SuganNaickerf** [comment]
Quick note : 

I had 2 projects open on separate windows. I looked at the datestamp and one shows correct (updated 7 hours ago) and the other shows 14 hours ago, which is incorrect. 

The one I lost, was the one showing 14 hrs ago. In terms of sequence I saved and closed the lost one 'first' and then saved and closed the 2nd project - which appears correct. 

Is this a possible defect when more than one project is open at a time?

**Comment by kc0tlh** [comment]
Appologies for the delayed response! Thankfully this issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Additional details in Github issue #2473
