### ISSUE TITLE
looks like lazy loading doesnot work for ionic projects

### ISSUE THREAD

**Issue by glongchi** [stackblitz/core#652]
keep getting error in console: for this case we are lazy loading a menu page
ERROR
Error: Uncaught (in promise): invalid link: menu

**Comment by 7martinelli** [comment]
that's the same issue as #632 . let's keep in the same line

**Comment by purplem1lk** [comment]
Closing this issue, as it is a duplicate of #632. If you have any questions, feel free to tag me or continue the conversation in #632. Thank you! :)
