### ISSUE TITLE
(intermediate value).slice is not a function

### ISSUE THREAD

**Issue by rjoydip** [stackblitz/core#655]
Getting below when I am executing `new Set()` to my javascript application.

```bash
(intermediate value).slice is not a function
Evaluating index.js
Booting application
```

**Comment by MAXMASTER001** [comment]
same!

**Comment by sulco** [comment]
Thanks for reporting this!

Thankfully with our latest updates, we should no longer have issues with `Set`, so I'm closing it (but feel free to reopen if you do stumble upon it again)
