### ISSUE TITLE
Console expanding to high on mobile device

### ISSUE THREAD

**Issue by az67128** [stackblitz/core#657]
When trying to open the console on a mobile device, console expanding to high, no scroll possible.
Screenshot [https://photos.app.goo.gl/Ynz166i72dmN94Ht5](url)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
