### ISSUE TITLE
Just a suggestion, thanks for this incredible environment!

### ISSUE THREAD

**Issue by pablojch3** [stackblitz/core#659]
It is possible from your part to integrate StencilJs to the interpreter, I tried in different ways to start a project but I had no luck
Thanks sou much!

**Comment by kc0tlh** [comment]
@pablojch3 this [Stencil repo](https://pr.new/github.com/ionic-team/stencil-component-starter) should get you up and running in our [new VS Code editor](https://stackblitz.com/codeflow)!
