### ISSUE TITLE
Code editor should recognise CSS3 Grid properties

### ISSUE THREAD

**Issue by MarkGaze** [stackblitz/core#66]
The code editor doesn't recognise CSS3 Grid properties (such as 'grid-template-rows') either in the intellisense or as valid syntax.

The code still works as intended when built but it would be nice to have the new CSS grid syntax in the intellisense and not have it underlined as a code issue.

**Comment by EricSimons** [comment]
That's super weird — I'll take a look into this. Not sure why CSS grid syntax isn't included in intellisense 🤔

**Comment by MarkGaze** [comment]
Looks like this is fixed in the latest version, closing the issue :)
