### ISSUE TITLE
Bulma dependency never completes install

### ISSUE THREAD

**Issue by ianbarber** [stackblitz/core#660]
If I add bulma as a dependency to an angular typescript project, I just get a spinner with INSTALLING DEPENDENCIES.

In the console I see:

formatted:"Internal Error: File to read not found or unreadable: /sass/~bulma/bulma.sass↵"
message:"File to read not found or unreadable: /sass/~bulma/bulma.sass"
status:3

Uncaught TypeError: Cannot read property 'replace' of undefined
    at engineworker-3aca3176ba1e11fb442ca.js:1
    at sass.sync.min.js:1
    at engineworker-3aca3176ba1e11fb442ca.js:1
    at d (engineworker-3aca3176ba1e11fb442ca.js:1)
    at MessagePort.[object process].toString.call.t.MessageChannel.port1.onmessage (engineworker-3aca3176ba1e11fb442ca.js:1)

Nothing seems to get the error back to the client, so the spinner just sits there.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with a project link and screenshots of the error. Thank you! :)
