### ISSUE TITLE
Error in stackbitz but works locally

### ISSUE THREAD

**Issue by RahmanM** [stackblitz/core#661]
Hi,

I am using PrimeReact component in a sample page and I get the following error:

"stackblitz Check your import statements & ensure you're importing the correct module names."

However, if I use the same thing locally it works.

Here is the sample project:

https://stackblitz.com/edit/react-nzmamt?file=index.js

thx

**Comment by tiliev** [comment]
@RahmanM, I am not able to open your sample. Do you still have this issue?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
