### ISSUE TITLE
can't save after drag&drop

### ISSUE THREAD

**Issue by comfortme** [stackblitz/core#662]
Hi
I can't save after drag&drop.  Save button becomes disabled and enabled again.
This is the error i get to the console PATCH https://stackblitz.com/api/projects/github-gmajee 500 ()
If I delete dropped file I can save again.

**Comment by sulco** [comment]
Thanks for reporting! With the series of updates to our UI and specifically file tree implementation, this should not be an issue anymore, but please feel free to reopen if you stumble upon it again.
