### ISSUE TITLE
Wrong last version of npm package

### ISSUE THREAD

**Issue by dlaraf** [stackblitz/core#667]
Hi!
Not very import but I'm trying to install the latest release of antd(3.9.2) package for use with a react example project but it seems that the required dependency rc-cascader@0.16.0(which is the last one in npm as well) is not up to date. If i try to install this dependency manually it installs the release 0.15.0, probably a cached one?

If i install the antd@3.8.2 with npm all works as expected as this one use that release of rc-cascader(0.15.0).

Best regards and thank you for this great work!

**Comment by tiliev** [comment]
@dlaraf, I can confirm installing `rc-cascader@latest` locally installs `0.16.0`, but in StackBlitz the installed version is `0.15.0`. Marking as bug.

**Comment by EmilYoYo** [comment]
I have this problem too. Your suggestion worked.

**Comment by maxime1992** [comment]
Any news on that?

Trying to install ngx-sub-form with the latest version (2.11.0) but it's only installing the previous one.
