### ISSUE TITLE
Repo 14 doesn't appear to exist

### ISSUE THREAD

**Issue by SoozeC** [stackblitz/core#670]
I'm working on the Angular 2 First Look tutorial by John Papa but item 14 on the azurewebsites.net doesn't go anywhere

**Comment by tiliev** [comment]
@SoozeC, can you share the link to this sample?

**Comment by purplem1lk** [comment]
This issue is not related to StackBlitz and will be closed accordingly. If you have any questions, feel free to tag me or ask to reopen this issue with a description and screenshots of the StackBlitz error. Thank you! :)
