### ISSUE TITLE
Having anonymously created project deleted

### ISSUE THREAD

**Issue by pesalvador** [stackblitz/core#673]
Hello, first of all thanks a lot for this great project ! It's really amazing !

We've been using stackblitz for learning purposes lately and have accidentally created a new angular  project before signing in. We cannot take the ownership any longer and whichever changes we make are obviously not being saved since it's not a fork.

The problem is that we got some private information in a mock repository class that we'd not like to see on the wild.

Is there a way to either delete this project or simply the mentioned file ?

Sorry for posting this as issue, but I wasn't very lucky getting help somewhere else.

**Comment by tiliev** [comment]
@pesalvador, someone from the StackBlitz team could assist you with deleting the project.
If you do not want to share the URL here, I suggest you contact directly Eric Simmons or Albert Pai via [discord](https://discordapp.com/invite/stackblitz).

**Comment by pesalvador** [comment]
@tiliev  Thanks for your reply ! I've just sent him a message through discord.

**Comment by beeman** [comment]
Hi @pesalvador. I was wondering if this is already done. If not I'm happy to help you remove it, you can find me email in my profile.

**Comment by arkadash** [comment]
Hi, I'm having the same issue
how can I delete an anonymous project?

**Comment by AntonioCMMorelli** [comment]
Load the project associated with your profile. Click on Settings on left side, a kind of gear, select Delete project

**Comment by quesaamio** [comment]
> Hi @pesalvador. I was wondering if this is already done. If not I'm happy to help you remove it, you can find me email in my profile.

need your help to delete an annonymously created project
