### ISSUE TITLE
AJAX request on every click?

### ISSUE THREAD

**Issue by mindplay-dk** [stackblitz/core#677]
Not sure if this is "by design", but it seemed odd to me - there's an AJAX request going on every time I click to position the cursor:

![ajax-bug](https://user-images.githubusercontent.com/103348/45545935-02c72200-b81c-11e8-9ee0-07b996124d8c.gif)

Must be a ton of server load?

The requests look identical.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with a project link and screenshots of the error. Thank you! :)
