### ISSUE TITLE
Jquery error

### ISSUE THREAD

**Issue by carlosbtlr** [stackblitz/core#678]
![untitled](https://user-images.githubusercontent.com/42342263/45590815-96424500-b939-11e8-8cc9-701d58ac7729.png)
Error in index.js (1:1)
$ is not defined
Evaluating index.js
Booting application

**Comment by tiliev** [comment]
@carlosbtlr, you can add the jQuery reference as an external resource instead of npm package - https://stackblitz.com/edit/reference-jquery. Or, you can directly reference it in the .html - https://stackblitz.com/edit/jquery.
