### ISSUE TITLE
The dependencies box shows all lowercase letters but submits capitals.

### ISSUE THREAD

**Issue by getsetbro** [stackblitz/core#679]
The dependencies input box shows that it has removed capital letters but it submits the capitals and then cannot find the npm package.

<img width="541" alt="screen shot 2018-09-17 at 11 02 20 am" src="https://user-images.githubusercontent.com/442793/45631639-55494e00-ba69-11e8-9cb2-5c89ff7408a8.png">

=[

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
