### ISSUE TITLE
unable to have images 

### ISSUE THREAD

**Issue by krishnacts42** [stackblitz/core#681]
If able to upload images and have the assets means it will be more good

**Comment by tiliev** [comment]
Hello, @krishnacts42
Currently StackBlitz does not support images and static assets. The team is working on this. You could take a look at this issue - https://github.com/stackblitz/core/issues/72.
You could workaround this by uploading your images elsewhere and referencing them in StackBlitz or using GitHub - https://github.com/stackblitz/core/issues/45#issuecomment-375162006.
