### ISSUE TITLE
Impossible to work due to focus by preview window

### ISSUE THREAD

**Issue by HarelM** [stackblitz/core#682]
When coding and the preview window refreshes the focus is captured by the preview window and you can't continue typing - this makes the coding experience a living hell...

**Comment by HarelM** [comment]
Might be because of the content of the code, but still:
https://stackblitz.com/edit/angular-material2-issue-focus

**Comment by tiliev** [comment]
@HarelM, you are right, the focus is lost for a moment. I'll mark this as a potential bug.
You can workaround this by changing the hot reload trigger with `Save` for example:

![hot-reload-save](https://user-images.githubusercontent.com/6439482/45738113-43e27c00-bbf8-11e8-976c-ee9d8e52b09b.PNG)

**Comment by HarelM** [comment]
This is still an issue, and can still be reproduced in the link above.
I'm guessing that there's a need to focus back the editor window after a refresh to prevent this...
