### ISSUE TITLE
I am not able to configure it getting this error

### ISSUE THREAD

**Issue by hitu4233** [stackblitz/core#683]
The pipe 'mask' could not be found ("an>{{ applicantsphone }}</span>
                <br>
                <span>{{ applicantsssn_id}} {{ [ERROR ->]value | mask:showMask }}</span><p>real value: {{ value | mask:showMask }}</p>

**Comment by tiliev** [comment]
@hitu4233, please provide a StackBlitz sample.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
