### ISSUE TITLE
Getting a "Check your import statements & ensure you're importing the correct module names"

### ISSUE THREAD

**Issue by another-guy** [stackblitz/core#685]
The code works fine in a Node.js environment on my desktop, but ob StackBlitz I am getting an error mentioned in the title. Where do I start troubleshooting? And how do I address the issue?

`https://stackblitz.com/edit/typescript-aqymzv`

![image](https://user-images.githubusercontent.com/5762340/45911347-d0429980-bdc6-11e8-9949-4cb0af34e4a7.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
