### ISSUE TITLE
error when starting example

### ISSUE THREAD

**Issue by jdavidboyd** [stackblitz/core#686]
Error in /node_modules/systemjs/dist/system.src.js (2860:18)
Unexpected token <
Evaluating https://xeyvdaoyvny.angular.stackblitz.io/blitzapp
Booting application

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
