### ISSUE TITLE
Wrong import statement for rxjs Observable in auto-generated Guard in Angular project

### ISSUE THREAD

**Issue by aryaag** [stackblitz/core#688]
**Bug:**
The code auto-generated on creating a guard (in an Angular Typescript project) has incorrect import for Observable.

**What is the expected behavior?**
Since the version used by default is `rxjs 6.1.0`, the import statement should be:
`import { Observable } from 'rxjs';`

**What is the current behavior?**
Currently the auto-generated import statement is:
`import { Observable } from 'rxjs/Observable';`

Because of which the linter warns with *Cannot find module 'rxjs/Observable'.*.

**What are the steps to reproduce?**
- Create a new 'Angular Typescript' project in stackblitz
- Right click on the app folder under Filels in the sidebar
- Click on GENERATE NEW... > Guard

Sample: https://stackblitz.com/edit/angular-guard-wrong-import?file=src/app/auth.guard.ts

**Comment by arya-aag** [comment]
This seems like a simple enough thing to fix, are there any contribution guidelines that I can follow to create a pull request with the fix?
