### ISSUE TITLE
Support for CSV

### ISSUE THREAD

**Issue by k-sav** [stackblitz/core#689]
It would be nice to be able to pull in a CSV file when trouble shooting D3 visualisations, but when creating a new file, the file extensions are currently limited to js, md, css, html, json, less, sass, scss.

**Comment by purplem1lk** [comment]
Thank you for your patience! You should be able to create CSV files in your StackBlitz projects. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)

<img width="1430" alt="Screen Shot 2021-04-27 at 9 43 21 AM" src="https://user-images.githubusercontent.com/49956513/116251816-0396f300-a73d-11eb-8aca-ce84d8c5a890.png">
