### ISSUE TITLE
Add Code folding

### ISSUE THREAD

**Issue by maxchernin** [stackblitz/core#69]
Can code folding be added to the editor?

**Comment by EricSimons** [comment]
It can! Will look into implementing once I'm back from travels later next wk :)

**Comment by lucapalomba** [comment]
What about?

**Comment by yahyaKacem** [comment]
Any news about this feature?

**Comment by magikMaker** [comment]
I do see the option in the Command Pallet, but somehow can't get it to work (I'm on a MacBook)
<img width="507" alt="screen shot 2018-09-19 at 22 38 49" src="https://user-images.githubusercontent.com/905811/45780003-d7e62f00-bc5c-11e8-8ec4-e2fce07277f0.png">

**Comment by Veechiry** [comment]
Please describe in detail

**Comment by magikMaker** [comment]
This is now possible (hover the mouse over the margin to the right of the line numbers).
I think this ticket can be closed.

<img width="412" alt="screenshot 2018-10-25 at 15 55 34" src="https://user-images.githubusercontent.com/905811/47505459-783bfe80-d86e-11e8-9fc8-b9e867d5b62c.png">
