### ISSUE TITLE
PWA error 502

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#695]
Hey, looking into getting started with webapps, just found out your awesome online IDE supports pwa's from the ngconf you had on April, so i had found an existing project (https://my-pwa.stackblitz.io/) that seems to work in edit mode. But sadly it didn't work in on mobile nor on a separate browser tab. After forking the project (pwa2.stackblitz.io) it produced similar a error: 

![image](https://user-images.githubusercontent.com/6582633/46154702-0eedbd80-c2b9-11e8-908f-391d5002c96a.png)

I looked up multiple other pwa projects on stackblitz but didn't seem to find any that worked on mobile. 
 
Can anyone provide an error free solution ?

**Comment by apai4** [comment]
@nukadelic thanks for reporting this, I just pushed an update that fixes this issue and it looks like your pwa is working again 😄 lmk if it's working for you as well!

**Comment by nukadelic** [comment]
@EricSimons @apai4 awesome, thanks a lot ! Any chance you would consider adding a popup "add to home screen" for android-chrome with an custom icon ? I recon it would completely surpass all other online editors once you open you "app/game" in fullscreen and no once could tell the difference !
