### ISSUE TITLE
css files not loading from node_modules 

### ISSUE THREAD

**Issue by sagarjadhav968** [stackblitz/core#696]
I think something goes wrong because of from today's morning onwards stopped loading CSS file which is in node_modules but it works perfectly previously.
https://stackblitz.com/github/sagarjadhav968/loginapp?file=.angular-cli.json

![screenshot from 2018-09-27 20-43-23](https://user-images.githubusercontent.com/26452039/46156193-92e27e00-c296-11e8-94a3-f5b330419d4e.png)

**Comment by apai4** [comment]
@sagarjadhav968 Sorry for the delay on this! I just pushed an update which fixes node_modules styles not loading properly when defined in `.angular-cli.json` so your app is now booting properly again. Lmk if you run into any more issues

**Comment by sagarjadhav968** [comment]
@apai4 absolutely fine...Please let us know after making changes of your release.. because my organization product is on **PRODUCTION**  and we have integrated SDK so Please make sure make the release note and share....thank you for reply...

**Comment by sagarjadhav968** [comment]
issue is resolved
