### ISSUE TITLE
Import error, can't find file: cluster

### ISSUE THREAD

**Issue by sebpearce** [stackblitz/core#698]
![image](https://user-images.githubusercontent.com/6406263/46180966-b513e480-c306-11e8-85e5-636663f0ed25.png)

I have a React app that was functioning with no issues, but once I refreshed the browser (2018-09-27) after the recent update, I got this. Re-installing dependencies didn't fix it.

It doesn't happen on new projects, and I was able to get past it by stripping the project back to a bare-bones React app with almost no code.

Would love to know if this has come up before and if there are things that typically cause it, as a lot of googling hasn't turned up much.

**Comment by sebpearce** [comment]
Sure, thanks for the quick response! URL is https://tricklenote.stackblitz.io

**Comment by apai4** [comment]
Thanks for letting us know, @sebpearce! We've pushed some updates today and your app looks like it's working again. Lmk if you run into any more issues!

@sagarjadhav968 can you see if you're project is working now? If you're still having problems with your project please post your URL here or feel free to open another issue.

**Comment by sagarjadhav968** [comment]
@apai4  not solved yet....can you check have added the link..i think something is wrong in your new changes because it works perfectly before 27th Sep but after have some issue
[https://stackblitz.com/github/sagarjadhav968/repo1](url)

**Comment by apai4** [comment]
Closing this issue, tracking @sagarjadhav968's problem in #696
