### ISSUE TITLE
Issue with Typescript theme

### ISSUE THREAD

**Issue by babakness** [stackblitz/core#699]
Hello,

I noticed that if I don't have at least two generics when using generics, the theme breaks. See image

<img width="969" alt="ball-demo-cr7qdm_-_stackblitz" src="https://user-images.githubusercontent.com/2024235/46185860-9d9a1480-c290-11e8-9f15-0c14d8ba3c05.png">

This is on Chrome 69 on Mac 10.13.5

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
