### ISSUE TITLE
Empty tooltips on Safari 10.1.1 (macOS 10.12.5)

### ISSUE THREAD

**Issue by kerrishotts** [stackblitz/core#7]
On Safari 10.1.1 I'm seeing some odd behavior wrt tooltips -- they appear blank. If I click on them, though, the content displays. Does not happen on Chrome 59.0.3071.115 on the same system.

<img width="418" alt="2017-08-03 at 16 16" src="https://user-images.githubusercontent.com/164498/28944217-5a306aa6-7867-11e7-8a3d-85a95f9fc5fb.png">

**Comment by claytonschneider** [comment]
@kerrishotts, looks like a regression in safari. we have a fix coming soon!
