### ISSUE TITLE
Styles are getting duplicated on file change

### ISSUE THREAD

**Issue by adamk33n3r** [stackblitz/core#703]
Here's an example https://stackblitz.com/edit/angular-v7k3u9

Change a file (any file, even a component typescript file) and notice that a new `<style>` tag is inserted every time.

Another issue that might be related is that if you make an error in the `styles.scss` file like for example misspelling `!important` like `!importan` it will forever error, even if you fix it. You must reload the entire page to resolve this issue. It's remembering when it was wrong and still trying to compile it. This also happens when editing a component's scss, not just the main `styles.scss`. Changing the reload mechanism to "save" doesn't even help. The errors show up on edit so I have to reload all the time, it's quite unbearable.

**Comment by EricSimons** [comment]
Eek, I’m so sorry about this 😥 This is likely due to our new v2 migration. @apai4 can you look into this ASAP?

**Comment by apai4** [comment]
Thanks for letting us know about this @adamk33n3r, this was an issue with the recent migration on our end and a fix has been deployed 😄 lmk if you're still running into issues with styles not unloading properly.

**Comment by apai4** [comment]
@adamk33n3r I pushed some updates for style reloading which should fix the duplicate styles and errors incorrectly persisting. Lmk if it works for you or if you run into any issues

**Comment by adamk33n3r** [comment]
@apai4 Thanks so much, it seems to be working fine now. It does still seem to show an scss error on edit even with hot reload trigger set to "save". But fixing the error and then saving works so that resolves that.

And thanks @EricSimons for responding so quickly. I didn't know there was a v2 upgrade until yesterday. It's good to see the app getting attention!

**Comment by tylde** [comment]
Sure, for example when I delete the font color from style.css it doesn't set to default.
https://stackblitz.com/edit/react-hnfhyt?file=style.css

**Comment by apai4** [comment]
@tylde Sorry for the delay, I just pushed a fix for this so styles in React should be unloading properly now 😃 Lmk if you're still running into problems with this

**Comment by tylde** [comment]
It works fine now, thanks. :)
