### ISSUE TITLE
Add support for other languages

### ISSUE THREAD

**Issue by filips123** [stackblitz/core#705]
Please add support for other programming languages, like Python 3, PHP, C...

**Comment by MathiasMagnus** [comment]
There is already a version of Clang compiled to Wasm which creates Wasm binaries to ran inside the browser. If the same could be added to Stackblitz, that would be awesome.

https://tbfleming.github.io/cib/

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If there are other languages you would like to see, feel free to tag me or ask to reopen this issue. Thank you! :)
