### ISSUE TITLE
Unable to run anything on IE

### ISSUE THREAD

**Issue by ihybrid11** [stackblitz/core#706]
Hi All,
Requesting your inputs here. I am unable to run anything on Stackblitz in IE 11. I am also not getting the Sign In button. IE shows the following issues - 
![capture](https://user-images.githubusercontent.com/10988084/46259282-fa7f1000-c4c6-11e8-934e-97da2a18c291.PNG)

**Comment by tiliev** [comment]
@ihybrid11, I can confirm the StackBlitz samples does not work in IE 11 anymore.

**Comment by apai4** [comment]
@ihybrid11 @tiliev Sorry for the delay on this, IE11 should be supported now again! Lmk if you run into any problems with projects in IE

**Comment by ihybrid11** [comment]
@apai4 @tiliev /team thanks for fixing this and thanks for your support on this.
It is working perfectly now. :)

**Comment by tiliev** [comment]
Thank you, it is working!
