### ISSUE TITLE
Where did Teleport go ?

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#709]
I remember using this to debug on mobile before, very handy and potentially the best feature i ever seen in any IDE

**Comment by dpsthree** [comment]
I noticed this was down earlier today as well, but it seems to working now.

**Comment by apai4** [comment]
@nukadelic @dpsthree sorry about that! We temporarily disabled Teleport earlier this week to isolate some issues on our end, but it's back and has been working for a couple days now 😃
