### ISSUE TITLE
Click to load not working

### ISSUE THREAD

**Issue by dymafr** [stackblitz/core#710]
Embedded stackblitz are loaded by default even if ctl is set to 1 in the link.
This issue is a regression, it was working as expected before.

Thanks a lot for your amazing work:)

**Comment by hadesMM** [comment]
same for us. It's an important issue for our mobile/tablet users as it crashes their browser

**Comment by carlschooff** [comment]
For us it seems to have magically fixed itself with no changes on our end.

**Comment by dymafr** [comment]
Same here

**Comment by purplem1lk** [comment]
Thank you for your patience - This issue looks resolved and will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a project link, description, and screenshots of the error. Thank you! :)
