### ISSUE TITLE
resulted in a network error response: an object that was not a Response was passed to respondWith()

### ISSUE THREAD

**Issue by msalehisedeh** [stackblitz/core#713]
I am getting the following error:
resulted in a network error response: an object that was not a Response was passed to respondWith()

what is wrong

https://visualize-it.stackblitz.io/

**Comment by bennypowers** [comment]
I get a similar error on firefox

```
A ServiceWorker passed a promise to FetchEvent.respondWith() that resolved with non-Response value ‘undefined’.
```

**Comment by bennypowers** [comment]
FIXED: I simply had the wrong URL to the remote resource I was trying to access.

**Comment by purplem1lk** [comment]
> FIXED: I simply had the wrong URL to the remote resource I was trying to access.

This issue is resolved and will be closed accordingly. If you have any questions, feel free to tag me. Thank you! :)
