### ISSUE TITLE
Component not getting registered in the app module ts file when generated by Angular Generator option

### ISSUE THREAD

**Issue by amrohit** [stackblitz/core#715]
Hi There!

After recent stackblitz update, Angular is not working as expected. Now for every newly generated component, I have to register those to app.module.ts manually. Also, the preview section do not reflect the recent changes as it were in the previous version. Please fix this. I am still waiting for it.

**Comment by dpsthree** [comment]
This seems to be fixed. Thanks for the quick turn around!
