### ISSUE TITLE
Import error, can't find files: core-js/es6/reflect

### ISSUE THREAD

**Issue by ssuperczynski** [stackblitz/core#717]
Latest StackBlitz update stopped import repo from github which is created by angular-cli.

Error in the console points that `core-js` isn't installed, but is declared in the package.json

```
Import error, can't find files:
core-js/es6/reflect
core-js/es7/reflect
zone.js/dist/zone
@angular/core
```

**Repo**: https://github.com/ssuperczynski/ngx-easy-table
**StackBlitz**: https://stackblitz.com/github/ssuperczynski/ngx-easy-table

**Comment by tiliev** [comment]
@ssuperczynski, `core-js` is not in package.json, some other packages are missing, too. I got it working by installing them  -https://stackblitz.com/edit/sb-core-717.

**Comment by ssuperczynski** [comment]
Hmm, but core-js is included in the package.json
https://github.com/ssuperczynski/ngx-easy-table/blob/master/package.json#L58

but when I check Stackblitz's package.json is not being included, is it intended?

**Comment by ssuperczynski** [comment]
Thank you for explanation, fixing this prompt did the trick and my repo works again.
Thanks for quick fix! 🚀
