### ISSUE TITLE
Syntax highlighting breaks after type assertion.

### ISSUE THREAD

**Issue by SammyIsra** [stackblitz/core#718]
Syntax highlighting on the editor seems to break whenever you do a type assertion of the form:
```ts
<Car>x
```
But not when you use the `as` keyword:
```ts
x as Car
```
Example: 
![image](https://user-images.githubusercontent.com/8962228/46537975-abe3c400-c880-11e8-8b22-ba8ac533e098.png)

You can see on line 8 I do a type assertion using the `as` keyword, and syntax highlight is just fine. However, on line 16 I do another type assertion using the `<Type>` style, and the syntax after that is all over the place.

This was on a blank TS project, with no custom dependencies or anything of the sort.

**Comment by ajpaul** [comment]
I am also seeing this.

`
let someValue: any = "this is a string";
let workingHighlight: number = (someValue as string).length;
let brokenHighlight: number = (<string>someValue).length;
`

The above code will trigger the problem.

**Comment by SamVerschueren** [comment]
We did a massive overhaul of the code tokenizers. This should work as in VS Code right now. Closing it as I expect it should work. Feel free to open a new issue if you experience other things.

![image](https://user-images.githubusercontent.com/1913805/114087953-c4e7e880-98b4-11eb-9e6e-5d028862ca54.png)
