### ISSUE TITLE
Issue on downloading the dependencies

### ISSUE THREAD

**Issue by Abilashs003** [stackblitz/core#720]
even installing the dependency its still showing not able to find the dependency

**Comment by Ajathashatru** [comment]
Steps:

-->download chart.js from  dependencies column
--> Try importing it to into any component .it shows "Not able to find dependency. "

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
