### ISSUE TITLE
Share not creating up to date code display

### ISSUE THREAD

**Issue by UniWrighte** [stackblitz/core#725]
most code sharing sites auto generate URLs when you make changes to a project. Changes are lost on refresh.

**Comment by nukadelic** [comment]
Maybe try hard reloading the page to delete the cached files. Worked for me.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
