### ISSUE TITLE
html like tags in typescript code breaks syntax highlighting. 

### ISSUE THREAD

**Issue by StephenWTurner** [stackblitz/core#726]
When casting a type in typescript like this:

`    const parent = <Group>groupRows[0];`

The syntax highlighting for the rest of the code changed, less seems to be coloured. 

Working on the theory that the `<Group>` was being interpreted as an opening tag I added a fake closing on in a comment

`    const parent = <Group>groupRows[0];  // </Group> (Fix syntax coloring)`

And it appeared to work around the issue in the rest of the file.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
