### ISSUE TITLE
rxjs template does not import css styles

### ISSUE THREAD

**Issue by kiwikern** [stackblitz/core#728]
In the rxjs template, the styles from the `styles.css` file are not imported by default. The following line should be added to the `index.ts` file: 
```
import './style.css';
```

**Comment by magikMaker** [comment]
I'm surprised this doesn't get picked up.

**Comment by kc0tlh** [comment]
@gamerboy, @magikMaker and @kiwikern: This has been resolved!

<img width="1436" alt="image" src="https://github.com/stackblitz/core/assets/1532264/c4ee2e96-36ab-4352-870b-8137dc9931ad">
