### ISSUE TITLE
Feature request: Allow server side coding in stackblitz

### ISSUE THREAD

**Issue by nitinjs** [stackblitz/core#729]
Hi,

Thank you for developing Stackblitz, it is great tool to work/test/learn angular without setting up any environment on my machine.

Feature request: 
1. Allow server side coding in stackblitz -> asp.net mvc/nodejs etc
2. DB connectivity through server side code -> mongodb/mysql

**Comment by pappasa** [comment]
Yes, I would also like to have that, because I am behind a corporate proxy, which does block npm installations. I found [this ](https://stackblitz.com/edit/mean) using the MEAN stack on Stackblitz, but I could not get it to work.

**Comment by nishabundela14** [comment]
any updates on this . facing same issue

**Comment by titombo** [comment]
Would like to know also how to overcome it

**Comment by kc0tlh** [comment]
As of today, these are the backend starter projects available on StackBlitz.com:
<img width="974" alt="image" src="https://github.com/stackblitz/core/assets/1532264/a4abc328-a75a-471f-b229-872937409126">

For enterprise users, please reach out to enterprise@stackblitz.com and visit [stackblitz.com/enterprise](stackblitz.com/enterprise) for more info.

**Comment by nitinjs** [comment]
As of today 08/2024
thanks for adding webcontainer support in Stackblitz which runs nodejs in browser
