### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by lazarljubenovic** [stackblitz/core#73]
I'm one of those weird developers that prefer to use a light theme. I hope it can fit somewhere on the roadmap.

**Comment by EricSimons** [comment]
@lazarljubenovic one of our first designs was with a light theme actually :) Def fits in on the roadmap — lots of plans to expose editor config options for color schemes, plugins, etc in the future

**Comment by prabirshrestha** [comment]
I would be interested in this too. Not for day to day coding but for live coding during presentations where light color projects better.

**Comment by billbarni** [comment]
Another interested dev here. I have a uncommon conditions where my eyes tire VERY fast on dark themes. Hope this gets implemented.

**Comment by maxrahder** [comment]
I'd like a light theme too. Dark themes lack the contrast I need.

**Comment by nemethmik** [comment]
You must be kidding, Stackblitz is brilliant but, cannot it be switched to light editor mode in 2019?

**Comment by JudyLipinski** [comment]
cant use well for projected demos as dark colors do not project well.

**Comment by beeman** [comment]
Since a few weeks we added support for User and Workspace settings, this allows you to set at least the syntax highlighting to the light theme. The rest of the UI will be dark for now. 

We totally understand the desire for a light theme and it's definitely something we aim to support in a more complete way down the road.

![image](https://user-images.githubusercontent.com/36491/54301824-b0c64580-458d-11e9-9db7-b0567702041b.png)

**Comment by lazarljubenovic** [comment]
MY EYES CAN BREATHE

Thanks :tada:

**Comment by DeborahK** [comment]
Has anyone gotten this to work? I edit my workspace settings exactly as shown in the above screen shot and nothing happens. I tried refreshing after the edit, and the settings change back to the dark theme.

How do we *save* the theme and apply it to the workspace?

**Comment by lazarljubenovic** [comment]
Hmm, it "just works" for me after hitting <kbd>CTRL</kbd> + <kbd>S</kbd> while on that screen, with focus inside the editor.

**Comment by DeborahK** [comment]
Doh! The Ctrl+S is the part I was missing. The Save button didn't light up and I didn't think of just using the keys. THANKS!

**Comment by beeman** [comment]
Glad to hear you got it working @DeborahK ! I'll see if we can make the experience more fluent!

**Comment by DeborahK** [comment]
Thanks! Lighting up the save button would help! :-)

**Comment by steffy2110** [comment]
> Hmm, it "just works" for me after hitting CTRL + S while on that screen, with focus inside the editor.

i tried saving using this but for me no change still:(

**Comment by JimbobTheSailor** [comment]
I see the light, I see the light ....awesome

**Comment by jeffwhelpley** [comment]
So, is there just vs-dark or vs-light as theme options in StackBlitz? I like vs-light for the most part for presentations, but one major issue is that in JavaScript files the code colors are way too light. It is unreadable on the big screen. Does anyone have a solution for this?

**Comment by DeborahK** [comment]
I met with Eric about this last week. Especially when doing screen shots or presenting ... dark seems too dark and light is *way* too light. AFAIK, there are no other choices. I'm hoping this changes soon. Maybe we need to create a new issue since this one is closed @jeffwhelpley ?

**Comment by jeffwhelpley** [comment]
@DeborahK I created a new issue #1092 for this.

**Comment by serefarikan** [comment]
In case anybody arrives at this issue from google, and in case @beeman 's suggestion is not working for you, as it has not worked for me, please see this[ very helpful comment ](https://github.com/stackblitz/core/issues/1092#issuecomment-674507229)from another issue. Hint: there is a 'toggle light/dark theme' button at the bottom left of the page now.

**Comment by gspassky** [comment]
@serefarikan you made my day ))) Never even thought to look up there!
