### ISSUE TITLE
Broken imports ( Can't find package `child_process` )

### ISSUE THREAD

**Issue by nukadelic** [stackblitz/core#730]
I remember before the update we were able to include static minified js files alongside the npm modules. Now when attempting to access one of my old projects it seems that `webcontainer` is failing to load a specific url that had broke everything. There is no error message on the html page besides empty brackets `{}`.  After removing the file url from the project dependencies and including the script with src to the remote file the fetch error had disappears from the developer console but the brackets are still there. Please have a look at my project: [https://stackblitz.com/edit/neat-asteroids](https://stackblitz.com/edit/neat-asteroids), many thanks in advance. 

P.S i was showing this to somebody on my phone two weeks ago with no trouble at all.

---
EDIT: tried installing the package both with npm and manually adding the entire minified file to a file in the project and imported it. In both cases the editor complains that child_process is missing ( which should come by default with node, adding the package to project didn't solve the issue either )
![image](https://user-images.githubusercontent.com/6582633/46918247-9a867e80-d01b-11e8-8b1d-4950e549d24e.png)

**Comment by apai4** [comment]
@nukadelic Sorry about that! I just pushed an update that fixes import issues around `child_process` and your project is working again 👍 thanks for reporting this!

**Comment by nukadelic** [comment]
thank you 👍
