### ISSUE TITLE
"Can't find package: " not found empty string dependency name

### ISSUE THREAD

**Issue by ibenjelloun** [stackblitz/core#732]
I came back to this old working simple code (https://stackblitz.com/edit/simplest-routing-example), and faced this error "Can't find package: " with empty dependency name :

![image](https://user-images.githubusercontent.com/1528304/47145830-fd517180-d2ca-11e8-827f-81dd11f42495.png)

I upgraded the packages with no success.

**Comment by fxvits** [comment]
I get the same issue

**Comment by ibenjelloun** [comment]
In my shared stackblitz, the issue was that my project made with angular 5 initially was updated to 6 when the `angular-cli.json` was deprecated. Then 7 and I did not make the required changes to the project structure.

Before :
app
    |_...
.angular-cli.json
index.html
main.ts
package.json
polyfills.ts
style.css

After :
src
   |_app
        |_ ...
    index.html
    main.ts
    polyfills.ts
    style.scss
angular.json
package.json

Notice that the style file is now `style.scss` and not `style.css`.
I'm closing this issue as it is not related to stackblitz, updating libraries to major versions require to updated the code to make it work.
