### ISSUE TITLE
Angular6 template - not running in IE11

### ISSUE THREAD

**Issue by sgentile** [stackblitz/core#733]
Having issue.... https://angular-6-primeng.stackblitz.io/

Runs fine in Chrome

I have the polyfills all setup in the polyfill.ts file

**Comment by vegarringdal** [comment]
maybe you are using a old version 😂 

![image](https://user-images.githubusercontent.com/2901416/47242243-74cbf180-d3ee-11e8-89df-f7fdab21100e.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists after confirming your IE version, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)
