### ISSUE TITLE
Console disappear from embed url after view change with devtoolsheight parameter

### ISSUE THREAD

**Issue by adrianbienias** [stackblitz/core#735]
1. Add devtoolsheight parameter to embed url and set value between 10-100.
2. Change view from both to editor.
3. Change view from editor to both or preview.
4. Console completely disappear from preview window.

Example for testing:
https://stackblitz.com/edit/ball-demo?embed=1&devtoolsheight=50

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
