### ISSUE TITLE
Issue when importing depedencies

### ISSUE THREAD

**Issue by Petrus3n** [stackblitz/core#736]
I have installed chart.js with the command 

> npm install chart.js --save 

and chart.js have appeared in depedencies as 

> "chart.js": "2.7.3"

then I import chart.js with this code 

> import {Chart} from 'chart.js';

Then it shows me this error:

>  Cannot find module 'chart.js'

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
