### ISSUE TITLE
Live Window Fooling React Dev Tools

### ISSUE THREAD

**Issue by Reader8765** [stackblitz/core#737]
If you watch this video, you can see that the React elements aren't being cleared:
https://drive.google.com/file/d/1xdqXY_5rd_SQ5RLcj26cTkq4wDgtejyg/view

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing (video link doesn't work anymore) and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
