### ISSUE TITLE
Angular project `can't find package: src` - Solved

### ISSUE THREAD

**Issue by linhub15** [stackblitz/core#738]
For anyone that runs into this issue. 
Using absolute paths for Typescript `import` statements causes project to give an error.
It works fine in VS Code locally, but not on Stackblitz.

![image](https://user-images.githubusercontent.com/10420994/47395340-9f19f980-d6e3-11e8-9f48-2f17d4ef6fbd.png)

**Wrong**: absolute import`import { Employee } from 'src/app/models/employee.model';`
**Right**: relative imports `import { Employee } from '../models/employee.model';`

I'm new to Angular so I'm not sure what the best practices are.

**Comment by EricSimons** [comment]
@linhub15 does it also work w/ the Angular CLI? I think we disabled absolute paths bc it wasn't supported in the newer versions of Ang CLI, but can investigate otherwise

**Comment by amit-kumar-dubey** [comment]
yes i have the same issue and it resolved by adding relative path.
thanks

**Comment by reza3zar** [comment]
but it doesn't to me!!!

**Comment by wallysoncarvalho** [comment]
Still having this problem, any ideia how to fix ?

**Comment by curchadw** [comment]
I tried another solution by trying to add it in manually....but it still will not work. Might have to just switch over locally.

**Comment by HemanthGirimath** [comment]
I did try the relative path. But its not working still the same error.
