### ISSUE TITLE
depdependency issue

### ISSUE THREAD

**Issue by kikithedeveloper** [stackblitz/core#740]
link: https://stackblitz.com/github/zefoy/ngx-swiper-wrapper/tree/master/example

Went in and saw this (screenshot below). Figure I should say something...

![image](https://user-images.githubusercontent.com/6993579/47504653-aacc0400-d83a-11e8-9f44-80445564bd91.png)

**Comment by EricSimons** [comment]
@kikithedeveloper in your package.json you have `"ngx-swiper-wrapper": "^7.0.0"`, but the latest published version is 6.4.1 :)
