### ISSUE TITLE
The url to this repository is invalid

### ISSUE THREAD

**Issue by michaeliyke** [stackblitz/core#741]
I was navigating the sample Angular codes on [this](http://angular2-first-look.azurewebsites.net/) website and upon  clicking [example 14](https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/projects/component-nest/?bust=1540490318909) I landed on a blank page that says <blockquote><i>The url to this repository is invalid. </i></blockquote> I could manage to skip it but I think it is necessary to let the creators know in time. Thanks

Michael C. Iyke

**Comment by tiliev** [comment]
@michaeliyke, I think this is the correct URL - https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/projects/component-next. It was misspelled.

**Comment by michaeliyke** [comment]
Thanks a lot for the quick response. please I suggest you also update the website itself with the correct spelling.

----- Reply message -----

**Comment by rml1997** [comment]
I've raised a PR with John Papa to highlight this issue. It is a problem with his website rather than StackBlitz.

**Comment by rml1997** [comment]
For the record, it should have been ComponentNest but he seems to have made a typo. As @tiliev says, https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/projects/component-next works currently.
