### ISSUE TITLE
Can't Find Package `Blank`

### ISSUE THREAD

**Issue by sliceofbytes** [stackblitz/core#742]
I was creating a quick blitz and managed to get this project in an invalid state by renaming the app.component.css multiple times. As far as I can tell their is nothing wrong with the visible files in the project.

It seems to think I'm missing a dependency with no name.  https://i.imgur.com/Wv0f9fa.png

Here is the example project in it's broken state.

https://stackblitz.com/edit/angular-gupzaz

**Comment by ibenjelloun** [comment]
This looks like a duplicate of this issue : https://github.com/stackblitz/core/issues/732

**Comment by sliceofbytes** [comment]
My appologies that does look like the same issue. Feel free to close this issue / merge it with https://github.com/stackblitz/core/issues/732

**Comment by ibenjelloun** [comment]
The shared project is broken because of an error in the `angular.json` :

```
"styles": [
              "src/styles.scss"
],
```

instead of :

```
"styles": [
              "src/styles.css"
],
```

**Comment by sliceofbytes** [comment]
Good catch, I thought I had renamed the styles file as well.
