### ISSUE TITLE
Update React to 16.7.0 Alpha

### ISSUE THREAD

**Issue by Reader8765** [stackblitz/core#747]
A big new version release of React has come out with hooks: https://reactjs.org/docs/hooks-intro.html. This needs to be the default or an option for the editor. The default is still 16.5.0 for some reason.

**Comment by sebpearce** [comment]
In case anyone is reading this and doesn't know, you can use React 16.7.0-alpha in StackBlitz by installing the `react@next` and `react-dom@next` dependencies instead of the standard React.

**Comment by Reader8765** [comment]
@sebpearce Not working for me. Can you post an example?

**Comment by sebpearce** [comment]
@Reader8765 

![2018-10-31 09 47 04](https://user-images.githubusercontent.com/6406263/47755405-2ffb6100-dcf2-11e8-8ed6-3b8b05b8da66.gif)

**Comment by Reader8765** [comment]
Thanks! I didn't know about the dependencies feature. I am a new user.
