### ISSUE TITLE
Dumping Event (Angular)

### ISSUE THREAD

**Issue by Maels1991** [stackblitz/core#750]
Hello everyone,

It seems that dumping a DOM Event object in the embedded console does not work as expected.

app.component.html
`<button (click)="dumpEvent($event)">Click</button>`

app.component.ts
```
click(event){
    console.log(event);
    // Incomplete output : MouseEvent {isTrusted: true}
    // Expected : MouseEvent {isTrusted: true, screenX: 458, screenY: 286, clientX: 111, clientY: 74, …}

}

```

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a project link, description, and screenshots of the error. Thank you! :)
