### ISSUE TITLE
Better iPad Pro support / external keyboard

### ISSUE THREAD

**Issue by okiess** [stackblitz/core#755]
Cursor keys and @ sign don’t work on iPad Pro with external Smart Keyboard.

**Comment by miguelchico** [comment]
No updates here?

**Comment by okiess** [comment]
No change, still not working...

**Comment by noodlemind** [comment]
The issue still seems to be existing.

**Comment by okiess** [comment]
Still nothing?

**Comment by EricSimons** [comment]
This is an upstream issue that VS Code themselves are working on IIRC. Will touch base with their folks and see what the latest is 👍

**Comment by michaelaflores** [comment]
Any updates here? Interested in using this combo

**Comment by six-edge** [comment]
Anyone know how to do a mouseover to see the typescript error on a tablet device? Short press brings up the context menu but I can't seem to get the error overlap appear.

**Comment by kc0tlh** [comment]
This should be working well now that [Safari support is launched](https://blog.stackblitz.com/posts/webcontainers-are-now-supported-on-safari/). Feel free to re-open if issues persist!
