### ISSUE TITLE
Update Sass.js to 0.10.11 to support first-class functions

### ISSUE THREAD

**Issue by tiliev** [stackblitz/core#757]
Currently Stackblitz uses Sass.js version `0.10.6` which uses libsass version `3.4.5`. Sass introduced first-class functions (more info [here](https://medium.com/@kaelig/sass-first-class-functions-6e718e2b5eb0)) in version `3.5`. Can you update Sass.js to version `0.10.11` (this uses libsass version `3.5.4`) so Stackblitz can support first-class functions?

**Comment by simeonoff** [comment]
@EricSimons any updates on whether the Sass.js version will be bumped anytime soon? The way it is right now, we resort to using only old Sass versions and syntax.

**Comment by zdrawku** [comment]
I want to emphasize on the importance of this issue, it has been a month since @tiliev logged it. Any type of comments will be highly appreciated?

@apai4, @EricSimons, @beeman

**Comment by beeman** [comment]
I can't promise anything yet, but I'm going to see if I can get this updated soon. Stay tuned.

**Comment by tiliev** [comment]
@beeman, @apai4, Could you please share what is the status of this issue? Should we expect the `Sass.js` version to updated soon?

**Comment by beeman** [comment]
@tiliev PR is created, currently waiting on a good test that we don't break anything with the new Sass.js version.

**Comment by kdinev** [comment]
@beeman Hey, a friendly reminder that we're still waiting on this update. 

I would like to know if it would happen soon, so we can update our own library's sass for our next update? We already have quite a few users complaining about sass warnings and it would be great if we can get rid of them relatively quickly. Thanks!

**Comment by zdrawku** [comment]
@apai4 may I ask, why you've closed this issue? Any comments would be highly appreciated.

**Comment by tiliev** [comment]
I can confirm it is updated with: 
sass.js - v0.10.13 (7209593) - built 2018-11-19
providing libsass 3.5.5 (39e30874)
via emscripten 1.38.18 (7a0e274)
Thanks a lot, guys!

**Comment by beeman** [comment]
The issue was closed automatically as it was referenced in the PR in a private repo that got merged.

[Here](https://stackblitz.com/edit/sassjs-function?file=src%2Fapp%2Fapp.component.scss) you can see a demo of how it works.

Thanks for the patience all!
