### ISSUE TITLE
Can't resolve all parameters for ApplicationModule: (?)

### ISSUE THREAD

**Issue by kuncevic** [stackblitz/core#758]
I have this repo https://github.com/kuncevic/ngx-line-chart-issue that successfully runs locally however when I am importing that in to stackblitz https://stackblitz.com/github/kuncevic/ngx-line-chart-issue it is giving an error screen:
```
Error in /turbo_modules/@angular/compiler@7.0.1/bundles/compiler.umd.js (1098:21)
Can't resolve all parameters for ApplicationModule: (?).
```

Any ideas why?

**Comment by pandamorphism** [comment]
The same for 7.0.2
> Error in /turbo_modules/@angular/compiler@7.0.2/bundles/compiler.umd.js (2617:21)
> Can't resolve all parameters for ApplicationModule: (?).

**Comment by schuchard** [comment]
I'm experiencing this too. `ng new`ing an app locally with Angular CLI 7.0.4 runs fine locally but will not load in Stackblitz.

**Comment by Gillespie59** [comment]
Hi. Any news about this issue ?

**Comment by pedroclayman** [comment]
adding `import 'core-js/es7/reflect';` into polyfills.ts solved the issue for me

**Comment by Gillespie59** [comment]
Also true for me

**Comment by schuchard** [comment]
`import 'core-js/es7/reflect';` in polyfills.ts worked for me.

**Comment by Gillespie59** [comment]
But why should add this polyfill only for stackblitz?

**Comment by alo** [comment]
Same here 👆🏽

**Comment by JochenFromm** [comment]
Yes, for me too. Stackblitz stopped working after an update from Angular 5 to Angular 7, and adding the line @pedroclayman mentioned [solved the problem](https://github.com/JochenFromm/QuoteInspector/commit/b6f867b8304adb3d58828dfb15827e83825a8363)

**Comment by mread1208** [comment]
Also getting this issue with Angular version 7.3.0.  Adding `import 'core-js/es7/reflect';` to the `src/polyfill.ts` file worked as described above.

**Comment by EliasKhajo** [comment]
i have the same issue `Can't resolve all parameters for ApplicationModule: (?).`

**Comment by xpioneer** [comment]
I have the same issue when I updated the version(I use `import 'core-js/es7/reflect';`).
![image](https://user-images.githubusercontent.com/30486161/59960735-259b0b00-94ff-11e9-9a0e-fcdab09a90ee.png)

The new version of core-js has been changed.
`import 'core-js/features/reflect';` It's working.

old version: `"core-js": "^2.6.1"`

new version: `"core-js": "^3.1.4"`

**Comment by schuchard** [comment]
If the `import 'core-js/features/reflect';` doesn't solve it, using the `@Inject` decorator may. 
https://angular.io/api/core/Inject#description

```ts
constructor(@Inject(UserService) userService: UserService) {}
```

**Comment by reyou** [comment]
Can some one help on Angular 8?
Seems like pollyfill come by default but still have issue with this.

https://codesandbox.io/s/angular-intro1-7kxtf

**Comment by btakita** [comment]
@reyou Did you figure out the cause of this issue?

**Comment by reyou** [comment]
@btakita nope. back to the local development :)

**Comment by Atticus29** [comment]
Has progress been made on this? I've asked a related question on S.O. here: https://stackoverflow.com/questions/62095576/expected-styles-to-be-an-array-of-strings-error-when-importing-from-github-to
