### ISSUE TITLE
Cannot sign in to stackblitz with github!

### ISSUE THREAD

**Issue by mediplex** [stackblitz/core#760]
I have been trying since a while to sign in with my github but when ever I try I receive this message: **Yikes! Something went wrong with your request**.

Check the attached.
<img width="1077" alt="stackblitz" src="https://user-images.githubusercontent.com/40671746/47744039-6654c400-dc91-11e8-9ba1-a598cee18c71.png">

Thanks,

**Comment by tiliev** [comment]
@mediplex, it works on my side. What's your OS, browser and browser version?

**Comment by mediplex** [comment]
Windows 10 / Chrome... both of them are up to date.

**Comment by samplesage** [comment]
I also experience the same issue then I followed the instruction of @apai4  on issue #95 but still I get the same message.

Also here are my OS and Browser/Browser Version
**OS** : Windows 7 SP 1
**Browser** : Google Chrome v70.0.3538.77

**Comment by mediplex** [comment]
@samplesage any update?

**Comment by darmway** [comment]
Same here. 
Windows 10 1809 / Ubuntu 18.04. 
Chrome 72.0.3626.108 and Firefox 65.0.1.

**Comment by maverick-coder** [comment]
Same here.
Windows 10 1809 build 17763.316
Chrome 72.0.3626.109

**Comment by Maryannah** [comment]
Same for me, has been an issue since I switched github accounts since Jan. 2019. Any updates on this ?

**Comment by projer** [comment]
Same here, new Github account, and impossible to login:
Windows 10 Pro 1803 build 17134.523
Chrome 74.0.3729.169

**Comment by sujitworx** [comment]
Cannot sign in into GitHub with new GitHub account. shows the same error as above. MAC OS X Mojave & Chrome Browser

**Comment by ItsMeRTXYZ** [comment]
Yes, I also am having this problem. And I recreated my GitHub. So that is the problem.

**Comment by ItsMeRTXYZ** [comment]
Just change your email

**Comment by Maryannah** [comment]
Litteral life saver. Thank you for that information ! Although annoying, this will do the job !

**Comment by ItsMeRTXYZ** [comment]
If you use gmail @Maryannah make it s.omething@gmail.com or something+2@gmail.com, you can put as many dots as you want in gmail addresses and you can add a +anything and it will all go to your inbox

**Comment by TroyEdwardLee** [comment]
Windows 10 Enterprise,
Chrome: Version 77.0.3865.90 (Official Build) (64-bit)
Same here.

**Comment by David-Ben-Mesecke** [comment]
Really? This is still not fixed? I have the same problem in 2020.

**Comment by Maryannah** [comment]
It is explained how to resolve that, and when you think about it the error seems logical. Consider making a little change to your email and you're done !

**Comment by David-Ben-Mesecke** [comment]
> It is explained how to resolve that, and when you think about it the error seems logical. Consider making a little change to your email and you're done !

No its not.

**Comment by Maryannah** [comment]
Well okay then, be stubborn and hope for a change in the near future :)

**Comment by David-Ben-Mesecke** [comment]
It's not going to get fixed just because you claim it is.

**Comment by EricSimons** [comment]
Hey all- this error typically happens when you don't have a confirmed email address in Github. You can ensure your email address is verified on Github's email settings page: https://github.com/settings/emails

On our end, we need to add a better error message for this. I've put it on our internal tracker and should have a fix out soon.

If anyone is hitting this error and has verified they have a confirmed email address in Github, please comment and lmk so we can investigate! 🙏

**Comment by David-Ben-Mesecke** [comment]
> If anyone is hitting this error and has verified they have a confirmed email address in Github, please comment and lmk so we can investigate! 🙏

Unfortunately that is exactly my case, my email is confirmed at github. I did check my browser console also, adding the error messages there to help you out.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT cdn.segment.com/analytics.js/v1/ta1kDK49qdEDEfd8KYxI37mW0GPkLKn1/analytics.min.js:1 

Failed to load resource: callback?code=b90009cc41bb977b20ca&state=430145957af5cac82f4e8371d09c7a4fc6636b656873e2eb:1 Failed to load resource: the server responded with a status of 422 ()

**Comment by EricSimons** [comment]
Yikes- thanks for bringing this to our attention, seems like there might be another bug causing that 422. @apai4 can you dig into our logs and see what's happening with @David-Ben-Mesecke's account?

**Comment by David-Ben-Mesecke** [comment]
Your welcome 👍

**Comment by apai4** [comment]
@David-Ben-Mesecke If your primary email on Github is confirmed, is it possible you have another Stackblitz account with the same email address? If so, can you try @ItsMeRTXYZ's [suggestion](https://github.com/stackblitz/core/issues/760#issuecomment-526950323) of changing/reconfirming your primary email on Github to something different? If you use Gmail you can add a period somewhere in your email to make it unique. Let us know if that fixes the issue for you. We'll work on improving the error message for this.

**Comment by David-Ben-Mesecke** [comment]
> @David-Ben-Mesecke If your primary email on Github is confirmed, is it possible you have another Stackblitz account with the same email address? If so, can you try @ItsMeRTXYZ's [suggestion](https://github.com/stackblitz/core/issues/760#issuecomment-526950323) of changing/reconfirming your primary email on Github to something different? If you use Gmail you can add a period somewhere in your email to make it unique. Let us know if that fixes the issue for you. We'll work on improving the error message for this.

Indeed that did the trick. thanks :)

**Comment by David-Ben-Mesecke** [comment]
That said, it's still a bug that needs fixing.

**Comment by projer** [comment]
> Hey all- this error typically happens when you don't have a confirmed email address in Github. You can ensure your email address is verified on Github's email settings page: https://github.com/settings/emails
> 
> On our end, we need to add a better error message for this. I've put it on our internal tracker and should have a fix out soon.
> 
> If anyone is hitting this error and has verified they have a confirmed email address in Github, please comment and lmk so we can investigate! 🙏

I have a 2 confirmed email address on GitHub, I tried with both of them as primary address, still have the same message. It's been almost 1 year I can't connect to Stackblitz.

Still "Failed to load resource: the server responded with a status of 422 ()"
![2020-04-16_16h50_53](https://user-images.githubusercontent.com/52035857/79471100-746fdf00-8002-11ea-8be6-bccac36de4e5.jpg)

**Comment by CarlosResendiz** [comment]
I have the same issue, my emai is already verified.

**Comment by CarlosResendiz** [comment]
@mediplex have you solved your issue?

**Comment by mediplex** [comment]
@CarlosResendiz no it's not solved yet!

**Comment by wcroteau** [comment]
Same issue here...

Changing, adding primary email address didn't solve the issue (all addresses are verified).

Note that it's failing on Chrome (in my case v84.0.4147.105) however it DOES work using Edge - clearly this isn't an email/verification problem it's a browser issue of some kind.

**Comment by wcroteau** [comment]
> Same issue here...
> 
> Changing, adding primary email address didn't solve the issue (all addresses are verified).
> 
> Note that it's failing on Chrome (in my case v84.0.4147.105) however it DOES work using Edge - clearly this isn't an email/verification problem it's a browser issue of some kind.

D'oh! 😊 

This turned out to be my anti-virus' "Anti-Tracker" (I'm using BitDefender) that was blocking tracking cookies...

**Comment by sswartzl** [comment]
The fix from @wcroteau worked for me. Paused BitDefender's anti-tracker on stackblitz and then the login worked fine.

**Comment by mediplex** [comment]
I tried different browser with all kind of workarounds but I'm still having the same issue since 2years+ 🤪

**Comment by maverick-coder** [comment]
+1 here

**Comment by StasUshomirsky** [comment]
Still having the same issue. Turned off Malwarebytes and AdBlock. Changed email. Email is verified in GitHub. Tried Chrome and Microsoft Edge. Still have the same issue.
Windows 10.0.18363 (64 bit)
Chrome 88.0.4324.150

**Comment by EricSimons** [comment]
Thanks for the info y’all. Will have our team take a look on Monday and see if something is up.

**Comment by Find-Me-Ariadne** [comment]
I really hope the issue will get fixed as I have tried multiple of the solutions listed above and nothing seems to work.

**Comment by StasUshomirsky** [comment]
I didn't do anything, but just tried again to login today and it worked!

**Comment by mediplex** [comment]
> I didn't do anything, but just tried again to login today and it worked!

I tried it again but I'm not that lucky 😅

**Comment by krzyhan** [comment]
Me neither :(

**Comment by kc0tlh** [comment]
**Update on this issue as of 3/23/2022**

There are at least 3 known causes of the Github Auth Login Issue:

1. You may not have a confirmed email address in Github. You can ensure your email address is verified on Github's email settings page to resolve this issue:​ https://github.com/settings/emails

2. You have changed your Github username or email address since you last logged into StackBlitz, causing a collision in our database. 

3. You have two separate GitHub accounts with an overlapping email address and/or username. 

If you are in situation 2 or 3, a temporary workaround is to change the email address and/or username of the Github account that you would like to log into StackBlitz with to resolve the collision in our database. 

Tip: If you don't want to change your actual Github email address, you can instead update it to have a +github added to the end, so it is unique. For example [alex@gmail.com](mailto:alex@gmail.com) can be entered into github as [alex+github@gmail.com](mailto:alex+github@gmail.com) and all email will still flow to the existing "alex" Gmail account.

Hopefully this temporary workaround resolves the issue for you. If not, please open a new issue with as much details about your Github username and email address history (what was it before, what is it now, etc) and we will take a look!

We are working internally to resolve this issue in a more permanent and clean way. For additional context and to track progress, please follow Github issue #1402.

**Comment by mediplex** [comment]
> **Update on this issue as of 3/23/2022**
> 
> There are at least 3 known causes of the Github Auth Login Issue:
> 
> 1. You may not have a confirmed email address in Github. You can ensure your email address is verified on Github's email settings page to resolve this issue:​ https://github.com/settings/emails
> 2. You have changed your Github username or email address since you last logged into StackBlitz, causing a collision in our database.
> 3. You have two separate GitHub accounts with an overlapping email address and/or username.
> 
> If you are in situation 2 or 3, a temporary workaround is to change the email address and/or username of the Github account that you would like to log into StackBlitz with to resolve the collision in our database.
> 
> Tip: If you don't want to change your actual Github email address, you can instead update it to have a +github added to the end, so it is unique. For example [alex@gmail.com](mailto:alex@gmail.com) can be entered into github as [alex+github@gmail.com](mailto:alex+github@gmail.com) and all email will still flow to the existing "alex" Gmail account.
> 
> Hopefully this temporary workaround resolves the issue for you. If not, please open a new issue with as much details about your Github username and email address history (what was it before, what is it now, etc) and we will take a look!
> 
> We are working internally to resolve this issue in a more permanent and clean way. For additional context and to track progress, please follow Github issue #1402.

Now it's working perfectly.
No walk around needed.

Thanks for the interaction
