### ISSUE TITLE
Not able to run Parcel.js on Stackblitz when entry file is in subfolder

### ISSUE THREAD

**Issue by abhiomkar** [stackblitz/core#762]
**Steps to reproduce:**

Open this demo project - https://stackblitz.com/edit/parcel-demo - contains `index.html` (entry file) and `index.js` JS resource inside `./src` folder.

**Expected result:**

It should bundle javascript and render the content inside index.html.

**Actual result:**

Preview shows - `Can't find package: ""`

![image](https://user-images.githubusercontent.com/47312/47756827-09014880-dc7a-11e8-8095-e979b93e9369.png)

Works fine when `index.html` and `index.js` files are stored at root folder.

What is the recommended way to debug these issues in Stackblitz?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are seeing different errors on your project link (can't find files). If your issue persists after importing the correct files, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

<img width="1137" alt="Screen Shot 2021-04-27 at 11 34 53 PM" src="https://user-images.githubusercontent.com/49956513/116342780-2e229380-a7b1-11eb-82f5-4086e022bc6f.png">
