### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by steve-reichbach** [stackblitz/core#765]
https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/projects/component-nest/?bust=1541104325918

**Comment by tiliev** [comment]
@steve-reichbach, this is the correct link - https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/projects/component-next/. Please log these issues in the repository from this course - https://github.com/johnpapa/angular-first-look-examples/issues.
