### ISSUE TITLE
Email Id issue while signup with stackblitz

### ISSUE THREAD

**Issue by armanavasthi** [stackblitz/core#766]
I have my email id varified with github since ling back. Still Stackblitz is not allowing me to signup. 

![image](https://user-images.githubusercontent.com/22725456/47901256-6fb67a00-dea5-11e8-81de-ed6e92fccb5d.png)

**Comment by sivatumma** [comment]
I too have the same issue: 
![image](https://user-images.githubusercontent.com/3370418/61690803-cd4a6980-ad47-11e9-896f-fe25d26111ca.png)

**Comment by sivatumma** [comment]
I found the solution. There are multiple emails in my github's **settings > email**. I have set a primary email of an old project but that now no longer active. I switched back to my current **verified** email now this works like charm

**Comment by armanavasthi** [comment]
yes it worked!!! Thanks
