### ISSUE TITLE
CORS error loading @angular/elements

### ISSUE THREAD

**Issue by emilio-martinez** [stackblitz/core#769]
I'm not getting this issue with the rest of the Angular packages—specifically for `@angular/elements`. Upon installing it hits a CORS issue which stops the application from loading, i.e., stuck in spinner in corner or "Starting dev server".

<img width="703" alt="screenshot 2018-11-03 09 57 15" src="https://user-images.githubusercontent.com/9163179/47955015-efe4ea00-df4e-11e8-9c79-13490f5460d9.png">

### Things I've tried

- Removing the package. Moves on from the "starting" phase of the app, but of couse, stops because the `@angular/elements` isn't available.
- Installing via entering in the Dependencies input or pressing the "Install X" button results in the same.
- Clearing the app storage and cache, including SW. No change other than getting signed out.

**Comment by apai4** [comment]
@emilio-martinez I think this may have been related to https://github.com/stackblitz/core/issues/768 which should be resolved now. Are you still having this issue?

**Comment by emilio-martinez** [comment]
Nope, I think this is resolved now. Thank you!
