### ISSUE TITLE
Angular 4

### ISSUE THREAD

**Issue by yybarham** [stackblitz/core#77]
Is it possible to add file from a desktop to my project?
Generally if it's text I can copy and paste
but what about Images ?

**Comment by cgatian** [comment]
I believe you need to link it though a public host/CDN

**Comment by MarcelMalik** [comment]
You can simple move files via drag & drop from your desktop into the file tree in StackBlitz.

**Comment by aat-antoine** [comment]
Everything has been said, if you need to add files from desktop to your project : drag & drop. For the images, follow this issue https://github.com/stackblitz/core/issues/72

Feel free to close issue if you found yours answers :)
