### ISSUE TITLE
ionic 4 : ion-icon not showing

### ISSUE THREAD

**Issue by auriou** [stackblitz/core#770]
we do not have icons on ionic projects 4
as for example in the menus.

https://stackblitz.com/edit/github-igwscn?file=src%2Fapp%2Fapp.component.html

issue on ionic  https://github.com/ionic-team/ionic/issues/15456 
but the problem is not ionic, but on stackblitz
like this must be an external resource ?

````
<ion-icon slot="start" [name]="p.icon"></ion-icon>
````
![image](https://user-images.githubusercontent.com/1873587/47959147-0fc2ef00-dfdd-11e8-8e63-b6e136717d0c.png)

thx

**Comment by purplem1lk** [comment]
Thank you for your patience - I'm not seeing any errors in my Network tab. It's possible that code changes during this time have resolved the issue that you were previously experiencing. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)


<img width="1440" alt="Screen Shot 2021-04-27 at 11 42 08 PM" src="https://user-images.githubusercontent.com/49956513/116343311-30392200-a7b2-11eb-89f4-2ec8f1768c53.png">
