### ISSUE TITLE
github import error

### ISSUE THREAD

**Issue by teslaji** [stackblitz/core#771]
I am not able to import github project to stackblitz using 
`stackblitz.com/{github_user}/{project_name}`

Here is the link: https://stackblitz.com/github/teslaji/mean-starter-kit

**Comment by schuchard** [comment]
`https://stackblitz.com/github/{github_user}/{project_name}`

**Comment by teslaji** [comment]
@schuchard I am trying to import with this link.
https://stackblitz.com/github/teslaji/mean-starter-kit

but still receiving error

> Something went wrong with this repository.
> 
> If you think this is a bug, please file an issue in our repo!

**Comment by schuchard** [comment]
sorry not sure what to do from there. I can vouch that it runs fine locally though.

**Comment by teslaji** [comment]
@EricSimons can you look into this issue or delegate someone who can look into this error. Thanks

**Comment by apai4** [comment]
@teslaji Sorry about this! Looks like this is happening because there's too many files to download in this repo, probably due to a `node_modules` folder being included in the repo: https://github.com/teslaji/mean-starter-kit/tree/master/server

Adding that folder to .gitignore may fix this issue. We'll work on showing a better error message for when this happens!

**Comment by purplem1lk** [comment]
> @teslaji Sorry about this! Looks like this is happening because there's too many files to download in this repo, probably due to a `node_modules` folder being included in the repo: [https://github.com/teslaji/mean-starter-kit/tree/master/server](https://github.com/teslaji/mean-starter-kit/tree/master/server?rgh-link-date=2018-11-16T18%3A19%3A54Z)
> 
> Adding that folder to .gitignore may fix this issue. We'll work on showing a better error message for when this happens!

This issue has been resolved and will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
