### ISSUE TITLE
Error Fork github import

### ISSUE THREAD

**Issue by TheILPlace** [stackblitz/core#776]
here is the scenario.
open am angular-cli sample project from github via stackblitz.
change one space.
press FORK.
you get a warning about changes wont be saved. press CANCEL
now the "fork" button as a spinner running, and you are done. 
you can continue to work and run the app. but cannot fork it. using the url in the "share" option, gives an error.
so you can run the code, but not save it anymore.

**Comment by tiagomsmagalhaes** [comment]
Also happened to me

**Comment by anddam** [comment]
The "workaround" is to fork as first thing, then saving will work as expected.
Personally I keep forgetting this and stumbling on this issue.

**Comment by purplem1lk** [comment]
> The "workaround" is to fork as first thing, then saving will work as expected.

Thank you for your patience - The resolution above is what we recommend with the current app so this issue will be closed accordingly. If an issue persists, feel free to tag me or ask to reopen this issue with a working project link and screenshots of the error. Thank you! :)
