### ISSUE TITLE
Underscores in project name causes "Name taken - try another"

### ISSUE THREAD

**Issue by ChrisJohns-me** [stackblitz/core#779]
When trying to rename a project to anything with an underscore, it incorrectly reports that the name is "taken".

![image](https://user-images.githubusercontent.com/9357528/48150450-f390ad80-e27b-11e8-99a4-52f50e110865.png)

**Comment by tawani** [comment]
Yes. This still happens and still no response?

**Comment by ardenne21** [comment]
I was about to report the same thing and ended here. This is still a problem.
