### ISSUE TITLE
vm.applyFsDiff fails to work on a angular project

### ISSUE THREAD

**Issue by beadarsh** [stackblitz/core#780]
Issue:

I have attached a stackblitz project which attempts to apply a batch update to a angular project by updating a file and adding a new one using vm.applyFsDiff.

[https://stackblitz.com/edit/angular-7-master](Project link attached)

This fails with the following error:
webcontainer.98cdf1bef4a967f01d9.js:8 Uncaught (in promise) Error: Error: ENOTEMPTY: Directory is not empty., '/~'

I can confirm this was working before with a Angular 5 project. Am i missing anything obvious?

Expected result: I would have expected the project to be updated and refreshed dynamically but instead fails with the above error

**Comment by demiro** [comment]
this is the error I am getting though

`client-d2514f6dd8e7522dd9afb.js:1 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at Object.SDK_APPLY_FS_DIFF (client-d2514f6dd8e7522dd9afb.js:1)
    at client-d2514f6dd8e7522dd9afb.js:1
    at Array.map (<anonymous>)
    at Object.dispatch (client-d2514f6dd8e7522dd9afb.js:1)
    at client-d2514f6dd8e7522dd9afb.js:1
    at MessagePort.e.onmessage (client-d2514f6dd8e7522dd9afb.js:1)`

**Comment by lamanabie** [comment]
I find out that u can fix this error by providing destory: [] to applyFsDiff

```
vm.applyFsDiff({
  create: {
    'index.ts': `console.log('hello');`,
  },
  destroy: [],
});
```

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
