### ISSUE TITLE
Saving uploaded jpg| png images throw 500 PATCH error

### ISSUE THREAD

**Issue by yduartep** [stackblitz/core#782]
I am trying to upload some **jpg**| **png** images, but everytime I save the project I receive the following error in the Google Console: 

PATCH https://stackblitz.com/api/projects/date-range-picker 500

Instead, If I try to upload .svg files, the save project is working correctly.

**Comment by miltonhowe** [comment]
Thank you, reading this issue solved my problem :) My entire project would not save, until I removed the binary files (`.png`, `.jpg`).

As a workaround, I replaced my images with DataURLs as suggested [here in issue #72](https://github.com/stackblitz/core/issues/72#issuecomment-398748498)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
