### ISSUE TITLE
react-auth0 tokenStorage object uses wrong this

### ISSUE THREAD

**Issue by Nilegfx** [stackblitz/core#783]
This was my first experience with your awesome service, however, after configuring Auth0, `react-auth0` project template doesn't seem to work because of the following part: 

```js
const tokenStorage = {
  tokens: {},
  setItem: (key, value) => this.token[key] = value,
  getItem: (key) => this.token[key],
  removeItem: (key) => this.token[key] = undefined
};
```
it has two obvious errors: 

- wrong `this` pointer in the final transpiled code (didn't have time to invistgate why or how do you setup your transpilers)
- it should be `this.tokens` not `this.token`

so I "hacked" it like that and it worked fine.

```js
const tokenStorage = {
  tokens: {},
  setItem: (key, value) => tokenStorage.tokens[key] = value,
  getItem: (key) => tokenStorage.tokens[key],
  removeItem: (key) => tokenStorage.tokens[key] = undefined
};
```

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with a working project link and screenshots of the error. Thank you! :)
