### ISSUE TITLE
grid-template-columns and named grid areas

### ISSUE THREAD

**Issue by BenRacicot** [stackblitz/core#786]
There seems to be an issue with ` grid-template-columns` and named grid areas.
```
    app-list{
        display: grid;
        grid-column-gap: 1.5vw;
        grid-template-columns:
        "[full-start]" // string interpolation
            minmax(calc(calc(100% - 1440px) / 2), 1fr)
            "[main-start]"
                repeat(14, "[col-start]" 1fr)
            "[main-end]"
            minmax(calc(calc(100% - 1440px) / 2), 1fr)
            "[full-end]";
```
The quotes makes SB not error, however the browser sees this as invalid syntax.

**Comment by wnodom** [comment]
I believe this has been fixed. I was having a similar issue with named grid lines in a `grid-template` rule a few weeks back, but I just checked again and it seems to be working now.

**Comment by purplem1lk** [comment]
Thank you for your patience - It's possible that various code changes have resolved this issue so you should be able to use grid-template accordingly. f this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
