### ISSUE TITLE
Angular project - "Import error, can't find file: /index.html"

### ISSUE THREAD

**Issue by rodrake1** [stackblitz/core#789]
```
Import error, can't find file:
index.html
```

This file is in src folder, looks like application tries to find it in root folder.

This is the stackblitz url: https://stackblitz.com/github/rodrake1/angular-portfolio/tree/master/course-project

**Comment by varnastadeus** [comment]
I have same issue:
try to open - https://stackblitz.com/github/ng-select/ng-select/tree/master

Error:
```
Import error, can't find files:
/index.html
/src/main.ts
```

even though the default project path is `src/demo`

**Comment by sivajisanapala** [comment]
Hi,

I am new to Stackblitz. Hope i have the similar problem.
![Capture](https://user-images.githubusercontent.com/20138121/63668170-f4d39c80-c7f3-11e9-8b1d-c1dc2a37cab7.PNG)
 While working on angular newly created html is not getting committed. Am i missing some where please help.

**Comment by tim1016** [comment]
Same problem with ionic project 
```
Import error, can't find files:
/index.html
/app/polyfills.ts
/app/main.ts
```

**Comment by Asheq096** [comment]
The Stackblitz docs say when importing projects, create a new JS project; however, when importing Angular applications, you should create an Angular Project instead and it will run fine.

**Comment by kc0tlh** [comment]
This issue is resolved by using [our new VS Code editor](stackblitz.com/codeflow)!
