### ISSUE TITLE
File type icons

### ISSUE THREAD

**Issue by RonnyO** [stackblitz/core#79]
Could be awesome to have icons associated with all kinds of file types, i.e. https://marketplace.visualstudio.com/items?itemName=qinjia.seti-icons

Really helps with big projects / folders with mixed contents.

**Comment by EricSimons** [comment]
@RonnyO I just shipped a brand new icon set to the site — would love to hear your feedback!

**Comment by David-Klemenc** [comment]
@EricSimons Which file icon theme are you using? (I'd like to set the same theme in my vsc) (I really want the router icon)

**Comment by polypus74** [comment]
@EricSimmons Came here looking for same answer as @David-Klemenc. Can we use that nice clean icon set with funky router icon in vscode ourselves? Is it available anywhere?

**Comment by EricSimons** [comment]
That icon pack is vscode material icons FYI! :)

**Comment by David-Klemenc** [comment]
Thank you @EricSimons  -  If anyone is wondering - you can get the Routing icon like this:

open settings.json and add:
`"material-icon-theme.files.associations": {
        "app-routing.module.ts": "Routing"
}`

P.S.
I don't know if writing a glob or something like `*routing.module.ts` is currently possible !?
