### ISSUE TITLE
Cant receive message messages from embedded iframe

### ISSUE THREAD

**Issue by msqaddura** [stackblitz/core#790]
I am trying to send a message from my angular app (without stackblitz) to an embed iframe (stackblitz) 
i can receive a message from the embedded, but i cant send on from the embedded iframe.
1) i cant call window.parent
2) i tried with the rdc but nothing would help

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We are launching new core technology into beta this month that should resolve this issue. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
