### ISSUE TITLE
Access embedded Monaco instance.

### ISSUE THREAD

**Issue by cherryApp** [stackblitz/core#791]
I can access the embedded Monaco instance?
When I create a new project, I give the vm instance.
I want to access the Microsoft Monaco instance, which runs in vm.
Or are there any other options, that I change editor value programmatically?

```
// Embed this project
window['embedNewProject'] = () => {

  sdk.embedProject('myDiv', project, {
    openFile: 'index.html'
  })
  // Get the VM of the embedded instance
  .then(vm => {
    // Wait 2 seconds...
    setTimeout(()=> {
      // Then update the VM's file system :)
      vm.applyFsDiff({
        create: {
          'index.html': `<h1>This was updated programmatically!</h1>`
        },
        destroy: ['randomFile.ts']
      });
    }, 2000)
  });

}
```

**Comment by cherryApp** [comment]
I want to send messages directly to Monaco.
I'm a teacher and I have a web-based application.  This application is able to replay a coding path.
Because I want to send several commands to Monaco, that Monaco changes it's content when I send a message to it.
The Stackblitz VM API able to change whole content, but this not necessary me.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. We recommend reaching out to the Monaco team if you are still having trouble, as well. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
