### ISSUE TITLE
Project not working

### ISSUE THREAD

**Issue by GurpreetSandhar** [stackblitz/core#792]
Hi,
My project on Angular 6 is not working.
https://stackblitz.com/github/GurpreetSandhar/Practice-Project
And also i have same problem with another projects also.

**Comment by tiliev** [comment]
@GurpreetSandhar, to correctly import a project from GitHub in StackBlitz, you should use a folder with `package.json` file in it. In your case [this ](https://github.com/GurpreetSandhar/Practice-Project/tree/master/component)is the correct folder. And this is the import link - https://stackblitz.com/github/GurpreetSandhar/Practice-Project/tree/master/component. The project throws an error, I guess it is the same bug Albert Pai is mentioning in his comment - https://github.com/stackblitz/core/issues/724#issuecomment-429473774.

**Comment by purplem1lk** [comment]
Thank you for your patience - This issue has been resolved by the final response in #724. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
