### ISSUE TITLE
couldn't open https://stackblitz.com/github/anvlkv/reproduce-stimulsoft

### ISSUE THREAD

**Issue by anvlkv** [stackblitz/core#793]

**Comment by purplem1lk** [comment]
<img width="1440" alt="Screen Shot 2021-05-04 at 1 42 49 PM" src="https://user-images.githubusercontent.com/49956513/117046377-a07a0300-acde-11eb-9505-74f1a02a9cb3.png">

Thank you for your patience - At this time, your project ink is giving the error screenshot above. We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
