### ISSUE TITLE
Font settings are not getting saved in the editor

### ISSUE THREAD

**Issue by Harshdand** [stackblitz/core#795]
Every time I open the project font settings are reset and I see default font size. I tried font zoom in but found that it doesn't save the font settings.

**Comment by mastergnus** [comment]
This happen to me too, is there any solution?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
