### ISSUE TITLE
Error: Can't find file ./App.vue

### ISSUE THREAD

**Issue by wwwizzarrdry** [stackblitz/core#796]
**index.js**
![image](https://user-images.githubusercontent.com/2218144/48964578-b8041c00-efbb-11e8-8c60-936b700634ae.png)

**App.vue**
![image](https://user-images.githubusercontent.com/2218144/48964570-84c18d00-efbb-11e8-9729-649eddfb606a.png)

**package.json**
![image](https://user-images.githubusercontent.com/2218144/48964584-d9fd9e80-efbb-11e8-8a11-9b86b289e53f.png)

**Comment by lazarljubenovic** [comment]
Try importing from `./App`, not `./App.vue`.

**Comment by zy308718320** [comment]
Need to add Vue 2 project template.

**Comment by purplem1lk** [comment]
> Try importing from `./App`, not `./App.vue`.

Thank you for your patience - We recommend trying this option and running your project. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
