### ISSUE TITLE
it's Awesome tool

### ISSUE THREAD

**Issue by Genuine-Identity** [stackblitz/core#797]
it's Awesome tool

**Comment by hangcs** [comment]
with too many bugs, I guess they are busy with doing talks instead of fixing bugs

**Comment by EricSimons** [comment]
@hangcs what bugs are you running into?

**Comment by Genuine-Identity** [comment]
> with too many bugs, I guess they are busy with doing talks instead of fixing bugs

**Comment by Genuine-Identity** [comment]
@hangcs - It is really a great tool. I am able to develop demo project online... https://adminlte-angular.stackblitz.io/user/login

**Comment by tiliev** [comment]
@Genuine-Identity, everything appears to be working in your project and it looks awesome.
Please reopen the issue if you experience any issues or bugs and provide detailed information.
