### ISSUE TITLE
Hot reload trigger always behaves as "Edit (auto)" if editor is refreshed

### ISSUE THREAD

**Issue by sebpearce** [stackblitz/core#799]
I'm on Chrome 70.0.3538.102.

- I have the preview open in a separate window
- I change the hot reload trigger to "Save"
- The preview updates on save as expected
- I refresh the editor page
- Now the preview updates on every edit, instead of respecting the "save" setting
- Refreshing the preview window does not change this, nor does changing the hot reload trigger setting back to "Edit (auto)" and "save" again.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
