### ISSUE TITLE
Support JSX pragmas in tsconfig.json

### ISSUE THREAD

**Issue by yelouafi** [stackblitz/core#8]
Amazing project!

Would be cool to have a general ES6/babel template like in https://codesandbox.io. This is especially useful for using JSX with other virtual dom libs like preact. I tried the `/* @jsx h */` at the top of the module (with the react template) but it doesn't work. Actual workaround is to redefine React.createElement but I think supporting a more general ES6/babel env out of the box is a game changer.

**Comment by EricSimons** [comment]
Great point! We're actually planning on allowing you to edit the tsconfig (which allows you to override the JSX pragma) — would that be a reasonable fix for you? Or is ES/Babel style a dealbreaker?

**Comment by yelouafi** [comment]
that would be great of course. I can create create a React project then customize it by overriding the JSX pragma & installing the required packages. I'm not sure however about adding Babel features (e.g. one wants to try lastest EC proposals, or install app specific Babel plugins). [create-react-app choices](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#supported-language-features-and-polyfills) are rather opinionated (for good reasons) and restricted.

Another option is to add the possibility to eject from the CRA template

**Comment by gibbok** [comment]
First of all, thanks for stackblitz, it is really cool tool!

Would be great if you can allow to configure the `tsconfig.json` directly like codesandbox.

...meanwhile do you have any workaround if I want to compile typescript using es2017?

**Comment by mjyc** [comment]
Another thanks for building Stackblitz and would love to see this feature implemented.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
