### ISSUE TITLE
hideExplorer flag is not working in sdk

### ISSUE THREAD

**Issue by ashwiniagre1** [stackblitz/core#800]
sdk
      .embedProject(this.elementId, project, {
        height: window.innerHeight - 180,
        hideDevTools: true,
       embed:true,
        hideExplorer:true,
        view: 'preview'
      })

**Comment by vesivagu** [comment]
any workarounds are there?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
