### ISSUE TITLE
Backspace is not working on mobile devices

### ISSUE THREAD

**Issue by shaaafi** [stackblitz/core#801]
The backspace is not working in mobile.

**Comment by sajidali** [comment]
On my mobile, it ia working. Please provide more info.

**Comment by maeqlin** [comment]
Not working either tested on android 9

**Comment by chevyfollowtooclose** [comment]
Backspace not working on pixel 2xl Android 10, gboard

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
