### ISSUE TITLE
Spread syntax works unexpectedly with String

### ISSUE THREAD

**Issue by Wunderwegner** [stackblitz/core#802]
Using a spread operator as shown below should explode a string into an array. However, it seems to be doing nothing (leaving the string as it is).

```js

// Browser console
const sampleString = 'Lorem';
console.log([...sampleString]);

// console: ['L', 'o', 'r', 'e', 'm']

// StackBlitz
const sampleString = 'Lorem';
console.log([...sampleString]);

// console: 'Lorem'
```

**Comment by sulco** [comment]
Thanks @Wunderwegner for reporting the issue!

Yeah, that was pretty confusing.. 
Thankfully, it's no longer an issue :)
