### ISSUE TITLE
Tensorflowjs typescript support

### ISSUE THREAD

**Issue by mohammedzamakhan** [stackblitz/core#804]
Tensorflow is written in typescript, but I do not get the typing support in the stackblitz

https://stackblitz.com/edit/typescript-nieyg2?file=index.ts

In this example, layers throws a typescript error, but if you see, it actually has a value to it.

It works fine in the local typescript environment

**Comment by kc0tlh** [comment]
Closing this as a duplicate of #711. Follow there for future updates!
