### ISSUE TITLE
Failed to decode downloaded font: <url>

### ISSUE THREAD

**Issue by benshabatnoam** [stackblitz/core#806]
When using a npm package that includes a font, I'm getting a warning 'Failed to decode downloaded font: <url?', and the font is not displaying.
When I download the [project](https://stackblitz.com/edit/changing-the-template-of-primeng-paginator?file=src%2Fapp%2Fapp.module.ts) and run it everything works.

**Comment by philip-sultanescu** [comment]
Same problem here

**Comment by purplem1lk** [comment]
Thank you for your patience - This is the current error I'm seeing from your project. We are unable to provide assistance, as we are seeing something different and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a description and screenshots of the error. Thank you! :)

<img width="1440" alt="Screen Shot 2021-05-04 at 2 03 30 PM" src="https://user-images.githubusercontent.com/49956513/117048910-8392ff00-ace1-11eb-9317-6bdc7bc35b2e.png">
