### ISSUE TITLE
Can't find package:@angular/common

### ISSUE THREAD

**Issue by relair** [stackblitz/core#807]
See https://stackblitz.com/edit/angular-dqzwpy
Angular common is already in dependencies but even after clicking install dependencies the error doesn't go away.
After some fiddling I found out it was 
import localeEnGb from '@angular/common/locales/en-Gb';
specifically causing the issue.
Why cannot I import locales? Why Is it showing a confusing error like that, which cannot be resolved?
It seems like a bug one way or another to me, hence this issue.

**Comment by purplem1lk** [comment]
This issue has been resolved by the user and will be closed accordingly. We are adding to our roadmap to provide more explicit error message handling so thank you for your suggestion!  We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
