### ISSUE TITLE
MERN stack live projects are not supported to code, it only supports frontend frameworks but not fullstack like ExpressJS with ReactJS.

### ISSUE THREAD

**Issue by ganesh-deshmukh** [stackblitz/core#808]
I tried opening this MERN stack project, but error thrown was "we currently don't support this platform."

[my-project](https://github.com/ganesh-deshmukh/connect-geeks)

**Comment by purplem1lk** [comment]
Thank you for your patience - Whenever platforms are not yet supported, we like to provide that error message so users can check our soon-to-come roadmap that will be available to the community to see what features are being worked on. We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

**Comment by ganesh-deshmukh** [comment]
Ok thanks for the update.
