### ISSUE TITLE
Can't load dependency from cloudflare anymore.

### ISSUE THREAD

**Issue by JoshuaHD** [stackblitz/core#809]
Before one of the last updates it was possible to load dependencies from Cloudflare. Now the input box for the URL is removed and when i enter the URL into the available textbox i get, not surprisingly, an error message that this is not an existing npm package.

How can i load external files now?

**Comment by JoshuaHD** [comment]
Currently i'm working around this way:
`
var head = document.getElementsByTagName("head")[0],
    cssLink = document.createElement("link");

cssLink.href = "https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.css";
cssLink.id="dynamic-css";
cssLink.rel="stylesheet";
cssLink.type="text/css";

head.appendChild(cssLink);
`

This works but is not as nice as having the link staticly in the head

**Comment by lifeinchords** [comment]
The strange part is that for projects I find by googling, the CDN / minified scripts display underneath the form field. I can only delete them, but not add them back. 

Example: https://stackblitz.com/edit/box2d
<img width="496" alt="Screen Shot 2019-03-25 at 10 38 17 PM" src="https://user-images.githubusercontent.com/716168/54967798-de789a80-4f4e-11e9-92de-d46e8357a245.png">

Am I missing something?

**Comment by JoshuaHD** [comment]
Just a guess, check if you can remove them by editing your package.json

**Comment by kbrehm0** [comment]
I can delete the entries under the field `dat.gui.min.js` etc.
I can't add new ones that are links to URLs and that are not npm packages

**Comment by abhilash1in** [comment]
I think that feature no longer exists.

**Comment by kc0tlh** [comment]
_Tagging related issues #823 #1195_

**Comment by HeyGarrison** [comment]
Just to jump in here... We shipped Private NPM support! You can read more on the docs here: https://developer.stackblitz.com/teams/private-npm-registry-integration#frontmatter-title
