### ISSUE TITLE
User Dashboard: Show latest projects

### ISSUE THREAD

**Issue by mdrobynin** [stackblitz/core#81]
It would be nice to see my latest projects directly at homepage

**Comment by mikegoodstadt** [comment]
- [x] The current Dashboard shows the latest projects.

**Comment by purplem1lk** [comment]
The current dashboard displays the latest projects (screenshot below). Thank you for your comment @mikegoodstadt! This issue will be closed accordingly.

<img width="1440" alt="Screen Shot 2021-04-22 at 7 55 10 PM" src="https://user-images.githubusercontent.com/49956513/115798622-aa2d6d80-a3a4-11eb-958b-e2eaac15cf0c.png">
