### ISSUE TITLE
Can't download project unless src/index.html is present

### ISSUE THREAD

**Issue by jeffhuys** [stackblitz/core#811]
I was trying to download this project: https://stackblitz.com/edit/github-co7ycb

When I clicked on the download button at the top, in my console it gave me `Error: File src/index.html does not exist!`
After I created `src/index.html` with something like `asdsad` and saved it, the download worked.

Not a *big* problem, as most projects have an `src/index.html`, but might be a small fix?

**Comment by HoseinGhanbari** [comment]
it's still exists and somehow annoying, [2020-02-20]
