### ISSUE TITLE
Exporting Angular sample does not work correctly

### ISSUE THREAD

**Issue by janunezc** [stackblitz/core#814]
https://stackblitz.com/angular/qmvvgllkned?file=index.html

I downloaded the project, did npm install and ng serve --open

It plain doesnt work.

In the Internet there are comments around missing "ghost" dependencies to ReactiveForms and things....

What I'd think about the whole npm ecosystem is that projects "as simple as this" are able to proper define and handle their dependencies.

**Comment by tiliev** [comment]
@janunezc, the exporting seems to not work properly with projects with the old Angular structure. Please refer the styles in `angular.json` to run the exported sample correctly:
```
"styles": [
    "src/styles.css"
]
```
Marking this as a bug.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
