### ISSUE TITLE
editor code format configs support wanted

### ISSUE THREAD

**Issue by xgqfrms** [stackblitz/core#816]
# editor code format configs support wanted

> can't set editor format rules

![image](https://user-images.githubusercontent.com/7291672/49414538-b9e59080-f7ae-11e8-9490-8bb942c0a1e4.png)

> wanted vs-code config

![image](https://user-images.githubusercontent.com/7291672/49414574-e1d4f400-f7ae-11e8-9618-212d09e930de.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
