### ISSUE TITLE
Nested Component

### ISSUE THREAD

**Issue by Taher80** [stackblitz/core#818]
Please fix the path to this link so we can understand well how nested component works , Thanks in advance

**Comment by tiliev** [comment]
@Taher80, which path do you mean? Please provide more information.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
