### ISSUE TITLE
server not responding

### ISSUE THREAD

**Issue by eben562012** [stackblitz/core#819]
after i have installed native ionic calendar dependency, and added some few lines of code to it, the server only shows starting dev server. this is what the feed i get when i run the code. i tried creating new project and with that if i try installing the dependency like an ionic native module. it runs for more than hours but as a result installs nothing. any help will be much appreciated.

**Comment by eben562012** [comment]
@ionic-native/core this is what keeps on running without installing. with @ionic-native/calendar am able to 
install but after installation the server runs(starting server) and never build component. i wish i could add snapshot but am using 
![image](https://user-images.githubusercontent.com/16543676/49585210-a58fc800-f955-11e8-854e-f1547fb4fcac.png)

**Comment by tiliev** [comment]
@eben562012, please share a StackBlitz URL of the sample so we could further investigate.

**Comment by apai4** [comment]
@eben562012 @EricSimons I just pushed a fix for the error that was happening container side so now the proper error should be shown

**Comment by eben562012** [comment]
how to do access the fix that you pushed or i should run the old project
which will the display the error that is keeping the server from not running

**Comment by ctoveloz** [comment]
> @ionic-native/core this is what keeps on running without installing. with @ionic-native/calendar am able to
> install but after installation the server runs(starting server) and never build component. i wish i could add snapshot but am using
> ![image](https://user-images.githubusercontent.com/16543676/49585210-a58fc800-f955-11e8-854e-f1547fb4fcac.png)

I have the same error when start a new project in 
Auth0 (React)
React

**Comment by purplem1lk** [comment]
Thank you for your patience - In addition to the fix that was pushed, we are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
