### ISSUE TITLE
Fresh create-react-app imported from Github can't start dev server

### ISSUE THREAD

**Issue by juraju-kentico** [stackblitz/core#820]
Hello everyone,

According to https://stackblitz.com/docs#upload-from-your-computer Stackblitz supports `create-react-app` projects. 

However, when I generate a fresh new CRA project, push it to Github, then try to import it to Stackblitz, the dev server is loading forever and I get the following errors in the console: 

https://stackblitz.com/github/juraju-kentico/cra

![image](https://user-images.githubusercontent.com/25588393/49589801-9a936280-f96a-11e8-9715-ebaf4eb1339d.png)

Any ideas what's going wrong and how to fix it? Thank you!

**Comment by whawker** [comment]
I have the same issue on my CRA project, with similar CORS errors.

https://stackblitz.com/github/whawker/react-jsx-highcharts-examples
