### ISSUE TITLE
share with console open

### ISSUE THREAD

**Issue by moshfeu** [stackblitz/core#826]
Let the user to check an option in the share popup so the console will be open by default.

Something like this:

![screenshot](https://user-images.githubusercontent.com/3723951/50362437-6d50d200-0570-11e9-8774-74cc89ff931e.png)

Thanks!

**Comment by sulco** [comment]
Done! :D

![image](https://user-images.githubusercontent.com/1511906/114006854-16ff1e80-9861-11eb-84c7-57dd12a8e3bb.png)
