### ISSUE TITLE
Using options with angular generator?

### ISSUE THREAD

**Issue by VBartilucci** [stackblitz/core#829]
Trying to run through the Hall of Heroes tutorial.  Generating components, services, etc, all see fine when using the angular generator - select the type, enter the name.

But when getting to creating the routing files, the command to be entered is:

`ng generate module app-routing --flat --module=app`

So I opened up the generator, selected module, and tried entering "app-routing --flat --module=app" but the options were ignored - "app-routing" was created in a folder, and not in the root.

So (how) can I pass options to the generator?

**Comment by tiliev** [comment]
@VBartilucci, I think this is not StackBlitz related since you can execute vanilla Angular CLI commands.
