### ISSUE TITLE
Making error message output non-selectable is a mistake

### ISSUE THREAD

**Issue by janpio** [stackblitz/core#83]
Example error message:
![image](https://user-images.githubusercontent.com/183673/29280830-0940b826-811d-11e7-8d8c-78e3e51770aa.png)

I can not copy/paste that text to an issue here but have to make a screenshot that I then post. This will not get indexed by Google, other users can not copy parts of the error message to google it. I myself can't just google the error.

**Comment by EricSimons** [comment]
@janpio digging into this, and it turns out this is actually Ionic that's hijacking the click events for text selection for everything in the body 😮  I'll see what I can do about it though!

**Comment by janpio** [comment]
Haha, then I created an issue about this a looong time ago already... (looking for it now)
