### ISSUE TITLE
Add Magenta.js support

### ISSUE THREAD

**Issue by CarmenPopoviciu** [stackblitz/core#830]
# 🚀 feature request

#### Description
Add featured project for [Magenta.js](https://github.com/tensorflow/magenta-js)

After working with Magenta.js a couple of times I am frustrated with the fact that no online IDE out there offers a template to get you started out of the box. In fact, there seems to be no support anywhere for either Magenta.js or Tensorflow.js projects.

#### Proposed Solution
I would like to close this gap and create a project template on Stackblitz to get developers started more easily. I've created a Stackblitz [demo app](https://stackblitz.com/edit/magenta-demo) of how I imagine a Magenta.js music project could look like. 

I'm up for working and making a PR for this issue and I'd also be more than happy to open a dialog with the Magenta.js folks to perfect and adjust it based on their feedback, if you're interested in providing this kind of support

<3

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you for your suggestion! :)
