### ISSUE TITLE
Unable to install dependency

### ISSUE THREAD

**Issue by mani-96** [stackblitz/core#831]
Even with the correct version number, I'm getting the error

![image](https://user-images.githubusercontent.com/34791300/50723492-8e82f800-1104-11e9-9391-b8128685b4ad.png)

Though I can install the same version in my local.

**Comment by tiliev** [comment]
@mani-96, I was able to install `ngx-accordion-from-object@1.0.8` correctly. Does everything works on your side as well?

**Comment by mani-96** [comment]
Yes, it works well now! Thanks!
