### ISSUE TITLE
Is it possible to import angular material themes?

### ISSUE THREAD

**Issue by almeidaalex** [stackblitz/core#832]
Hello stackblitz Team, this tool is really awesome! So fast, great job you've being done.

I'm trying to run my very simple project with Angular Material hosted at Github, and I've imported my CSS theme file into style.css as below

```css
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';
```
So I've got a Error
`Error: ENOENT: No such file or directory., '/dev/null'`

It seams like the stackblitz canno't file such file to import

You could try https://stackblitz.com/github/almeidaalex/abank
 Thx!

**Comment by billdwhite** [comment]
same here

**Comment by rajibhalder** [comment]
Same issue with me also.

**Comment by schaveyt** [comment]
I am importing with the same syntax and it is working. What I have seen sometimes is that I have to fully close all my browser windows to have the project get restarted. Alternatively, sanity check your issue in another browser.

**Comment by FrancescoBorzi** [comment]
same issue here, using latest Angular version:

https://stackblitz.com/github/francescoborzi/ngx-duration-picker

**Comment by davidtlee** [comment]
I'm having the same issue

**Comment by umangchadha** [comment]
same issue!

**Comment by KaranPato** [comment]
I am also having the same issue.

**Comment by Bansi23** [comment]
I'm facing the same issue.

**Comment by russlamb** [comment]
put your theme import in the styles.css file

**Comment by livecopper** [comment]
perhaps https://github.com/PKief/angular-material-starter might help?

had the same error when I manually created from that starter.
Successfully when added "environments" folder under src and refresh browser.
hope this helps.

**Comment by huayunh** [comment]
We got similar issues here -- ended up fixing it by yarn adding a dependency of dependency into our package.json.

**Comment by benni94** [comment]
in my case rename the styles.css file to style.scss resolved it. 
also .angular-cli.json under app, styles the path with styles.scss

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with a working project link and screenshots of the error. Thank you! :)

**Comment by thw0rted** [comment]
@purplem1lk , it's been a month and I'm still having the issue.

1. I began with [the starter from the Angular Components bug report template](https://stackblitz.com/fork/components-issue).
2. I opened `styles.scss` and changed `@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';` to `@use '~@angular/material' as mat;`, per the Angular [theme guide](https://material.angular.io/guide/theming#predefined-palettes).
3. As soon as I add the `@use` line, the app rebuilds and the output window shows

![image](https://user-images.githubusercontent.com/943160/121532611-cd1ceb00-c9ff-11eb-8ebd-71c24f6a0868.png)

(I need to put together a simple example application that uses a dark theme, and AFAICT there is still no option for a prebuilt dark theme.)

**Comment by crissxross** [comment]
I have the same issue using Angular 12 components with `@use '~@angular/material' as mat;`

**Comment by hevans90** [comment]
This project is starting to become a joke.

**Comment by sohaibamjad8** [comment]
![image](https://github.com/stackblitz/core/assets/11348355/dee803f4-a134-485e-8f0c-fee2d16f4a77)
Can someone please help on this?

**Comment by CosRodRamBar** [comment]
Boa noite pessoal, para este comando funcionar, tem que fazer a instalação do material:

Site: https://www.npmjs.com/package/@angular/material

Instalação: npm i @angular/material
