### ISSUE TITLE
Feature request: setting for no extra files

### ISSUE THREAD

**Issue by colinricardo** [stackblitz/core#833]
I use StackBlitz a lot for helping to answer StackOverflow questions. 

Every time I make a new project (through bookmark of `https://stackblitz.com/fork/react`), I delete the `Hello.js` and `style.css` files and remove the imports in the `index.js` file. I do this to avoid having code unrelated to what I'm trying to demonstrate, to minimize confusion. 

It would be nice if you could toggle a 'no-extra-files' mode, so that when you load a new project it just gives you the bare minimum, something like: 

```jsx
import React, { Component } from 'react';
import { render } from 'react-dom';

class App extends Component {
  constructor() {
    super();
    this.state = {
      name: 'React'
    };
  }

  render() {
    return (
      <div>
        <p name={this.state.name} />
        <p>
          Start editing to see some magic happen :)
        </p>
      </div>
    );
  }
}

render(<App />, document.getElementById('root'));
```

Maybe there's a way to do this already that I'm overlooking. 

Love StackBlitz, thanks for the amazing work!

**Comment by lazarljubenovic** [comment]
Can't you create your own starter and then fork that one?

**Comment by colinricardo** [comment]
Yep, I'll do that. Just thought there might be a one-click way. Thanks!
