### ISSUE TITLE
Feature request: Link to GitHub repo

### ISSUE THREAD

**Issue by arnohovhannisyan** [stackblitz/core#834]
The editor can connect to a repository and push changes to it. This would be very useful because I wouldn't have to download the project and push every time.

**Comment by lazarljubenovic** [comment]
Related: https://github.com/stackblitz/core/issues/167

**Comment by kc0tlh** [comment]
@auxves This issue is now resolved in [our new VS Code editor](https://stackblitz.com/codeflow)! Full writeup in Github issue #2473
