### ISSUE TITLE
Feature request: Add user and workspace settings

### ISSUE THREAD

**Issue by arnohovhannisyan** [stackblitz/core#835]
I would love to have an option to autoformat the document on each save, I have this set on my local installation and it has been doing wonders for me. Thanks!

EDIT: also, it would be great if the user settings were exposed so we could tweak stuff like font size and autoformat

**Comment by mderazon** [comment]
There's already a formatting button, but it doesn't run Prettier. I think it's more of an indentation fix.
I would love if it would run Prettier instead.

However, Prettier is pretty opinionated. I am not sure everyone will like it.

**Comment by JetBr33ze** [comment]
Exactly, having user settings would potentially allow the disabling of Prettier, but a lot of other things would be possible as well
