### ISSUE TITLE
Can't find package:src

### ISSUE THREAD

**Issue by ratnabh** [stackblitz/core#839]
![screenshot 2019-01-13 at 1 50 31 pm](https://user-images.githubusercontent.com/38026695/51083104-39fdff00-173a-11e9-8561-ee4ec52b5645.png)

my project does not run here even after clicking on install package src, I imported the project  from github repository
here is the link to StackBlitz
https://stackblitz.com/github/ratnabh/angular-shopping?file=src%2Fapp%2Fshopping%2Fshopping-list%2Fshopping-list.component.ts

**Comment by amit-kumar-dubey** [comment]
I have the same issue and i see the same https://github.com/stackblitz/core/issues/738: solved 
i use this reference and check and modify it 
in my case: 
**Right**: relative path import { environment } from '../environments/environment';
**Wrong**: import { environment } from 'src/environments/environment';

**Comment by wallysoncarvalho** [comment]
> I have the same issue and i see the same #738: solved
> i use this reference and check and modify it
> in my case:
> **Right**: relative path import { environment } from '../environments/environment';
> **Wrong**: import { environment } from 'src/environments/environment';

Didnt work for me !

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta next month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
