### ISSUE TITLE
[Ionic] Can't use @ionic/storage

### ISSUE THREAD

**Issue by janpio** [stackblitz/core#84]
Ionic Storage is one of the most used Ionic packages as it provides a super simple key-value store that is perfectly intergrated: https://ionicframework.com/docs/storage/

Unfortunately this is not usable on StackBlitz right now:

https://stackblitz.com/edit/ionic-zgw273?file=app%2Fapp.module.ts
![image](https://user-images.githubusercontent.com/183673/29280817-fec5b338-811c-11e7-9492-cf3c20c95873.png)

I added the dependency, could also import the library but as soon as I add the `IonicStorageModule.forRoot()` line to the import everything is broken.

**Comment by EricSimons** [comment]
This is actually because they have their package misconfigured :( I'm going to send them a tweet about this now — thanks for letting us know!

**Comment by EricSimons** [comment]
Will report back when I they respond to this tweet: https://twitter.com/ericsimons40/status/897176859326136320

**Comment by janpio** [comment]
This is about https://github.com/ionic-team/ionic-storage/blob/master/package.json#L5? What should be there instead?

**Comment by apai4** [comment]
The main field should be ES5 not ES2015, looks like there's an issue already open for it here: https://github.com/ionic-team/ionic-storage/issues/29

**Comment by apai4** [comment]
The ES5 build may be broken per https://github.com/ionic-team/ionic-storage/issues/18

**Comment by mapicard** [comment]
Any news on this? Is it working now???
