### ISSUE TITLE
create-react-app Project with typescript template could not be imported from github

### ISSUE THREAD

**Issue by vanmeegen** [stackblitz/core#840]
created a project with create-react-app and typescript template.
tried to import to https://stackblitz.com/github/vanmeegen/react-ts-mobx-template, but failed.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-11 at 10 39 47 AM](https://user-images.githubusercontent.com/49956513/117834518-382ea280-b245-11eb-9b31-b3a8a520edda.png)
