### ISSUE TITLE
Cannot able to view image.

### ISSUE THREAD

**Issue by KapilKadane** [stackblitz/core#841]
Hi I am using Stackblitz to work on my personal project, I am trying to use images in my project but I am not able to use images in my website project. Is this is a issue?

**Comment by tiliev** [comment]
Hello @KapilKadane,
Currently StackBlitz does not support images and static assets. The team is working on this. You could take a look at this issue - https://github.com/stackblitz/core/issues/72.
You could workaround this by uploading your images elsewhere and referencing them in StackBlitz or using GitHub - https://github.com/stackblitz/core/issues/45#issuecomment-375162006.
