### ISSUE TITLE
"Development build of the Firebase JS SDK" Message in Console

### ISSUE THREAD

**Issue by DanWahlin** [stackblitz/core#844]
I'm using v1.2.0 of the Stackblitz SDK and noticed the following message showing up (starting on January 15th, 2019):

`It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

Typescript:
import * as firebase from 'firebase/app';
import 'firebase/<PACKAGE>';
`

Not a huge deal since it's a warning (although it does take up quite a bit of space in the console), but since I've never seen it before I thought I'd mention it. Thanks!

**Comment by apai4** [comment]
This should be fixed now, thanks for letting us know!

**Comment by DanWahlin** [comment]
That was quick - thanks!
