### ISSUE TITLE
my repo isn't loading 

### ISSUE THREAD

**Issue by clevelandrachel** [stackblitz/core#853]
https://stackblitz.com/github/clevelandrachel/timetouse

**Comment by tiliev** [comment]
@clevelandrachel, you pushed your `node_modules` folder which is ~400 mb. `node_modules` should not be pushed to the repository. Please use a `.gitignore` file to ignore the `node_modules` folder.
Either way, I am not able to start your project locally.

**Comment by purplem1lk** [comment]
> @clevelandrachel, you committed your `node_modules` folder which is ~400 mb. `node_modules` should not be committed to the repository. Please use a `.gitignore` file to ignore the `node_modules` folder when commiting.
> Either way, I am not able to start your project locally.

This issue has been resolved and will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
