### ISSUE TITLE
Running a project from github is giving me this error

### ISSUE THREAD

**Issue by gautamkrishnar** [stackblitz/core#856]
Error in /turbo_modules/@angular/compiler@7.2.3/bundles/compiler.umd.js (2496:21)
Can't resolve all parameters for ApplicationModule: (?).

URL: https://stackblitz.com/github/Mozilla-Kerala/home-front

**Comment by tiliev** [comment]
@gautamkrishnar, please take a look at this issue - https://github.com/stackblitz/core/issues/758#issuecomment-436773474.
