### ISSUE TITLE
Settings from SDK-created embeds don't propagate when opening in new window

### ISSUE THREAD

**Issue by graynorton** [stackblitz/core#858]
1. Visit https://lit-element.polymer-project.org/guide/start
2. Scroll down and click one of the `Launch Code Editor` buttons
  - StackBlitz embed opens
3. In the embed, click the gear icon and confirm that the `Reload mechanism` is set to `Page reload`
4. Click `Edit on StackBlitz` in the lower right corner of the embed
  - Opens in new window
5. In the new window, click the gear icon

=> `Reload mechanism` is set to `Hot reload`

It's important for our use case that the settings we specify using the SDK propagate to the full-window experience. Since we're using web components and can only register a custom element once, hot reload causes runtime errors in our projects.

**Comment by EricSimons** [comment]
@graynorton great catch- I'm sorry about this! Should be a simple fix on our end, will knock out by EOD tmrw.

Also- I'm going to release a new version of our SDK tomorrow that enables the new polymer template 😄 Will circle back here once that's live as well. Lmk if there's anything else we can do to help!

**Comment by graynorton** [comment]
Awesome – thanks, @EricSimons!

**Comment by EricSimons** [comment]
@graynorton this is now fixed on prod! Just tested the lit-element docs too and seems to work correctly 👍 

Also, I just pushed a new version of the sdk (1.3.0) that enables Polymer support w/ no transpilation- just use `polymer` as the template instead of `javascript`/etc. Lmk if I can help y'all get set up with it!
