### ISSUE TITLE
I am seeing some of my files get deleted without me initiating the delete

### ISSUE THREAD

**Issue by weedrater** [stackblitz/core#86]
This has happened twice while working  over the course of a  few hours.  I had no indication that the file was going to be removed.  but it just disappeared

**Comment by EricSimons** [comment]
This is really bizarre — will check our logs when I'm back at my computer. Can you link the project URL(s) that you've seen this happen on?

**Comment by weedrater** [comment]
https://stackblitz.com/edit/weedrater-home-search

**Comment by weedrater** [comment]
Is it possible there is a hotkey for removing files?

**Comment by EricSimons** [comment]
No, but it is possible you might be accidentally clicking the delete button and not realizing it b/c we don't currently have a prompt to confirm deletes (really stupid oversight on our part, fix going out this week for it)

**Comment by weedrater** [comment]
NP, didn't loose too much work.  I'll keep an eye on it, in case I see a pattern

**Comment by weedrater** [comment]
This hasn't occurred in a while.  I most likely clicked the trash can icon.  Looking forward to that confirmation feature.
