### ISSUE TITLE
Ionic V4

### ISSUE THREAD

**Issue by 7martinelli** [stackblitz/core#860]
Stackblitz is not working on ionic v4.

**Comment by 7martinelli** [comment]
any update on ionic 4 for stackblitz?

**Comment by comfortme** [comment]
I don't think this issue is related to stackblitz. earlier beta versions of ionic 4 was running but current versions are not.
see this issue https://github.com/ionic-team/ionic/issues/16354

**Comment by 7martinelli** [comment]
The issue is not on ionic, the stackblitz team should upgrade to ionic 4 its template.

**Comment by 7martinelli** [comment]
All the examples in ionic 4 beta just mimic the funcionality. I did not see any real ionic 4 project working

**Comment by Noel-F** [comment]
Is this ever going to happen? I tried multiple times you make my own with the latest from ionic but with no success.

**Comment by sam-suresh** [comment]
+1

**Comment by purplem1lk** [comment]
Thank you for your patience - This issue has been [resolved](https://github.com/ionic-team/ionic-framework/issues/16354#issuecomment-515100104
) and will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
