### ISSUE TITLE
Can't copy folder?

### ISSUE THREAD

**Issue by p-craig-peddie** [stackblitz/core#864]
I'm trying to copy a folder from my local drive to the stackblitz project just like the docs say, but it never copies. No errors, nothing, just no copy. Files work fine. But the docs section say I can copy folders, and I have a bunch of components to copy to move my app up into stackblitz. Have tried chrome, firefox and safari. Is there a trick to use?

**Comment by comfortme** [comment]
hi.
this is an old issue https://github.com/stackblitz/core/issues/836

**Comment by beeman** [comment]
Closing as duplicate, we are working on improving this.
