### ISSUE TITLE
define is not a function when loading office-ui-fabric-react

### ISSUE THREAD

**Issue by bengry** [stackblitz/core#871]
I tried creating a sample Stackblitz for our package - [`@angular-react`](https://github.com/Microsoft/angular-react), but after adding all the dependencies, it seems like Stackblitz is having issues loading some files that usually Webpack (or the Angular CLI, using Webpack) handles.

I also tried to fake the dependency, just to see if it would go away by adding the following the `main.ts`:
```
window['define'] = () => {};
```

but the same errors shows up:
> Error in /turbo_modules/office-ui-fabric-react@6.139.0/lib-amd/components/OverflowSet/OverflowSet.scss.js (1:116)
define is not a function

[Repro Stackblitz](https://stackblitz.com/edit/angular-react)

**Comment by purplem1lk** [comment]
Thank you for your patience - I no longer see the errors that you posted. It's possible that this has been fixed over various code changes so this issue will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)

![Screen Shot 2021-05-11 at 11 16 02 AM](https://user-images.githubusercontent.com/49956513/117840567-48954c00-b24a-11eb-8638-155be13ac27d.png)
