### ISSUE TITLE
Server spins forever when when installing plotly.js and @types/plotly.js

### ISSUE THREAD

**Issue by oleersoy** [stackblitz/core#875]
This [SO post](https://stackoverflow.com/questions/54778149/installing-plotly-and-types-plotly-on-angular-stackblitz) has the description and stackblitz links.

Here's a copy just for convenience:

Attempting to install `plotly.js` and `@types/plotly.js` on Stackblitz, but after the install the dev server just spins.  Any ideas?

This is the stackblitz attempt:
https://stackblitz.com/edit/angular-ryyafw

**Comment by andrei-tatar** [comment]
Seems to be a CORS policy issue:

> Access to fetch at 'https://t.staticblitz.com/v6/plotly.js@1.44.4' from origin 'https://stackblitz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by kc0tlh** [comment]
This issue has been resolved!
