### ISSUE TITLE
Back Button destroyed source code view

### ISSUE THREAD

**Issue by mister-what** [stackblitz/core#88]
Hey guys,
using back Navigation destroyed the source view of my project. Tried different browsers, clear-cache/incognito mode. Code area stays black, even after forking the project.

Link to the [broken project](https://stackblitz.com/edit/broken-mr-what-cnkjzx)
Downloading project sources works.

**Comment by EricSimons** [comment]
@mister-what what browser are you using? I can't seem to repro this in chrome. Can you potentially take a screenshot (or video) of the issue that's happening?

**Comment by mister-what** [comment]
@EricSimons Yes, I have screen-shots. 

None of Firefox, Chrome, Chrome-Incognito is working. Opening the WebUI from another machine seems to work. I can't reproduce the problem on my laptop, it is just there on my desktop. Isn't that weird as f...?

As a developer wouldn't say that this is even possible... Here are screenshots from different browsers:

<img width="1464" alt="chrome-incognito" src="https://user-images.githubusercontent.com/1831300/29358331-f2993990-827a-11e7-8cb6-dac9e1951dbb.png">
<img width="1664" alt="firefox" src="https://user-images.githubusercontent.com/1831300/29358340-f9df0b44-827a-11e7-93f9-54c0ec7abb67.png">
<img width="1512" alt="chrome-default" src="https://user-images.githubusercontent.com/1831300/29358346-ffdcca2c-827a-11e7-9a12-dd7f3300ae3f.png">
<img width="1127" alt="chrome-incognito-source3" src="https://user-images.githubusercontent.com/1831300/29358442-5a7b67d6-827b-11e7-9d3d-7b839984fc3c.png">
<img width="1036" alt="chrome-incognito-source2" src="https://user-images.githubusercontent.com/1831300/29358441-5a75bcdc-827b-11e7-84f7-06abac63d612.png">
