### ISSUE TITLE
The url to this repository is invalid.

### ISSUE THREAD

**Issue by demitri2004** [stackblitz/core#887]

**Comment by beeman** [comment]
Hey @demitri2004, could you explain where we can find to URL you mentioned?

**Comment by justinemailone** [comment]
I'm having a similar issue. The URL provided under Share -> EDITOR URL is https://stackblitz.com/github/bnmizkmv which takes me to a "Yikes! The page you requested couldn't be found" page.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
