### ISSUE TITLE
Feature request: Editor SDK

### ISSUE THREAD

**Issue by alirezamirian** [stackblitz/core#888]
I know that stackblitz already has an SDK, but I'm talking about something different.

When someone works with stackblitz UI, they do stuff like:
- Opening one of the project files into the editor.
- Toggling console panel.
etc.

Being able to do these kind of stuff **programmatically**, is awsome. Consider a demo in which there are different buttons by which you can navigate to different parts, and at the same time editor switches to related file to that specific part. or in some point in the demo, you know that user needs to see console output, so you open it programmatically.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
