### ISSUE TITLE
Add main css file (main.css or style.css) on index.html level.

### ISSUE THREAD

**Issue by Andrey-Nosfer** [stackblitz/core#89]
Add main css file to global page styling, Like in CLI projects. Or ability to change head tag in index.html

thanks

**Comment by aat-antoine** [comment]
From my tests with angular, It seems it does not work on stackblitz's servers whereas it works if I export project and run locally.

Here is the example I coded
https://stackblitz.com/edit/stylewithstylescss

**Comment by damccull** [comment]
I can confirm having this problem as well. It seems the server is rewriting ALL requests to anything in the / directory to point at the index.html file. Therefore my browser is loading the style.css file, but its contents are the same as index.html instead of containing styles.

**Comment by EricSimons** [comment]
Hey all — you are totally correct, this isn't currently working on stackblitz but I'm actually adding it in now. You'll also have the ability to modify the angular-cli.json file itself and add in multiple stylesheets, use sass/less, etc :) I'm shooting to have this ready by Monday or Tuesday and will post back here once it's online!

**Comment by EricSimons** [comment]
@damccull @aat-antoine @Andrey-Nosfer took a little longer than expected, but SASS/LESS and the angular-cli.json config now works :) You can check it out in action in the [Angular starter template](https://stackblitz.com/fork/angular) or my [Angular Material starter template](https://stackblitz.com/edit/angular-material) — would love hear your thoughts :)

**Comment by aat-antoine** [comment]
For me, this issue can be closed, now css files can be configured in the .angular-cli.json. Good job :)

**Comment by EricSimons** [comment]
Awesome to hear @aat-antoine! Thanks :)
