### ISSUE TITLE
Can't install @stackblitz/turbo-resolver

### ISSUE THREAD

**Issue by scottc-netflix** [stackblitz/core#891]
'@stackblitz/turbo-resolver@0.1.0' is not in the npm registry.

Why is it not published to npm? Are we not supposed to be able to use it or...?

**Comment by VictorCoding** [comment]
https://www.npmjs.com/search?q=stackblitz

Doesn't look like they're much in the npm registry

**Comment by kc0tlh** [comment]
We now support [npm, yarn, and pnpm](https://blog.stackblitz.com/posts/announcing-native-package-manager-support/) inside [our new editor](https://stackblitz.com/codeflow).
