### ISSUE TITLE
create-react-app Error

### ISSUE THREAD

**Issue by richard-foxandcostudio** [stackblitz/core#893]
Should this not work?
https://stackblitz.com/github/facebook/create-react-app

**Comment by beeman** [comment]
Hey @richard-foxandcostudio , the repo you are trying to import is not actually a React app, but merely a sort of 'sdk' that helps you write React apps. This is why it can't be imported.

You should be able to import actual React projects though: [https://stackblitz.com/github/beeman/stackblitz-react](https://stackblitz.com/github/beeman/stackblitz-react).

Let me know if you have any other questions!

**Comment by richard-foxandcostudio** [comment]
Thank you for the explanation.
