### ISSUE TITLE
Clone from github not working

### ISSUE THREAD

**Issue by neunygph** [stackblitz/core#895]
Cloning a project on github is not working, even from https://github.com/facebook/create-react-app while in the document from https://stackblitz.com/docs#import-from-github saying create-react-app is also supported.

Thanks,

**Comment by beeman** [comment]
Hi @neunygph, the import sees to work as expected, for example check this link:

[https://stackblitz.com/github/beeman/stackblitz-react](https://stackblitz.com/github/beeman/stackblitz-react)

This imports the basic React starter project from GitHub.

The `create-react-app` repo you linked is the whole create-react-app 'sdk', so it's not the app itself.

I hope this clear it up a bit!

**Comment by neunygph** [comment]
Thanks @beeman . Also, I have a full MERN stack project with webpack and redux. Does it work with stackblitz ?

**Comment by neunygph** [comment]
This is one of my react project but it's not working.

https://github.com/Cezerin2/cezerin2-store

Thanks,

**Comment by beeman** [comment]
@neunygph the current version of StackBlitz runs all the compilation of the front-end apps in the browser. This means that there is no support for running Node-based tools.

This is something we are looking to provide in the future. For now though, it's limited to the front-end libraries that are officially supported.

I hope this answers your question.

**Comment by neunygph** [comment]
Ah I see, now it makes sense. Thanks @beeman  for the clarification.
