### ISSUE TITLE
Deleting opened file makes the editor explode

### ISSUE THREAD

**Issue by tonysamperi** [stackblitz/core#897]
When I delete a file opened this happens:

![image](https://user-images.githubusercontent.com/5957244/54523506-fb6e0600-496f-11e9-9a1b-236123c21271.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, in addition to your description and screenshots of the error. Thank you! :)

**Comment by tonysamperi** [comment]
I can confirm that the problem was solved. 
To be more clear: if you deleted a file which was opened in the editor, the error above happened.
