### ISSUE TITLE
Mobx Example works fine in Stackblitz, but fails when exported

### ISSUE THREAD

**Issue by aaronksaunders** [stackblitz/core#90]
It appears that the exported project doesn't support decorators... which I believe is because create-react-app doesn't support decorators.

Just wanted to confirm my suspicions.

Wondering if there is way to warn the user or keep the user from using decorations so that you don't have to spend the time unwinding the decorators when exporting the project

**Comment by EricSimons** [comment]
@aaronksaunders great catch! create-react-app indeed doesn't support decorators out of the box, so we'll need to figure out a way to export to a config that allows decorators. Either that or disabling decorators for React projects in stackblitz. Any thoughts on which would be more ideal?

**Comment by aaronksaunders** [comment]
i think at a minimum for now would be to just let folks know that it will not be supported when exporting...

keep up the great work!

**Comment by mattblackdev** [comment]
Shouldn't it be possible to just add [custom-react-scripts](https://medium.com/@kitze/configure-create-react-app-without-ejecting-d8450e96196a) and enable decorators? I will try it eventually but haven't needed to export yet! I love stackblitz!

**Comment by linonetwo** [comment]
Or allow the use of [react-app-rewired](https://github.com/timarney/react-app-rewired)
