### ISSUE TITLE
Doesn't detect package.json in child directory.

### ISSUE THREAD

**Issue by sharpninja** [stackblitz/core#902]
When openning a repository with the package.json in a child folder, Stack Blitz reports a missing package.json and if I feel this is an error to let you know here.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
