### ISSUE TITLE
Can't update angular to latest dependencies

### ISSUE THREAD

**Issue by WreckItRalph** [stackblitz/core#903]
Unable to update the dependencies in angular to latest version.

Reproduction steps:
1. Fork angular (new project).
2. Install latest dependencies.

You get an error for installing `core-js`, even though the latest version is installed.

Reason: Breaking changes in `core-js@3.0.0`

See the answer here:  [stackoverflow](https://stackoverflow.com/a/55280275/6019563)

**Comment by kc0tlh** [comment]
This issue has been resolved.
