### ISSUE TITLE
Angular Support on iPad 

### ISSUE THREAD

**Issue by tidustmp** [stackblitz/core#905]
Is Stackblitz support iPad safari? I can't use the ng generator using iPad.

**Comment by noodlemind** [comment]
I am trying to use stacklitz on my ipad with Chrome and Safari, both doesn't seem to work

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
