### ISSUE TITLE
Hot reload not working due to navigation error

### ISSUE THREAD

**Issue by bene-starzengruber** [stackblitz/core#906]
It seems like there is some problem with hot reloading for typescript projects.

The project is loaded and executed once but then for each hot-reload there is an error in the console
`Uncaught (in promise) TypeError: Cannot navigate to URL: https://typescript-ywmq7r.stackblitz.io/_relay_`
and the preview is basically broken (hot reload + manual reloading per button not working anymore)

example: https://stackblitz.com/edit/typescript-ywmq7r?file=index.ts

Windows 10/ Chrome 72.0.3626.121

**Comment by BenRacicot** [comment]
Yeah def strangely random. Commented out most of my code for:
`Uncaught (in promise) TypeError: Cannot navigate to URL: https://project-name.stackblitz.io/`
and
`Uncaught (in promise) TypeError: Cannot navigate to URL: https://project-name.stackblitz.io/_relay`

**Comment by bene-starzengruber** [comment]
It seems to be connected to some Firewall settings, as it only does not work at my desktop PC, everything is normal at Home.
Just a bit strange, that only chrome is affected...

**Comment by dwiyatci** [comment]
I've got a similar error message here:
> Uncaught (in promise) TypeError: Cannot navigate to URL: https://angular-7evq6w-4n4bdd.stackblitz.io/

I bet something is messed up with their SW implementation 'cause I also saw this warning message in the Chrome console:
> Service Worker was updated because "Update on reload" was checked in the DevTools Application panel.

I workaround this by unchecking "Update on reload" of that service worker for StackBlitz in the devtools:
**Application > Service Workers > Update on reload -> _uncheck_**
