### ISSUE TITLE
Unable to link github account

### ISSUE THREAD

**Issue by Maryannah** [stackblitz/core#909]
I have a github account. I have created a project in Stackblitz (Angular one if that matters). 

Stackblitz is authorized in my github settings. 

Yet, when I try to connect, I get this error : 

![image](https://user-images.githubusercontent.com/46892394/54994379-664cbc00-4fc4-11e9-9881-d8a530ee5b7c.png)

I have tested on another network, without and without a proxy, with and without a firewall, nothing makes it ... Any idea where this might come from ?

**Comment by Maryannah** [comment]
Any news about this issue ?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
