### ISSUE TITLE
Would this tool support emmet?

### ISSUE THREAD

**Issue by hstarorg** [stackblitz/core#91]
I used the online tool, and I want to use emmet for html file. Would you provide the function?

**Comment by lazarljubenovic** [comment]
It's not yet supported.

Duplicate of https://github.com/stackblitz/core/issues/25.

**Comment by hstarorg** [comment]
I have a lib: [https://github.com/hstarorg/emmet-monaco](https://github.com/hstarorg/emmet-monaco), maybe it can be used.

**Comment by EricSimons** [comment]
Shipped a while back! 🍻
