### ISSUE TITLE
Feature request: Option to select JS version for transpiler

### ISSUE THREAD

**Issue by rdking** [stackblitz/core#912]
StackBlitz is currently transpiling to ES 5 (or so it seems). It would be nice if there was a setting to select the ES version to target. New projects could still default to 5, but make 6-8 available as well.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
