### ISSUE TITLE
Stackblitz does not work in IE

### ISSUE THREAD

**Issue by LJ2319** [stackblitz/core#914]
Not sure if an update was pushed out, but stackblitz no longer loads in IE11. Trying to create a react example, and all that displays is a gray screen.
![Capture2](https://user-images.githubusercontent.com/28812539/55237158-dc8d3080-5207-11e9-9d4f-1348da061037.PNG)

**Comment by purplem1lk** [comment]
Thank you for your patience - We will be closing this issue and posting updates in #1155 to consolidate the resolution. If your issue persists, feel free to tag me or ask to reopen this issue with a recent project link, description and screenshots of the error. Thank you! :)
