### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by danavcohen** [stackblitz/core#915]
when I download an angular project the project look like he have not style.
In addition can you help we , I have anthor exist project and I want to join your projcet when I 
put it in the file and Include the compenents the data is not up. 
can you explain me what to do?

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
