### ISSUE TITLE
URLSearchParams not working

### ISSUE THREAD

**Issue by pratikamburle** [stackblitz/core#917]
While working with React project, i am not able to iterate **URLSearchParams(location.search).entities()** using for loop

for eg.:
// Create a test URLSearchParams object
var searchParams = new URLSearchParams("key1=value1&key2=value2");

// Display the key/value pairs
for(var pair of searchParams.entries()) {
   console.log(pair[0]+ ', '+ pair[1]); 
}

**Comment by sulco** [comment]
We've undergone a series of updates to the platform since this issue was submitted and it does no longer seem to appear.
Closing for now, please free to reopen if you're still experiencing it!
![Uploading image.png…]()
