### ISSUE TITLE
Support for -strictNullChecks configured in tsconfig.json

### ISSUE THREAD

**Issue by AFDevMike** [stackblitz/core#919]
Is there a way to enable the TS compiler option --stritcNullChecks?

**Comment by earshinov** [comment]
Related: https://github.com/stackblitz/core/issues/220

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue (or carry the conversation to #220). Thank you! :)

**Comment by PerryCodes** [comment]
I don't see where this is now working... Anyone else either able to enable strictNullChecks in compilerOptions or seeing the functionality enabled by default?
