### ISSUE TITLE
[Feature Request] Groups of Stackblitzs

### ISSUE THREAD

**Issue by oleersoy** [stackblitz/core#920]
In the documentation [for this project](https://www.npmjs.com/package/@fireflysemantics/slice) the first feature is **Live Stackblitz Demos**.

It would be nice if I could provide a link to a group of demoes.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
