### ISSUE TITLE
label B

### ISSUE THREAD

**Issue by jajatip** [stackblitz/core#921]
Hi,
when i am zooming in and zooming out. The position of label A marker is fixed ,but label B and C marker position is not fixed .label B and Label C are changed according to zoom in and zoom out .my scenario is to fixed the marker position.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
