### ISSUE TITLE
How to solve "Constructor requires 'new'" on stackblitz?

### ISSUE THREAD

**Issue by Lcfvs** [stackblitz/core#923]
Hi,

I tried to solve it, using a `.babelrc` for builtin constructors but doesn't seems applied.

```js
class CustomTarget extends window.EventTarget {}

new CustomTarget() // throws Constructor EventTarget requires 'new'
```

**Comment by Lcfvs** [comment]
The `.babelrc`

```json
{
  "plugins": [
    "babel-plugin-transform-es2015-classes",
    ["babel-plugin-transform-builtin-classes", {
      "globals": ["EventTarget"]
    }]
  ]
}
```

**Comment by purplem1lk** [comment]
Thank you for your patience - This looks related to #475, which has more recent activity so we will move the conversation to that issue. We are launching new core technology into beta this month that should resolve this issue. If your issue persists, feel free to tag me or leave a comment on #475 with a working project link, description, and screenshots of the error. Thank you! :)
