### ISSUE TITLE
StackBlitz font for code panel on windows

### ISSUE THREAD

**Issue by andrexx** [stackblitz/core#926]
Hi,

I am using Windows 10.
Yesterday, I noticed that the code began to appear in small font and became poorly readable. It became impossible to use (for me).
I looked at the styles and most likely the fallback works on Courier New which makes font display is small and ugly with 12px size.
As solution I would like to suggest to add "Consolas" before "Courier New" in the list of fallback fonts. It's much better than Courier.

Workaround: I fixed this for myself by downloading and installing the Fira Code font.

Thank you for great product!

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by webcolor-in** [comment]
![image](https://user-images.githubusercontent.com/55145799/145416679-27b3778c-32bc-4d58-95d5-48118f67b5c8.png)

Can this default font be changed to better? 

![image](https://user-images.githubusercontent.com/55145799/145416987-a95c3048-f460-432e-ac89-c9caf38bba3c.png)
