### ISSUE TITLE
My project happened to crash SB

### ISSUE THREAD

**Issue by JikkuJose** [stackblitz/core#93]
https://stackblitz.com/edit/content-switcher?file=index.js

**Comment by EricSimons** [comment]
That's v weird - did you drag and drop files into the editor by chance? Perhaps there were some large binaries in there that might be tanking it?

Cc @apai4 - can you investigate our logs?

**Comment by JikkuJose** [comment]
Nope, nothing of that sort. A very standard project using few libraries.

**Comment by apai4** [comment]
@JikkuJose sorry for the delay, just pushed a fix for this! Your project is working now, lmk if you run into any more issues
