### ISSUE TITLE
When deps are updated Stackblitz can't find core-js

### ISSUE THREAD

**Issue by oleersoy** [stackblitz/core#930]
I have this project:

https://stackblitz.com/edit/slice-todo

It runs with the current dependency versions, but if I updated the deps I get the message:
> Can't find package:core-js

Thoughts?

**Comment by beeman** [comment]
Hey @oleersoy I have seen the same issue, you can work around it by installing `core-js@2`

**Comment by oleersoy** [comment]
Hey @beeman - That was a sweet comment!  It works now!  Thanks!

**Comment by kolkov** [comment]
The same error in my https://github.com/kolkov/angular-editor library.

**Comment by MurhafSousli** [comment]
Thanks @beeman.. in the right place in the right time

**Comment by wzup** [comment]
@beeman 
> you can work around it by installing core-js@2

HOW?? How to install anything in Stackblitz? Does it have CLI?

**Comment by nimirea** [comment]
@wzup You can change the versions of installed packages (or add new packages) for a project in the package.json file. Just change `core-js: "^3.1.4"` to `core-js: "2.6.9"`

**Comment by seoriam** [comment]
@wzup You may also change it via the 'Dependencies' tab under the 'Project' tab (icon shaped like files) on the left sidebar. 

If you shorten the 'Files' tab and open the 'Dependencies', you can see the text input with placeholder "enter package name". You may enter your desired package and version with the format `{package}@{version}` (*without the curly braces*).

So downgrading core-js to 2 is as simple as entering `core-js@2` to the input and hitting enter. Same with upgrading or installing additional dependencies. I love StackBlitz.

**Comment by fr0** [comment]
Downgrading to `core-js@2` is a great workaround for some people, but if the behavior you're trying to replicate in your stackblitz depends on `corejs@3`, that's... not so great.

I'm very curious what bug would cause this. Doesn't stackblitz use the global npm registry?

**Comment by lhduc** [comment]
I've had same problem. But downgrading version did not help me. 
https://stackblitz.com/edit/angular-zjmixh
It works well on my local machine. Could you advice what I should do this case? Thanks.

**Comment by omostan** [comment]
> @wzup You can change the versions of installed packages (or add new packages) for a project in the package.json file. Just change `core-js: "^3.1.4"` to `core-js: "2.6.9"`

Your suggestion solved the problem.
Thanks!

**Comment by sibiraj-sr** [comment]
I had the same problem, this might be the same issue. if you open polyfills.ts in your angular project. You will have 

```js
import 'core-js/es6/symbol';
```

here `core-js/es6` is doesn't exist since v3, update it to `core-js/es`

```js
import 'core-js/es/symbol';
```

**Comment by omostan** [comment]
> I had the same problem, this might be the same issue. if you open polyfills.ts in your angular project. You will have
> 
> ```js
> import 'core-js/es6/symbol';
> ```
> 
> here `core-js/es6` is doesn't exist since v3, update it to `core-js/es`
> 
> ```js
> import 'core-js/es/symbol';
> ```

This is the best solution to the problem. With this solution, you can still use core-js current version without errors. According to @sibiraj-sr, core-js/es6 or core-js/es7 were removed from core-js v3. Editing polyfills.ts as stated removes the errors.

**Comment by purplem1lk** [comment]
> Hey @oleersoy I have seen the same issue, you can work around it by installing `core-js@2`


> I had the same problem, this might be the same issue. if you open polyfills.ts in your angular project. You will have
> 
> ```js
> import 'core-js/es6/symbol';
> ```
> 
> here `core-js/es6` is doesn't exist since v3, update it to `core-js/es`
> 
> ```js
> import 'core-js/es/symbol';
> ```

Thank you for your patience - This issue has been resolved and will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
