### ISSUE TITLE
matchAll() not working

### ISSUE THREAD

**Issue by juanpasolano** [stackblitz/core#931]
[Demo](https://stackblitz.com/edit/react-cpruzr).

```javascript
  const isRegEx = new RegExp(/(is:\s?)(\w+)?/ig);
  const matches = query.matchAll(isRegEx);
  console.log(matches);

  const matchesArray = [...matches];
  //const matches = isRegEx.exec(query);

  for (const match of matches) {
    console.log(match);
  }
```
It seems to me that String​.prototype​.matchAll() is not working as expected. 
If you see in the demo:
1. the line `[...matches]` throws a `matches.slice is not a function` which according to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll) is valid.
2. Iterating over the matches does not work either.

**Comment by sulco** [comment]
Thanks for reporting this!

Thankfully with our latest updates this should no longer be an issue, so I'm closing it (but feel free to reopen if you do stumble upon it again)
