### ISSUE TITLE
Connect repository infinite loading message

### ISSUE THREAD

**Issue by dkosasih** [stackblitz/core#933]
If I happened to have the same repository name that are already exists when I try to connect to repository for the first time, it will says "connecting" and stays on that screen forever without error message.

Ideally: It should let user know that a repo with that name has already exists.

**Comment by bretonio** [comment]
Also with this difficulty &mdash; as well as no success downloading and running with `npm i && npm start` ...

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
