### ISSUE TITLE
Changed my github account to organisation now can't login

### ISSUE THREAD

**Issue by deanmarcussen** [stackblitz/core#934]
I changed my github account to an organization recently, now when I try and create a new oauth for my new personal account on stackblitz I get a Yikes something went wrong error when redirecting back to stackblitz. Have tried clearing out the oauth validation for stackblitz on my github account.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
