### ISSUE TITLE
"Edit on StackBlitz" button in embed missing in Firefox

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [stackblitz/core#938]
It's visible in Chrome but not visible in Firefox.  Tested with latest versions of both on macOS and Windows.

**Comment by purplem1lk** [comment]
Thank you for your patience - The screenshot shows what I currently see in Firefox. Various code changes have updated this feature and it should be working across all browsers now. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

![Screen Shot 2021-05-12 at 8 32 21 PM](https://user-images.githubusercontent.com/49956513/118060626-293d1280-b361-11eb-8afb-00644960dc5a.png)
