### ISSUE TITLE
CSS on ng-pick-datetime not applied

### ISSUE THREAD

**Issue by Ukiand1** [stackblitz/core#94]
When trying to add this npm https://www.npmjs.com/package/ng-pick-datetime. He applies it but without CSS. 

Either way, awesome work man, truly amazing!

**Comment by Ukiand1** [comment]
The problem is in the npm itself, there was an update and styles are separated so if you wan't to call it here in the project either you put the path in styleUrls or copy their styles.css into your css file ( etc. copy everything into app.component.css)

**Comment by GAlexMES** [comment]
Both of your solutions are not working for me. Do you have any other suggestion or is there a official fix for this problem?

**Comment by EricSimons** [comment]
Hey all! This problem was fixed with our new support for CSS imports + SASS/LESS; more info here -> https://github.com/stackblitz/core/issues/89#issuecomment-327941849

Closing this issue for now but feel free to comment if you have q's!
