### ISSUE TITLE
Doesn't Work with React Projects Created with Parcel

### ISSUE THREAD

**Issue by brandiqa** [stackblitz/core#941]
I've created a React project using Parcel where I've manually installed React dependencies. For some reason, it assumes the project is Angular

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without being able to reproduce the issue you are seeing and will be closing this accordingly. It is possible that previous code changes have fixed this issue over time. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
