### ISSUE TITLE
Failure: Unsatisfied version range

### ISSUE THREAD

**Issue by paramquery** [stackblitz/core#942]
I'm unable to update pqgridtest1 npm package to latest version 0.0.22 due to the error.

Failure: Unsatisfied version range
Unable to resolve package pqgridtest1@ ^0.0.22
Please try installing a different version or range.

https://stackblitz.com/edit/paramquery-angular-locale?file=package.json

**Comment by sulco** [comment]
This project does not seem to exist anymore, so I'm closing the issue for now (please reopen if you're still running into this issue and can provide a link to the project so we can investigate)

**Comment by talentlessguy** [comment]
Same issue when trying to install `bnc-onboard`

![image](https://user-images.githubusercontent.com/35937217/126499174-1dc41b66-44e7-4c79-9ddf-c4496b4b1526.png)

**Comment by Royal-lobster** [comment]
> Same issue when trying to install `bnc-onboard`
> 
> ![image](https://user-images.githubusercontent.com/35937217/126499174-1dc41b66-44e7-4c79-9ddf-c4496b4b1526.png)

having the same error installing ```wagmi```
