### ISSUE TITLE
Stackblitz does not run and preview in Firefox 66.0.3 (32-bit)

### ISSUE THREAD

**Issue by ukozdan** [stackblitz/core#943]
Running a standard Angular project results in the following browser console error: 

`Duplicate definition of module 'vs/basic-languages/typescript/typescript' loader.js:1176
TypeError: ServiceWorker script at https://glxvpdmppvb.angular.stackblitz.io/_sw_.js for scope https://glxvpdmppvb.angular.stackblitz.io/ encountered an error during installation.`

**Comment by sulco** [comment]
Thanks for reporting this.
Looks like it's no longer an issue, so I'm closing it for now, but if you stumble upon it again, feel free to reopen!
