### ISSUE TITLE
Service worker started in Angular app caches network data

### ISSUE THREAD

**Issue by jforjava1981** [stackblitz/core#945]
I am connecting to local express backend nodejs server to load data from my stackblitz angular app.
 this works fine when server is up and load data. 
However when server is down stackblitz loads data using a service worker it loads somhow at the startup. I would like to disable this as i want to load data only when server is up.
This cconfuses as we are not sure if a problem occurs its because of angular code orde server problem as data is always available.
Please provide a way to disable service worker caching and providing data when backend server is down.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of what you're seeing. Thank you! :)
