### ISSUE TITLE
https://stackblitz.com/github/   github import not working

### ISSUE THREAD

**Issue by michaeljabbour** [stackblitz/core#946]

**Comment by CameronBanga** [comment]
Seeing this as well.

**Comment by CameronBanga** [comment]
![Screen Shot 2019-05-06 at 5 58 55 PM](https://user-images.githubusercontent.com/611354/57260315-ac1b8c00-7028-11e9-90bd-385eaf54a9fc.png)

**Comment by boisvertmath** [comment]
Same here

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
