### ISSUE TITLE
Great editor! But I am unable to sign in via gitHub

### ISSUE THREAD

**Issue by pain0486** [stackblitz/core#95]
I think this could be my go to sln for mocking in angular, especially with the export to a cli project.
However I am unable to login an actually save stuff to my account.

After enter credentials I am redirected to a blank screen. Console shows that https://stackblitz.com/api/users/auth/github/callback?code=2bc73a9dbd01d45220ab&state=5724b99c7883e1dd5e4aec5290c9a8a00e6387f02d8dd7f3 returned a 422
![callbackrequest](https://user-images.githubusercontent.com/11378706/29445300-9bb1804c-83ab-11e7-837f-d644ef868fab.PNG)

**Comment by EricSimons** [comment]
Yikes, this shouldn't be happening 😥 @apai4 can you dig into this asap?

**Comment by apai4** [comment]
@pain0486 Digging into this now, it looks there's been some auth requests failing with a 422 since a user is being created without an email. Do you have a valid/verified email address in your GitHub profile? The auth request isn't getting an email from the GitHub info for some reason.

**Comment by pain0486** [comment]
@apai4 That was exactly it. Apparently I have had an unverified email for a very long time. 
Thank You!

**Comment by aswathm78** [comment]
Hi,

I changed the email status to public. But still not working

**Comment by CarlosResendiz** [comment]
@pain0486 Have you fixed it?
