### ISSUE TITLE
Doesn't prompt for installing dependencies when there are import errors

### ISSUE THREAD

**Issue by davidtlee** [stackblitz/core#952]
**Edit: this is no longer a problem for me. I realized that I wasn't specifying the dependencies correctly in the Stackblitz API and so now the dependencies are initializing. I'll leave this issue here though because it might still be useful to first prompt to install dependencies before displaying other errors. (e.g. for someone loading a project from Github)**

In `styles.scss`, I have an import for angular material:
```
@import '@angular/material/prebuilt-themes/deeppurple-amber.css';
```
However, the dependency for angular/material isn't auto-loading, resulting in:

![image](https://user-images.githubusercontent.com/863081/56854822-a8358e80-68f1-11e9-8b0a-ade573466798.png)

Unfortunately, it also doesn't give me the typical prompt for installing dependencies (because of the error). The only way to fix this is to comment out that import so that I can see the dependencies needed, click to install packages, and then uncomment the import to get it to finally work.

Is there a way to make it first prompt for dependency installs before displaying other errors? Otherwise, it's hard to find all the locations that I need to comment out before I can install the packages.

**Comment by purplem1lk** [comment]
Thank you for your patience - This issue will be closed based on the author's edit, but we are noting better error handling messages in our upcoming roadmap -  We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
