### ISSUE TITLE
[FEAT. REQ.] Release Dependency Viewer panel as VSCode extension

### ISSUE THREAD

**Issue by apollolux** [stackblitz/core#953]
Hello! One of the features Stackblitz has that VSCode doesn't that I love is the Node Dependencies panel in the sidebar. I'm sure I'm not the only one who would love to see this available on VSCode as well, presumably running off of normal npm rather than jsdelivr or unpkg or even letting us configure the package manager executable to use, the repository(ies) to search, and the (templated) arguments to pass to the executable.

How reasonable would this be to separate out and release as a VSCode extension?

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)
