### ISSUE TITLE
Repository link doesn't work

### ISSUE THREAD

**Issue by petstu** [stackblitz/core#954]
http://angular2-first-look.azurewebsites.net/
14. Angular: Nested Components

https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/cli/projects/component-nest/?bust=1556721426484

Link doesn't work.

**Comment by willi84** [comment]
If that link or better the moved link to:
https://github.com/johnpapa/angular-first-look-examples/tree/master/_examples/component-nest

should work, John Papa needs to generate it with an angular.json or create a valid one

https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/master/_examples/component-nest


![image](https://user-images.githubusercontent.com/6207308/58876878-9ce33900-86cf-11e9-8d9c-4c3cc81286df.png)

**Comment by purplem1lk** [comment]
> If that link or better the moved link to:
> [https://github.com/johnpapa/angular-first-look-examples/tree/master/_examples/component-nest](https://github.com/johnpapa/angular-first-look-examples/tree/master/_examples/component-nest?rgh-link-date=2019-06-04T11%3A50%3A05Z)
> 
> should work, John Papa needs to generate it with an angular.json or create a valid one
> 
> [stackblitz.com/github/johnpapa/angular-first-look-examples/tree/master/_examples/component-nest](https://stackblitz.com/github/johnpapa/angular-first-look-examples/tree/master/_examples/component-nest)
> 
> ![image](https://user-images.githubusercontent.com/6207308/58876878-9ce33900-86cf-11e9-8d9c-4c3cc81286df.png)

Thank you for your patience - This issue should be resolved with the information above so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
