### ISSUE TITLE
Deploy to Space Button

### ISSUE THREAD

**Issue by Joe-Kang** [stackblitz/core#957]
The text 'Deploy to Space' overflows outside the button when window width is smaller. Not sure if that was intentional or not but does not look very nice.  I noticed the header changes when the width of the window is less than 765px. Consider increasing it 1050px since that is when the text starts to overflow.
Or maybe have a dropdown menu in the header with all the functions. 
![image](https://user-images.githubusercontent.com/32855100/57095891-efe95b00-6ce1-11e9-8c18-442f8d8bb5ad.png)

**Comment by kylecordes** [comment]
**Within the realm of human achievement:**  Deploy code to space with one click.

**Outside the realm of human achievement:**  Get CSS right the first time.

**Comment by EricSimons** [comment]
@Joe-Kang yeah this wasn't intentional- thanks for pointing it out! We'll get a fix in asap 🙏 ❤️
