### ISSUE TITLE
After importing my github repo, not able to push into it

### ISSUE THREAD

**Issue by NavjotSingh007** [stackblitz/core#960]
After I import my angular project from GitHub to stackblitz, If I make any changes in stackblitz, How to push it to my GitHub repo.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or continue the conversation in #1015, as it has more recent activity. Thank you! :)
