### ISSUE TITLE
StackBlitz Memberships

### ISSUE THREAD

**Issue by JaimeStill** [stackblitz/core#961]
Sorry if this is off topic / the wrong venue for this, but I couldn't think of anywhere else to raise the question. Today, I noticed the Memberships feature that was added to StackBlitz. I've been part of the $10 tier on Patreon since Oct. 2018. Would it be preferred to continue donations through Patreon, or to back the project through memberships? Having access to the Astronaut Membership features through my Patreon donation would be awesome, if that's at all possible.

**Comment by EricSimons** [comment]
@JaimeStill yes! We're still in the process of rolling out the new memberships- I apologize we haven't contacted y'all yet. Can you shoot me an email at eric@stackblitz.com & I'll get you hooked up with our astronaut plan?

**Comment by JaimeStill** [comment]
@EricSimons, email sent! No worries at all, I really appreciate the response. Loving how StackBlitz has evolved since I've started using it. Y'all are doing some great work!
