### ISSUE TITLE
Support for Flutter Web

### ISSUE THREAD

**Issue by rodydavis** [stackblitz/core#962]
https://flutter.dev/web

https://github.com/flutter/flutter_web

Can we support creating a new project for Flutter?

**Comment by AppleEducate** [comment]
![IMG_4E830BDFAA59-1](https://user-images.githubusercontent.com/31253215/57391156-ecdfe600-718b-11e9-800b-a8e38c10c311.jpeg)

**Comment by jagdishjadeja** [comment]
I was also looking if we can have this feature

**Comment by rodydavis** [comment]
Any updates?

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by rodydavis** [comment]
Wonderful 😁
