### ISSUE TITLE
stackblitz link has stopped working suddenly 

### ISSUE THREAD

**Issue by sharmaavikas** [stackblitz/core#963]
Dear Team,
I was working on a project which was on stackblitz, but suddenly it stops working, Please resolve this issue asap.. 

This is the Link---

https://stackblitz.com/edit/angular-i7q1vd?file=src%2Fapp%2Fapp-routing.module.ts

Thanks & Regards
Vikas Sharma

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
