### ISSUE TITLE
Cursor Navigation on iOS

### ISSUE THREAD

**Issue by BernhardRode** [stackblitz/core#964]
Hey,

I wanted to try out stackblitz using my new iPad Pro 12.9, attached to a Apple Smartfolio Keyboard.

The cursor navigation on stackblitz does not work at all. So no moving/selecting/... of code via the keyboard. 

I know that this may not be a real high priority thing for you. But I wanted to let you know about this issue.

@d3lm just for you :p

**Comment by BernhardRode** [comment]
https://github.com/ajaxorg/ace/blob/eb2437badf4013893e15cb873057607c09cc95ae/lib/ace/keyboard/textinput_ios.js

Maybe this could help.

**Comment by hadnet** [comment]
Same thing here using a belkin Ultimate Keyboard on my iPad. It's so frustrating and kinda spoils with much of the purpose of an online IDE.

**Comment by BernhardRode** [comment]
iPadOS 13  and new Safari fix the issues afaics  ;)
