### ISSUE TITLE
Angular loadChildren variable

### ISSUE THREAD

**Issue by maktarsis** [stackblitz/core#965]
Hey there!

I caught a strange mistake while implementing lazy loading in Angular.
It seems like a weird behavior when we doing like that

```typescript
const bazLoadChildren = 'app/baz/baz.module#BazModule';

export const routes: Routes = [
  {
    path: '',
    component: HelloComponent
  },
  {
    path: 'baz',
    loadChildren: bazLoadChildren
  }
];
```

As for me, it looks weird because loadChildren is still string literal and we can achieve a positive result in angular application with the same way

I need this approach to make a demo of my [package](https://github.com/maktarsis/routeshub)  and this issue is critical to me

[Link repro](https://stackblitz-routeshub-issue.stackblitz.io/) in stackblitz

**Comment by maktarsis** [comment]
Ok, now I'm not interested in solving this.

**Comment by EricSimons** [comment]
@maktarsis hey! sorry about the delay on this- you'll need to have the string directly on the loadChildren attribute for this to work in SB. Not sure if Angular CLI lets you do this locally either.

**Comment by maktarsis** [comment]
@EricSimons yeah, u r right, thanks

the only thing worth mentioning is that when I created this issue noticed that Angular and Stackblitz do it a little differently.

therefore this is not a problem already
