### ISSUE TITLE
scss imports are causing errors on stackblitz

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [stackblitz/core#966]
Whenever we import an scss file with the filename (including the extension) we do not have any issues in local setup with the Angular CLI. 

```
@import './wathever.scss'
```

However, using this on Stackblitz gives the following error:

`Error: ENOENT: No such file or directory., '/dev/null'`

After changing the import to the following we get ride of the error on stackblitz 

```
@import './wathever'
```

See https://stackblitz.com/edit/angular-import-scss?file=src%2F_test.scss for a reproduction of the issue.

**Comment by vidhya03** [comment]
its occurring for me also any clue

**Comment by vatsalpande** [comment]
Still facing this issue.

**Comment by seanlandsman** [comment]
@tobi-or-not-tobi I encountered this too and found it was actually an incorrect path. Looking at your example the same thing is true - if you change `styles.scss` to have this:

`@import './_test.scss';` 

then it works as expected

**Comment by tobi-or-not-tobi** [comment]
Thanks @seanlandsman for the feedback and solution you provide. I guess I was too used to the partial syntax in SASS, using underscores as a name prefix. The sass compilers i'm used to resolve those partials with or without the prefix. 
I've done a quick test with the standard angular template on stackblitz and it works fine now with this syntax as well. I assume that's because of the change from node-sass to dart-sass in angular 8. 

Closing as this is no longer an issue. Thanks again!

**Comment by dev-sharan** [comment]
@tobi-or-not-tobi 

can you help with this https://stackblitz.com/edit/github-kyd4ob

**Comment by dev-sharan** [comment]
@tobi-or-not-tobi @seanlandsman 
i am facing similar isuue

https://stackblitz.com/edit/angular-ivy-nc1qpr

**Comment by vran848115** [comment]
@tobi-or-not-tobi @seanlandsman 
tried above things , still facing issue.

https://stackblitz.com/github/rlmibwjvq?

**Comment by ramkumarsekar** [comment]
@tobi-or-not-tobi  tried above all step yet to solve. still facing issue.

https://stackblitz.com/edit/angular-cqgi9z?file=src%2Fstyles.css

**Comment by ramkumarsekar** [comment]
@tobi-or-not-tobi Still facing this issue.

https://stackblitz.com/edit/angular-cqgi9z?file=src%2Fstyles.css
