### ISSUE TITLE
can not eval this repo rdkmaster/jigsaw-seed

### ISSUE THREAD

**Issue by rdkmaster** [stackblitz/core#967]
can not eval this repo <https://github.com/rdkmaster/jigsaw-seed>

**Comment by willi84** [comment]
@rdkmaster what is your goal and what you mean with eval?

**Comment by rdkmaster** [comment]
[Jigsaw-seed](https://github.com/rdkmaster/jigsaw-seed) is a tipical angular based project, clone this repo to any PC and run `npm install; npm start`, the angular-cli will compile the repo and `http://localhost:4200` will be available for visiting as soon as the compilation is finished.

I think I should get the same result if I open this repo with stachblitz, that is what I want.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
