### ISSUE TITLE
Stackblitz preview are not working

### ISSUE THREAD

**Issue by DeepakXp** [stackblitz/core#968]
Demo url: https://stackblitz.com/angular/pxxqelnoebey?file=app%2Ftable-http-example.html

Error on Console: 
document not ready yet, trying again in 500 milliseconds...

cdn.carbonads.com/carbon.js?serve=CK7ICKQN&placement=stackblitzcom:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

loader.js:1176 Duplicate definition of module 'vs/basic-languages/typescript/typescript'
s.defineModule @ loader.js:1176

_relay_:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: ServiceWorker script evaluation failed

Chrome ver: Version 74.0.3729.131 (Official Build) (64-bit)

**Comment by purplem1lk** [comment]
Thank you for your patience - This is what I'm seeing from the project link you provided. We are unable to provide assistance without being able to reproduce the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

![Screen Shot 2021-05-13 at 11 27 18 AM](https://user-images.githubusercontent.com/49956513/118148053-30563600-b3de-11eb-9e42-feaef332643b.png)
