### ISSUE TITLE
StackBlitz editor in WKWebView ignores mouse clicks

### ISSUE THREAD

**Issue by ig-robstoffers** [stackblitz/core#969]
If you load a StackBlitz project URL into a MacOS application using WKWebView you are not able to click on text in the code files.  At first I thought it was because of the `user-select: none;` CSS that I saw in the dev tools but I can see that same CSS in the Chrome browser and selecting code text works fine there.

I have attached an XCode project that you should be able to open and run on a Mac which demonstrates the issue.

[WebViewStackBlitz2.zip](https://github.com/stackblitz/core/files/3179585/WebViewStackBlitz2.zip)

Steps to reproduce:
1.) Run attached sample
2.) Try clicking on code in open Typescript file

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without being able to reproduce the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
