### ISSUE TITLE
Stackblitz CLI

### ISSUE THREAD

**Issue by janpio** [stackblitz/core#97]
* `stackblitz upload` to just upload my current project I am in (e.g. Ionic) to Stackblitz and open the URL in the browser
* `stackblitz download xyz` to download the current project into the folder I am in right now. `npm install` to install deps, then use normal process (e.g. `ionic serve`)
* `stackblitz sync` to upload or download, depending on what is necessary

**Comment by EricSimons** [comment]
I love this idea! Adding it to our roadmap :) Would you be down to beta test it once we have first version avail?

**Comment by janpio** [comment]
Sure.

**Comment by buoyantair** [comment]
Wait up! There should also be things like being able to manage the whole workspace too!
Like: 
- common CLI functions 
- implementing git so that users can push to their repositories.. 
- and more?

**Comment by megawubs** [comment]
what's the status on this?

**Comment by seveves** [comment]
I would recommend https://github.com/lukeed/sade
