### ISSUE TITLE
My project not opening in stackblitz

### ISSUE THREAD

**Issue by PavelGorodetchi** [stackblitz/core#971]
my project not opening in stackblitz :
https://stackblitz.com/github/PavelGorodetchi/IVR_Project
![Screenshot_10](https://user-images.githubusercontent.com/42777048/58005828-684e6b00-7a9b-11e9-8cbb-a0ba79036d48.png)

**Comment by willi84** [comment]
@PavelGorodetchi on my chrome it does work, maybe its already fixed? which browser/environment are you using?

![image](https://user-images.githubusercontent.com/6207308/58869876-5dacec00-86bf-11e9-8b6d-353eb3f0e71a.png)
