### ISSUE TITLE
can import react project

### ISSUE THREAD

**Issue by limerence19** [stackblitz/core#972]

**Comment by willi84** [comment]
@limerence19  maybe give a sample?

when I try to import some random react project like:
https://github.com/ahfarmer/calculator
https://stackblitz.com/github/ahfarmer/calculator

I just have to install one more package to make it work
before
![image](https://user-images.githubusercontent.com/6207308/58870606-ce083d00-86c0-11e9-908a-73fe133ec46f.png)

after
![image](https://user-images.githubusercontent.com/6207308/58870649-e5472a80-86c0-11e9-85ae-27b326c0bd69.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
