### ISSUE TITLE
lit-html template dependencies out of date

### ISSUE THREAD

**Issue by justinfagnani** [stackblitz/core#975]
As reported by one of our users: https://github.com/Polymer/lit-html/issues/892

@EricSimons is it possible to share edit rights on a template?

**Comment by EricSimons** [comment]
Hey! Yup, I can assign that template to one of y’all. @justinfagnani should I assign to your account?

**Comment by justinfagnani** [comment]
That'd be awesome. How about /lit-element too?

**Comment by EricSimons** [comment]
Yup np! Just swapped both of those over to ya- lmk if there's anything else I can do to help
