### ISSUE TITLE
Enable lit-html and lit-element templates in SDK

### ISSUE THREAD

**Issue by katejeffreys** [stackblitz/core#976]
Could you please enable the [lit-html](https://stackblitz.com/edit/lit-html) and [lit-element](https://stackblitz.com/edit/lit-element) templates in the SDK? 

Thank you in advance :)

**Comment by EricSimons** [comment]
Hey @katejeffreys! We actually support this using the `polymer` template in the SDK- here's an example of lit-html working with it: https://stackblitz.com/edit/sdk-polymer-lit?file=index.ts

Lmk if that covers your use case okay and/or if I can be of any help!

**Comment by katejeffreys** [comment]
Thanks, it works great!
