### ISSUE TITLE
Static navigation don't work on Vanilla JS projects

### ISSUE THREAD

**Issue by carballosa** [stackblitz/core#977]
Can't navigate between simple html pages using static navigation. 

Check it out here: https://stackblitz.com/edit/issue-static-navigation-jc

**Comment by Snickdx** [comment]
Bumping this issue, was about to make a duplicate. Hope support for plain vanilla websites come soon as I'm planning to use stackblitz for a html course.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without being able to reproduce the issue you are seeing and will be closing this accordingly. It's possible that through previous code changes, this issue has been fixed. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)

**Comment by Snickdx** [comment]
Still can't get page navigation to work https://stackblitz.com/edit/js-aaup48?file=index.js also the removing index.js breaks the workspace even though it is not linked to any of the HTML files

**Comment by lsrugo770** [comment]
I am having the same issue in this project https://stackblitz.com/edit/berel?file=index.html
When you click "Log Out" it should navigate to the login.html page, but it stays on index.html, even though the address bar does update.
![Screen Shot 2021-06-22 at 9 45 55 PM](https://user-images.githubusercontent.com/41137165/123027371-58ed2a80-d3a3-11eb-8582-1dd562aab983.png)

https://user-images.githubusercontent.com/41137165/123027560-a6699780-d3a3-11eb-9663-dc04acac8057.mov

@purplem1lk Can you please look into this?

**Comment by lsrugo770** [comment]
> Still can't get page navigation to work https://stackblitz.com/edit/js-aaup48?file=index.js also the removing index.js breaks the workspace even though it is not linked to any of the HTML files

It seems like index.js is related to the JS bundler, but I don't see a way to configure it or turn it off. If you create a "web platform" project like this one https://stackblitz.com/edit/web-platform it does not use the bundler.
Is there a way to turn the bundler off in an existing project? @purplem1lk @EricSimons
