### ISSUE TITLE
Angular.Json prefix issue on stackblitz

### ISSUE THREAD

**Issue by HarshGajjar51** [stackblitz/core#978]
I have updated angular.json file and updated prefix to "ctp"
But, when I create new component it still considers the prefix as default "app"

![Screenshot_1](https://user-images.githubusercontent.com/51022701/58369186-7d505180-7f14-11e9-8719-a2774faf1891.png)
![Screenshot_2](https://user-images.githubusercontent.com/51022701/58369187-7d505180-7f14-11e9-9ae9-4aa407032916.png)

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without being able to reproduce the issue you are seeing and will be closing this accordingly. It's possible that through previous code changes, this issue has been fixed. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
