### ISSUE TITLE
Why new projects are created automatically everyday

### ISSUE THREAD

**Issue by manavpandya** [stackblitz/core#979]
For the last few days, I have observed that when I open the stalkblitz and go to profile.

Every day, 4 new projects are created automatically, what kind of issue is this or my account is accessed by someone else ???

I have also logged in using GitHub, provide me some workaround if someone has faced such issue.

**Comment by purplem1lk** [comment]
Thank you for your patience - Whenever you start a new project, it's automatically saved as a project in your account so you can access it later. We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with working project links and screenshots of the dashboard with the new projects you're seeing. Thank you! :)
