### ISSUE TITLE
Date in console displayed not correctly

### ISSUE THREAD

**Issue by vysheradugi4** [stackblitz/core#981]
When I tryed to show date in console like this:   
`console.log(new Date(2019, 0, 1));`
   
I got `2018-12-31T21:00:00.000Z`   
But expected `2019-01-01T00:00:00.000Z`

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
