### ISSUE TITLE
Angular generator does not work; at least when using a Mac

### ISSUE THREAD

**Issue by seaserpentdesign** [stackblitz/core#983]
Hi:

I have been doing the tutorial in https://angular.io/start, and it says to "Right click on the app folder and use the Angular Generator to generate a new component named product-alerts."

Since I use a Mac, I've been control-clicking this Angular generator, since control-clicking is the Mac version of right-clicking.

Nothing happens. A new component is not created.

Is there some keyboard command I should be using?

Please let me know. Thanks very much.

**Comment by emulicus** [comment]
For me when right-clicking on the folder it just opens regular right-click menu, not the stackblitz menu, so I don't even see the angular generator.

**Comment by aleixsuau** [comment]
Same problem here, I can't create a component, nothing happens but an error in the console:
![image](https://user-images.githubusercontent.com/25689432/75957793-186e5280-5ebb-11ea-9893-2f39d0d2a443.png)

**Comment by aleixsuau** [comment]
I found what was happening, it seems that although the folder was there visually, it was not created already in the system. I saved, reloaded the page and then I was able to create the component.

**Comment by kc0tlh** [comment]
This issue has been resolved.
