### ISSUE TITLE
Can't import folder/files into stackblitz editor (Angular)

### ISSUE THREAD

**Issue by seancosgrove** [stackblitz/core#984]
Working on a Mac, can't "drag and drop" any folders or files into the stackblitz editor

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without being able to reproduce your issue and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a screencast of what you are seeing. Thank you! :)
