### ISSUE TITLE
Code Reverted back to 19 days old code.

### ISSUE THREAD

**Issue by nasiruddin-saiyed** [stackblitz/core#985]
Hey guys i was creating demo in reactjs https://stackblitz.com/edit/react-fnnn17 and i edited on Saturday, 1st June and Yesterday  3rd June but all of my code is reverted back to old 19 days code. At first i thought yesterday that i have not logged in on Saturday then worked full day on that repo and now today ... it's same as old 19 days code  ... i'm very disappointed and angry please its my 2 full days of work has just gone ...

**Comment by nasiruddin-saiyed** [comment]
@EricSimons  can you please look into it.

**Comment by nasiruddin-saiyed** [comment]
cc @erikwco

**Comment by purplem1lk** [comment]
Thank you for your patience - I'm sorry to hear that you lost progress on this project. Unfortunately, we are unable to provide assistance without being able to reproduce the issue you are seeing and will be closing this accordingly. This seems like a unique issue and we'll note this in future code changes as we are releasing more features to improve the developer experience. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of what you are seeing. Thank you! :)
