### ISSUE TITLE
Can't install latest version luxon properly

### ISSUE THREAD

**Issue by fenixsolorzano** [stackblitz/core#986]
I was trying to use [luxon](https://www.npmjs.com/package/luxon) latest version (~1.16.0) in combination of `@types/luxon` but displays: `Error in /~/index.ts (4:28)`

**Comment by mhverbakel** [comment]
The issue occurs between release `1.11.4` and `1.12.0`, I think that https://github.com/moment/luxon/commit/a7388b99b8c09f4df052ecbf970887bfbea69b64 is the most probable cause.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without further information about your specific project will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
