### ISSUE TITLE
I make private repo to public in github but that shows some error

### ISSUE THREAD

**Issue by GayathriRamasamy** [stackblitz/core#987]

**Comment by GayathriRamasamy** [comment]
The dependencies for this project couldn't be resolved.
This usually means that a dependency in your package.json is incorrect.
If you think this is a bug, please file an issue in our repo!

**Comment by beeman** [comment]
@GayathriRamasamy could you please share the error message and the link to the blitz you have the issue with?

**Comment by sulco** [comment]
Without the repro link I need to close this one (please reopen if this is still relevant)
