### ISSUE TITLE
Make projects sortable

### ISSUE THREAD

**Issue by BenRacicot** [stackblitz/core#991]
I hope it's ok to leave a feature request here but I believe users truly need a way to sort their projects order. 

This way we can publicly display our projects the way we desire instead of newest blitz descending.

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by BenRacicot** [comment]
Hi @purplem1lk ! Hope you are well since this issue was created.
Is this feature being developed now that 2021 comes to an end?
