### ISSUE TITLE
Do you support AngularJS unit testing with karma+jasmine on stackblitz

### ISSUE THREAD

**Issue by jforjava1981** [stackblitz/core#993]

**Comment by purplem1lk** [comment]
Thank you for your patience - This feature is being considered for our upcoming roadmap - We’ll make an announcement in the near future. If this issue persists, feel free to tag me or ask to reopen this issue. Thank you! :)

**Comment by momofarm** [comment]
I've found the test feature in angularjs is missing in the template created / given by  stackblitz. 

No matter you'd like or not to add this feature in  near future, could you please at least sent it back so when we download the project we written in stackblitz, we can do some test without modify the config files. Which is quite a work.
