### ISSUE TITLE
Error opening this repository. Could not open using the url

### ISSUE THREAD

**Issue by salmankazmi** [stackblitz/core#994]
URL: [https://stackblitz.com/github/Fresiamay17/google-api-integration-app](url)

The app is not able to open this repository. This should open as it is a standard Angular app and the repository is open.

**Comment by purplem1lk** [comment]
Thank you for your patience - We are unable to provide assistance without being able to see the GitHub repository or to reproduce the issue you are seeing and will be closing this accordingly. If your issue persists, feel free to tag me or ask to reopen this issue with a working project link, description, and screenshots of the error. Thank you! :)
