### ISSUE TITLE
lots of issues

### ISSUE THREAD

**Issue by mttlyash** [stackblitz/core#997]
![Screenshot (7)](https://user-images.githubusercontent.com/50010542/59847554-72a4a300-9380-11e9-8c1a-ce4009d0be43.png)
1.Kindly solve your app issues there are lots of issues.
2.While using the stackblitz, I just cliked on the fork and it was continuously rotating like infinite loop.
3.While updating the dependencies it shows error download core.js file which is already installed and the app stop working.
4.The notification shade while updating dependencies the popup comes over the screen in the blue filed saying downloading dependencies but after installing them the notification shade never go off.

Last thing i want to say if someone codes here why don't the code saved here

**Comment by purplem1lk** [comment]
Thank you for your patience - We are launching new core technology into beta this month that should resolve this issue so this will be closed accordingly. If this issue persists, feel free to tag me or ask to reopen this issue with screenshots of the error. Thank you! :)
